.TH "_bdf_list_t_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bdf_list_t_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBfield\fP"
.br
.ti -1c
.RI "unsigned long \fBsize\fP"
.br
.ti -1c
.RI "unsigned long \fBused\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 398 of file bdflib\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
