.TH "_bdf_parse_t_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bdf_parse_t_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.ti -1c
.RI "unsigned long \fBcnt\fP"
.br
.ti -1c
.RI "unsigned long \fBrow\fP"
.br
.ti -1c
.RI "short \fBminlb\fP"
.br
.ti -1c
.RI "short \fBmaxlb\fP"
.br
.ti -1c
.RI "short \fBmaxrb\fP"
.br
.ti -1c
.RI "short \fBmaxas\fP"
.br
.ti -1c
.RI "short \fBmaxds\fP"
.br
.ti -1c
.RI "short \fBrbearing\fP"
.br
.ti -1c
.RI "char * \fBglyph_name\fP"
.br
.ti -1c
.RI "long \fBglyph_enc\fP"
.br
.ti -1c
.RI "\fBbdf_font_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBbdf_options_t\fP * \fBopts\fP"
.br
.ti -1c
.RI "unsigned long \fBhave\fP [34816]"
.br
.ti -1c
.RI "\fB_bdf_list_t\fP \fBlist\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 410 of file bdflib\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
