.TH "libmscore Directory Reference" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccidental\&.h\fP"
.br
.ti -1c
.RI "file \fBbox\&.h\fP"
.br
.ti -1c
.RI "file \fBchord\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchord\&.h\fP"
.br
.ti -1c
.RI "file \fBclef\&.cpp\fP"
.br
.ti -1c
.RI "file \fBclef\&.h\fP"
.br
.ti -1c
.RI "file \fBcmd\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelement\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmeasure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmeasure\&.h\fP"
.br
.ti -1c
.RI "file \fBmeasurebase\&.h\fP"
.br
.ti -1c
.RI "file \fBnote\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnote\&.h\fP"
.br
.ti -1c
.RI "file \fBrendermidi\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscore\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscore\&.h\fP"
.br
.ti -1c
.RI "file \fBselect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstaff\&.h\fP"
.br
.ti -1c
.RI "file \fBsystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.ti -1c
.RI "file \fBundo\&.cpp\fP"
.br
.ti -1c
.RI "file \fBundo\&.h\fP"
.br
.ti -1c
.RI "file \fBvelo\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvelo\&.h\fP"
.br
.in -1c
