.TH "thirdparty Directory Reference" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thirdparty Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBfreetype\fP"
.br
.ti -1c
.RI "directory \fBopenssl\fP"
.br
.ti -1c
.RI "directory \fBportmidi\fP"
.br
.ti -1c
.RI "directory \fBsingleapp\fP"
.br
.in -1c
