.TH "mscore Directory Reference" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mscore Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmusicxml\&.h\fP"
.br
.ti -1c
.RI "file \fBselectdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBselectnotedialog\&.cpp\fP"
.br
.in -1c
