.TH "build.release Directory Reference" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build.release Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaudiofile\fP"
.br
.ti -1c
.RI "directory \fBawl\fP"
.br
.ti -1c
.RI "directory \fBbww2mxml\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBlibmscore\fP"
.br
.ti -1c
.RI "directory \fBmanual\fP"
.br
.ti -1c
.RI "directory \fBmidi\fP"
.br
.ti -1c
.RI "directory \fBmstyle\fP"
.br
.ti -1c
.RI "directory \fBomr\fP"
.br
.ti -1c
.RI "directory \fBsynthesizer\fP"
.br
.ti -1c
.RI "directory \fBthirdparty\fP"
.br
.in -1c
