.TH "_ossl_old_des_ks_struct" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ossl_old_des_ks_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   _ossl_old_des_cblock \fB_\fP"
.br
.ti -1c
.RI "   DES_LONG \fBpad\fP [2]"
.br
.ti -1c
.RI "} \fBks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file des_old\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
