.TH "_type3_font_info" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_type3_font_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGfxFont\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBPDFDoc\fP * \fBdoc\fP"
.br
.ti -1c
.RI "\fBCairoFontEngine\fP * \fBfontEngine\fP"
.br
.ti -1c
.RI "GBool \fBprinting\fP"
.br
.ti -1c
.RI "\fBXRef\fP * \fBxref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 611 of file CairoFontEngine\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
