.TH "ActualText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActualText
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActualText\fP (\fBTextPage\fP *out)"
.br
.ti -1c
.RI "void \fBaddChar\fP (\fBGfxState\fP *state, double x, double y, double dx, double dy, CharCode c, int nBytes, Unicode *u, int uLen)"
.br
.ti -1c
.RI "void \fBbegin\fP (\fBGfxState\fP *state, \fBGooString\fP *text)"
.br
.ti -1c
.RI "void \fBend\fP (\fBGfxState\fP *state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 699 of file TextOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
