.TH "Addsynth" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Addsynth
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "int \fBsave\fP (const char *sdir)"
.br
.ti -1c
.RI "int \fBload\fP (const char *sdir)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fB_filename\fP [64]"
.br
.ti -1c
.RI "char \fB_stopname\fP [32]"
.br
.ti -1c
.RI "char \fB_copyrite\fP [56]"
.br
.ti -1c
.RI "char \fB_mnemonic\fP [8]"
.br
.ti -1c
.RI "char \fB_comments\fP [56]"
.br
.ti -1c
.RI "char \fB_reserved\fP [8]"
.br
.ti -1c
.RI "int32_t \fB_n0\fP"
.br
.ti -1c
.RI "int32_t \fB_n1\fP"
.br
.ti -1c
.RI "int32_t \fB_fn\fP"
.br
.ti -1c
.RI "int32_t \fB_fd\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_vol\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_off\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_ran\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_ins\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_att\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_atd\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_dct\fP"
.br
.ti -1c
.RI "\fBN_func\fP \fB_n_dcd\fP"
.br
.ti -1c
.RI "\fBHN_func\fP \fB_h_lev\fP"
.br
.ti -1c
.RI "\fBHN_func\fP \fB_h_ran\fP"
.br
.ti -1c
.RI "\fBHN_func\fP \fB_h_att\fP"
.br
.ti -1c
.RI "\fBHN_func\fP \fB_h_atp\fP"
.br
.ti -1c
.RI "char \fB_pan\fP"
.br
.ti -1c
.RI "int32_t \fB_del\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file addsynth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
