.TH "AF_AxisHintsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_AxisHintsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBnum_segments\fP"
.br
.ti -1c
.RI "FT_Int \fBmax_segments\fP"
.br
.ti -1c
.RI "\fBAF_Segment\fP \fBsegments\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_edges\fP"
.br
.ti -1c
.RI "FT_Int \fBmax_edges\fP"
.br
.ti -1c
.RI "\fBAF_Edge\fP \fBedges\fP"
.br
.ti -1c
.RI "AF_Direction \fBmajor_dir\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBAF_SegmentRec\fP \fBsegments\fP [AF_SEGMENTS_EMBEDDED]"
.br
.ti -1c
.RI "   \fBAF_EdgeRec\fP \fBedges\fP [AF_EDGES_EMBEDDED]"
.br
.ti -1c
.RI "} \fBembedded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 303 of file afhints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
