.TH "AF_CJKMetricsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_CJKMetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAF_StyleMetricsRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_UInt \fBunits_per_em\fP"
.br
.ti -1c
.RI "\fBAF_CJKAxisRec\fP \fBaxis\fP [AF_DIMENSION_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file afcjk\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
