.TH "AF_EdgeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_EdgeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Short \fBfpos\fP"
.br
.ti -1c
.RI "FT_Pos \fBopos\fP"
.br
.ti -1c
.RI "FT_Pos \fBpos\fP"
.br
.ti -1c
.RI "FT_Byte \fBflags\fP"
.br
.ti -1c
.RI "FT_Char \fBdir\fP"
.br
.ti -1c
.RI "FT_Fixed \fBscale\fP"
.br
.ti -1c
.RI "AF_Width \fBblue_edge\fP"
.br
.ti -1c
.RI "\fBAF_Edge\fP \fBlink\fP"
.br
.ti -1c
.RI "\fBAF_Edge\fP \fBserif\fP"
.br
.ti -1c
.RI "FT_Short \fBnum_linked\fP"
.br
.ti -1c
.RI "FT_Int \fBscore\fP"
.br
.ti -1c
.RI "\fBAF_Segment\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBAF_Segment\fP \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 279 of file afhints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
