.TH "AF_FaceGlobalsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_FaceGlobalsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "FT_Long \fBglyph_count\fP"
.br
.ti -1c
.RI "FT_UShort * \fBglyph_styles\fP"
.br
.ti -1c
.RI "FT_UInt \fBincrease_x_height\fP"
.br
.ti -1c
.RI "\fBAF_StyleMetrics\fP \fBmetrics\fP [AF_STYLE_MAX]"
.br
.ti -1c
.RI "AF_Module \fBmodule\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 105 of file afglobal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
