.TH "AF_GlyphHintsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_GlyphHintsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Fixed \fBx_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBx_delta\fP"
.br
.ti -1c
.RI "FT_Fixed \fBy_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBy_delta\fP"
.br
.ti -1c
.RI "FT_Int \fBmax_points\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_points\fP"
.br
.ti -1c
.RI "\fBAF_Point\fP \fBpoints\fP"
.br
.ti -1c
.RI "FT_Int \fBmax_contours\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_contours\fP"
.br
.ti -1c
.RI "\fBAF_Point\fP * \fBcontours\fP"
.br
.ti -1c
.RI "\fBAF_AxisHintsRec\fP \fBaxis\fP [AF_DIMENSION_MAX]"
.br
.ti -1c
.RI "FT_UInt32 \fBscaler_flags\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBother_flags\fP"
.br
.ti -1c
.RI "\fBAF_StyleMetrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_Pos \fBxmin_delta\fP"
.br
.ti -1c
.RI "FT_Pos \fBxmax_delta\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBAF_Point\fP \fBcontours\fP [AF_CONTOURS_EMBEDDED]"
.br
.ti -1c
.RI "   \fBAF_PointRec\fP \fBpoints\fP [AF_POINTS_EMBEDDED]"
.br
.ti -1c
.RI "} \fBembedded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 332 of file afhints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
