.TH "AF_LatinAxisRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_LatinAxisRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBscale\fP"
.br
.ti -1c
.RI "FT_Pos \fBdelta\fP"
.br
.ti -1c
.RI "FT_UInt \fBwidth_count\fP"
.br
.ti -1c
.RI "AF_WidthRec \fBwidths\fP [AF_LATIN_MAX_WIDTHS]"
.br
.ti -1c
.RI "FT_Pos \fBedge_distance_threshold\fP"
.br
.ti -1c
.RI "FT_Pos \fBstandard_width\fP"
.br
.ti -1c
.RI "FT_Bool \fBextra_light\fP"
.br
.ti -1c
.RI "FT_UInt \fBblue_count\fP"
.br
.ti -1c
.RI "\fBAF_LatinBlueRec\fP \fBblues\fP [AF_BLUE_STRINGSET_MAX]"
.br
.ti -1c
.RI "FT_Fixed \fBorg_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBorg_delta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file aflatin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
