.TH "AF_LoaderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_LoaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBAF_FaceGlobals\fP \fBglobals\fP"
.br
.ti -1c
.RI "\fBAF_GlyphHints\fP \fBhints\fP"
.br
.ti -1c
.RI "\fBAF_StyleMetrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_Bool \fBtransformed\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBtrans_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBtrans_delta\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp1\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file afloader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
