.TH "AF_PointRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_PointRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBflags\fP"
.br
.ti -1c
.RI "FT_Char \fBin_dir\fP"
.br
.ti -1c
.RI "FT_Char \fBout_dir\fP"
.br
.ti -1c
.RI "FT_Pos \fBox\fP"
.br
.ti -1c
.RI "FT_Pos \fBoy\fP"
.br
.ti -1c
.RI "FT_Short \fBfx\fP"
.br
.ti -1c
.RI "FT_Short \fBfy\fP"
.br
.ti -1c
.RI "FT_Pos \fBx\fP"
.br
.ti -1c
.RI "FT_Pos \fBy\fP"
.br
.ti -1c
.RI "FT_Pos \fBu\fP"
.br
.ti -1c
.RI "FT_Pos \fBv\fP"
.br
.ti -1c
.RI "\fBAF_Point\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBAF_Point\fP \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file afhints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
