.TH "AF_StyleClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_StyleClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_Style \fBstyle\fP"
.br
.ti -1c
.RI "AF_WritingSystem \fBwriting_system\fP"
.br
.ti -1c
.RI "AF_Script \fBscript\fP"
.br
.ti -1c
.RI "AF_Blue_Stringset \fBblue_stringset\fP"
.br
.ti -1c
.RI "AF_Coverage \fBcoverage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 439 of file aftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
