.TH "AF_StyleMetricsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_StyleMetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAF_StyleClass\fP \fBstyle_class\fP"
.br
.ti -1c
.RI "\fBAF_ScalerRec\fP \fBscaler\fP"
.br
.ti -1c
.RI "FT_Bool \fBdigits_have_same_width\fP"
.br
.ti -1c
.RI "\fBAF_FaceGlobals\fP \fBglobals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 467 of file aftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
