.TH "AF_WritingSystemClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_WritingSystemClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_WritingSystem \fBwriting_system\fP"
.br
.ti -1c
.RI "FT_Offset \fBstyle_metrics_size\fP"
.br
.ti -1c
.RI "AF_WritingSystem_InitMetricsFunc \fBstyle_metrics_init\fP"
.br
.ti -1c
.RI "AF_WritingSystem_ScaleMetricsFunc \fBstyle_metrics_scale\fP"
.br
.ti -1c
.RI "AF_WritingSystem_DoneMetricsFunc \fBstyle_metrics_done\fP"
.br
.ti -1c
.RI "AF_WritingSystem_InitHintsFunc \fBstyle_hints_init\fP"
.br
.ti -1c
.RI "AF_WritingSystem_ApplyHintsFunc \fBstyle_hints_apply\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 271 of file aftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
