.TH "AF_WarperRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_WarperRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Pos \fBx1\fP"
.br
.ti -1c
.RI "FT_Pos \fBx2\fP"
.br
.ti -1c
.RI "FT_Pos \fBt1\fP"
.br
.ti -1c
.RI "FT_Pos \fBt2\fP"
.br
.ti -1c
.RI "FT_Pos \fBx1min\fP"
.br
.ti -1c
.RI "FT_Pos \fBx1max\fP"
.br
.ti -1c
.RI "FT_Pos \fBx2min\fP"
.br
.ti -1c
.RI "FT_Pos \fBx2max\fP"
.br
.ti -1c
.RI "FT_Pos \fBw0\fP"
.br
.ti -1c
.RI "FT_Pos \fBwmin\fP"
.br
.ti -1c
.RI "FT_Pos \fBwmax\fP"
.br
.ti -1c
.RI "FT_Fixed \fBbest_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBbest_delta\fP"
.br
.ti -1c
.RI "AF_WarpScore \fBbest_score\fP"
.br
.ti -1c
.RI "AF_WarpScore \fBbest_distort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file afwarp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
