.TH "AFM_StreamRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFM_StreamRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte * \fBcursor\fP"
.br
.ti -1c
.RI "FT_Byte * \fBbase\fP"
.br
.ti -1c
.RI "FT_Byte * \fBlimit\fP"
.br
.ti -1c
.RI "FT_Int \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file afmparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
