.TH "AFM_ParserRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFM_ParserRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBAFM_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "\fBAFM_FontInfo\fP \fBFontInfo\fP"
.br
.ti -1c
.RI "FT_Int(* \fBget_index\fP )(const char *name, FT_Offset len, void *user_data)"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 753 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
