.TH "AFM_FontInfoRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFM_FontInfoRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Bool \fBIsCIDFont\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBFontBBox\fP"
.br
.ti -1c
.RI "FT_Fixed \fBAscender\fP"
.br
.ti -1c
.RI "FT_Fixed \fBDescender\fP"
.br
.ti -1c
.RI "\fBAFM_TrackKern\fP \fBTrackKerns\fP"
.br
.ti -1c
.RI "FT_UInt \fBNumTrackKern\fP"
.br
.ti -1c
.RI "\fBAFM_KernPair\fP \fBKernPairs\fP"
.br
.ti -1c
.RI "FT_UInt \fBNumKernPair\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 167 of file t1types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
