.TH "AgentParameters" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AgentParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBpostMarginFactor\fP"
.br
.ti -1c
.RI "double \fBpreMarginFactor\fP"
.br
.ti -1c
.RI "double \fBmaxChange\fP"
.br
.ti -1c
.RI "double \fBexpiryTime\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const double \fBDEFAULT_POST_MARGIN_FACTOR\fP = 0\&.3"
.br
.ti -1c
.RI "static const double \fBDEFAULT_PRE_MARGIN_FACTOR\fP = 0\&.15"
.br
.ti -1c
.RI "static const double \fBDEFAULT_MAX_CHANGE\fP = 0\&.2"
.br
.ti -1c
.RI "static const double \fBDEFAULT_EXPIRY_TIME\fP = 10\&.0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Agent\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double AgentParameters::expiryTime"
The default value of expiryTime, which is the time (in seconds) after which an \fBAgent\fP that has no \fBEvent\fP matching its beat predictions will be destroyed\&. 
.PP
Definition at line 61 of file Agent\&.h\&.
.SS "double AgentParameters::maxChange"
The maximum allowed deviation from the initial tempo, expressed as a fraction of the initial beat period\&. 
.PP
Definition at line 55 of file Agent\&.h\&.
.SS "double AgentParameters::postMarginFactor"
The maximum amount by which a beat can be later than the predicted beat time, expressed as a fraction of the beat period\&. 
.PP
Definition at line 44 of file Agent\&.h\&.
.SS "double AgentParameters::preMarginFactor"
The maximum amount by which a beat can be earlier than the predicted beat time, expressed as a fraction of the beat period\&. 
.PP
Definition at line 50 of file Agent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
