.TH "Animations" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animations
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimations\fP (QObject *)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~Animations\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "void \fBregisterWidget\fP (QWidget *widget) const"
.br
.RI "register animations corresponding to given widget, depending on its type\&. "
.ti -1c
.RI "void \fBunregisterWidget\fP (QWidget *widget) const"
.br
.ti -1c
.RI "\fBWidgetStateEngine\fP & \fBwidgetEnabilityEngine\fP (void) const"
.br
.RI "enability engine "
.ti -1c
.RI "\fBWidgetStateEngine\fP & \fBwidgetStateEngine\fP (void) const"
.br
.RI "abstractButton engine "
.ti -1c
.RI "\fBWidgetStateEngine\fP & \fBcomboBoxEngine\fP (void) const"
.br
.RI "editable combobox arrow hover engine "
.ti -1c
.RI "\fBWidgetStateEngine\fP & \fBtoolButtonEngine\fP (void) const"
.br
.RI "Tool buttons arrow hover engine\&. "
.ti -1c
.RI "\fBWidgetStateEngine\fP & \fBlineEditEngine\fP (void) const"
.br
.RI "lineEdit engine "
.ti -1c
.RI "\fBSplitterEngine\fP & \fBsplitterEngine\fP (void) const"
.br
.RI "splitter engine "
.ti -1c
.RI "\fBDockSeparatorEngine\fP & \fBdockSeparatorEngine\fP (void) const"
.br
.RI "dock separators engine "
.ti -1c
.RI "\fBHeaderViewEngine\fP & \fBheaderViewEngine\fP (void) const"
.br
.RI "header view engine "
.ti -1c
.RI "\fBProgressBarEngine\fP & \fBprogressBarEngine\fP (void) const"
.br
.RI "progressbar engine "
.ti -1c
.RI "\fBMenuBarBaseEngine\fP & \fBmenuBarEngine\fP (void) const"
.br
.RI "menubar engine "
.ti -1c
.RI "\fBMenuBaseEngine\fP & \fBmenuEngine\fP (void) const"
.br
.RI "menu engine "
.ti -1c
.RI "\fBScrollBarEngine\fP & \fBscrollBarEngine\fP (void) const"
.br
.RI "scrollbar engine "
.ti -1c
.RI "\fBSliderEngine\fP & \fBsliderEngine\fP (void) const"
.br
.RI "slider engine "
.ti -1c
.RI "\fBSpinBoxEngine\fP & \fBspinBoxEngine\fP (void) const"
.br
.RI "spinbox engine "
.ti -1c
.RI "\fBTabBarEngine\fP & \fBtabBarEngine\fP (void) const"
.br
.RI "tabbar "
.ti -1c
.RI "\fBToolBarEngine\fP & \fBtoolBarEngine\fP (void) const"
.br
.RI "toolbar "
.ti -1c
.RI "\fBToolBoxEngine\fP & \fBtoolBoxEngine\fP (void) const"
.br
.RI "toolbox "
.ti -1c
.RI "\fBMdiWindowEngine\fP & \fBmdiWindowEngine\fP (void) const"
.br
.RI "mdi windows "
.ti -1c
.RI "void \fBsetupEngines\fP (void)"
.br
.RI "setup engines "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBunregisterEngine\fP (QObject *)"
.br
.RI "enregister engine "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file animations\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Animations::unregisterWidget (QWidget * widget) const"
unregister all animations associated to a widget 
.PP
Definition at line 337 of file animations\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
