.TH "Animation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPropertyAnimation\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef QPointer< \fBAnimation\fP > \fBPointer\fP"
.br
.RI "TimeLine shared pointer\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimation\fP (int duration, QObject *parent)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~Animation\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "bool \fBisRunning\fP (void) const"
.br
.RI "true if running "
.ti -1c
.RI "void \fBrestart\fP (void)"
.br
.RI "restart "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file animation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
