.TH "AnimationData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnimationData
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.PP
Inherited by \fBDockSeparatorData\fP, \fBGenericData\fP, \fBHeaderViewData\fP, \fBMdiWindowData\fP, \fBMenuBarDataV1\fP, \fBMenuBarDataV2\fP, \fBSpinBoxData\fP, \fBTabBarData\fP, and \fBToolBarData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationData\fP (QObject *parent, QWidget *target)"
.br
.RI "constructor "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int)=0"
.br
.ti -1c
.RI "virtual bool \fBenabled\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetEnabled\fP (bool value)"
.br
.ti -1c
.RI "const QPointer< QWidget > & \fBtarget\fP (void) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static qreal \fBOpacityInvalid\fP = \-1"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetupAnimation\fP (const \fBAnimation::Pointer\fP &animation, const QByteArray &property)"
.br
.RI "setup animation "
.ti -1c
.RI "virtual void \fBsetDirty\fP () const"
.br
.RI "trigger target update "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file animationdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
