.TH "AnnotRichMedia" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnot\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivation\fP"
.br
.ti -1c
.RI "class \fBAsset\fP"
.br
.ti -1c
.RI "class \fBConfiguration\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBDeactivation\fP"
.br
.ti -1c
.RI "class \fBInstance\fP"
.br
.ti -1c
.RI "class \fBParams\fP"
.br
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotRichMedia\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotRichMedia\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBContent\fP * \fBgetContent\fP () const"
.br
.ti -1c
.RI "\fBSettings\fP * \fBgetSettings\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1417 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
