.TH "Annots" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Annots
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnots\fP (\fBPDFDoc\fP *docA, int page, \fBObject\fP *annotsObj)"
.br
.ti -1c
.RI "int \fBgetNumAnnots\fP ()"
.br
.ti -1c
.RI "\fBAnnot\fP * \fBgetAnnot\fP (int i)"
.br
.ti -1c
.RI "void \fBappendAnnot\fP (\fBAnnot\fP *annot)"
.br
.ti -1c
.RI "GBool \fBremoveAnnot\fP (\fBAnnot\fP *annot)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1585 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
