.TH "AnnotRichMedia::Content" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia::Content
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContent\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "int \fBgetConfigurationsCount\fP () const"
.br
.ti -1c
.RI "\fBConfiguration\fP * \fBgetConfiguration\fP (int index) const"
.br
.ti -1c
.RI "int \fBgetAssetsCount\fP () const"
.br
.ti -1c
.RI "\fBAsset\fP * \fBgetAsset\fP (int index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1494 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
