.TH "AnnotColor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotColor
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotColorSpace\fP { \fBcolorTransparent\fP = 0, \fBcolorGray\fP = 1, \fBcolorRGB\fP = 3, \fBcolorCMYK\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotColor\fP (double gray)"
.br
.ti -1c
.RI "\fBAnnotColor\fP (double r, double g, double b)"
.br
.ti -1c
.RI "\fBAnnotColor\fP (double c, double m, double y, double k)"
.br
.ti -1c
.RI "\fBAnnotColor\fP (\fBArray\fP *array, int adjust=0)"
.br
.ti -1c
.RI "void \fBadjustColor\fP (int adjust)"
.br
.ti -1c
.RI "AnnotColorSpace \fBgetSpace\fP () const"
.br
.ti -1c
.RI "const double * \fBgetValues\fP () const"
.br
.ti -1c
.RI "void \fBwriteToObject\fP (\fBXRef\fP *xref, \fBObject\fP *dest) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 306 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
