.TH "AnnotAppearanceCharacs" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotAppearanceCharacs
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotAppearanceCharacsTextPos\fP { \fBcaptionNoIcon\fP, \fBcaptionNoCaption\fP, \fBcaptionBelow\fP, \fBcaptionAbove\fP, \fBcaptionRight\fP, \fBcaptionLeft\fP, \fBcaptionOverlaid\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotAppearanceCharacs\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "int \fBgetRotation\fP ()"
.br
.ti -1c
.RI "\fBAnnotColor\fP * \fBgetBorderColor\fP ()"
.br
.ti -1c
.RI "\fBAnnotColor\fP * \fBgetBackColor\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetNormalCaption\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetRolloverCaption\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetAlternateCaption\fP ()"
.br
.ti -1c
.RI "\fBAnnotIconFit\fP * \fBgetIconFit\fP ()"
.br
.ti -1c
.RI "AnnotAppearanceCharacsTextPos \fBgetPosition\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBrotation\fP"
.br
.ti -1c
.RI "\fBAnnotColor\fP * \fBborderColor\fP"
.br
.ti -1c
.RI "\fBAnnotColor\fP * \fBbackColor\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBnormalCaption\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBrolloverCaption\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBalternateCaption\fP"
.br
.ti -1c
.RI "\fBAnnotIconFit\fP * \fBiconFit\fP"
.br
.ti -1c
.RI "AnnotAppearanceCharacsTextPos \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 416 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
