.TH "AnnotRichMedia::Settings" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia::Settings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettings\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "\fBActivation\fP * \fBgetActivation\fP () const"
.br
.ti -1c
.RI "\fBDeactivation\fP * \fBgetDeactivation\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1548 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
