.TH "AnnotRichMedia::Activation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia::Activation
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCondition\fP { \fBconditionPageOpened\fP, \fBconditionPageVisible\fP, \fBconditionUserAction\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivation\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "Condition \fBgetCondition\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1514 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
