.TH "AnnotAppearanceBBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotAppearanceBBox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotAppearanceBBox\fP (\fBPDFRectangle\fP *init)"
.br
.ti -1c
.RI "void \fBsetBorderWidth\fP (double w)"
.br
.ti -1c
.RI "void \fBextendTo\fP (double x, double y)"
.br
.ti -1c
.RI "void \fBgetBBoxRect\fP (double bbox[4]) const"
.br
.ti -1c
.RI "double \fBgetPageXMin\fP () const"
.br
.ti -1c
.RI "double \fBgetPageYMin\fP () const"
.br
.ti -1c
.RI "double \fBgetPageXMax\fP () const"
.br
.ti -1c
.RI "double \fBgetPageYMax\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 460 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
