.TH "AnnotLink" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotLink
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnot\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotLinkEffect\fP { \fBeffectNone\fP, \fBeffectInvert\fP, \fBeffectOutline\fP, \fBeffectPush\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotLink\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotLink\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBGfx\fP *gfx, GBool printing)"
.br
.ti -1c
.RI "\fBLinkAction\fP * \fBgetAction\fP () const"
.br
.ti -1c
.RI "AnnotLinkEffect \fBgetLinkEffect\fP () const"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetUriAction\fP () const"
.br
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP * \fBgetQuadrilaterals\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLinkAction\fP * \fBaction\fP"
.br
.ti -1c
.RI "AnnotLinkEffect \fBlinkEffect\fP"
.br
.ti -1c
.RI "\fBDict\fP * \fBuriAction\fP"
.br
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP * \fBquadrilaterals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 869 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
