.TH "AnnotBorderArray" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotBorderArray
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotBorder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotBorderArray\fP (\fBArray\fP *array)"
.br
.ti -1c
.RI "void \fBsetHorizontalCorner\fP (double hc)"
.br
.ti -1c
.RI "void \fBsetVerticalCorner\fP (double vc)"
.br
.ti -1c
.RI "double \fBgetHorizontalCorner\fP () const"
.br
.ti -1c
.RI "double \fBgetVerticalCorner\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 261 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
