.TH "AnnotText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotMarkup\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotTextState\fP { \fBstateUnknown\fP, \fBstateMarked\fP, \fBstateUnmarked\fP, \fBstateAccepted\fP, \fBstateRejected\fP, \fBstateCancelled\fP, \fBstateCompleted\fP, \fBstateNone\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotText\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotText\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBGfx\fP *gfx, GBool printing)"
.br
.ti -1c
.RI "GBool \fBgetOpen\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetIcon\fP () const"
.br
.ti -1c
.RI "AnnotTextState \fBgetState\fP () const"
.br
.ti -1c
.RI "void \fBsetOpen\fP (GBool openA)"
.br
.ti -1c
.RI "void \fBsetIcon\fP (\fBGooString\fP *new_icon)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 771 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
