.TH "AnnotRichMedia::Configuration" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia::Configuration
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBtype3D\fP, \fBtypeFlash\fP, \fBtypeSound\fP, \fBtypeVideo\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "Type \fBgetType\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP () const"
.br
.ti -1c
.RI "int \fBgetInstancesCount\fP () const"
.br
.ti -1c
.RI "\fBInstance\fP * \fBgetInstance\fP (int index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1452 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
