.TH "AnnotQuadrilaterals::AnnotQuadrilateral" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotQuadrilaterals::AnnotQuadrilateral
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotQuadrilateral\fP (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAnnotCoord\fP \fBcoord1\fP"
.br
.ti -1c
.RI "\fBAnnotCoord\fP \fBcoord2\fP"
.br
.ti -1c
.RI "\fBAnnotCoord\fP \fBcoord3\fP"
.br
.ti -1c
.RI "\fBAnnotCoord\fP \fBcoord4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
