.TH "AnnotScreen" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotScreen
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotScreen\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotScreen\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetTitle\fP ()"
.br
.ti -1c
.RI "\fBAnnotAppearanceCharacs\fP * \fBgetAppearCharacs\fP ()"
.br
.ti -1c
.RI "\fBLinkAction\fP * \fBgetAction\fP ()"
.br
.ti -1c
.RI "\fBLinkAction\fP * \fBgetAdditionalAction\fP (\fBAdditionalActionsType\fP type)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 840 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
