.TH "AnnotQuadrilaterals" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotQuadrilaterals
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnnotQuadrilateral\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP (\fBArray\fP *array, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP (\fBAnnotQuadrilateral\fP **quads, int quadsLength)"
.br
.ti -1c
.RI "double \fBgetX1\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetY1\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetX2\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetY2\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetX3\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetY3\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetX4\fP (int quadrilateral)"
.br
.ti -1c
.RI "double \fBgetY4\fP (int quadrilateral)"
.br
.ti -1c
.RI "int \fBgetQuadrilateralsLength\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAnnotQuadrilateral\fP ** \fBquadrilaterals\fP"
.br
.ti -1c
.RI "int \fBquadrilateralsLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
