.TH "AnnotBorderBS" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotBorderBS
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotBorder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotBorderBS\fP (\fBDict\fP *dict)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 285 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
