.TH "AnnotIconFit" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotIconFit
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotIconFitScaleWhen\fP { \fBscaleAlways\fP, \fBscaleBigger\fP, \fBscaleSmaller\fP, \fBscaleNever\fP }"
.br
.ti -1c
.RI "enum \fBAnnotIconFitScale\fP { \fBscaleAnamorphic\fP, \fBscaleProportional\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotIconFit\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "AnnotIconFitScaleWhen \fBgetScaleWhen\fP ()"
.br
.ti -1c
.RI "AnnotIconFitScale \fBgetScale\fP ()"
.br
.ti -1c
.RI "double \fBgetLeft\fP ()"
.br
.ti -1c
.RI "double \fBgetBottom\fP ()"
.br
.ti -1c
.RI "bool \fBgetFullyBounds\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "AnnotIconFitScaleWhen \fBscaleWhen\fP"
.br
.ti -1c
.RI "AnnotIconFitScale \fBscale\fP"
.br
.ti -1c
.RI "double \fBleft\fP"
.br
.ti -1c
.RI "double \fBbottom\fP"
.br
.ti -1c
.RI "bool \fBfullyBounds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 339 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
