.TH "AnnotPopup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotPopup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotPopup\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotPopup\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetParent\fP (\fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetParentNF\fP ()"
.br
.ti -1c
.RI "void \fBsetParent\fP (\fBObject\fP *parentA)"
.br
.ti -1c
.RI "void \fBsetParent\fP (\fBAnnot\fP *parentA)"
.br
.ti -1c
.RI "GBool \fBgetOpen\fP () const"
.br
.ti -1c
.RI "void \fBsetOpen\fP (GBool openA)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBObject\fP \fBparent\fP"
.br
.ti -1c
.RI "GBool \fBopen\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 695 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
