.TH "AnnotMarkup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotMarkup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnot\fP\&.
.PP
Inherited by \fBAnnotCaret\fP, \fBAnnotFileAttachment\fP, \fBAnnotFreeText\fP, \fBAnnotGeometry\fP, \fBAnnotInk\fP, \fBAnnotLine\fP, \fBAnnotPolygon\fP, \fBAnnotSound\fP, \fBAnnotStamp\fP, \fBAnnotText\fP, and \fBAnnotTextMarkup\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotMarkupReplyType\fP { \fBreplyTypeR\fP, \fBreplyTypeGroup\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotMarkup\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect)"
.br
.ti -1c
.RI "\fBAnnotMarkup\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetLabel\fP () const"
.br
.ti -1c
.RI "\fBAnnotPopup\fP * \fBgetPopup\fP () const"
.br
.ti -1c
.RI "double \fBgetOpacity\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetDate\fP () const"
.br
.ti -1c
.RI "int \fBgetInReplyToID\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetSubject\fP () const"
.br
.ti -1c
.RI "AnnotMarkupReplyType \fBgetReplyTo\fP () const"
.br
.ti -1c
.RI "AnnotExternalDataType \fBgetExData\fP () const"
.br
.ti -1c
.RI "void \fBsetPopup\fP (\fBAnnotPopup\fP *new_popup)"
.br
.ti -1c
.RI "void \fBsetLabel\fP (\fBGooString\fP *new_label)"
.br
.ti -1c
.RI "void \fBsetOpacity\fP (double opacityA)"
.br
.ti -1c
.RI "void \fBsetDate\fP (\fBGooString\fP *new_date)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBremoveReferencedObjects\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBlabel\fP"
.br
.ti -1c
.RI "\fBAnnotPopup\fP * \fBpopup\fP"
.br
.ti -1c
.RI "double \fBopacity\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBdate\fP"
.br
.ti -1c
.RI "\fBRef\fP \fBinReplyTo\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBsubject\fP"
.br
.ti -1c
.RI "AnnotMarkupReplyType \fBreplyTo\fP"
.br
.ti -1c
.RI "AnnotExternalDataType \fBexData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 719 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
