.TH "AnnotCoord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotCoord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotCoord\fP (double _x, double _y)"
.br
.ti -1c
.RI "double \fBgetX\fP () const"
.br
.ti -1c
.RI "double \fBgetY\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
