.TH "AnnotAppearance" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotAppearance
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAnnotAppearanceType\fP { \fBappearNormal\fP, \fBappearRollover\fP, \fBappearDown\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotAppearance\fP (\fBPDFDoc\fP *docA, \fBObject\fP *dict)"
.br
.ti -1c
.RI "void \fBgetAppearanceStream\fP (AnnotAppearanceType type, const char *state, \fBObject\fP *dest)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetStateKey\fP (int i)"
.br
.ti -1c
.RI "int \fBgetNumStates\fP ()"
.br
.ti -1c
.RI "void \fBremoveAllStreams\fP ()"
.br
.ti -1c
.RI "GBool \fBreferencesStream\fP (\fBRef\fP targetStreamRef)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPDFDoc\fP * \fBdoc\fP"
.br
.ti -1c
.RI "\fBXRef\fP * \fBxref\fP"
.br
.ti -1c
.RI "\fBObject\fP \fBappearDict\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 375 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
