.TH "AnnotSound" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotSound
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotMarkup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotSound\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect, \fBSound\fP *soundA)"
.br
.ti -1c
.RI "\fBAnnotSound\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBGfx\fP *gfx, GBool printing)"
.br
.ti -1c
.RI "\fBSound\fP * \fBgetSound\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1272 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
