.TH "AnnotTextMarkup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotTextMarkup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotMarkup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotTextMarkup\fP (\fBPDFDoc\fP *docA, \fBPDFRectangle\fP *rect, AnnotSubtype subType)"
.br
.ti -1c
.RI "\fBAnnotTextMarkup\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict, \fBObject\fP *obj)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBGfx\fP *gfx, GBool printing)"
.br
.ti -1c
.RI "void \fBsetType\fP (AnnotSubtype new_type)"
.br
.ti -1c
.RI "void \fBsetQuadrilaterals\fP (\fBAnnotQuadrilaterals\fP *quadPoints)"
.br
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP * \fBgetQuadrilaterals\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (\fBPDFDoc\fP *docA, \fBDict\fP *dict)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAnnotQuadrilaterals\fP * \fBquadrilaterals\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1048 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
