.TH "AnnotRichMedia::Params" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotRichMedia::Params
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParams\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFlashVars\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1419 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
