.TH "AnnotCalloutMultiLine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotCalloutMultiLine
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAnnotCalloutLine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotCalloutMultiLine\fP (double x1, double y1, double x2, double y2, double x3, double y3)"
.br
.ti -1c
.RI "double \fBgetX3\fP () const"
.br
.ti -1c
.RI "double \fBgetY3\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAnnotCoord\fP \fBcoord3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 143 of file Annot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
