.TH "Array" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArray\fP (\fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "int \fBincRef\fP ()"
.br
.ti -1c
.RI "int \fBdecRef\fP ()"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "\fBObject\fP * \fBcopy\fP (\fBXRef\fP *xrefA, \fBObject\fP *obj)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBObject\fP *elem)"
.br
.ti -1c
.RI "void \fBremove\fP (int i)"
.br
.ti -1c
.RI "\fBObject\fP * \fBget\fP (int i, \fBObject\fP *obj, int resursion=0)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetNF\fP (int i, \fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBgetString\fP (int i, \fBGooString\fP *string)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file Array\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
