.TH "Asection" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsection\fP (float fsam)"
.br
.ti -1c
.RI "float * \fBget_wptr\fP ()"
.br
.ti -1c
.RI "\fBSyntiParameter\fP * \fBget_apar\fP ()"
.br
.ti -1c
.RI "void \fBset_size\fP (float size)"
.br
.ti -1c
.RI "void \fBprocess\fP (float vol, float *W, float *X, float *Y, float *R)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fB_refl\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file asection\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Asection::_refl\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
{
    0\&.250f, 0\&.440f, 0\&.615f, 0\&.940f,
    0\&.200f, 0\&.370f, 0\&.560f, 0\&.900f,
    0\&.230f, 0\&.400f, 0\&.500f, 0\&.920f,
    0\&.280f, 0\&.460f, 0\&.690f, 0\&.960f
}
.fi
.PP
Definition at line 85 of file asection\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
