.TH "ASN1_ITEM_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASN1_ITEM_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBitype\fP"
.br
.ti -1c
.RI "long \fButype\fP"
.br
.ti -1c
.RI "const \fBASN1_TEMPLATE\fP * \fBtemplates\fP"
.br
.ti -1c
.RI "long \fBtcount\fP"
.br
.ti -1c
.RI "const void * \fBfuncs\fP"
.br
.ti -1c
.RI "long \fBsize\fP"
.br
.ti -1c
.RI "const char * \fBsname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 568 of file asn1t\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
