.TH "asn1_string_table_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asn1_string_table_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnid\fP"
.br
.ti -1c
.RI "long \fBminsize\fP"
.br
.ti -1c
.RI "long \fBmaxsize\fP"
.br
.ti -1c
.RI "unsigned long \fBmask\fP"
.br
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 271 of file asn1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
