.TH "asn1_type_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asn1_type_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   ASN1_BOOLEAN \fBboolean\fP"
.br
.ti -1c
.RI "   \fBASN1_STRING\fP * \fBasn1_string\fP"
.br
.ti -1c
.RI "   \fBASN1_OBJECT\fP * \fBobject\fP"
.br
.ti -1c
.RI "   \fBASN1_INTEGER\fP * \fBinteger\fP"
.br
.ti -1c
.RI "   \fBASN1_ENUMERATED\fP * \fBenumerated\fP"
.br
.ti -1c
.RI "   \fBASN1_BIT_STRING\fP * \fBbit_string\fP"
.br
.ti -1c
.RI "   \fBASN1_OCTET_STRING\fP * \fBoctet_string\fP"
.br
.ti -1c
.RI "   \fBASN1_PRINTABLESTRING\fP * \fBprintablestring\fP"
.br
.ti -1c
.RI "   \fBASN1_T61STRING\fP * \fBt61string\fP"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBia5string\fP"
.br
.ti -1c
.RI "   \fBASN1_GENERALSTRING\fP * \fBgeneralstring\fP"
.br
.ti -1c
.RI "   \fBASN1_BMPSTRING\fP * \fBbmpstring\fP"
.br
.ti -1c
.RI "   \fBASN1_UNIVERSALSTRING\fP * \fBuniversalstring\fP"
.br
.ti -1c
.RI "   \fBASN1_UTCTIME\fP * \fButctime\fP"
.br
.ti -1c
.RI "   \fBASN1_GENERALIZEDTIME\fP * \fBgeneralizedtime\fP"
.br
.ti -1c
.RI "   \fBASN1_VISIBLESTRING\fP * \fBvisiblestring\fP"
.br
.ti -1c
.RI "   \fBASN1_UTF8STRING\fP * \fButf8string\fP"
.br
.ti -1c
.RI "   \fBASN1_STRING\fP * \fBset\fP"
.br
.ti -1c
.RI "   \fBASN1_STRING\fP * \fBsequence\fP"
.br
.ti -1c
.RI "   ASN1_VALUE * \fBasn1_value\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 521 of file asn1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
