.TH "AudioFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBopen\fP (const QByteArray &)"
.br
.ti -1c
.RI "const char * \fBerror\fP () const"
.br
.ti -1c
.RI "int \fBread\fP (short *, int)"
.br
.ti -1c
.RI "int \fBchannels\fP () const"
.br
.ti -1c
.RI "int \fBframes\fP () const"
.br
.ti -1c
.RI "int \fBsamplerate\fP () const"
.br
.ti -1c
.RI "sf_count_t \fBgetFileLen\fP () const"
.br
.ti -1c
.RI "sf_count_t \fBtell\fP () const"
.br
.ti -1c
.RI "sf_count_t \fBread\fP (void *ptr, sf_count_t count)"
.br
.ti -1c
.RI "sf_count_t \fBwrite\fP (const void *ptr, sf_count_t count)"
.br
.ti -1c
.RI "sf_count_t \fBseek\fP (sf_count_t offset, int whence)"
.br
.ti -1c
.RI "unsigned int \fBloopStart\fP (int v=0)"
.br
.ti -1c
.RI "unsigned int \fBloopEnd\fP (int v=0)"
.br
.ti -1c
.RI "int \fBloopMode\fP (int v=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file audiofile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
