.TH "AUTHORITY_KEYID_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AUTHORITY_KEYID_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBkeyid\fP"
.br
.ti -1c
.RI "GENERAL_NAMES * \fBissuer\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBserial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 260 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
