.TH "Awl::Knob" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::Knob \- Base class of all dialer type input widgets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <knob\&.h>\fP
.PP
Inherits \fBAwl::AbstractSlider\fP\&.
.PP
Inherited by \fBAwl::MidiPanKnob\fP, \fBAwl::PanKnob\fP, and \fBAwl::VolKnob\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsliderPressed\fP (int)"
.br
.ti -1c
.RI "void \fBsliderReleased\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKnob\fP (QWidget *parent=0)"
.br
.RI "this is the AwlKnob contructor "
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.ti -1c
.RI "virtual int \fBheightForWidth\fP (int w) const"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.RI "return text decoration "
.ti -1c
.RI "void \fBsetText\fP (const QString &s)"
.br
.ti -1c
.RI "int \fBscaleSize\fP () const"
.br
.RI "return scale size in degrees "
.ti -1c
.RI "void \fBsetScaleSize\fP (int val)"
.br
.RI "set the scale size in degrees "
.ti -1c
.RI "int \fBmarkSize\fP () const"
.br
.ti -1c
.RI "void \fBsetMarkSize\fP (int val)"
.br
.RI "set size of the center marker "
.ti -1c
.RI "int \fBborder\fP () const"
.br
.ti -1c
.RI "void \fBsetBorder\fP (int val)"
.br
.RI "set border size "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBstartY\fP"
.br
.ti -1c
.RI "QString \fB_text\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBscaleSize\fP"
.br
.ti -1c
.RI "int \fBmarkSize\fP"
.br
.ti -1c
.RI "int \fBborder\fP"
.br
.ti -1c
.RI "QString \fBtext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class of all dialer type input widgets\&. 

xxxxxxxxx 
.PP
Definition at line 38 of file knob\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Awl::Knob::setScaleSize (int val)"

.PP
set the scale size in degrees the scale size is the max moving angle measured in degrees 
.PP
Definition at line 69 of file knob\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
