.TH "Awl::VolSlider" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::VolSlider \- Volume \fBSlider\fP entry widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <volslider\&.h>\fP
.PP
Inherits \fBAwl::Slider\fP\&.
.PP
Inherited by \fBAwl::MeterSlider\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsetValue\fP (double v)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVolSlider\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "virtual double \fBvalue\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Volume \fBSlider\fP entry widget\&. 

This widget implements a slider with a logarithmic floating point scale used to adjust the volume in an audio mixer\&. Internal value represents gain as a logarythmic dB value\&. 
.PP
Definition at line 39 of file volslider\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
