.TH "Awl::PosLabel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::PosLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QLabel\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetValue\fP (const \fBPos\fP &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPosLabel\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBPosLabel\fP (\fBTempoMap\fP *, \fBTimeSigMap\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetContext\fP (\fBTempoMap\fP *, \fBTimeSigMap\fP *)"
.br
.ti -1c
.RI "\fBPos\fP \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBsetSmpte\fP (bool)"
.br
.ti -1c
.RI "bool \fBsmpte\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file poslabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
