.TH "Awl::PitchLabel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::PitchLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QLabel\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetValue\fP (int)"
.br
.ti -1c
.RI "void \fBsetInt\fP (int)"
.br
.ti -1c
.RI "void \fBsetPitch\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPitchLabel\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBsetPitchMode\fP (bool val)"
.br
.ti -1c
.RI "bool \fBpitchMode\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file pitchlabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
