.TH "Awl::MeterSlider" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::MeterSlider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAwl::VolSlider\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBresetPeaks\fP ()"
.br
.ti -1c
.RI "void \fBsetMeterVal\fP (int channel, double value, double peak)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmeterClicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeterSlider\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetChannel\fP (int n)"
.br
.ti -1c
.RI "int \fBchannel\fP () const"
.br
.ti -1c
.RI "int \fBmeterWidth\fP () const"
.br
.ti -1c
.RI "void \fBsetMeterWidth\fP (int v)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBmeterWidth\fP"
.br
.ti -1c
.RI "int \fBchannel\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file mslider\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
