.TH "Awl::VolKnob" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::VolKnob \- Volume \fBKnob\fP entry widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <volknob\&.h>\fP
.PP
Inherits \fBAwl::Knob\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVolKnob\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Volume \fBKnob\fP entry widget\&. 

This widget implements knob with a logarithmic floating point scale used to adjust the volume in an audio mixer\&. 
.PP
Definition at line 37 of file volknob\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
