.TH "Awl::ColorLabel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::ColorLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QFrame\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcolorChanged\fP (QColor)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorLabel\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetColor\fP (const QColor &c)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.ti -1c
.RI "void \fBsetPixmap\fP (QPixmap *)"
.br
.ti -1c
.RI "QColor \fBcolor\fP () const"
.br
.ti -1c
.RI "QPixmap * \fBpixmap\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file colorlabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
