.TH "Awl::Slider" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::Slider \- Base class of all slider type input widgets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slider\&.h>\fP
.PP
Inherits \fBAwl::AbstractSlider\fP\&.
.PP
Inherited by \fBAwl::VolSlider\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsliderPressed\fP (int)"
.br
.ti -1c
.RI "void \fBsliderReleased\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlider\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBSlider\fP (Qt::Orientation orientation, QWidget *parent=0)"
.br
.ti -1c
.RI "virtual void \fBsetOrientation\fP (Qt::Orientation)"
.br
.ti -1c
.RI "Qt::Orientation \fBorientation\fP () const"
.br
.ti -1c
.RI "QSize \fBsliderSize\fP () const"
.br
.ti -1c
.RI "void \fBsetSliderSize\fP (const QSize &s)"
.br
.ti -1c
.RI "virtual void \fBsetInvertedAppearance\fP (bool val)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QPainterPath * \fBpoints\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Qt::Orientation \fBorientation\fP"
.br
.ti -1c
.RI "QSize \fBsliderSize\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class of all slider type input widgets\&. 

Inherits from AwlKnob 
.PP
Definition at line 37 of file slider\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
