.TH "Awl::MidiPanKnob" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Awl::MidiPanKnob \- MidiPan \fBKnob\fP entry widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <midipanknob\&.h>\fP
.PP
Inherits \fBAwl::Knob\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsetValue\fP (double v)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiPanKnob\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "virtual double \fBvalue\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
MidiPan \fBKnob\fP entry widget\&. 

This widget implements a centered floating point knob used to adjust the pan position in an audio mixer\&. 
.PP
Definition at line 37 of file midipanknob\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
