.TH "AwlPlugin" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AwlPlugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDesignerCustomWidgetInterface\&.
.PP
Inherited by \fBColorLabelPlugin\fP, \fBDenominatorSpinBoxPlugin\fP, \fBKnobPlugin\fP, \fBMeterSliderPlugin\fP, \fBMidiPanKnobPlugin\fP, \fBPanKnobPlugin\fP, \fBPitchEditPlugin\fP, \fBPitchLabelPlugin\fP, \fBSliderPlugin\fP, \fBVolKnobPlugin\fP, and \fBVolSliderPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisContainer\fP () const"
.br
.ti -1c
.RI "bool \fBisInitialized\fP () const"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const"
.br
.ti -1c
.RI "virtual QString \fBcodeTemplate\fP () const"
.br
.ti -1c
.RI "QString \fBwhatsThis\fP () const"
.br
.ti -1c
.RI "QString \fBtoolTip\fP () const"
.br
.ti -1c
.RI "QString \fBgroup\fP () const"
.br
.ti -1c
.RI "void \fBinitialize\fP (QDesignerFormEditorInterface *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file awlplugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
