.TH "BaseCache< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseCache< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits QCache< quint64, T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseCache\fP (int maxCost)"
.br
.RI "constructor "
.ti -1c
.RI "void \fBsetEnabled\fP (bool value)"
.br
.RI "enable "
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.RI "enable state "
.ti -1c
.RI "T * \fBobject\fP (const quint64 &key)"
.br
.RI "access "
.ti -1c
.RI "void \fBsetMaxCost\fP (int cost)"
.br
.RI "max cost "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class BaseCache< T >"

.PP
Definition at line 9 of file cache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
