.TH "BaseDataMap< K, T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseDataMap< K, T > \- data map  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datamap\&.h>\fP
.PP
Inherits QMap< const K *, QPointer< T > >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const K * \fBKey\fP"
.br
.ti -1c
.RI "typedef QPointer< T > \fBValue\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseDataMap\fP (void)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~BaseDataMap\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual QMap< Key, Value >::iterator \fBinsert\fP (const Key &key, const Value &value, bool \fBenabled\fP=true)"
.br
.RI "insertion "
.ti -1c
.RI "Value \fBfind\fP (Key key)"
.br
.RI "find value "
.ti -1c
.RI "bool \fBunregisterWidget\fP (Key key)"
.br
.RI "unregister widget "
.ti -1c
.RI "void \fBsetEnabled\fP (bool \fBenabled\fP)"
.br
.RI "maxFrame "
.ti -1c
.RI "bool \fBenabled\fP (void) const"
.br
.RI "enability "
.ti -1c
.RI "void \fBsetDuration\fP (int duration) const"
.br
.RI "duration "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename K, typename T>
.br
class BaseDataMap< K, T >"
data map 

it maps templatized data object to associated object 
.PP
Definition at line 32 of file datamap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
