.TH "bdf_glyph_t_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bdf_glyph_t_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "long \fBencoding\fP"
.br
.ti -1c
.RI "unsigned short \fBswidth\fP"
.br
.ti -1c
.RI "unsigned short \fBdwidth\fP"
.br
.ti -1c
.RI "\fBbdf_bbx_t\fP \fBbbx\fP"
.br
.ti -1c
.RI "unsigned char * \fBbitmap\fP"
.br
.ti -1c
.RI "unsigned long \fBbpr\fP"
.br
.ti -1c
.RI "unsigned short \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file bdf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
