.TH "bio_f_buffer_ctx_struct" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_f_buffer_ctx_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBibuf_size\fP"
.br
.ti -1c
.RI "int \fBobuf_size\fP"
.br
.ti -1c
.RI "char * \fBibuf\fP"
.br
.ti -1c
.RI "int \fBibuf_len\fP"
.br
.ti -1c
.RI "int \fBibuf_off\fP"
.br
.ti -1c
.RI "char * \fBobuf\fP"
.br
.ti -1c
.RI "int \fBobuf_len\fP"
.br
.ti -1c
.RI "int \fBobuf_off\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 334 of file bio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
