.TH "bio_method_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_method_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBbwrite\fP )(\fBBIO\fP *, const char *, int)"
.br
.ti -1c
.RI "int(* \fBbread\fP )(\fBBIO\fP *, char *, int)"
.br
.ti -1c
.RI "int(* \fBbputs\fP )(\fBBIO\fP *, const char *)"
.br
.ti -1c
.RI "int(* \fBbgets\fP )(\fBBIO\fP *, char *, int)"
.br
.ti -1c
.RI "long(* \fBctrl\fP )(\fBBIO\fP *, int, long, void *)"
.br
.ti -1c
.RI "int(* \fBcreate\fP )(\fBBIO\fP *)"
.br
.ti -1c
.RI "int(* \fBdestroy\fP )(\fBBIO\fP *)"
.br
.ti -1c
.RI "long(* \fBcallback_ctrl\fP )(\fBBIO\fP *, int, bio_info_cb *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 296 of file bio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
