.TH "bio_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBmethod\fP"
.br
.ti -1c
.RI "long(* \fBcallback\fP )(struct \fBbio_st\fP *, int, const char *, int, long, long)"
.br
.ti -1c
.RI "char * \fBcb_arg\fP"
.br
.ti -1c
.RI "int \fBinit\fP"
.br
.ti -1c
.RI "int \fBshutdown\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBretry_reason\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "struct \fBbio_st\fP * \fBnext_bio\fP"
.br
.ti -1c
.RI "struct \fBbio_st\fP * \fBprev_bio\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "unsigned long \fBnum_read\fP"
.br
.ti -1c
.RI "unsigned long \fBnum_write\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 310 of file bio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
