.TH "bio_dgram_sctp_sndinfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_dgram_sctp_sndinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsnd_sid\fP"
.br
.ti -1c
.RI "uint16_t \fBsnd_flags\fP"
.br
.ti -1c
.RI "uint32_t \fBsnd_ppid\fP"
.br
.ti -1c
.RI "uint32_t \fBsnd_context\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 363 of file bio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
