.TH "black_TWorker_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
black_TWorker_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Int \fBprecision_bits\fP"
.br
.ti -1c
.RI "Int \fBprecision\fP"
.br
.ti -1c
.RI "Int \fBprecision_half\fP"
.br
.ti -1c
.RI "Int \fBprecision_shift\fP"
.br
.ti -1c
.RI "Int \fBprecision_step\fP"
.br
.ti -1c
.RI "Int \fBprecision_jitter\fP"
.br
.ti -1c
.RI "Int \fBscale_shift\fP"
.br
.ti -1c
.RI "PLong \fBbuff\fP"
.br
.ti -1c
.RI "PLong \fBsizeBuff\fP"
.br
.ti -1c
.RI "PLong \fBmaxBuff\fP"
.br
.ti -1c
.RI "PLong \fBtop\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.ti -1c
.RI "Int \fBnumTurns\fP"
.br
.ti -1c
.RI "\fBTPoint\fP * \fBarc\fP"
.br
.ti -1c
.RI "UShort \fBbWidth\fP"
.br
.ti -1c
.RI "PByte \fBbTarget\fP"
.br
.ti -1c
.RI "PByte \fBgTarget\fP"
.br
.ti -1c
.RI "Long \fBlastX\fP"
.br
.ti -1c
.RI "Long \fBlastY\fP"
.br
.ti -1c
.RI "Long \fBminY\fP"
.br
.ti -1c
.RI "Long \fBmaxY\fP"
.br
.ti -1c
.RI "UShort \fBnum_Profs\fP"
.br
.ti -1c
.RI "Bool \fBfresh\fP"
.br
.ti -1c
.RI "Bool \fBjoint\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBcProfile\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBfProfile\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBgProfile\fP"
.br
.ti -1c
.RI "TStates \fBstate\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP \fBoutline\fP"
.br
.ti -1c
.RI "Long \fBtraceOfs\fP"
.br
.ti -1c
.RI "Long \fBtraceG\fP"
.br
.ti -1c
.RI "Short \fBtraceIncr\fP"
.br
.ti -1c
.RI "Function_Sweep_Init * \fBProc_Sweep_Init\fP"
.br
.ti -1c
.RI "Function_Sweep_Span * \fBProc_Sweep_Span\fP"
.br
.ti -1c
.RI "Function_Sweep_Span * \fBProc_Sweep_Drop\fP"
.br
.ti -1c
.RI "Function_Sweep_Step * \fBProc_Sweep_Step\fP"
.br
.ti -1c
.RI "Byte \fBdropOutControl\fP"
.br
.ti -1c
.RI "Bool \fBsecond_pass\fP"
.br
.ti -1c
.RI "\fBTPoint\fP \fBarcs\fP [3 *MaxBezier+1]"
.br
.ti -1c
.RI "\fBblack_TBand\fP \fBband_stack\fP [16]"
.br
.ti -1c
.RI "Int \fBband_top\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 466 of file ftraster\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
