.TH "bn_gencb_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bn_gencb_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBver\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   void(* \fBcb_1\fP )(int, int, void *)"
.br
.ti -1c
.RI "   int(* \fBcb_2\fP )(int, int, \fBBN_GENCB\fP *)"
.br
.ti -1c
.RI "} \fBcb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 354 of file bn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
