.TH "libmscore/box.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/box.h
.SH SYNOPSIS
.br
.PP
\fC#include 'measurebase\&.h'\fP
.br
\fC#include 'property\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::Box\fP"
.br
.RI "virtual base class for frames 'boxes' "
.ti -1c
.RI "class \fBMs::HBox\fP"
.br
.RI "horizontal frame "
.ti -1c
.RI "class \fBMs::VBox\fP"
.br
.RI "vertical frame "
.ti -1c
.RI "class \fBMs::FBox\fP"
.br
.RI "frame containing fret diagrams "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of HBox and VBox classes\&. 
.PP
Definition in file \fBbox\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
