.TH "bplist_info" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bplist_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBobject_count\fP"
.br
.ti -1c
.RI "const uint8_t * \fBdata_bytes\fP"
.br
.ti -1c
.RI "uint64_t \fBlength\fP"
.br
.ti -1c
.RI "uint64_t \fBoffset_table_offset\fP"
.br
.ti -1c
.RI "uint8_t \fBoffset_int_size\fP"
.br
.ti -1c
.RI "uint8_t \fBobject_ref_size\fP"
.br
.ti -1c
.RI "\fBcache_ptr\fP \fBcache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file readbinaryplist\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
