.TH "BuiltinFontWidths" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuiltinFontWidths
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuiltinFontWidths\fP (\fBBuiltinFontWidth\fP *widths, int sizeA)"
.br
.ti -1c
.RI "GBool \fBgetWidth\fP (const char *name, Gushort *width)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file BuiltinFont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
