.TH "Bww" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLexer\fP"
.br
.ti -1c
.RI "struct \fBMeasureBeginFlags\fP"
.br
.ti -1c
.RI "struct \fBMeasureDescription\fP"
.br
.ti -1c
.RI "struct \fBMeasureEndFlags\fP"
.br
.ti -1c
.RI "class \fBMsScWriter\fP"
.br
.ti -1c
.RI "class \fBMxmlWriter\fP"
.br
.ti -1c
.RI "struct \fBNoteDescription\fP"
.br
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSymbol\fP { \fBCOMMENT\fP, \fBHEADER\fP, \fBSTRING\fP, \fBCLEF\fP, \fBKEY\fP, \fBTEMPO\fP, \fBTSIG\fP, \fBPART\fP, \fBBAR\fP, \fBNOTE\fP, \fBTIE\fP, \fBTRIPLET\fP, \fBDOT\fP, \fBGRACE\fP, \fBUNKNOWN\fP, \fBNONE\fP }"
.br
.ti -1c
.RI "enum \fBStartStop\fP { \fBST_NONE\fP, \fBST_START\fP, \fBST_CONTINUE\fP, \fBST_STOP\fP }"
.br
.ti -1c
.RI "enum \fBBeamType\fP { \fBBM_NONE\fP, \fBBM_BEGIN\fP, \fBBM_CONTINUE\fP, \fBBM_END\fP, \fBBM_FORWARD_HOOK\fP, \fBBM_BACKWARD_HOOK\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBsymbolToString\fP (Symbol s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Symbol type to text translation\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
