.TH "Bww::MeasureBeginFlags" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::MeasureBeginFlags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <writer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrepeatBegin\fP"
.br
.ti -1c
.RI "bool \fBendingFirst\fP"
.br
.ti -1c
.RI "bool \fBendingSecond\fP"
.br
.ti -1c
.RI "bool \fBfirstOfSystem\fP"
.br
.ti -1c
.RI "bool \fBirregular\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The flags that need to be handled at the beginning of a measure\&. 
.PP
Definition at line 54 of file writer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
