.TH "Bww::NoteDescription" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::NoteDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteDescription\fP (const QString _pitch, const QString _beam, const QString _type, const int _dots, bool _tieStart=false, bool _tieStop=false, StartStop _triplet=ST_NONE, bool _grace=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBpitch\fP"
.br
.ti -1c
.RI "QString \fBbeam\fP"
.br
.ti -1c
.RI "QString \fBtype\fP"
.br
.ti -1c
.RI "int \fBdots\fP"
.br
.ti -1c
.RI "bool \fBtieStart\fP"
.br
.ti -1c
.RI "bool \fBtieStop\fP"
.br
.ti -1c
.RI "StartStop \fBtriplet\fP"
.br
.ti -1c
.RI "bool \fBgrace\fP"
.br
.ti -1c
.RI "StartStop \fBbeamState\fP"
.br
.ti -1c
.RI "QVector< BeamType > \fBbeamList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
