.TH "Bww::Parser" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (\fBLexer\fP &l, \fBWriter\fP &w)"
.br
.ti -1c
.RI "void \fBparse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The bww parser\&. 
.PP
Definition at line 82 of file parser\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Parser::Parser (\fBLexer\fP & l, \fBWriter\fP & w)"
\fBParser\fP constructor, using \fBLexer\fP \fIl\fP and \fBWriter\fP \fIw\fP\&. 
.PP
Definition at line 466 of file parser\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Parser::parse ()"
Parse the input stream and write result\&. 
.PP
Definition at line 485 of file parser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
