.TH "Bww::Lexer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::Lexer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lexer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLexer\fP (QIODevice *inDevice)"
.br
.ti -1c
.RI "void \fBgetSym\fP ()"
.br
.ti -1c
.RI "Symbol \fBsymType\fP () const"
.br
.ti -1c
.RI "QString \fBsymValue\fP () const"
.br
.ti -1c
.RI "int \fBsymLineNumber\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The bww lexer\&. 
.PP
Definition at line 45 of file lexer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lexer::Lexer (QIODevice * inDevice)"
\fBLexer\fP constructor, \fIinDevice\fP is the input\&. 
.PP
Definition at line 41 of file lexer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Lexer::getSym ()"
Get the next symbol, update type and value\&. 
.PP
Definition at line 344 of file lexer\&.cpp\&.
.SS "Symbol Lexer::symType () const"
Return the current symbols type\&. 
.PP
Definition at line 430 of file lexer\&.cpp\&.
.SS "QString Lexer::symValue () const"
Return the current symbols value\&. 
.PP
Definition at line 439 of file lexer\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
