.TH "Bww::MeasureEndFlags" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::MeasureEndFlags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <writer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrepeatEnd\fP"
.br
.ti -1c
.RI "bool \fBendingEnd\fP"
.br
.ti -1c
.RI "bool \fBlastOfSystem\fP"
.br
.ti -1c
.RI "bool \fBlastOfPart\fP"
.br
.ti -1c
.RI "bool \fBdoubleBarLine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The flags that need to be handled at the end of a measure\&. 
.PP
Definition at line 73 of file writer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
