.TH "Bww::MeasureDescription" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bww::MeasureDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMeasureBeginFlags\fP \fBmbf\fP"
.br
.ti -1c
.RI "QList< \fBNoteDescription\fP > \fBnotes\fP"
.br
.ti -1c
.RI "\fBMeasureEndFlags\fP \fBmef\fP"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
