.TH "CachedFileWriter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachedFileWriter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCachedFileWriter\fP (\fBCachedFile\fP *cachedFile, std::vector< int > *chunksA)"
.br
.ti -1c
.RI "size_t \fBwrite\fP (const char *ptr, size_t size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file CachedFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
