.TH "CachedFileLoader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachedFileLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCurlCachedFileLoader\fP, and \fBStdinCacheLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual size_t \fBinit\fP (\fBGooString\fP *uri, \fBCachedFile\fP *cachedFile)=0"
.br
.ti -1c
.RI "virtual int \fBload\fP (const std::vector< \fBByteRange\fP > &ranges, \fBCachedFileWriter\fP *writer)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file CachedFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
