.TH "CachedFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachedFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCachedFile\fP (\fBCachedFileLoader\fP *cacheLoader, \fBGooString\fP *uri)"
.br
.ti -1c
.RI "Guint \fBgetLength\fP ()"
.br
.ti -1c
.RI "long int \fBtell\fP ()"
.br
.ti -1c
.RI "int \fBseek\fP (long int offset, int origin)"
.br
.ti -1c
.RI "size_t \fBread\fP (void *ptr, size_t unitsize, size_t count)"
.br
.ti -1c
.RI "size_t \fBwrite\fP (const char *ptr, size_t size, size_t fromByte)"
.br
.ti -1c
.RI "int \fBcache\fP (const std::vector< \fBByteRange\fP > &ranges)"
.br
.ti -1c
.RI "void \fBincRefCnt\fP ()"
.br
.ti -1c
.RI "void \fBdecRefCnt\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCachedFileWriter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file CachedFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
