.TH "Cache< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBBaseCache\fP< T > \fBValue\fP"
.br
.RI "return cache matching a given key "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP * \fBget\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsetMaxCacheSize\fP (int value)"
.br
.RI "max cache size "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Cache< T >"

.PP
Definition at line 51 of file cache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
