.TH "CairoOutputDev::StrokePathClip" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CairoOutputDev::StrokePathClip
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGfxPath\fP * \fBpath\fP"
.br
.ti -1c
.RI "cairo_matrix_t \fBctm\fP"
.br
.ti -1c
.RI "double \fBline_width\fP"
.br
.ti -1c
.RI "double * \fBdashes\fP"
.br
.ti -1c
.RI "int \fBdash_count\fP"
.br
.ti -1c
.RI "double \fBdash_offset\fP"
.br
.ti -1c
.RI "cairo_line_cap_t \fBcap\fP"
.br
.ti -1c
.RI "cairo_line_join_t \fBjoin\fP"
.br
.ti -1c
.RI "double \fBmiter\fP"
.br
.ti -1c
.RI "int \fBref_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 304 of file CairoOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
