.TH "CairoImage" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CairoImage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCairoImage\fP (double x1, double y1, double x2, double y2)"
.br
.ti -1c
.RI "void \fBsetImage\fP (cairo_surface_t *image)"
.br
.ti -1c
.RI "cairo_surface_t * \fBgetImage\fP () const"
.br
.ti -1c
.RI "void \fBgetRect\fP (double *xa1, double *ya1, double *xa2, double *ya2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file CairoOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
