.TH "CairoFont" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CairoFont
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCairoFreeTypeFont\fP, and \fBCairoType3Font\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCairoFont\fP (\fBRef\fP ref, cairo_font_face_t *face, int *codeToGID, Guint codeToGIDLen, GBool substitute, GBool printing)"
.br
.ti -1c
.RI "virtual GBool \fBmatches\fP (\fBRef\fP &other, GBool printing)"
.br
.ti -1c
.RI "cairo_font_face_t * \fBgetFontFace\fP (void)"
.br
.ti -1c
.RI "unsigned long \fBgetGlyph\fP (CharCode code, Unicode *u, int uLen)"
.br
.ti -1c
.RI "double \fBgetSubstitutionCorrection\fP (\fBGfxFont\fP *gfxFont)"
.br
.ti -1c
.RI "GBool \fBisSubstitute\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRef\fP \fBref\fP"
.br
.ti -1c
.RI "cairo_font_face_t * \fBcairo_font_face\fP"
.br
.ti -1c
.RI "int * \fBcodeToGID\fP"
.br
.ti -1c
.RI "Guint \fBcodeToGIDLen\fP"
.br
.ti -1c
.RI "GBool \fBsubstitute\fP"
.br
.ti -1c
.RI "GBool \fBprinting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file CairoFontEngine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
