.TH "CairoRescaleBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CairoRescaleBox
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRescaleDrawImage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual GBool \fBdownScaleImage\fP (unsigned orig_width, unsigned orig_height, signed scaled_width, signed scaled_height, unsigned short int start_column, unsigned short int start_row, unsigned short int width, unsigned short int height, cairo_surface_t *dest_surface)"
.br
.ti -1c
.RI "virtual void \fBgetRow\fP (int row_num, uint32_t *row_data)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file CairoRescaleBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
