.TH "CairoType3Font" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CairoType3Font
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCairoFont\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual GBool \fBmatches\fP (\fBRef\fP &other, GBool printing)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCairoType3Font\fP * \fBcreate\fP (\fBGfxFont\fP *gfxFont, \fBPDFDoc\fP *doc, \fBCairoFontEngine\fP *fontEngine, GBool printing, \fBXRef\fP *xref)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 86 of file CairoFontEngine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
