.TH "ccs_header_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccs_header_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned short \fBseq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 153 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
