.TH "CF2_HintMoveRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_HintMoveRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBj\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBmoveUp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file cf2hints\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
