.TH "CF2_BlueRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_BlueRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_Fixed \fBcsBottomEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBcsTopEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBcsFlatEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBdsFlatEdge\fP"
.br
.ti -1c
.RI "FT_Bool \fBbottomZone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file cf2blues\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
