.TH "CF2_ArrStackRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_ArrStackRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.ti -1c
.RI "size_t \fBsizeItem\fP"
.br
.ti -1c
.RI "size_t \fBallocated\fP"
.br
.ti -1c
.RI "size_t \fBchunk\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBtotalSize\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file cf2arrst\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
