.TH "CF2_StackNumber_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_StackNumber_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   CF2_Fixed \fBr\fP"
.br
.ti -1c
.RI "   CF2_Frac \fBf\fP"
.br
.ti -1c
.RI "   CF2_Int \fBi\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "CF2_NumberType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file cf2stack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
