.TH "CF2_StackRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_StackRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.ti -1c
.RI "CF2_StackNumber \fBbuffer\fP [CF2_OPERAND_STACK_SIZE]"
.br
.ti -1c
.RI "CF2_StackNumber * \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file cf2stack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
