.TH "CF2_CallbackParamsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_CallbackParamsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Vector\fP \fBpt0\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpt1\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpt2\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpt3\fP"
.br
.ti -1c
.RI "CF2_Int \fBop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file cf2glue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
