.TH "CF2_FontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_FontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.ti -1c
.RI "CF2_RenderingFlags \fBrenderingFlags\fP"
.br
.ti -1c
.RI "\fBCF2_Matrix\fP \fBcurrentTransform\fP"
.br
.ti -1c
.RI "\fBCF2_Matrix\fP \fBinnerTransform\fP"
.br
.ti -1c
.RI "\fBCF2_Matrix\fP \fBouterTransform\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBppem\fP"
.br
.ti -1c
.RI "CF2_Int \fBunitsPerEm\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBsyntheticEmboldeningAmountX\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBsyntheticEmboldeningAmountY\fP"
.br
.ti -1c
.RI "\fBCF2_OutlineRec\fP \fBoutline\fP"
.br
.ti -1c
.RI "\fBCFF_Decoder\fP * \fBdecoder\fP"
.br
.ti -1c
.RI "\fBCFF_SubFont\fP \fBlastSubfont\fP"
.br
.ti -1c
.RI "FT_Bool \fBhinted\fP"
.br
.ti -1c
.RI "FT_Bool \fBdarkened\fP"
.br
.ti -1c
.RI "FT_Bool \fBstemDarkened\fP"
.br
.ti -1c
.RI "FT_Int \fBdarkenParams\fP [8]"
.br
.ti -1c
.RI "CF2_Fixed \fBstdVW\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBstdHW\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBdarkenX\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBdarkenY\fP"
.br
.ti -1c
.RI "FT_Bool \fBreverseWinding\fP"
.br
.ti -1c
.RI "\fBCF2_BluesRec\fP \fBblues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file cf2font\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
