.TH "CF2_Matrix_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_Matrix_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_F16Dot16 \fBa\fP"
.br
.ti -1c
.RI "CF2_F16Dot16 \fBb\fP"
.br
.ti -1c
.RI "CF2_F16Dot16 \fBc\fP"
.br
.ti -1c
.RI "CF2_F16Dot16 \fBd\fP"
.br
.ti -1c
.RI "CF2_F16Dot16 \fBtx\fP"
.br
.ti -1c
.RI "CF2_F16Dot16 \fBty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file cf2glue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
