.TH "CF2_HintRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_HintRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_UInt \fBflags\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBcsCoord\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBdsCoord\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file cf2blues\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
