.TH "CF2_BufferRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_BufferRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBstart\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBend\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file cf2read\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
