.TH "CF2_GlyphPathRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_GlyphPathRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCF2_Font\fP \fBfont\fP"
.br
.ti -1c
.RI "\fBCF2_OutlineCallbacks\fP \fBcallbacks\fP"
.br
.ti -1c
.RI "\fBCF2_HintMapRec\fP \fBhintMap\fP"
.br
.ti -1c
.RI "\fBCF2_HintMapRec\fP \fBfirstHintMap\fP"
.br
.ti -1c
.RI "\fBCF2_HintMapRec\fP \fBinitialHintMap\fP"
.br
.ti -1c
.RI "CF2_ArrStackRec \fBhintMoves\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBscaleX\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBscaleC\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBscaleY\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfractionalTranslation\fP"
.br
.ti -1c
.RI "FT_Bool \fBpathIsOpen\fP"
.br
.ti -1c
.RI "FT_Bool \fBpathIsClosing\fP"
.br
.ti -1c
.RI "FT_Bool \fBdarken\fP"
.br
.ti -1c
.RI "FT_Bool \fBmoveIsPending\fP"
.br
.ti -1c
.RI "CF2_ArrStack \fBhStemHintArray\fP"
.br
.ti -1c
.RI "CF2_ArrStack \fBvStemHintArray\fP"
.br
.ti -1c
.RI "\fBCF2_HintMask\fP \fBhintMask\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBhintOriginY\fP"
.br
.ti -1c
.RI "const \fBCF2_BluesRec\fP * \fBblues\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBxOffset\fP"
.br
.ti -1c
.RI "CF2_Fixed \fByOffset\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBmiterLimit\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBsnapThreshold\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBoffsetStart0\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBoffsetStart1\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBcurrentCS\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBcurrentDS\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBstart\fP"
.br
.ti -1c
.RI "FT_Bool \fBelemIsQueued\fP"
.br
.ti -1c
.RI "CF2_Int \fBprevElemOp\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBprevElemP0\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBprevElemP1\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBprevElemP2\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBprevElemP3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file cf2hints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
