.TH "CF2_OutlineCallbacksRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_OutlineCallbacksRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_Callback_Type \fBmoveTo\fP"
.br
.ti -1c
.RI "CF2_Callback_Type \fBlineTo\fP"
.br
.ti -1c
.RI "CF2_Callback_Type \fBquadTo\fP"
.br
.ti -1c
.RI "CF2_Callback_Type \fBcubeTo\fP"
.br
.ti -1c
.RI "CF2_Int \fBwindingMomentum\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file cf2glue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
