.TH "CF2_BluesRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_BluesRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_Fixed \fBscale\fP"
.br
.ti -1c
.RI "CF2_UInt \fBcount\fP"
.br
.ti -1c
.RI "FT_Bool \fBsuppressOvershoot\fP"
.br
.ti -1c
.RI "FT_Bool \fBdoEmBoxHints\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueScale\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueShift\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueFuzz\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBboost\fP"
.br
.ti -1c
.RI "\fBCF2_HintRec\fP \fBemBoxTopEdge\fP"
.br
.ti -1c
.RI "\fBCF2_HintRec\fP \fBemBoxBottomEdge\fP"
.br
.ti -1c
.RI "\fBCF2_BlueRec\fP \fBzone\fP [CF2_MAX_BLUES+CF2_MAX_OTHERBLUES]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file cf2blues\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
