.TH "CFF_DriverRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_DriverRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_DriverRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_UInt \fBhinting_engine\fP"
.br
.ti -1c
.RI "FT_Bool \fBno_stem_darkening\fP"
.br
.ti -1c
.RI "FT_Int \fBdarken_params\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file cffobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
