.TH "CFF_Decoder_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Decoder_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCFF_Builder\fP \fBbuilder\fP"
.br
.ti -1c
.RI "\fBCFF_Font\fP \fBcff\fP"
.br
.ti -1c
.RI "FT_Fixed \fBstack\fP [CFF_MAX_OPERANDS+1]"
.br
.ti -1c
.RI "FT_Fixed * \fBtop\fP"
.br
.ti -1c
.RI "\fBCFF_Decoder_Zone\fP \fBzones\fP [CFF_MAX_SUBRS_CALLS+1]"
.br
.ti -1c
.RI "\fBCFF_Decoder_Zone\fP * \fBzone\fP"
.br
.ti -1c
.RI "FT_Int \fBflex_state\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_flex_vectors\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBflex_vectors\fP [7]"
.br
.ti -1c
.RI "FT_Pos \fBglyph_width\fP"
.br
.ti -1c
.RI "FT_Pos \fBnominal_width\fP"
.br
.ti -1c
.RI "FT_Bool \fBread_width\fP"
.br
.ti -1c
.RI "FT_Bool \fBwidth_only\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_hints\fP"
.br
.ti -1c
.RI "FT_Fixed \fBbuildchar\fP [CFF_MAX_TRANS_ELEMENTS]"
.br
.ti -1c
.RI "FT_UInt \fBnum_locals\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_globals\fP"
.br
.ti -1c
.RI "FT_Int \fBlocals_bias\fP"
.br
.ti -1c
.RI "FT_Int \fBglobals_bias\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBlocals\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglobals\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglyph_names\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_Render_Mode \fBhint_mode\fP"
.br
.ti -1c
.RI "FT_Bool \fBseac\fP"
.br
.ti -1c
.RI "\fBCFF_SubFont\fP \fBcurrent_subfont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file cffgload\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
