.TH "CFF_FDSelectRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_FDSelectRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBformat\fP"
.br
.ti -1c
.RI "FT_UInt \fBrange_count\fP"
.br
.ti -1c
.RI "FT_Byte * \fBdata\fP"
.br
.ti -1c
.RI "FT_UInt \fBdata_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBcache_first\fP"
.br
.ti -1c
.RI "FT_UInt \fBcache_count\fP"
.br
.ti -1c
.RI "FT_Byte \fBcache_fd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
