.TH "CFF_SubFontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_SubFontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCFF_FontRecDictRec\fP \fBfont_dict\fP"
.br
.ti -1c
.RI "\fBCFF_PrivateRec\fP \fBprivate_dict\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBlocal_subrs_index\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBlocal_subrs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
