.TH "CFF_CharsetRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_CharsetRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBformat\fP"
.br
.ti -1c
.RI "FT_ULong \fBoffset\fP"
.br
.ti -1c
.RI "FT_UShort * \fBsids\fP"
.br
.ti -1c
.RI "FT_UShort * \fBcids\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_cid\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
