.TH "CFF_PrivateRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_PrivateRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBnum_blue_values\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_other_blues\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_family_blues\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_family_other_blues\fP"
.br
.ti -1c
.RI "FT_Pos \fBblue_values\fP [14]"
.br
.ti -1c
.RI "FT_Pos \fBother_blues\fP [10]"
.br
.ti -1c
.RI "FT_Pos \fBfamily_blues\fP [14]"
.br
.ti -1c
.RI "FT_Pos \fBfamily_other_blues\fP [10]"
.br
.ti -1c
.RI "FT_Fixed \fBblue_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBblue_shift\fP"
.br
.ti -1c
.RI "FT_Pos \fBblue_fuzz\fP"
.br
.ti -1c
.RI "FT_Pos \fBstandard_width\fP"
.br
.ti -1c
.RI "FT_Pos \fBstandard_height\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_snap_widths\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_snap_heights\fP"
.br
.ti -1c
.RI "FT_Pos \fBsnap_widths\fP [13]"
.br
.ti -1c
.RI "FT_Pos \fBsnap_heights\fP [13]"
.br
.ti -1c
.RI "FT_Bool \fBforce_bold\fP"
.br
.ti -1c
.RI "FT_Fixed \fBforce_bold_threshold\fP"
.br
.ti -1c
.RI "FT_Int \fBlenIV\fP"
.br
.ti -1c
.RI "FT_Int \fBlanguage_group\fP"
.br
.ti -1c
.RI "FT_Fixed \fBexpansion_factor\fP"
.br
.ti -1c
.RI "FT_Long \fBinitial_random_seed\fP"
.br
.ti -1c
.RI "FT_ULong \fBlocal_subrs_offset\fP"
.br
.ti -1c
.RI "FT_Pos \fBdefault_width\fP"
.br
.ti -1c
.RI "FT_Pos \fBnominal_width\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 151 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
