.TH "CFF_Builder_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Builder_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBTT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBCFF_GlyphSlot\fP \fBglyph\fP"
.br
.ti -1c
.RI "FT_GlyphLoader \fBloader\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP * \fBbase\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "FT_Pos \fBpos_x\fP"
.br
.ti -1c
.RI "FT_Pos \fBpos_y\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBleft_bearing\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBadvance\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBbbox\fP"
.br
.ti -1c
.RI "FT_Bool \fBpath_begun\fP"
.br
.ti -1c
.RI "FT_Bool \fBload_points\fP"
.br
.ti -1c
.RI "FT_Bool \fBno_recurse\fP"
.br
.ti -1c
.RI "FT_Bool \fBmetrics_only\fP"
.br
.ti -1c
.RI "void * \fBhints_funcs\fP"
.br
.ti -1c
.RI "void * \fBhints_globals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file cffgload\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
