.TH "CFF_FontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_FontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_faces\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_Byte \fBversion_major\fP"
.br
.ti -1c
.RI "FT_Byte \fBversion_minor\fP"
.br
.ti -1c
.RI "FT_Byte \fBheader_size\fP"
.br
.ti -1c
.RI "FT_Byte \fBabsolute_offsize\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBname_index\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBtop_dict_index\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBglobal_subrs_index\fP"
.br
.ti -1c
.RI "\fBCFF_EncodingRec\fP \fBencoding\fP"
.br
.ti -1c
.RI "\fBCFF_CharsetRec\fP \fBcharset\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBcharstrings_index\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBfont_dict_index\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBprivate_index\fP"
.br
.ti -1c
.RI "CFF_IndexRec \fBlocal_subrs_index\fP"
.br
.ti -1c
.RI "FT_String * \fBfont_name\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglobal_subrs\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_strings\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBstrings\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstring_pool\fP"
.br
.ti -1c
.RI "\fBCFF_SubFontRec\fP \fBtop_font\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_subfonts\fP"
.br
.ti -1c
.RI "\fBCFF_SubFont\fP \fBsubfonts\fP [CFF_MAX_CID_FONTS]"
.br
.ti -1c
.RI "\fBCFF_FDSelectRec\fP \fBfd_select\fP"
.br
.ti -1c
.RI "\fBPSHinter_Service\fP \fBpshinter\fP"
.br
.ti -1c
.RI "FT_Service_PsCMaps \fBpsnames\fP"
.br
.ti -1c
.RI "PS_FontInfoRec * \fBfont_info\fP"
.br
.ti -1c
.RI "FT_String * \fBregistry\fP"
.br
.ti -1c
.RI "FT_String * \fBordering\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBcf2_instance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 219 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
