.TH "CFF_ParserRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_ParserRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Library\fP \fBlibrary\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstart\fP"
.br
.ti -1c
.RI "FT_Byte * \fBlimit\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcursor\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstack\fP [CFF_MAX_STACK_DEPTH+1]"
.br
.ti -1c
.RI "FT_Byte ** \fBtop\fP"
.br
.ti -1c
.RI "FT_UInt \fBobject_code\fP"
.br
.ti -1c
.RI "void * \fBobject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file cffparse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
