.TH "CFF_Decoder_Zone_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Decoder_Zone_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte * \fBbase\fP"
.br
.ti -1c
.RI "FT_Byte * \fBlimit\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcursor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 151 of file cffgload\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
