.TH "CFF_Field_Handler_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Field_Handler_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkind\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "FT_UInt \fBoffset\fP"
.br
.ti -1c
.RI "FT_Byte \fBsize\fP"
.br
.ti -1c
.RI "CFF_Field_Reader \fBreader\fP"
.br
.ti -1c
.RI "FT_UInt \fBarray_max\fP"
.br
.ti -1c
.RI "FT_UInt \fBcount_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file cffparse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
