.TH "CFF_FontRecDictRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_FontRecDictRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBversion\fP"
.br
.ti -1c
.RI "FT_UInt \fBnotice\fP"
.br
.ti -1c
.RI "FT_UInt \fBcopyright\fP"
.br
.ti -1c
.RI "FT_UInt \fBfull_name\fP"
.br
.ti -1c
.RI "FT_UInt \fBfamily_name\fP"
.br
.ti -1c
.RI "FT_UInt \fBweight\fP"
.br
.ti -1c
.RI "FT_Bool \fBis_fixed_pitch\fP"
.br
.ti -1c
.RI "FT_Fixed \fBitalic_angle\fP"
.br
.ti -1c
.RI "FT_Fixed \fBunderline_position\fP"
.br
.ti -1c
.RI "FT_Fixed \fBunderline_thickness\fP"
.br
.ti -1c
.RI "FT_Int \fBpaint_type\fP"
.br
.ti -1c
.RI "FT_Int \fBcharstring_type\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBfont_matrix\fP"
.br
.ti -1c
.RI "FT_Bool \fBhas_font_matrix\fP"
.br
.ti -1c
.RI "FT_ULong \fBunits_per_em\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfont_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBunique_id\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBfont_bbox\fP"
.br
.ti -1c
.RI "FT_Pos \fBstroke_width\fP"
.br
.ti -1c
.RI "FT_ULong \fBcharset_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBencoding_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBcharstrings_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBprivate_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBprivate_size\fP"
.br
.ti -1c
.RI "FT_Long \fBsynthetic_base\fP"
.br
.ti -1c
.RI "FT_UInt \fBembedded_postscript\fP"
.br
.ti -1c
.RI "FT_UInt \fBcid_registry\fP"
.br
.ti -1c
.RI "FT_UInt \fBcid_ordering\fP"
.br
.ti -1c
.RI "FT_Long \fBcid_supplement\fP"
.br
.ti -1c
.RI "FT_Long \fBcid_font_version\fP"
.br
.ti -1c
.RI "FT_Long \fBcid_font_revision\fP"
.br
.ti -1c
.RI "FT_Long \fBcid_font_type\fP"
.br
.ti -1c
.RI "FT_ULong \fBcid_count\fP"
.br
.ti -1c
.RI "FT_ULong \fBcid_uid_base\fP"
.br
.ti -1c
.RI "FT_ULong \fBcid_fd_array_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBcid_fd_select_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBcid_font_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 105 of file cfftypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
