.TH "CFF_InternalRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_InternalRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PSH_Globals \fBtopfont\fP"
.br
.ti -1c
.RI "PSH_Globals \fBsubfonts\fP [CFF_MAX_CID_FONTS]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file cffobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
