.TH "Channel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Channel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannel\fP (\fBZerberus\fP *, int idx)"
.br
.ti -1c
.RI "void \fBpitchBend\fP (int)"
.br
.ti -1c
.RI "void \fBcontroller\fP (int ctrl, int val)"
.br
.ti -1c
.RI "\fBZInstrument\fP * \fBinstrument\fP () const"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (\fBZInstrument\fP *i)"
.br
.ti -1c
.RI "\fBZerberus\fP * \fBmsynth\fP () const"
.br
.ti -1c
.RI "int \fBsustain\fP () const"
.br
.ti -1c
.RI "float \fBgain\fP () const"
.br
.ti -1c
.RI "float \fBpanLeftGain\fP () const"
.br
.ti -1c
.RI "float \fBpanRightGain\fP () const"
.br
.ti -1c
.RI "int \fBidx\fP () const"
.br
.ti -1c
.RI "int \fBgetCtrl\fP (int CTRL) const"
.br
.ti -1c
.RI "void \fBresetCC\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file channel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
