.TH "CharCodeToUnicode" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharCodeToUnicode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBmergeCMap\fP (\fBGooString\fP *buf, int nBits)"
.br
.ti -1c
.RI "void \fBincRefCnt\fP ()"
.br
.ti -1c
.RI "void \fBdecRefCnt\fP ()"
.br
.ti -1c
.RI "GBool \fBmatch\fP (\fBGooString\fP *tagA)"
.br
.ti -1c
.RI "void \fBsetMapping\fP (CharCode c, Unicode *u, int len)"
.br
.ti -1c
.RI "int \fBmapToUnicode\fP (CharCode c, Unicode **u)"
.br
.ti -1c
.RI "int \fBmapToCharCode\fP (Unicode *u, CharCode *c, int usize)"
.br
.ti -1c
.RI "CharCode \fBgetLength\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBmakeIdentityMapping\fP ()"
.br
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBparseCIDToUnicode\fP (\fBGooString\fP *fileName, \fBGooString\fP *collection)"
.br
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBparseUnicodeToUnicode\fP (\fBGooString\fP *fileName)"
.br
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBmake8BitToUnicode\fP (Unicode *toUnicode)"
.br
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBparseCMap\fP (\fBGooString\fP *buf, int nBits)"
.br
.ti -1c
.RI "static \fBCharCodeToUnicode\fP * \fBparseCMapFromFile\fP (\fBGooString\fP *fileName, int nBits)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBUnicodeToCharCode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file CharCodeToUnicode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
