.TH "libmscore/chord.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/chord.h
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include 'chordrest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::Chord\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTremoloChordType\fP : char { \fBTremoloSingle\fP, \fBTremoloFirstNote\fP, \fBTremoloSecondNote\fP }"
.br
.ti -1c
.RI "enum \fBPlayEventType\fP : char { \fBAuto\fP, \fBUser\fP, \fBInvalidUser\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of classes Chord, HelpLine and NoteList\&. 
.PP
Definition in file \fBchord\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
