.TH "CID_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CID_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "void * \fBpsnames\fP"
.br
.ti -1c
.RI "void * \fBpsaux\fP"
.br
.ti -1c
.RI "\fBCID_FaceInfoRec\fP \fBcid\fP"
.br
.ti -1c
.RI "\fBPS_FontExtraRec\fP \fBfont_extra\fP"
.br
.ti -1c
.RI "\fBCID_Subrs\fP \fBsubrs\fP"
.br
.ti -1c
.RI "void * \fBpshinter\fP"
.br
.ti -1c
.RI "FT_Byte * \fBbinary_data\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBcid_stream\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 228 of file t1types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
