.TH "CID_Parser_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CID_Parser_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPS_ParserRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "FT_Byte * \fBpostscript\fP"
.br
.ti -1c
.RI "FT_ULong \fBpostscript_len\fP"
.br
.ti -1c
.RI "FT_ULong \fBdata_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBbinary_length\fP"
.br
.ti -1c
.RI "\fBCID_FaceInfo\fP \fBcid\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_dict\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file cidparse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
