.TH "libmscore/clef.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/clef.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br
\fC#include 'mscore\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMs::ClefTypeList\fP"
.br
.ti -1c
.RI "class \fBMs::ClefInfo\fP"
.br
.RI "Info about a clef\&. "
.ti -1c
.RI "class \fBMs::Clef\fP"
.br
.RI "Graphic representation of a clef\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBClefType\fP : signed char { \fBINVALID\fP = -1, \fBG\fP = 0, \fBG15_MB\fP, \fBG8_VB\fP, \fBG8_VA\fP, \fBG15_MA\fP, \fBG8_VB_O\fP, \fBG8_VB_P\fP, \fBG_1\fP, \fBC1\fP, \fBC2\fP, \fBC3\fP, \fBC4\fP, \fBC5\fP, \fBC_19C\fP, \fBC3_F18C\fP, \fBC4_F18C\fP, \fBC3_F20C\fP, \fBC4_F20C\fP, \fBF\fP, \fBF15_MB\fP, \fBF8_VB\fP, \fBF_8VA\fP, \fBF_15MA\fP, \fBF_B\fP, \fBF_C\fP, \fBF_F18C\fP, \fBF_19C\fP, \fBPERC\fP, \fBPERC2\fP, \fBTAB\fP, \fBTAB4\fP, \fBTAB_SERIF\fP, \fBTAB4_SERIF\fP, \fBMAX\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of classes Clef 
.PP
Definition in file \fBclef\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
