.TH "libmscore/clef.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/clef.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'clef\&.h'\fP
.br
\fC#include 'measure\&.h'\fP
.br
\fC#include 'ambitus\&.h'\fP
.br
\fC#include 'xml\&.h'\fP
.br
\fC#include 'sym\&.h'\fP
.br
\fC#include 'symbol\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'score\&.h'\fP
.br
\fC#include 'staff\&.h'\fP
.br
\fC#include 'segment\&.h'\fP
.br
\fC#include 'stafftype\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTR\fP(a)   QT_TRANSLATE_NOOP('clefTable', a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of classes Clef (partial) and ClefList (complete)\&. 
.PP
Definition in file \fBclef\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
