.TH "CMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMap
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBincRefCnt\fP ()"
.br
.ti -1c
.RI "void \fBdecRefCnt\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetCollection\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetCMapName\fP ()"
.br
.ti -1c
.RI "GBool \fBmatch\fP (\fBGooString\fP *collectionA, \fBGooString\fP *cMapNameA)"
.br
.ti -1c
.RI "CID \fBgetCID\fP (char *s, int len, CharCode *c, int *nUsed)"
.br
.ti -1c
.RI "int \fBgetWMode\fP ()"
.br
.ti -1c
.RI "void \fBsetReverseMap\fP (Guint *rmap, Guint rmapSize, Guint ncand)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCMap\fP * \fBparse\fP (\fBCMapCache\fP *cache, \fBGooString\fP *collectionA, \fBObject\fP *obj)"
.br
.ti -1c
.RI "static \fBCMap\fP * \fBparse\fP (\fBCMapCache\fP *cache, \fBGooString\fP *collectionA, \fBGooString\fP *cMapNameA)"
.br
.ti -1c
.RI "static \fBCMap\fP * \fBparse\fP (\fBCMapCache\fP *cache, \fBGooString\fP *collectionA, \fBStream\fP *str)"
.br
.ti -1c
.RI "static \fBCMap\fP * \fBparse\fP (\fBCMapCache\fP *cache, \fBGooString\fP *collectionA, \fBGooString\fP *cMapNameA, \fBStream\fP *stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file CMap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
