.TH "CMapVectorEntry" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMapVectorEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBisVector\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBCMapVectorEntry\fP * \fBvector\fP"
.br
.ti -1c
.RI "   CID \fBcid\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file CMap\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
