.TH "CMapCache" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMapCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMap\fP * \fBgetCMap\fP (\fBGooString\fP *collection, \fBGooString\fP *cMapName, \fBStream\fP *stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file CMap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
