.TH "cmpTrueTypeTableTagFunctor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmpTrueTypeTableTagFunctor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTrueTypeTable\fP &tab1, const \fBTrueTypeTable\fP &tab2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file FoFiTrueType\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
