.TH "cmpTrueTypeLocaIdxFunctor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmpTrueTypeLocaIdxFunctor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTrueTypeLoca\fP &loca1, const \fBTrueTypeLoca\fP &loca2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file FoFiTrueType\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
