.TH "cmpWidthExcepFunctor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmpWidthExcepFunctor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBGfxFontCIDWidthExcep\fP &w1, const \fBGfxFontCIDWidthExcep\fP &w2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1829 of file GfxFont\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
