.TH "ColorSchemePrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorSchemePrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorSchemePrivate\fP (QPalette::ColorGroup, const char *, \fBSetDefaultColors\fP)"
.br
.ti -1c
.RI "\fBColorSchemePrivate\fP (QPalette::ColorGroup, const char *, \fBSetDefaultColors\fP, const QBrush &)"
.br
.ti -1c
.RI "QBrush \fBbackground\fP (\fBColorScheme::BackgroundRole\fP) const"
.br
.ti -1c
.RI "QBrush \fBforeground\fP (\fBColorScheme::ForegroundRole\fP) const"
.br
.ti -1c
.RI "QBrush \fBdecoration\fP (\fBColorScheme::DecorationRole\fP) const"
.br
.ti -1c
.RI "qreal \fBcontrast\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 241 of file colorscheme\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
