.TH "ColorUtils" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QColor \fBtint\fP (const QColor &, const QColor &, qreal amount=\&.3)"
.br
.ti -1c
.RI "static QColor \fBmix\fP (const QColor &, const QColor &, qreal bias=\&.5)"
.br
.ti -1c
.RI "static qreal \fBluma\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "static QColor \fBshade\fP (const QColor &, qreal lumaAmount, qreal chromaAmount=0\&.0)"
.br
.ti -1c
.RI "static QColor \fBdarken\fP (const QColor &, qreal amount=0\&.5, qreal chromaGain=1\&.0)"
.br
.ti -1c
.RI "static QColor \fBlighten\fP (const QColor &, qreal amount=0\&.5, qreal chromaInverseGain=1\&.0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file colorutils\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
