.TH "color" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBcolor\fP &clr)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBcolor\fP &clr)"
.br
.ti -1c
.RI "\fBcolor\fP & \fBoperator=\fP (const \fBcolor\fP &clr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBg\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file fmt_opts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
