.TH "ComboBoxData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComboBoxData \- generic data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comboboxdata\&.h>\fP
.PP
Inherits \fBTransitionData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComboBoxData\fP (QObject *, QComboBox *, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~ComboBoxData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.RI "event filter "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBindexChanged\fP (void)"
.br
.RI "triggered when item is activated in combobox "
.ti -1c
.RI "virtual bool \fBinitializeAnimation\fP (void)"
.br
.RI "initialize animation "
.ti -1c
.RI "virtual bool \fBanimate\fP (void)"
.br
.RI "animate "
.ti -1c
.RI "virtual void \fBtargetDestroyed\fP (void)"
.br
.RI "called when target is destroyed "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBtimerEvent\fP (QTimerEvent *)"
.br
.RI "timer event "
.ti -1c
.RI "QRect \fBtargetRect\fP (void) const"
.br
.RI "target rect "
.in -1c
.SH "Detailed Description"
.PP 
generic data 
.PP
Definition at line 33 of file comboboxdata\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QRect ComboBoxData::targetRect (void) const\fC [inline]\fP, \fC [protected]\fP"

.PP
target rect return rect corresponding to the area to be updated when animating 
.PP
Definition at line 56 of file comboboxdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
