.TH "Comb" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comb
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetbuffer\fP (int size)"
.br
.ti -1c
.RI "void \fBsetdamp\fP (float val)"
.br
.ti -1c
.RI "float \fBgetdamp\fP () const"
.br
.ti -1c
.RI "void \fBsetfeedback\fP (float val)"
.br
.ti -1c
.RI "float \fBgetfeedback\fP () const"
.br
.ti -1c
.RI "float \fBprocess\fP (float input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file freeverb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
