.TH "conf_method_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conf_method_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBCONF\fP *(* \fBcreate\fP )(\fBCONF_METHOD\fP *meth)"
.br
.ti -1c
.RI "int(* \fBinit\fP )(\fBCONF\fP *conf)"
.br
.ti -1c
.RI "int(* \fBdestroy\fP )(\fBCONF\fP *conf)"
.br
.ti -1c
.RI "int(* \fBdestroy_data\fP )(\fBCONF\fP *conf)"
.br
.ti -1c
.RI "int(* \fBload_bio\fP )(\fBCONF\fP *conf, \fBBIO\fP *bp, long *eline)"
.br
.ti -1c
.RI "int(* \fBdump\fP )(const \fBCONF\fP *conf, \fBBIO\fP *bp)"
.br
.ti -1c
.RI "int(* \fBis_number\fP )(const \fBCONF\fP *conf, char c)"
.br
.ti -1c
.RI "int(* \fBto_int\fP )(const \fBCONF\fP *conf, char c)"
.br
.ti -1c
.RI "int(* \fBload\fP )(\fBCONF\fP *conf, const char *name, long *eline)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file conf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
