.TH "content.DocBlock" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocBlock \- DOC BLOCK CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, source, follow, processor)"
.br
.ti -1c
.RI "def \fBlocation\fP (self)"
.br
.ti -1c
.RI "def \fBget_markup\fP (self, tag_name)"
.br
.ti -1c
.RI "def \fBget_markup_words\fP (self, tag_name)"
.br
.ti -1c
.RI "def \fBget_markup_words_all\fP (self, tag_name)"
.br
.ti -1c
.RI "def \fBget_markup_text\fP (self, tag_name)"
.br
.ti -1c
.RI "def \fBget_markup_items\fP (self, tag_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsource\fP"
.br
.ti -1c
.RI "\fBcode\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBsection\fP"
.br
.ti -1c
.RI "\fBmarkups\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC BLOCK CLASS\&. 
.PP
Definition at line 523 of file content\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def content\&.DocBlock\&.get_markup ( self,  tag_name)"

.PP
.nf
Return the DocMarkup corresponding to a given tag in a block.
.fi
.PP
 
.PP
Definition at line 598 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
