.TH "content.ContentProcessor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.ContentProcessor \- CONTENT PROCESSOR CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBset_section\fP (self, section_name)"
.br
.ti -1c
.RI "def \fBadd_chapter\fP (self, block)"
.br
.ti -1c
.RI "def \fBreset\fP (self)"
.br
.ti -1c
.RI "def \fBadd_markup\fP (self)"
.br
.ti -1c
.RI "def \fBprocess_content\fP (self, content)"
.br
.ti -1c
.RI "def \fBparse_sources\fP (self, source_processor)"
.br
.ti -1c
.RI "def \fBfinish\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsections\fP"
.br
.ti -1c
.RI "\fBsection\fP"
.br
.ti -1c
.RI "\fBchapters\fP"
.br
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBmarkups\fP"
.br
.ti -1c
.RI "\fBmarkup\fP"
.br
.ti -1c
.RI "\fBmarkup_lines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CONTENT PROCESSOR CLASS\&. 
.PP
Definition at line 384 of file content\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def content\&.ContentProcessor\&.__init__ ( self)"

.PP
.nf
Initialize a block content processor.
.fi
.PP
 
.PP
Definition at line 386 of file content\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def content\&.ContentProcessor\&.add_markup ( self)"

.PP
.nf
Add a new markup section.
.fi
.PP
 
.PP
Definition at line 416 of file content\&.py\&.
.SS "def content\&.ContentProcessor\&.process_content ( self,  content)"

.PP
.nf
Process a block content and return a list of DocMarkup objects
   corresponding to it.
.fi
.PP
 
.PP
Definition at line 432 of file content\&.py\&.
.SS "def content\&.ContentProcessor\&.reset ( self)"

.PP
.nf
Reset the content processor for a new block.
.fi
.PP
 
.PP
Definition at line 410 of file content\&.py\&.
.SS "def content\&.ContentProcessor\&.set_section ( self,  section_name)"

.PP
.nf
Set current section during parsing.
.fi
.PP
 
.PP
Definition at line 397 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
