.TH "content.DocMarkup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocMarkup \- DOC MARKUP CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, tag, lines)"
.br
.ti -1c
.RI "def \fBget_name\fP (self)"
.br
.ti -1c
.RI "def \fBdump\fP (self, margin)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtag\fP"
.br
.ti -1c
.RI "\fBfields\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC MARKUP CLASS\&. 
.PP
Definition at line 276 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
