.TH "content.DocSection" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocSection \- DOC SECTION CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, name='Other')"
.br
.ti -1c
.RI "def \fBadd_def\fP (self, block)"
.br
.ti -1c
.RI "def \fBadd_block\fP (self, block)"
.br
.ti -1c
.RI "def \fBprocess\fP (self)"
.br
.ti -1c
.RI "def \fBreorder\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBblocks\fP"
.br
.ti -1c
.RI "\fBblock_names\fP"
.br
.ti -1c
.RI "\fBdefs\fP"
.br
.ti -1c
.RI "\fBabstract\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBorder\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBchapter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC SECTION CLASS\&. 
.PP
Definition at line 345 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
