.TH "content.DocPara" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocPara \- DOC PARA CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, lines)"
.br
.ti -1c
.RI "def \fBdump\fP (self, prefix='', width=60)"
.br
.ti -1c
.RI "def \fBdump_lines\fP (self, margin=0, width=60)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlines\fP"
.br
.ti -1c
.RI "\fBwords\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC PARA CLASS\&. 

`Normal' text paragraphs are stored in the `DocPara' class\&.
.PP
`self\&.words' contains the list of words that make up the paragraph\&. 
.PP
Definition at line 113 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
