.TH "content.DocCode" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocCode \- DOC CODE CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, margin, lines)"
.br
.ti -1c
.RI "def \fBdump\fP (self, prefix='', width=60)"
.br
.ti -1c
.RI "def \fBdump_lines\fP (self, margin=0, width=60)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlines\fP"
.br
.ti -1c
.RI "\fBwords\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC CODE CLASS\&. 

The `DocCode' class is used to store source code lines\&.
.PP
`self\&.lines' contains a set of source code lines that will be dumped as HTML in a 
.PP
.nf
 tag\&.
.fi
.PP
.PP
.PP
.nf
  The object is filled line by line by the parser; it strips the leading
  `margin' space from each input line before storing it in `self\&.lines'\&.
.fi
.PP

.PP
Definition at line 80 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
