.TH "content.DocField" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content.DocField \- DOC FIELD CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, name, lines)"
.br
.ti -1c
.RI "def \fBdump\fP (self, prefix='')"
.br
.ti -1c
.RI "def \fBdump_lines\fP (self, margin=0, width=60)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBitems\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DOC FIELD CLASS\&. 

The `DocField' class stores a list containing either `DocPara' or `DocCode' objects\&. Each \fBDocField\fP object also has an optional `name' that is used when the object corresponds to a field or value definition\&. 
.PP
Definition at line 161 of file content\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
