.TH "CurlCachedFileLoader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CurlCachedFileLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCachedFileLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBinit\fP (\fBGooString\fP *url, \fBCachedFile\fP *cachedFile)"
.br
.ti -1c
.RI "int \fBload\fP (const std::vector< \fBByteRange\fP > &ranges, \fBCachedFileWriter\fP *writer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file CurlCachedFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
