.TH "DataMap< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataMap< T > \- standard data map, using QObject as a key  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datamap\&.h>\fP
.PP
Inherits \fBBaseDataMap< QObject, T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataMap\fP (void)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~DataMap\fP (void)"
.br
.RI "destructor "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class DataMap< T >"
standard data map, using QObject as a key 
.PP
Definition at line 130 of file datamap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
