.TH "dbg_iter< std::istreambuf_iterator< T > >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbg_iter< std::istreambuf_iterator< T > >
.SH SYNOPSIS
.br
.PP
.PP
Inherits istreambuf_iterator< T >, and \fBdbg_iter_mixin< std::istreambuf_iterator< T > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdbg_iter\fP (std::basic_streambuf< T > *buf)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class dbg_iter< std::istreambuf_iterator< T > >"

.PP
Definition at line 40 of file dbg_iter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
