.TH "DCTScanInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DCTScanInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBcomp\fP [4]"
.br
.ti -1c
.RI "int \fBnumComps\fP"
.br
.ti -1c
.RI "int \fBdcHuffTable\fP [4]"
.br
.ti -1c
.RI "int \fBacHuffTable\fP [4]"
.br
.ti -1c
.RI "int \fBfirstCoeff\fP"
.br
.ti -1c
.RI "int \fBlastCoeff\fP"
.br
.ti -1c
.RI "int \fBah\fP"
.br
.ti -1c
.RI "int \fBal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 849 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
