.TH "DecoDefaultColors" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecoDefaultColors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBHover\fP [3]"
.br
.ti -1c
.RI "int \fBFocus\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 158 of file colorscheme\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
