.TH "Decrypt" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Decrypt
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GBool \fBmakeFileKey\fP (int encVersion, int encRevision, int keyLength, \fBGooString\fP *ownerKey, \fBGooString\fP *userKey, \fBGooString\fP *ownerEnc, \fBGooString\fP *userEnc, int permissions, \fBGooString\fP *fileID, \fBGooString\fP *ownerPassword, \fBGooString\fP *userPassword, Guchar *fileKey, GBool encryptMetadata, GBool *ownerPasswordOk)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file Decrypt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
