.TH "deprecated" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecatedDeprecated List 
 \- 
.IP "\fBMember \fBdiff_match_patch::patch_make\fP (const QString &text1, const QString &text2, const QList< Diff > &diffs)\fP" 1c
Prefer \fBpatch_make(const QString &text1, const QList<Diff> &diffs)\fP\&.  
.IP "\fBMember \fBPoppler::PageTransition::duration\fP () const\fP" 1c
This function is left for backward compatibility, use \fBdurationReal()\fP instead\&. 
.PP

