.TH "descriptor_node" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
descriptor_node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPmDeviceInfo\fP \fBpub\fP"
.br
.ti -1c
.RI "void * \fBdescriptor\fP"
.br
.ti -1c
.RI "void * \fBinternalDescriptor\fP"
.br
.ti -1c
.RI "\fBpm_fns_type\fP \fBdictionary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file pminternal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
