.TH "dh_method" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dh_method
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBgenerate_key\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBcompute_key\fP )(unsigned char *key, const \fBBIGNUM\fP *pub_key, \fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBbn_mod_exp\fP )(const \fBDH\fP *dh, \fBBIGNUM\fP *r, const \fBBIGNUM\fP *a, const \fBBIGNUM\fP *p, const \fBBIGNUM\fP *m, BN_CTX *ctx, \fBBN_MONT_CTX\fP *m_ctx)"
.br
.ti -1c
.RI "int(* \fBinit\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBfinish\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBapp_data\fP"
.br
.ti -1c
.RI "int(* \fBgenerate_params\fP )(\fBDH\fP *dh, int prime_len, int generator, \fBBN_GENCB\fP *cb)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file dh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
