.TH "Dict" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dict
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDict\fP (\fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "\fBDict\fP (\fBDict\fP *dictA)"
.br
.ti -1c
.RI "\fBDict\fP * \fBcopy\fP (\fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "int \fBincRef\fP ()"
.br
.ti -1c
.RI "int \fBdecRef\fP ()"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (char *key, \fBObject\fP *val)"
.br
.ti -1c
.RI "void \fBset\fP (const char *key, \fBObject\fP *val)"
.br
.ti -1c
.RI "void \fBremove\fP (const char *key)"
.br
.ti -1c
.RI "GBool \fBis\fP (const char *type)"
.br
.ti -1c
.RI "\fBObject\fP * \fBlookup\fP (const char *key, \fBObject\fP *obj, int recursion=0)"
.br
.ti -1c
.RI "\fBObject\fP * \fBlookupNF\fP (const char *key, \fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBlookupInt\fP (const char *key, const char *alt_key, int *value)"
.br
.ti -1c
.RI "char * \fBgetKey\fP (int i)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetVal\fP (int i, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetValNF\fP (int i, \fBObject\fP *obj)"
.br
.ti -1c
.RI "void \fBsetXRef\fP (\fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "\fBXRef\fP * \fBgetXRef\fP ()"
.br
.ti -1c
.RI "GBool \fBhasKey\fP (const char *key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file Dict\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
