.TH "diff_match_patch_test" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diff_match_patch_test
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun_all_tests\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCommonPrefix\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCommonSuffix\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCommonOverlap\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffHalfmatch\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffLinesToChars\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCharsToLines\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCleanupMerge\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCleanupSemanticLossless\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCleanupSemantic\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffCleanupEfficiency\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffPrettyHtml\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffText\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffDelta\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffXIndex\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffLevenshtein\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffBisect\fP ()"
.br
.ti -1c
.RI "void \fBtestDiffMain\fP ()"
.br
.ti -1c
.RI "void \fBtestMatchAlphabet\fP ()"
.br
.ti -1c
.RI "void \fBtestMatchBitap\fP ()"
.br
.ti -1c
.RI "void \fBtestMatchMain\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchObj\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchFromText\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchToText\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchAddContext\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchMake\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchSplitMax\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchAddPadding\fP ()"
.br
.ti -1c
.RI "void \fBtestPatchApply\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file diff_match_patch_test\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
