.TH "Division" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Division
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDivision\fP (\fBAsection\fP *asect, float fsam)"
.br
.ti -1c
.RI "void \fBset_rank\fP (int ind, \fBRankwave\fP *W, int pan, int del)"
.br
.ti -1c
.RI "void \fBset_swell\fP (float stat)"
.br
.ti -1c
.RI "void \fBset_tfreq\fP (float freq)"
.br
.ti -1c
.RI "void \fBset_tmodd\fP (float modd)"
.br
.ti -1c
.RI "void \fBset_div_mask\fP (int bits)"
.br
.ti -1c
.RI "void \fBclr_div_mask\fP (int bits)"
.br
.ti -1c
.RI "void \fBset_rank_mask\fP (int ind, int bits)"
.br
.ti -1c
.RI "void \fBclr_rank_mask\fP (int ind, int bits)"
.br
.ti -1c
.RI "void \fBtrem_on\fP ()"
.br
.ti -1c
.RI "void \fBtrem_off\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (int note, int mask)"
.br
.ti -1c
.RI "void \fBupdate\fP (unsigned char *keys)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file division\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
