.TH "Divis" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Divis
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHAS_SWELL\fP = 1, \fBHAS_TREM\fP = 2, \fBNRANK\fP = 32 }"
.br
.ti -1c
.RI "enum { \fBSWELL\fP, \fBTFREQ\fP, \fBTMODD\fP, \fBNPARAM\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fB_label\fP [16]"
.br
.ti -1c
.RI "int \fB_flags\fP"
.br
.ti -1c
.RI "int \fB_dmask\fP"
.br
.ti -1c
.RI "int \fB_nrank\fP"
.br
.ti -1c
.RI "int \fB_asect\fP"
.br
.ti -1c
.RI "int \fB_keybd\fP"
.br
.ti -1c
.RI "\fBSyntiParameter\fP \fB_param\fP [NPARAM]"
.br
.ti -1c
.RI "\fBRank\fP \fB_ranks\fP [NRANK]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file model\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
