.TH "DockSeparatorEngine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DockSeparatorEngine \- stores dockseparator hovered action and timeLine  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dockseparatorengine\&.h>\fP
.PP
Inherits \fBBaseEngine\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBunregisterWidget\fP (QObject *object)"
.br
.RI "remove widget from map "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDockSeparatorEngine\fP (QObject *parent)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~DockSeparatorEngine\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBregisterWidget\fP (QWidget *)"
.br
.RI "register dockseparator "
.ti -1c
.RI "virtual void \fBupdateRect\fP (const QObject *object, const QRect &r, const Qt::Orientation orientation, bool hovered)"
.br
.RI "update rect and hover value for data matching widget "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (const QObject *object, const QRect &r, const Qt::Orientation orientation)"
.br
.RI "returns true if object is animated "
.ti -1c
.RI "virtual qreal \fBopacity\fP (const QObject *object, const Qt::Orientation orientation)"
.br
.RI "returns true if object is animated "
.ti -1c
.RI "virtual void \fBsetEnabled\fP (bool value)"
.br
.RI "enability "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int value)"
.br
.RI "duration "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
stores dockseparator hovered action and timeLine 
.PP
Definition at line 35 of file dockseparatorengine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
