.TH "dso_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dso_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (void) *meth_data"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDSO_METHOD\fP * \fBmeth\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.ti -1c
.RI "DSO_NAME_CONVERTER_FUNC \fBname_converter\fP"
.br
.ti -1c
.RI "DSO_MERGER_FUNC \fBmerger\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBloaded_filename\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 183 of file dso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
