.TH "dtls1_state_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtls1_state_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsend_cookie\fP"
.br
.ti -1c
.RI "unsigned char \fBcookie\fP [DTLS1_COOKIE_LENGTH]"
.br
.ti -1c
.RI "unsigned char \fBrcvd_cookie\fP [DTLS1_COOKIE_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBcookie_len\fP"
.br
.ti -1c
.RI "unsigned short \fBr_epoch\fP"
.br
.ti -1c
.RI "unsigned short \fBw_epoch\fP"
.br
.ti -1c
.RI "\fBDTLS1_BITMAP\fP \fBbitmap\fP"
.br
.ti -1c
.RI "\fBDTLS1_BITMAP\fP \fBnext_bitmap\fP"
.br
.ti -1c
.RI "unsigned short \fBhandshake_write_seq\fP"
.br
.ti -1c
.RI "unsigned short \fBnext_handshake_write_seq\fP"
.br
.ti -1c
.RI "unsigned short \fBhandshake_read_seq\fP"
.br
.ti -1c
.RI "unsigned char \fBlast_write_sequence\fP [8]"
.br
.ti -1c
.RI "\fBrecord_pqueue\fP \fBunprocessed_rcds\fP"
.br
.ti -1c
.RI "\fBrecord_pqueue\fP \fBprocessed_rcds\fP"
.br
.ti -1c
.RI "pqueue \fBbuffered_messages\fP"
.br
.ti -1c
.RI "pqueue \fBsent_messages\fP"
.br
.ti -1c
.RI "\fBrecord_pqueue\fP \fBbuffered_app_data\fP"
.br
.ti -1c
.RI "unsigned int \fBlisten\fP"
.br
.ti -1c
.RI "unsigned int \fBmtu\fP"
.br
.ti -1c
.RI "struct \fBhm_header_st\fP \fBw_msg_hdr\fP"
.br
.ti -1c
.RI "struct \fBhm_header_st\fP \fBr_msg_hdr\fP"
.br
.ti -1c
.RI "struct \fBdtls1_timeout_st\fP \fBtimeout\fP"
.br
.ti -1c
.RI "struct timeval \fBnext_timeout\fP"
.br
.ti -1c
.RI "unsigned short \fBtimeout_duration\fP"
.br
.ti -1c
.RI "unsigned char \fBalert_fragment\fP [DTLS1_AL_HEADER_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBalert_fragment_len\fP"
.br
.ti -1c
.RI "unsigned char \fBhandshake_fragment\fP [DTLS1_HM_HEADER_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBhandshake_fragment_len\fP"
.br
.ti -1c
.RI "unsigned int \fBretransmitting\fP"
.br
.ti -1c
.RI "unsigned int \fBchange_cipher_spec_ok\fP"
.br
.ti -1c
.RI "int \fBnext_state\fP"
.br
.ti -1c
.RI "int \fBshutdown_received\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
