.TH "dtls1_bitmap_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtls1_bitmap_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBmap\fP"
.br
.ti -1c
.RI "unsigned char \fBmax_seq_num\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 120 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
