.TH "EmbFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmbFile\fP (\fBObject\fP *efStream)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBmodDate\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBcreateDate\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBchecksum\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBmimeType\fP ()"
.br
.ti -1c
.RI "\fBStream\fP * \fBstream\fP ()"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "GBool \fBsave\fP (const char *path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file FileSpec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
