.TH "EnableData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnableData \- Enable data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enabledata\&.h>\fP
.PP
Inherits \fBWidgetStateData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnableData\fP (QObject *parent, QWidget *target, int duration, bool state=true)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~EnableData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.RI "event filter "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Enable data\&. 
.PP
Definition at line 33 of file enabledata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
