.TH "EndOfDirectory" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EndOfDirectory
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uchar \fBsignature\fP [4]"
.br
.ti -1c
.RI "uchar \fBthis_disk\fP [2]"
.br
.ti -1c
.RI "uchar \fBstart_of_directory_disk\fP [2]"
.br
.ti -1c
.RI "uchar \fBnum_dir_entries_this_disk\fP [2]"
.br
.ti -1c
.RI "uchar \fBnum_dir_entries\fP [2]"
.br
.ti -1c
.RI "uchar \fBdirectory_size\fP [4]"
.br
.ti -1c
.RI "uchar \fBdir_start_offset\fP [4]"
.br
.ti -1c
.RI "uchar \fBcomment_length\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 345 of file qzip\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
