.TH "Envelope" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Envelope
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTable\fP (float *f)"
.br
.ti -1c
.RI "bool \fBstep\fP ()"
.br
.ti -1c
.RI "void \fBsetTime\fP (float ms, int sampleRate)"
.br
.ti -1c
.RI "void \fBsetConstant\fP (float v)"
.br
.ti -1c
.RI "void \fBsetVariable\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsteps\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "bool \fBconstant\fP = false"
.br
.ti -1c
.RI "float \fBoffset\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBmax\fP = 1\&.0"
.br
.ti -1c
.RI "float \fBval\fP"
.br
.ti -1c
.RI "float * \fBtable\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fBegPow\fP [EG_SIZE]"
.br
.ti -1c
.RI "static float \fBegLin\fP [EG_SIZE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file voice\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
