.TH "ERR_string_data_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ERR_string_data_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBerror\fP"
.br
.ti -1c
.RI "const char * \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 313 of file err\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
