.TH "err_state_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err_state_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCRYPTO_THREADID\fP \fBtid\fP"
.br
.ti -1c
.RI "int \fBerr_flags\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "unsigned long \fBerr_buffer\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "char * \fBerr_data\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "int \fBerr_data_flags\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "const char * \fBerr_file\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "int \fBerr_line\fP [ERR_NUM_ERRORS]"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBbottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 148 of file err\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
