.TH "ESS_issuer_serial" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESS_issuer_serial
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBGENERAL_NAME\fP) *issuer"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBserial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 248 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
