.TH "ESS_cert_id" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESS_cert_id
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBhash\fP"
.br
.ti -1c
.RI "\fBESS_ISSUER_SERIAL\fP * \fBissuer_serial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
