.TH "Event" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP (double t, double s)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBEvent\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "double \fBsalience\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
