.TH "evp_pkey_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evp_pkey_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP) *attributes"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBsave_type\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "const EVP_PKEY_ASN1_METHOD * \fBameth\fP"
.br
.ti -1c
.RI "ENGINE * \fBengine\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   struct \fBrsa_st\fP * \fBrsa\fP"
.br
.ti -1c
.RI "   struct \fBdsa_st\fP * \fBdsa\fP"
.br
.ti -1c
.RI "   struct \fBdh_st\fP * \fBdh\fP"
.br
.ti -1c
.RI "   struct ec_key_st * \fBec\fP"
.br
.ti -1c
.RI "} \fBpkey\fP"
.br
.ti -1c
.RI "int \fBsave_parameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file evp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
