.TH "FileOutStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileOutStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileOutStream\fP (FILE *fa, Goffset startA)"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual Goffset \fBgetPos\fP ()"
.br
.ti -1c
.RI "virtual void \fBput\fP (char c)"
.br
.ti -1c
.RI "virtual void \fBprintf\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 279 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
