.TH "FileSpec" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSpec
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileSpec\fP (\fBObject\fP *fileSpec)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFileName\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFileNameForPlatform\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetDescription\fP () const"
.br
.ti -1c
.RI "\fBEmbFile\fP * \fBgetEmbeddedFile\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file FileSpec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
