.TH "FilterStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStream\fP\&.
.PP
Inherited by \fBASCII85Encoder\fP, \fBASCII85Stream\fP, \fBASCIIHexEncoder\fP, \fBASCIIHexStream\fP, \fBBaseCryptStream\fP, \fBBufStream\fP, \fBCCITTFaxStream\fP, \fBCMYKGrayEncoder\fP, \fBDCTStream\fP, \fBDCTStream\fP, \fBDeviceNRecoder\fP, \fBEOFStream\fP, \fBFixedLengthEncoder\fP, \fBFlateEncoder\fP, \fBFlateStream\fP, \fBFlateStream\fP, \fBJBIG2Stream\fP, \fBJPXStream\fP, \fBJPXStream\fP, \fBLZWEncoder\fP, \fBLZWStream\fP, \fBRGBGrayEncoder\fP, \fBRunLengthEncoder\fP, and \fBRunLengthStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterStream\fP (\fBStream\fP *strA)"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual Goffset \fBgetPos\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetPos\fP (Goffset pos, int dir=0)"
.br
.ti -1c
.RI "virtual \fBBaseStream\fP * \fBgetBaseStream\fP ()"
.br
.ti -1c
.RI "virtual \fBStream\fP * \fBgetUndecodedStream\fP ()"
.br
.ti -1c
.RI "virtual \fBDict\fP * \fBgetDict\fP ()"
.br
.ti -1c
.RI "virtual \fBStream\fP * \fBgetNextStream\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetUnfilteredChar\fP ()"
.br
.ti -1c
.RI "virtual void \fBunfilteredReset\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBStream\fP * \fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 337 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
