.TH "FlatFrameShadow" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatFrameShadow \- frame shadow  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <frameshadow\&.h>\fP
.PP
Inherits \fBFrameShadowBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlatFrameShadow\fP (ShadowArea area, \fBStyleHelper\fP &helper)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~FlatFrameShadow\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual void \fBupdateGeometry\fP (void)"
.br
.RI "update geometry "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *)"
.br
.RI "painting "
.in -1c
.SH "Detailed Description"
.PP 
frame shadow 

this allows the shadow to be painted over the widgets viewport 
.PP
Definition at line 225 of file frameshadow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
