.TH "FluidS::Mod" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Mod
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclone\fP (\fBMod\fP *mod) const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "int \fBhas_source\fP (bool cc, int ctrl)"
.br
.ti -1c
.RI "void \fBset_source1\fP (int src, int flags)"
.br
.ti -1c
.RI "void \fBset_source2\fP (int src, int flags)"
.br
.ti -1c
.RI "void \fBset_dest\fP (int val)"
.br
.ti -1c
.RI "void \fBset_amount\fP (double val)"
.br
.ti -1c
.RI "int \fBget_source1\fP () const"
.br
.ti -1c
.RI "int \fBget_flags1\fP () const"
.br
.ti -1c
.RI "int \fBget_source2\fP () const"
.br
.ti -1c
.RI "int \fBget_flags2\fP () const"
.br
.ti -1c
.RI "int \fBget_dest\fP () const"
.br
.ti -1c
.RI "double \fBget_amount\fP () const"
.br
.ti -1c
.RI "float \fBget_value\fP (\fBChannel\fP *chan, \fBVoice\fP *voice)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBdest\fP"
.br
.ti -1c
.RI "unsigned char \fBsrc1\fP"
.br
.ti -1c
.RI "unsigned char \fBflags1\fP"
.br
.ti -1c
.RI "unsigned char \fBsrc2\fP"
.br
.ti -1c
.RI "unsigned char \fBflags2\fP"
.br
.ti -1c
.RI "double \fBamount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 550 of file fluid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
