.TH "FluidS::Preset" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Preset
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreset\fP (\fBSFont\fP *sfont)"
.br
.ti -1c
.RI "QString \fBget_name\fP () const"
.br
.ti -1c
.RI "int \fBget_banknum\fP () const"
.br
.ti -1c
.RI "int \fBget_num\fP () const"
.br
.ti -1c
.RI "bool \fBnoteon\fP (\fBFluid\fP *, unsigned id, int chan, int key, int vel, double nt)"
.br
.ti -1c
.RI "void \fBsetGlobalZone\fP (\fBZone\fP *z)"
.br
.ti -1c
.RI "bool \fBimportSfont\fP ()"
.br
.ti -1c
.RI "\fBZone\fP * \fBglobal_zone\fP ()"
.br
.ti -1c
.RI "void \fBloadSamples\fP ()"
.br
.ti -1c
.RI "QList< \fBZone\fP * > \fBgetZones\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "\fBSFont\fP * \fBsfont\fP"
.br
.ti -1c
.RI "int \fBbank\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBZone\fP * \fB_global_zone\fP"
.br
.ti -1c
.RI "QList< \fBZone\fP * > \fBzones\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file sfont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
