.TH "FluidS::Zone" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Zone
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBimportZone\fP ()"
.br
.ti -1c
.RI "bool \fBinside_range\fP (int key, int vel) const"
.br
.ti -1c
.RI "\fBInstrument\fP * \fBget_inst\fP () const"
.br
.ti -1c
.RI "\fBSample\fP * \fBget_sample\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBSample\fP * \fBsample\fP"
.br
.ti -1c
.RI "   int \fBsampIdx\fP"
.br
.ti -1c
.RI "   \fBInstrument\fP * \fBinstrument\fP"
.br
.ti -1c
.RI "   int \fBinstIdx\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "QList< \fBSFGen\fP * > \fBgen\fP"
.br
.ti -1c
.RI "QList< \fBSFMod\fP * > \fBmod\fP"
.br
.ti -1c
.RI "int \fBkeylo\fP"
.br
.ti -1c
.RI "int \fBkeyhi\fP"
.br
.ti -1c
.RI "int \fBvello\fP"
.br
.ti -1c
.RI "int \fBvelhi\fP"
.br
.ti -1c
.RI "\fBGenerator\fP \fBgenlist\fP [GEN_LAST]"
.br
.ti -1c
.RI "QList< \fBMod\fP * > \fBmodlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file sfont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
