.TH "FluidS::fluid_interp_coeff_t" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::fluid_interp_coeff_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBa0\fP"
.br
.ti -1c
.RI "float \fBa1\fP"
.br
.ti -1c
.RI "float \fBa2\fP"
.br
.ti -1c
.RI "float \fBa3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 524 of file fluid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
