.TH "FluidS::Generator" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Generator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fluid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_mod\fP (double _val)"
.br
.ti -1c
.RI "void \fBset_nrpn\fP (double _val)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBflags\fP"
.br
.ti -1c
.RI "double \fBval\fP"
.br
.ti -1c
.RI "double \fBmod\fP"
.br
.ti -1c
.RI "double \fBnrpn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SoundFont generator structure\&. 
.PP
Definition at line 483 of file fluid\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char FluidS::Generator::flags"
Is the generator set or not (#fluid_gen_flags) 
.PP
Definition at line 485 of file fluid\&.h\&.
.SS "double FluidS::Generator::mod"
Change by modulators 
.PP
Definition at line 487 of file fluid\&.h\&.
.SS "double FluidS::Generator::nrpn"
Change by NRPN messages 
.PP
Definition at line 488 of file fluid\&.h\&.
.SS "double FluidS::Generator::val"
The nominal value 
.PP
Definition at line 486 of file fluid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
