.TH "FluidS::SFont" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::SFont
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSFont\fP (\fBFluid\fP *f)"
.br
.ti -1c
.RI "QString \fBget_name\fP () const"
.br
.ti -1c
.RI "\fBPreset\fP * \fBget_preset\fP (int bank, int prenum)"
.br
.ti -1c
.RI "bool \fBread\fP (const QString &file)"
.br
.ti -1c
.RI "int \fBload_sampledata\fP ()"
.br
.ti -1c
.RI "unsigned int \fBsamplePos\fP () const"
.br
.ti -1c
.RI "int \fBid\fP () const"
.br
.ti -1c
.RI "void \fBsetId\fP (int i)"
.br
.ti -1c
.RI "void \fBsetSamplepos\fP (unsigned v)"
.br
.ti -1c
.RI "void \fBsetSamplesize\fP (unsigned v)"
.br
.ti -1c
.RI "unsigned \fBgetSamplesize\fP () const"
.br
.ti -1c
.RI "const QList< \fBPreset\fP * > \fBgetPresets\fP () const"
.br
.ti -1c
.RI "\fBSFVersion\fP \fBversion\fP () const"
.br
.ti -1c
.RI "int \fBbankOffset\fP () const"
.br
.ti -1c
.RI "void \fBsetBankOffset\fP (int val)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPreset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file sfont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
