.TH "FluidS::Instrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Instrument
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZone\fP * \fBget_global_zone\fP () const"
.br
.ti -1c
.RI "QList< \fBZone\fP * > \fBget_zone\fP ()"
.br
.ti -1c
.RI "bool \fBimport_sfont\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBZone\fP * \fBglobal_zone\fP"
.br
.ti -1c
.RI "QList< \fBZone\fP * > \fBzones\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 199 of file sfont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
