.TH "FluidS::fluid_env_data_t" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::fluid_env_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.ti -1c
.RI "float \fBcoeff\fP"
.br
.ti -1c
.RI "float \fBincr\fP"
.br
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file voice\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
