.TH "FluidS::Channel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Channel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannel\fP (\fBFluid\fP *synth, int num)"
.br
.ti -1c
.RI "bool \fBsustained\fP () const"
.br
.ti -1c
.RI "void \fBsetGen\fP (int n, float v, char a)"
.br
.ti -1c
.RI "float \fBgetGen\fP (int n) const"
.br
.ti -1c
.RI "char \fBgetGenAbs\fP (int n) const"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBinitCtrl\fP ()"
.br
.ti -1c
.RI "void \fBsetCC\fP (int n, int val)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsetPreset\fP (\fBPreset\fP *p)"
.br
.ti -1c
.RI "\fBPreset\fP * \fBpreset\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetSfontnum\fP () const"
.br
.ti -1c
.RI "void \fBsetSfontnum\fP (unsigned int s)"
.br
.ti -1c
.RI "unsigned int \fBgetBanknum\fP () const"
.br
.ti -1c
.RI "void \fBsetBanknum\fP (unsigned int b)"
.br
.ti -1c
.RI "void \fBsetPrognum\fP (int p)"
.br
.ti -1c
.RI "int \fBgetPrognum\fP () const"
.br
.ti -1c
.RI "void \fBsetcc\fP (int ctrl, int val)"
.br
.ti -1c
.RI "void \fBpitchBend\fP (int val)"
.br
.ti -1c
.RI "int \fBgetPitchBend\fP () const"
.br
.ti -1c
.RI "void \fBpitchWheelSens\fP (int val)"
.br
.ti -1c
.RI "int \fBgetCC\fP (int num)"
.br
.ti -1c
.RI "int \fBgetNum\fP () const"
.br
.ti -1c
.RI "void \fBsetInterpMethod\fP (int m)"
.br
.ti -1c
.RI "int \fBgetInterpMethod\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBchannum\fP"
.br
.ti -1c
.RI "short \fBkey_pressure\fP"
.br
.ti -1c
.RI "short \fBchannel_pressure\fP"
.br
.ti -1c
.RI "short \fBpitch_bend\fP"
.br
.ti -1c
.RI "short \fBpitch_wheel_sensitivity\fP"
.br
.ti -1c
.RI "short \fBcc\fP [128]"
.br
.ti -1c
.RI "unsigned char \fBbank_msb\fP"
.br
.ti -1c
.RI "int \fBinterp_method\fP"
.br
.ti -1c
.RI "short \fBnrpn_select\fP"
.br
.ti -1c
.RI "float \fBgen\fP [GEN_LAST]"
.br
.ti -1c
.RI "char \fBgen_abs\fP [GEN_LAST]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file fluid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
