.TH "FluidGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SynthesizerGui\fP, and \fBUi::FluidGui\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsynthesizerChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFluidGui\fP (\fBMs::Synthesizer\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 43 of file fluidgui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
