.TH "FluidS::Phase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::Phase
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator+=\fP (const \fBPhase\fP &p)"
.br
.ti -1c
.RI "void \fBsetInt\fP (qint32 b)"
.br
.ti -1c
.RI "void \fBsetFloat\fP (double b)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBPhase\fP &b)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (int b)"
.br
.ti -1c
.RI "int \fBindex\fP () const"
.br
.ti -1c
.RI "quint32 \fBfract\fP () const"
.br
.ti -1c
.RI "quint32 \fBindex_round\fP () const"
.br
.ti -1c
.RI "\fBPhase\fP (qint64 v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qint64 \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 634 of file fluid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
