.TH "FluidS::SFPhdr" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FluidS::SFPhdr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBname\fP [20]"
.br
.ti -1c
.RI "unsigned short \fBpreset\fP"
.br
.ti -1c
.RI "unsigned short \fBbank\fP"
.br
.ti -1c
.RI "unsigned short \fBpbagndx\fP"
.br
.ti -1c
.RI "unsigned int \fBlibrary\fP"
.br
.ti -1c
.RI "unsigned int \fBgenre\fP"
.br
.ti -1c
.RI "unsigned int \fBmorphology\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 344 of file sfont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
