.TH "FNT_CMapRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FNT_CMapRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMapRec\fP \fBcmap\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBfirst\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 603 of file winfnt\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
