.TH "FoFiBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoFiBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFoFiTrueType\fP, \fBFoFiType1\fP, and \fBFoFiType1C\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFoFiBase\fP (char *fileA, int lenA, GBool freeFileDataA)"
.br
.ti -1c
.RI "int \fBgetS8\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "int \fBgetU8\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "int \fBgetS16BE\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "int \fBgetU16BE\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "int \fBgetS32BE\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "Guint \fBgetU32BE\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "Guint \fBgetU32LE\fP (int pos, GBool *ok)"
.br
.ti -1c
.RI "Guint \fBgetUVarBE\fP (int pos, int size, GBool *ok)"
.br
.ti -1c
.RI "GBool \fBcheckRegion\fP (int pos, int size)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static char * \fBreadFile\fP (char *fileName, int *fileLen)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Guchar * \fBfileData\fP"
.br
.ti -1c
.RI "Guchar * \fBfile\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "GBool \fBfreeFileData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file FoFiBase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
