.TH "FoFiIdentifier" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoFiIdentifier
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static FoFiIdentifierType \fBidentifyMem\fP (char *file, int len)"
.br
.ti -1c
.RI "static FoFiIdentifierType \fBidentifyFile\fP (char *fileName)"
.br
.ti -1c
.RI "static FoFiIdentifierType \fBidentifyStream\fP (int(*getChar)(void *data), void *data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file FoFiIdentifier\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
