.TH "FoFiTrueType" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoFiTrueType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFoFiBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GBool \fBisOpenTypeCFF\fP ()"
.br
.ti -1c
.RI "int \fBgetNumCmaps\fP ()"
.br
.ti -1c
.RI "int \fBgetCmapPlatform\fP (int i)"
.br
.ti -1c
.RI "int \fBgetCmapEncoding\fP (int i)"
.br
.ti -1c
.RI "int \fBfindCmap\fP (int platform, int encoding)"
.br
.ti -1c
.RI "int \fBmapCodeToGID\fP (int i, Guint c)"
.br
.ti -1c
.RI "Guint \fBmapToVertGID\fP (Guint orgGID)"
.br
.ti -1c
.RI "int \fBmapNameToGID\fP (char *name)"
.br
.ti -1c
.RI "int * \fBgetCIDToGIDMap\fP (int *nCIDs)"
.br
.ti -1c
.RI "int \fBgetEmbeddingRights\fP ()"
.br
.ti -1c
.RI "void \fBgetFontMatrix\fP (double *mat)"
.br
.ti -1c
.RI "void \fBconvertToType42\fP (char *psName, char **encoding, int *codeToGID, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToType1\fP (char *psName, const char **newEncoding, GBool ascii, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToCIDType2\fP (char *psName, int *cidMap, int nCIDs, GBool needVerticalMetrics, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToCIDType0\fP (char *psName, int *cidMap, int nCIDs, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToType0\fP (char *psName, int *cidMap, int nCIDs, GBool needVerticalMetrics, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToType0\fP (char *psName, int *cidMap, int nCIDs, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "GBool \fBgetCFFBlock\fP (char **start, int *length)"
.br
.ti -1c
.RI "int \fBsetupGSUB\fP (const char *scriptName)"
.br
.ti -1c
.RI "int \fBsetupGSUB\fP (const char *scriptName, const char *languageName)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFoFiTrueType\fP * \fBmake\fP (char *fileA, int lenA, int faceIndexA=0)"
.br
.ti -1c
.RI "static \fBFoFiTrueType\fP * \fBload\fP (char *fileName, int faceIndexA=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 46 of file FoFiTrueType\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
