.TH "FoFiType1" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoFiType1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFoFiBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBgetName\fP ()"
.br
.ti -1c
.RI "char ** \fBgetEncoding\fP ()"
.br
.ti -1c
.RI "void \fBgetFontMatrix\fP (double *mat)"
.br
.ti -1c
.RI "void \fBwriteEncoded\fP (const char **newEncoding, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFoFiType1\fP * \fBmake\fP (char *fileA, int lenA)"
.br
.ti -1c
.RI "static \fBFoFiType1\fP * \fBload\fP (char *fileName)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file FoFiType1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
