.TH "FoFiType1C" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoFiType1C
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFoFiBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBgetName\fP ()"
.br
.ti -1c
.RI "char ** \fBgetEncoding\fP ()"
.br
.ti -1c
.RI "int \fBgetNumGlyphs\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetGlyphName\fP (int gid)"
.br
.ti -1c
.RI "int * \fBgetCIDToGIDMap\fP (int *nCIDs)"
.br
.ti -1c
.RI "void \fBgetFontMatrix\fP (double *mat)"
.br
.ti -1c
.RI "void \fBconvertToType1\fP (char *psName, const char **newEncoding, GBool ascii, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToCIDType0\fP (char *psName, int *codeMap, int nCodes, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.ti -1c
.RI "void \fBconvertToType0\fP (char *psName, int *codeMap, int nCodes, FoFiOutputFunc outputFunc, void *outputStream)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFoFiType1C\fP * \fBmake\fP (char *fileA, int lenA)"
.br
.ti -1c
.RI "static \fBFoFiType1C\fP * \fBload\fP (char *fileName)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 147 of file FoFiType1C\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
