.TH "FontInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBunknown\fP, \fBType1\fP, \fBType1C\fP, \fBType1COT\fP, \fBType3\fP, \fBTrueType\fP, \fBTrueTypeOT\fP, \fBCIDType0\fP, \fBCIDType0C\fP, \fBCIDType0COT\fP, \fBCIDTrueType\fP, \fBCIDTrueTypeOT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontInfo\fP (\fBGfxFont\fP *fontA, \fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "\fBFontInfo\fP (\fBFontInfo\fP &f)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetSubstituteName\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFile\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetEncoding\fP ()"
.br
.ti -1c
.RI "Type \fBgetType\fP ()"
.br
.ti -1c
.RI "GBool \fBgetEmbedded\fP ()"
.br
.ti -1c
.RI "GBool \fBgetSubset\fP ()"
.br
.ti -1c
.RI "GBool \fBgetToUnicode\fP ()"
.br
.ti -1c
.RI "\fBRef\fP \fBgetRef\fP ()"
.br
.ti -1c
.RI "\fBRef\fP \fBgetEmbRef\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file FontInfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
