.TH "font" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
font
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBfont_family\fP { \fBff_none\fP, \fBff_serif\fP, \fBff_sans_serif\fP, \fBff_cursive\fP, \fBff_fantasy\fP, \fBff_monospace\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBfont\fP &f)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBfont\fP &f)"
.br
.ti -1c
.RI "\fBfont\fP & \fBoperator=\fP (const \fBfont\fP &f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "font_family \fBfamily\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "int \fBcharset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file fmt_opts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
