.TH "FormFieldSignature" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormFieldSignature
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormFieldSignature\fP (\fBPDFDoc\fP *docA, \fBObject\fP *dict, const \fBRef\fP &ref, \fBFormField\fP *parent, std::set< int > *usedParents)"
.br
.ti -1c
.RI "\fBSignatureInfo\fP * \fBvalidateSignature\fP (bool doVerifyCert, bool forceRevalidation)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 493 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
