.TH "formatting_options" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatting_options
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBhalign\fP { \fBalign_left\fP, \fBalign_right\fP, \fBalign_center\fP, \fBalign_justify\fP, \fBalign_error\fP }"
.br
.ti -1c
.RI "enum \fBvalign\fP { \fBva_normal\fP, \fBva_sub\fP, \fBva_sup\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBformatting_options\fP &opt)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBformatting_options\fP &opt)"
.br
.ti -1c
.RI "\fBformatting_options\fP & \fBoperator=\fP (const \fBformatting_options\fP &opt)"
.br
.ti -1c
.RI "std::string \fBget_par_str\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBchpBold\fP"
.br
.ti -1c
.RI "bool \fBchpItalic\fP"
.br
.ti -1c
.RI "bool \fBchpUnderline\fP"
.br
.ti -1c
.RI "valign \fBchpVAlign\fP"
.br
.ti -1c
.RI "int \fBchpFontSize\fP"
.br
.ti -1c
.RI "int \fBchpHighlight\fP"
.br
.ti -1c
.RI "\fBcolor\fP \fBchpFColor\fP"
.br
.ti -1c
.RI "\fBcolor\fP \fBchpBColor\fP"
.br
.ti -1c
.RI "\fBfont\fP \fBchpFont\fP"
.br
.ti -1c
.RI "int \fBpapLeft\fP"
.br
.ti -1c
.RI "int \fBpapRight\fP"
.br
.ti -1c
.RI "int \fBpapFirst\fP"
.br
.ti -1c
.RI "int \fBpapBefore\fP"
.br
.ti -1c
.RI "int \fBpapAfter\fP"
.br
.ti -1c
.RI "halign \fBpapAlign\fP"
.br
.ti -1c
.RI "bool \fBpapInTbl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file fmt_opts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
