.TH "FormFieldText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormFieldText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormFieldText\fP (\fBPDFDoc\fP *docA, \fBObject\fP *dict, const \fBRef\fP &ref, \fBFormField\fP *parent, std::set< int > *usedParents)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetContentCopy\fP ()"
.br
.ti -1c
.RI "void \fBsetContentCopy\fP (\fBGooString\fP *new_content)"
.br
.ti -1c
.RI "bool \fBisMultiline\fP () const"
.br
.ti -1c
.RI "bool \fBisPassword\fP () const"
.br
.ti -1c
.RI "bool \fBisFileSelect\fP () const"
.br
.ti -1c
.RI "bool \fBnoSpellCheck\fP () const"
.br
.ti -1c
.RI "bool \fBnoScroll\fP () const"
.br
.ti -1c
.RI "bool \fBisComb\fP () const"
.br
.ti -1c
.RI "bool \fBisRichText\fP () const"
.br
.ti -1c
.RI "int \fBgetMaxLen\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBcontent\fP"
.br
.ti -1c
.RI "bool \fBmultiline\fP"
.br
.ti -1c
.RI "bool \fBpassword\fP"
.br
.ti -1c
.RI "bool \fBfileSelect\fP"
.br
.ti -1c
.RI "bool \fBdoNotSpellCheck\fP"
.br
.ti -1c
.RI "bool \fBdoNotScroll\fP"
.br
.ti -1c
.RI "bool \fBcomb\fP"
.br
.ti -1c
.RI "bool \fBrichText\fP"
.br
.ti -1c
.RI "int \fBmaxLen\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 386 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
