.TH "FormFieldButton" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormFieldButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormFieldButton\fP (\fBPDFDoc\fP *docA, \fBObject\fP *dict, const \fBRef\fP &ref, \fBFormField\fP *parent, std::set< int > *usedParents)"
.br
.ti -1c
.RI "FormButtonType \fBgetButtonType\fP ()"
.br
.ti -1c
.RI "bool \fBnoToggleToOff\fP () const"
.br
.ti -1c
.RI "GBool \fBsetState\fP (char *state)"
.br
.ti -1c
.RI "GBool \fBgetState\fP (char *state)"
.br
.ti -1c
.RI "char * \fBgetAppearanceState\fP ()"
.br
.ti -1c
.RI "void \fBfillChildrenSiblingsID\fP ()"
.br
.ti -1c
.RI "void \fBsetNumSiblings\fP (int num)"
.br
.ti -1c
.RI "void \fBsetSibling\fP (int i, \fBFormFieldButton\fP *id)"
.br
.ti -1c
.RI "\fBFormFieldButton\fP * \fBgetSibling\fP (int i) const"
.br
.ti -1c
.RI "int \fBgetNumSiblings\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateState\fP (char *state)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFormFieldButton\fP ** \fBsiblings\fP"
.br
.ti -1c
.RI "int \fBnumSiblings\fP"
.br
.ti -1c
.RI "FormButtonType \fBbtype\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBactive_child\fP"
.br
.ti -1c
.RI "bool \fBnoAllOff\fP"
.br
.ti -1c
.RI "\fBObject\fP \fBappearanceState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 340 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
