.TH "Form" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Form
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm\fP (\fBPDFDoc\fP *docA, \fBObject\fP *acroForm)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObj\fP () const"
.br
.ti -1c
.RI "GBool \fBgetNeedAppearances\fP () const"
.br
.ti -1c
.RI "int \fBgetNumFields\fP () const"
.br
.ti -1c
.RI "\fBFormField\fP * \fBgetRootField\fP (int i) const"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetDefaultAppearance\fP () const"
.br
.ti -1c
.RI "VariableTextQuadding \fBgetTextQuadding\fP () const"
.br
.ti -1c
.RI "\fBGfxResources\fP * \fBgetDefaultResources\fP () const"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetDefaultResourcesObj\fP ()"
.br
.ti -1c
.RI "\fBFormWidget\fP * \fBfindWidgetByRef\fP (\fBRef\fP aref)"
.br
.ti -1c
.RI "void \fBpostWidgetsLoad\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBObject\fP * \fBfieldLookup\fP (\fBDict\fP *field, const char *key, \fBObject\fP *obj)"
.br
.ti -1c
.RI "static \fBFormField\fP * \fBcreateFieldFromDict\fP (\fBObject\fP *obj, \fBPDFDoc\fP *docA, const \fBRef\fP &aref, \fBFormField\fP *parent, std::set< int > *usedParents)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 519 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
