.TH "formatter.Formatter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter.Formatter \- FORMATTER CLASS\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtohtml\&.HtmlFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, processor)"
.br
.ti -1c
.RI "def \fBadd_identifier\fP (self, name, block)"
.br
.ti -1c
.RI "def \fBtoc_enter\fP (self)"
.br
.ti -1c
.RI "def \fBtoc_chapter_enter\fP (self, chapter)"
.br
.ti -1c
.RI "def \fBtoc_section_enter\fP (self, section)"
.br
.ti -1c
.RI "def \fBtoc_section_exit\fP (self, section)"
.br
.ti -1c
.RI "def \fBtoc_chapter_exit\fP (self, chapter)"
.br
.ti -1c
.RI "def \fBtoc_index\fP (self, index_filename)"
.br
.ti -1c
.RI "def \fBtoc_exit\fP (self)"
.br
.ti -1c
.RI "def \fBtoc_dump\fP (self, toc_filename=None, index_filename=None)"
.br
.ti -1c
.RI "def \fBindex_enter\fP (self)"
.br
.ti -1c
.RI "def \fBindex_name_enter\fP (self, name)"
.br
.ti -1c
.RI "def \fBindex_name_exit\fP (self, name)"
.br
.ti -1c
.RI "def \fBindex_exit\fP (self)"
.br
.ti -1c
.RI "def \fBindex_dump\fP (self, index_filename=None)"
.br
.ti -1c
.RI "def \fBsection_enter\fP (self, section)"
.br
.ti -1c
.RI "def \fBblock_enter\fP (self, block)"
.br
.ti -1c
.RI "def \fBmarkup_enter\fP (self, markup, block=None)"
.br
.ti -1c
.RI "def \fBfield_enter\fP (self, field, markup=None, block=None)"
.br
.ti -1c
.RI "def \fBfield_exit\fP (self, field, markup=None, block=None)"
.br
.ti -1c
.RI "def \fBmarkup_exit\fP (self, markup, block=None)"
.br
.ti -1c
.RI "def \fBblock_exit\fP (self, block)"
.br
.ti -1c
.RI "def \fBsection_exit\fP (self, section)"
.br
.ti -1c
.RI "def \fBsection_dump\fP (self, section, section_filename=None)"
.br
.ti -1c
.RI "def \fBsection_dump_all\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprocessor\fP"
.br
.ti -1c
.RI "\fBidentifiers\fP"
.br
.ti -1c
.RI "\fBchapters\fP"
.br
.ti -1c
.RI "\fBsections\fP"
.br
.ti -1c
.RI "\fBblock_index\fP"
.br
.ti -1c
.RI "\fBblocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FORMATTER CLASS\&. 
.PP
Definition at line 35 of file formatter\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
