.TH "FormFieldChoice" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormFieldChoice
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormField\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBChoiceOpt\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormFieldChoice\fP (\fBPDFDoc\fP *docA, \fBObject\fP *aobj, const \fBRef\fP &ref, \fBFormField\fP *parent, std::set< int > *usedParents)"
.br
.ti -1c
.RI "int \fBgetNumChoices\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetChoice\fP (int i)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetExportVal\fP (int i)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetSelectedChoice\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (int i)"
.br
.ti -1c
.RI "void \fBtoggle\fP (int i)"
.br
.ti -1c
.RI "void \fBdeselectAll\fP ()"
.br
.ti -1c
.RI "void \fBsetEditChoice\fP (\fBGooString\fP *new_content)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetEditChoice\fP ()"
.br
.ti -1c
.RI "bool \fBisSelected\fP (int i)"
.br
.ti -1c
.RI "int \fBgetNumSelected\fP ()"
.br
.ti -1c
.RI "bool \fBisCombo\fP () const"
.br
.ti -1c
.RI "bool \fBhasEdit\fP () const"
.br
.ti -1c
.RI "bool \fBisMultiSelect\fP () const"
.br
.ti -1c
.RI "bool \fBnoSpellCheck\fP () const"
.br
.ti -1c
.RI "bool \fBcommitOnSelChange\fP () const"
.br
.ti -1c
.RI "bool \fBisListBox\fP () const"
.br
.ti -1c
.RI "int \fBgetTopIndex\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBunselectAll\fP ()"
.br
.ti -1c
.RI "void \fBupdateSelection\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBcombo\fP"
.br
.ti -1c
.RI "bool \fBedit\fP"
.br
.ti -1c
.RI "bool \fBmultiselect\fP"
.br
.ti -1c
.RI "bool \fBdoNotSpellCheck\fP"
.br
.ti -1c
.RI "bool \fBdoCommitOnSelChange\fP"
.br
.ti -1c
.RI "int \fBnumChoices\fP"
.br
.ti -1c
.RI "\fBChoiceOpt\fP * \fBchoices\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBeditedChoice\fP"
.br
.ti -1c
.RI "int \fBtopIdx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 424 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
