.TH "FormPageWidgets" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormPageWidgets
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormPageWidgets\fP (\fBAnnots\fP *annots, unsigned int page, \fBForm\fP *form)"
.br
.ti -1c
.RI "int \fBgetNumWidgets\fP () const"
.br
.ti -1c
.RI "\fBFormWidget\fP * \fBgetWidget\fP (int i) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 564 of file Form\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
