.TH "FrameShadowBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameShadowBase \- frame shadow  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <frameshadow\&.h>\fP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBFlatFrameShadow\fP, and \fBSunkenFrameShadow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameShadowBase\fP (ShadowArea area)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~FrameShadowBase\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "void \fBsetShadowArea\fP (ShadowArea area)"
.br
.RI "shadow area "
.ti -1c
.RI "const ShadowArea & \fBshadowArea\fP () const"
.br
.RI "shadow area "
.ti -1c
.RI "virtual void \fBupdateGeometry\fP (void)=0"
.br
.RI "update geometry "
.ti -1c
.RI "virtual void \fBupdateState\fP (bool, bool, qreal, AnimationMode)"
.br
.RI "update state "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBevent\fP (QEvent *e)"
.br
.RI "event handler "
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.RI "initialization "
.ti -1c
.RI "virtual QWidget * \fBviewport\fP (void) const"
.br
.RI "return viewport associated to parent widget "
.in -1c
.SH "Detailed Description"
.PP 
frame shadow 

this allows the shadow to be painted over the widgets viewport 
.PP
Definition at line 111 of file frameshadow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
