.TH "Freeverb" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Freeverb
.SH SYNOPSIS
.br
.PP
.PP
Inherits Effect\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBprocess\fP (int n, float *in, float *out)"
.br
.ti -1c
.RI "virtual void \fBsetNValue\fP (int idx, double value)"
.br
.ti -1c
.RI "virtual double \fBnvalue\fP (int idx) const"
.br
.ti -1c
.RI "bool \fBsetPreset\fP (int)"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const"
.br
.ti -1c
.RI "virtual EffectGui * \fBgui\fP ()"
.br
.ti -1c
.RI "virtual const std::vector< ParDescr > & \fBparDescr\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file freeverb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
