.TH "FT_AutoHinter_InterfaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_AutoHinter_InterfaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_AutoHinter_GlobalResetFunc \fBreset_face\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlobalGetFunc \fBget_global_hints\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlobalDoneFunc \fBdone_global_hints\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlyphLoadFunc \fBload_glyph\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 190 of file autohint\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
