.TH "FT_Bitmap_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Bitmap_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBrows\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuffer\fP"
.br
.ti -1c
.RI "unsigned short \fBnum_grays\fP"
.br
.ti -1c
.RI "unsigned char \fBpixel_mode\fP"
.br
.ti -1c
.RI "unsigned char \fBpalette_mode\fP"
.br
.ti -1c
.RI "void * \fBpalette\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file ftimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
