.TH "FT_CMap_ClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_CMap_ClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBsize\fP"
.br
.ti -1c
.RI "FT_CMap_InitFunc \fBinit\fP"
.br
.ti -1c
.RI "FT_CMap_DoneFunc \fBdone\fP"
.br
.ti -1c
.RI "FT_CMap_CharIndexFunc \fBchar_index\fP"
.br
.ti -1c
.RI "FT_CMap_CharNextFunc \fBchar_next\fP"
.br
.ti -1c
.RI "FT_CMap_CharVarIndexFunc \fBchar_var_index\fP"
.br
.ti -1c
.RI "FT_CMap_CharVarIsDefaultFunc \fBchar_var_default\fP"
.br
.ti -1c
.RI "FT_CMap_VariantListFunc \fBvariant_list\fP"
.br
.ti -1c
.RI "FT_CMap_CharVariantListFunc \fBcharvariant_list\fP"
.br
.ti -1c
.RI "FT_CMap_VariantCharListFunc \fBvariantchar_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 193 of file ftobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
