.TH "FT_Driver_ClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Driver_ClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Module_Class\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Long \fBface_object_size\fP"
.br
.ti -1c
.RI "FT_Long \fBsize_object_size\fP"
.br
.ti -1c
.RI "FT_Long \fBslot_object_size\fP"
.br
.ti -1c
.RI "FT_Face_InitFunc \fBinit_face\fP"
.br
.ti -1c
.RI "FT_Face_DoneFunc \fBdone_face\fP"
.br
.ti -1c
.RI "FT_Size_InitFunc \fBinit_size\fP"
.br
.ti -1c
.RI "FT_Size_DoneFunc \fBdone_size\fP"
.br
.ti -1c
.RI "FT_Slot_InitFunc \fBinit_slot\fP"
.br
.ti -1c
.RI "FT_Slot_DoneFunc \fBdone_slot\fP"
.br
.ti -1c
.RI "FT_Slot_LoadFunc \fBload_glyph\fP"
.br
.ti -1c
.RI "FT_Face_GetKerningFunc \fBget_kerning\fP"
.br
.ti -1c
.RI "FT_Face_AttachFunc \fBattach_file\fP"
.br
.ti -1c
.RI "FT_Face_GetAdvancesFunc \fBget_advances\fP"
.br
.ti -1c
.RI "FT_Size_RequestFunc \fBrequest_size\fP"
.br
.ti -1c
.RI "FT_Size_SelectFunc \fBselect_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 166 of file ftdriver\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
