.TH "FT_Frame_Field_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Frame_Field_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBvalue\fP"
.br
.ti -1c
.RI "FT_Byte \fBsize\fP"
.br
.ti -1c
.RI "FT_UShort \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file ftstream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
