.TH "FT_Face_InternalRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Face_InternalRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Matrix\fP \fBtransform_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBtransform_delta\fP"
.br
.ti -1c
.RI "FT_Int \fBtransform_flags\fP"
.br
.ti -1c
.RI "\fBFT_ServiceCacheRec\fP \fBservices\fP"
.br
.ti -1c
.RI "FT_Bool \fBignore_unpatented_hinter\fP"
.br
.ti -1c
.RI "FT_Int \fBrefcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 356 of file ftobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
