.TH "FT_GlyphLoaderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_GlyphLoaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_points\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_contours\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_subglyphs\fP"
.br
.ti -1c
.RI "FT_Bool \fBuse_extra\fP"
.br
.ti -1c
.RI "\fBFT_GlyphLoadRec\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBFT_GlyphLoadRec\fP \fBcurrent\fP"
.br
.ti -1c
.RI "void * \fBother\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file ftgloadr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
