.TH "FT_Int64_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Int64_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt32 \fBlo\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBhi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file ftcalc\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
