.TH "FT_LibraryRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_LibraryRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Int \fBversion_major\fP"
.br
.ti -1c
.RI "FT_Int \fBversion_minor\fP"
.br
.ti -1c
.RI "FT_Int \fBversion_patch\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_modules\fP"
.br
.ti -1c
.RI "\fBFT_Module\fP \fBmodules\fP [FT_MAX_MODULES]"
.br
.ti -1c
.RI "\fBFT_ListRec\fP \fBrenderers\fP"
.br
.ti -1c
.RI "\fBFT_Renderer\fP \fBcur_renderer\fP"
.br
.ti -1c
.RI "\fBFT_Module\fP \fBauto_hinter\fP"
.br
.ti -1c
.RI "FT_Byte * \fBraster_pool\fP"
.br
.ti -1c
.RI "FT_ULong \fBraster_pool_size\fP"
.br
.ti -1c
.RI "FT_DebugHook_Func \fBdebug_hooks\fP [4]"
.br
.ti -1c
.RI "FT_Int \fBrefcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 856 of file ftobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
