.TH "FT_LzwStateRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_LzwStateRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_LzwPhase \fBphase\fP"
.br
.ti -1c
.RI "FT_Int \fBin_eof\fP"
.br
.ti -1c
.RI "FT_Byte \fBbuf_tab\fP [16]"
.br
.ti -1c
.RI "FT_UInt \fBbuf_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBbuf_size\fP"
.br
.ti -1c
.RI "FT_Bool \fBbuf_clear\fP"
.br
.ti -1c
.RI "FT_Offset \fBbuf_total\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_bits\fP"
.br
.ti -1c
.RI "FT_Int \fBblock_mode\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_free\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_bits\fP"
.br
.ti -1c
.RI "FT_UInt \fBfree_ent\fP"
.br
.ti -1c
.RI "FT_UInt \fBfree_bits\fP"
.br
.ti -1c
.RI "FT_UInt \fBold_code\fP"
.br
.ti -1c
.RI "FT_UInt \fBold_char\fP"
.br
.ti -1c
.RI "FT_UInt \fBin_code\fP"
.br
.ti -1c
.RI "FT_UShort * \fBprefix\fP"
.br
.ti -1c
.RI "FT_Byte * \fBsuffix\fP"
.br
.ti -1c
.RI "FT_UInt \fBprefix_size\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstack\fP"
.br
.ti -1c
.RI "FT_UInt \fBstack_top\fP"
.br
.ti -1c
.RI "FT_Offset \fBstack_size\fP"
.br
.ti -1c
.RI "FT_Byte \fBstack_0\fP [FT_LZW_DEFAULT_STACK_SIZE]"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBsource\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file ftzopen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
