.TH "FT_MM_Axis_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_MM_Axis_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBname\fP"
.br
.ti -1c
.RI "FT_Long \fBminimum\fP"
.br
.ti -1c
.RI "FT_Long \fBmaximum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file ftmm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
