.TH "FT_Outline_Funcs_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Outline_Funcs_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Outline_MoveToFunc \fBmove_to\fP"
.br
.ti -1c
.RI "FT_Outline_LineToFunc \fBline_to\fP"
.br
.ti -1c
.RI "FT_Outline_ConicToFunc \fBconic_to\fP"
.br
.ti -1c
.RI "FT_Outline_CubicToFunc \fBcubic_to\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.ti -1c
.RI "FT_Pos \fBdelta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 628 of file ftimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
