.TH "FT_RendererRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_RendererRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_ModuleRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_Renderer_Class\fP * \fBclazz\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBglyph_format\fP"
.br
.ti -1c
.RI "FT_Glyph_Class \fBglyph_class\fP"
.br
.ti -1c
.RI "FT_Raster \fBraster\fP"
.br
.ti -1c
.RI "FT_Raster_Render_Func \fBraster_render\fP"
.br
.ti -1c
.RI "FT_Renderer_RenderFunc \fBrender\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 691 of file ftobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
