.TH "FT_Renderer_Class_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Renderer_Class_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Module_Class\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBglyph_format\fP"
.br
.ti -1c
.RI "FT_Renderer_RenderFunc \fBrender_glyph\fP"
.br
.ti -1c
.RI "FT_Renderer_TransformFunc \fBtransform_glyph\fP"
.br
.ti -1c
.RI "FT_Renderer_GetCBoxFunc \fBget_glyph_cbox\fP"
.br
.ti -1c
.RI "FT_Renderer_SetModeFunc \fBset_mode\fP"
.br
.ti -1c
.RI "\fBFT_Raster_Funcs\fP * \fBraster_class\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file ftrender\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
