.TH "FT_Span_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Span_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "unsigned short \fBlen\fP"
.br
.ti -1c
.RI "unsigned char \fBcoverage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 828 of file ftimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
