.TH "FT_ServiceCacheRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_ServiceCacheRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Pointer \fBservice_POSTSCRIPT_FONT_NAME\fP"
.br
.ti -1c
.RI "FT_Pointer \fBservice_MULTI_MASTERS\fP"
.br
.ti -1c
.RI "FT_Pointer \fBservice_GLYPH_DICT\fP"
.br
.ti -1c
.RI "FT_Pointer \fBservice_PFR_METRICS\fP"
.br
.ti -1c
.RI "FT_Pointer \fBservice_WINFNT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 634 of file ftserv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
