.TH "FT_ServiceDescRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_ServiceDescRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBserv_id\fP"
.br
.ti -1c
.RI "const void * \fBserv_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file ftserv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
