.TH "FT_StrokerRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_StrokerRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Angle \fBangle_in\fP"
.br
.ti -1c
.RI "FT_Angle \fBangle_out\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBcenter\fP"
.br
.ti -1c
.RI "FT_Fixed \fBline_length\fP"
.br
.ti -1c
.RI "FT_Bool \fBfirst_point\fP"
.br
.ti -1c
.RI "FT_Bool \fBsubpath_open\fP"
.br
.ti -1c
.RI "FT_Angle \fBsubpath_angle\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBsubpath_start\fP"
.br
.ti -1c
.RI "FT_Fixed \fBsubpath_line_length\fP"
.br
.ti -1c
.RI "FT_Bool \fBhandle_wide_strokes\fP"
.br
.ti -1c
.RI "FT_Stroker_LineCap \fBline_cap\fP"
.br
.ti -1c
.RI "FT_Stroker_LineJoin \fBline_join\fP"
.br
.ti -1c
.RI "FT_Stroker_LineJoin \fBline_join_saved\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmiter_limit\fP"
.br
.ti -1c
.RI "FT_Fixed \fBradius\fP"
.br
.ti -1c
.RI "\fBFT_StrokeBorderRec\fP \fBborders\fP [2]"
.br
.ti -1c
.RI "\fBFT_Library\fP \fBlibrary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 771 of file ftstroke\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
