.TH "FT_Vector_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Vector_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Pos \fBx\fP"
.br
.ti -1c
.RI "FT_Pos \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file ftimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
