.TH "FT_ValidatorRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_ValidatorRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ft_jmp_buf \fBjump_buffer\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBbase\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBlimit\fP"
.br
.ti -1c
.RI "FT_ValidationLevel \fBlevel\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file ftvalid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
