.TH "FTC_ManagerRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_ManagerRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Library\fP \fBlibrary\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBFTC_Node\fP \fBnodes_list\fP"
.br
.ti -1c
.RI "FT_Offset \fBmax_weight\fP"
.br
.ti -1c
.RI "FT_Offset \fBcur_weight\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_nodes\fP"
.br
.ti -1c
.RI "\fBFTC_Cache\fP \fBcaches\fP [FTC_MAX_CACHES]"
.br
.ti -1c
.RI "FT_UInt \fBnum_caches\fP"
.br
.ti -1c
.RI "\fBFTC_MruListRec\fP \fBfaces\fP"
.br
.ti -1c
.RI "\fBFTC_MruListRec\fP \fBsizes\fP"
.br
.ti -1c
.RI "FT_Pointer \fBrequest_data\fP"
.br
.ti -1c
.RI "FTC_Face_Requester \fBrequest_face\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file ftcmanag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
