.TH "FTC_FamilyRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_FamilyRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_MruNodeRec\fP \fBmrunode\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_nodes\fP"
.br
.ti -1c
.RI "\fBFTC_Cache\fP \fBcache\fP"
.br
.ti -1c
.RI "FTC_MruListClass \fBclazz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file ftcglyph\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
