.TH "FTC_MruListClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_MruListClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Offset \fBnode_size\fP"
.br
.ti -1c
.RI "FTC_MruNode_CompareFunc \fBnode_compare\fP"
.br
.ti -1c
.RI "FTC_MruNode_InitFunc \fBnode_init\fP"
.br
.ti -1c
.RI "FTC_MruNode_ResetFunc \fBnode_reset\fP"
.br
.ti -1c
.RI "FTC_MruNode_DoneFunc \fBnode_done\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file ftcmru\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
