.TH "FTC_CacheClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_CacheClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FTC_Node_NewFunc \fBnode_new\fP"
.br
.ti -1c
.RI "FTC_Node_WeightFunc \fBnode_weight\fP"
.br
.ti -1c
.RI "FTC_Node_CompareFunc \fBnode_compare\fP"
.br
.ti -1c
.RI "FTC_Node_CompareFunc \fBnode_remove_faceid\fP"
.br
.ti -1c
.RI "FTC_Node_FreeFunc \fBnode_free\fP"
.br
.ti -1c
.RI "FT_Offset \fBcache_size\fP"
.br
.ti -1c
.RI "FTC_Cache_InitFunc \fBcache_init\fP"
.br
.ti -1c
.RI "FTC_Cache_DoneFunc \fBcache_done\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file ftccache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
