.TH "FTC_CMapNodeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_CMapNodeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_NodeRec\fP \fBnode\fP"
.br
.ti -1c
.RI "FTC_FaceID \fBface_id\fP"
.br
.ti -1c
.RI "FT_UInt \fBcmap_index\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBfirst\fP"
.br
.ti -1c
.RI "FT_UInt16 \fBindices\fP [FTC_CMAP_INDICES_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file ftccmap\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
