.TH "FTC_GCacheClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_GCacheClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_CacheClassRec\fP \fBclazz\fP"
.br
.ti -1c
.RI "FTC_MruListClass \fBfamily_class\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file ftcglyph\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
