.TH "FTC_INodeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_INodeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_GNodeRec\fP \fBgnode\fP"
.br
.ti -1c
.RI "\fBFT_Glyph\fP \fBglyph\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file ftcimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
