.TH "FTC_GCacheRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_GCacheRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_CacheRec\fP \fBcache\fP"
.br
.ti -1c
.RI "\fBFTC_MruListRec\fP \fBfamilies\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file ftcglyph\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
