.TH "FTC_SNodeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_SNodeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFTC_GNodeRec\fP \fBgnode\fP"
.br
.ti -1c
.RI "FT_UInt \fBcount\fP"
.br
.ti -1c
.RI "\fBFTC_SBitRec\fP \fBsbits\fP [FTC_SBIT_ITEMS_PER_NODE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file ftcsbits\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
