.TH "GDir" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GDir
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGDir\fP (char *name, GBool doStatA=gTrue)"
.br
.ti -1c
.RI "\fBGDirEntry\fP * \fBgetNextEntry\fP ()"
.br
.ti -1c
.RI "void \fBrewind\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file gfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
