.TH "GDirEntry" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GDirEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGDirEntry\fP (char *dirPath, char *nameA, GBool doStat)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFullPath\fP ()"
.br
.ti -1c
.RI "GBool \fBisDir\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file gfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
