.TH "GenericData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericData \- generic data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <genericdata\&.h>\fP
.PP
Inherits \fBAnimationData\fP\&.
.PP
Inherited by \fBProgressBarData\fP, \fBSliderData\fP, and \fBWidgetStateData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericData\fP (QObject *parent, QWidget *widget, int duration)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~GenericData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBanimation\fP () const"
.br
.RI "return animation object "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int duration)"
.br
.RI "duration "
.ti -1c
.RI "virtual qreal \fBopacity\fP (void) const"
.br
.RI "opacity "
.ti -1c
.RI "virtual void \fBsetOpacity\fP (qreal value)"
.br
.RI "opacity "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBopacity\fP"
.br
.RI "declare opacity property "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
generic data 
.PP
Definition at line 35 of file genericdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
