.TH "GENERAL_NAME_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GENERAL_NAME_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   \fBOTHERNAME\fP * \fBotherName\fP"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBrfc822Name\fP"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBdNSName\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBx400Address\fP"
.br
.ti -1c
.RI "   \fBX509_NAME\fP * \fBdirectoryName\fP"
.br
.ti -1c
.RI "   \fBEDIPARTYNAME\fP * \fBediPartyName\fP"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBuniformResourceIdentifier\fP"
.br
.ti -1c
.RI "   \fBASN1_OCTET_STRING\fP * \fBiPAddress\fP"
.br
.ti -1c
.RI "   \fBASN1_OBJECT\fP * \fBregisteredID\fP"
.br
.ti -1c
.RI "   \fBASN1_OCTET_STRING\fP * \fBip\fP"
.br
.ti -1c
.RI "   \fBX509_NAME\fP * \fBdirn\fP"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBia5\fP"
.br
.ti -1c
.RI "   \fBASN1_OBJECT\fP * \fBrid\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 173 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
