.TH "Gfx" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gfx
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfx\fP (\fBPDFDoc\fP *docA, \fBOutputDev\fP *outA, int pageNum, \fBDict\fP *resDict, double hDPI, double vDPI, \fBPDFRectangle\fP *box, \fBPDFRectangle\fP *cropBox, int rotate, GBool(*abortCheckCbkA)(void *data)=NULL, void *abortCheckCbkDataA=NULL, \fBXRef\fP *xrefA=NULL)"
.br
.ti -1c
.RI "\fBGfx\fP (\fBPDFDoc\fP *docA, \fBOutputDev\fP *outA, \fBDict\fP *resDict, \fBPDFRectangle\fP *box, \fBPDFRectangle\fP *cropBox, GBool(*abortCheckCbkA)(void *data)=NULL, void *abortCheckCbkDataA=NULL, \fBXRef\fP *xrefA=NULL)"
.br
.ti -1c
.RI "\fBXRef\fP * \fBgetXRef\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP (\fBObject\fP *obj, GBool topLevel=gTrue)"
.br
.ti -1c
.RI "void \fBdrawAnnot\fP (\fBObject\fP *str, \fBAnnotBorder\fP *border, \fBAnnotColor\fP *aColor, double xMin, double yMin, double xMax, double yMax, int rotate)"
.br
.ti -1c
.RI "void \fBsaveState\fP ()"
.br
.ti -1c
.RI "void \fBpushStateGuard\fP ()"
.br
.ti -1c
.RI "void \fBrestoreState\fP ()"
.br
.ti -1c
.RI "void \fBpopStateGuard\fP ()"
.br
.ti -1c
.RI "\fBGfxState\fP * \fBgetState\fP ()"
.br
.ti -1c
.RI "GBool \fBcheckTransparencyGroup\fP (\fBDict\fP *resDict)"
.br
.ti -1c
.RI "void \fBdrawForm\fP (\fBObject\fP *str, \fBDict\fP *resDict, double *matrix, double *bbox, GBool transpGroup=gFalse, GBool softMask=gFalse, \fBGfxColorSpace\fP *blendingColorSpace=NULL, GBool isolated=gFalse, GBool knockout=gFalse, GBool alpha=gFalse, \fBFunction\fP *transferFunc=NULL, \fBGfxColor\fP *backdropColor=NULL)"
.br
.ti -1c
.RI "void \fBpushResources\fP (\fBDict\fP *resDict)"
.br
.ti -1c
.RI "void \fBpopResources\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file Gfx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
