.TH "Gfx8BitFont" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gfx8BitFont
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxFont\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfx8BitFont\fP (\fBXRef\fP *xref, const char *tagA, \fBRef\fP idA, \fBGooString\fP *nameA, GfxFontType typeA, \fBRef\fP embFontIDA, \fBDict\fP *fontDict)"
.br
.ti -1c
.RI "virtual int \fBgetNextChar\fP (char *s, int len, CharCode *code, Unicode **u, int *uLen, double *dx, double *dy, double *ox, double *oy)"
.br
.ti -1c
.RI "char ** \fBgetEncoding\fP ()"
.br
.ti -1c
.RI "\fBCharCodeToUnicode\fP * \fBgetToUnicode\fP ()"
.br
.ti -1c
.RI "char * \fBgetCharName\fP (int code)"
.br
.ti -1c
.RI "GBool \fBgetHasEncoding\fP ()"
.br
.ti -1c
.RI "GBool \fBgetUsesMacRomanEnc\fP ()"
.br
.ti -1c
.RI "double \fBgetWidth\fP (Guchar c)"
.br
.ti -1c
.RI "int * \fBgetCodeToGIDMap\fP (\fBFoFiTrueType\fP *ff)"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetCharProcs\fP ()"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetCharProc\fP (int code, \fBObject\fP *proc)"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetResources\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGfxFont\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 319 of file GfxFont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
