.TH "GfxColorTransform" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxColorTransform
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdoTransform\fP (void *in, void *out, unsigned int size)"
.br
.ti -1c
.RI "\fBGfxColorTransform\fP (void *transformA, int cmsIntent, unsigned int inputPixelType, unsigned int transformPixelType)"
.br
.ti -1c
.RI "int \fBgetIntent\fP ()"
.br
.ti -1c
.RI "int \fBgetInputPixelType\fP ()"
.br
.ti -1c
.RI "int \fBgetTransformPixelType\fP ()"
.br
.ti -1c
.RI "void \fBref\fP ()"
.br
.ti -1c
.RI "unsigned int \fBunref\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
