.TH "GfxFunctionShading" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxFunctionShading
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxShading\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxFunctionShading\fP (double x0A, double y0A, double x1A, double y1A, double *matrixA, \fBFunction\fP **funcsA, int nFuncsA)"
.br
.ti -1c
.RI "\fBGfxFunctionShading\fP (\fBGfxFunctionShading\fP *shading)"
.br
.ti -1c
.RI "virtual \fBGfxShading\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "void \fBgetDomain\fP (double *x0A, double *y0A, double *x1A, double *y1A)"
.br
.ti -1c
.RI "double * \fBgetMatrix\fP ()"
.br
.ti -1c
.RI "int \fBgetNFuncs\fP ()"
.br
.ti -1c
.RI "\fBFunction\fP * \fBgetFunc\fP (int i)"
.br
.ti -1c
.RI "void \fBgetColor\fP (double x, double y, \fBGfxColor\fP *\fBcolor\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxFunctionShading\fP * \fBparse\fP (\fBGfxResources\fP *res, \fBDict\fP *dict, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 920 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
