.TH "GfxFontDict" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxFontDict
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxFontDict\fP (\fBXRef\fP *xref, \fBRef\fP *fontDictRef, \fBDict\fP *fontDict)"
.br
.ti -1c
.RI "\fBGfxFont\fP * \fBlookup\fP (char *tag)"
.br
.ti -1c
.RI "int \fBgetNumFonts\fP ()"
.br
.ti -1c
.RI "\fBGfxFont\fP * \fBgetFont\fP (int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 433 of file GfxFont\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
