.TH "GfxImageColorMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxImageColorMap
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxImageColorMap\fP (int bitsA, \fBObject\fP *decode, \fBGfxColorSpace\fP *colorSpaceA)"
.br
.ti -1c
.RI "\fBGfxImageColorMap\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "\fBGfxColorSpace\fP * \fBgetColorSpace\fP ()"
.br
.ti -1c
.RI "int \fBgetNumPixelComps\fP ()"
.br
.ti -1c
.RI "int \fBgetBits\fP ()"
.br
.ti -1c
.RI "double \fBgetDecodeLow\fP (int i)"
.br
.ti -1c
.RI "double \fBgetDecodeHigh\fP (int i)"
.br
.ti -1c
.RI "bool \fBuseRGBLine\fP ()"
.br
.ti -1c
.RI "bool \fBuseCMYKLine\fP ()"
.br
.ti -1c
.RI "bool \fBuseDeviceNLine\fP ()"
.br
.ti -1c
.RI "void \fBgetGray\fP (Guchar *x, GfxGray *gray)"
.br
.ti -1c
.RI "void \fBgetRGB\fP (Guchar *x, \fBGfxRGB\fP *rgb)"
.br
.ti -1c
.RI "void \fBgetRGBLine\fP (Guchar *in, unsigned int *out, int length)"
.br
.ti -1c
.RI "void \fBgetRGBLine\fP (Guchar *in, Guchar *out, int length)"
.br
.ti -1c
.RI "void \fBgetRGBXLine\fP (Guchar *in, Guchar *out, int length)"
.br
.ti -1c
.RI "void \fBgetGrayLine\fP (Guchar *in, Guchar *out, int length)"
.br
.ti -1c
.RI "void \fBgetCMYKLine\fP (Guchar *in, Guchar *out, int length)"
.br
.ti -1c
.RI "void \fBgetDeviceNLine\fP (Guchar *in, Guchar *out, int length)"
.br
.ti -1c
.RI "void \fBgetCMYK\fP (Guchar *x, \fBGfxCMYK\fP *cmyk)"
.br
.ti -1c
.RI "void \fBgetDeviceN\fP (Guchar *x, \fBGfxColor\fP *deviceN)"
.br
.ti -1c
.RI "void \fBgetColor\fP (Guchar *x, \fBGfxColor\fP *\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBsetMatteColor\fP (\fBGfxColor\fP *\fBcolor\fP)"
.br
.ti -1c
.RI "\fBGfxColor\fP * \fBgetMatteColor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1154 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
