.TH "GfxPatch" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPatch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GfxState\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBColorValue\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP [4][4]"
.br
.ti -1c
.RI "double \fBy\fP [4][4]"
.br
.ti -1c
.RI "\fBColorValue\fP \fBcolor\fP [2][2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A tensor product cubic bezier patch consisting of 4x4 points and 4 color values\&.
.PP
See the Shading Type 7 specifications\&. Note that Shading Type 6 is also represented using \fBGfxPatch\fP\&. 
.PP
Definition at line 1092 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
