.TH "GfxPatternColorSpace" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPatternColorSpace
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxColorSpace\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxPatternColorSpace\fP (\fBGfxColorSpace\fP *underA)"
.br
.ti -1c
.RI "virtual \fBGfxColorSpace\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual GfxColorSpaceMode \fBgetMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetGray\fP (\fBGfxColor\fP *\fBcolor\fP, GfxGray *gray)"
.br
.ti -1c
.RI "virtual void \fBgetRGB\fP (\fBGfxColor\fP *\fBcolor\fP, \fBGfxRGB\fP *rgb)"
.br
.ti -1c
.RI "virtual void \fBgetCMYK\fP (\fBGfxColor\fP *\fBcolor\fP, \fBGfxCMYK\fP *cmyk)"
.br
.ti -1c
.RI "virtual void \fBgetDeviceN\fP (\fBGfxColor\fP *\fBcolor\fP, \fBGfxColor\fP *deviceN)"
.br
.ti -1c
.RI "virtual int \fBgetNComps\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetDefaultColor\fP (\fBGfxColor\fP *\fBcolor\fP)"
.br
.ti -1c
.RI "\fBGfxColorSpace\fP * \fBgetUnder\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxColorSpace\fP * \fBparse\fP (\fBGfxResources\fP *res, \fBArray\fP *arr, \fBOutputDev\fP *out, \fBGfxState\fP *state, int recursion)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 726 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
