.TH "GfxPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGfxShadingPattern\fP, and \fBGfxTilingPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxPattern\fP (int typeA)"
.br
.ti -1c
.RI "virtual \fBGfxPattern\fP * \fBcopy\fP ()=0"
.br
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxPattern\fP * \fBparse\fP (\fBGfxResources\fP *res, \fBObject\fP *obj, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 758 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
