.TH "GfxPatchMeshShading" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPatchMeshShading
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxShading\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxPatchMeshShading\fP (int typeA, \fBGfxPatch\fP *patchesA, int nPatchesA, \fBFunction\fP **funcsA, int nFuncsA)"
.br
.ti -1c
.RI "\fBGfxPatchMeshShading\fP (\fBGfxPatchMeshShading\fP *shading)"
.br
.ti -1c
.RI "virtual \fBGfxShading\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "int \fBgetNPatches\fP ()"
.br
.ti -1c
.RI "\fBGfxPatch\fP * \fBgetPatch\fP (int i)"
.br
.ti -1c
.RI "bool \fBisParameterized\fP () const"
.br
.ti -1c
.RI "double \fBgetParameterDomainMin\fP () const"
.br
.ti -1c
.RI "double \fBgetParameterDomainMax\fP () const"
.br
.ti -1c
.RI "void \fBgetParameterizedColor\fP (double t, \fBGfxColor\fP *\fBcolor\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxPatchMeshShading\fP * \fBparse\fP (\fBGfxResources\fP *res, int typeA, \fBDict\fP *dict, \fBStream\fP *str, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1113 of file GfxState\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double GfxPatchMeshShading::getParameterDomainMax () const\fC [inline]\fP"
isParameterized() == true 
.PP
Definition at line 1138 of file GfxState\&.h\&.
.SS "double GfxPatchMeshShading::getParameterDomainMin () const\fC [inline]\fP"
isParameterized() == true 
.PP
Definition at line 1133 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
