.TH "GfxPatch::ColorValue" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPatch::ColorValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GfxState\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBc\fP [gfxColorMaxComps]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a single color value for the patch\&. 
.PP
Definition at line 1096 of file GfxState\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double GfxPatch::ColorValue::c[gfxColorMaxComps]"
For parameterized patches, only element 0 is valid; it contains the single parameter\&.
.PP
For non-parameterized patches, c contains all color components as decoded from the input stream\&. In this case, you will need to use dblToCol() before assigning them to \fBGfxColor\fP\&. 
.PP
Definition at line 1105 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
