.TH "GfxPath" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxPath
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxPath\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "GBool \fBisCurPt\fP ()"
.br
.ti -1c
.RI "GBool \fBisPath\fP ()"
.br
.ti -1c
.RI "int \fBgetNumSubpaths\fP ()"
.br
.ti -1c
.RI "\fBGfxSubpath\fP * \fBgetSubpath\fP (int i)"
.br
.ti -1c
.RI "double \fBgetLastX\fP ()"
.br
.ti -1c
.RI "double \fBgetLastY\fP ()"
.br
.ti -1c
.RI "void \fBmoveTo\fP (double x, double y)"
.br
.ti -1c
.RI "void \fBlineTo\fP (double x, double y)"
.br
.ti -1c
.RI "void \fBcurveTo\fP (double x1, double y1, double x2, double y2, double x3, double y3)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBappend\fP (\fBGfxPath\fP *path)"
.br
.ti -1c
.RI "void \fBoffset\fP (double dx, double dy)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1278 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
