.TH "GfxResources" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxResources
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxResources\fP (\fBXRef\fP *xref, \fBDict\fP *resDict, \fBGfxResources\fP *nextA)"
.br
.ti -1c
.RI "\fBGfxFont\fP * \fBlookupFont\fP (char *name)"
.br
.ti -1c
.RI "GBool \fBlookupXObject\fP (char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBlookupXObjectNF\fP (char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBlookupMarkedContentNF\fP (char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "void \fBlookupColorSpace\fP (const char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBGfxPattern\fP * \fBlookupPattern\fP (char *name, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.ti -1c
.RI "\fBGfxShading\fP * \fBlookupShading\fP (char *name, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.ti -1c
.RI "GBool \fBlookupGState\fP (char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBlookupGStateNF\fP (char *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBGfxResources\fP * \fBgetNext\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file Gfx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
