.TH "GfxShading" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxShading
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGfxFunctionShading\fP, \fBGfxGouraudTriangleShading\fP, \fBGfxPatchMeshShading\fP, and \fBGfxUnivariateShading\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxShading\fP (int typeA)"
.br
.ti -1c
.RI "\fBGfxShading\fP (\fBGfxShading\fP *shading)"
.br
.ti -1c
.RI "virtual \fBGfxShading\fP * \fBcopy\fP ()=0"
.br
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.ti -1c
.RI "\fBGfxColorSpace\fP * \fBgetColorSpace\fP ()"
.br
.ti -1c
.RI "\fBGfxColor\fP * \fBgetBackground\fP ()"
.br
.ti -1c
.RI "GBool \fBgetHasBackground\fP ()"
.br
.ti -1c
.RI "void \fBgetBBox\fP (double *xMinA, double *yMinA, double *xMaxA, double *yMaxA)"
.br
.ti -1c
.RI "GBool \fBgetHasBBox\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxShading\fP * \fBparse\fP (\fBGfxResources\fP *res, \fBObject\fP *obj, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "GBool \fBinit\fP (\fBGfxResources\fP *res, \fBDict\fP *dict, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBGfxColorSpace\fP * \fBcolorSpace\fP"
.br
.ti -1c
.RI "\fBGfxColor\fP \fBbackground\fP"
.br
.ti -1c
.RI "GBool \fBhasBackground\fP"
.br
.ti -1c
.RI "double \fBxMin\fP"
.br
.ti -1c
.RI "double \fByMin\fP"
.br
.ti -1c
.RI "double \fBxMax\fP"
.br
.ti -1c
.RI "double \fByMax\fP"
.br
.ti -1c
.RI "GBool \fBhasBBox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 840 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
