.TH "GfxStackStateSaver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxStackStateSaver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxStackStateSaver\fP (\fBGfx\fP *gfx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGfx\fP *const \fBgfx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5256 of file Gfx\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
