.TH "GfxShadingPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxShadingPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBGfxPattern\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "\fBGfxShading\fP * \fBgetShading\fP ()"
.br
.ti -1c
.RI "double * \fBgetMatrix\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxShadingPattern\fP * \fBparse\fP (\fBGfxResources\fP *res, \fBObject\fP *patObj, \fBOutputDev\fP *out, \fBGfxState\fP *state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 817 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
