.TH "GfxTilingPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxTilingPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBGfxPattern\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "int \fBgetPaintType\fP ()"
.br
.ti -1c
.RI "int \fBgetTilingType\fP ()"
.br
.ti -1c
.RI "double * \fBgetBBox\fP ()"
.br
.ti -1c
.RI "double \fBgetXStep\fP ()"
.br
.ti -1c
.RI "double \fBgetYStep\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetResDict\fP ()"
.br
.ti -1c
.RI "double * \fBgetMatrix\fP ()"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetContentStream\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGfxTilingPattern\fP * \fBparse\fP (\fBObject\fP *patObj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 779 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
