.TH "GfxUnivariateShading" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GfxUnivariateShading
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGfxShading\fP\&.
.PP
Inherited by \fBGfxAxialShading\fP, and \fBGfxRadialShading\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGfxUnivariateShading\fP (int typeA, double t0A, double t1A, \fBFunction\fP **funcsA, int nFuncsA, GBool extend0A, GBool extend1A)"
.br
.ti -1c
.RI "\fBGfxUnivariateShading\fP (\fBGfxUnivariateShading\fP *shading)"
.br
.ti -1c
.RI "double \fBgetDomain0\fP ()"
.br
.ti -1c
.RI "double \fBgetDomain1\fP ()"
.br
.ti -1c
.RI "GBool \fBgetExtend0\fP ()"
.br
.ti -1c
.RI "GBool \fBgetExtend1\fP ()"
.br
.ti -1c
.RI "int \fBgetNFuncs\fP ()"
.br
.ti -1c
.RI "\fBFunction\fP * \fBgetFunc\fP (int i)"
.br
.ti -1c
.RI "void \fBgetColor\fP (double t, \fBGfxColor\fP *\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBsetupCache\fP (const \fBMatrix\fP *ctm, double xMin, double yMin, double xMax, double yMax)"
.br
.ti -1c
.RI "virtual void \fBgetParameterRange\fP (double *lower, double *upper, double xMin, double yMin, double xMax, double yMax)=0"
.br
.ti -1c
.RI "virtual double \fBgetDistance\fP (double tMin, double tMax)=0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 875 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
