.TH "glnames.StringTable" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glnames.StringTable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, name_list, master_table_name)"
.br
.ti -1c
.RI "def \fBdump\fP (self, file)"
.br
.ti -1c
.RI "def \fBdump_sublist\fP (self, file, table_name, macro_name, sublist)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnames\fP"
.br
.ti -1c
.RI "\fBmaster_table\fP"
.br
.ti -1c
.RI "\fBindices\fP"
.br
.ti -1c
.RI "\fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4908 of file glnames\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
