.TH "glnames.StringNode" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glnames.StringNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, letter, value)"
.br
.ti -1c
.RI "def \fB__cmp__\fP (self, other)"
.br
.ti -1c
.RI "def \fBadd\fP (self, word, value)"
.br
.ti -1c
.RI "def \fBoptimize\fP (self)"
.br
.ti -1c
.RI "def \fBdump_debug\fP (self, write, margin)"
.br
.ti -1c
.RI "def \fBlocate\fP (self, index)"
.br
.ti -1c
.RI "def \fBstore\fP (self, storage)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBletter\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBchildren\fP"
.br
.ti -1c
.RI "\fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5036 of file glnames\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
