.TH "GooHash" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GooHash
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGooHash\fP (GBool deleteKeysA=gFalse)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBGooString\fP *key, void *val)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBGooString\fP *key, int val)"
.br
.ti -1c
.RI "void \fBreplace\fP (\fBGooString\fP *key, void *val)"
.br
.ti -1c
.RI "void \fBreplace\fP (\fBGooString\fP *key, int val)"
.br
.ti -1c
.RI "void * \fBlookup\fP (\fBGooString\fP *key)"
.br
.ti -1c
.RI "int \fBlookupInt\fP (\fBGooString\fP *key)"
.br
.ti -1c
.RI "void * \fBlookup\fP (const char *key)"
.br
.ti -1c
.RI "int \fBlookupInt\fP (const char *key)"
.br
.ti -1c
.RI "void * \fBremove\fP (\fBGooString\fP *key)"
.br
.ti -1c
.RI "int \fBremoveInt\fP (\fBGooString\fP *key)"
.br
.ti -1c
.RI "void * \fBremove\fP (const char *key)"
.br
.ti -1c
.RI "int \fBremoveInt\fP (const char *key)"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "void \fBstartIter\fP (\fBGooHashIter\fP **iter)"
.br
.ti -1c
.RI "GBool \fBgetNext\fP (\fBGooHashIter\fP **iter, \fBGooString\fP **key, void **val)"
.br
.ti -1c
.RI "GBool \fBgetNext\fP (\fBGooHashIter\fP **iter, \fBGooString\fP **key, int *val)"
.br
.ti -1c
.RI "void \fBkillIter\fP (\fBGooHashIter\fP **iter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file GooHash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
