.TH "GooList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GooList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGooList\fP (int sizeA)"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "\fBGooList\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "void * \fBget\fP (int i)"
.br
.ti -1c
.RI "void \fBput\fP (int i, void *p)"
.br
.ti -1c
.RI "void \fBappend\fP (void *p)"
.br
.ti -1c
.RI "void \fBappend\fP (\fBGooList\fP *list)"
.br
.ti -1c
.RI "void \fBinsert\fP (int i, void *p)"
.br
.ti -1c
.RI "void * \fBdel\fP (int i)"
.br
.ti -1c
.RI "void \fBsort\fP (int(*cmp)(const void *ptr1, const void *ptr2))"
.br
.ti -1c
.RI "void \fBreverse\fP ()"
.br
.ti -1c
.RI "void \fBsetAllocIncr\fP (int incA)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file GooList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
