.TH "GooString" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GooString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGooString\fP (const char *sA)"
.br
.ti -1c
.RI "\fBGooString\fP (const char *sA, int lengthA)"
.br
.ti -1c
.RI "\fBGooString\fP (\fBGooString\fP *str, int idx, int lengthA)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBSet\fP (const char *newStr, int newLen=CALC_STRING_LEN)"
.br
.ti -1c
.RI "\fBGooString\fP (const \fBGooString\fP *str)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBcopy\fP () const"
.br
.ti -1c
.RI "\fBGooString\fP (\fBGooString\fP *str1, \fBGooString\fP *str2)"
.br
.ti -1c
.RI "int \fBgetLength\fP () const"
.br
.ti -1c
.RI "char * \fBgetCString\fP ()"
.br
.ti -1c
.RI "const char * \fBgetCString\fP () const"
.br
.ti -1c
.RI "char \fBgetChar\fP (int i) const"
.br
.ti -1c
.RI "void \fBsetChar\fP (int i, char c)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBclear\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBappend\fP (char c)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBappend\fP (\fBGooString\fP *str)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBappend\fP (const char *str, int lengthA=CALC_STRING_LEN)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBappendf\fP (const char *fmt,\&.\&.\&.) GOOSTRING_FORMAT"
.br
.ti -1c
.RI "\fBGooString\fP * \fBappendfv\fP (const char *fmt, va_list argList)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBinsert\fP (int i, char c)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBinsert\fP (int i, \fBGooString\fP *str)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBinsert\fP (int i, const char *str, int lengthA=CALC_STRING_LEN)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBdel\fP (int i, int n=1)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBupperCase\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBlowerCase\fP ()"
.br
.ti -1c
.RI "int \fBcmp\fP (\fBGooString\fP *str) const"
.br
.ti -1c
.RI "int \fBcmpN\fP (\fBGooString\fP *str, int n) const"
.br
.ti -1c
.RI "int \fBcmp\fP (const char *sA) const"
.br
.ti -1c
.RI "int \fBcmpN\fP (const char *sA, int n) const"
.br
.ti -1c
.RI "GBool \fBendsWith\fP (const char *suffix) const"
.br
.ti -1c
.RI "GBool \fBhasUnicodeMarker\fP (void)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBsanitizedName\fP (GBool psmode)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGooString\fP * \fBfromInt\fP (int x)"
.br
.ti -1c
.RI "static \fBGooString\fP * \fBformat\fP (const char *fmt,\&.\&.\&.) GOOSTRING_FORMAT"
.br
.ti -1c
.RI "static \fBGooString\fP * \fBformatv\fP (const char *fmt, va_list argList)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCALC_STRING_LEN\fP = \-1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file GooString\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
