.TH "GooStringFormatArg" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GooStringFormatArg
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "Guint \fBui\fP"
.br
.ti -1c
.RI "long \fBl\fP"
.br
.ti -1c
.RI "Gulong \fBul\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file GooString\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
