.TH "gray_TWorker_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gray_TWorker_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ft_jmp_buf \fBjump_buffer\fP"
.br
.ti -1c
.RI "TCoord \fBex\fP"
.br
.ti -1c
.RI "TCoord \fBey\fP"
.br
.ti -1c
.RI "TPos \fBmin_ex\fP"
.br
.ti -1c
.RI "TPos \fBmax_ex\fP"
.br
.ti -1c
.RI "TPos \fBmin_ey\fP"
.br
.ti -1c
.RI "TPos \fBmax_ey\fP"
.br
.ti -1c
.RI "TPos \fBcount_ex\fP"
.br
.ti -1c
.RI "TPos \fBcount_ey\fP"
.br
.ti -1c
.RI "TArea \fBarea\fP"
.br
.ti -1c
.RI "TCoord \fBcover\fP"
.br
.ti -1c
.RI "int \fBinvalid\fP"
.br
.ti -1c
.RI "\fBPCell\fP \fBcells\fP"
.br
.ti -1c
.RI "FT_PtrDist \fBmax_cells\fP"
.br
.ti -1c
.RI "FT_PtrDist \fBnum_cells\fP"
.br
.ti -1c
.RI "TPos \fBx\fP"
.br
.ti -1c
.RI "TPos \fBy\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBbez_stack\fP [32 *3+1]"
.br
.ti -1c
.RI "int \fBlev_stack\fP [32]"
.br
.ti -1c
.RI "\fBFT_Outline\fP \fBoutline\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBclip_box\fP"
.br
.ti -1c
.RI "\fBFT_Span\fP \fBgray_spans\fP [FT_MAX_GRAY_SPANS]"
.br
.ti -1c
.RI "int \fBnum_gray_spans\fP"
.br
.ti -1c
.RI "FT_Raster_Span_Func \fBrender_span\fP"
.br
.ti -1c
.RI "void * \fBrender_span_data\fP"
.br
.ti -1c
.RI "int \fBspan_y\fP"
.br
.ti -1c
.RI "int \fBband_size\fP"
.br
.ti -1c
.RI "int \fBband_shoot\fP"
.br
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.ti -1c
.RI "long \fBbuffer_size\fP"
.br
.ti -1c
.RI "\fBPCell\fP * \fBycells\fP"
.br
.ti -1c
.RI "TPos \fBycount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 425 of file ftgrays\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
