.TH "GX_BlendRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GX_BlendRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_axis\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBnormalizedcoords\fP"
.br
.ti -1c
.RI "\fBFT_MM_Var\fP * \fBmmvar\fP"
.br
.ti -1c
.RI "FT_Offset \fBmmvar_len\fP"
.br
.ti -1c
.RI "FT_Bool \fBavar_checked\fP"
.br
.ti -1c
.RI "\fBGX_AVarSegment\fP \fBavar_segment\fP"
.br
.ti -1c
.RI "FT_UInt \fBtuplecount\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBtuplecoords\fP"
.br
.ti -1c
.RI "FT_UInt \fBgv_glyphcnt\fP"
.br
.ti -1c
.RI "FT_ULong * \fBglyphoffsets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file ttgxvar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
