.TH "GXV_XStateTable_ValidatorRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_XStateTable_ValidatorRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBentry_glyphoffset_fmt\fP"
.br
.ti -1c
.RI "void * \fBoptdata\fP"
.br
.ti -1c
.RI "GXV_XStateTable_Subtable_Setup_Func \fBsubtable_setup_func\fP"
.br
.ti -1c
.RI "GXV_XStateTable_Entry_Validate_Func \fBentry_validate_func\fP"
.br
.ti -1c
.RI "GXV_XStateTable_OptData_Load_Func \fBoptdata_load_func\fP"
.br
.ti -1c
.RI "FT_ULong \fBnClasses\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxClassID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file gxvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
