.TH "GXV_LookupValueDesc_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_LookupValueDesc_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBu\fP"
.br
.ti -1c
.RI "FT_Short \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file gxvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
