.TH "GXV_kern_DataRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_kern_DataRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GXV_kern_Version \fBversion\fP"
.br
.ti -1c
.RI "void * \fBsubtable_data\fP"
.br
.ti -1c
.RI "GXV_kern_Dialect \fBdialect_request\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file gxvkern\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
