.TH "GXV_StateTable_GlyphOffsetDesc_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_StateTable_GlyphOffsetDesc_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBuc\fP"
.br
.ti -1c
.RI "FT_UShort \fBu\fP"
.br
.ti -1c
.RI "FT_ULong \fBul\fP"
.br
.ti -1c
.RI "FT_Char \fBc\fP"
.br
.ti -1c
.RI "FT_Short \fBs\fP"
.br
.ti -1c
.RI "FT_Long \fBl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file gxvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
