.TH "GXV_odtect_RangeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_odtect_RangeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnRanges\fP"
.br
.ti -1c
.RI "\fBGXV_odtect_Data\fP \fBrange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 543 of file gxvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
