.TH "GXV_Feature_RegistryRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_Feature_RegistryRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Bool \fBexistence\fP"
.br
.ti -1c
.RI "FT_Bool \fBapple_reserved\fP"
.br
.ti -1c
.RI "FT_Bool \fBexclusive\fP"
.br
.ti -1c
.RI "FT_Byte \fBnSettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file gxvfeat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
