.TH "GXV_morx_subtable_type5_StateOptRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_morx_subtable_type5_StateOptRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBinsertionGlyphList\fP"
.br
.ti -1c
.RI "FT_ULong \fBinsertionGlyphList_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file gxvmorx5\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
