.TH "GXV_mort_featureRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_mort_featureRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBfeatureType\fP"
.br
.ti -1c
.RI "FT_UShort \fBfeatureSetting\fP"
.br
.ti -1c
.RI "FT_ULong \fBenableFlags\fP"
.br
.ti -1c
.RI "FT_ULong \fBdisableFlags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file gxvmort\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
