.TH "GXV_kern_subtable_fmt2_DataRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_kern_subtable_fmt2_DataRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBrowWidth\fP"
.br
.ti -1c
.RI "FT_UShort \fBarray\fP"
.br
.ti -1c
.RI "FT_UShort \fBoffset_min\fP [2]"
.br
.ti -1c
.RI "FT_UShort \fBoffset_max\fP [2]"
.br
.ti -1c
.RI "const FT_String * \fBclass_tag\fP [2]"
.br
.ti -1c
.RI "\fBGXV_odtect_Range\fP \fBodtect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 353 of file gxvkern\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
