.TH "GXV_ValidatorRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_ValidatorRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Validator \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "void * \fBtable_data\fP"
.br
.ti -1c
.RI "FT_ULong \fBsubtable_length\fP"
.br
.ti -1c
.RI "GXV_LookupValue_SignSpec \fBlookupval_sign\fP"
.br
.ti -1c
.RI "GXV_Lookup_Value_Validate_Func \fBlookupval_func\fP"
.br
.ti -1c
.RI "GXV_Lookup_Fmt4_Transit_Func \fBlookupfmt4_trans\fP"
.br
.ti -1c
.RI "FT_Bytes \fBlookuptbl_head\fP"
.br
.ti -1c
.RI "FT_UShort \fBmin_gid\fP"
.br
.ti -1c
.RI "FT_UShort \fBmax_gid\fP"
.br
.ti -1c
.RI "\fBGXV_StateTable_ValidatorRec\fP \fBstatetable\fP"
.br
.ti -1c
.RI "\fBGXV_XStateTable_ValidatorRec\fP \fBxstatetable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file gxvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
