.TH "GXV_feat_DataRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_feat_DataRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBreserved_size\fP"
.br
.ti -1c
.RI "FT_UShort \fBfeature\fP"
.br
.ti -1c
.RI "FT_UShort \fBsetting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file gxvfeat\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
