.TH "GXV_mort_subtable_type2_StateOptRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_mort_subtable_type2_StateOptRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBligActionTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBcomponentTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBligatureTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBligActionTable_length\fP"
.br
.ti -1c
.RI "FT_UShort \fBcomponentTable_length\fP"
.br
.ti -1c
.RI "FT_UShort \fBligatureTable_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file gxvmort2\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
