.TH "HeaderViewData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeaderViewData \- headerviews  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <headerviewdata\&.h>\fP
.PP
Inherits \fBAnimationData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeaderViewData\fP (QObject *parent, QWidget *target, int duration)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~HeaderViewData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "void \fBsetDuration\fP (int duration)"
.br
.RI "duration "
.ti -1c
.RI "bool \fBupdateState\fP (const QPoint &, bool)"
.br
.RI "update state "
.ti -1c
.RI "virtual \fBAnimation::Pointer\fP \fBanimation\fP (const QPoint &position) const"
.br
.RI "return \fBAnimation\fP associated to action at given position, if any "
.ti -1c
.RI "virtual qreal \fBopacity\fP (const QPoint &position) const"
.br
.RI "return opacity associated to action at given position, if any "
.in -1c
.PP
.RI "\fBcurrent index handling\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual qreal \fBcurrentOpacity\fP (void) const"
.br
.RI "current opacity "
.ti -1c
.RI "virtual void \fBsetCurrentOpacity\fP (qreal value)"
.br
.RI "current opacity "
.ti -1c
.RI "virtual int \fBcurrentIndex\fP (void) const"
.br
.RI "current index "
.ti -1c
.RI "virtual void \fBsetCurrentIndex\fP (int index)"
.br
.RI "current index "
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBcurrentIndexAnimation\fP (void) const"
.br
.RI "current index animation "
.in -1c
.in -1c
.PP
.RI "\fBprevious index handling\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual qreal \fBpreviousOpacity\fP (void) const"
.br
.RI "previous opacity "
.ti -1c
.RI "virtual void \fBsetPreviousOpacity\fP (qreal value)"
.br
.RI "previous opacity "
.ti -1c
.RI "virtual int \fBpreviousIndex\fP (void) const"
.br
.RI "previous index "
.ti -1c
.RI "virtual void \fBsetPreviousIndex\fP (int index)"
.br
.RI "previous index "
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBpreviousIndexAnimation\fP (void) const"
.br
.RI "previous index \fBAnimation\fP "
.in -1c
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetDirty\fP (void) const"
.br
.RI "dirty "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBcurrentOpacity\fP"
.br
.RI "declare opacity property "
.ti -1c
.RI "qreal \fBpreviousOpacity\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
headerviews 
.PP
Definition at line 33 of file headerviewdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
