.TH "Hints" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hints
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHints\fP (\fBBaseStream\fP *str, \fBLinearization\fP *linearization, \fBXRef\fP *xref, \fBSecurityHandler\fP *secHdlr)"
.br
.ti -1c
.RI "int \fBgetPageObjectNum\fP (int page)"
.br
.ti -1c
.RI "Goffset \fBgetPageOffset\fP (int page)"
.br
.ti -1c
.RI "std::vector< \fBByteRange\fP > * \fBgetPageRanges\fP (int page)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file Hints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
