.TH "html_text" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html_text
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhtml_text\fP (const \fBformatting_options\fP &_opt)"
.br
.ti -1c
.RI "const std::string & \fBstr\fP ()"
.br
.ti -1c
.RI "template<class T > void \fBwrite\fP (T s)"
.br
.ti -1c
.RI "std::string \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file fmt_opts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
