.TH "ImageSection" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageSection
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBy0\fP"
.br
.ti -1c
.RI "int \fBy1\fP"
.br
.ti -1c
.RI "int \fBia0\fP"
.br
.ti -1c
.RI "int \fBia1\fP"
.br
.ti -1c
.RI "int \fBib0\fP"
.br
.ti -1c
.RI "int \fBib1\fP"
.br
.ti -1c
.RI "SplashCoord \fBxa0\fP"
.br
.ti -1c
.RI "SplashCoord \fBya0\fP"
.br
.ti -1c
.RI "SplashCoord \fBxa1\fP"
.br
.ti -1c
.RI "SplashCoord \fBya1\fP"
.br
.ti -1c
.RI "SplashCoord \fBdxdya\fP"
.br
.ti -1c
.RI "SplashCoord \fBxb0\fP"
.br
.ti -1c
.RI "SplashCoord \fByb0\fP"
.br
.ti -1c
.RI "SplashCoord \fBxb1\fP"
.br
.ti -1c
.RI "SplashCoord \fByb1\fP"
.br
.ti -1c
.RI "SplashCoord \fBdxdyb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file Splash\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
