.TH "ImageStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageStream\fP (\fBStream\fP *strA, int widthA, int nCompsA, int nBitsA)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "GBool \fBgetPixel\fP (Guchar *pix)"
.br
.ti -1c
.RI "Guchar * \fBgetLine\fP ()"
.br
.ti -1c
.RI "void \fBskipLine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 362 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
