.TH "ImgWriter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImgWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNetPBMWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBinit\fP (FILE *f, int width, int height, int hDPI, int vDPI)=0"
.br
.ti -1c
.RI "virtual bool \fBwritePointers\fP (unsigned char **rowPointers, int rowCount)=0"
.br
.ti -1c
.RI "virtual bool \fBwriteRow\fP (unsigned char **row)=0"
.br
.ti -1c
.RI "virtual bool \fBclose\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBsupportCMYK\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file ImgWriter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
