.TH "inflate_codes_state" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inflate_codes_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "inflate_codes_mode \fBmode\fP"
.br
.ti -1c
.RI "uInt \fBlen\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      inflate_huft * \fBtree\fP"
.br
.ti -1c
.RI "      uInt \fBneed\fP"
.br
.ti -1c
.RI "   } \fBcode\fP"
.br
.ti -1c
.RI "   uInt \fBlit\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uInt \fBget\fP"
.br
.ti -1c
.RI "      uInt \fBdist\fP"
.br
.ti -1c
.RI "   } \fBcopy\fP"
.br
.ti -1c
.RI "} \fBsub\fP"
.br
.ti -1c
.RI "Byte \fBlbits\fP"
.br
.ti -1c
.RI "Byte \fBdbits\fP"
.br
.ti -1c
.RI "inflate_huft * \fBltree\fP"
.br
.ti -1c
.RI "inflate_huft * \fBdtree\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file infcodes\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
