.TH "inflate_blocks_state" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inflate_blocks_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "inflate_block_mode \fBmode\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uInt \fBleft\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uInt \fBtable\fP"
.br
.ti -1c
.RI "      uInt \fBindex\fP"
.br
.ti -1c
.RI "      uIntf * \fBblens\fP"
.br
.ti -1c
.RI "      uInt \fBbb\fP"
.br
.ti -1c
.RI "      inflate_huft * \fBtb\fP"
.br
.ti -1c
.RI "   } \fBtrees\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      inflate_codes_statef * \fBcodes\fP"
.br
.ti -1c
.RI "   } \fBdecode\fP"
.br
.ti -1c
.RI "} \fBsub\fP"
.br
.ti -1c
.RI "uInt \fBlast\fP"
.br
.ti -1c
.RI "uInt \fBbitk\fP"
.br
.ti -1c
.RI "uLong \fBbitb\fP"
.br
.ti -1c
.RI "inflate_huft * \fBhufts\fP"
.br
.ti -1c
.RI "Bytef * \fBwindow\fP"
.br
.ti -1c
.RI "Bytef * \fBend\fP"
.br
.ti -1c
.RI "Bytef * \fBread\fP"
.br
.ti -1c
.RI "Bytef * \fBwrite\fP"
.br
.ti -1c
.RI "check_func \fBcheckfn\fP"
.br
.ti -1c
.RI "uLong \fBcheck\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file infutil\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
