.TH "inflate_huft_s" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inflate_huft_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      Byte \fBExop\fP"
.br
.ti -1c
.RI "      Byte \fBBits\fP"
.br
.ti -1c
.RI "   } \fBwhat\fP"
.br
.ti -1c
.RI "   uInt \fBpad\fP"
.br
.ti -1c
.RI "} \fBword\fP"
.br
.ti -1c
.RI "uInt \fBbase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file inftrees\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
