.TH "Interval< T, K >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interval< T, K >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterval\fP (K s, K e, const T &v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "K \fBstart\fP"
.br
.ti -1c
.RI "K \fBstop\fP"
.br
.ti -1c
.RI "T \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, typename K = int>
.br
class Interval< T, K >"

.PP
Definition at line 12 of file IntervalTree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
