.TH "internal_state" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "inflate_mode \fBmode\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uInt \fBmethod\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uLong \fBwas\fP"
.br
.ti -1c
.RI "      uLong \fBneed\fP"
.br
.ti -1c
.RI "   } \fBcheck\fP"
.br
.ti -1c
.RI "   uInt \fBmarker\fP"
.br
.ti -1c
.RI "} \fBsub\fP"
.br
.ti -1c
.RI "int \fBnowrap\fP"
.br
.ti -1c
.RI "uInt \fBwbits\fP"
.br
.ti -1c
.RI "inflate_blocks_statef * \fBblocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file inflate\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
