.TH "IPAddressFamily_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPAddressFamily_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBaddressFamily\fP"
.br
.ti -1c
.RI "\fBIPAddressChoice\fP * \fBipAddressChoice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 780 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
