.TH "ITC_mesg" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITC_mesg
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBM_def_rank\fP, \fBM_ifc_anoff\fP, \fBM_ifc_aupar\fP, \fBM_ifc_chconf\fP, \fBM_ifc_dipar\fP, \fBM_ifc_edit\fP, \fBM_ifc_ifelm\fP, \fBM_ifc_init\fP, \fBM_ifc_preset\fP, \fBM_ifc_retune\fP, \fBM_ifc_txtip\fP, \fBM_midi_info\fP, and \fBM_new_divis\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBITC_mesg\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
