.TH "JArithmeticDecoder" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JArithmeticDecoder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetStream\fP (\fBStream\fP *strA)"
.br
.ti -1c
.RI "void \fBsetStream\fP (\fBStream\fP *strA, int dataLenA)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP (int dataLenA)"
.br
.ti -1c
.RI "void \fBcleanup\fP ()"
.br
.ti -1c
.RI "int \fBdecodeBit\fP (Guint context, \fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "int \fBdecodeByte\fP (Guint context, \fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "GBool \fBdecodeInt\fP (int *x, \fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "Guint \fBdecodeIAID\fP (Guint codeLen, \fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "void \fBresetByteCounter\fP ()"
.br
.ti -1c
.RI "Guint \fBgetByteCounter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file JArithmeticDecoder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
