.TH "JBIG2CodeTable" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBIG2CodeTable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBIG2Segment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJBIG2CodeTable\fP (Guint segNumA, \fBJBIG2HuffmanTable\fP *tableA)"
.br
.ti -1c
.RI "virtual JBIG2SegmentType \fBgetType\fP ()"
.br
.ti -1c
.RI "\fBJBIG2HuffmanTable\fP * \fBgetHuffTable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1145 of file JBIG2Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
