.TH "JBIG2SymbolDict" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBIG2SymbolDict
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBIG2Segment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJBIG2SymbolDict\fP (Guint segNumA, Guint sizeA)"
.br
.ti -1c
.RI "virtual JBIG2SegmentType \fBgetType\fP ()"
.br
.ti -1c
.RI "Guint \fBgetSize\fP ()"
.br
.ti -1c
.RI "void \fBsetBitmap\fP (Guint idx, \fBJBIG2Bitmap\fP *bitmap)"
.br
.ti -1c
.RI "\fBJBIG2Bitmap\fP * \fBgetBitmap\fP (Guint idx)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "void \fBsetGenericRegionStats\fP (\fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "void \fBsetRefinementRegionStats\fP (\fBJArithmeticDecoderStats\fP *stats)"
.br
.ti -1c
.RI "\fBJArithmeticDecoderStats\fP * \fBgetGenericRegionStats\fP ()"
.br
.ti -1c
.RI "\fBJArithmeticDecoderStats\fP * \fBgetRefinementRegionStats\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1043 of file JBIG2Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
