.TH "JBIG2Bitmap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBIG2Bitmap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJBIG2Segment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJBIG2Bitmap\fP (Guint segNumA, int wA, int hA)"
.br
.ti -1c
.RI "virtual JBIG2SegmentType \fBgetType\fP ()"
.br
.ti -1c
.RI "\fBJBIG2Bitmap\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "\fBJBIG2Bitmap\fP * \fBgetSlice\fP (Guint x, Guint y, Guint wA, Guint hA)"
.br
.ti -1c
.RI "void \fBexpand\fP (int newH, Guint pixel)"
.br
.ti -1c
.RI "void \fBclearToZero\fP ()"
.br
.ti -1c
.RI "void \fBclearToOne\fP ()"
.br
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "int \fBgetLineSize\fP ()"
.br
.ti -1c
.RI "int \fBgetPixel\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBsetPixel\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBclearPixel\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBgetPixelPtr\fP (int x, int y, \fBJBIG2BitmapPtr\fP *ptr)"
.br
.ti -1c
.RI "int \fBnextPixel\fP (\fBJBIG2BitmapPtr\fP *ptr)"
.br
.ti -1c
.RI "void \fBduplicateRow\fP (int yDest, int ySrc)"
.br
.ti -1c
.RI "void \fBcombine\fP (\fBJBIG2Bitmap\fP *bitmap, int x, int y, Guint combOp)"
.br
.ti -1c
.RI "Guchar * \fBgetDataPtr\fP ()"
.br
.ti -1c
.RI "int \fBgetDataSize\fP ()"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 673 of file JBIG2Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
