.TH "JBIG2MMRDecoder" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBIG2MMRDecoder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetStream\fP (\fBStream\fP *strA)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "int \fBget2DCode\fP ()"
.br
.ti -1c
.RI "int \fBgetBlackCode\fP ()"
.br
.ti -1c
.RI "int \fBgetWhiteCode\fP ()"
.br
.ti -1c
.RI "Guint \fBget24Bits\fP ()"
.br
.ti -1c
.RI "void \fBskipTo\fP (Guint length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 463 of file JBIG2Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
