.TH "JBIG2Segment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JBIG2Segment
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJBIG2Bitmap\fP, \fBJBIG2CodeTable\fP, \fBJBIG2PatternDict\fP, and \fBJBIG2SymbolDict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJBIG2Segment\fP (Guint segNumA)"
.br
.ti -1c
.RI "void \fBsetSegNum\fP (Guint segNumA)"
.br
.ti -1c
.RI "Guint \fBgetSegNum\fP ()"
.br
.ti -1c
.RI "virtual JBIG2SegmentType \fBgetType\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 649 of file JBIG2Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
