.TH "JPXColorSpecCIELab" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXColorSpecCIELab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBrl\fP"
.br
.ti -1c
.RI "Guint \fBol\fP"
.br
.ti -1c
.RI "Guint \fBra\fP"
.br
.ti -1c
.RI "Guint \fBoa\fP"
.br
.ti -1c
.RI "Guint \fBrb\fP"
.br
.ti -1c
.RI "Guint \fBob\fP"
.br
.ti -1c
.RI "Guint \fBil\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
