.TH "JPXColorSpec" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXColorSpec
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBmeth\fP"
.br
.ti -1c
.RI "int \fBprec\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBJPXColorSpecEnumerated\fP \fBenumerated\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
