.TH "JPXCodeBlock" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXCodeBlock
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBx0\fP"
.br
.ti -1c
.RI "Guint \fBy0\fP"
.br
.ti -1c
.RI "Guint \fBx1\fP"
.br
.ti -1c
.RI "Guint \fBy1\fP"
.br
.ti -1c
.RI "GBool \fBseen\fP"
.br
.ti -1c
.RI "Guint \fBlBlock\fP"
.br
.ti -1c
.RI "Guint \fBnextPass\fP"
.br
.ti -1c
.RI "Guint \fBnZeroBitPlanes\fP"
.br
.ti -1c
.RI "Guint \fBincluded\fP"
.br
.ti -1c
.RI "Guint \fBnCodingPasses\fP"
.br
.ti -1c
.RI "Guint * \fBdataLen\fP"
.br
.ti -1c
.RI "Guint \fBdataLenSize\fP"
.br
.ti -1c
.RI "int * \fBcoeffs\fP"
.br
.ti -1c
.RI "char * \fBtouched\fP"
.br
.ti -1c
.RI "Gushort \fBlen\fP"
.br
.ti -1c
.RI "\fBJArithmeticDecoder\fP * \fBarithDecoder\fP"
.br
.ti -1c
.RI "\fBJArithmeticDecoderStats\fP * \fBstats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
