.TH "JPXPalette" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXPalette
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBnEntries\fP"
.br
.ti -1c
.RI "Guint \fBnComps\fP"
.br
.ti -1c
.RI "Guint * \fBbpc\fP"
.br
.ti -1c
.RI "int * \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
