.TH "JPXResLevel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXResLevel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBprecinctWidth\fP"
.br
.ti -1c
.RI "Guint \fBprecinctHeight\fP"
.br
.ti -1c
.RI "Guint \fBx0\fP"
.br
.ti -1c
.RI "Guint \fBy0\fP"
.br
.ti -1c
.RI "Guint \fBx1\fP"
.br
.ti -1c
.RI "Guint \fBy1\fP"
.br
.ti -1c
.RI "Guint \fBbx0\fP [3]"
.br
.ti -1c
.RI "Guint \fBby0\fP [3]"
.br
.ti -1c
.RI "Guint \fBbx1\fP [3]"
.br
.ti -1c
.RI "Guint \fBby1\fP [3]"
.br
.ti -1c
.RI "\fBJPXPrecinct\fP * \fBprecincts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
