.TH "JPXStreamPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXStreamPrivate
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "opj_image_t * \fBimage\fP"
.br
.ti -1c
.RI "int \fBcounter\fP"
.br
.ti -1c
.RI "int \fBccounter\fP"
.br
.ti -1c
.RI "int \fBnpixels\fP"
.br
.ti -1c
.RI "int \fBncomps\fP"
.br
.ti -1c
.RI "GBool \fBindexed\fP"
.br
.ti -1c
.RI "GBool \fBinited\fP"
.br
.ti -1c
.RI "int \fBsmaskInData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file JPEG2000Stream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
