.TH "JPXSubband" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXSubband
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBx0\fP"
.br
.ti -1c
.RI "Guint \fBy0\fP"
.br
.ti -1c
.RI "Guint \fBx1\fP"
.br
.ti -1c
.RI "Guint \fBy1\fP"
.br
.ti -1c
.RI "Guint \fBnXCBs\fP"
.br
.ti -1c
.RI "Guint \fBnYCBs\fP"
.br
.ti -1c
.RI "Guint \fBmaxTTLevel\fP"
.br
.ti -1c
.RI "\fBJPXTagTreeNode\fP * \fBinclusion\fP"
.br
.ti -1c
.RI "\fBJPXTagTreeNode\fP * \fBzeroBitPlane\fP"
.br
.ti -1c
.RI "\fBJPXCodeBlock\fP * \fBcbs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
