.TH "JPXTile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXTile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBinit\fP"
.br
.ti -1c
.RI "Guint \fBprogOrder\fP"
.br
.ti -1c
.RI "Guint \fBnLayers\fP"
.br
.ti -1c
.RI "Guint \fBmultiComp\fP"
.br
.ti -1c
.RI "Guint \fBx0\fP"
.br
.ti -1c
.RI "Guint \fBy0\fP"
.br
.ti -1c
.RI "Guint \fBx1\fP"
.br
.ti -1c
.RI "Guint \fBy1\fP"
.br
.ti -1c
.RI "Guint \fBmaxNDecompLevels\fP"
.br
.ti -1c
.RI "Guint \fBcomp\fP"
.br
.ti -1c
.RI "Guint \fBres\fP"
.br
.ti -1c
.RI "Guint \fBprecinct\fP"
.br
.ti -1c
.RI "Guint \fBlayer\fP"
.br
.ti -1c
.RI "\fBJPXTileComp\fP * \fBtileComps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
