.TH "JPXTileComp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPXTileComp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBsgned\fP"
.br
.ti -1c
.RI "Guint \fBprec\fP"
.br
.ti -1c
.RI "Guint \fBhSep\fP"
.br
.ti -1c
.RI "Guint \fBvSep\fP"
.br
.ti -1c
.RI "Guint \fBstyle\fP"
.br
.ti -1c
.RI "Guint \fBnDecompLevels\fP"
.br
.ti -1c
.RI "Guint \fBcodeBlockW\fP"
.br
.ti -1c
.RI "Guint \fBcodeBlockH\fP"
.br
.ti -1c
.RI "Guint \fBcodeBlockStyle\fP"
.br
.ti -1c
.RI "Guint \fBtransform\fP"
.br
.ti -1c
.RI "Guint \fBquantStyle\fP"
.br
.ti -1c
.RI "Guint * \fBquantSteps\fP"
.br
.ti -1c
.RI "Guint \fBnQuantSteps\fP"
.br
.ti -1c
.RI "Guint \fBx0\fP"
.br
.ti -1c
.RI "Guint \fBy0\fP"
.br
.ti -1c
.RI "Guint \fBx1\fP"
.br
.ti -1c
.RI "Guint \fBy1\fP"
.br
.ti -1c
.RI "Guint \fBw\fP"
.br
.ti -1c
.RI "Guint \fBcbW\fP"
.br
.ti -1c
.RI "Guint \fBcbH\fP"
.br
.ti -1c
.RI "int * \fBdata\fP"
.br
.ti -1c
.RI "int * \fBbuf\fP"
.br
.ti -1c
.RI "\fBJPXResLevel\fP * \fBresLevels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file JPXStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
