.TH "killing_ptr_vector< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
killing_ptr_vector< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits vector< T *>\&.
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class killing_ptr_vector< T >"

.PP
Definition at line 41 of file rtf_table\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
