.TH "KQOAuthUtils" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KQOAuthUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBhmac_sha1\fP (const QString &message, const QString &key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file kqoauthutils\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QString KQOAuthUtils::hmac_sha1 (const QString & message, const QString & key)\fC [static]\fP"
KQOAuth - An OAuth authentication library for Qt\&.
.PP
Author: Johan Paul (johan.paul@gmail.com) http://www.johanpaul.com
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
KQOAuth is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with KQOAuth\&. If not, see http://www.gnu.org/licenses/\&. 
.PP
Definition at line 33 of file kqoauthutils\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
