.TH "KQOAuthAuthReplyServerPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KQOAuthAuthReplyServerPrivate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kqoauthauthreplyserver_p\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBonIncomingConnection\fP ()"
.br
.ti -1c
.RI "void \fBonBytesReady\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKQOAuthAuthReplyServerPrivate\fP (\fBKQOAuthAuthReplyServer\fP *parent)"
.br
.ti -1c
.RI "QMultiMap< QString, QString > \fBparseQueryParams\fP (QByteArray *sdata)"
.br
.ti -1c
.RI "\fBQ_DECLARE_PUBLIC\fP (\fBKQOAuthAuthReplyServer\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKQOAuthAuthReplyServer\fP * \fBq_ptr\fP"
.br
.ti -1c
.RI "QTcpSocket * \fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
KQOAuth - An OAuth authentication library for Qt\&.
.PP
Author: Johan Paul (johan.paul@gmail.com) http://www.johanpaul.com
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
KQOAuth is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with KQOAuth\&. If not, see http://www.gnu.org/licenses/\&. 
.PP
Definition at line 29 of file kqoauthauthreplyserver_p\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KQOAuthAuthReplyServerPrivate::KQOAuthAuthReplyServerPrivate (\fBKQOAuthAuthReplyServer\fP * parent)"
KQOAuth - An OAuth authentication library for Qt\&.
.PP
Author: Johan Paul (johan.paul@gmail.com) http://www.johanpaul.com
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
KQOAuth is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with KQOAuth\&. If not, see http://www.gnu.org/licenses/\&. 
.PP
Definition at line 30 of file kqoauthauthreplyserver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
