.TH "KQOAuthRequest_XAuth" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KQOAuthRequest_XAuth
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKQOAuthRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKQOAuthRequest_XAuth\fP (QObject *parent=0)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "void \fBsetXAuthLogin\fP (const QString &username='', const QString &password='')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file kqoauthrequest_xauth\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KQOAuthRequest_XAuth::KQOAuthRequest_XAuth (QObject * parent = \fC0\fP)"
Public implementations\&. 
.PP
Definition at line 40 of file kqoauthrequest_xauth\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool KQOAuthRequest_XAuth::isValid () const\fC [virtual]\fP"
These methods can be overridden in child classes which are different types of OAuth requests\&. 
.PP
Reimplemented from \fBKQOAuthRequest\fP\&.
.PP
Definition at line 46 of file kqoauthrequest_xauth\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
