.TH "kssl_ctx_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kssl_ctx_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBservice_name\fP"
.br
.ti -1c
.RI "char * \fBservice_host\fP"
.br
.ti -1c
.RI "char * \fBclient_princ\fP"
.br
.ti -1c
.RI "char * \fBkeytab_file\fP"
.br
.ti -1c
.RI "char * \fBcred_cache\fP"
.br
.ti -1c
.RI "krb5_enctype \fBenctype\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "krb5_octet FAR * \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file kssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
