.TH "LabelData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LabelData \- generic data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <labeldata\&.h>\fP
.PP
Inherits \fBTransitionData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLabelData\fP (QObject *, QLabel *, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~LabelData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.RI "event filter "
.ti -1c
.RI "bool \fBisLocked\fP (void) const"
.br
.RI "returns true if animations are locked "
.ti -1c
.RI "void \fBlockAnimations\fP (void)"
.br
.RI "start lock animation timer "
.ti -1c
.RI "void \fBunlockAnimations\fP (void)"
.br
.RI "start lock animation timer "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBinitializeAnimation\fP (void)"
.br
.RI "initialize animation "
.ti -1c
.RI "virtual bool \fBanimate\fP (void)"
.br
.RI "animate "
.ti -1c
.RI "virtual void \fBtargetDestroyed\fP (void)"
.br
.RI "called when target is destroyed "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBtimerEvent\fP (QTimerEvent *)"
.br
.RI "timer event "
.in -1c
.SH "Detailed Description"
.PP 
generic data 
.PP
Definition at line 33 of file labeldata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
