.TH "Ladspa_CS_chorus3" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ladspa_CS_chorus3
.SH SYNOPSIS
.br
.PP
.PP
Inherits LadspaPlugin\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBINPUT\fP, \fBOUTPUT1\fP, \fBOUTPUT2\fP, \fBOUTPUT3\fP, \fBDELAY\fP, \fBFREQ1\fP, \fBTMOD1\fP, \fBFREQ2\fP, \fBTMOD2\fP, \fBNPORT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLadspa_CS_chorus3\fP (unsigned long fsam)"
.br
.ti -1c
.RI "virtual void \fBsetport\fP (unsigned long port, LADSPA_Data *data)"
.br
.ti -1c
.RI "virtual void \fBactive\fP (bool act)"
.br
.ti -1c
.RI "virtual void \fBrunproc\fP (unsigned long len, bool add)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file cs_chorus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
