.TH "bww2mxml/lexer.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/lexer.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QMap>\fP
.br
\fC#include <QtCore/QString>\fP
.br
\fC#include <QtCore/QStringList>\fP
.br
\fC#include <QtCore/QTextStream>\fP
.br
\fC#include 'symbols\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBww::Lexer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of class \fBLexer\fP 
.PP
Definition in file \fBlexer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
