.TH "bww2mxml/lexer.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/lexer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QRegExp>\fP
.br
\fC#include <QtCore/QtDebug>\fP
.br
\fC#include 'lexer\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BWW file lexical analysis\&.
.PP
Loosely based on BWW file format - BNF specification by tjm found in http://forums.bobdunsire.com/forums/showthread.php?t=123219 
.PP
Definition in file \fBlexer\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
