.TH "Lexer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lexer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLexer\fP (\fBXRef\fP *xrefA, \fBStream\fP *str)"
.br
.ti -1c
.RI "\fBLexer\fP (\fBXRef\fP *xrefA, \fBObject\fP *obj)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObj\fP (\fBObject\fP *obj, int objNum=\-1)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObj\fP (\fBObject\fP *obj, const char *cmdA, int objNum)"
.br
.ti -1c
.RI "void \fBskipToNextLine\fP ()"
.br
.ti -1c
.RI "void \fBskipChar\fP ()"
.br
.ti -1c
.RI "\fBStream\fP * \fBgetStream\fP ()"
.br
.ti -1c
.RI "Goffset \fBgetPos\fP ()"
.br
.ti -1c
.RI "void \fBsetPos\fP (Goffset pos, int dir=0)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GBool \fBisSpace\fP (int c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlookCharLastValueCached\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBLOOK_VALUE_NOT_CACHED\fP = \-3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file Lexer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
