.TH "LinkDest" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkDest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkDest\fP (\fBArray\fP *a)"
.br
.ti -1c
.RI "\fBLinkDest\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "LinkDestKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "GBool \fBisPageRef\fP ()"
.br
.ti -1c
.RI "int \fBgetPageNum\fP ()"
.br
.ti -1c
.RI "\fBRef\fP \fBgetPageRef\fP ()"
.br
.ti -1c
.RI "double \fBgetLeft\fP ()"
.br
.ti -1c
.RI "double \fBgetBottom\fP ()"
.br
.ti -1c
.RI "double \fBgetRight\fP ()"
.br
.ti -1c
.RI "double \fBgetTop\fP ()"
.br
.ti -1c
.RI "double \fBgetZoom\fP ()"
.br
.ti -1c
.RI "GBool \fBgetChangeLeft\fP ()"
.br
.ti -1c
.RI "GBool \fBgetChangeTop\fP ()"
.br
.ti -1c
.RI "GBool \fBgetChangeZoom\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file Link\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
