.TH "LinkUnknown" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkUnknown
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLinkAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkUnknown\fP (char *actionA)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "virtual LinkActionKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetAction\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 450 of file Link\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
