.TH "LinkRendition" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkRendition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLinkAction\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBRenditionOperation\fP { \fBNoRendition\fP, \fBPlayRendition\fP, \fBStopRendition\fP, \fBPauseRendition\fP, \fBResumeRendition\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkRendition\fP (\fBObject\fP *Obj)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "virtual LinkActionKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "GBool \fBhasRenditionObject\fP ()"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetRenditionObject\fP ()"
.br
.ti -1c
.RI "GBool \fBhasScreenAnnot\fP ()"
.br
.ti -1c
.RI "\fBRef\fP \fBgetScreenAnnot\fP ()"
.br
.ti -1c
.RI "\fBRenditionOperation\fP \fBgetOperation\fP ()"
.br
.ti -1c
.RI "\fBMediaRendition\fP * \fBgetMedia\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetScript\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 321 of file Link\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLinkRendition::RenditionOperation\fP"
Describes the possible rendition operations\&. 
.PP
Definition at line 326 of file Link\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
