.TH "LinkSound" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkSound
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLinkAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkSound\fP (\fBObject\fP *soundObj)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "virtual LinkActionKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "double \fBgetVolume\fP ()"
.br
.ti -1c
.RI "GBool \fBgetSynchronous\fP ()"
.br
.ti -1c
.RI "GBool \fBgetRepeat\fP ()"
.br
.ti -1c
.RI "GBool \fBgetMix\fP ()"
.br
.ti -1c
.RI "\fBSound\fP * \fBgetSound\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 369 of file Link\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
