.TH "LinkAction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkAction
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLinkGoTo\fP, \fBLinkGoToR\fP, \fBLinkJavaScript\fP, \fBLinkLaunch\fP, \fBLinkMovie\fP, \fBLinkNamed\fP, \fBLinkOCGState\fP, \fBLinkRendition\fP, \fBLinkSound\fP, \fBLinkUnknown\fP, and \fBLinkURI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual GBool \fBisOk\fP ()=0"
.br
.ti -1c
.RI "virtual LinkActionKind \fBgetKind\fP ()=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLinkAction\fP * \fBparseDest\fP (\fBObject\fP *obj)"
.br
.ti -1c
.RI "static \fBLinkAction\fP * \fBparseAction\fP (\fBObject\fP *obj, \fBGooString\fP *baseURI=NULL)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file Link\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
