.TH "LocalPDFDocBuilder" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalPDFDocBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPDFDocBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPDFDoc\fP * \fBbuildPDFDoc\fP (const \fBGooString\fP &uri, \fBGooString\fP *ownerPassword=NULL, \fBGooString\fP *userPassword=NULL, void *guiDataA=NULL)"
.br
.ti -1c
.RI "GBool \fBsupports\fP (const \fBGooString\fP &uri)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file LocalPDFDocBuilder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
