.TH "M_def_rank" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_def_rank
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_def_rank\fP (int type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_divis\fP"
.br
.ti -1c
.RI "int \fB_rank\fP"
.br
.ti -1c
.RI "int \fB_group\fP"
.br
.ti -1c
.RI "int \fB_ifelm\fP"
.br
.ti -1c
.RI "float \fB_fsamp\fP"
.br
.ti -1c
.RI "float \fB_fbase\fP"
.br
.ti -1c
.RI "float * \fB_scale\fP"
.br
.ti -1c
.RI "\fBAddsynth\fP * \fB_sdef\fP"
.br
.ti -1c
.RI "\fBRankwave\fP * \fB_wave\fP"
.br
.ti -1c
.RI "const char * \fB_path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
