.TH "M_ifc_edit" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_edit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_edit\fP (int type, int group, int ifelm, \fBAddsynth\fP *synth)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_group\fP"
.br
.ti -1c
.RI "int \fB_ifelm\fP"
.br
.ti -1c
.RI "\fBAddsynth\fP * \fB_synth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 308 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
