.TH "M_ifc_aupar" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_aupar
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_aupar\fP (int s, int a, int p, float v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_srcid\fP"
.br
.ti -1c
.RI "int \fB_asect\fP"
.br
.ti -1c
.RI "int \fB_parid\fP"
.br
.ti -1c
.RI "float \fB_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 203 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
