.TH "M_ifc_init" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_init
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fB_stops\fP"
.br
.ti -1c
.RI "const char * \fB_waves\fP"
.br
.ti -1c
.RI "const char * \fB_instr\fP"
.br
.ti -1c
.RI "const char * \fB_appid\fP"
.br
.ti -1c
.RI "int \fB_client\fP"
.br
.ti -1c
.RI "int \fB_ipport\fP"
.br
.ti -1c
.RI "int \fB_nasect\fP"
.br
.ti -1c
.RI "int \fB_nkeybd\fP"
.br
.ti -1c
.RI "int \fB_ndivis\fP"
.br
.ti -1c
.RI "int \fB_ngroup\fP"
.br
.ti -1c
.RI "int \fB_ntempe\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fB_label\fP"
.br
.ti -1c
.RI "   int \fB_flags\fP"
.br
.ti -1c
.RI "} \fB_keybdd\fP [NKEYBD]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fB_label\fP"
.br
.ti -1c
.RI "   int \fB_asect\fP"
.br
.ti -1c
.RI "   int \fB_flags\fP"
.br
.ti -1c
.RI "} \fB_divisd\fP [NDIVIS]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fB_label\fP"
.br
.ti -1c
.RI "   int \fB_nifelm\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      const char * \fB_label\fP"
.br
.ti -1c
.RI "      const char * \fB_mnemo\fP"
.br
.ti -1c
.RI "      int \fB_type\fP"
.br
.ti -1c
.RI "   } \fB_ifelmd\fP [32]"
.br
.ti -1c
.RI "} \fB_groupd\fP [8]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fB_label\fP"
.br
.ti -1c
.RI "   const char * \fB_mnemo\fP"
.br
.ti -1c
.RI "} \fB_temped\fP [16]"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 146 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
