.TH "M_ifc_preset" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_preset
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_preset\fP (int type, int bank, int pres, int stat, uint32_t *bits)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_bank\fP"
.br
.ti -1c
.RI "int \fB_pres\fP"
.br
.ti -1c
.RI "int \fB_stat\fP"
.br
.ti -1c
.RI "uint32_t \fB_bits\fP [NGROUP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 287 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
