.TH "M_ifc_retune" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_retune
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_retune\fP (float f, int t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fB_freq\fP"
.br
.ti -1c
.RI "int \fB_temp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 241 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
