.TH "M_ifc_chconf" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_chconf
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_chconf\fP (int type, int index, uint16_t *bits)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_index\fP"
.br
.ti -1c
.RI "uint16_t \fB_bits\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 270 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
