.TH "M_ifc_ifelm" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_ifc_ifelm
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBM_ifc_ifelm\fP (int type, int g, int i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_group\fP"
.br
.ti -1c
.RI "int \fB_ifelm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
