.TH "M_midi_info" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_midi_info
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBITC_mesg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_client\fP"
.br
.ti -1c
.RI "int \fB_ipport\fP"
.br
.ti -1c
.RI "uint16_t \fB_chbits\fP [16]"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 97 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
