.TH "MarkedContentOutputDev" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MarkedContentOutputDev
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutputDev\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarkedContentOutputDev\fP (int mcidA)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBupsideDown\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBuseDrawChar\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBinterpretType3Chars\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBneedNonText\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBneedCharCount\fP ()"
.br
.ti -1c
.RI "virtual void \fBstartPage\fP (int pageNum, \fBGfxState\fP *state, \fBXRef\fP *xref)"
.br
.ti -1c
.RI "virtual void \fBendPage\fP ()"
.br
.ti -1c
.RI "virtual void \fBdrawChar\fP (\fBGfxState\fP *state, double xx, double yy, double dx, double dy, double ox, double oy, CharCode c, int nBytes, Unicode *u, int uLen)"
.br
.ti -1c
.RI "virtual void \fBbeginMarkedContent\fP (char *name, \fBDict\fP *properties)"
.br
.ti -1c
.RI "virtual void \fBendMarkedContent\fP (\fBGfxState\fP *state)"
.br
.ti -1c
.RI "const TextSpanArray & \fBgetTextSpans\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file MarkedContentOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
