.TH "Matrix" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (double xx, double yx, double xy, double yy, double x0, double y0)"
.br
.ti -1c
.RI "GBool \fBinvertTo\fP (\fBMatrix\fP *other) const"
.br
.ti -1c
.RI "void \fBtranslate\fP (double tx, double ty)"
.br
.ti -1c
.RI "void \fBscale\fP (double sx, double sy)"
.br
.ti -1c
.RI "void \fBtransform\fP (double x, double y, double *tx, double *ty) const"
.br
.ti -1c
.RI "double \fBdeterminant\fP () const"
.br
.ti -1c
.RI "double \fBnorm\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBm\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file GfxState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
