.TH "MCentralFileHeader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCentralFileHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalFileHeader\fP \fBtoLocalHeader\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uchar \fBsignature\fP [4]"
.br
.ti -1c
.RI "uchar \fBversion_made\fP [2]"
.br
.ti -1c
.RI "uchar \fBversion_needed\fP [2]"
.br
.ti -1c
.RI "uchar \fBgeneral_purpose_bits\fP [2]"
.br
.ti -1c
.RI "uchar \fBcompression_method\fP [2]"
.br
.ti -1c
.RI "uchar \fBlast_mod_file\fP [4]"
.br
.ti -1c
.RI "uchar \fBcrc_32\fP [4]"
.br
.ti -1c
.RI "uchar \fBcompressed_size\fP [4]"
.br
.ti -1c
.RI "uchar \fBuncompressed_size\fP [4]"
.br
.ti -1c
.RI "uchar \fBfile_name_length\fP [2]"
.br
.ti -1c
.RI "uchar \fBextra_field_length\fP [2]"
.br
.ti -1c
.RI "uchar \fBfile_comment_length\fP [2]"
.br
.ti -1c
.RI "uchar \fBdisk_start\fP [2]"
.br
.ti -1c
.RI "uchar \fBinternal_file_attributes\fP [2]"
.br
.ti -1c
.RI "uchar \fBexternal_file_attributes\fP [4]"
.br
.ti -1c
.RI "uchar \fBoffset_local_header\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 324 of file qzip\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
