.TH "MD4state_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD4state_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MD4_LONG \fBA\fP"
.br
.ti -1c
.RI "MD4_LONG \fBB\fP"
.br
.ti -1c
.RI "MD4_LONG \fBC\fP"
.br
.ti -1c
.RI "MD4_LONG \fBD\fP"
.br
.ti -1c
.RI "MD4_LONG \fBNl\fP"
.br
.ti -1c
.RI "MD4_LONG \fBNh\fP"
.br
.ti -1c
.RI "MD4_LONG \fBdata\fP [MD4_LBLOCK]"
.br
.ti -1c
.RI "unsigned int \fBnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file md4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
