.TH "md_fonts_bravura_bravura-text" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_fonts_bravura_bravura-textAn introduction to using Bravura Text 
 \- \fIVersion 1\&.1, 30 October 2015\fP
.PP
Bravura Text is a \fCSMuFL-compliant\fP font containing musical symbols intended for use in text-based applications such as word processors, text editors, desktop publishers, and it can also be used on the web\&.
.PP
Bravura Text is licensed under the \fCSIL Open Font License\fP, which means it is free to use, redistribute, and modify, but please do respect the conditions set out in the license\&.
.PP
.SS "\fBGlyph\fP repertoire"
.PP
Bravura Text is a reference implementation for SMuFL, the Standard Music Font Layout, and as such contains all of the symbols defined in the SMuFL specification\&. \fCDownload the SMuFL specification\fP for a complete list of the symbols in Bravura Text, including a description and code point\&.
.PP
SMuFL uses the Private Use Area of Unicode's Basic Multilingual Plane (U+E000 through U+FFFF) to encode all of the included symbols\&. This means that the symbols cannot be typed by using the alphanumeric keys on your computer's keyboard on their own\&.
.PP
.SS "Setting up for Unicode input"
.PP
Detailed instructions for how to enable Unicode input on all operating systems are beyond the scope of this document\&. SIL provides \fCan excellent page\fP with links to information and tools for Windows, OS X and Linux\&. In this document some basic instructions are included, but you may need to refer to other resources for help with your operating system and application of choice\&.
.PP
.SS "Windows"
.PP
There are multiple ways to type Unicode characters on Windows\&. Here are three methods you can try:
.PP
.SS "Method 1: hexadecimal input followed by \fCAlt\fP"
.PP
On Windows, some applications, such as Microsoft Word (part of the Microsoft Office suite) and WordPad (included with every Windows installation), have support for converting a typed alphanumeric sequence into a single Unicode character\&.
.PP
The Unicode code point for a G (treble) clef in Bravura Text is U+E050, which is a hexadecimal number (57424 in decimal)\&. To enter this character in Word or WordPad, type \fCE050\fP followed by \fCAlt+X\fP (hold the \fCAlt\fP key and then hit the \fCX\fP key)\&. The typed characters \fBE050\fP will be replaced by a single character, which may display as an empty rectangle or a rectangle containing \fB?\fP\&. Select this character and change the font to Bravura Text, and the G clef appears\&.
.PP
Although Unicode code points are normally written in the form U+E050, you can ignore the 'U+' part when entering the code point in this and the following method\&.
.PP
.SS "Method 2: \fCAlt\fP + hexadecimal input"
.PP
If the application you are using does not support the kind of conversion described above, you can enable Unicode input by holding \fCAlt\fP, then typing \fC+\fP \fBon the numeric keypad\fP, then typing the hexadecimal number on the numeric keypad, before finally releasing \fCAlt\fP\&. For example, to type the G clef (U+E050), hold \fCAlt\fP, type keypad \fC+\fP, then \fCE050\fP, then release \fCAlt\fP\&. Again, if Bravura Text is not the selected font, you may see an empty rectangle or a rectangle containing \fB?\fP\&. Select this character and change the font to Bravura Text, and the G clef appears\&.
.PP
.SS "Method 3: Character Map"
.PP
The built-in Character Map application can copy any Unicode character to the system clipboard so that it can be pasted into another application\&. To run Character Map, click the \fCStart\fP button or hit the \fCWindows\fP key on your keyboard, then type \fCcharmap\fP and hit \fCReturn\fP\&. Character Map will run\&.
.PP
In Character Map, choose \fBBravura Text\fP from the \fBFont\fP menu at the top of the window\&. Switch on the \fBAdvanced view\fP checkbox at the bottom of the window, which makes extra options appear\&. Choose \fBUnicode\fP from the \fBCharacter set\fP menu, then choose \fBUnicode Subrange\fP from the bottom of the \fB\fBGroup\fP by\fP menu\&. A further pop-up window appears, captioned \fB\fBGroup\fP By\fP, showing a list of Unicode subranges; choose \fBPrivate Use Characters\fP from the bottom of the list\&. (You can then close the \fB\fBGroup\fP By\fP window if you wish\&.)
.PP
The grid that occupies the main part of the Character Map window now displays all of the symbols in Bravura Text (unfortunately, it is not possible to enlarge the display, so they are rather small)\&. Once you have located the character you require, either select it with the mouse and click \fBSelect\fP or double-click it, and it is added to the \fBCharacters to copy\fP edit control\&. Click \fBCopy\fP to copy the contents of \fBCharacters to copy\fP to the clipboard, then switch to the application into which you want to paste the text, and choose \fCEdit\fP ▸ \fCPaste\fP, or type \fCCtrl+V\fP\&.
.PP
.SS "Other methods"
.PP
You may wish to experiment with third-party utilities that can assist with locating and inserting Unicode characters\&. No recommendation or warranty is implied by listing these free utilities, which you may try at your own risk:
.PP
.IP "\(bu" 2
\fCCatchChar\fP allows you to add commonly-used Unicode characters to a menu that can be triggered from within any application via a keyboard shortcut\&.
.IP "\(bu" 2
\fCBabelMap\fP is an advanced alternative to Windows's built-in Character Map application\&.
.PP
.PP
Other commercial (non-free) utilities are also available, including \fCPopChar\fP\&.
.PP
.SS "OS X"
.PP
For Mac computers running OS X, the simplest method to insert arbitrary Unicode characters is using the provided Unicode Hex Input input method\&. To enable it:
.PP
.IP "\(bu" 2
In System Preferences, choose \fBKeyboard\fP\&.
.IP "\(bu" 2
On the \fBKeyboard\fP tab, switch on \fBShow Keyboard & Character Viewers in menu bar\fP\&. When switched on, you will see a national flag corresponding to your computer keyboard's normal language and/or layout appear in the menu bar to the left of the Spotlight icon\&.
.IP "\(bu" 2
On the \fBInput Sources\fP tab, click \fB+**, and in the sheet that appears, select **Others\fP in the left-hand list, then select \fBUnicode Hex Input\fP in the right-hand list, then click \fBAdd\fP to close the sheet\&.
.IP "\(bu" 2
Ensure \fBShow Input menu in menu bar\fP is switched on, then close System Preferences\&.
.PP
.PP
The Unicode Hex Input input method works in the majority of OS X applications\&. To try it out, for example, open a new text document in TextEdit\&. Bravura Text does not appear by default in the font menu in TextEdit's toolbar, because it is not an English-language font, so to choose Bravura Text you must show the Fonts panel by choosing \fCFormat\fP ▸ \fCFont\fP ▸ \fCShow Fonts\fP or typing \fC⌘T\fP\&. In the Fonts panel, choose \fBAll fonts\fP under \fBCollection\fP, then choose \fBBravura Text\fP under \fBFamily\fP, then close the Fonts panel (type \fC⌘T\fP again)\&.
.PP
Bravura Text is now the chosen font (and will now appear in the font menu in TextEdit's toolbar for this document)\&. To type a G (treble) clef, which has the code point U+E050, first choose the \fBUnicode Hex Input\fP input method from the input menu in the menu bar\&. Now hold down \fCAlt\fP and type \fCE050\fP (do not type the 'U+' prefix), then release \fCAlt\fP\&.
.PP
If you want to switch between your normal language input method and the Unicode Hex Input method quickly, you can assign a system keyboard shortcut in the \fBKeyboard\fP pane of System Preferences\&. Choose the \fBShortcuts\fP tab, then in the left-hand list choose \fBInput Sources\fP\&. Switch on the checkbox for either or both of \fBSelect the previous input source\fP and \fBSelect the next input source\fP, and assign a keyboard shortcut\&. The default shortcut suggested by OS X is used for Spotlight by default, so you may wish to assign another shortcut, e\&.g\&. \fC^Space\fP (\fC^\fP is the symbol that corresponds to the \fCCtrl\fP key)\&.
.PP
.SS "Usage notes for Bravura Text"
.PP
.SS "Scale factor"
.PP
Bravura Text is scaled such that the height of a five-line staff (e\&.g\&. U+E014) is approximately the same as the height of an upper case letter in a regular text font at the same point size\&. It is designed to be used both in-line, i\&.e\&. in the middle of a run of text at the same point size, and on its own, typically at a larger point size\&. As such, all symbols in Bravura Text are scaled appropriately to be drawn at the correct size on a five-line staff\&.
.PP
One exception to this is for the bold italic letters used for dynamics, which are scaled such that they are approximately the same size as a lower case letter in a regular text font at the same point size\&.
.PP
.SS "Zero-width characters"
.PP
Symbols depicting staves and staff lines in Bravura Text have zero width\&. This is to allow other musical symbols to be printed on top of them\&.
.PP
Staff line symbols are provided in three widths: narrow (one space wide); normal (two spaces wide); and wide (three spaces wide)\&.
.PP
The space is the normal unit of measurement when working with printed music notation\&. One space is the vertical distance between the middle of one staff line and the middle of the staff line above; as such a five-line staff is four spaces tall\&.
.PP
Time signature digits also have zero width, to allow them to be positioned above one another\&. Leger line glyphs similarly have zero width\&.
.PP
All other glyphs have zero side-bearings, i\&.e\&. the advance width of each glyph is exactly equal to the bounding box of its symbol\&.
.PP
.SS "Space characters"
.PP
In order to insert space between symbols, use the following keys:
.PP
.IP "\(bu" 2
Typing \fCSpace\fP advances the input position by half a space\&.
.IP "\(bu" 2
Typing \fC-\fP (hyphen) advances the input position by one space\&.
.IP "\(bu" 2
Typing \fC=\fP (equals) advances the input position by two spaces\&.
.PP
.PP
.SS "Default vertical positioning"
.PP
Many glyphs in Bravura Text are provided at multiple vertical positions, so that they can appear at different staff positions\&. With the exception of common clefs, all glyphs that can be drawn at different vertical positions are positioned by default such that they will appear on the middle line of a five-line staff glyph (e\&.g\&. U+E014)\&. The common clefs are positioned by default as follows:
.PP
.IP "\(bu" 2
G clef (e\&.g\&. U+E050): as for a treble clef, i\&.e\&. the bottom of the lower loop aligned with the bottom staff line
.IP "\(bu" 2
F clef (e\&.g\&. U+E061): as for a bass clef, i\&.e\&. the two dots positioned either side of the second-highest staff line
.IP "\(bu" 2
C clef (e\&.g\&. U+E058): as for an alto clef, i\&.e\&. the center of the clef positioned on the middle staff line
.PP
.PP
The following ranges of glyphs (as defined in the SMuFL specification) can be moved to different vertical positions on the staff:
.PP
.IP "\(bu" 2
Leger lines (within the \fBStaves\fP range)
.IP "\(bu" 2
All noteheads (within the \fBNoteheads\fP, \fBSlash noteheads\fP, \fBRound and square noteheads\fP, \fBNote clusters\fP, \fBNote name noteheads ranges\fP)
.IP "\(bu" 2
Precomposed notes with stems and flags (within the \fBIndividual notes\fP and \fBBeamed groups of notes\fP ranges)
.IP "\(bu" 2
Precomposed stems (within the \fBStems\fP range)
.IP "\(bu" 2
Flags for notes (within the \fBFlags\fP range)
.IP "\(bu" 2
All accidentals (within the \fBStandard accidentals\fP, \fBGould arrow quarter-tone accidentals\fP, \fBStein-Zimmermann accidentals\fP, \fBExtended Stein-Zimmermann accidentals\fP, \fBSims accidentals\fP, \fBJohnston accidentals for Just Intonation\fP, \fBExtended Helmholtz-Ellis JI accidentals\fP, all Sagittal ranges, \fBWyschnegradsky accidentals\fP, \fBArel-Ezgi-Uzdilek (AEU) accidentals\fP, \fBTurkish folk music accidentals\fP, \fBPersian accidentals\fP, \fBOther accidentals\fP ranges)
.IP "\(bu" 2
Articulations (within the \fBArticulations\fP range)
.IP "\(bu" 2
Fermatas, caesuras, breathmarks (within the \fBHolds and pauses\fP range)
.IP "\(bu" 2
Rests (within the \fBRests\fP range)
.IP "\(bu" 2
1-, 2- and 4-bar repeat indicators (within the \fBBar repeats\fP range)
.IP "\(bu" 2
Medieval and Renaissance clefs, prolation and mensuration signs, noteheads and stems, individual notes, plainchant single- and multi-note forms, plainchant articulations, and accidentals (within the \fBMedieval and Renaissance\&.\&.\&.\fP ranges)
.IP "\(bu" 2
\fBKievan square notation\fP
.PP
.PP
.SS "Altering vertical position"
.PP
Bravura Text uses OpenType ligatures to modify the default vertical position of symbols\&. In OpenType fonts, ligatures are a kind of glyph substitution, where two or more glyphs are replaced with another single glyph\&. This is commonly used in text fonts to produce an elegant appearance for particular combinations of letters, such as 'fi' or 'fl'\&.
.PP
In Bravura Text, ligatures are used to adjust the vertical position of individual symbols\&. First, you enter the code point corresponding to the amount by which you want to change the vertical position, and then you enter the code point for the symbol itself\&. Provided the application you are using supports OpenType ligatures, you should see the symbol appear at the desired vertical position\&.
.PP
The code points to use to raise or lower the position of symbols are as follows (the pitch names shown in parentheses correspond to a five-line staff with a treble clef; the default vertical position for movable symbols is therefore B4):
.PP
.IP "\(bu" 2
Raise by one staff position (C5): U+EB90
.IP "\(bu" 2
Raise by two staff positions (D5): U+EB91
.IP "\(bu" 2
Raise by three staff positions (E5): U+EB92
.IP "\(bu" 2
Raise by four staff positions (F5): U+EB93
.IP "\(bu" 2
Raise by five staff positions (G5): U+EB94
.IP "\(bu" 2
Raise by six staff positions (A5): U+EB95
.IP "\(bu" 2
Raise by seven staff positions (B5): U+EB96
.IP "\(bu" 2
Raise by eight staff positions (C6): U+EB97
.IP "\(bu" 2
Lower by one staff position (A4): U+EB98
.IP "\(bu" 2
Lower by two staff positions (G4): U+EB99
.IP "\(bu" 2
Lower by three staff positions (F4): U+EB9A
.IP "\(bu" 2
Lower by four staff positions (E4): U+EB9B
.IP "\(bu" 2
Lower by five staff positions (D4): U+EB9C
.IP "\(bu" 2
Lower by six staff positions (C4): U+EB9D
.IP "\(bu" 2
Lower by seven staff positions (B3): U+EB9E
.IP "\(bu" 2
Lower by eight staff positions (A3): U+EB9F
.PP
.PP
So to position, say, a black notehead at the G4 staff position, you would first enter U+EB99 (lower by two staff positions) followed immediately by U+E0A4 (the black notehead)\&.
.PP
Noteheads positioned outside the staff (i\&.e\&. raised or lowered by six or more staff positions) will not automatically show leger lines, so those must be added separately \fIbefore\fP the notehead (since they have zero width), and raised or lowered by the same number of staff positions\&.
.PP
Special code points are provided to shift time signature digits to the correct vertical position:
.PP
.IP "\(bu" 2
Position as numerator (top number): U+E09E
.IP "\(bu" 2
Position as denominator (bottom number): U+E09F
.PP
.PP
To enter the time signature 4/4, you would first enter U+E09E (position as numerator), followed immediately by U+E084 (time signature 4), then U+E09F (position as denominator), followed by U+E084 again\&. Finally, advance the input position by inputting one or more spaces\&.
.PP
.SS "Further information"
.PP
Detailed technical support is not available for the use of Bravura Text, but if you encounter any problems using this font, please use the \fC\fBsmufl-discuss\fP mailing list\fP to contact the SMuFL community about your problem\&. 
