.TH "md_mtest_libmscore_parts__r_e_a_d_m_e" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_mtest_libmscore_parts__r_e_a_d_m_eFilename convention 
 \- \fBpart-_{1}_-_{2}_\&.mscx\fP
.PP
_{1}_ which element is tested
.PP
.IP "\(bu" 2
\fCempty\fP -> just notes
.IP "\(bu" 2
\fCall\fP -> all or as much as possible elements
.IP "\(bu" 2
\fIelement name\fP -> tests for a specific element (fingering, symbol etc\&.\&.\&.)
.PP
.PP
{2} action - which action is tested for the given element
.PP
.IP "\(bu" 2
\fIempty string\fP = no parts created
.IP "\(bu" 2
\fCparts\fP == parts created
.IP "\(bu" 2
\fIactions for elements\fP == (add, uadd, uradd, del, udel, urdel) for elements
.IP "\(bu" 2
\fIactions for all\fP == ()
.PP
.PP
.SH "Linked Parts "
.PP
.PP
.IP "1." 4
create
.IP "2." 4
add
.IP "3." 4
add undo
.IP "4." 4
add redo
.IP "5." 4
remove
.IP "6." 4
remove undo
.IP "7." 4
remove redo
.PP
.PP
.PP
.nf
1 234 567 ELEMENT
x xxx xxx SYMBOL
- --- --- TEXT
- --- --- INSTRUMENT_NAME
- --- --- BAR_LINE
- --- --- STEM_SLASH
- --- --- LINE
- --- --- BRACKET
- --- --- ARPEGGIO
- --- --- ACCIDENTAL
x --- --- NOTE
x --- --- STEM
x --- --- CLEF
x --- --- KEYSIG
x --- --- TIMESIG
x --- --- REST
x xxx xxx BREATH
- --- --- GLISSANDO
- --- --- REPEAT_MEASURE
- --- --- IMAGE
- --- --- TIE
- --- --- ARTICULATION
- --- --- CHORDLINE
- --- --- DYNAMIC
- --- --- BEAM
- --- --- HOOK
- --- --- LYRICS
- --- --- FIGURED_BASS
- --- --- MARKER
- --- --- JUMP
x xxx xxx FINGERING
- --- --- TUPLET
- --- --- TEMPO_TEXT
- --- --- STAFF_TEXT
- --- --- REHEARSAL_MARK
- --- --- INSTRUMENT_CHANGE
- --- --- HARMONY
- --- --- FRET_DIAGRAM
- --- --- BEND
- --- --- TREMOLOBAR
- --- --- VOLTA
- --- --- SLUR_SEGMENT
- --- --- HAIRPIN_SEGMENT
- --- --- OTTAVA_SEGMENT
- --- --- TRILL_SEGMENT
- --- --- TEXTLINE_SEGMENT
- --- --- VOLTA_SEGMENT
- --- --- LAYOUT_BREAK
- --- --- SPACER
- --- --- STAFF_STATE
- --- --- LEDGER_LINE
- --- --- NOTEHEAD
- --- --- NOTEDOT
- --- --- TREMOLO
- --- --- MEASURE
- --- --- STAFF_LINES
- --- --- RUBBERBAND
- --- --- TAB_DURATION_SYMBOL
- --- --- FSYMBOL

- --- --- HAIRPIN
- --- --- OTTAVA
- --- --- PEDAL
- --- --- TRILL
- --- --- TEXTLINE
- --- --- SLUR

- --- --- HBOX
x --- --- VBOX
- --- --- TBOX
- --- --- FBOX
- --- --- ACCIDENTAL_BRACKET
.fi
.PP
 
