.TH "md_share_instruments__r_e_a_d_m_e" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_share_instruments__r_e_a_d_m_eTranslation of the instrument list 
 \- 
.IP "\(bu" 2
\fC\fBgenerateTs\&.py\fP\fP parses \fCinstruments\&.xml\fP and create a fake \fC\fBinstrumentsxml\&.h\fP\fP file
.IP "\(bu" 2
gen-instruments-projectfile creates a pro file for the translations, so we can run lupdate and lrelease on it
.IP "\(bu" 2
the TS file is loaded by MuseScore and the instruments are translated when the instruments\&.xml file is loaded
.PP
.PP
.SS "If instruments\&.xml is modified "
.PP
.IP "\(bu" 2
run \fC\fBgenerateTs\&.py\fP\fP and lupdate\&.sh
.IP "\(bu" 2
push the new file updated ts en_US file to transifex 
.PP

