.TH "MdiWindowData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MdiWindowData \- handles mdiwindow arrows hover  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mdiwindowdata\&.h>\fP
.PP
Inherits \fBAnimationData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMdiWindowData\fP (QObject *, QWidget *, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~MdiWindowData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBupdateState\fP (int primitive, bool value)"
.br
.RI "animation state "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (int primitive) const"
.br
.RI "animation state "
.ti -1c
.RI "virtual qreal \fBopacity\fP (int primitive) const"
.br
.RI "opacity "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int duration)"
.br
.RI "duration "
.in -1c
.PP
.RI "\fBcurrent animation\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "qreal \fBcurrentOpacity\fP (void) const"
.br
.RI "opacity "
.ti -1c
.RI "void \fBsetCurrentOpacity\fP (qreal value)"
.br
.RI "opacity "
.ti -1c
.RI "\fBAnimation::Pointer\fP \fBcurrentAnimation\fP (void) const"
.br
.RI "animation "
.in -1c
.in -1c
.PP
.RI "\fBprevious animation\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "qreal \fBpreviousOpacity\fP (void) const"
.br
.RI "opacity "
.ti -1c
.RI "void \fBsetPreviousOpacity\fP (qreal value)"
.br
.RI "opacity "
.ti -1c
.RI "\fBAnimation::Pointer\fP \fBpreviousAnimation\fP (void) const"
.br
.RI "animation "
.in -1c
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBcurrentOpacity\fP"
.br
.RI "declare opacity property "
.ti -1c
.RI "qreal \fBpreviousOpacity\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
handles mdiwindow arrows hover 
.PP
Definition at line 33 of file mdiwindowdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
