.TH "MeasureToTick::TimeTick" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeasureToTick::TimeTick
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumerator_\fP"
.br
.ti -1c
.RI "int \fBdenominator_\fP"
.br
.ti -1c
.RI "int \fBmeasure_\fP"
.br
.ti -1c
.RI "int \fBtick_\fP"
.br
.ti -1c
.RI "bool \fBisSymbol_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file importove\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
