.TH "libmscore/measure.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/measure.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'measure\&.h'\fP
.br
\fC#include 'accidental\&.h'\fP
.br
\fC#include 'ambitus\&.h'\fP
.br
\fC#include 'articulation\&.h'\fP
.br
\fC#include 'barline\&.h'\fP
.br
\fC#include 'beam\&.h'\fP
.br
\fC#include 'box\&.h'\fP
.br
\fC#include 'bracket\&.h'\fP
.br
\fC#include 'breath\&.h'\fP
.br
\fC#include 'chord\&.h'\fP
.br
\fC#include 'clef\&.h'\fP
.br
\fC#include 'drumset\&.h'\fP
.br
\fC#include 'duration\&.h'\fP
.br
\fC#include 'dynamic\&.h'\fP
.br
\fC#include 'fret\&.h'\fP
.br
\fC#include 'glissando\&.h'\fP
.br
\fC#include 'hairpin\&.h'\fP
.br
\fC#include 'harmony\&.h'\fP
.br
\fC#include 'hook\&.h'\fP
.br
\fC#include 'icon\&.h'\fP
.br
\fC#include 'image\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'keysig\&.h'\fP
.br
\fC#include 'layoutbreak\&.h'\fP
.br
\fC#include 'layout\&.h'\fP
.br
\fC#include 'note\&.h'\fP
.br
\fC#include 'ottava\&.h'\fP
.br
\fC#include 'page\&.h'\fP
.br
\fC#include 'part\&.h'\fP
.br
\fC#include 'pedal\&.h'\fP
.br
\fC#include 'pitchspelling\&.h'\fP
.br
\fC#include 'repeat\&.h'\fP
.br
\fC#include 'rest\&.h'\fP
.br
\fC#include 'score\&.h'\fP
.br
\fC#include 'segment\&.h'\fP
.br
\fC#include 'select\&.h'\fP
.br
\fC#include 'sig\&.h'\fP
.br
\fC#include 'slur\&.h'\fP
.br
\fC#include 'spacer\&.h'\fP
.br
\fC#include 'staff\&.h'\fP
.br
\fC#include 'stafftext\&.h'\fP
.br
\fC#include 'stafftype\&.h'\fP
.br
\fC#include 'stringdata\&.h'\fP
.br
\fC#include 'style\&.h'\fP
.br
\fC#include 'sym\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'tempotext\&.h'\fP
.br
\fC#include 'text\&.h'\fP
.br
\fC#include 'tie\&.h'\fP
.br
\fC#include 'tiemap\&.h'\fP
.br
\fC#include 'timesig\&.h'\fP
.br
\fC#include 'tremolo\&.h'\fP
.br
\fC#include 'trill\&.h'\fP
.br
\fC#include 'tuplet\&.h'\fP
.br
\fC#include 'tupletmap\&.h'\fP
.br
\fC#include 'undo\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'volta\&.h'\fP
.br
\fC#include 'xml\&.h'\fP
.br
\fC#include 'systemdivider\&.h'\fP
.br
\fC#include 'stafftypechange\&.h'\fP
.br
\fC#include 'stafflines\&.h'\fP
.br
\fC#include 'bracketItem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::MStaff\fP"
.br
.RI "Per staff values of measure\&. "
.ti -1c
.RI "struct \fBMs::AcEl\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of most part of class Measure\&. 
.PP
Definition in file \fBmeasure\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
