.TH "MeasureToTick" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeasureToTick
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTimeTick\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbuild\fP (\fBOVE::OveSong\fP *ove, int quarter)"
.br
.ti -1c
.RI "int \fBgetTick\fP (int measure, int tick_pos)"
.br
.ti -1c
.RI "QList< \fBTimeTick\fP > \fBgetTimeTicks\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBunitToTick\fP (int unit, int quarter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file importove\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
