.TH "libmscore/measurebase.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/measurebase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br
\fC#include 'layoutbreak\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::MeasureBase\fP"
.br
.RI "Virtual base class for \fBMeasure\fP, \fBHBox\fP and \fBVBox\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRepeat\fP : char { \fBNONE\fP = 0, \fBEND\fP = 1, \fBSTART\fP = 2, \fBMEASURE\fP = 4, \fBJUMP\fP = 8 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr Repeat \fBMs::operator|\fP (Repeat t1, Repeat t2)"
.br
.ti -1c
.RI "constexpr bool \fBMs::operator &\fP (Repeat t1, Repeat t2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of MeasureBase class\&. 
.PP
Definition in file \fBmeasurebase\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
