.TH "libmscore/measure.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/measure.h
.SH SYNOPSIS
.br
.PP
\fC#include 'measurebase\&.h'\fP
.br
\fC#include 'fraction\&.h'\fP
.br
\fC#include 'segmentlist\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::Measure\fP"
.br
.RI "one measure in a system "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMeasureNumberMode\fP : char { \fBAUTO\fP, \fBSHOW\fP, \fBHIDE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of class Measure\&. 
.PP
Definition in file \fBmeasure\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
