.TH "MediaRendition" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaRendition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMediaRendition\fP (\fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "\fBMediaParameters\fP * \fBgetMHParameters\fP ()"
.br
.ti -1c
.RI "\fBMediaParameters\fP * \fBgetBEParameters\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetContentType\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFileName\fP ()"
.br
.ti -1c
.RI "GBool \fBgetIsEmbedded\fP ()"
.br
.ti -1c
.RI "\fBStream\fP * \fBgetEmbbededStream\fP ()"
.br
.ti -1c
.RI "void \fBoutputToFile\fP (FILE *)"
.br
.ti -1c
.RI "\fBMediaRendition\fP * \fBcopy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file Rendition\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
