.TH "MediaWindowParameters" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaWindowParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMediaWindowType\fP { \fBwindowFloating\fP = 0, \fBwindowFullscreen\fP, \fBwindowHidden\fP, \fBwindowEmbedded\fP }"
.br
.ti -1c
.RI "enum \fBMediaWindowRelativeTo\fP { \fBwindowRelativeToDocument\fP = 0, \fBwindowRelativeToApplication\fP, \fBwindowRelativeToDesktop\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparseFWParams\fP (\fBObject\fP *obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MediaWindowType \fBtype\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "MediaWindowRelativeTo \fBrelativeTo\fP"
.br
.ti -1c
.RI "double \fBXPosition\fP"
.br
.ti -1c
.RI "double \fBYPosition\fP"
.br
.ti -1c
.RI "GBool \fBhasTitleBar\fP"
.br
.ti -1c
.RI "GBool \fBhasCloseButton\fP"
.br
.ti -1c
.RI "GBool \fBisResizeable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file Rendition\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
