.TH "MediaParameters" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaParameters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBColor\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMediaFittingPolicy\fP { \fBfittingMeet\fP = 0, \fBfittingSlice\fP, \fBfittingFill\fP, \fBfittingScroll\fP, \fBfittingHidden\fP, \fBfittingUndefined\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparseMediaPlayParameters\fP (\fBObject\fP *playObj)"
.br
.ti -1c
.RI "void \fBparseMediaScreenParameters\fP (\fBObject\fP *screenObj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBduration\fP"
.br
.ti -1c
.RI "int \fBvolume\fP"
.br
.ti -1c
.RI "MediaFittingPolicy \fBfittingPolicy\fP"
.br
.ti -1c
.RI "GBool \fBautoPlay\fP"
.br
.ti -1c
.RI "double \fBrepeatCount\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBbgColor\fP"
.br
.ti -1c
.RI "double \fBopacity\fP"
.br
.ti -1c
.RI "GBool \fBshowControls\fP"
.br
.ti -1c
.RI "\fBMediaWindowParameters\fP \fBwindowParams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file Rendition\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
