.TH "MemStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemStream\fP (char *bufA, Goffset startA, Goffset lengthA, \fBObject\fP *dictA)"
.br
.ti -1c
.RI "virtual \fBBaseStream\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual \fBStream\fP * \fBmakeSubStream\fP (Goffset start, GBool limited, Goffset lengthA, \fBObject\fP *dictA)"
.br
.ti -1c
.RI "virtual StreamKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetChar\fP ()"
.br
.ti -1c
.RI "virtual int \fBlookChar\fP ()"
.br
.ti -1c
.RI "virtual Goffset \fBgetPos\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetPos\fP (Goffset pos, int dir=0)"
.br
.ti -1c
.RI "virtual Goffset \fBgetStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBmoveStart\fP (Goffset delta)"
.br
.ti -1c
.RI "virtual void \fBsetNeedFree\fP (GBool val)"
.br
.ti -1c
.RI "virtual int \fBgetUnfilteredChar\fP ()"
.br
.ti -1c
.RI "virtual void \fBunfilteredReset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 559 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
