.TH "MenuDataV1" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuDataV1 \- menubar data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menudata\&.h>\fP
.PP
Inherits \fBMenuBarDataV1\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuDataV1\fP (QObject *parent, QWidget *target, int duration)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~MenuDataV1\fP (void)"
.br
.RI "destructor "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBenterEvent\fP (const QObject *object)"
.br
.RI "menubar enterEvent "
.ti -1c
.RI "virtual void \fBleaveEvent\fP (const QObject *object)"
.br
.RI "menubar enterEvent "
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (const QObject *object)"
.br
.RI "menubar mouseMoveEvent "
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (const QObject *object)"
.br
.RI "menubar mousePressEvent "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
menubar data 

most members are identical to menubar data\&. The one that are not are using templatized versions, because QMenuBar and QMenu API are very similar 
.PP
Definition at line 37 of file menudata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
