.TH "MenuBarEngineV1" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuBarEngineV1 \- fading menubar animation  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menubarengine\&.h>\fP
.PP
Inherits \fBMenuBarBaseEngine\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBunregisterWidget\fP (QObject *object)"
.br
.RI "remove widget from map "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuBarEngineV1\fP (QObject *parent)"
.br
.RI "constructor "
.ti -1c
.RI "\fBMenuBarEngineV1\fP (QObject *parent, \fBMenuBarBaseEngine\fP *other)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~MenuBarEngineV1\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBregisterWidget\fP (QWidget *)"
.br
.RI "register menubar "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (const QObject *object, const QPoint &point)"
.br
.RI "true if widget is animated "
.ti -1c
.RI "virtual qreal \fBopacity\fP (const QObject *object, const QPoint &point)"
.br
.RI "animation opacity "
.ti -1c
.RI "virtual QRect \fBcurrentRect\fP (const QObject *object, const QPoint &point)"
.br
.RI "return 'hover' rect position when widget is animated "
.ti -1c
.RI "virtual void \fBsetEnabled\fP (bool value)"
.br
.RI "enability "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int \fBduration\fP)"
.br
.RI "duration "
.ti -1c
.RI "virtual \fBWidgetList\fP \fBregisteredWidgets\fP (void) const"
.br
.RI "return list of registered widgets "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
fading menubar animation 
.PP
Definition at line 91 of file menubarengine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
