.TH "MgStyle" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MgStyle
.SH SYNOPSIS
.br
.PP
.PP
Inherits QCommonStyle\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBconfigurationChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBpixelMetric\fP (PixelMetric, const QStyleOption *=0, const QWidget *=0) const"
.br
.ti -1c
.RI "virtual int \fBstyleHint\fP (StyleHint, const QStyleOption *=0, const QWidget *=0, QStyleHintReturn *=0) const"
.br
.ti -1c
.RI "virtual QRect \fBsubElementRect\fP (SubElement, const QStyleOption *, const QWidget *) const"
.br
.ti -1c
.RI "virtual QRect \fBsubControlRect\fP (ComplexControl, const QStyleOptionComplex *, SubControl, const QWidget *) const"
.br
.ti -1c
.RI "QSize \fBsizeFromContents\fP (ContentsType, const QStyleOption *, const QSize &, const QWidget *) const"
.br
.ti -1c
.RI "SubControl \fBhitTestComplexControl\fP (ComplexControl, const QStyleOptionComplex *, const QPoint &, const QWidget *) const"
.br
.ti -1c
.RI "virtual void \fBpolish\fP (QWidget *widget)"
.br
.ti -1c
.RI "void \fBunpolish\fP (QWidget *widget)"
.br
.ti -1c
.RI "void \fBdrawPrimitive\fP (PrimitiveElement, const QStyleOption *, QPainter *, const QWidget *) const"
.br
.ti -1c
.RI "void \fBdrawControl\fP (ControlElement, const QStyleOption *, QPainter *, const QWidget *) const"
.br
.ti -1c
.RI "void \fBdrawComplexControl\fP (ComplexControl, const QStyleOptionComplex *, QPainter *, const QWidget *) const"
.br
.ti -1c
.RI "virtual void \fBdrawItemText\fP (QPainter *, const QRect &, int alignment, const QPalette &, bool enabled, const QString &, QPalette::ColorRole=QPalette::NoRole) const"
.br
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.ti -1c
.RI "\fBAnimations\fP & \fBanimations\fP () const"
.br
.ti -1c
.RI "\fBTransitions\fP & \fBtransitions\fP () const"
.br
.ti -1c
.RI "\fBFrameShadowFactory\fP & \fBframeShadowFactory\fP () const"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual QIcon \fBstandardIcon\fP (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file mstyle\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int MgStyle::pixelMetric (PixelMetric metric, const QStyleOption * option = \fC0\fP, const QWidget * widget = \fC0\fP) const\fC [virtual]\fP"
tabbar 
.PP
Definition at line 143 of file mstyle\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
