.TH "MgStyleConfigData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MgStyleConfigData
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBMB_NONE\fP, \fBMB_FOLLOW_MOUSE\fP, \fBMB_FADE\fP, \fBME_NONE\fP, \fBME_FADE\fP, \fBME_FOLLOW_MOUSE\fP, \fBTB_NONE\fP, \fBTB_FADE\fP, \fBTB_FOLLOW_MOUSE\fP }"
.br
.ti -1c
.RI "enum { \fBMM_DARK\fP, \fBMM_STRONG\fP, \fBMM_SUBTLE\fP }"
.br
.ti -1c
.RI "enum { \fBTS_SINGLE\fP, \fBTS_PLAIN\fP }"
.br
.ti -1c
.RI "enum { \fBWD_FULL\fP, \fBWD_MINIMAL\fP }"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBgenericAnimationsEnabled\fP = true"
.br
.ti -1c
.RI "static int \fBgenericAnimationsDuration\fP = 150"
.br
.ti -1c
.RI "static int \fBtoolBarAnimationsDuration\fP = 50"
.br
.ti -1c
.RI "static int \fBmenuAnimationsDuration\fP = 150"
.br
.ti -1c
.RI "static int \fBprogressBarAnimationsDuration\fP"
.br
.ti -1c
.RI "static int \fBprogressBarBusyStepDuration\fP = 50"
.br
.ti -1c
.RI "static int \fBmenuBarAnimationsDuration\fP = 150"
.br
.ti -1c
.RI "static int \fBmenuFollowMouseAnimationsDuration\fP = 40"
.br
.ti -1c
.RI "static int \fBmenuBarFollowMouseAnimationsDuration\fP = 80"
.br
.ti -1c
.RI "static bool \fBanimationsEnabled\fP = true"
.br
.ti -1c
.RI "static bool \fBprogressBarAnimationsEnabled\fP = true"
.br
.ti -1c
.RI "static bool \fBprogressBarAnimated\fP = true"
.br
.ti -1c
.RI "static int \fBmenuBarAnimationType\fP = MgStyleConfigData::MB_FADE"
.br
.ti -1c
.RI "static int \fBmenuAnimationType\fP = MgStyleConfigData::ME_FADE"
.br
.ti -1c
.RI "static bool \fBmenuBarAnimationsEnabled\fP = true"
.br
.ti -1c
.RI "static bool \fBmenuAnimationsEnabled\fP = true"
.br
.ti -1c
.RI "static int \fBtoolBarAnimationType\fP = MgStyleConfigData::TB_FADE"
.br
.ti -1c
.RI "static int \fBmenuHighlightMode\fP = MgStyleConfigData::MM_SUBTLE"
.br
.ti -1c
.RI "static bool \fBtabSubtleShadow\fP = true"
.br
.ti -1c
.RI "static bool \fBshowMnemonics\fP = true"
.br
.ti -1c
.RI "static int \fBscrollBarAddLineButtons\fP = 1"
.br
.ti -1c
.RI "static int \fBscrollBarSubLineButtons\fP = 1"
.br
.ti -1c
.RI "static int \fBscrollBarWidth\fP = 15"
.br
.ti -1c
.RI "static int \fBtabStyle\fP = MgStyleConfigData::TS_SINGLE"
.br
.ti -1c
.RI "static bool \fBviewDrawFocusIndicator\fP = true"
.br
.ti -1c
.RI "static bool \fBcacheEnabled\fP = true"
.br
.ti -1c
.RI "static int \fBmaxCacheSize\fP = 512"
.br
.ti -1c
.RI "static bool \fBwidgetExplorerEnabled\fP = false"
.br
.ti -1c
.RI "static bool \fBdrawWidgetRects\fP = true"
.br
.ti -1c
.RI "static bool \fBcomboBoxTransitionsEnabled\fP = false"
.br
.ti -1c
.RI "static bool \fBlabelTransitionsEnabled\fP = true"
.br
.ti -1c
.RI "static bool \fBlineEditTransitionsEnabled\fP = true"
.br
.ti -1c
.RI "static bool \fBstackedWidgetTransitionsEnabled\fP = false"
.br
.ti -1c
.RI "static int \fBcomboBoxTransitionsDuration\fP = 75"
.br
.ti -1c
.RI "static int \fBlabelTransitionsDuration\fP = 75"
.br
.ti -1c
.RI "static int \fBlineEditTransitionsDuration\fP = 150"
.br
.ti -1c
.RI "static int \fBstackedWidgetTransitionsDuration\fP = 150"
.br
.ti -1c
.RI "static bool \fBtoolTipDrawStyledFrames\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file mconfig\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
