.TH "MIconEnginePrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MIconEnginePrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBpmcKey\fP (const QSize &size, QIcon::Mode mode, QIcon::State state)"
.br
.ti -1c
.RI "void \fBstepSerialNum\fP ()"
.br
.ti -1c
.RI "void \fBloadDataForModeAndState\fP (QSvgRenderer *renderer, QIcon::Mode mode, QIcon::State state)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBhashKey\fP (QIcon::Mode mode, QIcon::State state)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QHash< int, QString > \fBsvgFiles\fP"
.br
.ti -1c
.RI "QHash< int, QByteArray > * \fBsvgBuffers\fP"
.br
.ti -1c
.RI "QHash< int, QPixmap > * \fBaddedPixmaps\fP"
.br
.ti -1c
.RI "int \fBserialNum\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static QAtomicInt \fBlastSerialNum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file miconengine\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
