.TH "midi_macosxcm_struct" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
midi_macosxcm_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBsync_time\fP"
.br
.ti -1c
.RI "UInt64 \fBdelta\fP"
.br
.ti -1c
.RI "UInt64 \fBlast_time\fP"
.br
.ti -1c
.RI "int \fBfirst_message\fP"
.br
.ti -1c
.RI "int \fBsysex_mode\fP"
.br
.ti -1c
.RI "unsigned long \fBsysex_word\fP"
.br
.ti -1c
.RI "unsigned int \fBsysex_byte_count\fP"
.br
.ti -1c
.RI "char \fBerror\fP [PM_HOST_ERROR_MSG_LEN]"
.br
.ti -1c
.RI "char \fBcallback_error\fP [PM_HOST_ERROR_MSG_LEN]"
.br
.ti -1c
.RI "Byte \fBpacketBuffer\fP [PACKET_BUFFER_SIZE]"
.br
.ti -1c
.RI "MIDIPacketList * \fBpacketList\fP"
.br
.ti -1c
.RI "MIDIPacket * \fBpacket\fP"
.br
.ti -1c
.RI "Byte \fBsysex_buffer\fP [SYSEX_BUFFER_SIZE]"
.br
.ti -1c
.RI "MIDITimeStamp \fBsysex_timestamp\fP"
.br
.ti -1c
.RI "unsigned char \fBlast_command\fP"
.br
.ti -1c
.RI "long \fBlast_msg_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file pmmacosxcm\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
