.TH "MidiInstrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiInstrument
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBinstrName\fP (int type, int hbank, int lbank, int program)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBhbank\fP"
.br
.ti -1c
.RI "int \fBlbank\fP"
.br
.ti -1c
.RI "int \fBpatch\fP"
.br
.ti -1c
.RI "int \fBsplit\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file midiinstrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
