.TH "midiwinmm_struct" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
midiwinmm_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   HMIDISTRM \fBstream\fP"
.br
.ti -1c
.RI "   HMIDIOUT \fBout\fP"
.br
.ti -1c
.RI "   HMIDIIN \fBin\fP"
.br
.ti -1c
.RI "} \fBhandle\fP"
.br
.ti -1c
.RI "LPMIDIHDR * \fBbuffers\fP"
.br
.ti -1c
.RI "int \fBmax_buffers\fP"
.br
.ti -1c
.RI "int \fBbuffers_expanded\fP"
.br
.ti -1c
.RI "int \fBnum_buffers\fP"
.br
.ti -1c
.RI "int \fBnext_buffer\fP"
.br
.ti -1c
.RI "HANDLE \fBbuffer_signal\fP"
.br
.ti -1c
.RI "unsigned long \fBlast_time\fP"
.br
.ti -1c
.RI "int \fBfirst_message\fP"
.br
.ti -1c
.RI "int \fBsysex_mode\fP"
.br
.ti -1c
.RI "unsigned long \fBsysex_word\fP"
.br
.ti -1c
.RI "unsigned int \fBsysex_byte_count\fP"
.br
.ti -1c
.RI "LPMIDIHDR \fBhdr\fP"
.br
.ti -1c
.RI "unsigned long \fBsync_time\fP"
.br
.ti -1c
.RI "long \fBdelta\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "CRITICAL_SECTION \fBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 115 of file pmwinmm\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
