.TH "MidiTrack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiTrack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiTrack\fP (\fBMidiFile\fP *)"
.br
.ti -1c
.RI "const std::multimap< int, \fBMidiEvent\fP > & \fBevents\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBMidiEvent\fP > & \fBevents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file midifile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
