.TH "MidiEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiEvent\fP (MidiEventType t, char c, char a, char b)"
.br
.ti -1c
.RI "void \fBset\fP (MidiEventType t, char c, char a, char b)"
.br
.ti -1c
.RI "MidiEventType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBsetType\fP (MidiEventType t)"
.br
.ti -1c
.RI "char \fBchannel\fP () const"
.br
.ti -1c
.RI "char \fBdataA\fP () const"
.br
.ti -1c
.RI "char \fBdataB\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file midievent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
