.TH "MovieActivationParameters" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieActivationParameters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMovieTime\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMovieRepeatMode\fP { \fBrepeatModeOnce\fP, \fBrepeatModeOpen\fP, \fBrepeatModeRepeat\fP, \fBrepeatModePalindrome\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparseMovieActivation\fP (\fBObject\fP *actObj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMovieTime\fP \fBstart\fP"
.br
.ti -1c
.RI "\fBMovieTime\fP \fBduration\fP"
.br
.ti -1c
.RI "double \fBrate\fP"
.br
.ti -1c
.RI "int \fBvolume\fP"
.br
.ti -1c
.RI "GBool \fBshowControls\fP"
.br
.ti -1c
.RI "GBool \fBsynchronousPlay\fP"
.br
.ti -1c
.RI "MovieRepeatMode \fBrepeatMode\fP"
.br
.ti -1c
.RI "GBool \fBfloatingWindow\fP"
.br
.ti -1c
.RI "double \fBxPosition\fP"
.br
.ti -1c
.RI "double \fByPosition\fP"
.br
.ti -1c
.RI "int \fBznum\fP"
.br
.ti -1c
.RI "int \fBzdenum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file Movie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
