.TH "Movie" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMovie\fP (\fBObject\fP *objMovie, \fBObject\fP *objAct)"
.br
.ti -1c
.RI "\fBMovie\fP (\fBObject\fP *objMovie)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "\fBMovieActivationParameters\fP * \fBgetActivationParameters\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFileName\fP ()"
.br
.ti -1c
.RI "Gushort \fBgetRotationAngle\fP ()"
.br
.ti -1c
.RI "void \fBgetAspect\fP (int *widthA, int *heightA)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetPoster\fP (\fBObject\fP *obj)"
.br
.ti -1c
.RI "GBool \fBgetShowPoster\fP ()"
.br
.ti -1c
.RI "GBool \fBgetUseFloatingWindow\fP ()"
.br
.ti -1c
.RI "void \fBgetFloatingWindowSize\fP (int *width, int *height)"
.br
.ti -1c
.RI "\fBMovie\fP * \fBcopy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file Movie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
