.TH "MQZipReaderPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQZipReaderPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMQZipPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQZipReaderPrivate\fP (QIODevice *device, bool ownDev)"
.br
.ti -1c
.RI "void \fBscanFiles\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MQZipReader::Status \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 435 of file qzip\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
