.TH "MQZipReader::FileInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQZipReader::FileInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileInfo\fP (const \fBFileInfo\fP &other)"
.br
.ti -1c
.RI "\fBFileInfo\fP & \fBoperator=\fP (const \fBFileInfo\fP &other)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBfilePath\fP"
.br
.ti -1c
.RI "uint \fBisDir\fP: 1"
.br
.ti -1c
.RI "uint \fBisFile\fP: 1"
.br
.ti -1c
.RI "uint \fBisSymLink\fP: 1"
.br
.ti -1c
.RI "QFile::Permissions \fBpermissions\fP"
.br
.ti -1c
.RI "uint \fBcrc32\fP"
.br
.ti -1c
.RI "qint64 \fBsize\fP"
.br
.ti -1c
.RI "QDateTime \fBlastModified\fP"
.br
.ti -1c
.RI "void * \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file qzipreader_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
