.TH "MQZipPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQZipPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMQZipReaderPrivate\fP, and \fBMQZipWriterPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMQZipPrivate\fP (QIODevice *device, bool ownDev)"
.br
.ti -1c
.RI "void \fBfillFileInfo\fP (int index, \fBMQZipReader::FileInfo\fP &fileInfo) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QIODevice * \fBdevice\fP"
.br
.ti -1c
.RI "bool \fBownDevice\fP"
.br
.ti -1c
.RI "bool \fBdirtyFileTree\fP"
.br
.ti -1c
.RI "QList< \fBFileHeader\fP > \fBfileHeaders\fP"
.br
.ti -1c
.RI "QByteArray \fBcomment\fP"
.br
.ti -1c
.RI "uint \fBstart_of_directory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 397 of file qzip\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
