.TH "Ms::AlsaAudio" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AlsaAudio
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Driver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlsaAudio\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP (bool hot=false)"
.br
.ti -1c
.RI "virtual bool \fBstart\fP (bool hotPlug=false)"
.br
.ti -1c
.RI "virtual bool \fBstop\fP ()"
.br
.ti -1c
.RI "float * \fBgetLBuffer\fP (long n)"
.br
.ti -1c
.RI "float * \fBgetRBuffer\fP (long n)"
.br
.ti -1c
.RI "virtual bool \fBisRealtime\fP () const"
.br
.ti -1c
.RI "virtual void \fBstartTransport\fP ()"
.br
.ti -1c
.RI "virtual void \fBstopTransport\fP ()"
.br
.ti -1c
.RI "virtual Transport \fBgetState\fP () override"
.br
.ti -1c
.RI "virtual int \fBsampleRate\fP () const"
.br
.ti -1c
.RI "void \fBalsaLoop\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (int n, void *l)"
.br
.ti -1c
.RI "virtual void \fBmidiRead\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdateOutPortCount\fP (int maxport)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 111 of file alsa\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
