.TH "Ms::AlsaMidiDriver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AlsaMidiDriver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::MidiDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlsaMidiDriver\fP (\fBSeq\fP *s)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP ()"
.br
.ti -1c
.RI "virtual \fBPort\fP \fBregisterOutPort\fP (const QString &name)"
.br
.ti -1c
.RI "virtual \fBPort\fP \fBregisterInPort\fP (const QString &name)"
.br
.ti -1c
.RI "virtual void \fBgetInputPollFd\fP (struct pollfd **, int *n)"
.br
.ti -1c
.RI "virtual void \fBgetOutputPollFd\fP (struct pollfd **, int *n)"
.br
.ti -1c
.RI "virtual void \fBread\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (const \fBEvent\fP &)"
.br
.ti -1c
.RI "virtual void \fBupdateInPortCount\fP (int)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 41 of file alsamidi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
