.TH "Ms::AlsaDriver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AlsaDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlsaDriver\fP (QString, unsigned, snd_pcm_uframes_t, unsigned)"
.br
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBprintinfo\fP ()"
.br
.ti -1c
.RI "bool \fBpcmStart\fP ()"
.br
.ti -1c
.RI "int \fBpcmStop\fP ()"
.br
.ti -1c
.RI "snd_pcm_uframes_t \fBfsize\fP () const"
.br
.ti -1c
.RI "unsigned int \fBsampleRate\fP () const"
.br
.ti -1c
.RI "void \fBwrite\fP (int n, float *l, float *r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file alsa\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
