.TH "Ms::AccessibleToolButton" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AccessibleToolButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits QToolButton\&.
.PP
Inherited by \fBMs::ToolButtonMenu\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccessibleToolButton\fP (QWidget *parent, QAction *defaultQAction=0)"
.br
.ti -1c
.RI "void \fBfocusInEvent\fP (QFocusEvent *e)"
.br
.ti -1c
.RI "void \fBfocusOutEvent\fP (QFocusEvent *e)"
.br
.ti -1c
.RI "void \fBkeyPressEvent\fP (QKeyEvent *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file accessibletoolbutton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
