.TH "Ms::Audio" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Audio
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QString & \fBpath\fP () const"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &s)"
.br
.ti -1c
.RI "const QByteArray & \fBdata\fP () const"
.br
.ti -1c
.RI "QByteArray \fBdata\fP ()"
.br
.ti -1c
.RI "void \fBsetData\fP (const QByteArray &ba)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file audio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
