.TH "Ms::Articulation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Articulation \- articulation marks  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <articulation\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArticulation\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBArticulation\fP (SymId, \fBScore\fP *)"
.br
.ti -1c
.RI "\fBArticulation\fP & \fBoperator=\fP (const \fBArticulation\fP &)=delete"
.br
.ti -1c
.RI "virtual \fBArticulation\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const override"
.br
.ti -1c
.RI "SymId \fBsymId\fP () const"
.br
.ti -1c
.RI "void \fBsetSymId\fP (SymId id)"
.br
.ti -1c
.RI "virtual int \fBsubtype\fP () const override"
.br
.ti -1c
.RI "QString \fBuserName\fP () const"
.br
.ti -1c
.RI "const char * \fBarticulationName\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual bool \fBreadProperties\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBreset\fP () override"
.br
.ti -1c
.RI "virtual QLineF \fBdragAnchor\fP () const override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual PropertyFlags \fBpropertyFlags\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual void \fBresetProperty\fP (P_ID id) override"
.br
.ti -1c
.RI "StyleIdx \fBgetPropertyStyle\fP (P_ID id) const override"
.br
.ti -1c
.RI "bool \fBup\fP () const"
.br
.ti -1c
.RI "void \fBsetUp\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetDirection\fP (\fBDirection\fP d)"
.br
.ti -1c
.RI "\fBDirection\fP \fBdirection\fP () const"
.br
.ti -1c
.RI "\fBChordRest\fP * \fBchordRest\fP () const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "\fBMeasure\fP * \fBmeasure\fP () const"
.br
.ti -1c
.RI "\fBSystem\fP * \fBsystem\fP () const"
.br
.ti -1c
.RI "\fBPage\fP * \fBpage\fP () const"
.br
.ti -1c
.RI "ArticulationAnchor \fBanchor\fP () const"
.br
.ti -1c
.RI "void \fBsetAnchor\fP (ArticulationAnchor v)"
.br
.ti -1c
.RI "qreal \fBtimeStretch\fP () const"
.br
.ti -1c
.RI "void \fBsetTimeStretch\fP (qreal val)"
.br
.ti -1c
.RI "MScore::OrnamentStyle \fBornamentStyle\fP () const"
.br
.ti -1c
.RI "void \fBsetOrnamentStyle\fP (MScore::OrnamentStyle val)"
.br
.ti -1c
.RI "bool \fBplayArticulation\fP () const"
.br
.ti -1c
.RI "void \fBsetPlayArticulation\fP (bool val)"
.br
.ti -1c
.RI "QString \fBchannelName\fP () const"
.br
.ti -1c
.RI "void \fBsetChannelName\fP (const QString &s)"
.br
.ti -1c
.RI "QString \fBaccessibleInfo\fP () const override"
.br
.ti -1c
.RI "bool \fBisFermata\fP () const"
.br
.ti -1c
.RI "bool \fBisTenuto\fP () const"
.br
.ti -1c
.RI "bool \fBisStaccato\fP () const"
.br
.ti -1c
.RI "bool \fBisAccent\fP () const"
.br
.ti -1c
.RI "bool \fBisLuteFingering\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
articulation marks 
.PP
Definition at line 57 of file articulation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
