.TH "Ms::AbstractDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AbstractDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.PP
Inherited by \fBMs::AlbumManager\fP, \fBMs::Debugger\fP, \fBMs::PageSettings\fP, \fBMs::PreferenceDialog\fP, and \fBMs::Startcenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractDialog\fP (QWidget *parent=0, Qt::WindowFlags f=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "virtual void \fBretranslate\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file abstractdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
