.TH "Ms::AccessibleSearchBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AccessibleSearchBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and QAccessibleWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsearchFinished\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccessibleSearchBox\fP (\fBSearchComboBox\fP *comboBox)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QAccessibleInterface * \fBSearchBoxFactory\fP (const QString &classname, QObject *object)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file searchComboBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
