.TH "Ms::Ambitus" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Ambitus
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAmbitus\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBAmbitus\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "void \fBinitFrom\fP (\fBAmbitus\fP *a)"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "NoteHead::Group \fBnoteHeadGroup\fP () const"
.br
.ti -1c
.RI "NoteHead::Type \fBnoteHeadType\fP () const"
.br
.ti -1c
.RI "MScore::DirectionH \fBdirection\fP () const"
.br
.ti -1c
.RI "bool \fBhasLine\fP () const"
.br
.ti -1c
.RI "\fBSpatium\fP \fBlineWidth\fP () const"
.br
.ti -1c
.RI "int \fBtopOctave\fP () const"
.br
.ti -1c
.RI "int \fBbottomOctave\fP () const"
.br
.ti -1c
.RI "int \fBtopPitch\fP () const"
.br
.ti -1c
.RI "int \fBbottomPitch\fP () const"
.br
.ti -1c
.RI "int \fBtopTpc\fP () const"
.br
.ti -1c
.RI "int \fBbottomTpc\fP () const"
.br
.ti -1c
.RI "void \fBsetNoteHeadGroup\fP (NoteHead::Group val)"
.br
.ti -1c
.RI "void \fBsetNoteHeadType\fP (NoteHead::Type val)"
.br
.ti -1c
.RI "void \fBsetDirection\fP (MScore::DirectionH val)"
.br
.ti -1c
.RI "void \fBsetHasLine\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetLineWidth\fP (\fBSpatium\fP val)"
.br
.ti -1c
.RI "void \fBsetTopPitch\fP (int val)"
.br
.ti -1c
.RI "void \fBsetBottomPitch\fP (int val)"
.br
.ti -1c
.RI "void \fBsetTopTpc\fP (int val)"
.br
.ti -1c
.RI "void \fBsetBottomTpc\fP (int val)"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "SymId \fBnoteHead\fP () const"
.br
.ti -1c
.RI "qreal \fBheadWidth\fP () const"
.br
.ti -1c
.RI "void \fBupdateRange\fP ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QPointF \fBpagePos\fP () const override"
.br
.RI "position in page coordinates "
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBscanElements\fP (void *data, void(*func)(void *, \fBElement\fP *), bool all=true) override"
.br
.ti -1c
.RI "virtual void \fBsetTrack\fP (int val) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual bool \fBreadProperties\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.ti -1c
.RI "virtual QString \fBscreenReaderInfo\fP () const override"
.br
.ti -1c
.RI "QVariant \fBgetProperty\fP (P_ID) const"
.br
.ti -1c
.RI "bool \fBsetProperty\fP (P_ID propertyId, const QVariant &)"
.br
.ti -1c
.RI "QVariant \fBpropertyDefault\fP (P_ID id) const"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBnextElement\fP () override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBprevElement\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file ambitus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
