.TH "Ms::AccidentalState" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AccidentalState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (Key key)"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBKeySigEvent\fP &, ClefType)"
.br
.ti -1c
.RI "AccidentalVal \fBaccidentalVal\fP (int line, bool &error) const"
.br
.ti -1c
.RI "AccidentalVal \fBaccidentalVal\fP (int line) const"
.br
.ti -1c
.RI "bool \fBtieContext\fP (int line) const"
.br
.ti -1c
.RI "void \fBsetAccidentalVal\fP (int line, AccidentalVal val, bool tieContext=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
