.TH "Ms::AccessibleScoreView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AccessibleScoreView
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and QAccessibleWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccessibleScoreView\fP (\fBScoreView\fP *c)"
.br
.ti -1c
.RI "int \fBchildCount\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QAccessibleInterface * \fBchild\fP (int) const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QAccessibleInterface * \fBparent\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QRect \fBrect\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QAccessible::Role \fBrole\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QString \fBtext\fP (QAccessible::Text t) const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QWindow * \fBwindow\fP () const Q_DECL_OVERRIDE"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QAccessibleInterface * \fBScoreViewFactory\fP (const QString &classname, QObject *object)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file scoreaccessibility\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
