.TH "Ms::AlbumManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AlbumManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::AbstractDialog\fP, and \fBUi::AlbumManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlbumManager\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetAlbum\fP (\fBMovements\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBretranslate\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 27 of file albummanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
