.TH "Ms::AlignSelect" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::AlignSelect
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::AlignSelect\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBalignChanged\fP (Align)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlignSelect\fP (QWidget *parent)"
.br
.ti -1c
.RI "Align \fBalign\fP () const"
.br
.ti -1c
.RI "void \fBsetAlign\fP (Align)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file alignSelect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
