.TH "Ms::BspTree::Node" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BspTree::Node
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : char { \fBHORIZONTAL\fP, \fBVERTICAL\fP, \fBLEAF\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   qreal \fBoffset\fP"
.br
.ti -1c
.RI "   int \fBleafIndex\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "Type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file bsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
