.TH "Ms::BagpipeEmbellishment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BagpipeEmbellishment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBagpipeEmbellishment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBBagpipeEmbellishment\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "int \fBembelType\fP () const"
.br
.ti -1c
.RI "void \fBsetEmbelType\fP (int val)"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "noteList \fBgetNoteList\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBnEmbellishments\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBBagpipeEmbellishmentInfo\fP \fBBagpipeEmbellishmentList\fP []"
.br
.ti -1c
.RI "static \fBBagpipeNoteInfo\fP \fBBagpipeNoteInfoList\fP []"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 51 of file bagpembell\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBagpipeNoteInfo\fP Ms::BagpipeEmbellishment::BagpipeNoteInfoList\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
      { "LG",  6,  65},
      { "LA",  5,  67},
      { "B",   4,  69},
      { "C",   3,  71}, 
      { "D",   2,  72},
      { "E",   1,  74},
      { "F",   0,  76}, 
      { "HG", -1,  77},
      { "HA", -2,  79}
}
.fi
.PP
Definition at line 71 of file bagpembell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
