.TH "Ms::BSymbol" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BSymbol \- base class for \fBSymbol\fP and \fBImage\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsymbol\&.h>\fP
.PP
Inherits \fBMs::Element\fP, and \fBMs::ElementLayout\fP\&.
.PP
Inherited by \fBMs::FSymbol\fP, \fBMs::Image\fP, and \fBMs::Symbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBSymbol\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBBSymbol\fP (const \fBBSymbol\fP &)"
.br
.ti -1c
.RI "\fBBSymbol\fP & \fBoperator=\fP (const \fBBSymbol\fP &)=delete"
.br
.ti -1c
.RI "virtual void \fBadd\fP (\fBElement\fP *) override"
.br
.ti -1c
.RI "virtual void \fBremove\fP (\fBElement\fP *) override"
.br
.ti -1c
.RI "virtual void \fBscanElements\fP (void *data, void(*func)(void *, \fBElement\fP *), bool all=true) override"
.br
.ti -1c
.RI "virtual bool \fBacceptDrop\fP (\fBEditData\fP &) const override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBdrop\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QRectF \fBdrag\fP (\fBEditData\fP &) override"
.br
.RI "Return update Rect relative to canvas\&. "
.ti -1c
.RI "void \fBwriteProperties\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "const QList< \fBElement\fP * > & \fBleafs\fP () const"
.br
.ti -1c
.RI "QList< \fBElement\fP * > & \fBleafs\fP ()"
.br
.ti -1c
.RI "virtual QPointF \fBpagePos\fP () const override"
.br
.RI "position in page coordinates "
.ti -1c
.RI "virtual QPointF \fBcanvasPos\fP () const override"
.br
.RI "position in canvas coordinates "
.ti -1c
.RI "virtual QLineF \fBdragAnchor\fP () const override"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "bool \fBsystemFlag\fP () const"
.br
.ti -1c
.RI "void \fBsetSystemFlag\fP (bool val)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
base class for \fBSymbol\fP and \fBImage\fP 
.PP
Definition at line 26 of file bsymbol\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Ms::BSymbol::acceptDrop (\fBEditData\fP &) const\fC [override]\fP, \fC [virtual]\fP"
Return true if this element accepts a drop at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&.
.PP
Reimplemented by elements that accept drops\&. Used to change cursor shape while dragging to indicate drop targets\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 130 of file bsymbol\&.cpp\&.
.SS "\fBElement\fP * Ms::BSymbol::drop (\fBEditData\fP &)\fC [override]\fP, \fC [virtual]\fP"
Handle a dropped element at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&. Returns dropped element if any\&. The ownership of element in DropData is transfered to the called element (if not used, element has to be deleted)\&. The returned element will be selected if not in note edit mode\&.
.PP
Reimplemented by elements that accept drops\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 140 of file bsymbol\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
