.TH "Ms::BspTreeVisitor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BspTreeVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::FindItemBspTreeVisitor\fP, \fBMs::InsertItemBspTreeVisitor\fP, and \fBMs::RemoveItemBspTreeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBvisit\fP (QList< \fBElement\fP *> *items)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file bsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
