.TH "Ms::Bm" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Bm
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBm\fP (signed char a, signed char b)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBkey\fP (int a, int b, int c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "signed char \fBl\fP"
.br
.ti -1c
.RI "signed char \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 662 of file beam\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
