.TH "Ms::BasicDrawObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BasicDrawObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::CapellaObj\fP\&.
.PP
Inherited by \fBMs::BasicRectObj\fP, \fBMs::GroupObj\fP, \fBMs::GuitarObj\fP, \fBMs::LineObj\fP, \fBMs::NotelinesObj\fP, \fBMs::PolygonObj\fP, \fBMs::SimpleTextObj\fP, \fBMs::SlurObj\fP, \fBMs::TransposableObj\fP, \fBMs::TrillObj\fP, and \fBMs::VoltaObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicDrawObj\fP (CapellaType t, \fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBmodeX\fP"
.br
.ti -1c
.RI "unsigned char \fBmodeY\fP"
.br
.ti -1c
.RI "unsigned char \fBdistY\fP"
.br
.ti -1c
.RI "unsigned char \fBflags\fP"
.br
.ti -1c
.RI "int \fBnRefNote\fP"
.br
.ti -1c
.RI "int \fBnNotes\fP"
.br
.ti -1c
.RI "bool \fBbackground\fP"
.br
.ti -1c
.RI "int \fBpageRange\fP"
.br
.ti -1c
.RI "CapellaType \fBtype\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 241 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
