.TH "Ms::BeamFragment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BeamFragment
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qreal \fBpy1\fP [2]"
.br
.ti -1c
.RI "qreal \fBpy2\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file beam\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
