.TH "Ms::BspTree" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BspTree
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (const QRectF &rect, int depth)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBElement\fP *item)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBElement\fP *item)"
.br
.ti -1c
.RI "QList< \fBElement\fP * > \fBitems\fP (const QRectF &rect)"
.br
.ti -1c
.RI "QList< \fBElement\fP * > \fBitems\fP (const QPointF &pos)"
.br
.ti -1c
.RI "int \fBleafCount\fP () const"
.br
.ti -1c
.RI "int \fBfirstChildIndex\fP (int index) const"
.br
.ti -1c
.RI "int \fBparentIndex\fP (int index) const"
.br
.ti -1c
.RI "QString \fBdebug\fP (int index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file bsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
