.TH "Ms::BasicDurationalObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BasicDurationalObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::CapellaObj\fP\&.
.PP
Inherited by \fBMs::ChordObj\fP, and \fBMs::RestObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicDurationalObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e, unsigned int &fullm)"
.br
.ti -1c
.RI "void \fBreadCapxDisplay\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBreadCapxObjectArray\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "int \fBticks\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnDots\fP"
.br
.ti -1c
.RI "bool \fBnoDuration\fP"
.br
.ti -1c
.RI "bool \fBpostGrace\fP"
.br
.ti -1c
.RI "bool \fBbSmall\fP"
.br
.ti -1c
.RI "bool \fBnotBlack\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "TIMESTEP \fBt\fP"
.br
.ti -1c
.RI "int \fBhorizontalShift\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "bool \fBtripartite\fP"
.br
.ti -1c
.RI "bool \fBisProlonging\fP"
.br
.ti -1c
.RI "bool \fBinvisible\fP"
.br
.ti -1c
.RI "QList< \fBBasicDrawObj\fP * > \fBobjects\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 519 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
