.TH "Ms::BEDrawingDataX" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BEDrawingDataX
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBEDrawingDataX\fP (SymId hs, SymId fs, const qreal m, const qreal s, const int nn)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const SymId \fBheadsym\fP"
.br
.ti -1c
.RI "const SymId \fBflagsym\fP"
.br
.ti -1c
.RI "const qreal \fBmags\fP"
.br
.ti -1c
.RI "qreal \fBheadw\fP"
.br
.ti -1c
.RI "qreal \fBheadp\fP"
.br
.ti -1c
.RI "const qreal \fBspatium\fP"
.br
.ti -1c
.RI "const qreal \fBlw\fP"
.br
.ti -1c
.RI "qreal \fBxl\fP"
.br
.ti -1c
.RI "const qreal \fBxcorr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 386 of file bagpembell\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
