.TH "Ms::BEDrawingDataY" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BEDrawingDataY
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBEDrawingDataY\fP (const int l, const qreal s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const qreal \fBy1b\fP"
.br
.ti -1c
.RI "const qreal \fBy1f\fP"
.br
.ti -1c
.RI "const qreal \fBy2\fP"
.br
.ti -1c
.RI "const qreal \fBycorr\fP"
.br
.ti -1c
.RI "const qreal \fBbw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 418 of file bagpembell\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
