.TH "Ms::BarLineEditData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BarLineEditData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::ElementEditData\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qreal \fByoff1\fP"
.br
.ti -1c
.RI "qreal \fByoff2\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file barline\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
