.TH "Ms::BBFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BBFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBread\fP (const QString &)"
.br
.ti -1c
.RI "QList< \fBBBTrack\fP * > * \fBtracks\fP ()"
.br
.ti -1c
.RI "int \fBmeasures\fP () const"
.br
.ti -1c
.RI "const char * \fBtitle\fP () const"
.br
.ti -1c
.RI "\fBTimeSigMap\fP \fBsiglist\fP () const"
.br
.ti -1c
.RI "QList< \fBBBChord\fP > \fBchords\fP ()"
.br
.ti -1c
.RI "int \fBstartChorus\fP () const"
.br
.ti -1c
.RI "int \fBendChorus\fP () const"
.br
.ti -1c
.RI "int \fBrepeats\fP () const"
.br
.ti -1c
.RI "int \fBkey\fP () const"
.br
.ti -1c
.RI "void \fBconvertTrack\fP (\fBScore\fP *score, \fBBBTrack\fP *track, int staffIdx)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file bb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
