.TH "Ms::BarLineTableItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BarLineTableItem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BarLineType \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBuserName\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file barline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
