.TH "Ms::BracketItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BracketItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::ScoreElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBracketItem\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBBracketItem\fP (\fBScore\fP *s, BracketType a, int b)"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "bool \fBselected\fP () const"
.br
.ti -1c
.RI "int \fBbracketSpan\fP () const"
.br
.ti -1c
.RI "BracketType \fBbracketType\fP () const"
.br
.ti -1c
.RI "void \fBsetSelected\fP (bool v)"
.br
.ti -1c
.RI "void \fBsetBracketSpan\fP (int v)"
.br
.ti -1c
.RI "void \fBsetBracketType\fP (BracketType v)"
.br
.ti -1c
.RI "\fBStaff\fP * \fBstaff\fP ()"
.br
.ti -1c
.RI "void \fBsetStaff\fP (\fBStaff\fP *s)"
.br
.ti -1c
.RI "int \fBcolumn\fP () const"
.br
.ti -1c
.RI "void \fBsetColumn\fP (int v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file bracketItem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
