.TH "Ms::BBTrack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BBTrack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBBTrack\fP (\fBBBFile\fP *)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "const \fBEventList\fP \fBevents\fP () const"
.br
.ti -1c
.RI "\fBEventList\fP & \fBevents\fP ()"
.br
.ti -1c
.RI "int \fBoutChannel\fP () const"
.br
.ti -1c
.RI "void \fBsetOutChannel\fP (int n)"
.br
.ti -1c
.RI "void \fBinsert\fP (const \fBEvent\fP &e)"
.br
.ti -1c
.RI "void \fBappend\fP (const \fBEvent\fP &e)"
.br
.ti -1c
.RI "void \fBfindChords\fP ()"
.br
.ti -1c
.RI "int \fBseparateVoices\fP (int)"
.br
.ti -1c
.RI "void \fBcleanup\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBBFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file bb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
