.TH "Ms::BendCanvas" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BendCanvas
.SH SYNOPSIS
.br
.PP
.PP
Inherits QFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBendCanvas\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "const QList< \fBPitchValue\fP > & \fBpoints\fP () const"
.br
.ti -1c
.RI "QList< \fBPitchValue\fP > & \fBpoints\fP ()"
.br
.ti -1c
.RI "void \fBsetPoints\fP (const QList< \fBPitchValue\fP > &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file bendcanvas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
