.TH "Ms::BBChord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::BBChord
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbeat\fP"
.br
.ti -1c
.RI "unsigned char \fBbass\fP"
.br
.ti -1c
.RI "unsigned char \fBroot\fP"
.br
.ti -1c
.RI "unsigned char \fBextension\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file bb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
