.TH "Ms::ChordStyleEditor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordStyleEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::ChordStyleEditor\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBaccept\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChordStyleEditor\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "bool \fBdirty\fP () const"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.ti -1c
.RI "void \fBrestore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file harmonyedit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
