.TH "Ms::ChangeFretting" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChangeFretting
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeFretting\fP (\fBNote\fP *note, int pitch, int string, int fret, int tpc1, int tpc2)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 323 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
