.TH "Ms::ClefInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ClefInfo \- Info about a clef\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clef\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBtag\fP (ClefType t)"
.br
.ti -1c
.RI "static const char * \fBsign\fP (ClefType t)"
.br
.ti -1c
.RI "static int \fBline\fP (ClefType t)"
.br
.ti -1c
.RI "static int \fBoctChng\fP (ClefType t)"
.br
.ti -1c
.RI "static int \fBpitchOffset\fP (ClefType t)"
.br
.ti -1c
.RI "static SymId \fBsymId\fP (ClefType t)"
.br
.ti -1c
.RI "static const signed char * \fBlines\fP (ClefType t)"
.br
.ti -1c
.RI "static const char * \fBname\fP (ClefType t)"
.br
.ti -1c
.RI "static StaffGroup \fBstaffGroup\fP (ClefType t)"
.br
.ti -1c
.RI "static ClefType \fBtag2type\fP (const QString &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fB_tag\fP"
.br
.RI "comprehensive name for instruments\&.xml "
.ti -1c
.RI "const char * \fB_sign\fP"
.br
.RI "Name for musicXml\&. "
.ti -1c
.RI "int \fB_line\fP"
.br
.RI "\fBLine\fP for musicXml and for positioning on the staff\&. "
.ti -1c
.RI "int \fB_octChng\fP"
.br
.RI "Octave change for musicXml\&. "
.ti -1c
.RI "int \fB_pitchOffset\fP"
.br
.RI "Pitch offset for line 0\&. "
.ti -1c
.RI "signed char \fB_lines\fP [14]"
.br
.ti -1c
.RI "SymId \fB_symId\fP"
.br
.ti -1c
.RI "const char * \fB_name\fP"
.br
.ti -1c
.RI "StaffGroup \fB_staffGroup\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBClefInfo\fP \fBclefTable\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Info about a clef\&. 
.PP
Definition at line 95 of file clef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
