.TH "Ms::ChordItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGraphicsRectItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChordItem\fP (\fBChordView\fP *, \fBNote\fP *, \fBNoteEvent\fP *)"
.br
.ti -1c
.RI "virtual int \fBtype\fP () const"
.br
.ti -1c
.RI "\fBNoteEvent\fP * \fBevent\fP () const"
.br
.ti -1c
.RI "\fBNote\fP * \fBnote\fP () const"
.br
.ti -1c
.RI "bool \fBcurrent\fP () const"
.br
.ti -1c
.RI "void \fBsetCurrent\fP (bool v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file chordview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
