.TH "Ms::ChordLine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordLine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chordline\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChordLine\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBChordLine\fP (const \fBChordLine\fP &)"
.br
.ti -1c
.RI "virtual \fBChordLine\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBsetChordLineType\fP (ChordLineType)"
.br
.ti -1c
.RI "ChordLineType \fBchordLineType\fP () const"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisStraight\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetStraight\fP (bool straight)"
.br
.ti -1c
.RI "virtual void \fBsetLengthX\fP (qreal length)"
.br
.ti -1c
.RI "virtual void \fBsetLengthY\fP (qreal length)"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBeditDrag\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBupdateGrips\fP (\fBEditData\fP &) const override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
bezier line attached to top note of a chord implements fall, doit, plop, bend 
.PP
Definition at line 34 of file chordline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
