.TH "Ms::CNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CNote
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "signed char \fBpitch\fP"
.br
.ti -1c
.RI "int \fBexplAlteration\fP"
.br
.ti -1c
.RI "int \fBheadType\fP"
.br
.ti -1c
.RI "int \fBalteration\fP"
.br
.ti -1c
.RI "int \fBsilent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 557 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
