.TH "Ms::ChangeProperty" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChangeProperty
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeProperty\fP (\fBScoreElement\fP *e, P_ID i, const QVariant &v, PropertyFlags ps=PropertyFlags::NOSTYLE)"
.br
.ti -1c
.RI "P_ID \fBgetId\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 935 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
