.TH "Ms::CapSystem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapSystem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnAddBarCount\fP"
.br
.ti -1c
.RI "bool \fBbBarCountReset\fP"
.br
.ti -1c
.RI "unsigned char \fBexplLeftIndent\fP"
.br
.ti -1c
.RI "BeamMode \fBbeamMode\fP"
.br
.ti -1c
.RI "unsigned \fBtempo\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "bool \fBbJustified\fP"
.br
.ti -1c
.RI "bool \fBbPageBreak\fP"
.br
.ti -1c
.RI "int \fBinstrNotation\fP"
.br
.ti -1c
.RI "QList< \fBCapStaff\fP * > \fBstaves\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 217 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
