.TH "Ms::CapExplicitBarline" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapExplicitBarline
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::NoteObj\fP, and \fBMs::CapellaObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapExplicitBarline\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "BarLineType \fBtype\fP () const"
.br
.ti -1c
.RI "int \fBbarMode\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 137 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
