.TH "Ms::ClefTypeList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ClefTypeList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClefTypeList\fP (ClefType a, ClefType b)"
.br
.ti -1c
.RI "\fBClefTypeList\fP (ClefType a)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBClefTypeList\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBClefTypeList\fP &t) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ClefType \fB_concertClef\fP = ClefType::G"
.br
.ti -1c
.RI "ClefType \fB_transposingClef\fP = ClefType::G"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file clef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
