.TH "Ms::CharFormat" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CharFormat
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCharFormat\fP &) const"
.br
.ti -1c
.RI "bool \fBbold\fP () const"
.br
.ti -1c
.RI "bool \fBitalic\fP () const"
.br
.ti -1c
.RI "bool \fBunderline\fP () const"
.br
.ti -1c
.RI "bool \fBpreedit\fP () const"
.br
.ti -1c
.RI "VerticalAlignment \fBvalign\fP () const"
.br
.ti -1c
.RI "qreal \fBfontSize\fP () const"
.br
.ti -1c
.RI "QString \fBfontFamily\fP () const"
.br
.ti -1c
.RI "void \fBsetBold\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetItalic\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetUnderline\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetPreedit\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetValign\fP (VerticalAlignment val)"
.br
.ti -1c
.RI "void \fBsetFontSize\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetFontFamily\fP (const QString &val)"
.br
.ti -1c
.RI "void \fBsetFormat\fP (FormatId, QVariant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file text\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
