.TH "Ms::CmdState" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CmdState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "UpdateMode \fBupdateMode\fP () const"
.br
.ti -1c
.RI "void \fBsetUpdateMode\fP (UpdateMode m)"
.br
.ti -1c
.RI "void \fB_setUpdateMode\fP (UpdateMode m)"
.br
.ti -1c
.RI "bool \fBlayoutRange\fP () const"
.br
.ti -1c
.RI "bool \fBupdateAll\fP () const"
.br
.ti -1c
.RI "bool \fBupdateRange\fP () const"
.br
.ti -1c
.RI "void \fBsetTick\fP (int t)"
.br
.ti -1c
.RI "int \fBstartTick\fP () const"
.br
.ti -1c
.RI "int \fBendTick\fP () const"
.br
.ti -1c
.RI "void \fBdump\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayoutFlags \fBlayoutFlags\fP"
.br
.ti -1c
.RI "bool \fB_excerptsChanged\fP { false }"
.br
.ti -1c
.RI "bool \fB_instrumentsChanged\fP { false }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 245 of file score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
