.TH "Ms::Cursor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Cursor
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCursor\fP (\fBScore\fP *c=0)"
.br
.ti -1c
.RI "\fBCursor\fP (\fBScore\fP *, bool)"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "int \fBtrack\fP () const"
.br
.ti -1c
.RI "void \fBsetTrack\fP (int v)"
.br
.ti -1c
.RI "int \fBstaffIdx\fP () const"
.br
.ti -1c
.RI "void \fBsetStaffIdx\fP (int v)"
.br
.ti -1c
.RI "int \fBvoice\fP () const"
.br
.ti -1c
.RI "void \fBsetVoice\fP (int v)"
.br
.ti -1c
.RI "int \fBfilter\fP () const"
.br
.ti -1c
.RI "void \fBsetFilter\fP (int f)"
.br
.ti -1c
.RI "Q_INVOKABLE \fBMs::ElementW\fP * \fBelement\fP () const"
.br
.ti -1c
.RI "Q_INVOKABLE \fBMs::ElementW\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "Q_INVOKABLE \fBMs::ElementW\fP * \fBmeasure\fP () const"
.br
.ti -1c
.RI "int \fBtick\fP ()"
.br
.ti -1c
.RI "double \fBtime\fP ()"
.br
.ti -1c
.RI "qreal \fBtempo\fP ()"
.br
.ti -1c
.RI "int \fBqmlKeySignature\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBrewind\fP (int type)"
.br
.ti -1c
.RI "Q_INVOKABLE bool \fBnext\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE bool \fBnextMeasure\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBadd\fP (\fBMs::Element\fP *)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBaddNote\fP (int pitch)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetDuration\fP (int z, int n)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBtrack\fP"
.br
.ti -1c
.RI "int \fBstaffIdx\fP"
.br
.ti -1c
.RI "int \fBvoice\fP"
.br
.ti -1c
.RI "int \fBfilter\fP"
.br
.ti -1c
.RI "int \fBtick\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "qreal \fBtempo\fP"
.br
.ti -1c
.RI "int \fBkeySignature\fP"
.br
.ti -1c
.RI "\fBMs::Score\fP \fBscore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file cursor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
