.TH "Ms::Compressor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Compressor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (float fsamp)"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (int n, float *inp, float *out)"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const"
.br
.ti -1c
.RI "virtual \fBEffectGui\fP * \fBgui\fP ()"
.br
.ti -1c
.RI "virtual const std::vector< \fBParDescr\fP > & \fBparDescr\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetNValue\fP (int parameter, double value)"
.br
.ti -1c
.RI "virtual double \fBnvalue\fP (int idx) const"
.br
.ti -1c
.RI "virtual \fBSynthesizerGroup\fP \fBstate\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetState\fP (const \fBSynthesizerGroup\fP &)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 54 of file compressor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
