.TH "Ms::CapStaffLayout" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapStaffLayout
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uchar \fBbarlineMode\fP"
.br
.ti -1c
.RI "uchar \fBnoteLines\fP"
.br
.ti -1c
.RI "bool \fBbSmall\fP"
.br
.ti -1c
.RI "int \fBtopDist\fP"
.br
.ti -1c
.RI "int \fBbtmDist\fP"
.br
.ti -1c
.RI "int \fBgroupDist\fP"
.br
.ti -1c
.RI "uchar \fBbarlineFrom\fP"
.br
.ti -1c
.RI "uchar \fBbarlineTo\fP"
.br
.ti -1c
.RI "\fBForm\fP \fBform\fP"
.br
.ti -1c
.RI "ClefLine \fBline\fP"
.br
.ti -1c
.RI "Oct \fBoct\fP"
.br
.ti -1c
.RI "bool \fBbPercussion\fP"
.br
.ti -1c
.RI "bool \fBbSoundMapIn\fP"
.br
.ti -1c
.RI "bool \fBbSoundMapOut\fP"
.br
.ti -1c
.RI "char \fBsoundMapIn\fP [128]"
.br
.ti -1c
.RI "char \fBsoundMapOut\fP [128]"
.br
.ti -1c
.RI "int \fBsound\fP"
.br
.ti -1c
.RI "int \fBvolume\fP"
.br
.ti -1c
.RI "int \fBtransp\fP"
.br
.ti -1c
.RI "QString \fBdescr\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBabbrev\fP"
.br
.ti -1c
.RI "QString \fBintermediateName\fP"
.br
.ti -1c
.RI "QString \fBintermediateAbbrev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 183 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
