.TH "Ms::ChangePitch" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChangePitch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangePitch\fP (\fBNote\fP *note, int pitch, int tpc1, int tpc2)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 307 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
