.TH "Ms::ChordList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordList
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMap< int, ChordDescription >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "bool \fBread\fP (const QString &)"
.br
.ti -1c
.RI "bool \fBwrite\fP (const QString &) const"
.br
.ti -1c
.RI "bool \fBloaded\fP () const"
.br
.ti -1c
.RI "void \fBunload\fP ()"
.br
.ti -1c
.RI "\fBChordSymbol\fP \fBsymbol\fP (const QString &s) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBChordFont\fP > \fBfonts\fP"
.br
.ti -1c
.RI "QList< \fBRenderAction\fP > \fBrenderListRoot\fP"
.br
.ti -1c
.RI "QList< \fBRenderAction\fP > \fBrenderListBase\fP"
.br
.ti -1c
.RI "QList< \fBChordToken\fP > \fBchordTokenList\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBprivateID\fP = \-1000"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 228 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
