.TH "Ms::ChordObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicDurationalObj\fP, and \fBMs::NoteObj\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStemDir\fP : signed char { \fBDOWN\fP = -1, \fBAUTO\fP = 0, \fBUP\fP = 1, \fBNONE\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChordObj\fP (\fBCapella\fP *)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBreadCapxLyrics\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBreadCapxNotes\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBreadCapxStem\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBreadCapxArticulation\fP (\fBXmlReader\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BeamMode \fBbeamMode\fP"
.br
.ti -1c
.RI "signed char \fBnotationStave\fP"
.br
.ti -1c
.RI "char \fBdStemLength\fP"
.br
.ti -1c
.RI "unsigned char \fBnTremoloBars\fP"
.br
.ti -1c
.RI "unsigned \fBarticulation\fP"
.br
.ti -1c
.RI "bool \fBleftTie\fP"
.br
.ti -1c
.RI "bool \fBrightTie\fP"
.br
.ti -1c
.RI "char \fBbeamShift\fP"
.br
.ti -1c
.RI "char \fBbeamSlope\fP"
.br
.ti -1c
.RI "QList< \fBVerse\fP > \fBverse\fP"
.br
.ti -1c
.RI "QList< \fBCNote\fP > \fBnotes\fP"
.br
.ti -1c
.RI "StemDir \fBstemDir\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 569 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
