.TH "Ms::ChordView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordView
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGraphicsView\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBmoveLocator\fP ()"
.br
.ti -1c
.RI "void \fBselectionChanged\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmagChanged\fP (double, double)"
.br
.ti -1c
.RI "void \fBxposChanged\fP (int)"
.br
.ti -1c
.RI "void \fBpitchChanged\fP (int)"
.br
.ti -1c
.RI "void \fBposChanged\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetChord\fP (\fBChord\fP *)"
.br
.ti -1c
.RI "void \fBensureVisible\fP (int tick)"
.br
.ti -1c
.RI "QList< QGraphicsItem * > \fBitems\fP ()"
.br
.ti -1c
.RI "bool \fBevenGrid\fP () const"
.br
.ti -1c
.RI "void \fBsetEvenGrid\fP (bool val)"
.br
.ti -1c
.RI "\fBGripItem\fP * \fBrightGrip\fP () const"
.br
.ti -1c
.RI "void \fBsetCurItem\fP (\fBChordItem\fP *)"
.br
.ti -1c
.RI "bool \fBdirty\fP () const"
.br
.ti -1c
.RI "void \fBsetDirty\fP (bool b)"
.br
.ti -1c
.RI "\fBNote\fP * \fBcurNote\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBpos2pix\fP (int pos)"
.br
.ti -1c
.RI "static int \fBpix2pos\fP (int pix)"
.br
.ti -1c
.RI "static int \fBy2pitch\fP (int pix)"
.br
.ti -1c
.RI "static int \fBpitch2y\fP (int pitch)"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBdeleteItem\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwheelEvent\fP (QWheelEvent *)"
.br
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QMouseEvent *)"
.br
.ti -1c
.RI "virtual void \fBleaveEvent\fP (QEvent *)"
.br
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file chordview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
