.TH "Ms::ContinuousPanel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ContinuousPanel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContinuousPanel\fP (\fBScoreView\fP *sv)"
.br
.ti -1c
.RI "QRectF \fBrect\fP () const"
.br
.ti -1c
.RI "void \fBsetRect\fP (const QRectF &r)"
.br
.ti -1c
.RI "bool \fBactive\fP () const"
.br
.ti -1c
.RI "void \fBsetActive\fP (bool val)"
.br
.ti -1c
.RI "bool \fBvisible\fP ()"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "qreal \fBwidth\fP ()"
.br
.ti -1c
.RI "void \fBpaint\fP (const QRect &r, QPainter &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file continuouspanel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
