.TH "Ms::CapMeter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapMeter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::NoteObj\fP, and \fBMs::CapellaObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapMeter\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBnumerator\fP"
.br
.ti -1c
.RI "int \fBlog2Denom\fP"
.br
.ti -1c
.RI "bool \fBallaBreve\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 122 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
