.TH "Ms::ChordSymbol" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordSymbol
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfontIdx\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBvalue\fP"
.br
.ti -1c
.RI "QChar \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
