.TH "Ms::ChordDescription" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChordDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChordDescription\fP (int)"
.br
.ti -1c
.RI "\fBChordDescription\fP (const QString &)"
.br
.ti -1c
.RI "QString \fBquality\fP () const"
.br
.ti -1c
.RI "void \fBcomplete\fP (\fBParsedChord\fP *pc, const \fBChordList\fP *)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "QStringList \fBnames\fP"
.br
.ti -1c
.RI "QList< \fBParsedChord\fP > \fBparsedChords\fP"
.br
.ti -1c
.RI "QString \fBxmlKind\fP"
.br
.ti -1c
.RI "QString \fBxmlText\fP"
.br
.ti -1c
.RI "QString \fBxmlSymbols\fP"
.br
.ti -1c
.RI "QString \fBxmlParens\fP"
.br
.ti -1c
.RI "QStringList \fBxmlDegrees\fP"
.br
.ti -1c
.RI "\fBHChord\fP \fBchord\fP"
.br
.ti -1c
.RI "QList< \fBRenderAction\fP > \fBrenderList\fP"
.br
.ti -1c
.RI "bool \fBgenerated\fP"
.br
.ti -1c
.RI "bool \fBrenderListGenerated\fP"
.br
.ti -1c
.RI "bool \fBexportOk\fP"
.br
.ti -1c
.RI "QString \fB_quality\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 173 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
