.TH "Ms::CapVoice" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapVoice
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uchar \fBy0Lyrics\fP"
.br
.ti -1c
.RI "uchar \fBdyLyrics\fP"
.br
.ti -1c
.RI "QFont \fBlyricsFont\fP"
.br
.ti -1c
.RI "unsigned char \fBstemDir\fP"
.br
.ti -1c
.RI "QList< \fBNoteObj\fP * > \fBobjects\fP"
.br
.ti -1c
.RI "int \fBvoiceNo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
