.TH "Ms::CapClef" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapClef
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::NoteObj\fP, and \fBMs::CapellaObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapClef\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "const char * \fBname\fP ()"
.br
.ti -1c
.RI "ClefType \fBclef\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ClefType \fBclefType\fP (\fBForm\fP, ClefLine, Oct)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ClefLine \fBline\fP"
.br
.ti -1c
.RI "Oct \fBoct\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 87 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
