.TH "Ms::CapellaObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::CapellaObj
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::BasicDrawObj\fP, \fBMs::BasicDurationalObj\fP, \fBMs::CapClef\fP, \fBMs::CapExplicitBarline\fP, \fBMs::CapKey\fP, and \fBMs::CapMeter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapellaObj\fP (\fBCapella\fP *c)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCapella\fP * \fBcap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
