.TH "Ms::Compound" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Compound
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompound\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBCompound\fP (const \fBCompound\fP &)"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual void \fBaddElement\fP (\fBElement\fP *, qreal x, qreal y)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetSelected\fP (bool f)"
.br
.ti -1c
.RI "virtual void \fBsetVisible\fP (bool)"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "const QList< \fBElement\fP * > & \fBgetElements\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 544 of file element\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ms::Compound::addElement (\fBElement\fP * e, qreal x, qreal y)\fC [virtual]\fP"
offset \fIx\fP and \fIy\fP are in Point units 
.PP
Definition at line 811 of file element\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
