.TH "Ms::ChangePart" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ChangePart
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangePart\fP (\fBPart\fP *, \fBInstrument\fP *, const QString &name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 598 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
