.TH "Ms::DoubleLabel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DoubleLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QLabel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDoubleLabel\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetValue\fP (double)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 432 of file debugger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
