.TH "Ms::DirectionsAnchor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DirectionsAnchor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectionsAnchor\fP (\fBElement\fP *a, bool s, int t)"
.br
.ti -1c
.RI "\fBDirectionsAnchor\fP (int t)"
.br
.ti -1c
.RI "\fBElement\fP * \fBgetDirect\fP ()"
.br
.ti -1c
.RI "\fBElement\fP * \fBgetAnchor\fP ()"
.br
.ti -1c
.RI "bool \fBgetStart\fP ()"
.br
.ti -1c
.RI "int \fBgetTick\fP ()"
.br
.ti -1c
.RI "void \fBsetDirect\fP (\fBElement\fP *d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 774 of file exportxml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
