.TH "Ms::DownloadUtils" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DownloadUtils
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdownload\fP ()"
.br
.ti -1c
.RI "void \fBdownloadFinished\fP (QNetworkReply *data)"
.br
.ti -1c
.RI "void \fBdownloadProgress\fP (qint64 recieved, qint64 total)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdone\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDownloadUtils\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetTarget\fP (const QString &t)"
.br
.ti -1c
.RI "void \fBsetLocalFile\fP (const QString &t)"
.br
.ti -1c
.RI "bool \fBsaveFile\fP ()"
.br
.ti -1c
.RI "QByteArray \fBreturnData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file downloadUtils\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
