.TH "Ms::DragTransitionExampleView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DragTransitionExampleView
.SH SYNOPSIS
.br
.PP
.PP
Inherits QEventTransition\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragTransitionExampleView\fP (\fBExampleView\fP *c)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBonTransition\fP (QEvent *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file exampleview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
