.TH "Ms::DrumInstrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DrumInstrument
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrumInstrument\fP (const char *s, NoteHead::Group nh, int l, \fBDirection\fP d, int v=0, char sc=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "NoteHead::Group \fBnotehead\fP"
.br
.RI "notehead symbol set "
.ti -1c
.RI "int \fBline\fP"
.br
.RI "place notehead onto this line "
.ti -1c
.RI "\fBDirection\fP \fBstemDirection\fP"
.br
.ti -1c
.RI "int \fBvoice\fP"
.br
.ti -1c
.RI "char \fBshortcut\fP"
.br
.RI "accelerator key (CDEFGAB) "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file drumset\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
