.TH "Ms::Drumset" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Drumset
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP (int pitch) const"
.br
.ti -1c
.RI "NoteHead::Group \fBnoteHead\fP (int pitch) const"
.br
.ti -1c
.RI "int \fBline\fP (int pitch) const"
.br
.ti -1c
.RI "int \fBvoice\fP (int pitch) const"
.br
.ti -1c
.RI "\fBDirection\fP \fBstemDirection\fP (int pitch) const"
.br
.ti -1c
.RI "const QString & \fBname\fP (int pitch) const"
.br
.ti -1c
.RI "int \fBshortcut\fP (int pitch) const"
.br
.ti -1c
.RI "void \fBsave\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBload\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &, int)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "int \fBnextPitch\fP (int) const"
.br
.ti -1c
.RI "int \fBprevPitch\fP (int) const"
.br
.ti -1c
.RI "\fBDrumInstrument\fP & \fBdrum\fP (int i)"
.br
.ti -1c
.RI "const \fBDrumInstrument\fP & \fBdrum\fP (int i) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file drumset\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
