.TH "Ms::Dyn" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Dyn
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvelocity\fP"
.br
.RI "associated midi velocity (0-127, -1 = none) "
.ti -1c
.RI "bool \fBaccent\fP"
.br
.RI "if true add velocity to current chord velocity "
.ti -1c
.RI "const char * \fBtag\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file dynamic\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
