.TH "Ms::DrumTools" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DrumTools
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrumTools\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetDrumset\fP (\fBScore\fP *, \fBStaff\fP *, const \fBDrumset\fP *)"
.br
.ti -1c
.RI "void \fBupdateDrumset\fP (const \fBDrumset\fP *ds)"
.br
.ti -1c
.RI "int \fBselectedDrumNote\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file drumtools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
