.TH "Ms::DrumrollEditor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::DrumrollEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBchangeSelection\fP (SelState)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrumrollEditor\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetStaff\fP (\fBStaff\fP *staff)"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "void \fBheartBeat\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file drumroll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
