.TH "Ms::Debugger" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Debugger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::AbstractDialog\fP, and \fBUi::DebuggerBase\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetElement\fP (\fBElement\fP *)"
.br
.ti -1c
.RI "void \fBreloadClicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugger\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.ti -1c
.RI "void \fBupdateList\fP (\fBScore\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBretranslate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBScore\fP * \fBcs\fP"
.br
.ti -1c
.RI "\fBElement\fP * \fBcurElement\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 81 of file debugger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
