.TH "Ms::ElementEditData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ElementEditData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::BarLineEditData\fP, \fBMs::ImageEditData\fP, \fBMs::NoteEditData\fP, and \fBMs::TextEditData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpushProperty\fP (P_ID pid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBe\fP"
.br
.ti -1c
.RI "QList< \fBPropertyData\fP > \fBpropertyData\fP"
.br
.ti -1c
.RI "QPointF \fBstartDragPosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 473 of file element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
