.TH "Ms::ExcerptItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ExcerptItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QListWidgetItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExcerptItem\fP (\fBExcerpt\fP *, QListWidget *parent=0)"
.br
.ti -1c
.RI "\fBExcerpt\fP * \fBexcerpt\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file excerptsdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
