.TH "Ms::EditStringData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EditStringData
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::EditStringDataBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditStringData\fP (QWidget *parent, QList< \fBinstrString\fP > *strings, int *frets)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QString \fBmidiCodeToStr\fP (int midiCode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file editstringdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
