.TH "Ms::EditStyle" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EditStyle
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::EditStyleBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditStyle\fP (\fBScore\fP *, QWidget *)"
.br
.ti -1c
.RI "void \fBsetPage\fP (int no)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBPAGE_NOTE\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file editstyle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
