.TH "Ms::ExportMidi" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ExportMidi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportMidi\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "bool \fBwrite\fP (const QString &name, bool midiExpandRepeats)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMidiFile\fP \fBmf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file exportmidi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
