.TH "Ms::EventMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EventMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits multimap< int, NPlayEvent >\&.
.SH "Detailed Description"
.PP 
Definition at line 314 of file event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
