.TH "Ms::EffectGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EffectGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBMs::CompressorGui\fP, \fBMs::NoEffectGui\fP, and \fBMs::ZitaEffectGui\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP (const QString &name, qreal)"
.br
.ti -1c
.RI "void \fBvalueChanged\fP (qreal, int)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectGui\fP (\fBEffect\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "\fBEffect\fP * \fBeffect\fP () const"
.br
.ti -1c
.RI "virtual void \fBupdateValues\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file effectgui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
