.TH "Ms::Event" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Event
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::PlayEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP (const \fBEvent\fP &)"
.br
.ti -1c
.RI "\fBEvent\fP (int t)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBEvent\fP &) const"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "int \fBnoquantOntime\fP () const"
.br
.ti -1c
.RI "void \fBsetNoquantOntime\fP (int v)"
.br
.ti -1c
.RI "int \fBnoquantDuration\fP () const"
.br
.ti -1c
.RI "void \fBsetNoquantDuration\fP (int v)"
.br
.ti -1c
.RI "int \fBontime\fP () const"
.br
.ti -1c
.RI "void \fBsetOntime\fP (int v)"
.br
.ti -1c
.RI "int \fBduration\fP () const"
.br
.ti -1c
.RI "void \fBsetDuration\fP (int v)"
.br
.ti -1c
.RI "int \fBvoice\fP () const"
.br
.ti -1c
.RI "void \fBsetVoice\fP (int val)"
.br
.ti -1c
.RI "int \fBofftime\fP () const"
.br
.ti -1c
.RI "QList< \fBEvent\fP > & \fBnotes\fP ()"
.br
.ti -1c
.RI "const uchar * \fBedata\fP () const"
.br
.ti -1c
.RI "void \fBsetEData\fP (uchar *d)"
.br
.ti -1c
.RI "int \fBlen\fP () const"
.br
.ti -1c
.RI "void \fBsetLen\fP (int l)"
.br
.ti -1c
.RI "int \fBmetaType\fP () const"
.br
.ti -1c
.RI "void \fBsetMetaType\fP (int v)"
.br
.ti -1c
.RI "int \fBtpc\fP () const"
.br
.ti -1c
.RI "void \fBsetTpc\fP (int v)"
.br
.ti -1c
.RI "const \fBNote\fP * \fBnote\fP () const"
.br
.ti -1c
.RI "void \fBsetNote\fP (const \fBNote\fP *v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 253 of file event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
