.TH "Ms::EditPitch" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EditPitch
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::EditPitchBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditPitch\fP (QWidget *parent)"
.br
.ti -1c
.RI "\fBEditPitch\fP (QWidget *parent, int midiCode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file editpitch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
