.TH "Ms::ElementMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ElementMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits QHash< Element *, Element *>\&.
.PP
Inherited by \fBMs::TieMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBfindNew\fP (\fBElement\fP *o) const"
.br
.ti -1c
.RI "void \fBadd\fP (\fBElement\fP *o, \fBElement\fP *n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file elementmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
