.TH "Ms::ExportMusicXml" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ExportMusicXml
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportMusicXml\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "void \fBwrite\fP (QIODevice *dev)"
.br
.ti -1c
.RI "void \fBcredits\fP (\fBXmlWriter\fP &xml)"
.br
.ti -1c
.RI "void \fBmoveToTick\fP (int t)"
.br
.ti -1c
.RI "void \fBwords\fP (\fBText\fP const *const text, int staff)"
.br
.ti -1c
.RI "void \fBrehearsal\fP (\fBRehearsalMark\fP const *const rmk, int staff)"
.br
.ti -1c
.RI "void \fBhairpin\fP (\fBHairpin\fP const *const hp, int staff, int tick)"
.br
.ti -1c
.RI "void \fBottava\fP (\fBOttava\fP const *const ot, int staff, int tick)"
.br
.ti -1c
.RI "void \fBpedal\fP (\fBPedal\fP const *const pd, int staff, int tick)"
.br
.ti -1c
.RI "void \fBtextLine\fP (\fBTextLine\fP const *const tl, int staff, int tick)"
.br
.ti -1c
.RI "void \fBdynamic\fP (\fBDynamic\fP const *const dyn, int staff)"
.br
.ti -1c
.RI "void \fBsymbol\fP (\fBSymbol\fP const *const sym, int staff)"
.br
.ti -1c
.RI "void \fBtempoText\fP (\fBTempoText\fP const *const text, int staff)"
.br
.ti -1c
.RI "void \fBharmony\fP (\fBHarmony\fP const *const, \fBFretDiagram\fP const *const fd, int offset=0)"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 268 of file exportxml\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ms::ExportMusicXml::write (QIODevice * dev)"
Write the score to \fIdev\fP in MusicXML format\&. 
.PP
Definition at line 5002 of file exportxml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
