.TH "Ms::ElementList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ElementList
.SH SYNOPSIS
.br
.PP
.PP
Inherits vector< Element *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBremove\fP (\fBElement\fP *)"
.br
.RI "Remove \fIel\fP from the list\&. Return true on success\&. "
.ti -1c
.RI "void \fBreplace\fP (\fBElement\fP *old, \fBElement\fP *n)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &, const char *name) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 497 of file element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
