.TH "Ms::Excerpt" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Excerpt
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExcerpt\fP (\fBMasterScore\fP *s=0)"
.br
.ti -1c
.RI "QList< \fBPart\fP * > & \fBparts\fP ()"
.br
.ti -1c
.RI "void \fBsetParts\fP (const QList< \fBPart\fP *> &p)"
.br
.ti -1c
.RI "QMultiMap< int, int > & \fBtracks\fP ()"
.br
.ti -1c
.RI "void \fBsetTracks\fP (const QMultiMap< int, int > &t)"
.br
.ti -1c
.RI "\fBMasterScore\fP * \fBoscore\fP () const"
.br
.ti -1c
.RI "\fBScore\fP * \fBpartScore\fP () const"
.br
.ti -1c
.RI "void \fBsetPartScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBExcerpt\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBExcerpt\fP &) const"
.br
.ti -1c
.RI "QString \fBtitle\fP () const"
.br
.ti -1c
.RI "void \fBsetTitle\fP (const QString &s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QList< \fBExcerpt\fP * > \fBcreateAllExcerpt\fP (\fBMasterScore\fP *score)"
.br
.ti -1c
.RI "static QString \fBcreateName\fP (const QString &partName, QList< \fBExcerpt\fP *> &)"
.br
.ti -1c
.RI "static void \fBcreateExcerpt\fP (\fBExcerpt\fP *)"
.br
.ti -1c
.RI "static void \fBcloneStaves\fP (\fBScore\fP *oscore, \fBScore\fP *score, const QList< int > &map, QMultiMap< int, int > &allTracks)"
.br
.ti -1c
.RI "static void \fBcloneStaff\fP (\fBStaff\fP *ostaff, \fBStaff\fP *nstaff)"
.br
.ti -1c
.RI "static void \fBcloneStaff2\fP (\fBStaff\fP *ostaff, \fBStaff\fP *nstaff, int stick, int etick)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMs::Score\fP \fBpartScore\fP"
.br
.ti -1c
.RI "QString \fBtitle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file excerpt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
