.TH "Ms::ElementLayout" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ElementLayout
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::BSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementLayout\fP (Align a, const QPointF &o, \fBOffsetType\fP ot)"
.br
.ti -1c
.RI "Align \fBalign\fP () const"
.br
.ti -1c
.RI "\fBOffsetType\fP \fBoffsetType\fP () const"
.br
.ti -1c
.RI "qreal \fBxOffset\fP () const"
.br
.ti -1c
.RI "qreal \fByOffset\fP () const"
.br
.ti -1c
.RI "const QPointF & \fBoffset\fP () const"
.br
.ti -1c
.RI "QPointF \fBoffset\fP (qreal) const"
.br
.ti -1c
.RI "void \fBsetAlign\fP (Align val)"
.br
.ti -1c
.RI "void \fBsetXoff\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetYoff\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetOffsetType\fP (\fBOffsetType\fP val)"
.br
.ti -1c
.RI "void \fBlayout\fP (\fBElement\fP *) const"
.br
.ti -1c
.RI "void \fBwriteProperties\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "void \fBwriteProperties\fP (\fBXmlWriter\fP &xml, const \fBElementLayout\fP &) const"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBrestyle\fP (const \fBElementLayout\fP &ol, const \fBElementLayout\fP &nl)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Align \fB_align\fP"
.br
.ti -1c
.RI "QPointF \fB_offset\fP"
.br
.ti -1c
.RI "\fBOffsetType\fP \fB_offsetType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file elementlayout\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
