.TH "Ms::EditDrumset" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EditDrumset
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::EditDrumsetBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditDrumset\fP (const \fBDrumset\fP *ds, QWidget *parent=0)"
.br
.ti -1c
.RI "const \fBDrumset\fP * \fBdrumset\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file editdrumset\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
