.TH "Ms::EditData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::EditData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBclearData\fP ()"
.br
.ti -1c
.RI "\fBElementEditData\fP * \fBgetData\fP (const \fBElement\fP *) const"
.br
.ti -1c
.RI "void \fBaddData\fP (\fBElementEditData\fP *)"
.br
.ti -1c
.RI "bool \fBcontrol\fP () const"
.br
.ti -1c
.RI "bool \fBshift\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMuseScoreView\fP * \fBview\fP { 0 }"
.br
.ti -1c
.RI "QVector< QRectF > \fBgrip\fP"
.br
.ti -1c
.RI "int \fBgrips\fP { 0 }"
.br
.ti -1c
.RI "Grip \fBcurGrip\fP { Grip(0) }"
.br
.ti -1c
.RI "QPointF \fBpos\fP"
.br
.ti -1c
.RI "QPointF \fBstartMove\fP"
.br
.ti -1c
.RI "QPointF \fBlastPos\fP"
.br
.ti -1c
.RI "QPointF \fBdelta\fP"
.br
.ti -1c
.RI "bool \fBhRaster\fP { false }"
.br
.ti -1c
.RI "bool \fBvRaster\fP { false }"
.br
.ti -1c
.RI "int \fBkey\fP { 0 }"
.br
.ti -1c
.RI "Qt::KeyboardModifiers \fBmodifiers\fP { 0 }"
.br
.ti -1c
.RI "QString \fBs\fP"
.br
.ti -1c
.RI "Qt::MouseButtons \fBbuttons\fP { Qt::NoButton }"
.br
.ti -1c
.RI "QPointF \fBdragOffset\fP"
.br
.ti -1c
.RI "\fBElement\fP * \fBelement\fP { 0 }"
.br
.ti -1c
.RI "\fBFraction\fP \fBduration\fP { \fBFraction\fP(1,4) }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
