.TH "Ms::FifoBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::FifoBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::SeqMsgFifo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "int \fBcount\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBisFull\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP ()"
.br
.ti -1c
.RI "void \fBpop\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBridx\fP"
.br
.ti -1c
.RI "int \fBwidx\fP"
.br
.ti -1c
.RI "std::atomic< int > \fBcounter\fP"
.br
.ti -1c
.RI "int \fBmaxCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file fifo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
