.TH "Ms::FSymbol" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::FSymbol \- \fBSymbol\fP constructed from a font glyph\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <symbol\&.h>\fP
.PP
Inherits \fBMs::BSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFSymbol\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBFSymbol\fP (const \fBFSymbol\fP &)"
.br
.ti -1c
.RI "virtual \fBFSymbol\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "virtual qreal \fBbaseLine\fP () const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "QFont \fBfont\fP () const"
.br
.ti -1c
.RI "int \fBcode\fP () const"
.br
.ti -1c
.RI "void \fBsetFont\fP (const QFont &f)"
.br
.ti -1c
.RI "void \fBsetCode\fP (int val)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSymbol\fP constructed from a font glyph\&. 
.PP
Definition at line 67 of file symbol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
