.TH "Ms::Fraction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Fraction
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::TimeSigFrac\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBFraction\fP (int z=0, int n=1)"
.br
.ti -1c
.RI "int \fBnumerator\fP () const"
.br
.ti -1c
.RI "int \fBdenominator\fP () const"
.br
.ti -1c
.RI "int & \fBrnumerator\fP ()"
.br
.ti -1c
.RI "int & \fBrdenominator\fP ()"
.br
.ti -1c
.RI "void \fBsetNumerator\fP (int v)"
.br
.ti -1c
.RI "void \fBsetDenominator\fP (int v)"
.br
.ti -1c
.RI "void \fBset\fP (int z, int n)"
.br
.ti -1c
.RI "bool \fBisZero\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "void \fBreduce\fP ()"
.br
.ti -1c
.RI "\fBFraction\fP \fBreduced\fP () const"
.br
.ti -1c
.RI "\fBFraction\fP \fBabsValue\fP () const"
.br
.ti -1c
.RI "bool \fBidentical\fP (const \fBFraction\fP &v) const"
.br
.ti -1c
.RI "int \fBticks\fP () const"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator+=\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator\-=\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator*=\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator*=\fP (int)"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator/=\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "\fBFraction\fP & \fBoperator/=\fP (int)"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator+\fP (const \fBFraction\fP &v) const"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator\-\fP (const \fBFraction\fP &v) const"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator*\fP (const \fBFraction\fP &v) const"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator*\fP (int v) const"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator/\fP (const \fBFraction\fP &v) const"
.br
.ti -1c
.RI "\fBFraction\fP \fBoperator/\fP (int v) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBFraction\fP &) const"
.br
.ti -1c
.RI "QString \fBprint\fP () const"
.br
.ti -1c
.RI "\fBoperator QVariant\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFraction\fP \fBfromTicks\fP (int v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file fraction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
