.TH "Ms::FretDiagramProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::FretDiagramProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::FretDiagramProperties\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFretDiagramProperties\fP (\fBFretDiagram\fP *, QWidget *parent=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file fretproperties\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
