.TH "Ms::GuitarPro1" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::GuitarPro1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::GuitarPro\fP\&.
.PP
Inherited by \fBMs::GuitarPro2\fP, and \fBMs::GuitarPro3\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuitarPro1\fP (\fBScore\fP *s, int v)"
.br
.ti -1c
.RI "virtual void \fBread\fP (QFile *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadNote\fP (int string, \fBNote\fP *note)"
.br
.ti -1c
.RI "virtual int \fBreadBeatEffects\fP (int track, \fBSegment\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 255 of file importgtp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
