.TH "Ms::GripItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::GripItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGraphicsRectItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGripItem\fP (int gripType, \fBChordView\fP *)"
.br
.ti -1c
.RI "virtual int \fBtype\fP () const"
.br
.ti -1c
.RI "\fBChordItem\fP * \fBevent\fP () const"
.br
.ti -1c
.RI "void \fBsetEvent\fP (\fBChordItem\fP *e)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QGraphicsSceneMouseEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file chordview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
