.TH "Ms::GpBar" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::GpBar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFraction\fP \fBtimesig\fP"
.br
.ti -1c
.RI "bool \fBfreeTime\fP"
.br
.ti -1c
.RI "int \fBkeysig\fP"
.br
.ti -1c
.RI "QString \fBmarker\fP"
.br
.ti -1c
.RI "BarLineType \fBbarLine\fP"
.br
.ti -1c
.RI "Repeat \fBrepeatFlags\fP"
.br
.ti -1c
.RI "int \fBrepeats\fP"
.br
.ti -1c
.RI "\fBGPVolta\fP \fBvolta\fP"
.br
.ti -1c
.RI "QString \fBdirection\fP"
.br
.ti -1c
.RI "QString \fBdirectionStyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file importgtp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
