.TH "Ms::GlyphKey" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::GlyphKey
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlyphKey\fP (\fBFT_Face\fP _f, SymId _id, float mx, float my, float s, QColor c)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBGlyphKey\fP &) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "SymId \fBid\fP"
.br
.ti -1c
.RI "qreal \fBmagX\fP"
.br
.ti -1c
.RI "qreal \fBmagY\fP"
.br
.ti -1c
.RI "qreal \fBworldScale\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2740 of file sym\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
