.TH "Ms::GlissandoSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::GlissandoSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::LineSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlissandoSegment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBGlissando\fP * \fBglissando\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual \fBGlissandoSegment\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 31 of file glissando\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
