.TH "Ms::Hairpin" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Hairpin
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::TextLineBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHairpin\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBHairpin\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "HairpinType \fBhairpinType\fP () const"
.br
.ti -1c
.RI "void \fBsetHairpinType\fP (HairpinType val)"
.br
.ti -1c
.RI "void \fBundoSetHairpinType\fP (HairpinType)"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual \fBLineSegment\fP * \fBcreateLineSegment\fP () override"
.br
.ti -1c
.RI "bool \fBhairpinCircledTip\fP () const"
.br
.ti -1c
.RI "void \fBsetHairpinCircledTip\fP (bool val)"
.br
.ti -1c
.RI "int \fBveloChange\fP () const"
.br
.ti -1c
.RI "void \fBsetVeloChange\fP (int v)"
.br
.ti -1c
.RI "void \fBundoSetVeloChange\fP (int v)"
.br
.ti -1c
.RI "Dynamic::Range \fBdynRange\fP () const"
.br
.ti -1c
.RI "void \fBsetDynRange\fP (Dynamic::Range t)"
.br
.ti -1c
.RI "void \fBundoSetDynRange\fP (Dynamic::Range t)"
.br
.ti -1c
.RI "\fBSpatium\fP \fBhairpinHeight\fP () const"
.br
.ti -1c
.RI "void \fBsetHairpinHeight\fP (\fBSpatium\fP val)"
.br
.ti -1c
.RI "\fBSpatium\fP \fBhairpinContHeight\fP () const"
.br
.ti -1c
.RI "void \fBsetHairpinContHeight\fP (\fBSpatium\fP val)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual PropertyFlags \fBpropertyFlags\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual void \fBresetProperty\fP (P_ID id) override"
.br
.ti -1c
.RI "virtual StyleIdx \fBgetPropertyStyle\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual void \fBsetYoff\fP (qreal) override"
.br
.ti -1c
.RI "virtual void \fBstyleChanged\fP () override"
.br
.ti -1c
.RI "virtual void \fBreset\fP () override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Ms::Dynamic::Range \fBdynRange\fP"
.br
.ti -1c
.RI "Ms::HairpinType \fBhairpinType\fP"
.br
.ti -1c
.RI "int \fBveloChange\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 78 of file hairpin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
