.TH "Ms::HBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::HBox \- horizontal frame  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <box\&.h>\fP
.PP
Inherits \fBMs::Box\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHBox\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "virtual \fBHBox\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QRectF \fBdrag\fP (\fBEditData\fP &) override"
.br
.RI "Return update Rect relative to canvas\&. "
.ti -1c
.RI "virtual void \fBendEditDrag\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "void \fBlayout2\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisMovable\fP () const override"
.br
.ti -1c
.RI "virtual void \fBcomputeMinWidth\fP ()"
.br
.ti -1c
.RI "bool \fBcreateSystemHeader\fP () const"
.br
.ti -1c
.RI "void \fBsetCreateSystemHeader\fP (bool val)"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
horizontal frame 
.PP
Definition at line 102 of file box\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
