.TH "Ms::HarmonyCanvas" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::HarmonyCanvas
.SH SYNOPSIS
.br
.PP
.PP
Inherits QFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHarmonyCanvas\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetChordDescription\fP (\fBChordDescription\fP *sd, \fBChordList\fP *cl)"
.br
.ti -1c
.RI "const QList< \fBTextSegment\fP * > & \fBgetTextList\fP () const"
.br
.ti -1c
.RI "void \fBupdateChordDescription\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file harmonycanvas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
