.TH "Ms::HDegree" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::HDegree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDegree\fP (int v, int a, HDegreeType t)"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.ti -1c
.RI "int \fBalter\fP () const"
.br
.ti -1c
.RI "HDegreeType \fBtype\fP () const"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
