.TH "Ms::Hook" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Hook
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Symbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHook\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "virtual \fBHook\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "void \fBsetHookType\fP (int v)"
.br
.ti -1c
.RI "int \fBhookType\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file hook\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
