.TH "Ms::HChord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::HChord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHChord\fP (int k)"
.br
.ti -1c
.RI "\fBHChord\fP (int a, int b, int c=\-1, int d=\-1, int e=\-1, int f=\-1, int g=\-1, int h=\-1, int i=\-1, int k=\-1, int l=\-1)"
.br
.ti -1c
.RI "\fBHChord\fP (const QString &)"
.br
.ti -1c
.RI "void \fBrotate\fP (int semiTones)"
.br
.ti -1c
.RI "bool \fBcontains\fP (int key) const"
.br
.ti -1c
.RI "\fBHChord\fP & \fBoperator+=\fP (int key)"
.br
.ti -1c
.RI "\fBHChord\fP & \fBoperator\-=\fP (int key)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBHChord\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBHChord\fP &o) const"
.br
.ti -1c
.RI "int \fBgetKeys\fP () const"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP (int tpc) const"
.br
.ti -1c
.RI "QString \fBvoicing\fP () const"
.br
.ti -1c
.RI "void \fBadd\fP (const QList< \fBHDegree\fP > &degreeList)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBkeys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
