.TH "Ms::InspectorFretDiagram" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InspectorFretDiagram
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InspectorElementBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorFretDiagram\fP (QWidget *parent)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file inspectorFret\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
