.TH "Ms::Interval" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Interval
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterval\fP (int a, int b)"
.br
.ti -1c
.RI "\fBInterval\fP (int _chromatic)"
.br
.ti -1c
.RI "void \fBflip\fP ()"
.br
.ti -1c
.RI "bool \fBisZero\fP () const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBInterval\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBInterval\fP &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "signed char \fBdiatonic\fP"
.br
.ti -1c
.RI "signed char \fBchromatic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file interval\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
