.TH "Ms::InspectorTextBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InspectorTextBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InspectorElementBase\fP\&.
.PP
Inherited by \fBMs::InspectorDynamic\fP, \fBMs::InspectorFingering\fP, \fBMs::InspectorIname\fP, \fBMs::InspectorJump\fP, \fBMs::InspectorLyric\fP, \fBMs::InspectorMarker\fP, \fBMs::InspectorStaffText\fP, \fBMs::InspectorTempoText\fP, and \fBMs::InspectorText\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorTextBase\fP (QWidget *parent)"
.br
.ti -1c
.RI "virtual void \fBsetElement\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBUi::InspectorText\fP \fBt\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file inspectorTextBase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
