.TH "Ms::InspectorBeam" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InspectorBeam
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InspectorElementBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorBeam\fP (QWidget *parent)"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBvalueChanged\fP (int idx) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetValue\fP (const \fBInspectorItem\fP &, QVariant val) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 27 of file inspectorBeam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
