.TH "Ms::Inspector" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Inspector
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspector\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBElement\fP * \fBelement\fP () const"
.br
.ti -1c
.RI "const QList< \fBElement\fP * > * \fBel\fP () const"
.br
.ti -1c
.RI "void \fBsetInspectorEdit\fP (bool val)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 329 of file inspector\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
