.TH "Ms::ImageStoreItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ImageStoreItem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageStoreItem\fP (const QString &p)"
.br
.ti -1c
.RI "void \fBdereference\fP (\fBImage\fP *)"
.br
.ti -1c
.RI "void \fBreference\fP (\fBImage\fP *)"
.br
.ti -1c
.RI "const QString & \fBpath\fP () const"
.br
.ti -1c
.RI "QByteArray & \fBbuffer\fP ()"
.br
.ti -1c
.RI "bool \fBloaded\fP () const"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &val)"
.br
.ti -1c
.RI "bool \fBisUsed\fP (\fBScore\fP *) const"
.br
.ti -1c
.RI "void \fBload\fP ()"
.br
.ti -1c
.RI "QString \fBhashName\fP () const"
.br
.ti -1c
.RI "const QByteArray & \fBhash\fP () const"
.br
.ti -1c
.RI "void \fBset\fP (const QByteArray &b, const QByteArray &h)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file imageStore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
