.TH "Ms::InsertItemBspTreeVisitor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InsertItemBspTreeVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BspTreeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvisit\fP (QList< \fBElement\fP *> *items)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file bsp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
