.TH "Ms::InspectorText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InspectorText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InspectorTextBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorText\fP (QWidget *parent)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 27 of file inspectorText\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
