.TH "Ms::InspectorElementBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InspectorElementBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InspectorBase\fP\&.
.PP
Inherited by \fBMs::InspectorAccidental\fP, \fBMs::InspectorAmbitus\fP, \fBMs::InspectorArpeggio\fP, \fBMs::InspectorArticulation\fP, \fBMs::InspectorBarLine\fP, \fBMs::InspectorBeam\fP, \fBMs::InspectorBend\fP, \fBMs::InspectorCaesura\fP, \fBMs::InspectorClef\fP, \fBMs::InspectorElement\fP, \fBMs::InspectorFretDiagram\fP, \fBMs::InspectorGlissando\fP, \fBMs::InspectorHairpin\fP, \fBMs::InspectorImage\fP, \fBMs::InspectorKeySig\fP, \fBMs::InspectorNote\fP, \fBMs::InspectorOttava\fP, \fBMs::InspectorRest\fP, \fBMs::InspectorSlurTie\fP, \fBMs::InspectorTextBase\fP, \fBMs::InspectorTextLine\fP, \fBMs::InspectorTimeSig\fP, \fBMs::InspectorTremoloBar\fP, \fBMs::InspectorTrill\fP, \fBMs::InspectorTuplet\fP, and \fBMs::InspectorVolta\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspectorElementBase\fP (QWidget *parent)"
.br
.ti -1c
.RI "virtual void \fBsetElement\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBUiInspectorElement\fP \fBe\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file inspectorElementBase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
