.TH "Ms::InstrumentName" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentName
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstrumentName\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "virtual \fBInstrumentName\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "int \fBlayoutPos\fP () const"
.br
.ti -1c
.RI "void \fBsetLayoutPos\fP (int val)"
.br
.ti -1c
.RI "QString \fBinstrumentNameTypeName\fP () const"
.br
.ti -1c
.RI "InstrumentNameType \fBinstrumentNameType\fP () const"
.br
.ti -1c
.RI "void \fBsetInstrumentNameType\fP (InstrumentNameType v)"
.br
.ti -1c
.RI "void \fBsetInstrumentNameType\fP (const QString &s)"
.br
.ti -1c
.RI "virtual bool \fBedit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBendEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file iname\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
