.TH "Ms::InstrumentTemplateListItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentTemplateListItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTreeWidgetItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstrumentTemplateListItem\fP (QString group, QTreeWidget *parent)"
.br
.ti -1c
.RI "\fBInstrumentTemplateListItem\fP (\fBInstrumentTemplate\fP *i, \fBInstrumentTemplateListItem\fP *parent)"
.br
.ti -1c
.RI "\fBInstrumentTemplateListItem\fP (\fBInstrumentTemplate\fP *i, QTreeWidget *parent)"
.br
.ti -1c
.RI "\fBInstrumentTemplate\fP * \fBinstrumentTemplate\fP () const"
.br
.ti -1c
.RI "virtual QString \fBtext\fP (int col) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file instrwidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
