.TH "Ms::InstrumentGenre" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentGenre
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "void \fBwrite1\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file instrtemplate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
