.TH "Ms::InsertRemoveMeasures" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InsertRemoveMeasures
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.PP
Inherited by \fBMs::InsertMeasures\fP, and \fBMs::RemoveMeasures\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInsertRemoveMeasures\fP (\fBMeasureBase\fP *_fm, \fBMeasureBase\fP *_lm)"
.br
.ti -1c
.RI "virtual void \fBundo\fP (\fBEditData\fP *) override=0"
.br
.ti -1c
.RI "virtual void \fBredo\fP (\fBEditData\fP *) override=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBremoveMeasures\fP ()"
.br
.ti -1c
.RI "void \fBinsertMeasures\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 689 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
