.TH "Ms::Icon" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Icon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIcon\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBIcon\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "IconType \fBiconType\fP () const"
.br
.ti -1c
.RI "void \fBsetIconType\fP (IconType val)"
.br
.ti -1c
.RI "void \fBsetAction\fP (const QByteArray &a, const QIcon &i)"
.br
.ti -1c
.RI "const QByteArray & \fBaction\fP () const"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const"
.br
.ti -1c
.RI "void \fBsetExtent\fP (int v)"
.br
.ti -1c
.RI "int \fBextent\fP () const"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file icon\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
