.TH "Ms::InstrumentList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentList
.SH SYNOPSIS
.br
.PP
.PP
Inherits map< const int, Instrument *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBInstrument\fP * \fBinstrument\fP (int tick) const"
.br
.ti -1c
.RI "\fBInstrument\fP * \fBinstrument\fP (int tick)"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (\fBInstrument\fP *, int tick)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 226 of file instrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
