.TH "Ms::InstrumentGroup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "bool \fBextended\fP"
.br
.ti -1c
.RI "QList< \fBInstrumentTemplate\fP * > \fBinstrumentTemplates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file instrtemplate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
