.TH "Ms::InstrumentChange" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentChange
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstrumentChange\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBInstrumentChange\fP (const \fBInstrument\fP &, \fBScore\fP *)"
.br
.ti -1c
.RI "\fBInstrumentChange\fP (const \fBInstrumentChange\fP &)"
.br
.ti -1c
.RI "virtual \fBInstrumentChange\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "\fBInstrument\fP * \fBinstrument\fP () const"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (\fBInstrument\fP *i)"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (\fBInstrument\fP &&i)"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (const \fBInstrument\fP &i)"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file instrchange\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
