.TH "Ms::InstrumentsWidget" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::InstrumentsWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::InstrumentsWidget\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBbuildTemplateList\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcompleteChanged\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstrumentsWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBgenPartList\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBcreateInstruments\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "QTreeWidget * \fBgetPartiturList\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 119 of file instrwidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
