.TH "Ms::JackAudio" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::JackAudio
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Driver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJackAudio\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP (bool hot=false)"
.br
.ti -1c
.RI "virtual bool \fBstart\fP (bool hotPlug=false)"
.br
.ti -1c
.RI "virtual bool \fBstop\fP ()"
.br
.ti -1c
.RI "int \fBframePos\fP () const"
.br
.ti -1c
.RI "void \fBconnect\fP (void *, void *)"
.br
.ti -1c
.RI "void \fBconnect\fP (const char *src, const char *dst)"
.br
.ti -1c
.RI "void \fBdisconnect\fP (void *src, void *dst)"
.br
.ti -1c
.RI "virtual bool \fBisRealtime\fP () const"
.br
.ti -1c
.RI "virtual void \fBstartTransport\fP ()"
.br
.ti -1c
.RI "virtual void \fBstopTransport\fP ()"
.br
.ti -1c
.RI "virtual Transport \fBgetState\fP () override"
.br
.ti -1c
.RI "virtual void \fBseekTransport\fP (int)"
.br
.ti -1c
.RI "virtual int \fBsampleRate\fP () const"
.br
.ti -1c
.RI "virtual void \fBputEvent\fP (const \fBNPlayEvent\fP &, unsigned framePos)"
.br
.ti -1c
.RI "virtual void \fBmidiRead\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterPort\fP (const QString &name, bool input, bool midi)"
.br
.ti -1c
.RI "virtual void \fBunregisterPort\fP (jack_port_t *)"
.br
.ti -1c
.RI "virtual void \fBhandleTimeSigTempoChanged\fP ()"
.br
.ti -1c
.RI "virtual void \fBcheckTransportSeek\fP (int, int, bool)"
.br
.ti -1c
.RI "virtual int \fBbufferSize\fP ()"
.br
.ti -1c
.RI "void \fBsetBufferSize\fP (int nframes)"
.br
.ti -1c
.RI "void \fBupdateOutPortCount\fP (int)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 38 of file jackaudio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
