.TH "Ms::JSHighlighter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::JSHighlighter
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSyntaxHighlighter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSHighlighter\fP (QTextDocument *parent=0)"
.br
.ti -1c
.RI "void \fBsetColor\fP (QmlEdit::ColorComponent component, const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBmark\fP (const QString &str, Qt::CaseSensitivity caseSensitivity)"
.br
.ti -1c
.RI "QStringList \fBkeywords\fP () const"
.br
.ti -1c
.RI "void \fBsetKeywords\fP (const QStringList &keywords)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBhighlightBlock\fP (const QString &text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 103 of file qmledit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
