.TH "Ms::KeySigEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::KeySigEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeySigEvent\fP (const \fBKeySigEvent\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBKeySigEvent\fP &e) const"
.br
.ti -1c
.RI "void \fBsetKey\fP (Key v)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.ti -1c
.RI "Key \fBkey\fP () const"
.br
.ti -1c
.RI "KeyMode \fBmode\fP () const"
.br
.ti -1c
.RI "void \fBsetMode\fP (KeyMode m)"
.br
.ti -1c
.RI "bool \fBcustom\fP () const"
.br
.ti -1c
.RI "void \fBsetCustom\fP (bool val)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBisAtonal\fP () const"
.br
.ti -1c
.RI "void \fBinitFromSubtype\fP (int)"
.br
.ti -1c
.RI "QList< \fBKeySym\fP > & \fBkeySymbols\fP ()"
.br
.ti -1c
.RI "const QList< \fBKeySym\fP > & \fBkeySymbols\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
