.TH "Ms::LoginManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LoginManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBtryLogin\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBloginError\fP (const QString &error)"
.br
.ti -1c
.RI "void \fBloginSuccess\fP ()"
.br
.ti -1c
.RI "void \fBgetUserError\fP (const QString &error)"
.br
.ti -1c
.RI "void \fBgetUserSuccess\fP ()"
.br
.ti -1c
.RI "void \fBgetScoreError\fP (const QString &error)"
.br
.ti -1c
.RI "void \fBgetScoreSuccess\fP (const QString &title, const QString &description, bool priv, const QString &license, const QString &tags, const QString &url)"
.br
.ti -1c
.RI "void \fBuploadError\fP (const QString &error)"
.br
.ti -1c
.RI "void \fBuploadSuccess\fP (const QString &url, const QString &nid, const QString &vid)"
.br
.ti -1c
.RI "void \fBtryLoginSuccess\fP ()"
.br
.ti -1c
.RI "void \fBdisplaySuccess\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginManager\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBlogin\fP (QString login, QString password)"
.br
.ti -1c
.RI "void \fBupload\fP (const QString &path, int nid, const QString &title, const QString &description, const QString &priv, const QString &license, const QString &tags, const QString &changes)"
.br
.ti -1c
.RI "bool \fBhasAccessToken\fP ()"
.br
.ti -1c
.RI "void \fBgetUser\fP ()"
.br
.ti -1c
.RI "void \fBgetScore\fP (int nid)"
.br
.ti -1c
.RI "void \fBgetMediaUrl\fP (const QString &nid, const QString &vid, const QString &format)"
.br
.ti -1c
.RI "bool \fBsave\fP ()"
.br
.ti -1c
.RI "bool \fBload\fP ()"
.br
.ti -1c
.RI "bool \fBlogout\fP ()"
.br
.ti -1c
.RI "QString \fBuserName\fP ()"
.br
.ti -1c
.RI "int \fBuid\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file loginmanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
