.TH "Ms::LayoutContext" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LayoutContext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlayout\fP ()"
.br
.ti -1c
.RI "int \fBadjustMeasureNo\fP (\fBMeasureBase\fP *)"
.br
.ti -1c
.RI "void \fBgetEmptyPage\fP ()"
.br
.ti -1c
.RI "void \fBcollectPage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBScore\fP * \fBscore\fP { 0 }"
.br
.ti -1c
.RI "bool \fBstartWithLongNames\fP { true }"
.br
.ti -1c
.RI "bool \fBfirstSystem\fP { true }"
.br
.ti -1c
.RI "\fBPage\fP * \fBpage\fP { 0 }"
.br
.ti -1c
.RI "int \fBcurPage\fP { 0 }"
.br
.ti -1c
.RI "int \fBtick\fP { 0 }"
.br
.ti -1c
.RI "\fBFraction\fP \fBsig\fP"
.br
.ti -1c
.RI "QList< \fBSystem\fP * > \fBsystemList\fP"
.br
.ti -1c
.RI "\fBSystem\fP * \fBprevSystem\fP { 0 }"
.br
.ti -1c
.RI "\fBSystem\fP * \fBcurSystem\fP { 0 }"
.br
.ti -1c
.RI "\fBMeasureBase\fP * \fBsystemOldMeasure\fP"
.br
.ti -1c
.RI "bool \fBrangeDone\fP { false }"
.br
.ti -1c
.RI "\fBMeasureBase\fP * \fBprevMeasure\fP { 0 }"
.br
.ti -1c
.RI "\fBMeasureBase\fP * \fBcurMeasure\fP { 0 }"
.br
.ti -1c
.RI "\fBMeasureBase\fP * \fBnextMeasure\fP { 0 }"
.br
.ti -1c
.RI "int \fBmeasureNo\fP { 0 }"
.br
.ti -1c
.RI "int \fBendTick\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file layout\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
