.TH "Ms::LineObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LineObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicDrawObj\fP\&.
.PP
Inherited by \fBMs::BracketObj\fP, \fBMs::RectEllipseObj\fP, \fBMs::WavyLineObj\fP, and \fBMs::WedgeObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLineObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "\fBLineObj\fP (CapellaType t, \fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QPointF \fBpt1\fP"
.br
.ti -1c
.RI "QPointF \fBpt2\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "char \fBlineWidth\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 313 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
