.TH "Ms::LayoutBreak" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LayoutBreak \- symbols for line break, page break etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <layoutbreak\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBPAGE\fP, \fBLINE\fP, \fBSECTION\fP, \fBNOBREAK\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayoutBreak\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "\fBLayoutBreak\fP (const \fBLayoutBreak\fP &)"
.br
.ti -1c
.RI "virtual \fBLayoutBreak\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual bool \fBsystemFlag\fP () const override"
.br
.ti -1c
.RI "void \fBsetLayoutBreakType\fP (Type)"
.br
.ti -1c
.RI "Type \fBlayoutBreakType\fP () const"
.br
.ti -1c
.RI "void \fBundoSetLayoutBreakType\fP (Type)"
.br
.ti -1c
.RI "virtual bool \fBacceptDrop\fP (\fBEditData\fP &) const override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBdrop\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "\fBMeasure\fP * \fBmeasure\fP () const"
.br
.ti -1c
.RI "qreal \fBpause\fP () const"
.br
.ti -1c
.RI "void \fBsetPause\fP (qreal v)"
.br
.ti -1c
.RI "bool \fBstartWithLongNames\fP () const"
.br
.ti -1c
.RI "void \fBsetStartWithLongNames\fP (bool v)"
.br
.ti -1c
.RI "bool \fBstartWithMeasureOne\fP () const"
.br
.ti -1c
.RI "void \fBsetStartWithMeasureOne\fP (bool v)"
.br
.ti -1c
.RI "bool \fBisPageBreak\fP () const"
.br
.ti -1c
.RI "bool \fBisLineBreak\fP () const"
.br
.ti -1c
.RI "bool \fBisSectionBreak\fP () const"
.br
.ti -1c
.RI "bool \fBisNoBreak\fP () const"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Ms::LayoutBreak::Type \fBlayoutBreakType\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
symbols for line break, page break etc\&. 
.PP
Definition at line 29 of file layoutbreak\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Ms::LayoutBreak::acceptDrop (\fBEditData\fP &) const\fC [override]\fP, \fC [virtual]\fP"
Return true if this element accepts a drop at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&.
.PP
Reimplemented by elements that accept drops\&. Used to change cursor shape while dragging to indicate drop targets\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 213 of file layoutbreak\&.cpp\&.
.SS "\fBElement\fP * Ms::LayoutBreak::drop (\fBEditData\fP &)\fC [override]\fP, \fC [virtual]\fP"
Handle a dropped element at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&. Returns dropped element if any\&. The ownership of element in DropData is transfered to the called element (if not used, element has to be deleted)\&. The returned element will be selected if not in note edit mode\&.
.PP
Reimplemented by elements that accept drops\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 223 of file layoutbreak\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
