.TH "Ms::Line" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Line
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.PP
Inherited by \fBMs::LedgerLine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLine\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBLine\fP (\fBScore\fP *, bool vertical)"
.br
.ti -1c
.RI "\fBLine\fP & \fBoperator=\fP (const \fBLine\fP &)"
.br
.ti -1c
.RI "virtual \fBLine\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "void \fBwriteProperties\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "qreal \fBlen\fP () const"
.br
.ti -1c
.RI "qreal \fBlineWidth\fP () const"
.br
.ti -1c
.RI "void \fBsetLen\fP (qreal v)"
.br
.ti -1c
.RI "void \fBsetLineWidth\fP (qreal v)"
.br
.ti -1c
.RI "virtual void \fBspatiumChanged\fP (qreal, qreal) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBvertical\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 510 of file element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
