.TH "Ms::LyricsLine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LyricsLine
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SLine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLyricsLine\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBLyricsLine\fP (const \fBLyricsLine\fP &)"
.br
.ti -1c
.RI "virtual \fBLyricsLine\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual \fBLineSegment\fP * \fBcreateLineSegment\fP () override"
.br
.ti -1c
.RI "virtual void \fBremoveUnmanaged\fP () override"
.br
.ti -1c
.RI "\fBLyrics\fP * \fBlyrics\fP () const"
.br
.ti -1c
.RI "\fBLyrics\fP * \fBnextLyrics\fP () const"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &v) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLyrics\fP * \fB_nextLyrics\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 147 of file lyrics\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
