.TH "Ms::LinkUnlink" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LinkUnlink
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::UndoCommand\fP\&.
.PP
Inherited by \fBMs::Link\fP, and \fBMs::Unlink\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkUnlink\fP (\fBScoreElement\fP *_e, \fBScoreElement\fP *_le)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdoLink\fP ()"
.br
.ti -1c
.RI "void \fBdoUnlink\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1120 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
