.TH "Ms::LyricsLineSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LyricsLineSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::LineSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLyricsLineSegment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBLyricsLineSegment\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "\fBLyricsLine\fP * \fBlyricsLine\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_numOfDashes\fP"
.br
.ti -1c
.RI "qreal \fB_dashLength\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 172 of file lyrics\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
