.TH "Ms::LinkedStaves" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LinkedStaves
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QList< \fBStaff\fP * > & \fBstaves\fP ()"
.br
.ti -1c
.RI "const QList< \fBStaff\fP * > & \fBstaves\fP () const"
.br
.ti -1c
.RI "void \fBadd\fP (\fBStaff\fP *)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBStaff\fP *)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file staff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
