.TH "Ms::LedgerLineData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LedgerLineData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "qreal \fBminX\fP"
.br
.ti -1c
.RI "qreal \fBmaxX\fP"
.br
.ti -1c
.RI "bool \fBvisible\fP"
.br
.ti -1c
.RI "bool \fBaccidental\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file chord\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
