.TH "Ms::LinkedElements" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::LinkedElements
.SH SYNOPSIS
.br
.PP
.PP
Inherits QList< ScoreElement *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkedElements\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBLinkedElements\fP (\fBScore\fP *, int id)"
.br
.ti -1c
.RI "void \fBsetLid\fP (\fBScore\fP *, int val)"
.br
.ti -1c
.RI "int \fBlid\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file scoreElement\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
