.TH "Ms::MidiRemote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiRemote
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBchannel\fP"
.br
.ti -1c
.RI "MidiRemoteType \fBtype\fP"
.br
.ti -1c
.RI "int \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
