.TH "Ms::MidiTuplet::TupletData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTuplet::TupletData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvoice\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBonTime\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBlen\fP"
.br
.ti -1c
.RI "int \fBtupletNumber\fP"
.br
.ti -1c
.RI "std::vector< \fBDurationElement\fP * > \fBelements\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file importmidi_tuplet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
