.TH "Ms::MagBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MagBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits QComboBox\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmagChanged\fP (MagIdx)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMagBox\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMag\fP (double)"
.br
.ti -1c
.RI "void \fBsetMagIdx\fP (MagIdx)"
.br
.ti -1c
.RI "double \fBgetMag\fP (\fBScoreView\fP *) const"
.br
.ti -1c
.RI "double \fBgetLMag\fP (\fBScoreView\fP *) const"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool val)"
.br
.ti -1c
.RI "QString \fBcurrentText\fP () const"
.br
.ti -1c
.RI "int \fBcount\fP () const"
.br
.ti -1c
.RI "void \fBremoveItem\fP (int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file magbox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
