.TH "Ms::MuseScoreCore" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MuseScoreCore
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::MuseScore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScore\fP * \fBcurrentScore\fP () const"
.br
.ti -1c
.RI "void \fBsetCurrentScore\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "virtual bool \fBsaveAs\fP (\fBScore\fP *, bool, const QString &, const QString &)"
.br
.ti -1c
.RI "virtual void \fBcloseScore\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "virtual void \fBcmd\fP (QAction *)"
.br
.ti -1c
.RI "virtual void \fBsetCurrentView\fP (int, int)"
.br
.ti -1c
.RI "virtual int \fBappendScore\fP (\fBMasterScore\fP *s)"
.br
.ti -1c
.RI "virtual void \fBendCmd\fP ()"
.br
.ti -1c
.RI "virtual \fBScore\fP * \fBopenScore\fP (const QString &)"
.br
.ti -1c
.RI "QList< \fBMasterScore\fP * > & \fBscores\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMuseScoreCore\fP * \fBmscoreCore\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBScore\fP * \fBcs\fP { 0 }"
.br
.ti -1c
.RI "QList< \fBMasterScore\fP * > \fBscoreList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file musescoreCore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
