.TH "Ms::MidiOperations::CurrentMidiFileSetter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiOperations::CurrentMidiFileSetter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCurrentMidiFileSetter\fP (\fBData\fP &opers, const QString &fileName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 256 of file importmidi_operations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
