.TH "Ms::MidiLyrics::BestTrack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiLyrics::BestTrack
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP = \-1"
.br
.ti -1c
.RI "std::vector< std::pair< \fBReducedFraction\fP, \fBReducedFraction\fP > > \fBmatchedLyricTimes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file importmidi_lyrics\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
