.TH "Ms::MidiNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiNote
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "int \fBvelo\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoffTime\fP"
.br
.ti -1c
.RI "\fBTie\fP * \fBtie\fP = nullptr"
.br
.ti -1c
.RI "bool \fBstaccato\fP = false"
.br
.ti -1c
.RI "bool \fBisInTuplet\fP = false"
.br
.ti -1c
.RI "std::multimap< \fBReducedFraction\fP, \fBMidiTuplet::TupletData\fP >::iterator \fBtuplet\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoffTimeQuant\fP = \fBReducedFraction\fP(\-1, 1)"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBorigOnTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file importmidi_chord\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
