.TH "Ms::MusicXMLParserDirection" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MusicXMLParserDirection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMusicXMLParserDirection\fP (QXmlStreamReader &e, \fBScore\fP *score, const \fBMusicXMLParserPass1\fP &pass1, \fBMusicXMLParserPass2\fP &pass2)"
.br
.ti -1c
.RI "void \fBdirection\fP (const QString &partId, \fBMeasure\fP *measure, const int tick, MusicXmlSpannerMap &spanners)"
.br
.ti -1c
.RI "void \fBlogError\fP (const QString &error)"
.br
.ti -1c
.RI "void \fBlogDebugInfo\fP (const QString &info)"
.br
.ti -1c
.RI "void \fBskipLogCurrElem\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 209 of file importmxmlpass2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ms::MusicXMLParserDirection::MusicXMLParserDirection (QXmlStreamReader & e, \fBScore\fP * score, const \fBMusicXMLParserPass1\fP & pass1, \fBMusicXMLParserPass2\fP & pass2)"
\fBMusicXMLParserDirection\fP constructor\&. 
.PP
Definition at line 6007 of file importmxmlpass2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ms::MusicXMLParserDirection::direction (const QString & partId, \fBMeasure\fP * measure, const int tick, MusicXmlSpannerMap & spanners)"
Parse the /score-partwise/part/measure/direction node\&. 
.PP
Definition at line 2310 of file importmxmlpass2\&.cpp\&.
.SS "void Ms::MusicXMLParserDirection::logDebugInfo (const QString & info)"
Log debug \fIinfo\fP (non-fatal events relevant for debugging)\&. 
.PP
Definition at line 1565 of file importmxmlpass2\&.cpp\&.
.SS "void Ms::MusicXMLParserDirection::logError (const QString & error)"
Log \fIerror\fP (possibly non-fatal but to be reported to the user anyway)\&. 
.PP
Definition at line 1579 of file importmxmlpass2\&.cpp\&.
.SS "void Ms::MusicXMLParserDirection::skipLogCurrElem ()"
Skip the current element, log debug as info\&. 
.PP
Definition at line 1551 of file importmxmlpass2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
