.TH "Ms::Meter::DivisionInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Meter::DivisionInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReducedFraction\fP \fBonTime\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBlen\fP"
.br
.ti -1c
.RI "bool \fBisTuplet\fP = false"
.br
.ti -1c
.RI "std::vector< \fBDivLengthInfo\fP > \fBdivLengths\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file importmidi_inner\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
