.TH "Ms::MidiOperations::TrackOp< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiOperations::TrackOp< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackOp\fP (T defaultValue)"
.br
.ti -1c
.RI "const T & \fBvalue\fP (int trackIndex) const"
.br
.ti -1c
.RI "void \fBsetValue\fP (int trackIndex, T value)"
.br
.ti -1c
.RI "const T & \fBdefaultValue\fP () const"
.br
.ti -1c
.RI "bool \fBcanRedefineDefaultLater\fP () const"
.br
.ti -1c
.RI "void \fBsetDefaultValue\fP (T value, bool canRedefineDefaultLater=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Ms::MidiOperations::TrackOp< T >"

.PP
Definition at line 31 of file importmidi_operations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
