.TH "Ms::MidiTrack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTrack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "const std::multimap< int, \fBMidiEvent\fP > & \fBevents\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBMidiEvent\fP > & \fBevents\fP ()"
.br
.ti -1c
.RI "int \fBoutChannel\fP () const"
.br
.ti -1c
.RI "void \fBsetOutChannel\fP (int n)"
.br
.ti -1c
.RI "int \fBoutPort\fP () const"
.br
.ti -1c
.RI "void \fBsetOutPort\fP (int n)"
.br
.ti -1c
.RI "bool \fBdrumTrack\fP () const"
.br
.ti -1c
.RI "void \fBinsert\fP (int tick, const \fBMidiEvent\fP &)"
.br
.ti -1c
.RI "void \fBmergeNoteOnOffAndFindMidiType\fP (MidiType *mt)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadXml\fP (\fBXmlReader\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file midifile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
