.TH "Ms::MidiOperations::HumanBeatData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiOperations::HumanBeatData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::set< \fBReducedFraction\fP > \fBbeatSet\fP"
.br
.ti -1c
.RI "int \fBaddedFirstBeats\fP = 0"
.br
.ti -1c
.RI "int \fBaddedLastBeats\fP = 0"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBfirstChordTick\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBlastChordTick\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBtimeSig\fP"
.br
.ti -1c
.RI "bool \fBmeasureCount2xLess\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file importmidi_operations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
