.TH "Ms::MxmlSupport" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MxmlSupport
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBstringToInt\fP (const QString &s, bool *ok)"
.br
.ti -1c
.RI "static \fBFraction\fP \fBdurationAsFraction\fP (const int divisions, const QDomElement e)"
.br
.ti -1c
.RI "static \fBFraction\fP \fBnoteTypeToFraction\fP (QString type)"
.br
.ti -1c
.RI "static \fBFraction\fP \fBcalculateFraction\fP (QString type, int dots, int normalNotes, int actualNotes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file musicxmlsupport\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFraction\fP Ms::MxmlSupport::calculateFraction (QString type, int dots, int normalNotes, int actualNotes)\fC [static]\fP"
Convert note type, number of dots and actual and normal notes into a duration 
.PP
Definition at line 351 of file musicxmlsupport\&.cpp\&.
.SS "\fBFraction\fP Ms::MxmlSupport::durationAsFraction (const int divisions, const QDomElement e)\fC [static]\fP"
Return duration specified in the element e as \fBFraction\fP\&. Caller must ensure divisions is valid\&. 
.PP
Definition at line 286 of file musicxmlsupport\&.cpp\&.
.SS "\fBFraction\fP Ms::MxmlSupport::noteTypeToFraction (QString type)\fC [static]\fP"
Convert MusicXML note type to fraction\&. 
.PP
Definition at line 309 of file musicxmlsupport\&.cpp\&.
.SS "int Ms::MxmlSupport::stringToInt (const QString & s, bool * ok)\fC [static]\fP"
Convert a string in \fIs\fP into an int\&. Set *ok to true iff conversion was successful\&. \fIs\fP may end with '\&.0', as is generated by Audiveris 3\&.2 and up, in elements <divisions>, <duration>, <alter> and <sound> attributes dynamics and tempo\&. In case of error val return a default value of 0\&. \fBNote\fP that non-integer values cannot be handled by mscore\&. 
.PP
Definition at line 267 of file musicxmlsupport\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
