.TH "Ms::MCursor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MCursor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMCursor\fP (\fBScore\fP *s=0)"
.br
.ti -1c
.RI "void \fBcreateScore\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBsaveScore\fP ()"
.br
.ti -1c
.RI "void \fBaddPart\fP (const QString &instrument)"
.br
.ti -1c
.RI "\fBChord\fP * \fBaddChord\fP (int pitch, const \fBTDuration\fP &duration)"
.br
.ti -1c
.RI "void \fBaddKeySig\fP (Key)"
.br
.ti -1c
.RI "\fBTimeSig\fP * \fBaddTimeSig\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "void \fBmove\fP (int track, int tick)"
.br
.ti -1c
.RI "\fBMasterScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBMasterScore\fP *s)"
.br
.ti -1c
.RI "void \fBsetTimeSig\fP (\fBFraction\fP f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file mcursor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
