.TH "Ms::Movements" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Movements
.SH SYNOPSIS
.br
.PP
.PP
Inherits vector< MasterScore *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBpageIdx\fP (\fBPage\fP *page) const"
.br
.ti -1c
.RI "int \fBnpages\fP () const"
.br
.ti -1c
.RI "const QList< \fBPage\fP * > & \fBpages\fP () const"
.br
.ti -1c
.RI "QList< \fBPage\fP * > & \fBpages\fP ()"
.br
.ti -1c
.RI "\fBUndoStack\fP * \fBundo\fP () const"
.br
.ti -1c
.RI "\fBMStyle\fP & \fBstyle\fP ()"
.br
.ti -1c
.RI "const \fBMStyle\fP & \fBstyle\fP () const"
.br
.ti -1c
.RI "\fBText\fP * \fBheaderText\fP () const"
.br
.ti -1c
.RI "\fBText\fP * \fBfooterText\fP () const"
.br
.ti -1c
.RI "void \fBsetHeaderText\fP (\fBText\fP *t)"
.br
.ti -1c
.RI "void \fBsetFooterText\fP (\fBText\fP *t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 295 of file score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
