.TH "Ms::MasterPalette" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MasterPalette
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::MasterPalette\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclosed\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMasterPalette\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBselectItem\fP (const QString &s)"
.br
.ti -1c
.RI "QString \fBselectedItem\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP (bool firstTime=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file masterpalette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
