.TH "Ms::MusicXmlInstrList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MusicXmlInstrList
.SH SYNOPSIS
.br
.PP
.PP
Inherits map< Fraction, QString >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QString \fBinstrument\fP (const \fBFraction\fP f) const"
.br
.ti -1c
.RI "void \fBsetInstrument\fP (const QString instr, const \fBFraction\fP f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file importxmlfirstpass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
