.TH "Ms::MidiMapping" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiMapping
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPart\fP * \fBpart\fP"
.br
.ti -1c
.RI "\fBChannel\fP * \fBarticulation\fP"
.br
.ti -1c
.RI "signed char \fBport\fP"
.br
.ti -1c
.RI "signed char \fBchannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
