.TH "Ms::MidiTie::TieStateMachine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTie::TieStateMachine
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP : char { \fBUNTIED\fP, \fBTIED_FOR\fP, \fBTIED_BOTH\fP, \fBTIED_BACK\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddSeg\fP (const \fBSegment\fP *seg, int strack)"
.br
.ti -1c
.RI "State \fBstate\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file importmidi_tie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
