.TH "Ms::MStaff" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MStaff \- Per staff values of measure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMStaff\fP (const \fBMStaff\fP &)"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "void \fBsetTrack\fP (int)"
.br
.ti -1c
.RI "\fBShape\fP \fBshape\fP () const"
.br
.ti -1c
.RI "\fBShape\fP & \fBshape\fP ()"
.br
.ti -1c
.RI "\fBText\fP * \fBnoText\fP () const"
.br
.ti -1c
.RI "void \fBsetNoText\fP (\fBText\fP *t)"
.br
.ti -1c
.RI "\fBStaffLines\fP * \fBlines\fP () const"
.br
.ti -1c
.RI "void \fBsetLines\fP (\fBStaffLines\fP *l)"
.br
.ti -1c
.RI "\fBSpacer\fP * \fBvspacerUp\fP () const"
.br
.ti -1c
.RI "void \fBsetVspacerUp\fP (\fBSpacer\fP *s)"
.br
.ti -1c
.RI "\fBSpacer\fP * \fBvspacerDown\fP () const"
.br
.ti -1c
.RI "void \fBsetVspacerDown\fP (\fBSpacer\fP *s)"
.br
.ti -1c
.RI "bool \fBhasVoices\fP () const"
.br
.ti -1c
.RI "void \fBsetHasVoices\fP (bool val)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool val)"
.br
.ti -1c
.RI "bool \fBslashStyle\fP () const"
.br
.ti -1c
.RI "void \fBsetSlashStyle\fP (bool val)"
.br
.ti -1c
.RI "bool \fBcorrupted\fP () const"
.br
.ti -1c
.RI "void \fBsetCorrupted\fP (bool val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Per staff values of measure\&. 
.PP
Definition at line 89 of file measure\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
