.TH "Ms::MidiEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::MidiCoreEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiEvent\fP (uchar t, uchar c, uchar a, uchar b)"
.br
.ti -1c
.RI "const uchar * \fBedata\fP () const"
.br
.ti -1c
.RI "void \fBsetEData\fP (uchar *d)"
.br
.ti -1c
.RI "int \fBlen\fP () const"
.br
.ti -1c
.RI "void \fBsetLen\fP (int l)"
.br
.ti -1c
.RI "int \fBmetaType\fP () const"
.br
.ti -1c
.RI "void \fBsetMetaType\fP (int v)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uchar * \fB_edata\fP"
.br
.ti -1c
.RI "int \fB_len\fP"
.br
.ti -1c
.RI "int \fB_metaType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 192 of file event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
