.TH "Ms::MusicXMLDrumInstrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MusicXMLDrumInstrument
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <musicxmlsupport\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBtoString\fP () const"
.br
.ti -1c
.RI "\fBMusicXMLDrumInstrument\fP (QString s)"
.br
.ti -1c
.RI "\fBMusicXMLDrumInstrument\fP (int p, QString s, NoteHead::Group nh, int l, \fBDirection\fP d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBsound\fP"
.br
.ti -1c
.RI "QString \fBvirtLib\fP"
.br
.ti -1c
.RI "QString \fBvirtName\fP"
.br
.ti -1c
.RI "int \fBmidiChannel\fP"
.br
.ti -1c
.RI "int \fBmidiPort\fP"
.br
.ti -1c
.RI "int \fBmidiProgram\fP"
.br
.ti -1c
.RI "int \fBmidiVolume\fP"
.br
.ti -1c
.RI "int \fBmidiPan\fP"
.br
.ti -1c
.RI "NoteHead::Group \fBnotehead\fP"
.br
.RI "notehead symbol set "
.ti -1c
.RI "int \fBline\fP"
.br
.RI "place notehead onto this line "
.ti -1c
.RI "\fBDirection\fP \fBstemDirection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A single instrument in a MusicXML part\&. Used for both a drum part and a (non-drum) multi-instrument part 
.PP
Definition at line 129 of file musicxmlsupport\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
