.TH "Ms::MNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MNote
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMNote\fP (const \fBEvent\fP &_mc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEvent\fP \fBmc\fP"
.br
.ti -1c
.RI "QList< \fBTie\fP * > \fBties\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file bb\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
