.TH "Ms::MusicXmlTupletDesc" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MusicXmlTupletDesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <importmxmlpass2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MxmlStartStop \fBtype\fP"
.br
.ti -1c
.RI "Element::Placement \fBplacement\fP"
.br
.ti -1c
.RI "Tuplet::BracketType \fBbracket\fP"
.br
.ti -1c
.RI "Tuplet::NumberType \fBshownumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describe the information extracted from a single note/notations/tuplet element\&. 
.PP
Definition at line 56 of file importmxmlpass2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
