.TH "Ms::MPaintDevice" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MPaintDevice
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPaintDevice\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QPaintEngine * \fBpaintEngine\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBmetric\fP (PaintDeviceMetric m) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 365 of file mscore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
