.TH "Ms::MidiOperations::Data" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiOperations::Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileData\fP * \fBdata\fP ()"
.br
.ti -1c
.RI "const \fBFileData\fP * \fBdata\fP () const"
.br
.ti -1c
.RI "void \fBaddNewMidiFile\fP (const QString &fileName)"
.br
.ti -1c
.RI "int \fBcurrentTrack\fP () const"
.br
.ti -1c
.RI "void \fBsetMidiFileData\fP (const QString &fileName, const \fBMidiFile\fP &midiFile)"
.br
.ti -1c
.RI "void \fBexcludeMidiFile\fP (const QString &fileName)"
.br
.ti -1c
.RI "bool \fBhasMidiFile\fP (const QString &fileName)"
.br
.ti -1c
.RI "const \fBMidiFile\fP * \fBmidiFile\fP (const QString &fileName)"
.br
.ti -1c
.RI "QStringList \fBallMidiFiles\fP () const"
.br
.ti -1c
.RI "void \fBsetOperationsFile\fP (const QString &fileName)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCurrentTrackSetter\fP"
.br
.ti -1c
.RI "class \fBCurrentMidiFileSetter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 204 of file importmidi_operations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
