.TH "Ms::MuseData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MuseData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMuseData\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "bool \fBread\fP (const QString &)"
.br
.ti -1c
.RI "void \fBconvert\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file musedata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
