.TH "Ms::MusicXmlPart" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MusicXmlPart
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMusicXmlPart\fP (QString id='', QString name='')"
.br
.ti -1c
.RI "void \fBaddMeasureNumberAndDuration\fP (QString measureNumber, \fBFraction\fP measureDuration)"
.br
.ti -1c
.RI "QString \fBgetId\fP () const"
.br
.ti -1c
.RI "QString \fBtoString\fP () const"
.br
.ti -1c
.RI "\fBFraction\fP \fBmeasureDuration\fP (int i) const"
.br
.ti -1c
.RI "int \fBnMeasures\fP () const"
.br
.ti -1c
.RI "int \fBoctaveShift\fP (const int staff, const \fBFraction\fP f) const"
.br
.ti -1c
.RI "void \fBaddOctaveShift\fP (const int staff, const int shift, const \fBFraction\fP f)"
.br
.ti -1c
.RI "void \fBcalcOctaveShifts\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VoiceList \fBvoicelist\fP"
.br
.ti -1c
.RI "\fBMusicXmlInstrList\fP \fB_instrList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file importxmlfirstpass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
