.TH "Ms::MStyle" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MStyle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprecomputeValues\fP ()"
.br
.ti -1c
.RI "QVariant \fBvalue\fP (StyleIdx idx) const"
.br
.ti -1c
.RI "qreal \fBpvalue\fP (StyleIdx idx) const"
.br
.ti -1c
.RI "void \fBset\fP (StyleIdx idx, const QVariant &v)"
.br
.ti -1c
.RI "bool \fBisDefault\fP (StyleIdx idx) const"
.br
.ti -1c
.RI "const \fBChordDescription\fP * \fBchordDescription\fP (int id) const"
.br
.ti -1c
.RI "\fBChordList\fP * \fBchordList\fP ()"
.br
.ti -1c
.RI "void \fBsetChordList\fP (\fBChordList\fP *, bool custom=true)"
.br
.ti -1c
.RI "void \fBsetCustomChordList\fP (bool t)"
.br
.ti -1c
.RI "bool \fBload\fP (QFile *qf)"
.br
.ti -1c
.RI "void \fBload\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "void \fBsave\fP (\fBXmlWriter\fP &xml, bool optimize)"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBvalueType\fP (const StyleIdx)"
.br
.ti -1c
.RI "static const char * \fBvalueName\fP (const StyleIdx)"
.br
.ti -1c
.RI "static StyleIdx \fBstyleIdx\fP (const QString &name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 746 of file style\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
