.TH "Ms::MidiCoreEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiCoreEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::MidiEvent\fP, and \fBMs::PlayEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiCoreEvent\fP (uchar t, uchar c, uchar a, uchar b)"
.br
.ti -1c
.RI "void \fBset\fP (uchar t, uchar c, uchar a, uchar b)"
.br
.ti -1c
.RI "uchar \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBsetType\fP (uchar t)"
.br
.ti -1c
.RI "uchar \fBchannel\fP () const"
.br
.ti -1c
.RI "void \fBsetChannel\fP (uchar c)"
.br
.ti -1c
.RI "int \fBdataA\fP () const"
.br
.ti -1c
.RI "int \fBpitch\fP () const"
.br
.ti -1c
.RI "int \fBcontroller\fP () const"
.br
.ti -1c
.RI "void \fBsetDataA\fP (int v)"
.br
.ti -1c
.RI "void \fBsetPitch\fP (int v)"
.br
.ti -1c
.RI "void \fBsetController\fP (int v)"
.br
.ti -1c
.RI "int \fBdataB\fP () const"
.br
.ti -1c
.RI "int \fBvelo\fP () const"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBsetDataB\fP (int v)"
.br
.ti -1c
.RI "void \fBsetVelo\fP (int v)"
.br
.ti -1c
.RI "void \fBsetValue\fP (int v)"
.br
.ti -1c
.RI "void \fBsetData\fP (int a, int b)"
.br
.ti -1c
.RI "void \fBsetData\fP (int t, int a, int b)"
.br
.ti -1c
.RI "bool \fBisChannelEvent\fP () const"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMidiCoreEvent\fP &e) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uchar \fB_type\fP = 0"
.br
.ti -1c
.RI "uchar \fB_channel\fP = 0"
.br
.ti -1c
.RI "uchar \fB_a\fP = 0"
.br
.ti -1c
.RI "uchar \fB_b\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 138 of file event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
