.TH "Ms::MidiTuplet::TupletLimits" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTuplet::TupletLimits
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReducedFraction\fP \fBratio\fP"
.br
.ti -1c
.RI "int \fBminNoteCount\fP"
.br
.ti -1c
.RI "int \fBminNoteCountAddVoice\fP"
.br
.ti -1c
.RI "int \fBminNoteCountStaccato\fP"
.br
.ti -1c
.RI "int \fBminNoteCountHuman\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file importmidi_tuplet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
