.TH "Ms::MultiValueEditor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MultiValueEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBokClicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiValueEditor\fP (const QStringList &values, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "QStringList \fBdata\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file importmidi_delegate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
