.TH "Ms::MidiOperations::FileData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiOperations::FileData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMidiFile\fP \fBmidiFile\fP"
.br
.ti -1c
.RI "int \fBprocessingsOfOpenedFile\fP = 0"
.br
.ti -1c
.RI "bool \fBhasTempoText\fP = false"
.br
.ti -1c
.RI "QByteArray \fBHHeaderData\fP"
.br
.ti -1c
.RI "QByteArray \fBVHeaderData\fP"
.br
.ti -1c
.RI "int \fBtrackCount\fP = 0"
.br
.ti -1c
.RI "\fBOpers\fP \fBtrackOpers\fP"
.br
.ti -1c
.RI "QString \fBcharset\fP = MidiCharset::defaultCharset()"
.br
.ti -1c
.RI "QList< std::multimap< \fBReducedFraction\fP, std::string > > \fBlyricTracks\fP"
.br
.ti -1c
.RI "std::multimap< \fBReducedFraction\fP, QString > \fBchordNames\fP"
.br
.ti -1c
.RI "\fBHumanBeatData\fP \fBhumanBeatData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file importmidi_operations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
