.TH "Ms::MidiChord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiChord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisStaccato\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvoice\fP = 0"
.br
.ti -1c
.RI "QList< \fBMidiNote\fP > \fBnotes\fP"
.br
.ti -1c
.RI "bool \fBisInTuplet\fP = false"
.br
.ti -1c
.RI "int \fBbarIndex\fP = \-1"
.br
.ti -1c
.RI "std::multimap< \fBReducedFraction\fP, \fBMidiTuplet::TupletData\fP >::iterator \fBtuplet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file importmidi_chord\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
