.TH "Ms::MeasureBaseList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MeasureBaseList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeasureBase\fP * \fBfirst\fP () const"
.br
.ti -1c
.RI "\fBMeasureBase\fP * \fBlast\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBMeasureBase\fP *)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBMeasureBase\fP *)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBMeasureBase\fP *, \fBMeasureBase\fP *)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBMeasureBase\fP *, \fBMeasureBase\fP *)"
.br
.ti -1c
.RI "void \fBchange\fP (\fBMeasureBase\fP *o, \fBMeasureBase\fP *n)"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
