.TH "Ms::MuseScoreView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MuseScoreView
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::ExampleView\fP, \fBMs::PianorollEditor\fP, and \fBMs::ScoreView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPage\fP * \fBpoint2page\fP (const QPointF &)"
.br
.ti -1c
.RI "\fBElement\fP * \fBelementAt\fP (const QPointF &p)"
.br
.ti -1c
.RI "const QList< \fBElement\fP * > \fBelementsAt\fP (const QPointF &)"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBelementNear\fP (QPointF)"
.br
.ti -1c
.RI "virtual void \fBlayoutChanged\fP ()"
.br
.ti -1c
.RI "virtual void \fBdataChanged\fP (const QRectF &)=0"
.br
.ti -1c
.RI "virtual void \fBupdateAll\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBmoveCursor\fP ()"
.br
.ti -1c
.RI "virtual void \fBshowLoopCursors\fP (bool)"
.br
.ti -1c
.RI "virtual void \fBadjustCanvasPosition\fP (const \fBElement\fP *, bool)"
.br
.ti -1c
.RI "virtual void \fBsetScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "virtual void \fBremoveScore\fP ()"
.br
.ti -1c
.RI "virtual void \fBchangeEditElement\fP (\fBElement\fP *)"
.br
.ti -1c
.RI "virtual QCursor \fBcursor\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetCursor\fP (const QCursor &)"
.br
.ti -1c
.RI "virtual int \fBgripCount\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetDropRectangle\fP (const QRectF &)"
.br
.ti -1c
.RI "virtual void \fBcmdAddSlur\fP (\fBNote\fP *, \fBNote\fP *)"
.br
.ti -1c
.RI "virtual void \fBcmdAddHairpin\fP (HairpinType)"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP ()"
.br
.ti -1c
.RI "virtual void \fBstartEditMode\fP (\fBElement\fP *)"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBElement\fP *, Grip)"
.br
.ti -1c
.RI "virtual void \fBstartNoteEntryMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBdrawBackground\fP (QPainter *, const QRectF &) const =0"
.br
.ti -1c
.RI "virtual void \fBsetDropTarget\fP (const \fBElement\fP *)"
.br
.ti -1c
.RI "virtual void \fBlyricsTab\fP (bool, bool, bool)"
.br
.ti -1c
.RI "virtual void \fBlyricsReturn\fP ()"
.br
.ti -1c
.RI "virtual void \fBlyricsEndEdit\fP ()"
.br
.ti -1c
.RI "virtual void \fBlyricsUpDown\fP (bool, bool)"
.br
.ti -1c
.RI "virtual void \fBlyricsMinus\fP ()"
.br
.ti -1c
.RI "virtual void \fBlyricsUnderscore\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBScore\fP * \fB_score\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file mscoreview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
