.TH "Ms::Meter::Node" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Meter::Node
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (int edgeLevel, int midLevel)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBedgeLevel\fP"
.br
.ti -1c
.RI "int \fBmidLevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 342 of file importmidi_meter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
