.TH "Ms::MidiClef::MinMaxPitch" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiClef::MinMaxPitch
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinMaxPitch\fP (int minPitch, int maxPitch)"
.br
.ti -1c
.RI "int \fBminPitch\fP () const"
.br
.ti -1c
.RI "int \fBmaxPitch\fP () const"
.br
.ti -1c
.RI "int \fBempty\fP () const"
.br
.ti -1c
.RI "void \fBaddPitch\fP (int pitch)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file importmidi_clef\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
