.TH "Ms::MidiDriver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiDriver
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::AlsaMidiDriver\fP, and \fBMs::PortMidiDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMidiDriver\fP (\fBSeq\fP *s)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBgetInputPollFd\fP (struct pollfd **, int *n)=0"
.br
.ti -1c
.RI "virtual void \fBgetOutputPollFd\fP (struct pollfd **, int *n)=0"
.br
.ti -1c
.RI "virtual void \fBread\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (const \fBEvent\fP &)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPort\fP \fBmidiInPort\fP"
.br
.ti -1c
.RI "QList< \fBPort\fP > \fBmidiOutPorts\fP"
.br
.ti -1c
.RI "\fBSeq\fP * \fBseq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file mididriver\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
