.TH "Ms::MidiTuplet::TupletInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTuplet::TupletInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBonTime\fP = {\-1, 1}"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBlen\fP = {\-1, 1}"
.br
.ti -1c
.RI "int \fBtupletNumber\fP = \-1"
.br
.ti -1c
.RI "std::map< \fBReducedFraction\fP, std::multimap< \fBReducedFraction\fP, \fBMidiChord\fP >::iterator > \fBchords\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBtupletSumError\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBregularSumError\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBsumLengthOfRests\fP"
.br
.ti -1c
.RI "int \fBfirstChordIndex\fP = \-1"
.br
.ti -1c
.RI "std::map< \fBReducedFraction\fP, int > \fBstaccatoChords\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file importmidi_inner\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
