.TH "Ms::MidiArticulation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiArticulation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "\fBMidiArticulation\fP (const QString &n, const QString &d, int v, int g)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMidiArticulation\fP &i) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBdescr\fP"
.br
.ti -1c
.RI "int \fBvelocity\fP"
.br
.ti -1c
.RI "int \fBgateTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file instrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
