.TH "Ms::MidiTuplet::ValidTuplets" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::MidiTuplet::ValidTuplets
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidTuplets\fP (int tupletsSize)"
.br
.ti -1c
.RI "int \fBfirst\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP (int index) const"
.br
.ti -1c
.RI "int \fBnext\fP (int index) const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "int \fBexclude\fP (int index)"
.br
.ti -1c
.RI "std::vector< std::pair< int, int > > \fBsave\fP ()"
.br
.ti -1c
.RI "void \fBrestore\fP (const std::vector< std::pair< int, int >> &indexes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 463 of file importmidi_tuplet_filter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
