.TH "Ms::NoteGroups" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteGroups
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGroupBox, and \fBUi::NoteGroups\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteGroups\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetSig\fP (\fBFraction\fP sig, const \fBGroups\fP &)"
.br
.ti -1c
.RI "\fBGroups\fP \fBgroups\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file noteGroups\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
