.TH "Ms::NoteObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteObj
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMs::CapClef\fP, \fBMs::CapExplicitBarline\fP, \fBMs::CapKey\fP, \fBMs::CapMeter\fP, \fBMs::ChordObj\fP, and \fBMs::RestObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteObj\fP (CapellaNoteObjectType t)"
.br
.ti -1c
.RI "CapellaNoteObjectType \fBtype\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
