.TH "Ms::NoteDot" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteDot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteDot\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "virtual \fBNoteDot\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "\fBNote\fP * \fBnote\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file notedot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
