.TH "Ms::NoteList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <musicxmlsupport\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddNote\fP (const int startTick, const int endTick, const int staff)"
.br
.ti -1c
.RI "void \fBdump\fP (const QString &voice) const"
.br
.ti -1c
.RI "bool \fBstavesOverlap\fP (const int staff1, const int staff2) const"
.br
.ti -1c
.RI "bool \fBanyStaffOverlaps\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of note start/stop times in a voice in all staves\&. 
.PP
Definition at line 49 of file musicxmlsupport\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Ms::NoteList::anyStaffOverlaps () const"
Determine if any note in any staff overlaps\&. 
.PP
Definition at line 92 of file musicxmlsupport\&.cpp\&.
.SS "bool Ms::NoteList::stavesOverlap (const int staff1, const int staff2) const"
Determine if any note in staff1 and staff2 overlaps\&. 
.PP
Definition at line 77 of file musicxmlsupport\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
