.TH "Ms::NewWizard" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NewWizard
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWizard\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPage\fP { \fBInvalid\fP = -1, \fBType\fP, \fBInstruments\fP, \fBTemplate\fP, \fBKeysig\fP, \fBTimesig\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewWizard\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "virtual int \fBnextId\fP () const"
.br
.ti -1c
.RI "QString \fBtemplatePath\fP () const"
.br
.ti -1c
.RI "int \fBmeasures\fP () const"
.br
.ti -1c
.RI "\fBFraction\fP \fBtimesig\fP () const"
.br
.ti -1c
.RI "void \fBcreateInstruments\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "QString \fBtitle\fP () const"
.br
.ti -1c
.RI "QString \fBsubtitle\fP () const"
.br
.ti -1c
.RI "QString \fBcomposer\fP () const"
.br
.ti -1c
.RI "QString \fBpoet\fP () const"
.br
.ti -1c
.RI "QString \fBcopyright\fP () const"
.br
.ti -1c
.RI "\fBKeySigEvent\fP \fBkeysig\fP () const"
.br
.ti -1c
.RI "bool \fBpickupMeasure\fP (int *z, int *n) const"
.br
.ti -1c
.RI "TimeSigType \fBtimesigType\fP () const"
.br
.ti -1c
.RI "double \fBtempo\fP () const"
.br
.ti -1c
.RI "bool \fBcreateTempo\fP () const"
.br
.ti -1c
.RI "bool \fBemptyScore\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQWizardPage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 174 of file newwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
