.TH "Ms::NoteEventList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteEventList
.SH SYNOPSIS
.br
.PP
.PP
Inherits QList< NoteEvent >\&.
.SH "Detailed Description"
.PP 
Definition at line 51 of file noteevent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
