.TH "Ms::NewWizardPage2" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NewWizardPage2
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWizardPage\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetComplete\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewWizardPage2\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "virtual bool \fBisComplete\fP () const override"
.br
.ti -1c
.RI "void \fBcreateInstruments\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual void \fBinitializePage\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file newwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
