.TH "Ms::NoEffect" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoEffect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (float) override"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (int, float *, float *) override"
.br
.ti -1c
.RI "virtual void \fBsetNValue\fP (int, double) override"
.br
.ti -1c
.RI "virtual double \fBvalue\fP (int) const override"
.br
.ti -1c
.RI "virtual double \fBnvalue\fP (int) const override"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const override"
.br
.ti -1c
.RI "virtual \fBEffectGui\fP * \fBgui\fP () override"
.br
.ti -1c
.RI "virtual const std::vector< \fBParDescr\fP > & \fBparDescr\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file noeffect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
