.TH "Ms::NewWizardPage1" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NewWizardPage1
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWizardPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewWizardPage1\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QString \fBtitle\fP () const"
.br
.ti -1c
.RI "QString \fBsubtitle\fP () const"
.br
.ti -1c
.RI "QString \fBcomposer\fP () const"
.br
.ti -1c
.RI "QString \fBpoet\fP () const"
.br
.ti -1c
.RI "QString \fBcopyright\fP () const"
.br
.ti -1c
.RI "virtual void \fBinitializePage\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file newwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
