.TH "Ms::NoteEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteEvent\fP (int a, int b, int c)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "int \fBpitch\fP () const"
.br
.ti -1c
.RI "int \fBontime\fP () const"
.br
.ti -1c
.RI "int \fBofftime\fP () const"
.br
.ti -1c
.RI "int \fBlen\fP () const"
.br
.ti -1c
.RI "void \fBsetPitch\fP (int v)"
.br
.ti -1c
.RI "void \fBsetOntime\fP (int v)"
.br
.ti -1c
.RI "void \fBsetLen\fP (int v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNoteEvent\fP &) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file noteevent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
