.TH "Ms::NotePattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NotePattern
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBNote\fP * > \fBel\fP"
.br
.ti -1c
.RI "int \fBpitch\fP = \-1"
.br
.ti -1c
.RI "int \fBtpc\fP = Tpc::TPC_INVALID"
.br
.ti -1c
.RI "NoteHead::Group \fBnotehead\fP = NoteHead::Group::HEAD_INVALID"
.br
.ti -1c
.RI "\fBTDuration\fP \fBduration\fP = \fBTDuration\fP()"
.br
.ti -1c
.RI "NoteType \fBtype\fP = NoteType::INVALID"
.br
.ti -1c
.RI "int \fBstaffStart\fP"
.br
.ti -1c
.RI "int \fBstaffEnd\fP"
.br
.ti -1c
.RI "int \fBvoice\fP"
.br
.ti -1c
.RI "const \fBSystem\fP * \fBsystem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file select\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
