.TH "Ms::NPlayEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NPlayEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::PlayEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNPlayEvent\fP (uchar t, uchar c, uchar a, uchar b)"
.br
.ti -1c
.RI "\fBNPlayEvent\fP (const \fBMidiCoreEvent\fP &e)"
.br
.ti -1c
.RI "\fBNPlayEvent\fP (BeatType beatType)"
.br
.ti -1c
.RI "const \fBNote\fP * \fBnote\fP () const"
.br
.ti -1c
.RI "void \fBsetNote\fP (const \fBNote\fP *v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 236 of file event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
