.TH "Ms::NoteLine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteLine
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::TextLineBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteLine\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBNoteLine\fP (const \fBNoteLine\fP &)"
.br
.ti -1c
.RI "virtual \fBNoteLine\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBsetStartNote\fP (\fBNote\fP *n)"
.br
.ti -1c
.RI "\fBNote\fP * \fBstartNote\fP () const"
.br
.ti -1c
.RI "void \fBsetEndNote\fP (\fBNote\fP *n)"
.br
.ti -1c
.RI "\fBNote\fP * \fBendNote\fP () const"
.br
.ti -1c
.RI "virtual \fBLineSegment\fP * \fBcreateLineSegment\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 51 of file noteline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
