.TH "Ms::NoteVal" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::NoteVal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoteVal\fP (int p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpitch\fP { \-1 }"
.br
.ti -1c
.RI "int \fBtpc1\fP { Tpc::TPC_INVALID }"
.br
.ti -1c
.RI "int \fBtpc2\fP { Tpc::TPC_INVALID }"
.br
.ti -1c
.RI "int \fBfret\fP { FRET_NONE }"
.br
.ti -1c
.RI "int \fBstring\fP { STRING_NONE }"
.br
.ti -1c
.RI "NoteHead::Group \fBheadGroup\fP { NoteHead::Group::HEAD_NORMAL }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 158 of file note\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
