.TH "Ms::Navigator" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Navigator
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateViewRect\fP ()"
.br
.ti -1c
.RI "void \fBlayoutChanged\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBviewRectMoved\fP (const QRectF &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNavigator\fP (\fBNScrollArea\fP *sa, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetScoreView\fP (\fBScoreView\fP *)"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "void \fBsetPreviewOnly\fP (bool b)"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "void \fBsetViewRect\fP (const QRectF &r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file navigator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
