.TH "Ms::OmrSystem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrSystem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrSystem\fP (\fBOmrPage\fP *p)"
.br
.ti -1c
.RI "const QList< \fBOmrStaff\fP > & \fBstaves\fP () const"
.br
.ti -1c
.RI "QList< \fBOmrStaff\fP > & \fBstaves\fP ()"
.br
.ti -1c
.RI "QList< \fBOmrMeasure\fP > & \fBmeasures\fP ()"
.br
.ti -1c
.RI "const QList< \fBOmrMeasure\fP > & \fBmeasures\fP () const"
.br
.ti -1c
.RI "void \fBsearchSysBarLines\fP ()"
.br
.ti -1c
.RI "float \fBsearchBarLinesvar\fP (int n_staff, int **note_labels)"
.br
.ti -1c
.RI "void \fBsearchNotes\fP ()"
.br
.ti -1c
.RI "void \fBsearchNotes\fP (int *note_labels, int ran)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< QLine > \fBbarLines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 161 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
