.TH "Ms::Ossia" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Ossia \- not implemented yet  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ossia\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOssia\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBOssia\fP (const \fBOssia\fP &)"
.br
.ti -1c
.RI "virtual \fBOssia\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
not implemented yet 
.PP
Definition at line 25 of file ossia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
