.TH "Ms::OffsetSelect" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OffsetSelect
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::OffsetSelect\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBoffsetChanged\fP (const QPointF &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOffsetSelect\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetSuffix\fP (const QString &)"
.br
.ti -1c
.RI "QPointF \fBoffset\fP () const"
.br
.ti -1c
.RI "void \fBsetOffset\fP (const QPointF &)"
.br
.ti -1c
.RI "void \fBshowRaster\fP (bool)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file offsetSelect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
