.TH "Ms::OmrClef" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrClef
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::OmrPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrClef\fP (const \fBOmrPattern\fP &p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ClefType \fBtype\fP = ClefType::G"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
