.TH "Ms::Omr" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Omr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmr\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBOmr\fP (const QString &, \fBScore\fP *)"
.br
.ti -1c
.RI "bool \fBreadPdf\fP ()"
.br
.ti -1c
.RI "int \fBpagesInDocument\fP () const"
.br
.ti -1c
.RI "int \fBnumPages\fP () const"
.br
.ti -1c
.RI "\fBOmrPage\fP * \fBpage\fP (int)"
.br
.ti -1c
.RI "const QList< \fBOmrPage\fP * > & \fBpages\fP () const"
.br
.ti -1c
.RI "\fBOmrView\fP * \fBnewOmrView\fP (\fBScoreView\fP *)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "double \fBspatiumMM\fP () const"
.br
.ti -1c
.RI "double \fBspatium\fP () const"
.br
.ti -1c
.RI "double \fBdpmm\fP () const"
.br
.ti -1c
.RI "double \fBstaffDistance\fP () const"
.br
.ti -1c
.RI "double \fBsystemDistance\fP () const"
.br
.ti -1c
.RI "\fBScore\fP * \fBscore\fP () const"
.br
.ti -1c
.RI "const QString & \fBpath\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file omr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
