.TH "Ms::OmrStaff" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrStaff
.SH SYNOPSIS
.br
.PP
.PP
Inherits QRect\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrStaff\fP (const QRect &r)"
.br
.ti -1c
.RI "\fBOmrStaff\fP (int x, int y, int w, int h)"
.br
.ti -1c
.RI "QList< \fBOmrNote\fP * > & \fBnotes\fP ()"
.br
.ti -1c
.RI "const QList< \fBOmrNote\fP * > & \fBnotes\fP () const"
.br
.ti -1c
.RI "\fBOmrClef\fP \fBclef\fP () const"
.br
.ti -1c
.RI "void \fBsetClef\fP (const \fBOmrClef\fP &c)"
.br
.ti -1c
.RI "\fBOmrKeySig\fP \fBkeySig\fP () const"
.br
.ti -1c
.RI "void \fBsetKeySig\fP (const \fBOmrKeySig\fP &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
