.TH "Ms::OmrMeasure" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrMeasure
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrMeasure\fP (int x1, int x2)"
.br
.ti -1c
.RI "QList< QList< \fBOmrChord\fP > > & \fBchords\fP ()"
.br
.ti -1c
.RI "const QList< QList< \fBOmrChord\fP > > & \fBchords\fP () const"
.br
.ti -1c
.RI "int \fBx1\fP () const"
.br
.ti -1c
.RI "int \fBx2\fP () const"
.br
.ti -1c
.RI "\fBOmrTimesig\fP * \fBtimesig\fP () const"
.br
.ti -1c
.RI "void \fBsetTimesig\fP (\fBOmrTimesig\fP *ts)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
