.TH "Ms::OmrNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrNote
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::OmrPattern\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
