.TH "Ms::OmrPage" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrPage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrPage\fP (\fBOmr\fP *_parent)"
.br
.ti -1c
.RI "void \fBsetImage\fP (const QImage &i)"
.br
.ti -1c
.RI "const QImage & \fBimage\fP () const"
.br
.ti -1c
.RI "QImage & \fBimage\fP ()"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "int \fBwidth\fP () const"
.br
.ti -1c
.RI "int \fBheight\fP () const"
.br
.ti -1c
.RI "const uint * \fBscanLine\fP (int y) const"
.br
.ti -1c
.RI "const uint * \fBbits\fP () const"
.br
.ti -1c
.RI "int \fBwordsPerLine\fP () const"
.br
.ti -1c
.RI "const QList< QLine > & \fBsl\fP ()"
.br
.ti -1c
.RI "const QList< \fBHLine\fP > & \fBl\fP ()"
.br
.ti -1c
.RI "const QList< QRect > & \fBslices\fP () const"
.br
.ti -1c
.RI "double \fBspatium\fP () const"
.br
.ti -1c
.RI "double \fBratio\fP () const"
.br
.ti -1c
.RI "double \fBstaffDistance\fP () const"
.br
.ti -1c
.RI "double \fBsystemDistance\fP () const"
.br
.ti -1c
.RI "void \fBreadHeader\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "void \fBreadBarLines\fP ()"
.br
.ti -1c
.RI "float \fBsearchBarLines\fP (int start_staff, int end_staff)"
.br
.ti -1c
.RI "void \fBidentifySystems\fP ()"
.br
.ti -1c
.RI "const QList< \fBOmrSystem\fP > & \fBsystems\fP () const"
.br
.ti -1c
.RI "\fBOmrSystem\fP * \fBsystem\fP (int idx)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "bool \fBdot\fP (int x, int y) const"
.br
.ti -1c
.RI "bool \fBisBlack\fP (int x, int y) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
