.TH "Ms::OmrChord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrChord
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTDuration\fP \fBduration\fP"
.br
.ti -1c
.RI "QList< \fBOmrNote\fP * > \fBnotes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file omrpage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
