.TH "Ms::Ottava" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Ottava
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::TextLineBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOttava\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBOttava\fP (const \fBOttava\fP &)"
.br
.ti -1c
.RI "virtual \fBOttava\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "void \fBsetOttavaType\fP (OttavaType val)"
.br
.ti -1c
.RI "OttavaType \fBottavaType\fP () const"
.br
.ti -1c
.RI "void \fBundoSetOttavaType\fP (OttavaType val)"
.br
.ti -1c
.RI "bool \fBnumbersOnly\fP () const"
.br
.ti -1c
.RI "void \fBsetNumbersOnly\fP (bool val)"
.br
.ti -1c
.RI "virtual \fBLineSegment\fP * \fBcreateLineSegment\fP () override"
.br
.ti -1c
.RI "int \fBpitchShift\fP () const"
.br
.ti -1c
.RI "virtual void \fBendEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &de) override"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual PropertyFlags \fBpropertyFlags\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual StyleIdx \fBgetPropertyStyle\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual void \fBstyleChanged\fP () override"
.br
.ti -1c
.RI "virtual void \fBreset\fP () override"
.br
.ti -1c
.RI "virtual void \fBsetYoff\fP (qreal) override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBOttavaSegment\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 75 of file ottava\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
