.TH "Ms::OmrState" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBimportPdfPage\fP (\fBOmrPage\fP *omrPage, qreal top)"
.br
.ti -1c
.RI "int \fBimportPdfSystem\fP (\fBOmrSystem\fP *omrSystem)"
.br
.ti -1c
.RI "void \fBimportPdfMeasure\fP (\fBOmrMeasure\fP *m, const \fBOmrSystem\fP *omrSystem)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMasterScore\fP * \fBscore\fP = 0"
.br
.ti -1c
.RI "\fBFraction\fP \fBtimesig\fP { 4, 4}"
.br
.ti -1c
.RI "int \fBtick\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file importpdf\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
