.TH "Ms::OmrView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OmrView
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetScale\fP (double)"
.br
.ti -1c
.RI "void \fBsetOffset\fP (double, double)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBpageNumberChanged\fP (int)"
.br
.ti -1c
.RI "void \fBxPosChanged\fP (int)"
.br
.ti -1c
.RI "void \fByPosChanged\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmrView\fP (\fBScoreView\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetOmr\fP (\fBOmr\fP *)"
.br
.ti -1c
.RI "\fBOmr\fP * \fBomr\fP () const"
.br
.ti -1c
.RI "bool \fBfotoMode\fP () const"
.br
.ti -1c
.RI "void \fBsetFotoMode\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetShowLines\fP (bool val)"
.br
.ti -1c
.RI "bool \fBshowLines\fP () const"
.br
.ti -1c
.RI "bool \fBshowBarlines\fP () const"
.br
.ti -1c
.RI "bool \fBshowSlices\fP () const"
.br
.ti -1c
.RI "bool \fBshowStaves\fP () const"
.br
.ti -1c
.RI "void \fBsetShowBarlines\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetShowSlices\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetShowStaves\fP (bool val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file omrview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
