.TH "Ms::OperationsDelegate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::OperationsDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSeparatorDelegate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperationsDelegate\fP (QWidget *appWindow, bool rightArrowAlign)"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const"
.br
.ti -1c
.RI "QWidget * \fBcreateEditor\fP (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const"
.br
.ti -1c
.RI "void \fBsetEditorData\fP (QWidget *editor, const QModelIndex &index) const"
.br
.ti -1c
.RI "void \fBsetModelData\fP (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file importmidi_delegate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
