.TH "Ms::PosLen" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PosLen
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Pos\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPosLen\fP (\fBTempoMap\fP *, \fBTimeSigMap\fP *)"
.br
.ti -1c
.RI "\fBPosLen\fP (const \fBPosLen\fP &)"
.br
.ti -1c
.RI "void \fBdump\fP (int n=0) const"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &, const char *) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBsetLenTick\fP (unsigned)"
.br
.ti -1c
.RI "void \fBsetLenFrame\fP (unsigned)"
.br
.ti -1c
.RI "unsigned \fBlenTick\fP () const"
.br
.ti -1c
.RI "unsigned \fBlenFrame\fP () const"
.br
.ti -1c
.RI "\fBPos\fP \fBend\fP () const"
.br
.ti -1c
.RI "unsigned \fBendTick\fP () const"
.br
.ti -1c
.RI "unsigned \fBendFrame\fP () const"
.br
.ti -1c
.RI "void \fBsetPos\fP (const \fBPos\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPosLen\fP &s) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 112 of file pos\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
