.TH "Ms::PianoItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PianoItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGraphicsRectItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPianoItem\fP (\fBNote\fP *, \fBNoteEvent\fP *)"
.br
.ti -1c
.RI "virtual int \fBtype\fP () const"
.br
.ti -1c
.RI "\fBNote\fP * \fBnote\fP ()"
.br
.ti -1c
.RI "\fBNoteEvent\fP * \fBevent\fP ()"
.br
.ti -1c
.RI "QRectF \fBupdateValues\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pianoview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
