.TH "Ms::PitchList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PitchList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pitch\&.h>\fP
.PP
Inherits QMap< int, int >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBpitchOffset\fP (int tick) const"
.br
.ti -1c
.RI "void \fBsetPitchOffset\fP (int tick, int offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPitchList\fP List of note pitch offsets 
.PP
Definition at line 23 of file pitch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
