.TH "Ms::PartEdit" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PartEdit
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::PartEditBase\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsoloChanged\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartEdit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetPart\fP (\fBPart\fP *, \fBChannel\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 37 of file mixer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
