.TH "Ms::PluginManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PluginManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::PluginManager\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclosed\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginManager\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file pluginManager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
