.TH "Ms::Pdf" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Pdf
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBopen\fP (const QString &path)"
.br
.ti -1c
.RI "int \fBnumPages\fP () const"
.br
.ti -1c
.RI "QImage \fBpage\fP (int)"
.br
.ti -1c
.RI "QImage \fBbinarization\fP (QImage image)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file pdf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
