.TH "Ms::PropertyMetaData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PropertyMetaData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "P_ID \fBid\fP"
.br
.ti -1c
.RI "const char * \fBqml\fP"
.br
.ti -1c
.RI "bool \fBlink\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "P_TYPE \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file property\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
