.TH "Ms::Pedal" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Pedal
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::TextLineBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPedal\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBPedal\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "\fBLineSegment\fP * \fBcreateLineSegment\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetYoff\fP (qreal) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID propertyId) const override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QPointF \fBlinePos\fP (Grip, \fBSystem\fP **) const override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPedalLine\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 45 of file pedal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
