.TH "Ms::PageFormat" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PageFormat
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QSizeF & \fBsize\fP () const"
.br
.ti -1c
.RI "qreal \fBwidth\fP () const"
.br
.ti -1c
.RI "qreal \fBheight\fP () const"
.br
.ti -1c
.RI "void \fBsetSize\fP (const QSizeF &s)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "qreal \fBevenLeftMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBoddLeftMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBevenTopMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBevenBottomMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBoddTopMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBoddBottomMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBprintableWidth\fP () const"
.br
.ti -1c
.RI "void \fBsetEvenLeftMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetOddLeftMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetEvenTopMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetEvenBottomMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetOddTopMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetOddBottomMargin\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetPrintableWidth\fP (qreal val)"
.br
.ti -1c
.RI "bool \fBtwosided\fP () const"
.br
.ti -1c
.RI "void \fBsetTwosided\fP (bool val)"
.br
.ti -1c
.RI "qreal \fBevenRightMargin\fP () const"
.br
.ti -1c
.RI "qreal \fBoddRightMargin\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QSizeF \fBsize\fP"
.br
.ti -1c
.RI "qreal \fBprintableWidth\fP"
.br
.ti -1c
.RI "qreal \fBevenLeftMargin\fP"
.br
.ti -1c
.RI "qreal \fBoddLeftMargin\fP"
.br
.ti -1c
.RI "qreal \fBevenTopMargin\fP"
.br
.ti -1c
.RI "qreal \fBevenBottomMargin\fP"
.br
.ti -1c
.RI "qreal \fBoddTopMargin\fP"
.br
.ti -1c
.RI "qreal \fBoddBottomMargin\fP"
.br
.ti -1c
.RI "bool \fBtwosided\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file read206\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
