.TH "Ms::Preferences" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Preferences
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBreadPluginList\fP ()"
.br
.ti -1c
.RI "void \fBwritePluginList\fP ()"
.br
.ti -1c
.RI "void \fBupdatePluginList\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP ()"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "QColor \fBreadColor\fP (QString key, QColor def)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "bool \fBreadDefaultStyle\fP ()"
.br
.ti -1c
.RI "bool \fBisThemeDark\fP ()"
.br
.ti -1c
.RI "bool \fBisOxygen\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbgUseColor\fP"
.br
.ti -1c
.RI "bool \fBfgUseColor\fP"
.br
.ti -1c
.RI "QString \fBbgWallpaper\fP"
.br
.ti -1c
.RI "QString \fBfgWallpaper\fP"
.br
.ti -1c
.RI "QColor \fBfgColor\fP"
.br
.ti -1c
.RI "int \fBiconHeight\fP"
.br
.ti -1c
.RI "int \fBiconWidth\fP"
.br
.ti -1c
.RI "QColor \fBdropColor\fP"
.br
.ti -1c
.RI "QColor \fBpianoHlColor\fP"
.br
.ti -1c
.RI "bool \fBenableMidiInput\fP"
.br
.ti -1c
.RI "int \fBrealtimeDelay\fP"
.br
.ti -1c
.RI "bool \fBplayNotes\fP"
.br
.ti -1c
.RI "bool \fBplayChordOnAddNote\fP"
.br
.ti -1c
.RI "bool \fBshowNavigator\fP"
.br
.ti -1c
.RI "bool \fBshowPlayPanel\fP"
.br
.ti -1c
.RI "bool \fBshowStatusBar\fP"
.br
.ti -1c
.RI "bool \fBuseAlsaAudio\fP"
.br
.ti -1c
.RI "bool \fBuseJackAudio\fP"
.br
.ti -1c
.RI "bool \fBusePortaudioAudio\fP"
.br
.ti -1c
.RI "bool \fBusePulseAudio\fP"
.br
.ti -1c
.RI "bool \fBuseJackMidi\fP"
.br
.ti -1c
.RI "bool \fBuseJackTransport\fP"
.br
.ti -1c
.RI "bool \fBjackTimebaseMaster\fP"
.br
.ti -1c
.RI "bool \fBrememberLastConnections\fP"
.br
.ti -1c
.RI "QString \fBalsaDevice\fP"
.br
.ti -1c
.RI "int \fBalsaSampleRate\fP"
.br
.ti -1c
.RI "int \fBalsaPeriodSize\fP"
.br
.ti -1c
.RI "int \fBalsaFragments\fP"
.br
.ti -1c
.RI "int \fBportaudioDevice\fP"
.br
.ti -1c
.RI "QString \fBportMidiInput\fP"
.br
.ti -1c
.RI "QString \fBportMidiOutput\fP"
.br
.ti -1c
.RI "int \fBportMidiInputBufferCount\fP"
.br
.ti -1c
.RI "int \fBportMidiOutputBufferCount\fP"
.br
.ti -1c
.RI "int \fBportMidiOutputLatencyMilliseconds\fP"
.br
.ti -1c
.RI "bool \fBantialiasedDrawing\fP"
.br
.ti -1c
.RI "SessionStart \fBsessionStart\fP"
.br
.ti -1c
.RI "QString \fBstartScore\fP"
.br
.ti -1c
.RI "QString \fBdefaultStyleFile\fP"
.br
.ti -1c
.RI "bool \fBshowSplashScreen\fP"
.br
.ti -1c
.RI "bool \fBshowStartcenter\fP"
.br
.ti -1c
.RI "bool \fBuseMidiRemote\fP"
.br
.ti -1c
.RI "\fBMidiRemote\fP \fBmidiRemote\fP [MIDI_REMOTES]"
.br
.ti -1c
.RI "bool \fBadvanceOnRelease\fP"
.br
.ti -1c
.RI "bool \fBmidiExpandRepeats\fP"
.br
.ti -1c
.RI "bool \fBmidiExportRPNs\fP"
.br
.ti -1c
.RI "QString \fBinstrumentList1\fP"
.br
.ti -1c
.RI "QString \fBinstrumentList2\fP"
.br
.ti -1c
.RI "bool \fBmusicxmlImportLayout\fP"
.br
.ti -1c
.RI "bool \fBmusicxmlImportBreaks\fP"
.br
.ti -1c
.RI "bool \fBmusicxmlExportLayout\fP"
.br
.ti -1c
.RI "MusicxmlExportBreaks \fBmusicxmlExportBreaks\fP"
.br
.ti -1c
.RI "bool \fBalternateNoteEntryMethod\fP"
.br
.ti -1c
.RI "int \fBproximity\fP"
.br
.ti -1c
.RI "bool \fBautoSave\fP"
.br
.ti -1c
.RI "int \fBautoSaveTime\fP"
.br
.ti -1c
.RI "double \fBpngResolution\fP"
.br
.ti -1c
.RI "bool \fBpngTransparent\fP"
.br
.ti -1c
.RI "QString \fBlanguage\fP"
.br
.ti -1c
.RI "double \fBmag\fP"
.br
.ti -1c
.RI "bool \fBshowMidiControls\fP"
.br
.ti -1c
.RI "bool \fBcheckUpdateStartup\fP"
.br
.ti -1c
.RI "bool \fBfollowSong\fP"
.br
.ti -1c
.RI "QString \fBimportCharsetOve\fP"
.br
.ti -1c
.RI "QString \fBimportCharsetGP\fP"
.br
.ti -1c
.RI "QString \fBimportStyleFile\fP"
.br
.ti -1c
.RI "int \fBshortestNote\fP"
.br
.ti -1c
.RI "\fBMidiOperations::Data\fP \fBmidiImportOperations\fP"
.br
.ti -1c
.RI "bool \fBuseOsc\fP"
.br
.ti -1c
.RI "int \fBoscPort\fP"
.br
.ti -1c
.RI "bool \fBsinglePalette\fP"
.br
.ti -1c
.RI "MuseScoreStyleType \fBglobalStyle\fP"
.br
.ti -1c
.RI "bool \fBanimations\fP"
.br
.ti -1c
.RI "QString \fBmyScoresPath\fP"
.br
.ti -1c
.RI "QString \fBmyStylesPath\fP"
.br
.ti -1c
.RI "QString \fBmyImagesPath\fP"
.br
.ti -1c
.RI "QString \fBmyTemplatesPath\fP"
.br
.ti -1c
.RI "QString \fBmyPluginsPath\fP"
.br
.ti -1c
.RI "QString \fBmySoundfontsPath\fP"
.br
.ti -1c
.RI "bool \fBnativeDialogs\fP"
.br
.ti -1c
.RI "int \fBexportAudioSampleRate\fP"
.br
.ti -1c
.RI "int \fBexportMp3BitRate\fP"
.br
.ti -1c
.RI "QString \fBworkspace\fP"
.br
.ti -1c
.RI "int \fBexportPdfDpi\fP"
.br
.ti -1c
.RI "bool \fBdirty\fP"
.br
.ti -1c
.RI "QList< \fBPluginDescription\fP > \fBpluginList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file preferences\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
