.TH "Ms::PaletteBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PaletteBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBchanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaletteBox\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBaddPalette\fP (\fBPalette\fP *)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &)"
.br
.ti -1c
.RI "bool \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "QList< \fBPalette\fP * > \fBpalettes\fP () const"
.br
.ti -1c
.RI "void \fBupdateWorkspaces\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file palettebox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
