.TH "Ms::PedalSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PedalSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::TextLineBaseSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPedalSegment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual \fBPedalSegment\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "\fBPedal\fP * \fBpedal\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPedal\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file pedal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
