.TH "Ms::Pattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Pattern
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPattern\fP (\fBScore\fP *s, SymId id, double spatium)"
.br
.ti -1c
.RI "\fBPattern\fP (\fBScore\fP *s, QString name)"
.br
.ti -1c
.RI "\fBPattern\fP (QImage *, int, int, int, int)"
.br
.ti -1c
.RI "double \fBmatch\fP (const \fBPattern\fP *) const"
.br
.ti -1c
.RI "double \fBmatch\fP (const QImage *, int, int) const"
.br
.ti -1c
.RI "double \fBmatch\fP (const QImage *img, int col, int row, double bg_parm) const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "const QImage * \fBimage\fP () const"
.br
.ti -1c
.RI "int \fBw\fP () const"
.br
.ti -1c
.RI "int \fBh\fP () const"
.br
.ti -1c
.RI "bool \fBdot\fP (int x, int y) const"
.br
.ti -1c
.RI "SymId \fBid\fP () const"
.br
.ti -1c
.RI "void \fBsetId\fP (SymId val)"
.br
.ti -1c
.RI "const QPoint & \fBbase\fP () const"
.br
.ti -1c
.RI "void \fBsetBase\fP (const QPoint &v)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QImage \fB_image\fP"
.br
.ti -1c
.RI "SymId \fB_id\fP"
.br
.ti -1c
.RI "QPoint \fB_base\fP"
.br
.ti -1c
.RI "\fBScore\fP * \fB_score\fP"
.br
.ti -1c
.RI "float ** \fBmodel\fP"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcols\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file pattern\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
