.TH "Ms::PitchValue" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PitchValue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPitchValue\fP (int a, int b, bool c=false)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPitchValue\fP &pv) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtime\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "bool \fBvibrato\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file pitchvalue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
