.TH "Ms::PartListItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PartListItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTreeWidgetItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartListItem\fP (\fBPart\fP *p, QTreeWidget *lv)"
.br
.ti -1c
.RI "\fBPartListItem\fP (const \fBInstrumentTemplate\fP *i, QTreeWidget *lv)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool val)"
.br
.ti -1c
.RI "void \fBupdateClefs\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ListItemOp \fBop\fP"
.br
.ti -1c
.RI "\fBPart\fP * \fBpart\fP"
.br
.ti -1c
.RI "const \fBInstrumentTemplate\fP * \fBit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file instrwidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
