.TH "Ms::Pareq" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Pareq
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetfsamp\fP (float fsamp)"
.br
.ti -1c
.RI "void \fBsetparam\fP (float f, float g)"
.br
.ti -1c
.RI "void \fBset_gn\fP (float g)"
.br
.ti -1c
.RI "float \fBgn\fP () const"
.br
.ti -1c
.RI "void \fBset_fr\fP (float f)"
.br
.ti -1c
.RI "float \fBfr\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBprepare\fP (int nsamp)"
.br
.ti -1c
.RI "void \fBprocess\fP (int nsamp, float *data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file zita\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
