.TH "Ms::PluginDescription" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PluginDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "QString \fBversion\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.ti -1c
.RI "bool \fBload\fP"
.br
.ti -1c
.RI "\fBShortcut\fP \fBshortcut\fP"
.br
.ti -1c
.RI "QString \fBmenuPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file preferences\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
