.TH "Ms::PositionCursor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PositionCursor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPositionCursor\fP (\fBScoreView\fP *sv)"
.br
.ti -1c
.RI "void \fBsetType\fP (CursorType t)"
.br
.ti -1c
.RI "QRectF \fBrect\fP () const"
.br
.ti -1c
.RI "void \fBsetRect\fP (const QRectF &r)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool val)"
.br
.ti -1c
.RI "QColor \fBcolor\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (const QColor &c)"
.br
.ti -1c
.RI "int \fBtick\fP () const"
.br
.ti -1c
.RI "void \fBsetTick\fP (int val)"
.br
.ti -1c
.RI "void \fBupdate\fP (QWidget *)"
.br
.ti -1c
.RI "void \fBmove\fP (int tick)"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *)"
.br
.ti -1c
.RI "QRectF \fBbbox\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file textcursor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
