.TH "Ms::PaletteCell" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PaletteCell
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBelement\fP { 0 }"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBtag\fP"
.br
.ti -1c
.RI "bool \fBdrawStaff\fP { false }"
.br
.ti -1c
.RI "double \fBx\fP { 0\&.0 }"
.br
.ti -1c
.RI "double \fBy\fP { 0\&.0 }"
.br
.ti -1c
.RI "double \fBxoffset\fP { 0\&.0 }"
.br
.ti -1c
.RI "double \fByoffset\fP { 0\&.0 }"
.br
.ti -1c
.RI "qreal \fBmag\fP { 1\&.0 }"
.br
.ti -1c
.RI "bool \fBreadOnly\fP { false }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file palette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
