.TH "Ms::Port" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Port
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort\fP (unsigned char client, unsigned char port)"
.br
.ti -1c
.RI "void \fBsetZero\fP ()"
.br
.ti -1c
.RI "bool \fBisZero\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPort\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPort\fP &p) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "unsigned char \fBalsaPort\fP () const"
.br
.ti -1c
.RI "unsigned char \fBalsaClient\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMidiDriver\fP"
.br
.ti -1c
.RI "class \fBAlsaMidiDriver\fP"
.br
.ti -1c
.RI "class \fBPortMidiDriver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file mididriver\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
