.TH "Ms::PaletteScrollArea" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PaletteScrollArea
.SH SYNOPSIS
.br
.PP
.PP
Inherits QScrollArea\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaletteScrollArea\fP (\fBPalette\fP *w, QWidget *parent=0)"
.br
.ti -1c
.RI "bool \fBrestrictHeight\fP () const"
.br
.ti -1c
.RI "void \fBsetRestrictHeight\fP (bool val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file palette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
