.TH "Ms::PianoTools" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PianoTools
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBkeyPressed\fP (int pitch, bool chord, int vel)"
.br
.ti -1c
.RI "void \fBkeyReleased\fP (int pitch, bool chord, int vel)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPianoTools\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBpressPitch\fP (int pitch)"
.br
.ti -1c
.RI "void \fBreleasePitch\fP (int pitch)"
.br
.ti -1c
.RI "void \fBheartBeat\fP (QList< const \fBNote\fP *> notes)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file pianotools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
