.TH "Ms::PulseAudio" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PulseAudio
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Driver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPulseAudio\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP (bool hot=false)"
.br
.ti -1c
.RI "virtual bool \fBstart\fP (bool hotPlug=false)"
.br
.ti -1c
.RI "virtual bool \fBstop\fP ()"
.br
.ti -1c
.RI "virtual Transport \fBgetState\fP () override"
.br
.ti -1c
.RI "virtual int \fBsampleRate\fP () const"
.br
.ti -1c
.RI "virtual void \fBstopTransport\fP ()"
.br
.ti -1c
.RI "virtual void \fBstartTransport\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 27 of file pulseaudio\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
