.TH "Ms::PaletteBoxButton" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PaletteBoxButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits QToolButton\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBshowPalette\fP (bool)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBpaletteCmd\fP (PaletteCommand, int)"
.br
.ti -1c
.RI "void \fBcloseAll\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaletteBoxButton\fP (\fBPalette\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetId\fP (int v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file paletteBoxButton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
