.TH "Ms::PianorollEditor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PianorollEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow, and \fBMs::MuseScoreView\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBchangeSelection\fP (SelState)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPianorollEditor\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetStaff\fP (\fBStaff\fP *staff)"
.br
.ti -1c
.RI "void \fBheartBeat\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "virtual void \fBdataChanged\fP (const QRectF &)"
.br
.ti -1c
.RI "virtual void \fBupdateAll\fP ()"
.br
.ti -1c
.RI "virtual void \fBadjustCanvasPosition\fP (const \fBElement\fP *, bool)"
.br
.ti -1c
.RI "virtual void \fBremoveScore\fP ()"
.br
.ti -1c
.RI "virtual void \fBchangeEditElement\fP (\fBElement\fP *)"
.br
.ti -1c
.RI "virtual QCursor \fBcursor\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetCursor\fP (const QCursor &)"
.br
.ti -1c
.RI "virtual int \fBgripCount\fP () const"
.br
.ti -1c
.RI "virtual const QRectF & \fBgetGrip\fP (Grip) const"
.br
.ti -1c
.RI "virtual const QTransform & \fBmatrix\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetDropRectangle\fP (const QRectF &)"
.br
.ti -1c
.RI "virtual void \fBcmdAddSlur\fP (\fBNote\fP *, \fBNote\fP *)"
.br
.ti -1c
.RI "virtual void \fBcmdAddHairpin\fP (bool)"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP ()"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBElement\fP *, Grip)"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBelementNear\fP (QPointF)"
.br
.ti -1c
.RI "virtual void \fBdrawBackground\fP (QPainter *, const QRectF &) const"
.br
.ti -1c
.RI "void \fBsetLocator\fP (POS pos, int tick)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 40 of file pianoroll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
