.TH "Ms::PortMidiDriver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PortMidiDriver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::MidiDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPortMidiDriver\fP (\fBSeq\fP *)"
.br
.ti -1c
.RI "virtual bool \fBinit\fP ()"
.br
.ti -1c
.RI "virtual \fBPort\fP \fBregisterOutPort\fP (const QString &name)"
.br
.ti -1c
.RI "virtual \fBPort\fP \fBregisterInPort\fP (const QString &name)"
.br
.ti -1c
.RI "virtual void \fBgetInputPollFd\fP (struct pollfd **, int *n)"
.br
.ti -1c
.RI "virtual void \fBgetOutputPollFd\fP (struct pollfd **, int *n)"
.br
.ti -1c
.RI "virtual void \fBread\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (const \fBEvent\fP &)"
.br
.ti -1c
.RI "QStringList \fBdeviceInList\fP () const"
.br
.ti -1c
.RI "QStringList \fBdeviceOutList\fP () const"
.br
.ti -1c
.RI "int \fBgetDeviceIn\fP (const QString &interfaceAndName)"
.br
.ti -1c
.RI "int \fBgetDeviceOut\fP (const QString &interfaceAndName)"
.br
.ti -1c
.RI "PmStream * \fBgetInputStream\fP ()"
.br
.ti -1c
.RI "PmStream * \fBgetOutputStream\fP ()"
.br
.ti -1c
.RI "bool \fBcanOutput\fP ()"
.br
.ti -1c
.RI "bool \fBisSameCoreMidiIacBus\fP (const QString &inInterfaceAndName, const QString &outInterfaceAndName)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 41 of file pm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
