.TH "Ms::Palette" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Palette
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBboxClicked\fP (int)"
.br
.ti -1c
.RI "void \fBchanged\fP ()"
.br
.ti -1c
.RI "void \fBdisplayMore\fP (const QString &paletteName)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPalette\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBPaletteCell\fP * \fBappend\fP (\fBElement\fP *, const QString &name, QString tag=QString(), qreal mag=1\&.0)"
.br
.ti -1c
.RI "\fBPaletteCell\fP * \fBadd\fP (int idx, \fBElement\fP *, const QString &name, const QString tag=QString(), qreal mag=1\&.0)"
.br
.ti -1c
.RI "void \fBemitChanged\fP ()"
.br
.ti -1c
.RI "void \fBsetGrid\fP (int, int)"
.br
.ti -1c
.RI "\fBElement\fP * \fBelement\fP (int idx)"
.br
.ti -1c
.RI "void \fBsetDrawGrid\fP (bool val)"
.br
.ti -1c
.RI "bool \fBdrawGrid\fP () const"
.br
.ti -1c
.RI "bool \fBread\fP (const QString &path)"
.br
.ti -1c
.RI "void \fBwrite\fP (const QString &path)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "bool \fBread\fP (QFile *)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsetSelectable\fP (bool val)"
.br
.ti -1c
.RI "bool \fBselectable\fP () const"
.br
.ti -1c
.RI "int \fBgetSelectedIdx\fP () const"
.br
.ti -1c
.RI "void \fBsetSelected\fP (int idx)"
.br
.ti -1c
.RI "bool \fBreadOnly\fP () const"
.br
.ti -1c
.RI "void \fBsetReadOnly\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetDisableDoubleClick\fP (bool val)"
.br
.ti -1c
.RI "bool \fBsystemPalette\fP () const"
.br
.ti -1c
.RI "void \fBsetSystemPalette\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetMag\fP (qreal val)"
.br
.ti -1c
.RI "qreal \fBmag\fP () const"
.br
.ti -1c
.RI "void \fBsetYOffset\fP (qreal val)"
.br
.ti -1c
.RI "qreal \fByOffset\fP () const"
.br
.ti -1c
.RI "int \fBcolumns\fP () const"
.br
.ti -1c
.RI "int \fBrows\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "\fBPaletteCell\fP * \fBcellAt\fP (int index) const"
.br
.ti -1c
.RI "void \fBsetCellReadOnly\fP (int c, bool v)"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &s)"
.br
.ti -1c
.RI "int \fBgridWidth\fP () const"
.br
.ti -1c
.RI "int \fBgridHeight\fP () const"
.br
.ti -1c
.RI "bool \fBmoreElements\fP () const"
.br
.ti -1c
.RI "void \fBsetMoreElements\fP (bool val)"
.br
.ti -1c
.RI "bool \fBfilter\fP (const QString &text)"
.br
.RI "return true if all filtered "
.ti -1c
.RI "void \fBsetShowContextMenu\fP (bool val)"
.br
.ti -1c
.RI "virtual int \fBheightForWidth\fP (int) const"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file palette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
