.TH "Ms::PlayPanel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PlayPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::PlayPanelBase\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetGain\fP (float)"
.br
.ti -1c
.RI "void \fBsetPos\fP (int)"
.br
.ti -1c
.RI "void \fBheartBeat\fP (int rpos, int apos, int samples)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrelTempoChanged\fP (double)"
.br
.ti -1c
.RI "void \fBmetronomeGainChanged\fP (float)"
.br
.ti -1c
.RI "void \fBposChange\fP (int)"
.br
.ti -1c
.RI "void \fBgainChange\fP (float)"
.br
.ti -1c
.RI "void \fBclosed\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayPanel\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetTempo\fP (double)"
.br
.ti -1c
.RI "void \fBsetRelTempo\fP (qreal)"
.br
.ti -1c
.RI "void \fBsetEndpos\fP (int)"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "bool \fBisTempoSliderPressed\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file playpanel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
