.TH "Ms::PianoKeyItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PianoKeyItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QGraphicsPathItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPianoKeyItem\fP (\fBHPiano\fP *, int p)"
.br
.ti -1c
.RI "void \fBsetType\fP (int val)"
.br
.ti -1c
.RI "int \fBpitch\fP ()"
.br
.ti -1c
.RI "void \fBsetPressed\fP (bool p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file pianotools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
