.TH "Ms::ParsedChord" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ParsedChord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBparse\fP (const QString &, const \fBChordList\fP *, bool syntaxOnly=false, bool preferMinor=false)"
.br
.ti -1c
.RI "QString \fBfromXml\fP (const QString &, const QString &, const QString &, const QString &, const QList< \fBHDegree\fP > &, const \fBChordList\fP *)"
.br
.ti -1c
.RI "const QList< \fBRenderAction\fP > & \fBrenderList\fP (const \fBChordList\fP *)"
.br
.ti -1c
.RI "bool \fBparseable\fP () const"
.br
.ti -1c
.RI "bool \fBunderstandable\fP () const"
.br
.ti -1c
.RI "const QString & \fBname\fP () const"
.br
.ti -1c
.RI "const QString & \fBquality\fP () const"
.br
.ti -1c
.RI "const QString & \fBextension\fP () const"
.br
.ti -1c
.RI "const QString & \fBmodifiers\fP () const"
.br
.ti -1c
.RI "const QString & \fBxmlKind\fP () const"
.br
.ti -1c
.RI "const QString & \fBxmlText\fP () const"
.br
.ti -1c
.RI "const QString & \fBxmlSymbols\fP () const"
.br
.ti -1c
.RI "const QString & \fBxmlParens\fP () const"
.br
.ti -1c
.RI "const QStringList & \fBxmlDegrees\fP () const"
.br
.ti -1c
.RI "int \fBkeys\fP () const"
.br
.ti -1c
.RI "const QString & \fBhandle\fP () const"
.br
.ti -1c
.RI "\fBoperator QString\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBParsedChord\fP &c) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBParsedChord\fP &c) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
