.TH "Ms::PreferenceDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::PreferenceDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::AbstractDialog\fP, and \fBUi::PrefsDialogBase\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBpreferencesChanged\fP ()"
.br
.ti -1c
.RI "void \fBmixerPreferencesChanged\fP (bool showMidiControls)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreferenceDialog\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetPreferences\fP (const \fBPreferences\fP &p)"
.br
.ti -1c
.RI "void \fBupdateRemote\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file prefsdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
