.TH "Ms::Quantize::QuantData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Quantize::QuantData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::multimap< \fBReducedFraction\fP, \fBMidiChord\fP >::const_iterator \fBchord\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBquant\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBquantForLen\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBchordRangeStart\fP"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBchordRangeEnd\fP"
.br
.ti -1c
.RI "bool \fBcanMergeWithPrev\fP = false"
.br
.ti -1c
.RI "int \fBmetricalLevelForLen\fP"
.br
.ti -1c
.RI "std::vector< \fBQuantPos\fP > \fBpositions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 545 of file importmidi_quant\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
