.TH "Ms::QmlEdit" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::QmlEdit
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPlainTextEdit\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColorComponent\fP { \fBNormal\fP, \fBComment\fP, \fBNumber\fP, \fBString\fP, \fBOperator\fP, \fBIdentifier\fP, \fBKeyword\fP, \fBBuiltIn\fP, \fBMarker\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQmlEdit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBlineNumberAreaPaintEvent\fP (QPaintEvent *)"
.br
.ti -1c
.RI "int \fBlineNumberAreaWidth\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file qmledit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
