.TH "Ms::Quantize::QuantInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Quantize::QuantInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReducedFraction\fP \fBonTime\fP"
.br
.ti -1c
.RI "double \fBpenalty\fP = 0\&.0"
.br
.ti -1c
.RI "std::multimap< \fBReducedFraction\fP, \fBMidiChord\fP >::const_iterator \fBchord\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 994 of file importmidi_quant\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
