.TH "Ms::QmlListAccess< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::QmlListAccess< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits QQmlListProperty< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQmlListAccess\fP (QObject *obj, std::vector< T *> &container)"
.br
.ti -1c
.RI "\fBQmlListAccess\fP (QObject *obj, QVector< T *> &container)"
.br
.ti -1c
.RI "\fBQmlListAccess\fP (QObject *obj, QList< T *> &container)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBstdVectorCount\fP (QQmlListProperty< T > *l)"
.br
.ti -1c
.RI "static T * \fBstdVectorAt\fP (QQmlListProperty< T > *l, int i)"
.br
.ti -1c
.RI "static int \fBqVectorCount\fP (QQmlListProperty< T > *l)"
.br
.ti -1c
.RI "static T * \fBqVectorAt\fP (QQmlListProperty< T > *l, int i)"
.br
.ti -1c
.RI "static int \fBqListCount\fP (QQmlListProperty< T > *l)"
.br
.ti -1c
.RI "static T * \fBqListAt\fP (QQmlListProperty< T > *l, int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Ms::QmlListAccess< T >"

.PP
Definition at line 517 of file mscore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
