.TH "Ms::RemoveMeasures" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RemoveMeasures
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::InsertRemoveMeasures\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoveMeasures\fP (\fBMeasureBase\fP *m1, \fBMeasureBase\fP *m2)"
.br
.ti -1c
.RI "virtual void \fBundo\fP (\fBEditData\fP *) override"
.br
.ti -1c
.RI "virtual void \fBredo\fP (\fBEditData\fP *) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 707 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
