.TH "Ms::RepeatSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RepeatSegment
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtick\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fButick\fP"
.br
.ti -1c
.RI "qreal \fButime\fP"
.br
.ti -1c
.RI "qreal \fBtimeOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file repeatlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
