.TH "Ms::RepeatMeasure" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RepeatMeasure
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Rest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRepeatMeasure\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBRepeatMeasure\fP & \fBoperator=\fP (const \fBRepeatMeasure\fP &)=delete"
.br
.ti -1c
.RI "virtual \fBRepeatMeasure\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBlinkedClone\fP () override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual \fBFraction\fP \fBduration\fP () const override"
.br
.ti -1c
.RI "\fBFraction\fP \fBactualDuration\fP () const"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file repeat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
