.TH "Ms::ResourceManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ResourceManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::Resource\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdownload\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResourceManager\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBdisplayLanguages\fP ()"
.br
.ti -1c
.RI "void \fBdisplayPlugins\fP ()"
.br
.ti -1c
.RI "bool \fBverifyFile\fP (QString path, QString hash)"
.br
.ti -1c
.RI "bool \fBverifyLanguageFile\fP (QString filename, QString hash)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArray \fBtxt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file resourceManager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
