.TH "Ms::RadonInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RadonInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRadonInfo\fP (ulong w, ulong h)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "ushort \fBgetCell\fP (int x, int y) const"
.br
.ti -1c
.RI "void \fBsetCell\fP (int x, int y, ushort value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ushort * \fBcells\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file skew\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
