.TH "Ms::RepeatList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RepeatList
.SH SYNOPSIS
.br
.PP
.PP
Inherits QList< RepeatSegment *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRepeatList\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "void \fBunwind\fP ()"
.br
.ti -1c
.RI "int \fButick2tick\fP (int tick) const"
.br
.ti -1c
.RI "int \fBtick2utick\fP (int tick) const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "int \fButime2utick\fP (qreal) const"
.br
.ti -1c
.RI "qreal \fButick2utime\fP (int) const"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "int \fBticks\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file repeatlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
