.TH "Ms::RehearsalMark" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RehearsalMark
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SystemText\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRehearsalMark\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "virtual \fBRehearsalMark\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file rehearsalmark\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
