.TH "Ms::RenderAction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::RenderAction
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBRenderActionType\fP : char { \fBSET\fP, \fBMOVE\fP, \fBPUSH\fP, \fBPOP\fP, \fBNOTE\fP, \fBACCIDENTAL\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderAction\fP (RenderActionType t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RenderActionType \fBtype\fP"
.br
.ti -1c
.RI "qreal \fBmovex\fP"
.br
.ti -1c
.RI "qreal \fBmovey\fP"
.br
.ti -1c
.RI "QString \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file chordlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
