.TH "Ms::Revision" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Revision
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBsetParent\fP (\fBRevision\fP *r)"
.br
.ti -1c
.RI "\fBRevision\fP * \fBparent\fP () const"
.br
.ti -1c
.RI "const QList< \fBRevision\fP * > & \fBbranches\fP () const"
.br
.ti -1c
.RI "void \fBsetId\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBsetDiff\fP (const QString &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file revisions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
