.TH "Ms::Ruler" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Ruler
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetXpos\fP (int)"
.br
.ti -1c
.RI "void \fBsetMag\fP (double xmag, double ymag)"
.br
.ti -1c
.RI "void \fBsetPos\fP (const \fBPos\fP &)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBposChanged\fP (const \fBPos\fP &)"
.br
.ti -1c
.RI "void \fBlocatorMoved\fP (int idx, const \fBPos\fP &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRuler\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *, \fBPos\fP *locator)"
.br
.ti -1c
.RI "double \fBxmag\fP () const"
.br
.ti -1c
.RI "int \fBxpos\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file ruler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
