.TH "Ms::Revisions" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Revisions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBRevision\fP *)"
.br
.ti -1c
.RI "QString \fBgetRevision\fP (QString id)"
.br
.ti -1c
.RI "\fBRevision\fP * \fBtrunk\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file revisions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
