.TH "Ms::ReducedFraction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ReducedFraction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReducedFraction\fP (int z, int n)"
.br
.ti -1c
.RI "\fBReducedFraction\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "\fBFraction\fP \fBfraction\fP () const"
.br
.ti -1c
.RI "int \fBnumerator\fP () const"
.br
.ti -1c
.RI "int \fBdenominator\fP () const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBreduced\fP () const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBabsValue\fP () const"
.br
.ti -1c
.RI "double \fBtoDouble\fP () const"
.br
.ti -1c
.RI "int \fBticks\fP () const"
.br
.ti -1c
.RI "void \fBreduce\fP ()"
.br
.ti -1c
.RI "bool \fBisIdenticalTo\fP (const \fBReducedFraction\fP &f) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator+=\fP (const \fBReducedFraction\fP &)"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator\-=\fP (const \fBReducedFraction\fP &)"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator*=\fP (const \fBReducedFraction\fP &)"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator*=\fP (int)"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator/=\fP (const \fBReducedFraction\fP &)"
.br
.ti -1c
.RI "\fBReducedFraction\fP & \fBoperator/=\fP (int)"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator+\fP (const \fBReducedFraction\fP &v) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator\-\fP (const \fBReducedFraction\fP &v) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator*\fP (const \fBReducedFraction\fP &v) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator*\fP (int v) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator/\fP (const \fBReducedFraction\fP &v) const"
.br
.ti -1c
.RI "\fBReducedFraction\fP \fBoperator/\fP (int v) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBReducedFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBReducedFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBReducedFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBReducedFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBReducedFraction\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBReducedFraction\fP &) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBReducedFraction\fP \fBfromTicks\fP (int ticks)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file importmidi_fraction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
