.TH "Ms::SimpleTextObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SimpleTextObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicDrawObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleTextObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.ti -1c
.RI "QFont \fBfont\fP () const"
.br
.ti -1c
.RI "QPointF \fBpos\fP () const"
.br
.ti -1c
.RI "unsigned char \fBtextalign\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 469 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
