.TH "Ms::ScoreAccessibility" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreAccessibility
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateAccessibilityInfo\fP ()"
.br
.ti -1c
.RI "void \fBclearAccessibilityInfo\fP ()"
.br
.ti -1c
.RI "void \fBcurrentInfoChanged\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcreateInstance\fP (QMainWindow *statusBar)"
.br
.ti -1c
.RI "static \fBScoreAccessibility\fP * \fBinstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file scoreaccessibility\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
