.TH "Ms::ScorePreview" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScorePreview
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::ScorePreview\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetScore\fP (const QString &)"
.br
.ti -1c
.RI "void \fBsetScore\fP (const \fBScoreInfo\fP &)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdoubleClicked\fP (QString)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScorePreview\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file scorePreview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
