.TH "Ms::SpannerMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SpannerMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits multimap< int, Spanner *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const std::vector< ::\fBInterval\fP< \fBSpanner\fP * > > & \fBfindContained\fP (int start, int stop)"
.br
.ti -1c
.RI "const std::vector< ::\fBInterval\fP< \fBSpanner\fP * > > & \fBfindOverlapping\fP (int start, int stop)"
.br
.ti -1c
.RI "const std::multimap< int, \fBSpanner\fP * > & \fBmap\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBSpanner\fP * >::const_reverse_iterator \fBcrbegin\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBSpanner\fP * >::const_reverse_iterator \fBcrend\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBSpanner\fP * >::const_iterator \fBcbegin\fP () const"
.br
.ti -1c
.RI "std::multimap< int, \fBSpanner\fP * >::const_iterator \fBcend\fP () const"
.br
.ti -1c
.RI "void \fBaddSpanner\fP (\fBSpanner\fP *s)"
.br
.ti -1c
.RI "bool \fBremoveSpanner\fP (\fBSpanner\fP *s)"
.br
.ti -1c
.RI "void \fBupdate\fP () const"
.br
.ti -1c
.RI "void \fBsetDirty\fP () const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file spannermap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
