.TH "Ms::Spatium" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Spatium
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpatium\fP (qreal v)"
.br
.ti -1c
.RI "constexpr qreal \fBval\fP () const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSpatium\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSpatium\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSpatium\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSpatium\fP &a) const"
.br
.ti -1c
.RI "bool \fBisZero\fP () const"
.br
.ti -1c
.RI "\fBSpatium\fP & \fBoperator+=\fP (const \fBSpatium\fP &a)"
.br
.ti -1c
.RI "\fBSpatium\fP & \fBoperator\-=\fP (const \fBSpatium\fP &a)"
.br
.ti -1c
.RI "\fBSpatium\fP & \fBoperator/=\fP (qreal d)"
.br
.ti -1c
.RI "qreal \fBoperator/\fP (const \fBSpatium\fP &b)"
.br
.ti -1c
.RI "\fBSpatium\fP & \fBoperator*=\fP (int d)"
.br
.ti -1c
.RI "\fBSpatium\fP & \fBoperator*=\fP (qreal d)"
.br
.ti -1c
.RI "\fBSpatium\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBoperator QVariant\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBtoDouble\fP (const \fBSpatium\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file spatium\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
