.TH "Ms::SectionBreakProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SectionBreakProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::SectionBreakProperties\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionBreakProperties\fP (\fBLayoutBreak\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "double \fBpause\fP () const"
.br
.ti -1c
.RI "bool \fBstartWithLongNames\fP () const"
.br
.ti -1c
.RI "bool \fBstartWithMeasureOne\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file sectionbreakprop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
