.TH "Ms::ShadowNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ShadowNote
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shadownote\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShadowNote\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "virtual \fBShadowNote\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "int \fBline\fP () const"
.br
.ti -1c
.RI "void \fBsetLine\fP (int n)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "void \fBsetState\fP (SymId noteSymbol, int voice, \fBTDuration\fP duration, bool rest=false)"
.br
.ti -1c
.RI "SymId \fBgetNoteFlag\fP () const"
.br
.ti -1c
.RI "bool \fBcomputeUp\fP () const"
.br
.ti -1c
.RI "SymId \fBnotehead\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Graphic representation of a shadow note, which shows the note insert position in note entry mode\&. 
.PP
Definition at line 30 of file shadownote\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
