.TH "Ms::StaffText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StaffText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Text\fP\&.
.PP
Inherited by \fBMs::SystemText\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaffText\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "\fBStaffText\fP (SubStyle, \fBScore\fP *=0)"
.br
.ti -1c
.RI "virtual \fBStaffText\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual bool \fBreadProperties\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual int \fBsubtype\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QString \fBsubtypeName\fP () const"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "QString \fBchannelName\fP (int voice) const"
.br
.ti -1c
.RI "void \fBsetChannelName\fP (int v, const QString &s)"
.br
.ti -1c
.RI "void \fBsetSwingParameters\fP (int unit, int ratio)"
.br
.ti -1c
.RI "const QList< \fBChannelActions\fP > * \fBchannelActions\fP () const"
.br
.ti -1c
.RI "QList< \fBChannelActions\fP > * \fBchannelActions\fP ()"
.br
.ti -1c
.RI "const \fBSwingParameters\fP * \fBswingParameters\fP () const"
.br
.ti -1c
.RI "void \fBclearAeolusStops\fP ()"
.br
.ti -1c
.RI "void \fBsetAeolusStop\fP (int group, int idx, bool val)"
.br
.ti -1c
.RI "bool \fBgetAeolusStop\fP (int group, int idx) const"
.br
.ti -1c
.RI "void \fBsetSetAeolusStops\fP (bool val)"
.br
.ti -1c
.RI "void \fBsetSwing\fP (bool checked)"
.br
.ti -1c
.RI "bool \fBsetAeolusStops\fP () const"
.br
.ti -1c
.RI "bool \fBswing\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwriteProperties\fP (\fBXmlWriter\fP &xml) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 35 of file stafftext\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
