.TH "Ms::SegmentList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SegmentList
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconst_iterator\fP"
.br
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBcheck\fP ()"
.br
.ti -1c
.RI "\fBSegmentList\fP \fBclone\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBfirst\fP () const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBfirst\fP (SegmentType) const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBlast\fP () const"
.br
.ti -1c
.RI "\fBSegment\fP * \fBfirstCRSegment\fP () const"
.br
.ti -1c
.RI "void \fBremove\fP (\fBSegment\fP *)"
.br
.ti -1c
.RI "void \fBpush_back\fP (\fBSegment\fP *)"
.br
.ti -1c
.RI "void \fBpush_front\fP (\fBSegment\fP *)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBSegment\fP *e, \fBSegment\fP *el)"
.br
.RI "Insert \fBSegment\fP \fIe\fP before \fBSegment\fP \fIel\fP\&. "
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file segmentlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
