.TH "Ms::Spacer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Spacer \- Vertical spacer element to adjust the distance of staves\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spacer\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpacer\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBSpacer\fP (const \fBSpacer\fP &)"
.br
.ti -1c
.RI "virtual \fBSpacer\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "SpacerType \fBspacerType\fP () const"
.br
.ti -1c
.RI "void \fBsetSpacerType\fP (SpacerType t)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual bool \fBisEditable\fP () const"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBeditDrag\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBupdateGrips\fP (\fBEditData\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBspatiumChanged\fP (qreal, qreal)"
.br
.ti -1c
.RI "void \fBsetGap\fP (qreal sp)"
.br
.ti -1c
.RI "qreal \fBgap\fP () const"
.br
.ti -1c
.RI "QVariant \fBgetProperty\fP (P_ID propertyId) const"
.br
.ti -1c
.RI "bool \fBsetProperty\fP (P_ID propertyId, const QVariant &)"
.br
.ti -1c
.RI "QVariant \fBpropertyDefault\fP (P_ID id) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Vertical spacer element to adjust the distance of staves\&. 
.PP
Definition at line 33 of file spacer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
