.TH "Ms::SynthesizerGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SynthesizerGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBAeolusGui\fP, \fBFluidGui\fP, and \fBZerberusGui\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsynthesizerChanged\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsfChanged\fP ()"
.br
.ti -1c
.RI "void \fBvalueChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSynthesizerGui\fP (\fBSynthesizer\fP *)"
.br
.ti -1c
.RI "\fBSynthesizer\fP * \fBsynthesizer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file synthesizergui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
