.TH "Ms::ScoreTab" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreTab
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateExcerpts\fP ()"
.br
.ti -1c
.RI "void \fBsetExcerpt\fP (int)"
.br
.ti -1c
.RI "void \fBsetCurrent\fP (int)"
.br
.ti -1c
.RI "void \fBtabMoved\fP (int, int)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcurrentScoreViewChanged\fP (\fBScoreView\fP *)"
.br
.ti -1c
.RI "void \fBtabCloseRequested\fP (int)"
.br
.ti -1c
.RI "void \fBactionTriggered\fP (QAction *)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoreTab\fP (QList< \fBMasterScore\fP *> *, QWidget *parent=0)"
.br
.ti -1c
.RI "QTabBar * \fBgetTab\fP () const"
.br
.ti -1c
.RI "void \fBinsertTab\fP (\fBMasterScore\fP *)"
.br
.ti -1c
.RI "void \fBsetTabText\fP (int, const QString &)"
.br
.ti -1c
.RI "int \fBcurrentIndex\fP () const"
.br
.ti -1c
.RI "void \fBsetCurrentIndex\fP (int)"
.br
.ti -1c
.RI "void \fBremoveTab\fP (int)"
.br
.ti -1c
.RI "int \fBcount\fP () const"
.br
.ti -1c
.RI "\fBScoreView\fP * \fBview\fP (int) const"
.br
.ti -1c
.RI "QSplitter * \fBviewSplitter\fP (int n) const"
.br
.ti -1c
.RI "\fBScoreView\fP * \fBview\fP () const"
.br
.ti -1c
.RI "bool \fBcontains\fP (\fBScoreView\fP *) const"
.br
.ti -1c
.RI "void \fBinitScoreView\fP (int idx, double mag, MagIdx magIdx, double xoffset, double yoffset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file scoretab\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
