.TH "Ms::ScoreBrowser" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreBrowser
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::ScoreBrowser\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBleave\fP ()"
.br
.ti -1c
.RI "void \fBscoreSelected\fP (QString)"
.br
.ti -1c
.RI "void \fBscoreActivated\fP (QString)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoreBrowser\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetScores\fP (QFileInfoList &)"
.br
.ti -1c
.RI "void \fBsetStripNumbers\fP (bool val)"
.br
.ti -1c
.RI "void \fBselectFirst\fP ()"
.br
.ti -1c
.RI "void \fBselectLast\fP ()"
.br
.ti -1c
.RI "void \fBsetBoldTitle\fP (bool bold)"
.br
.ti -1c
.RI "void \fBsetShowCustomCategory\fP (bool showCustomCategory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 48 of file scoreBrowser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
