.TH "Ms::SpannerSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SpannerSegment \- parent: \fBSystem\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spanner\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.PP
Inherited by \fBMs::LineSegment\fP, and \fBMs::SlurTieSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpannerSegment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBSpannerSegment\fP (const \fBSpannerSegment\fP &)"
.br
.ti -1c
.RI "virtual \fBSpannerSegment\fP * \fBclone\fP () const =0"
.br
.ti -1c
.RI "\fBSpanner\fP * \fBspanner\fP () const"
.br
.ti -1c
.RI "\fBSpanner\fP * \fBsetSpanner\fP (\fBSpanner\fP *val)"
.br
.ti -1c
.RI "void \fBsetSpannerSegmentType\fP (SpannerSegmentType s)"
.br
.ti -1c
.RI "SpannerSegmentType \fBspannerSegmentType\fP () const"
.br
.ti -1c
.RI "bool \fBisSingleType\fP () const"
.br
.ti -1c
.RI "bool \fBisBeginType\fP () const"
.br
.ti -1c
.RI "bool \fBisSingleBeginType\fP () const"
.br
.ti -1c
.RI "bool \fBisSingleEndType\fP () const"
.br
.ti -1c
.RI "bool \fBisMiddleType\fP () const"
.br
.ti -1c
.RI "bool \fBisEndType\fP () const"
.br
.ti -1c
.RI "void \fBsetSystem\fP (\fBSystem\fP *s)"
.br
.ti -1c
.RI "\fBSystem\fP * \fBsystem\fP () const"
.br
.ti -1c
.RI "const QPointF & \fBuserOff2\fP () const"
.br
.ti -1c
.RI "void \fBsetUserOff2\fP (const QPointF &o)"
.br
.ti -1c
.RI "void \fBsetUserXoffset2\fP (qreal x)"
.br
.ti -1c
.RI "qreal & \fBrUserXoffset2\fP ()"
.br
.ti -1c
.RI "qreal & \fBrUserYoffset2\fP ()"
.br
.ti -1c
.RI "void \fBsetPos2\fP (const QPointF &p)"
.br
.ti -1c
.RI "QPointF \fBpos2\fP () const"
.br
.ti -1c
.RI "const QPointF & \fBipos2\fP () const"
.br
.ti -1c
.RI "qreal & \fBrxpos2\fP ()"
.br
.ti -1c
.RI "qreal & \fBrypos2\fP ()"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBendEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual bool \fBisEditable\fP () const override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID id, const QVariant &v) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "void \fBreset\fP () override"
.br
.ti -1c
.RI "virtual void \fBsetSelected\fP (bool f) override"
.br
.ti -1c
.RI "virtual void \fBsetVisible\fP (bool f) override"
.br
.ti -1c
.RI "virtual void \fBsetColor\fP (const QColor &col) override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBnextElement\fP () override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBprevElement\fP () override"
.br
.ti -1c
.RI "virtual bool \fBisSpannerSegment\fP () const override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.ti -1c
.RI "virtual void \fBstyleChanged\fP () override"
.br
.ti -1c
.RI "virtual void \fBtriggerLayout\fP () const override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QPointF \fB_p2\fP"
.br
.ti -1c
.RI "QPointF \fB_userOff2\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
parent: \fBSystem\fP 
.PP
Definition at line 35 of file spanner\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
