.TH "Ms::SelectionWindow" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SelectionWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclosed\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectionWindow\fP (QWidget *parent=0, \fBScore\fP *score=0)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file selectionwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
