.TH "Ms::StaffTypeTemplates" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StaffTypeTemplates
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::StaffTypeTemplates\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaffTypeTemplates\fP (const \fBStaffType\fP &, QWidget *parent=0)"
.br
.ti -1c
.RI "\fBStaffType\fP * \fBstaffType\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file editstafftype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
