.TH "Ms::StaffListItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StaffListItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and QTreeWidgetItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaffListItem\fP (\fBPartListItem\fP *li)"
.br
.ti -1c
.RI "int \fBpartIdx\fP () const"
.br
.ti -1c
.RI "void \fBsetPartIdx\fP (int val)"
.br
.ti -1c
.RI "void \fBsetClefType\fP (const \fBClefTypeList\fP &val)"
.br
.ti -1c
.RI "const \fBClefTypeList\fP & \fBclefType\fP () const"
.br
.ti -1c
.RI "void \fBsetDefaultClefType\fP (const \fBClefTypeList\fP &val)"
.br
.ti -1c
.RI "const \fBClefTypeList\fP & \fBdefaultClefType\fP () const"
.br
.ti -1c
.RI "void \fBsetLinked\fP (bool val)"
.br
.ti -1c
.RI "bool \fBlinked\fP () const"
.br
.ti -1c
.RI "void \fBsetStaffType\fP (const \fBStaffType\fP *)"
.br
.ti -1c
.RI "void \fBsetStaffType\fP (int)"
.br
.ti -1c
.RI "const \fBStaffType\fP * \fBstaffType\fP () const"
.br
.ti -1c
.RI "int \fBstaffTypeIdx\fP () const"
.br
.ti -1c
.RI "void \fBinitStaffTypeCombo\fP (bool forceRecreate=false)"
.br
.ti -1c
.RI "QComboBox * \fBstaffTypeCombo\fP ()"
.br
.ti -1c
.RI "\fBStaff\fP * \fBstaff\fP () const"
.br
.ti -1c
.RI "void \fBsetStaff\fP (\fBStaff\fP *s)"
.br
.ti -1c
.RI "ListItemOp \fBop\fP () const"
.br
.ti -1c
.RI "void \fBsetOp\fP (ListItemOp v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file instrwidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
