.TH "Ms::SysStaff" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SysStaff \- One staff of a \fBSystem\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QRectF & \fBbbox\fP () const"
.br
.ti -1c
.RI "QRectF & \fBbbox\fP ()"
.br
.ti -1c
.RI "void \fBsetbbox\fP (const QRectF &r)"
.br
.ti -1c
.RI "qreal \fBy\fP () const"
.br
.ti -1c
.RI "void \fBsetYOff\fP (qreal offset)"
.br
.ti -1c
.RI "bool \fBshow\fP () const"
.br
.ti -1c
.RI "void \fBsetShow\fP (bool v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidx\fP { 0 }"
.br
.ti -1c
.RI "QList< \fBInstrumentName\fP * > \fBinstrumentNames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One staff of a \fBSystem\fP\&. 
.PP
Definition at line 46 of file system\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
