.TH "Ms::StyledPropertyListName" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StyledPropertyListName
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const std::vector< \fBStyledProperty\fP > * \fBspl\fP"
.br
.ti -1c
.RI "SubStyle \fBss\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1140 of file style\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
