.TH "Ms::SlurObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SlurObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicDrawObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlurObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBnEnd\fP"
.br
.ti -1c
.RI "unsigned char \fBnMid\fP"
.br
.ti -1c
.RI "unsigned char \fBnDotDist\fP"
.br
.ti -1c
.RI "unsigned char \fBnDotWidth\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 439 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
