.TH "Ms::StyleType" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StyleType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "StyleIdx \fBstyleIdx\fP () const"
.br
.ti -1c
.RI "int \fBidx\fP () const"
.br
.ti -1c
.RI "const char * \fBvalueType\fP () const"
.br
.ti -1c
.RI "const char * \fBname\fP () const"
.br
.ti -1c
.RI "const QVariant & \fBdefaultValue\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "StyleIdx \fB_idx\fP"
.br
.ti -1c
.RI "const char * \fB_name\fP"
.br
.ti -1c
.RI "QVariant \fB_defaultValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file style\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
