.TH "Ms::SynthControl" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SynthControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::SynthControl\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetGain\fP (float)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBgainChanged\fP (float)"
.br
.ti -1c
.RI "void \fBsoundFontChanged\fP ()"
.br
.ti -1c
.RI "void \fBclosed\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSynthControl\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetMeter\fP (float, float, float, float)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBsetScore\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "void \fBwriteSettings\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBretranslate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file synthcontrol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
