.TH "Ms::SearchComboBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SearchComboBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits QComboBox\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSearchType\fP { \fBSEARCH_MEASURE\fP, \fBSEARCH_PAGE\fP, \fBSEARCH_REHEARSAL_MARK\fP, \fBNO_SEARCH\fP }"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcurrentSearchFinished\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "SearchType \fBsearchType\fP ()"
.br
.ti -1c
.RI "bool \fBfound\fP ()"
.br
.ti -1c
.RI "\fBSearchComboBox\fP (QWidget *p=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file searchComboBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
