.TH "Ms::SynthesizerGroup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SynthesizerGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits list< IdValue >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const QString & \fBname\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &s)"
.br
.ti -1c
.RI "\fBSynthesizerGroup\fP (const char *n, std::list< \fBIdValue\fP > l)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file synthesizerstate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
