.TH "Ms::SeqMsg" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SeqMsg
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSeqMsg\fP (SeqMsgId _id, int val)"
.br
.ti -1c
.RI "\fBSeqMsg\fP (SeqMsgId _id, qreal val)"
.br
.ti -1c
.RI "\fBSeqMsg\fP (SeqMsgId _id, const \fBNPlayEvent\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SeqMsgId \fBid\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBintVal\fP"
.br
.ti -1c
.RI "   qreal \fBrealVal\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "\fBNPlayEvent\fP \fBevent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file seq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
