.TH "Ms::SNote" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SNote
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBontime\fP"
.br
.ti -1c
.RI "int \fBofftime\fP"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "int \fBtpc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file analyse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
