.TH "Ms::StaffNameList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StaffNameList
.SH SYNOPSIS
.br
.PP
.PP
Inherits QList< StaffName >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &xml, const char *name) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file instrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
