.TH "Ms::SlurDesc" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SlurDesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <musicxml\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP : char { \fBNONE\fP, \fBSTART\fP, \fBSTOP\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlur\fP * \fBslur\fP () const"
.br
.ti -1c
.RI "void \fBstart\fP (\fBSlur\fP *slur)"
.br
.ti -1c
.RI "void \fBstop\fP (\fBSlur\fP *slur)"
.br
.ti -1c
.RI "bool \fBisStart\fP () const"
.br
.ti -1c
.RI "bool \fBisStop\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The description of Slurs being handled 
.PP
Definition at line 109 of file musicxml\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
