.TH "Ms::ShortcutCaptureDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ShortcutCaptureDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::ShortcutCaptureDialogBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShortcutCaptureDialog\fP (\fBShortcut\fP *s, QMap< QString, \fBShortcut\fP *> localShortcuts, QWidget *parent=0)"
.br
.ti -1c
.RI "QKeySequence \fBgetKey\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file shortcutcapturedialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
