.TH "Ms::SelectionFilter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SelectionFilter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectionFilter\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "int & \fBfiltered\fP ()"
.br
.ti -1c
.RI "void \fBsetFiltered\fP (SelectionFilterType type, bool set)"
.br
.ti -1c
.RI "bool \fBisFiltered\fP (SelectionFilterType type) const"
.br
.ti -1c
.RI "bool \fBcanSelect\fP (const \fBElement\fP *) const"
.br
.ti -1c
.RI "bool \fBcanSelectVoice\fP (int track) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file select\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
