.TH "Ms::ScoreItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits QListWidgetItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoreItem\fP (const \fBScoreInfo\fP &i)"
.br
.ti -1c
.RI "const \fBScoreInfo\fP & \fBinfo\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file scoreBrowser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
