.TH "Ms::StaffName" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StaffName
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStaffName\fP (const QString &s, int p=0)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBStaffName\fP &) const"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &xml, const char *name) const"
.br
.ti -1c
.RI "int \fBpos\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file instrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
