.TH "Ms::ShowElementBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ShowElementBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBMs::AccidentalView\fP, \fBMs::ArticulationView\fP, \fBMs::BarLineView\fP, \fBMs::BeamView\fP, \fBMs::BoxView\fP, \fBMs::ChordDebug\fP, \fBMs::ClefView\fP, \fBMs::DynamicView\fP, \fBMs::ElementView\fP, \fBMs::HarmonyView\fP, \fBMs::KeySigView\fP, \fBMs::LineSegmentView\fP, \fBMs::LyricsView\fP, \fBMs::MeasureView\fP, \fBMs::RestView\fP, \fBMs::SegmentView\fP, \fBMs::ShowNoteWidget\fP, \fBMs::ShowPageWidget\fP, \fBMs::SlurSegmentView\fP, \fBMs::SpannerView\fP, \fBMs::StemView\fP, \fBMs::SystemView\fP, \fBMs::TextLineSegmentView\fP, \fBMs::TextView\fP, \fBMs::TieSegmentView\fP, \fBMs::TimeSigView\fP, \fBMs::TremoloView\fP, \fBMs::TupletView\fP, \fBMs::VoltaSegmentView\fP, and \fBMs::VoltaView\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBgotoElement\fP (QListWidgetItem *)"
.br
.ti -1c
.RI "void \fBgotoElement\fP (QTreeWidgetItem *)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBelementChanged\fP (\fBElement\fP *)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetElement\fP (\fBElement\fP *)"
.br
.ti -1c
.RI "\fBElement\fP * \fBelement\fP () const"
.br
.ti -1c
.RI "QWidget * \fBaddWidget\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QVBoxLayout * \fBlayout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 138 of file debugger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
