.TH "Ms::StemSlash" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StemSlash \- used for grace notes of type acciaccatura  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stemslash\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStemSlash\fP (\fBScore\fP *s=0)"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const"
.br
.ti -1c
.RI "void \fBsetLine\fP (const QLineF &l)"
.br
.ti -1c
.RI "virtual \fBStemSlash\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
used for grace notes of type acciaccatura 
.PP
Definition at line 26 of file stemslash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
