.TH "Ms::Shape" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Shape
.SH SYNOPSIS
.br
.PP
.PP
Inherits vector< QRectF >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShape\fP (const QRectF &r)"
.br
.ti -1c
.RI "void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "void \fBadd\fP (const \fBShape\fP &s)"
.br
.ti -1c
.RI "void \fBadd\fP (const QRectF &r)"
.br
.ti -1c
.RI "void \fBremove\fP (const QRectF &)"
.br
.ti -1c
.RI "void \fBremove\fP (const \fBShape\fP &)"
.br
.ti -1c
.RI "void \fBtranslate\fP (const QPointF &)"
.br
.ti -1c
.RI "\fBShape\fP \fBtranslated\fP (const QPointF &) const"
.br
.ti -1c
.RI "qreal \fBminHorizontalDistance\fP (const \fBShape\fP &) const"
.br
.ti -1c
.RI "qreal \fBminVerticalDistance\fP (const \fBShape\fP &) const"
.br
.ti -1c
.RI "qreal \fBtopDistance\fP (const QPointF &) const"
.br
.ti -1c
.RI "qreal \fBbottomDistance\fP (const QPointF &) const"
.br
.ti -1c
.RI "qreal \fBleft\fP () const"
.br
.ti -1c
.RI "qreal \fBright\fP () const"
.br
.ti -1c
.RI "qreal \fBtop\fP () const"
.br
.ti -1c
.RI "qreal \fBbottom\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBcontains\fP (const QPointF &) const"
.br
.ti -1c
.RI "bool \fBintersects\fP (const QRectF &rr) const"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file shape\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
