.TH "Ms::SigEvent" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SigEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBread\fP (\fBXmlReader\fP &, int fileDivision)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &, int) const"
.br
.ti -1c
.RI "constexpr \fBSigEvent\fP ()"
.br
.RI "default \fBSigEvent\fP is invalid "
.ti -1c
.RI "\fBSigEvent\fP (const \fBFraction\fP &s, int bar=0)"
.br
.ti -1c
.RI "\fBSigEvent\fP (const \fBFraction\fP &s, const \fBFraction\fP &ss, int bar=0)"
.br
.ti -1c
.RI "\fBSigEvent\fP (const \fBSigEvent\fP &e)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSigEvent\fP &e) const"
.br
.ti -1c
.RI "bool \fBvalid\fP () const"
.br
.ti -1c
.RI "QString \fBprint\fP () const"
.br
.ti -1c
.RI "\fBTimeSigFrac\fP \fBtimesig\fP () const"
.br
.ti -1c
.RI "\fBTimeSigFrac\fP \fBnominal\fP () const"
.br
.ti -1c
.RI "void \fBsetNominal\fP (const \fBFraction\fP &f)"
.br
.ti -1c
.RI "int \fBbar\fP () const"
.br
.ti -1c
.RI "void \fBsetBar\fP (int val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file sig\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
