.TH "Ms::Swing::SwingDetector" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Swing::SwingDetector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwingDetector\fP (MidiOperations::Swing st)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBChordRest\fP *cr)"
.br
.ti -1c
.RI "bool \fBwasSwingApplied\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file importmidi_swing\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
