.TH "Ms::ScoreInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits QFileInfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoreInfo\fP (const QFileInfo &fi)"
.br
.ti -1c
.RI "QPixmap \fBpixmap\fP () const"
.br
.ti -1c
.RI "void \fBsetPixmap\fP (const QPixmap &pm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file scoreInfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
