.TH "Ms::SegmentList::iterator" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SegmentList::iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (\fBSegment\fP *s)"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP ()"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i) const"
.br
.ti -1c
.RI "\fBSegment\fP & \fBoperator*\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file segmentlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
