.TH "Ms::SimpleButton" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SimpleButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits QToolButton\&.
.PP
Inherited by \fBMs::GreendotButton\fP, and \fBMs::RecordButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleButton\fP (QPixmap *on, QPixmap *off, QWidget *parent=0)"
.br
.ti -1c
.RI "\fBSimpleButton\fP (const QString &on, const QString &off, QWidget *parent=0)"
.br
.ti -1c
.RI "\fBSimpleButton\fP (const QString &s, QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file simplebutton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
