.TH "Ms::Sym" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Sym
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "void \fBsetSymList\fP (const std::vector< SymId > &sl)"
.br
.ti -1c
.RI "const std::vector< SymId > & \fBsymList\fP () const"
.br
.ti -1c
.RI "FT_UInt \fBindex\fP () const"
.br
.ti -1c
.RI "void \fBsetIndex\fP (FT_UInt i)"
.br
.ti -1c
.RI "int \fBcode\fP () const"
.br
.ti -1c
.RI "void \fBsetCode\fP (int val)"
.br
.ti -1c
.RI "QRectF \fBbbox\fP () const"
.br
.ti -1c
.RI "void \fBsetBbox\fP (QRectF val)"
.br
.ti -1c
.RI "qreal \fBadvance\fP () const"
.br
.ti -1c
.RI "void \fBsetAdvance\fP (qreal val)"
.br
.ti -1c
.RI "QPointF \fBstemDownNW\fP () const"
.br
.ti -1c
.RI "void \fBsetStemDownNW\fP (const QPointF &r)"
.br
.ti -1c
.RI "QPointF \fBstemUpSE\fP () const"
.br
.ti -1c
.RI "void \fBsetStemUpSE\fP (const QPointF &r)"
.br
.ti -1c
.RI "QPointF \fBcutOutNE\fP () const"
.br
.ti -1c
.RI "void \fBsetCutOutNE\fP (const QPointF &r)"
.br
.ti -1c
.RI "QPointF \fBcutOutNW\fP () const"
.br
.ti -1c
.RI "void \fBsetCutOutNW\fP (const QPointF &r)"
.br
.ti -1c
.RI "QPointF \fBcutOutSE\fP () const"
.br
.ti -1c
.RI "void \fBsetCutOutSE\fP (const QPointF &r)"
.br
.ti -1c
.RI "QPointF \fBcutOutSW\fP () const"
.br
.ti -1c
.RI "void \fBsetCutOutSW\fP (const QPointF &r)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static SymId \fBname2id\fP (const QString &s)"
.br
.ti -1c
.RI "static SymId \fBoldName2id\fP (const QString s)"
.br
.ti -1c
.RI "static const char * \fBid2name\fP (SymId id)"
.br
.ti -1c
.RI "static QString \fBid2userName\fP (SymId id)"
.br
.ti -1c
.RI "static SymId \fBuserName2id\fP (const QString &s)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::array< const char *, int(SymId::lastSym)+1 > \fBsymNames\fP"
.br
.ti -1c
.RI "static const std::array< const char *, int(SymId::lastSym)+1 > \fBsymUserNames\fP"
.br
.ti -1c
.RI "static QHash< QString, SymId > \fBlnhash\fP"
.br
.ti -1c
.RI "static QHash< QString, SymId > \fBlonhash\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_code\fP = \-1"
.br
.ti -1c
.RI "FT_UInt \fB_index\fP"
.br
.ti -1c
.RI "QRectF \fB_bbox\fP"
.br
.ti -1c
.RI "qreal \fB_advance\fP"
.br
.ti -1c
.RI "QPointF \fB_stemDownNW\fP"
.br
.ti -1c
.RI "QPointF \fB_stemUpSE\fP"
.br
.ti -1c
.RI "QPointF \fB_cutOutNE\fP"
.br
.ti -1c
.RI "QPointF \fB_cutOutNW\fP"
.br
.ti -1c
.RI "QPointF \fB_cutOutSE\fP"
.br
.ti -1c
.RI "QPointF \fB_cutOutSW\fP"
.br
.ti -1c
.RI "std::vector< SymId > \fB_ids\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBScoreFont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2673 of file sym\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
