.TH "Ms::ScoreListWidget" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ScoreListWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QListWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoreListWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "int \fBcellWidth\fP () const"
.br
.ti -1c
.RI "int \fBcellHeight\fP () const"
.br
.ti -1c
.RI "int \fBspace\fP () const"
.br
.ti -1c
.RI "QSize \fBcellSize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file scoreBrowser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
