.TH "Ms::SelectNoteDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SelectNoteDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::SelectNoteDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectNoteDialog\fP (const \fBNote\fP *n, QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetPattern\fP (\fBNotePattern\fP *p)"
.br
.ti -1c
.RI "bool \fBdoReplace\fP () const"
.br
.ti -1c
.RI "bool \fBdoAdd\fP () const"
.br
.ti -1c
.RI "bool \fBdoSubtract\fP () const"
.br
.ti -1c
.RI "bool \fBdoFromSelection\fP () const"
.br
.ti -1c
.RI "bool \fBisInSelection\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file selectnotedialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
