.TH "Ms::StyledProperty" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::StyledProperty
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "StyleIdx \fBstyleIdx\fP"
.br
.ti -1c
.RI "P_ID \fBpropertyIdx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 684 of file style\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
