.TH "Ms::SystemDivider" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SystemDivider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Symbol\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBLEFT\fP, \fBRIGHT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSystemDivider\fP (\fBScore\fP *s=0)"
.br
.ti -1c
.RI "\fBSystemDivider\fP (const \fBSystemDivider\fP &)"
.br
.ti -1c
.RI "virtual \fBSystemDivider\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "Type \fBdividerType\fP () const"
.br
.ti -1c
.RI "void \fBsetDividerType\fP (Type v)"
.br
.ti -1c
.RI "virtual QRectF \fBdrag\fP (\fBEditData\fP &) override"
.br
.RI "Return update Rect relative to canvas\&. "
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual \fBSegment\fP * \fBsegment\fP () const override"
.br
.ti -1c
.RI "\fBSystem\fP * \fBsystem\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file systemdivider\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
