.TH "Ms::SelectDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::SelectDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::SelectDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectDialog\fP (const \fBElement\fP *e, QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetPattern\fP (\fBElementPattern\fP *p)"
.br
.ti -1c
.RI "bool \fBdoReplace\fP () const"
.br
.ti -1c
.RI "bool \fBdoAdd\fP () const"
.br
.ti -1c
.RI "bool \fBdoSubtract\fP () const"
.br
.ti -1c
.RI "bool \fBdoFromSelection\fP () const"
.br
.ti -1c
.RI "bool \fBisInSelection\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file selectdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
