.TH "Ms::TremoloBarProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TremoloBarProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::TremoloBarDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTremoloBarProperties\fP (\fBTremoloBar\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "const QList< \fBPitchValue\fP > & \fBpoints\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 37 of file tremolobarprop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
