.TH "Ms::TempoPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TempoPattern
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTempoPattern\fP (const char *s, qreal v, TDuration::DurationType val, int dots=0)"
.br
.ti -1c
.RI "\fBTempoPattern\fP (const QString &s, double v, bool r, bool i, bool f, bool b, bool m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpattern\fP"
.br
.ti -1c
.RI "qreal \fBf\fP"
.br
.ti -1c
.RI "\fBTDuration\fP \fBd\fP"
.br
.ti -1c
.RI "QString \fBpattern\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "bool \fBrelative\fP"
.br
.ti -1c
.RI "bool \fBitalian\fP"
.br
.ti -1c
.RI "bool \fBfollowText\fP"
.br
.ti -1c
.RI "bool \fBbasic\fP"
.br
.ti -1c
.RI "bool \fBmasterOnly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file tempotext\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
