.TH "Ms::TracksModel::Column" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TracksModel::Column
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColumn\fP (\fBMidiOperations::Opers\fP &opers)"
.br
.ti -1c
.RI "virtual QVariant \fBvalue\fP (int trackIndex) const =0"
.br
.ti -1c
.RI "virtual void \fBsetValue\fP (const QVariant &value, int trackIndex)=0"
.br
.ti -1c
.RI "virtual QString \fBheaderName\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBisVisible\fP (int) const"
.br
.ti -1c
.RI "virtual QStringList \fBvalueList\fP (int) const"
.br
.ti -1c
.RI "virtual int \fBwidth\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisEditable\fP (int) const"
.br
.ti -1c
.RI "virtual bool \fBisForAllTracksOnly\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMidiOperations::Opers\fP & \fB_opers\fP"
.br
.ti -1c
.RI "QStringList \fB_values\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file importmidi_model\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
