.TH "Ms::TextObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicRectObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBtext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 455 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
