.TH "Ms::TimeSigProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TimeSigProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::TimeSigProperties\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBaccept\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeSigProperties\fP (\fBTimeSig\fP *, QWidget *parent=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file timesigproperties\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
