.TH "Ms::Tie" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Tie \- a \fBTie\fP has a \fBNote\fP as startElement/endElement  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tie\&.h>\fP
.PP
Inherits \fBMs::SlurTie\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTie\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "virtual \fBTie\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "void \fBsetStartNote\fP (\fBNote\fP *note)"
.br
.ti -1c
.RI "void \fBsetEndNote\fP (\fBNote\fP *note)"
.br
.ti -1c
.RI "\fBNote\fP * \fBstartNote\fP () const"
.br
.ti -1c
.RI "\fBNote\fP * \fBendNote\fP () const"
.br
.ti -1c
.RI "void \fBcalculateDirection\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBslurPos\fP (\fBSlurPos\fP *) override"
.br
.ti -1c
.RI "virtual void \fBstartEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "virtual void \fBendEdit\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "bool \fBreadProperties\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "\fBTieSegment\fP * \fBfrontSegment\fP () const"
.br
.ti -1c
.RI "\fBTieSegment\fP * \fBbackSegment\fP () const"
.br
.ti -1c
.RI "\fBTieSegment\fP * \fBtakeLastSegment\fP ()"
.br
.ti -1c
.RI "\fBTieSegment\fP * \fBsegmentAt\fP (int n) const"
.br
.ti -1c
.RI "virtual \fBSlurTieSegment\fP * \fBnewSlurTieSegment\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
a \fBTie\fP has a \fBNote\fP as startElement/endElement 
.PP
Definition at line 68 of file tie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
