.TH "Ms::TracksModel" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TracksModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits QAbstractTableModel\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColumn\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP (const \fBMidiOperations::Opers\fP &opers, const QList< std::string > &lyricsList, int trackCount, const QString &midiFile, bool hasHumanBeats, bool hasTempoText, bool hasChordNames)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBupdateCharset\fP ()"
.br
.ti -1c
.RI "void \fBnotifyAllApplied\fP ()"
.br
.ti -1c
.RI "const \fBMidiOperations::Opers\fP & \fBtrackOpers\fP () const"
.br
.ti -1c
.RI "int \fBtrackCount\fP () const"
.br
.ti -1c
.RI "int \fBtrackCountForImport\fP () const"
.br
.ti -1c
.RI "int \fBfrozenRowCount\fP () const"
.br
.ti -1c
.RI "int \fBfrozenColCount\fP () const"
.br
.ti -1c
.RI "int \fBrowFromTrackIndex\fP (int trackIndex) const"
.br
.ti -1c
.RI "int \fBtrackIndexFromRow\fP (int row) const"
.br
.ti -1c
.RI "bool \fBisAllApplied\fP () const"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role=Qt::DisplayRole) const"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file importmidi_model\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
