.TH "Ms::TimeSigMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TimeSigMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits map< int, SigEvent >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (int tick, const \fBFraction\fP &)"
.br
.ti -1c
.RI "void \fBadd\fP (int tick, const \fBSigEvent\fP &ev)"
.br
.ti -1c
.RI "void \fBdel\fP (int tick)"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &, int fileDiv)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBXmlWriter\fP &) const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "const \fBSigEvent\fP & \fBtimesig\fP (int tick) const"
.br
.ti -1c
.RI "void \fBtickValues\fP (int t, int *bar, int *beat, int *tick) const"
.br
.ti -1c
.RI "int \fBbar2tick\fP (int bar, int beat) const"
.br
.ti -1c
.RI "QString \fBpos\fP (int t) const"
.br
.ti -1c
.RI "unsigned \fBraster\fP (unsigned tick, int raster) const"
.br
.ti -1c
.RI "unsigned \fBraster1\fP (unsigned tick, int raster) const"
.br
.ti -1c
.RI "unsigned \fBraster2\fP (unsigned tick, int raster) const"
.br
.ti -1c
.RI "int \fBrasterStep\fP (unsigned tick, int raster) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file sig\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
