.TH "Ms::TextSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextSegment
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "qreal \fBwidth\fP () const"
.br
.ti -1c
.RI "QRectF \fBboundingRect\fP () const"
.br
.ti -1c
.RI "QRectF \fBtightBoundingRect\fP () const"
.br
.ti -1c
.RI "\fBTextSegment\fP (const QFont &f, qreal _x, qreal _y)"
.br
.ti -1c
.RI "\fBTextSegment\fP (const QString &, const QFont &, qreal x, qreal y)"
.br
.ti -1c
.RI "void \fBset\fP (const QString &, const QFont &, qreal x, qreal y)"
.br
.ti -1c
.RI "void \fBsetText\fP (const QString &t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QFont \fBfont\fP"
.br
.ti -1c
.RI "QString \fBtext\fP"
.br
.ti -1c
.RI "qreal \fBx\fP"
.br
.ti -1c
.RI "qreal \fBy\fP"
.br
.ti -1c
.RI "bool \fBselect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file harmony\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
