.TH "Ms::TempoMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TempoMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits map< int, TEvent >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.ti -1c
.RI "qreal \fBtempo\fP (int tick) const"
.br
.ti -1c
.RI "qreal \fBtick2time\fP (int tick, int *sn=0) const"
.br
.ti -1c
.RI "qreal \fBtick2timeLC\fP (int tick, int *sn) const"
.br
.ti -1c
.RI "qreal \fBtick2time\fP (int tick, qreal time, int *sn) const"
.br
.ti -1c
.RI "int \fBtime2tick\fP (qreal time, int *sn=0) const"
.br
.ti -1c
.RI "int \fBtime2tick\fP (qreal time, int tick, int *sn) const"
.br
.ti -1c
.RI "int \fBtempoSN\fP () const"
.br
.ti -1c
.RI "void \fBsetTempo\fP (int t, qreal)"
.br
.ti -1c
.RI "void \fBsetPause\fP (int t, qreal)"
.br
.ti -1c
.RI "void \fBdelTempo\fP (int tick)"
.br
.ti -1c
.RI "void \fBsetRelTempo\fP (qreal val)"
.br
.ti -1c
.RI "qreal \fBrelTempo\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file tempo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
