.TH "Ms::Tile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Tile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBno\fP"
.br
.ti -1c
.RI "QRect \fBr\fP"
.br
.ti -1c
.RI "QPixmap \fBpm\fP"
.br
.ti -1c
.RI "\fBOmrPage\fP * \fBpage\fP"
.br
.ti -1c
.RI "int \fBpageNo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file omrview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
