.TH "Ms::TablatureDurationFont" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TablatureDurationFont
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBread\fP (\fBXmlReader\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBfamily\fP"
.br
.ti -1c
.RI "QString \fBdisplayName\fP"
.br
.ti -1c
.RI "qreal \fBdefPitch\fP"
.br
.ti -1c
.RI "qreal \fBdefYOffset\fP"
.br
.ti -1c
.RI "qreal \fBgridBeamWidth\fP = GRID_BEAM_DEF_WIDTH"
.br
.ti -1c
.RI "qreal \fBgridStemHeight\fP = GRID_STEM_DEF_HEIGHT"
.br
.ti -1c
.RI "qreal \fBgridStemWidth\fP = GRID_STEM_DEF_WIDTH"
.br
.ti -1c
.RI "TDuration::DurationType \fBzeroBeamLevel\fP = TDuration::DurationType::V_QUARTER"
.br
.ti -1c
.RI "QChar \fBdisplayDot\fP"
.br
.ti -1c
.RI "QChar \fBdisplayValue\fP [int(TabVal::NUM_OF)]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file stafftype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
