.TH "Ms::TremoloBar" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TremoloBar
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTremoloBar\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBTremoloBar\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &e) override"
.br
.ti -1c
.RI "QList< \fBPitchValue\fP > & \fBpoints\fP ()"
.br
.ti -1c
.RI "const QList< \fBPitchValue\fP > & \fBpoints\fP () const"
.br
.ti -1c
.RI "void \fBsetPoints\fP (const QList< \fBPitchValue\fP > &p)"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual PropertyFlags \fBpropertyFlags\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual void \fBresetProperty\fP (P_ID id) override"
.br
.ti -1c
.RI "virtual void \fBstyleChanged\fP () override"
.br
.ti -1c
.RI "virtual void \fBreset\fP () override"
.br
.ti -1c
.RI "virtual void \fBspatiumChanged\fP (qreal oldValue, qreal newValue) override"
.br
.ti -1c
.RI "qreal \fBuserMag\fP () const"
.br
.ti -1c
.RI "void \fBsetUserMag\fP (qreal m)"
.br
.ti -1c
.RI "void \fBundoSetUserMag\fP (qreal val)"
.br
.ti -1c
.RI "void \fBsetLineWidth\fP (\fBSpatium\fP v)"
.br
.ti -1c
.RI "\fBSpatium\fP \fBlineWidth\fP () const"
.br
.ti -1c
.RI "void \fBundoSetLineWidth\fP (\fBSpatium\fP)"
.br
.ti -1c
.RI "bool \fBplay\fP () const"
.br
.ti -1c
.RI "void \fBsetPlay\fP (bool val)"
.br
.ti -1c
.RI "void \fBundoSetPlay\fP (bool)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBuserMag\fP"
.br
.ti -1c
.RI "\fBSpatium\fP \fBlineWidth\fP"
.br
.ti -1c
.RI "bool \fBplay\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 29 of file tremolobar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
