.TH "Ms::TrackList" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TrackList
.SH SYNOPSIS
.br
.PP
.PP
Inherits QList< Element *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackList\fP (\fBScoreRange\fP *r)"
.br
.ti -1c
.RI "\fBFraction\fP \fBduration\fP () const"
.br
.ti -1c
.RI "\fBScoreRange\fP * \fBrange\fP () const"
.br
.ti -1c
.RI "int \fBtrack\fP () const"
.br
.ti -1c
.RI "void \fBsetTrack\fP (int val)"
.br
.ti -1c
.RI "void \fBread\fP (const \fBSegment\fP *fs, const \fBSegment\fP *ls)"
.br
.ti -1c
.RI "bool \fBwrite\fP (\fBScore\fP *, int tick) const"
.br
.ti -1c
.RI "void \fBappendGap\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "bool \fBtruncate\fP (const \fBFraction\fP &)"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file range\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
