.TH "Ms::TimeSig" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TimeSig \- This class represents a time signature\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timesig\&.h>\fP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeSig\fP (\fBScore\fP *=0)"
.br
.ti -1c
.RI "QString \fBssig\fP () const"
.br
.ti -1c
.RI "void \fBsetSSig\fP (const QString &)"
.br
.ti -1c
.RI "virtual \fBTimeSig\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "TimeSigType \fBtimeSigType\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTimeSig\fP &) const"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const override"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "\fBFraction\fP \fBsig\fP () const"
.br
.ti -1c
.RI "void \fBsetSig\fP (const \fBFraction\fP &f, TimeSigType st=TimeSigType::NORMAL)"
.br
.ti -1c
.RI "int \fBnumerator\fP () const"
.br
.ti -1c
.RI "int \fBdenominator\fP () const"
.br
.ti -1c
.RI "\fBFraction\fP \fBstretch\fP () const"
.br
.ti -1c
.RI "void \fBsetStretch\fP (const \fBFraction\fP &s)"
.br
.ti -1c
.RI "int \fBnumeratorStretch\fP () const"
.br
.ti -1c
.RI "int \fBdenominatorStretch\fP () const"
.br
.ti -1c
.RI "bool \fBacceptDrop\fP (\fBEditData\fP &) const override"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBdrop\fP (\fBEditData\fP &) override"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "\fBMeasure\fP * \fBmeasure\fP () const"
.br
.ti -1c
.RI "bool \fBshowCourtesySig\fP () const"
.br
.ti -1c
.RI "void \fBsetShowCourtesySig\fP (bool v)"
.br
.ti -1c
.RI "QString \fBnumeratorString\fP () const"
.br
.ti -1c
.RI "void \fBsetNumeratorString\fP (const QString &)"
.br
.ti -1c
.RI "QString \fBdenominatorString\fP () const"
.br
.ti -1c
.RI "void \fBsetDenominatorString\fP (const QString &)"
.br
.ti -1c
.RI "void \fBsetLargeParentheses\fP (bool v)"
.br
.ti -1c
.RI "void \fBsetScale\fP (const QSizeF &s)"
.br
.ti -1c
.RI "void \fBsetFrom\fP (const \fBTimeSig\fP *)"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual StyleIdx \fBgetPropertyStyle\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual void \fBstyleChanged\fP () override"
.br
.ti -1c
.RI "virtual PropertyFlags \fBpropertyFlags\fP (P_ID id) const override"
.br
.ti -1c
.RI "bool \fBhasCustomText\fP () const"
.br
.ti -1c
.RI "const \fBGroups\fP & \fBgroups\fP () const"
.br
.ti -1c
.RI "void \fBsetGroups\fP (const \fBGroups\fP &e)"
.br
.ti -1c
.RI "\fBFraction\fP \fBglobalSig\fP () const"
.br
.ti -1c
.RI "void \fBsetGlobalSig\fP (const \fBFraction\fP &f)"
.br
.ti -1c
.RI "bool \fBisLocal\fP () const"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBnextElement\fP ()"
.br
.ti -1c
.RI "virtual \fBElement\fP * \fBprevElement\fP ()"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class represents a time signature\&. 
.PP
Definition at line 50 of file timesig\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Ms::TimeSig::acceptDrop (\fBEditData\fP &) const\fC [override]\fP, \fC [virtual]\fP"
Return true if this element accepts a drop at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&.
.PP
Reimplemented by elements that accept drops\&. Used to change cursor shape while dragging to indicate drop targets\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 77 of file timesig\&.cpp\&.
.SS "\fBElement\fP * Ms::TimeSig::drop (\fBEditData\fP &)\fC [override]\fP, \fC [virtual]\fP"
Handle a dropped element at canvas relative \fIpos\fP of given element \fItype\fP and \fIsubtype\fP\&. Returns dropped element if any\&. The ownership of element in DropData is transfered to the called element (if not used, element has to be deleted)\&. The returned element will be selected if not in note edit mode\&.
.PP
Reimplemented by elements that accept drops\&. 
.PP
Reimplemented from \fBMs::Element\fP\&.
.PP
Definition at line 86 of file timesig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
