.TH "Ms::TempoText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TempoText \- Tempo marker which determines the midi tempo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tempotext\&.h>\fP
.PP
Inherits \fBMs::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTempoText\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "virtual \fBTempoText\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "\fBMeasure\fP * \fBmeasure\fP () const"
.br
.ti -1c
.RI "qreal \fBtempo\fP () const"
.br
.ti -1c
.RI "void \fBsetTempo\fP (qreal v)"
.br
.ti -1c
.RI "void \fBundoSetTempo\fP (qreal v)"
.br
.ti -1c
.RI "bool \fBisRelative\fP ()"
.br
.ti -1c
.RI "void \fBsetRelative\fP (qreal v)"
.br
.ti -1c
.RI "bool \fBfollowText\fP () const"
.br
.ti -1c
.RI "void \fBsetFollowText\fP (bool v)"
.br
.ti -1c
.RI "void \fBundoSetFollowText\fP (bool v)"
.br
.ti -1c
.RI "void \fBupdateRelative\fP ()"
.br
.ti -1c
.RI "virtual void \fBtextChanged\fP () override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBfindTempoDuration\fP (const QString &s, int &len, \fBTDuration\fP &dur)"
.br
.ti -1c
.RI "static QString \fBduration2tempoTextString\fP (const \fBTDuration\fP dur)"
.br
.ti -1c
.RI "static QString \fBduration2userName\fP (const \fBTDuration\fP t)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBtempo\fP"
.br
.ti -1c
.RI "bool \fBfollowText\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tempo marker which determines the midi tempo\&. 
.PP
Definition at line 29 of file tempotext\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
