.TH "Ms::TextTools" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextTools
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDockWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextTools\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBupdateTools\fP (\fBEditData\fP &)"
.br
.ti -1c
.RI "QAction * \fBkbAction\fP () const"
.br
.ti -1c
.RI "void \fBtoggleBold\fP ()"
.br
.ti -1c
.RI "void \fBtoggleItalic\fP ()"
.br
.ti -1c
.RI "void \fBtoggleUnderline\fP ()"
.br
.ti -1c
.RI "\fBText\fP * \fBtextElement\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file texttools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
