.TH "Ms::TextPalette" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextPalette
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget, and \fBUi::TextPaletteBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextPalette\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetText\fP (\fBText\fP *te)"
.br
.ti -1c
.RI "\fBText\fP * \fBtext\fP ()"
.br
.ti -1c
.RI "void \fBsetFont\fP (const QFont &\fBfont\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 35 of file textpalette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
