.TH "Ms::TabDurationSymbol" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TabDurationSymbol
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTabDurationSymbol\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBTabDurationSymbol\fP (\fBScore\fP *s, \fBStaffType\fP *tab, TDuration::DurationType type, int dots)"
.br
.ti -1c
.RI "\fBTabDurationSymbol\fP (const \fBTabDurationSymbol\fP &)"
.br
.ti -1c
.RI "virtual \fBTabDurationSymbol\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual bool \fBisEditable\fP () const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "TabBeamGrid \fBbeamGrid\fP ()"
.br
.ti -1c
.RI "void \fBlayout2\fP ()"
.br
.ti -1c
.RI "void \fBsetDuration\fP (TDuration::DurationType type, int dots, \fBStaffType\fP *tab)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 416 of file stafftype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
