.TH "Ms::TextLineBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextLineBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SLine\fP\&.
.PP
Inherited by \fBMs::Hairpin\fP, \fBMs::NoteLine\fP, \fBMs::Ottava\fP, \fBMs::Pedal\fP, \fBMs::TextLine\fP, and \fBMs::Volta\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextLineBase\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBTextLineBase\fP (const \fBTextLineBase\fP &)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "virtual void \fBwriteProperties\fP (\fBXmlWriter\fP &xml) const override"
.br
.ti -1c
.RI "virtual bool \fBreadProperties\fP (\fBXmlReader\fP &node) override"
.br
.ti -1c
.RI "virtual void \fBspatiumChanged\fP (qreal, qreal) override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextLineBaseSegment\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 73 of file textlinebase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
