.TH "Ms::Tuplet2" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Tuplet2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTuplet2\fP (\fBTuplet\fP *_o, \fBTuplet\fP *_n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTuplet\fP * \fBo\fP"
.br
.ti -1c
.RI "\fBTuplet\fP * \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file tupletmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
