.TH "Ms::Tremolo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Tremolo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTremolo\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBTremolo\fP (const \fBTremolo\fP &)"
.br
.ti -1c
.RI "\fBTremolo\fP & \fBoperator=\fP (const \fBTremolo\fP &)=delete"
.br
.ti -1c
.RI "virtual \fBTremolo\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual int \fBsubtype\fP () const"
.br
.ti -1c
.RI "virtual QString \fBsubtypeName\fP () const"
.br
.ti -1c
.RI "QString \fBtremoloTypeName\fP () const"
.br
.ti -1c
.RI "void \fBsetTremoloType\fP (const QString &s)"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord\fP () const"
.br
.ti -1c
.RI "void \fBsetTremoloType\fP (TremoloType t)"
.br
.ti -1c
.RI "TremoloType \fBtremoloType\fP () const"
.br
.ti -1c
.RI "virtual qreal \fBmag\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const"
.br
.ti -1c
.RI "virtual void \fBlayout\fP ()"
.br
.ti -1c
.RI "void \fBlayout2\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &xml) const"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord1\fP () const"
.br
.ti -1c
.RI "\fBChord\fP * \fBchord2\fP () const"
.br
.ti -1c
.RI "void \fBsetChords\fP (\fBChord\fP *c1, \fBChord\fP *c2)"
.br
.ti -1c
.RI "\fBFraction\fP \fBtremoloLen\fP () const"
.br
.ti -1c
.RI "bool \fBtwoNotes\fP () const"
.br
.ti -1c
.RI "int \fBlines\fP () const"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file tremolo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
