.TH "Ms::TransposeDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TransposeDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::TransposeDialogBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransposeDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBenableTransposeKeys\fP (bool val)"
.br
.ti -1c
.RI "void \fBenableTransposeByKey\fP (bool val)"
.br
.ti -1c
.RI "void \fBenableTransposeChordNames\fP (bool val)"
.br
.ti -1c
.RI "bool \fBgetTransposeKeys\fP () const"
.br
.ti -1c
.RI "bool \fBgetTransposeChordNames\fP () const"
.br
.ti -1c
.RI "Key \fBtransposeKey\fP () const"
.br
.ti -1c
.RI "int \fBtransposeInterval\fP () const"
.br
.ti -1c
.RI "TransposeDirection \fBdirection\fP () const"
.br
.ti -1c
.RI "TransposeMode \fBmode\fP () const"
.br
.ti -1c
.RI "void \fBsetKey\fP (Key k)"
.br
.ti -1c
.RI "bool \fBuseDoubleSharpsFlats\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file transposedialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
