.TH "Ms::TextCursor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextCursor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextCursor\fP (\fBText\fP *t)"
.br
.ti -1c
.RI "\fBText\fP * \fBtext\fP () const"
.br
.ti -1c
.RI "bool \fBhasSelection\fP () const"
.br
.ti -1c
.RI "void \fBclearSelection\fP ()"
.br
.ti -1c
.RI "\fBCharFormat\fP * \fBformat\fP ()"
.br
.ti -1c
.RI "const \fBCharFormat\fP * \fBformat\fP () const"
.br
.ti -1c
.RI "void \fBsetFormat\fP (const \fBCharFormat\fP &f)"
.br
.ti -1c
.RI "int \fBline\fP () const"
.br
.ti -1c
.RI "int \fBcolumn\fP () const"
.br
.ti -1c
.RI "int \fBselectLine\fP () const"
.br
.ti -1c
.RI "int \fBselectColumn\fP () const"
.br
.ti -1c
.RI "void \fBsetLine\fP (int val)"
.br
.ti -1c
.RI "void \fBsetColumn\fP (int val)"
.br
.ti -1c
.RI "void \fBsetSelectLine\fP (int val)"
.br
.ti -1c
.RI "void \fBsetSelectColumn\fP (int val)"
.br
.ti -1c
.RI "void \fBsetText\fP (\fBText\fP *t)"
.br
.ti -1c
.RI "int \fBcolumns\fP () const"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBTextBlock\fP & \fBcurLine\fP () const"
.br
.ti -1c
.RI "QRectF \fBcursorRect\fP () const"
.br
.ti -1c
.RI "bool \fBmovePosition\fP (QTextCursor::MoveOperation op, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor, int count=1)"
.br
.ti -1c
.RI "void \fBmoveCursorToEnd\fP ()"
.br
.ti -1c
.RI "void \fBmoveCursorToStart\fP ()"
.br
.ti -1c
.RI "QChar \fBcurrentCharacter\fP () const"
.br
.ti -1c
.RI "bool \fBset\fP (const QPointF &p, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor)"
.br
.ti -1c
.RI "QString \fBselectedText\fP () const"
.br
.ti -1c
.RI "void \fBupdateCursorFormat\fP ()"
.br
.ti -1c
.RI "void \fBsetFormat\fP (FormatId, QVariant)"
.br
.ti -1c
.RI "void \fBchangeSelectionFormat\fP (FormatId id, QVariant val)"
.br
.ti -1c
.RI "bool \fBdeleteChar\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file text\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
