.TH "Ms::TupletDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TupletDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog, and \fBUi::TupletDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTupletDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetupTuplet\fP (\fBTuplet\fP *tuplet)"
.br
.ti -1c
.RI "int \fBgetNormalNotes\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file tupletdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
