.TH "Ms::ToolButtonMenu" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ToolButtonMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::AccessibleToolButton\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTYPES\fP { \fBFIXED\fP, \fBICON_CHANGED\fP, \fBACTION_SWAPPED\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToolButtonMenu\fP (QString str, TYPES type, QAction *defaultAction, QActionGroup *alternativeActions, QWidget *parent)"
.br
.ti -1c
.RI "void \fBaddAction\fP (QAction *a)"
.br
.ti -1c
.RI "void \fBaddSeparator\fP ()"
.br
.ti -1c
.RI "void \fBaddActions\fP (QList< QAction *> actions)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBchangeIcon\fP (QAction *a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file toolbuttonmenu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
