.TH "Ms::TimeSigFrac" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TimeSigFrac
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Fraction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBTimeSigFrac\fP (int n=0, int d=1)"
.br
.ti -1c
.RI "\fBTimeSigFrac\fP (const \fBFraction\fP &f)"
.br
.ti -1c
.RI "\fBTimeSigFrac\fP (const \fBTimeSigFrac\fP &f)"
.br
.ti -1c
.RI "bool \fBisCompound\fP () const"
.br
.ti -1c
.RI "bool \fBisBeatedCompound\fP (qreal tempo) const"
.br
.ti -1c
.RI "int \fBdUnitTicks\fP () const"
.br
.ti -1c
.RI "int \fBticksPerMeasure\fP () const"
.br
.ti -1c
.RI "int \fBdUnitsPerBeat\fP () const"
.br
.ti -1c
.RI "int \fBbeatTicks\fP () const"
.br
.ti -1c
.RI "int \fBbeatsPerMeasure\fP () const"
.br
.ti -1c
.RI "int \fBsubbeatTicks\fP (int level) const"
.br
.ti -1c
.RI "int \fBmaxSubbeatLevel\fP () const"
.br
.ti -1c
.RI "bool \fBisTriple\fP () const"
.br
.ti -1c
.RI "bool \fBisDuple\fP () const"
.br
.ti -1c
.RI "qreal \fBtempo2beatsPerMinute\fP (qreal tempo) const"
.br
.ti -1c
.RI "qreal \fBbeatsPerMinute2tempo\fP (qreal bpm) const"
.br
.ti -1c
.RI "BeatType \fBrtick2beatType\fP (int rtick) const"
.br
.ti -1c
.RI "int \fBrtick2subbeatLevel\fP (int rtick) const"
.br
.ti -1c
.RI "BeatType \fBstrongestBeatInRange\fP (int rtick1, int rtick2, int *dUnitsCrossed=0, int *subbeatTick=0, bool saveLast=false) const"
.br
.ti -1c
.RI "int \fBstrongestSubbeatLevelInRange\fP (int rtick1, int rtick2, int *subbeatTick=0) const"
.br
.ti -1c
.RI "int \fBticksPastDUnit\fP (int rtick) const"
.br
.ti -1c
.RI "int \fBticksToNextDUnit\fP (int rtick) const"
.br
.ti -1c
.RI "int \fBticksPastBeat\fP (int rtick) const"
.br
.ti -1c
.RI "int \fBticksToNextBeat\fP (int rtick) const"
.br
.ti -1c
.RI "int \fBticksPastSubbeat\fP (int rtick, int level) const"
.br
.ti -1c
.RI "int \fBticksToNextSubbeat\fP (int rtick, int level) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 41 of file sig\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
