.TH "Ms::TextLineBaseSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::TextLineBaseSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::LineSegment\fP\&.
.PP
Inherited by \fBMs::HairpinSegment\fP, \fBMs::OttavaSegment\fP, \fBMs::PedalSegment\fP, \fBMs::TextLineSegment\fP, and \fBMs::VoltaSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextLineBaseSegment\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "\fBTextLineBaseSegment\fP (const \fBTextLineBaseSegment\fP &)"
.br
.ti -1c
.RI "\fBTextLineBase\fP * \fBtextLineBase\fP () const"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *) const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual void \fBsetSelected\fP (bool f)"
.br
.ti -1c
.RI "virtual void \fBspatiumChanged\fP (qreal, qreal) override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID id) const override"
.br
.ti -1c
.RI "virtual \fBShape\fP \fBshape\fP () const override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBText\fP * \fB_text\fP"
.br
.ti -1c
.RI "\fBText\fP * \fB_endText\fP"
.br
.ti -1c
.RI "QPointF \fBpoints\fP [4]"
.br
.ti -1c
.RI "int \fBnpoints\fP"
.br
.ti -1c
.RI "bool \fBtwoLines\fP { false }"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 32 of file textlinebase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
