.TH "Ms::Trill" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Trill
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SLine\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : char { \fBTRILL_LINE\fP, \fBUPPRALL_LINE\fP, \fBDOWNPRALL_LINE\fP, \fBPRALLPRALL_LINE\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrill\fP (\fBScore\fP *s)"
.br
.ti -1c
.RI "virtual \fBTrill\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual \fBLineSegment\fP * \fBcreateLineSegment\fP () override"
.br
.ti -1c
.RI "virtual void \fBadd\fP (\fBElement\fP *) override"
.br
.ti -1c
.RI "virtual void \fBremove\fP (\fBElement\fP *) override"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBXmlWriter\fP &) const override"
.br
.ti -1c
.RI "virtual void \fBread\fP (\fBXmlReader\fP &) override"
.br
.ti -1c
.RI "void \fBsetTrillType\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBundoSetTrillType\fP (Type val)"
.br
.ti -1c
.RI "void \fBsetTrillType\fP (Type tt)"
.br
.ti -1c
.RI "Type \fBtrillType\fP () const"
.br
.ti -1c
.RI "void \fBsetOrnamentStyle\fP (MScore::OrnamentStyle val)"
.br
.ti -1c
.RI "MScore::OrnamentStyle \fBornamentStyle\fP () const"
.br
.ti -1c
.RI "void \fBsetPlayArticulation\fP (bool val)"
.br
.ti -1c
.RI "bool \fBplayArticulation\fP () const"
.br
.ti -1c
.RI "QString \fBtrillTypeName\fP () const"
.br
.ti -1c
.RI "QString \fBtrillTypeUserName\fP () const"
.br
.ti -1c
.RI "\fBAccidental\fP * \fBaccidental\fP () const"
.br
.ti -1c
.RI "void \fBsetAccidental\fP (\fBAccidental\fP *a)"
.br
.ti -1c
.RI "\fBSegment\fP * \fBsegment\fP () const"
.br
.ti -1c
.RI "virtual void \fBscanElements\fP (void *data, void(*func)(void *, \fBElement\fP *), bool all=true) override"
.br
.ti -1c
.RI "virtual QVariant \fBgetProperty\fP (P_ID propertyId) const override"
.br
.ti -1c
.RI "virtual bool \fBsetProperty\fP (P_ID propertyId, const QVariant &) override"
.br
.ti -1c
.RI "virtual QVariant \fBpropertyDefault\fP (P_ID) const override"
.br
.ti -1c
.RI "virtual void \fBsetYoff\fP (qreal) override"
.br
.ti -1c
.RI "virtual QString \fBaccessibleInfo\fP () const override"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Ms::Trill::Type \fBtrillType\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 62 of file trill\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
