.TH "Ms::UP" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::UP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUP\fP &up) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QPointF \fBp\fP"
.br
.ti -1c
.RI "QPointF \fBoff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file slurtie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
