.TH "Ms::UpdateState" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::UpdateState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QRectF \fBrefresh\fP"
.br
.RI "area to update, canvas coordinates "
.ti -1c
.RI "bool \fB_playNote\fP { false }"
.br
.RI "play selected note after command "
.ti -1c
.RI "bool \fB_playChord\fP { false }"
.br
.RI "play whole chord for the selected note "
.ti -1c
.RI "bool \fB_selectionChanged\fP { false }"
.br
.ti -1c
.RI "QList< \fBScoreElement\fP * > \fB_deleteList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 275 of file score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
