.TH "Ms::VoiceDesc" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::VoiceDesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <musicxmlsupport\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBincrChordRests\fP (int s)"
.br
.ti -1c
.RI "int \fBnumberChordRests\fP () const"
.br
.ti -1c
.RI "int \fBnumberChordRests\fP (int s) const"
.br
.ti -1c
.RI "int \fBpreferredStaff\fP () const"
.br
.RI "Determine preferred staff for this voice\&. "
.ti -1c
.RI "void \fBsetStaff\fP (int s)"
.br
.ti -1c
.RI "int \fBstaff\fP () const"
.br
.ti -1c
.RI "void \fBsetVoice\fP (int v)"
.br
.ti -1c
.RI "int \fBvoice\fP () const"
.br
.ti -1c
.RI "void \fBsetVoice\fP (int s, int v)"
.br
.ti -1c
.RI "int \fBvoice\fP (int s) const"
.br
.ti -1c
.RI "void \fBsetOverlap\fP (bool b)"
.br
.ti -1c
.RI "bool \fBoverlaps\fP () const"
.br
.ti -1c
.RI "void \fBsetStaffAlloc\fP (int s, int i)"
.br
.ti -1c
.RI "int \fBstaffAlloc\fP (int s) const"
.br
.ti -1c
.RI "QString \fBtoString\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The description of a single voice in a MusicXML part\&. 
.PP
Definition at line 68 of file musicxmlsupport\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
