.TH "Ms::VBox" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::VBox \- vertical frame  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <box\&.h>\fP
.PP
Inherits \fBMs::Box\fP\&.
.PP
Inherited by \fBMs::FBox\fP, and \fBMs::TBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVBox\fP (\fBScore\fP *score)"
.br
.ti -1c
.RI "virtual \fBVBox\fP * \fBclone\fP () const override"
.br
.ti -1c
.RI "virtual ElementType \fBtype\fP () const override"
.br
.ti -1c
.RI "virtual void \fBlayout\fP () override"
.br
.ti -1c
.RI "virtual QPointF \fBgetGrip\fP (Grip) const override"
.br
.ti -1c
.RI "virtual void \fBsetGrip\fP (Grip, const QPointF &) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
vertical frame 
.PP
Definition at line 134 of file box\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
