.TH "Ms::ValidatorMessageHandler" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ValidatorMessageHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <musicxmlsupport\&.h>\fP
.PP
Inherits QAbstractMessageHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBgetErrors\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhandleMessage\fP (QtMsgType type, const QString &description, const QUrl &identifier, const QSourceLocation &sourceLocation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message handler for the MusicXML schema validator QXmlSchemaValidator\&. 
.PP
Definition at line 185 of file musicxmlsupport\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
