.TH "Ms::VoltaObj" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::VoltaObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::BasicDrawObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVoltaObj\fP (\fBCapella\fP *c)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBreadCapx\fP (\fBXmlReader\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx0\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "bool \fBbLeft\fP"
.br
.ti -1c
.RI "bool \fBbRight\fP"
.br
.ti -1c
.RI "bool \fBbDotted\fP"
.br
.ti -1c
.RI "bool \fBallNumbers\fP"
.br
.ti -1c
.RI "int \fBfrom\fP"
.br
.ti -1c
.RI "int \fBto\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 384 of file capella\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
