.TH "Ms::Workspace" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::Workspace
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetDirty\fP (bool val=true)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorkspace\fP (const QString &n, const QString &p, bool d, bool r)"
.br
.ti -1c
.RI "QString \fBpath\fP () const"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &s)"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &s)"
.br
.ti -1c
.RI "bool \fBdirty\fP () const"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP ()"
.br
.ti -1c
.RI "void \fBread\fP (\fBXmlReader\fP &)"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "bool \fBreadOnly\fP () const"
.br
.ti -1c
.RI "void \fBsetReadOnly\fP (bool val)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitWorkspace\fP ()"
.br
.ti -1c
.RI "static QList< \fBWorkspace\fP * > & \fBworkspaces\fP ()"
.br
.ti -1c
.RI "static \fBWorkspace\fP * \fBcreateNewWorkspace\fP (const QString &name)"
.br
.ti -1c
.RI "static void \fBwriteBuiltinWorkspace\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBWorkspace\fP * \fBcurrentWorkspace\fP"
.br
.ti -1c
.RI "static bool \fBworkspacesRead\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file workspace\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
