.TH "Ms::XmlNesting" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::XmlNesting
.SH SYNOPSIS
.br
.PP
.PP
Inherits QStack< QString >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlNesting\fP (QString *s)"
.br
.ti -1c
.RI "void \fBpushToken\fP (const QString &t)"
.br
.ti -1c
.RI "void \fBpushB\fP ()"
.br
.ti -1c
.RI "void \fBpushI\fP ()"
.br
.ti -1c
.RI "void \fBpushU\fP ()"
.br
.ti -1c
.RI "QString \fBpopToken\fP ()"
.br
.ti -1c
.RI "void \fBpopToken\fP (const char *t)"
.br
.ti -1c
.RI "void \fBpopB\fP ()"
.br
.ti -1c
.RI "void \fBpopI\fP ()"
.br
.ti -1c
.RI "void \fBpopU\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1252 of file text\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
