.TH "Ms::XmlWriter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::XmlWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTextStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlWriter\fP (\fBScore\fP *)"
.br
.ti -1c
.RI "\fBXmlWriter\fP (\fBScore\fP *s, QIODevice *dev)"
.br
.ti -1c
.RI "int \fBspannerId\fP () const"
.br
.ti -1c
.RI "int \fBcurTick\fP () const"
.br
.ti -1c
.RI "int \fBcurTrack\fP () const"
.br
.ti -1c
.RI "int \fBtickDiff\fP () const"
.br
.ti -1c
.RI "int \fBtrackDiff\fP () const"
.br
.ti -1c
.RI "bool \fBclipboardmode\fP () const"
.br
.ti -1c
.RI "bool \fBexcerptmode\fP () const"
.br
.ti -1c
.RI "bool \fBwriteOmr\fP () const"
.br
.ti -1c
.RI "int \fBnextTupletId\fP ()"
.br
.ti -1c
.RI "int \fBnextBeamId\fP ()"
.br
.ti -1c
.RI "void \fBsetClipboardmode\fP (bool v)"
.br
.ti -1c
.RI "void \fBsetExcerptmode\fP (bool v)"
.br
.ti -1c
.RI "void \fBsetWriteOmr\fP (bool v)"
.br
.ti -1c
.RI "void \fBsetTupletId\fP (int v)"
.br
.ti -1c
.RI "void \fBsetBeamId\fP (int v)"
.br
.ti -1c
.RI "void \fBsetSpannerId\fP (int v)"
.br
.ti -1c
.RI "void \fBsetCurTick\fP (int v)"
.br
.ti -1c
.RI "void \fBsetCurTrack\fP (int v)"
.br
.ti -1c
.RI "void \fBsetTickDiff\fP (int v)"
.br
.ti -1c
.RI "void \fBsetTrackDiff\fP (int v)"
.br
.ti -1c
.RI "void \fBincCurTick\fP (int v)"
.br
.ti -1c
.RI "int \fBaddSpanner\fP (const \fBSpanner\fP *)"
.br
.ti -1c
.RI "const \fBSpanner\fP * \fBfindSpanner\fP (int id)"
.br
.ti -1c
.RI "int \fBspannerId\fP (const \fBSpanner\fP *)"
.br
.ti -1c
.RI "void \fBsTag\fP (const char *name, \fBSpatium\fP sp)"
.br
.ti -1c
.RI "void \fBpTag\fP (const char *name, PlaceText)"
.br
.ti -1c
.RI "void \fBheader\fP ()"
.br
.ti -1c
.RI "void \fBstag\fP (const QString &)"
.br
.ti -1c
.RI "void \fBetag\fP ()"
.br
.ti -1c
.RI "void \fBtagE\fP (const QString &)"
.br
.ti -1c
.RI "void \fBtagE\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBntag\fP (const char *name)"
.br
.ti -1c
.RI "void \fBnetag\fP (const char *name)"
.br
.ti -1c
.RI "void \fBtag\fP (P_ID id, void *data, void *defaultVal)"
.br
.ti -1c
.RI "void \fBtag\fP (P_ID id, QVariant data, QVariant defaultData=QVariant())"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, QVariant data, QVariant defaultData=QVariant())"
.br
.ti -1c
.RI "void \fBtag\fP (const QString &, QVariant data)"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, const char *s)"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, const QString &s)"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, const QWidget *)"
.br
.ti -1c
.RI "void \fBwriteXml\fP (const QString &, QString s)"
.br
.ti -1c
.RI "void \fBdump\fP (int len, const unsigned char *p)"
.br
.ti -1c
.RI "void \fBsetFilter\fP (\fBSelectionFilter\fP f)"
.br
.ti -1c
.RI "bool \fBcanWrite\fP (const \fBElement\fP *) const"
.br
.ti -1c
.RI "bool \fBcanWriteVoice\fP (int track) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBxmlString\fP (const QString &)"
.br
.ti -1c
.RI "static QString \fBxmlString\fP (ushort c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file xml\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
