.TH "Ms::ZitaReverb" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ms::ZitaReverb
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (float fsamp)"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "virtual void \fBprocess\fP (int n, float *inp, float *out)"
.br
.ti -1c
.RI "void \fBset_delay\fP (float v)"
.br
.ti -1c
.RI "float \fBdelay\fP () const"
.br
.ti -1c
.RI "void \fBset_xover\fP (float v)"
.br
.ti -1c
.RI "float \fBxover\fP () const"
.br
.ti -1c
.RI "void \fBset_rtlow\fP (float v)"
.br
.ti -1c
.RI "float \fBrtlow\fP () const"
.br
.ti -1c
.RI "void \fBset_rtmid\fP (float v)"
.br
.ti -1c
.RI "float \fBrtmid\fP () const"
.br
.ti -1c
.RI "void \fBset_fdamp\fP (float v)"
.br
.ti -1c
.RI "float \fBfdamp\fP () const"
.br
.ti -1c
.RI "void \fBset_eq1fr\fP (float f)"
.br
.ti -1c
.RI "float \fBeq1fr\fP () const"
.br
.ti -1c
.RI "void \fBset_eq1gn\fP (float f)"
.br
.ti -1c
.RI "float \fBeq1gn\fP () const"
.br
.ti -1c
.RI "void \fBset_eq2fr\fP (float f)"
.br
.ti -1c
.RI "float \fBeq2fr\fP () const"
.br
.ti -1c
.RI "void \fBset_eq2gn\fP (float f)"
.br
.ti -1c
.RI "float \fBeq2gn\fP () const"
.br
.ti -1c
.RI "void \fBset_opmix\fP (float v)"
.br
.ti -1c
.RI "float \fBopmix\fP () const"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const"
.br
.ti -1c
.RI "virtual \fBEffectGui\fP * \fBgui\fP ()"
.br
.ti -1c
.RI "virtual const std::vector< \fBParDescr\fP > & \fBparDescr\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetNValue\fP (int parameter, double value)"
.br
.ti -1c
.RI "virtual double \fBnvalue\fP (int idx) const"
.br
.ti -1c
.RI "virtual \fBSynthesizerGroup\fP \fBstate\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetState\fP (const \fBSynthesizerGroup\fP &)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 200 of file zita\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
