.TH "mscore/musicxml.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mscore/musicxml.h
.SH SYNOPSIS
.br
.PP
\fC#include 'libmscore/fraction\&.h'\fP
.br
\fC#include 'libmscore/mscore\&.h'\fP
.br
\fC#include 'libmscore/pitchspelling\&.h'\fP
.br
\fC#include 'libmscore/line\&.h'\fP
.br
\fC#include 'importxmlfirstpass\&.h'\fP
.br
\fC#include 'musicxmlsupport\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMs::MusicXmlPartGroup\fP"
.br
.ti -1c
.RI "struct \fBMs::CreditWords\fP"
.br
.ti -1c
.RI "class \fBMs::JumpMarkerDesc\fP"
.br
.ti -1c
.RI "class \fBMs::SlurDesc\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< CreditWords * > \fBMs::CreditWordsList\fP"
.br
.ti -1c
.RI "typedef CreditWordsList::iterator \fBMs::iCreditWords\fP"
.br
.ti -1c
.RI "typedef CreditWordsList::const_iterator \fBMs::ciCreditWords\fP"
.br
.ti -1c
.RI "typedef QList< JumpMarkerDesc > \fBMs::JumpMarkerDescList\fP"
.br
.ti -1c
.RI "typedef std::vector< MusicXmlPartGroup * > \fBMs::MusicXmlPartGroupList\fP"
.br
.ti -1c
.RI "typedef QMap< SLine *, QPair< int, int > > \fBMs::MusicXmlSpannerMap\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNoSystem\fP = 0, \fBTopSystem\fP = 1, \fBNewSystem\fP = 2, \fBNewPage\fP = 3 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBMs::MAX_LYRICS\fP = 16"
.br
.ti -1c
.RI "const int \fBMs::MAX_PART_GROUPS\fP = 8"
.br
.ti -1c
.RI "const int \fBMs::MAX_NUMBER_LEVEL\fP = 6"
.br
.ti -1c
.RI "const int \fBMs::MAX_BRACKETS\fP = 9"
.br
.ti -1c
.RI "const int \fBMs::MAX_DASHES\fP = 8"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of class MusicXML 
.PP
Definition in file \fBmusicxml\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
