.TH "MutexLocker" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MutexLocker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutexLocker\fP (GooMutex *mutexA)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file GooMutex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
