.TH "bww2mxml/mxmlwriter.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/mxmlwriter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QtDebug>\fP
.br
\fC#include 'mxmlwriter\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Output writer for BWW to MusicXML converter\&. 
.PP
Definition in file \fBmxmlwriter\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
