.TH "N_func" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
N_func
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP (float v)"
.br
.ti -1c
.RI "void \fBsetv\fP (int i, float v)"
.br
.ti -1c
.RI "void \fBclrv\fP (int i)"
.br
.ti -1c
.RI "float \fBvs\fP (int i) const"
.br
.ti -1c
.RI "int \fBst\fP (int i) const"
.br
.ti -1c
.RI "float \fBvi\fP (int n) const"
.br
.ti -1c
.RI "void \fBwrite\fP (FILE *)"
.br
.ti -1c
.RI "void \fBread\fP (QFile *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file addsynth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
