.TH "NameTree" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameTree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBXRef\fP *xref, \fBObject\fP *tree)"
.br
.ti -1c
.RI "GBool \fBlookup\fP (\fBGooString\fP *name, \fBObject\fP *obj)"
.br
.ti -1c
.RI "int \fBnumEntries\fP ()"
.br
.ti -1c
.RI "\fBObject\fP \fBgetValue\fP (int i)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP (int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file Catalog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
