.TH "NameToCharCodeEntry" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameToCharCodeEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "CharCode \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file NameToCharCode\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
