.TH "Netscape_certificate_sequence" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Netscape_certificate_sequence
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP) *certs"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 545 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
