.TH "libmscore/note.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/note.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include 'note\&.h'\fP
.br
\fC#include 'score\&.h'\fP
.br
\fC#include 'chord\&.h'\fP
.br
\fC#include 'sym\&.h'\fP
.br
\fC#include 'xml\&.h'\fP
.br
\fC#include 'slur\&.h'\fP
.br
\fC#include 'tie\&.h'\fP
.br
\fC#include 'text\&.h'\fP
.br
\fC#include 'clef\&.h'\fP
.br
\fC#include 'staff\&.h'\fP
.br
\fC#include 'pitchspelling\&.h'\fP
.br
\fC#include 'arpeggio\&.h'\fP
.br
\fC#include 'tremolo\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'image\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'tuplet\&.h'\fP
.br
\fC#include 'articulation\&.h'\fP
.br
\fC#include 'drumset\&.h'\fP
.br
\fC#include 'segment\&.h'\fP
.br
\fC#include 'measure\&.h'\fP
.br
\fC#include 'undo\&.h'\fP
.br
\fC#include 'part\&.h'\fP
.br
\fC#include 'stafftype\&.h'\fP
.br
\fC#include 'stringdata\&.h'\fP
.br
\fC#include 'fret\&.h'\fP
.br
\fC#include 'harmony\&.h'\fP
.br
\fC#include 'fingering\&.h'\fP
.br
\fC#include 'bend\&.h'\fP
.br
\fC#include 'accidental\&.h'\fP
.br
\fC#include 'page\&.h'\fP
.br
\fC#include 'icon\&.h'\fP
.br
\fC#include 'notedot\&.h'\fP
.br
\fC#include 'spanner\&.h'\fP
.br
\fC#include 'glissando\&.h'\fP
.br
\fC#include 'bagpembell\&.h'\fP
.br
\fC#include 'hairpin\&.h'\fP
.br
\fC#include 'textline\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMs::NoteHeadName\fP"
.br
.ti -1c
.RI "class \fBMs::NoteEditData\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of classes Note and ShadowNote\&. 
.PP
Definition in file \fBnote\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
