.TH "ObjectKey" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectKey
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPopplerCacheKey\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectKey\fP (int numA, int genA)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPopplerCacheKey\fP &key) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBgen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file PopplerCache\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
