.TH "ObjectStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectStream\fP (\fBXRef\fP *xref, int objStrNumA, int recursion=0)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBgetObjStrNum\fP ()"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObject\fP (int objIdx, int objNum, \fBObject\fP *obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file XRef\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
