.TH "ObjectStreamKey" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectStreamKey
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPopplerCacheKey\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectStreamKey\fP (int num)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPopplerCacheKey\fP &key) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBobjStrNum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file XRef\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
