.TH "OCDisplayNode" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OCDisplayNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP ()"
.br
.ti -1c
.RI "\fBOptionalContentGroup\fP * \fBgetOCG\fP ()"
.br
.ti -1c
.RI "int \fBgetNumChildren\fP ()"
.br
.ti -1c
.RI "\fBOCDisplayNode\fP * \fBgetChild\fP (int idx)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBOCDisplayNode\fP * \fBparse\fP (\fBObject\fP *obj, \fBOCGs\fP *oc, \fBXRef\fP *xref, int recursion=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file OptionalContent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
