.TH "ocsp_cert_status_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_cert_status_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   ASN1_NULL * \fBgood\fP"
.br
.ti -1c
.RI "   \fBOCSP_REVOKEDINFO\fP * \fBrevoked\fP"
.br
.ti -1c
.RI "   ASN1_NULL * \fBunknown\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 236 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
