.TH "ocsp_single_response_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_single_response_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP) *singleExtensions"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOCSP_CERTID\fP * \fBcertId\fP"
.br
.ti -1c
.RI "\fBOCSP_CERTSTATUS\fP * \fBcertStatus\fP"
.br
.ti -1c
.RI "\fBASN1_GENERALIZEDTIME\fP * \fBthisUpdate\fP"
.br
.ti -1c
.RI "\fBASN1_GENERALIZEDTIME\fP * \fBnextUpdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 253 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
