.TH "Openscore" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Openscore
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Q_INVOKABLE QString \fBgetName\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetName\fP (QString name)"
.br
.ti -1c
.RI "Q_INVOKABLE int \fBselectMeasure\fP (int id, int colorOn)"
.br
.ti -1c
.RI "Q_INVOKABLE int \fBnumberOfTU\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE QString \fBgetName\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetName\fP (QString name)"
.br
.ti -1c
.RI "Q_INVOKABLE int \fBselectMeasure\fP (int id, int colorOn)"
.br
.ti -1c
.RI "Q_INVOKABLE int \fBnumberOfTU\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file mscoreapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
