.TH "Openmscore" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Openmscore
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenmscore\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "Q_INVOKABLE Score * \fBcurrentScore\fP () const"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBnewFile\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE QString \fBgetLocaleISOCode\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE bool \fBopenPDF\fP (QString path)"
.br
.ti -1c
.RI "\fBOpenmscore\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "Q_INVOKABLE Score * \fBcurrentScore\fP () const"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBnewFile\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE QString \fBgetLocaleISOCode\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE bool \fBopenPDF\fP (QString path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file mscoreapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
