.TH "OptionalContentGroup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionalContentGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBOn\fP, \fBOff\fP }"
.br
.ti -1c
.RI "enum \fBUsageState\fP { \fBocUsageOn\fP, \fBocUsageOff\fP, \fBocUsageUnset\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionalContentGroup\fP (\fBDict\fP *dict)"
.br
.ti -1c
.RI "\fBOptionalContentGroup\fP (\fBGooString\fP *label)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetName\fP () const"
.br
.ti -1c
.RI "\fBRef\fP \fBgetRef\fP () const"
.br
.ti -1c
.RI "void \fBsetRef\fP (const \fBRef\fP ref)"
.br
.ti -1c
.RI "State \fBgetState\fP ()"
.br
.ti -1c
.RI "void \fBsetState\fP (State state)"
.br
.ti -1c
.RI "UsageState \fBgetViewState\fP ()"
.br
.ti -1c
.RI "UsageState \fBgetPrintState\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file OptionalContent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
