.TH "OTV_ValidatorRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OTV_ValidatorRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Validator \fBroot\fP"
.br
.ti -1c
.RI "FT_UInt \fBtype_count\fP"
.br
.ti -1c
.RI "OTV_Validate_Func * \fBtype_funcs\fP"
.br
.ti -1c
.RI "FT_UInt \fBlookup_count\fP"
.br
.ti -1c
.RI "FT_UInt \fBglyph_count\fP"
.br
.ti -1c
.RI "FT_UInt \fBnesting_level\fP"
.br
.ti -1c
.RI "OTV_Validate_Func \fBfunc\fP [3]"
.br
.ti -1c
.RI "FT_UInt \fBextra1\fP"
.br
.ti -1c
.RI "FT_UInt \fBextra2\fP"
.br
.ti -1c
.RI "FT_Bytes \fBextra3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file otvcommn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
