.TH "OutlineItem" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutlineItem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutlineItem\fP (\fBDict\fP *dict, \fBXRef\fP *xrefA)"
.br
.ti -1c
.RI "void \fBopen\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "Unicode * \fBgetTitle\fP ()"
.br
.ti -1c
.RI "int \fBgetTitleLength\fP ()"
.br
.ti -1c
.RI "\fBLinkAction\fP * \fBgetAction\fP ()"
.br
.ti -1c
.RI "GBool \fBisOpen\fP ()"
.br
.ti -1c
.RI "GBool \fBhasKids\fP ()"
.br
.ti -1c
.RI "\fBGooList\fP * \fBgetKids\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGooList\fP * \fBreadItemList\fP (\fBObject\fP *firstItemRef, \fBObject\fP *lastItemRef, \fBXRef\fP *xrefA)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file Outline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
