.TH "Outline" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outline
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutline\fP (\fBObject\fP *outlineObj, \fBXRef\fP *xref)"
.br
.ti -1c
.RI "\fBGooList\fP * \fBgetItems\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file Outline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
