.TH "OutStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutStream
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFileOutStream\fP, and \fBPoppler::QIODeviceOutStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBincRef\fP ()"
.br
.ti -1c
.RI "int \fBdecRef\fP ()"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()=0"
.br
.ti -1c
.RI "virtual Goffset \fBgetPos\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBput\fP (char c)=0"
.br
.ti -1c
.RI "virtual void \fBprintf\fP (const char *format,\&.\&.\&.) GCC_PRINTF_FORMAT(2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 248 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
