.TH "OVE::OffsetElement" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::OffsetElement
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOVE::Articulation\fP, \fBOVE::MusicData\fP, and \fBOVE::Staff\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetXOffset\fP (int offset)"
.br
.ti -1c
.RI "virtual int \fBgetXOffset\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetYOffset\fP (int offset)"
.br
.ti -1c
.RI "virtual int \fBgetYOffset\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 592 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
