.TH "OVE::NoteContainer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::NoteContainer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::LengthElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIsGrace\fP (bool grace)"
.br
.ti -1c
.RI "bool \fBgetIsGrace\fP () const"
.br
.ti -1c
.RI "void \fBsetIsCue\fP (bool cue)"
.br
.ti -1c
.RI "bool \fBgetIsCue\fP () const"
.br
.ti -1c
.RI "void \fBsetIsRest\fP (bool rest)"
.br
.ti -1c
.RI "bool \fBgetIsRest\fP () const"
.br
.ti -1c
.RI "void \fBsetIsRaw\fP (bool raw)"
.br
.ti -1c
.RI "bool \fBgetIsRaw\fP () const"
.br
.ti -1c
.RI "void \fBsetNoteType\fP (NoteType type)"
.br
.ti -1c
.RI "NoteType \fBgetNoteType\fP () const"
.br
.ti -1c
.RI "void \fBsetDot\fP (int dot)"
.br
.ti -1c
.RI "int \fBgetDot\fP () const"
.br
.ti -1c
.RI "void \fBsetGraceNoteType\fP (NoteType type)"
.br
.ti -1c
.RI "NoteType \fBgetGraceNoteType\fP () const"
.br
.ti -1c
.RI "void \fBsetInBeam\fP (bool in)"
.br
.ti -1c
.RI "bool \fBgetInBeam\fP () const"
.br
.ti -1c
.RI "void \fBsetStemUp\fP (bool up)"
.br
.ti -1c
.RI "bool \fBgetStemUp\fP (void) const"
.br
.ti -1c
.RI "void \fBsetShowStem\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowStem\fP () const"
.br
.ti -1c
.RI "void \fBsetStemLength\fP (int line)"
.br
.ti -1c
.RI "int \fBgetStemLength\fP () const"
.br
.ti -1c
.RI "void \fBsetTuplet\fP (int tuplet)"
.br
.ti -1c
.RI "int \fBgetTuplet\fP () const"
.br
.ti -1c
.RI "void \fBsetSpace\fP (int space)"
.br
.ti -1c
.RI "int \fBgetSpace\fP () const"
.br
.ti -1c
.RI "void \fBaddNoteRest\fP (\fBNote\fP *note)"
.br
.ti -1c
.RI "QList< \fBNote\fP * > \fBgetNotesRests\fP () const"
.br
.ti -1c
.RI "void \fBaddArticulation\fP (\fBArticulation\fP *art)"
.br
.ti -1c
.RI "QList< \fBArticulation\fP * > \fBgetArticulations\fP () const"
.br
.ti -1c
.RI "void \fBsetNoteShift\fP (int octave)"
.br
.ti -1c
.RI "int \fBgetNoteShift\fP () const"
.br
.ti -1c
.RI "int \fBgetOffsetStaff\fP () const"
.br
.ti -1c
.RI "int \fBgetDuration\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1261 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
