.TH "OVE::Text" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Text
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::LengthElement\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : char { \fBRehearsal\fP, \fBSystemText\fP, \fBMeasureText\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTextType\fP (Type type)"
.br
.ti -1c
.RI "Type \fBgetTextType\fP () const"
.br
.ti -1c
.RI "void \fBsetHorizontalMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetHorizontalMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetVerticalMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetVerticalMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetLineThick\fP (int thick)"
.br
.ti -1c
.RI "int \fBgetLineThick\fP () const"
.br
.ti -1c
.RI "void \fBsetText\fP (const QString &text)"
.br
.ti -1c
.RI "QString \fBgetText\fP () const"
.br
.ti -1c
.RI "void \fBsetWidth\fP (int width)"
.br
.ti -1c
.RI "int \fBgetWidth\fP () const"
.br
.ti -1c
.RI "void \fBsetHeight\fP (int height)"
.br
.ti -1c
.RI "int \fBgetHeight\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1798 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
