.TH "OVE::Tempo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Tempo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetLeftNoteType\fP (int type)"
.br
.ti -1c
.RI "NoteType \fBgetLeftNoteType\fP () const"
.br
.ti -1c
.RI "void \fBsetShowMark\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowMark\fP () const"
.br
.ti -1c
.RI "void \fBsetShowBeforeText\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowBeforeText\fP () const"
.br
.ti -1c
.RI "void \fBsetShowParenthesis\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowParenthesis\fP () const"
.br
.ti -1c
.RI "void \fBsetTypeTempo\fP (double tempo)"
.br
.ti -1c
.RI "double \fBgetTypeTempo\fP () const"
.br
.ti -1c
.RI "double \fBgetQuarterTempo\fP () const"
.br
.ti -1c
.RI "void \fBsetLeftText\fP (const QString &str)"
.br
.ti -1c
.RI "QString \fBgetLeftText\fP () const"
.br
.ti -1c
.RI "void \fBsetRightText\fP (const QString &str)"
.br
.ti -1c
.RI "QString \fBgetRightText\fP () const"
.br
.ti -1c
.RI "void \fBsetSwingEighth\fP (bool swing)"
.br
.ti -1c
.RI "bool \fBgetSwingEighth\fP () const"
.br
.ti -1c
.RI "void \fBsetRightNoteType\fP (int type)"
.br
.ti -1c
.RI "NoteType \fBgetRightNoteType\fP () const"
.br
.ti -1c
.RI "void \fBsetLeftNoteDot\fP (bool showDot)"
.br
.ti -1c
.RI "bool \fBgetLeftNoteDot\fP () const"
.br
.ti -1c
.RI "void \fBsetRightNoteDot\fP (bool showDot)"
.br
.ti -1c
.RI "bool \fBgetRightNoteDot\fP () const"
.br
.ti -1c
.RI "void \fBsetRightSideType\fP (int type)"
.br
.ti -1c
.RI "int \fBgetRightSideType\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1740 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
