.TH "OVE::MidiData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MidiData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::TickElement\fP\&.
.PP
Inherited by \fBOVE::MidiChannelPressure\fP, \fBOVE::MidiController\fP, \fBOVE::MidiPitchWheel\fP, and \fBOVE::MidiProgramChange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "MidiType \fBgetMidiType\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MidiType \fBmidiType_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 659 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
