.TH "OVE::Decorator" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Decorator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : char { \fBDotted_Barline\fP = 0, \fBArticulation\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDecoratorType\fP (Type type)"
.br
.ti -1c
.RI "Type \fBgetDecoratorType\fP () const"
.br
.ti -1c
.RI "void \fBsetArticulationType\fP (ArticulationType type)"
.br
.ti -1c
.RI "ArticulationType \fBgetArticulationType\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1398 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
