.TH "OVE::Page" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Page
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetBeginLine\fP (int line)"
.br
.ti -1c
.RI "int \fBgetBeginLine\fP () const"
.br
.ti -1c
.RI "void \fBsetLineCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetLineCount\fP () const"
.br
.ti -1c
.RI "void \fBsetLineInterval\fP (int \fBinterval\fP)"
.br
.ti -1c
.RI "int \fBgetLineInterval\fP () const"
.br
.ti -1c
.RI "void \fBsetStaffInterval\fP (int \fBinterval\fP)"
.br
.ti -1c
.RI "int \fBgetStaffInterval\fP () const"
.br
.ti -1c
.RI "void \fBsetStaffInlineInterval\fP (int \fBinterval\fP)"
.br
.ti -1c
.RI "int \fBgetStaffInlineInterval\fP () const"
.br
.ti -1c
.RI "void \fBsetLineBarCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetLineBarCount\fP () const"
.br
.ti -1c
.RI "void \fBsetPageLineCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetPageLineCount\fP () const"
.br
.ti -1c
.RI "void \fBsetLeftMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetLeftMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetTopMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetTopMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetRightMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetRightMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetBottomMargin\fP (int margin)"
.br
.ti -1c
.RI "int \fBgetBottomMargin\fP () const"
.br
.ti -1c
.RI "void \fBsetPageWidth\fP (int width)"
.br
.ti -1c
.RI "int \fBgetPageWidth\fP () const"
.br
.ti -1c
.RI "void \fBsetPageHeight\fP (int height)"
.br
.ti -1c
.RI "int \fBgetPageHeight\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 974 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
