.TH "OVE::GroupChunk" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::GroupChunk
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::Chunk\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCountBlock\fP * \fBgetCountBlock\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCountBlock\fP * \fBchildCount_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2318 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
