.TH "OVE::MeasurePos" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MeasurePos
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetMeasure\fP (int measure)"
.br
.ti -1c
.RI "int \fBgetMeasure\fP () const"
.br
.ti -1c
.RI "void \fBsetOffset\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetOffset\fP () const"
.br
.ti -1c
.RI "\fBMeasurePos\fP \fBshiftMeasure\fP (int measure) const"
.br
.ti -1c
.RI "\fBMeasurePos\fP \fBshiftOffset\fP (int offset) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMeasurePos\fP &mp) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBMeasurePos\fP &mp) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMeasurePos\fP &mp) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBMeasurePos\fP &mp) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBMeasurePos\fP &mp) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBMeasurePos\fP &mp) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 519 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
