.TH "OVE::OveOrganizer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::OveOrganizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOveOrganizer\fP (\fBOveSong\fP *ove)"
.br
.ti -1c
.RI "void \fBorganize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2577 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
