.TH "OVE::MusicData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MusicData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::TickElement\fP, \fBOVE::PairElement\fP, and \fBOVE::OffsetElement\fP\&.
.PP
Inherited by \fBOVE::BarNumber\fP, \fBOVE::Beam\fP, \fBOVE::Clef\fP, \fBOVE::Decorator\fP, \fBOVE::Dynamics\fP, \fBOVE::Expressions\fP, \fBOVE::Glissando\fP, \fBOVE::Harmony\fP, \fBOVE::HarpPedal\fP, \fBOVE::Key\fP, \fBOVE::KuoHao\fP, \fBOVE::Lyric\fP, \fBOVE::MeasureRepeat\fP, \fBOVE::MultiMeasureRest\fP, \fBOVE::NoteContainer\fP, \fBOVE::NumericEnding\fP, \fBOVE::OctaveShift\fP, \fBOVE::OctaveShiftEndPoint\fP, \fBOVE::Pedal\fP, \fBOVE::RepeatSymbol\fP, \fBOVE::Slur\fP, \fBOVE::Tempo\fP, \fBOVE::Text\fP, \fBOVE::Tie\fP, \fBOVE::TimeSignature\fP, \fBOVE::Tuplet\fP, \fBOVE::Wedge\fP, and \fBOVE::WedgeEndPoint\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBXmlDataType\fP : char { \fBAttributes\fP = 0, \fBNoteBeam\fP, \fBNotations\fP, \fBDirection\fP, \fBNone\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "MusicDataType \fBgetMusicDataType\fP () const"
.br
.ti -1c
.RI "void \fBsetShow\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShow\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (unsigned int \fBcolor\fP)"
.br
.ti -1c
.RI "unsigned int \fBgetColor\fP () const"
.br
.ti -1c
.RI "void \fBsetVoice\fP (unsigned int voice)"
.br
.ti -1c
.RI "unsigned int \fBgetVoice\fP () const"
.br
.ti -1c
.RI "void \fBcopyCommonBlock\fP (const \fBMusicData\fP &source)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static XmlDataType \fBgetXmlDataType\fP (MusicDataType type)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MusicDataType \fBmusicDataType_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 623 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
