.TH "OVE::MidiChannelPressure" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MidiChannelPressure
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MidiData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetPressure\fP (int pressure)"
.br
.ti -1c
.RI "int \fBgetPressure\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2056 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
