.TH "OVE::PairElement" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::PairElement
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeasurePos\fP * \fBstart\fP () const"
.br
.ti -1c
.RI "\fBMeasurePos\fP * \fBstop\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 546 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
