.TH "OVE::IOVEStreamLoader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::IOVEStreamLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOVE::OveSerialize\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetNotify\fP (\fBIOveNotify\fP *notify)=0"
.br
.ti -1c
.RI "virtual void \fBsetFileStream\fP (unsigned char *buffer, unsigned int size)=0"
.br
.ti -1c
.RI "virtual void \fBsetOve\fP (\fBOveSong\fP *ove)=0"
.br
.ti -1c
.RI "virtual bool \fBload\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBrelease\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 486 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
