.TH "OVE::BasicParse" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::BasicParse
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOVE::BarsParse\fP, \fBOVE::GroupParse\fP\fC [private]\fP, \fBOVE::LineGroupParse\fP, \fBOVE::LyricChunkParse\fP, \fBOVE::OvscParse\fP, \fBOVE::PageGroupParse\fP, \fBOVE::StaffCountGetter\fP, \fBOVE::TitleChunkParse\fP, and \fBOVE::TrackParse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicParse\fP (\fBOveSong\fP *ove)"
.br
.ti -1c
.RI "void \fBsetNotify\fP (\fBIOveNotify\fP *notify)"
.br
.ti -1c
.RI "virtual bool \fBparse\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBreadBuffer\fP (\fBBlock\fP &placeHolder, int size)"
.br
.ti -1c
.RI "bool \fBjump\fP (int offset)"
.br
.ti -1c
.RI "void \fBmessageOut\fP (const QString &str)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBOveSong\fP * \fBove_\fP"
.br
.ti -1c
.RI "\fBStreamHandle\fP * \fBhandle_\fP"
.br
.ti -1c
.RI "\fBIOveNotify\fP * \fBnotify_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2331 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
