.TH "OVE::FixedBlock" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::FixedBlock
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::Block\fP\&.
.PP
Inherited by \fBOVE::CountBlock\fP, \fBOVE::NameBlock\fP, and \fBOVE::SizeBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFixedBlock\fP (unsigned int count)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2224 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
