.TH "OVE::HarpPedal" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::HarpPedal
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetShowType\fP (int type)"
.br
.ti -1c
.RI "int \fBgetShowType\fP () const"
.br
.ti -1c
.RI "void \fBsetShowCharFlag\fP (int flag)"
.br
.ti -1c
.RI "int \fBgetShowCharFlag\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1666 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
