.TH "OVE::Voice" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Voice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetChannel\fP (int channel)"
.br
.ti -1c
.RI "int \fBgetChannel\fP () const"
.br
.ti -1c
.RI "void \fBsetVolume\fP (int volume)"
.br
.ti -1c
.RI "int \fBgetVolume\fP () const"
.br
.ti -1c
.RI "void \fBsetPitchShift\fP (int pitchShift)"
.br
.ti -1c
.RI "int \fBgetPitchShift\fP () const"
.br
.ti -1c
.RI "void \fBsetPan\fP (int pan)"
.br
.ti -1c
.RI "int \fBgetPan\fP () const"
.br
.ti -1c
.RI "void \fBsetPatch\fP (int patch)"
.br
.ti -1c
.RI "int \fBgetPatch\fP () const"
.br
.ti -1c
.RI "void \fBsetStemType\fP (int stemType)"
.br
.ti -1c
.RI "int \fBgetStemType\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetDefaultPatch\fP ()"
.br
.ti -1c
.RI "static int \fBgetDefaultVolume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 798 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
