.TH "OVE::Beam" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Beam
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::PairEnds\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIsGrace\fP (bool grace)"
.br
.ti -1c
.RI "bool \fBgetIsGrace\fP () const"
.br
.ti -1c
.RI "void \fBaddLine\fP (const \fBMeasurePos\fP &startMp, const \fBMeasurePos\fP &endMp)"
.br
.ti -1c
.RI "const QList< QPair< \fBMeasurePos\fP, \fBMeasurePos\fP > > \fBgetLines\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1339 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
