.TH "OVE::TimeSignature" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::TimeSignature
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetNumerator\fP (int numerator)"
.br
.ti -1c
.RI "int \fBgetNumerator\fP () const"
.br
.ti -1c
.RI "void \fBsetDenominator\fP (int denominator)"
.br
.ti -1c
.RI "int \fBgetDenominator\fP () const"
.br
.ti -1c
.RI "void \fBsetIsSymbol\fP (bool symbol)"
.br
.ti -1c
.RI "bool \fBgetIsSymbol\fP () const"
.br
.ti -1c
.RI "void \fBsetBeatLength\fP (int length)"
.br
.ti -1c
.RI "int \fBgetBeatLength\fP () const"
.br
.ti -1c
.RI "void \fBsetBarLength\fP (int length)"
.br
.ti -1c
.RI "int \fBgetBarLength\fP () const"
.br
.ti -1c
.RI "void \fBaddBeat\fP (int startUnit, int lengthUnit, int startTick)"
.br
.ti -1c
.RI "void \fBendAddBeat\fP ()"
.br
.ti -1c
.RI "int \fBgetUnits\fP () const"
.br
.ti -1c
.RI "void \fBsetReplaceFont\fP (bool replace)"
.br
.ti -1c
.RI "bool \fBgetReplaceFont\fP () const"
.br
.ti -1c
.RI "void \fBsetShowBeatGroup\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowBeatGroup\fP () const"
.br
.ti -1c
.RI "void \fBsetGroupNumerator1\fP (int numerator)"
.br
.ti -1c
.RI "void \fBsetGroupNumerator2\fP (int numerator)"
.br
.ti -1c
.RI "void \fBsetGroupNumerator3\fP (int numerator)"
.br
.ti -1c
.RI "void \fBsetGroupDenominator1\fP (int denominator)"
.br
.ti -1c
.RI "void \fBsetGroupDenominator2\fP (int denominator)"
.br
.ti -1c
.RI "void \fBsetGroupDenominator3\fP (int denominator)"
.br
.ti -1c
.RI "void \fBsetBeamGroup1\fP (int count)"
.br
.ti -1c
.RI "void \fBsetBeamGroup2\fP (int count)"
.br
.ti -1c
.RI "void \fBsetBeamGroup3\fP (int count)"
.br
.ti -1c
.RI "void \fBsetBeamGroup4\fP (int count)"
.br
.ti -1c
.RI "void \fBset16thBeamCount\fP (int count)"
.br
.ti -1c
.RI "void \fBset32thBeamCount\fP (int count)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1843 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
