.TH "OVE::Track" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Track
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDrumNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetName\fP (const QString &str)"
.br
.ti -1c
.RI "QString \fBgetName\fP (void) const"
.br
.ti -1c
.RI "void \fBsetBriefName\fP (const QString &str)"
.br
.ti -1c
.RI "QString \fBgetBriefName\fP (void) const"
.br
.ti -1c
.RI "void \fBsetPatch\fP (unsigned int patch)"
.br
.ti -1c
.RI "unsigned int \fBgetPatch\fP () const"
.br
.ti -1c
.RI "void \fBsetChannel\fP (int channel)"
.br
.ti -1c
.RI "int \fBgetChannel\fP () const"
.br
.ti -1c
.RI "void \fBsetShowName\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowName\fP () const"
.br
.ti -1c
.RI "void \fBsetShowBriefName\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowBriefName\fP () const"
.br
.ti -1c
.RI "void \fBsetMute\fP (bool mute)"
.br
.ti -1c
.RI "bool \fBgetMute\fP () const"
.br
.ti -1c
.RI "void \fBsetSolo\fP (bool solo)"
.br
.ti -1c
.RI "bool \fBgetSolo\fP () const"
.br
.ti -1c
.RI "void \fBsetShowKeyEachLine\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowKeyEachLine\fP () const"
.br
.ti -1c
.RI "void \fBsetVoiceCount\fP (int voices)"
.br
.ti -1c
.RI "int \fBgetVoiceCount\fP () const"
.br
.ti -1c
.RI "void \fBaddVoice\fP (\fBVoice\fP *voice)"
.br
.ti -1c
.RI "QList< \fBVoice\fP * > \fBgetVoices\fP () const"
.br
.ti -1c
.RI "void \fBsetShowTranspose\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowTranspose\fP () const"
.br
.ti -1c
.RI "void \fBsetTranspose\fP (int transpose)"
.br
.ti -1c
.RI "int \fBgetTranspose\fP () const"
.br
.ti -1c
.RI "void \fBsetNoteShift\fP (int shift)"
.br
.ti -1c
.RI "int \fBgetNoteShift\fP () const"
.br
.ti -1c
.RI "void \fBsetStartClef\fP (int clef)"
.br
.ti -1c
.RI "ClefType \fBgetStartClef\fP () const"
.br
.ti -1c
.RI "void \fBsetTransposeClef\fP (int clef)"
.br
.ti -1c
.RI "ClefType \fBgetTansposeClef\fP () const"
.br
.ti -1c
.RI "void \fBsetStartKey\fP (int key)"
.br
.ti -1c
.RI "int \fBgetStartKey\fP () const"
.br
.ti -1c
.RI "void \fBsetDisplayPercent\fP (unsigned int percent)"
.br
.ti -1c
.RI "unsigned int \fBgetDisplayPercent\fP () const"
.br
.ti -1c
.RI "void \fBsetShowLegerLine\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowLegerLine\fP () const"
.br
.ti -1c
.RI "void \fBsetShowClef\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowClef\fP () const"
.br
.ti -1c
.RI "void \fBsetShowTimeSignature\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowTimeSignature\fP () const"
.br
.ti -1c
.RI "void \fBsetShowKeySignature\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowKeySignature\fP () const"
.br
.ti -1c
.RI "void \fBsetShowBarline\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowBarline\fP () const"
.br
.ti -1c
.RI "void \fBsetFillWithRest\fP (bool fill)"
.br
.ti -1c
.RI "bool \fBgetFillWithRest\fP () const"
.br
.ti -1c
.RI "void \fBsetFlatTail\fP (bool flat)"
.br
.ti -1c
.RI "bool \fBgetFlatTail\fP () const"
.br
.ti -1c
.RI "void \fBsetShowClefEachLine\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowClefEachLine\fP () const"
.br
.ti -1c
.RI "void \fBaddDrum\fP (const \fBDrumNode\fP &node)"
.br
.ti -1c
.RI "QList< \fBDrumNode\fP > \fBgetDrumKit\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "void \fBsetPart\fP (int part)"
.br
.ti -1c
.RI "int \fBgetPart\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 834 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
