.TH "OVE::Slur" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Slur
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::PairEnds\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetContainerCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetContainerCount\fP () const"
.br
.ti -1c
.RI "void \fBsetShowOnTop\fP (bool top)"
.br
.ti -1c
.RI "bool \fBgetShowOnTop\fP () const"
.br
.ti -1c
.RI "\fBOffsetElement\fP * \fBgetHandle2\fP () const"
.br
.ti -1c
.RI "\fBOffsetElement\fP * \fBgetHandle3\fP () const"
.br
.ti -1c
.RI "void \fBsetNoteTimePercent\fP (int percent)"
.br
.ti -1c
.RI "int \fBgetNoteTimePercent\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1527 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
