.TH "OVE::IOveNotify" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::IOveNotify
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBloadInfo\fP (const QString &info)=0"
.br
.ti -1c
.RI "virtual void \fBloadError\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBloadPosition\fP (int currentMeasure, int totalMeasure, int currentTrack, int totalTrack)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 475 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
