.TH "OVE::Line" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Line
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddStaff\fP (\fBStaff\fP *staff)"
.br
.ti -1c
.RI "int \fBgetStaffCount\fP () const"
.br
.ti -1c
.RI "\fBStaff\fP * \fBgetStaff\fP (int idx) const"
.br
.ti -1c
.RI "void \fBsetBeginBar\fP (unsigned int bar)"
.br
.ti -1c
.RI "unsigned int \fBgetBeginBar\fP () const"
.br
.ti -1c
.RI "void \fBsetBarCount\fP (unsigned int count)"
.br
.ti -1c
.RI "unsigned int \fBgetBarCount\fP () const"
.br
.ti -1c
.RI "void \fBsetYOffset\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetYOffset\fP () const"
.br
.ti -1c
.RI "void \fBsetLeftXOffset\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetLeftXOffset\fP () const"
.br
.ti -1c
.RI "void \fBsetRightXOffset\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetRightXOffset\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1039 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
