.TH "OVE::Chunk" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Chunk
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOVE::GroupChunk\fP, and \fBOVE::SizeChunk\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameBlock\fP \fBgetName\fP () const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const QString \fBTrackName\fP = 'TRAK'"
.br
.ti -1c
.RI "static const QString \fBPageName\fP = 'PAGE'"
.br
.ti -1c
.RI "static const QString \fBLineName\fP = 'LINE'"
.br
.ti -1c
.RI "static const QString \fBStaffName\fP = 'STAF'"
.br
.ti -1c
.RI "static const QString \fBMeasureName\fP = 'MEAS'"
.br
.ti -1c
.RI "static const QString \fBConductName\fP = 'COND'"
.br
.ti -1c
.RI "static const QString \fBBdatName\fP = 'BDAT'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNameBlock\fP \fBnameBlock_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2279 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
