.TH "OVE::NumericEnding" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::NumericEnding
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::PairEnds\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOffsetElement\fP * \fBgetNumericHandle\fP () const"
.br
.ti -1c
.RI "void \fBsetHeight\fP (int height)"
.br
.ti -1c
.RI "int \fBgetHeight\fP () const"
.br
.ti -1c
.RI "void \fBsetText\fP (const QString &text)"
.br
.ti -1c
.RI "QString \fBgetText\fP () const"
.br
.ti -1c
.RI "QList< int > \fBgetNumbers\fP () const"
.br
.ti -1c
.RI "int \fBgetJumpCount\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1969 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
