.TH "OVE::SizeChunk" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::SizeChunk
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::Chunk\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSizeBlock\fP * \fBgetSizeBlock\fP () const"
.br
.ti -1c
.RI "\fBBlock\fP * \fBgetDataBlock\fP () const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned int \fBversion3TrackSize\fP = 0x13a"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSizeBlock\fP * \fBsizeBlock_\fP"
.br
.ti -1c
.RI "\fBBlock\fP * \fBdataBlock_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2301 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
