.TH "OVE::Measure" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Measure
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::LengthElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeasure\fP (int index=0)"
.br
.ti -1c
.RI "\fBBarNumber\fP * \fBgetBarNumber\fP () const"
.br
.ti -1c
.RI "\fBTimeSignature\fP * \fBgetTime\fP () const"
.br
.ti -1c
.RI "void \fBsetLeftBarline\fP (int barline)"
.br
.ti -1c
.RI "BarLineType \fBgetLeftBarline\fP () const"
.br
.ti -1c
.RI "void \fBsetRightBarline\fP (int barline)"
.br
.ti -1c
.RI "BarLineType \fBgetRightBarline\fP () const"
.br
.ti -1c
.RI "void \fBsetBackwardRepeatCount\fP (int repeatCount)"
.br
.ti -1c
.RI "int \fBgetBackwardRepeatCount\fP () const"
.br
.ti -1c
.RI "void \fBsetTypeTempo\fP (double tempo)"
.br
.ti -1c
.RI "double \fBgetTypeTempo\fP () const"
.br
.ti -1c
.RI "void \fBsetIsPickup\fP (bool pickup)"
.br
.ti -1c
.RI "bool \fBgetIsPickup\fP () const"
.br
.ti -1c
.RI "void \fBsetIsMultiMeasureRest\fP (bool rest)"
.br
.ti -1c
.RI "bool \fBgetIsMultiMeasureRest\fP () const"
.br
.ti -1c
.RI "void \fBsetMultiMeasureRestCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetMultiMeasureRestCount\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2083 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
