.TH "OVE::MeasureData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MeasureData
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPairType\fP : char { \fBStart\fP, \fBStop\fP, \fBAll\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClef\fP * \fBgetClef\fP () const"
.br
.ti -1c
.RI "\fBKey\fP * \fBgetKey\fP () const"
.br
.ti -1c
.RI "void \fBaddNoteContainer\fP (\fBNoteContainer\fP *ptr)"
.br
.ti -1c
.RI "QList< \fBNoteContainer\fP * > \fBgetNoteContainers\fP () const"
.br
.ti -1c
.RI "void \fBaddMusicData\fP (\fBMusicData\fP *ptr)"
.br
.ti -1c
.RI "QList< \fBMusicData\fP * > \fBgetMusicDatas\fP (MusicDataType type)"
.br
.ti -1c
.RI "void \fBaddCrossMeasureElement\fP (\fBMusicData\fP *ptr, bool start)"
.br
.ti -1c
.RI "QList< \fBMusicData\fP * > \fBgetCrossMeasureElements\fP (MusicDataType type, PairType pairType)"
.br
.ti -1c
.RI "void \fBaddMidiData\fP (\fBMidiData\fP *ptr)"
.br
.ti -1c
.RI "QList< \fBMidiData\fP * > \fBgetMidiDatas\fP (MidiType type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2132 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
