.TH "OVE::OctaveShiftEndPoint" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::OctaveShiftEndPoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::LengthElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetOctaveShiftType\fP (OctaveShiftType type)"
.br
.ti -1c
.RI "OctaveShiftType \fBgetOctaveShiftType\fP () const"
.br
.ti -1c
.RI "void \fBsetOctaveShiftPosition\fP (OctaveShiftPosition position)"
.br
.ti -1c
.RI "OctaveShiftPosition \fBgetOctaveShiftPosition\fP () const"
.br
.ti -1c
.RI "void \fBsetEndTick\fP (int tick)"
.br
.ti -1c
.RI "int \fBgetEndTick\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1706 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
