.TH "OVE::Dynamics" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Dynamics
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDynamicsType\fP (int type)"
.br
.ti -1c
.RI "DynamicsType \fBgetDynamicsType\fP () const"
.br
.ti -1c
.RI "void \fBsetIsPlayback\fP (bool play)"
.br
.ti -1c
.RI "bool \fBgetIsPlayback\fP () const"
.br
.ti -1c
.RI "void \fBsetVelocity\fP (int vel)"
.br
.ti -1c
.RI "int \fBgetVelocity\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1553 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
