.TH "OVE::MidiController" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::MidiController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MidiData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetController\fP (int number)"
.br
.ti -1c
.RI "int \fBgetController\fP () const"
.br
.ti -1c
.RI "void \fBsetValue\fP (int value)"
.br
.ti -1c
.RI "int \fBgetValue\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2026 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
