.TH "OVE::NameBlock" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::NameBlock
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::FixedBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisEqual\fP (const QString &name) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2253 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
