.TH "OVE::Harmony" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Harmony
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP, and \fBOVE::LengthElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetHarmonyType\fP (QString type)"
.br
.ti -1c
.RI "QString \fBgetHarmonyType\fP () const"
.br
.ti -1c
.RI "void \fBsetRoot\fP (int root=0)"
.br
.ti -1c
.RI "int \fBgetRoot\fP () const"
.br
.ti -1c
.RI "void \fBsetBass\fP (int bass)"
.br
.ti -1c
.RI "int \fBgetBass\fP () const"
.br
.ti -1c
.RI "void \fBsetAlterRoot\fP (int val)"
.br
.ti -1c
.RI "int \fBgetAlterRoot\fP () const"
.br
.ti -1c
.RI "void \fBsetAlterBass\fP (int val)"
.br
.ti -1c
.RI "int \fBgetAlterBass\fP () const"
.br
.ti -1c
.RI "void \fBsetBassOnBottom\fP (bool on)"
.br
.ti -1c
.RI "bool \fBgetBassOnBottom\fP () const"
.br
.ti -1c
.RI "void \fBsetAngle\fP (int angle)"
.br
.ti -1c
.RI "int \fBgetAngle\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1460 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
