.TH "OVE::Note" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::Note
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::LineElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIsRest\fP (bool rest)"
.br
.ti -1c
.RI "bool \fBgetIsRest\fP () const"
.br
.ti -1c
.RI "void \fBsetNote\fP (unsigned int note)"
.br
.ti -1c
.RI "unsigned int \fBgetNote\fP () const"
.br
.ti -1c
.RI "void \fBsetAccidental\fP (int type)"
.br
.ti -1c
.RI "AccidentalType \fBgetAccidental\fP () const"
.br
.ti -1c
.RI "void \fBsetShowAccidental\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowAccidental\fP () const"
.br
.ti -1c
.RI "void \fBsetOnVelocity\fP (unsigned int velocity)"
.br
.ti -1c
.RI "unsigned int \fBgetOnVelocity\fP () const"
.br
.ti -1c
.RI "void \fBsetOffVelocity\fP (unsigned int velocity)"
.br
.ti -1c
.RI "unsigned int \fBgetOffVelocity\fP () const"
.br
.ti -1c
.RI "void \fBsetHeadType\fP (int type)"
.br
.ti -1c
.RI "NoteHeadType \fBgetHeadType\fP () const"
.br
.ti -1c
.RI "void \fBsetTiePos\fP (int tiePos)"
.br
.ti -1c
.RI "TiePos \fBgetTiePos\fP () const"
.br
.ti -1c
.RI "void \fBsetOffsetStaff\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetOffsetStaff\fP () const"
.br
.ti -1c
.RI "void \fBsetShow\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShow\fP () const"
.br
.ti -1c
.RI "void \fBsetOffsetTick\fP (int offset)"
.br
.ti -1c
.RI "int \fBgetOffsetTick\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1104 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
