.TH "OVE::GroupParse" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::GroupParse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::BasicParse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGroupParse\fP (\fBOveSong\fP *ove)"
.br
.ti -1c
.RI "void \fBaddSizeChunk\fP (\fBSizeChunk\fP *sizeChunk)"
.br
.ti -1c
.RI "virtual bool \fBparse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2385 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
