.TH "OVE::BarNumber" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::BarNumber
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::MusicData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIndex\fP (int index)"
.br
.ti -1c
.RI "int \fBgetIndex\fP () const"
.br
.ti -1c
.RI "void \fBsetShowOnParagraphStart\fP (bool show)"
.br
.ti -1c
.RI "bool \fBgetShowOnParagraphStart\fP () const"
.br
.ti -1c
.RI "void \fBsetAlign\fP (int align)"
.br
.ti -1c
.RI "int \fBgetAlign\fP () const"
.br
.ti -1c
.RI "void \fBsetShowFlag\fP (int flag)"
.br
.ti -1c
.RI "int \fBgetShowFlag\fP () const"
.br
.ti -1c
.RI "void \fBsetShowEveryBarCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetShowEveryBarCount\fP () const"
.br
.ti -1c
.RI "void \fBsetPrefix\fP (const QString &str)"
.br
.ti -1c
.RI "QString \fBgetPrefix\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1991 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
