.TH "OVE::OveSerialize" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVE::OveSerialize
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOVE::IOVEStreamLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetOve\fP (\fBOveSong\fP *ove)"
.br
.ti -1c
.RI "virtual void \fBsetFileStream\fP (unsigned char *buffer, unsigned int size)"
.br
.ti -1c
.RI "virtual void \fBsetNotify\fP (\fBIOveNotify\fP *notify)"
.br
.ti -1c
.RI "virtual bool \fBload\fP (void)"
.br
.ti -1c
.RI "virtual void \fBrelease\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2611 of file ove\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
