.TH "OveToMScore" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OveToMScore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBconvert\fP (\fBOVE::OveSong\fP *oveData, \fBScore\fP *score)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 180 of file importove\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
