.TH "PageAttrs" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageAttrs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageAttrs\fP (\fBPageAttrs\fP *attrs, \fBDict\fP *dict)"
.br
.ti -1c
.RI "\fBPDFRectangle\fP * \fBgetMediaBox\fP ()"
.br
.ti -1c
.RI "\fBPDFRectangle\fP * \fBgetCropBox\fP ()"
.br
.ti -1c
.RI "GBool \fBisCropped\fP ()"
.br
.ti -1c
.RI "\fBPDFRectangle\fP * \fBgetBleedBox\fP ()"
.br
.ti -1c
.RI "\fBPDFRectangle\fP * \fBgetTrimBox\fP ()"
.br
.ti -1c
.RI "\fBPDFRectangle\fP * \fBgetArtBox\fP ()"
.br
.ti -1c
.RI "int \fBgetRotate\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetLastModified\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetBoxColorInfo\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetGroup\fP ()"
.br
.ti -1c
.RI "\fBStream\fP * \fBgetMetadata\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetPieceInfo\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetSeparationInfo\fP ()"
.br
.ti -1c
.RI "\fBDict\fP * \fBgetResourceDict\fP ()"
.br
.ti -1c
.RI "void \fBreplaceResource\fP (\fBObject\fP obj1)"
.br
.ti -1c
.RI "void \fBclipBoxes\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file Page\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
