.TH "PageTransition" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageTransition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageTransition\fP (\fBObject\fP *trans)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "PageTransitionType \fBgetType\fP ()"
.br
.ti -1c
.RI "double \fBgetDuration\fP ()"
.br
.ti -1c
.RI "PageTransitionAlignment \fBgetAlignment\fP ()"
.br
.ti -1c
.RI "PageTransitionDirection \fBgetDirection\fP ()"
.br
.ti -1c
.RI "int \fBgetAngle\fP ()"
.br
.ti -1c
.RI "double \fBgetScale\fP ()"
.br
.ti -1c
.RI "GBool \fBisRectangular\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file PageTransition\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
