.TH "PaintDeviceDataMap< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaintDeviceDataMap< T > \- QPaintDevice based dataMap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datamap\&.h>\fP
.PP
Inherits \fBBaseDataMap< QPaintDevice, T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaintDeviceDataMap\fP (void)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~PaintDeviceDataMap\fP (void)"
.br
.RI "destructor "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class PaintDeviceDataMap< T >"
QPaintDevice based dataMap\&. 
.PP
Definition at line 145 of file datamap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
