.TH "bww2mxml/parser.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/parser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QStringList>\fP
.br
\fC#include <QtCore/QtDebug>\fP
.br
\fC#include <QtCore/QMap>\fP
.br
\fC#include 'lexer\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'writer\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple parser for bww files\&. The file header is handled one line at a time, until a line starting with '&' is found\&. The parser then builds measures from uinterrupted sequences of notes\&. 
.PP
Definition in file \fBparser\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
