.TH "bww2mxml/parser.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/parser.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QList>\fP
.br
\fC#include <QtCore/QString>\fP
.br
\fC#include <QtCore/QVector>\fP
.br
\fC#include 'writer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBww::NoteDescription\fP"
.br
.ti -1c
.RI "struct \fBBww::MeasureDescription\fP"
.br
.ti -1c
.RI "class \fBBww::Parser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of class \fBParser\fP 
.PP
Definition in file \fBparser\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
