.TH "Parser" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (\fBXRef\fP *xrefA, \fBLexer\fP *lexerA, GBool allowStreamsA)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObj\fP (\fBObject\fP *obj, GBool simpleOnly=gFalse, Guchar *fileKey=NULL, CryptAlgorithm encAlgorithm=cryptRC4, int keyLength=0, int objNum=0, int objGen=0, int recursion=0, GBool strict=gFalse)"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetObj\fP (\fBObject\fP *obj, int recursion)"
.br
.ti -1c
.RI "\fBStream\fP * \fBgetStream\fP ()"
.br
.ti -1c
.RI "Goffset \fBgetPos\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file Parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
