.TH "Patch" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Patch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff_match_patch\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatch\fP ()"
.br
.ti -1c
.RI "bool \fBisNull\fP () const"
.br
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBDiff\fP > \fBdiffs\fP"
.br
.ti -1c
.RI "int \fBstart1\fP"
.br
.ti -1c
.RI "int \fBstart2\fP"
.br
.ti -1c
.RI "int \fBlength1\fP"
.br
.ti -1c
.RI "int \fBlength2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBClass\fP representing one patch operation\&. 
.PP
Definition at line 108 of file diff_match_patch\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Patch::Patch ()"
Constructor\&. Initializes with an empty list of diffs\&. 
.PP
Definition at line 98 of file diff_match_patch\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString Patch::toString ()"
Emmulate GNU diff's format\&. Header: @ -382,8 +481,9 @ Indicies are printed as 1-based, not 0-based\&. 
.PP
\fBReturns:\fP
.RS 4
The GNU diff string 
.RE
.PP

.PP
Definition at line 118 of file diff_match_patch\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
