.TH "PathObject" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathObject \- Connect osc-messages with QObjects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qosctypes\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBsend\fP (QVariant)"
.br
.RI "send outgoing data "
.ti -1c
.RI "void \fBsend\fP (int)"
.br
.ti -1c
.RI "void \fBsend\fP (QString)"
.br
.ti -1c
.RI "void \fBsend\fP (double)"
.br
.ti -1c
.RI "void \fBsend\fP ()"
.br
.in -1c
.in -1c
.SS "Signals"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBdata\fP (QVariant)"
.br
.RI "signal incoming data "
.ti -1c
.RI "void \fBdata\fP (int)"
.br
.ti -1c
.RI "void \fBdata\fP (double)"
.br
.ti -1c
.RI "void \fBdata\fP (QString)"
.br
.ti -1c
.RI "void \fBdata\fP (QVariantList)"
.br
.ti -1c
.RI "void \fBdata\fP ()"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPathObject\fP (QString path, QVariant::Type type, \fBQOscClient\fP *parent)"
.br
.ti -1c
.RI "\fBPathObject\fP (QString path, QVariant::Type type, \fBQOscServer\fP *parent)"
.br
.ti -1c
.RI "QString \fBpath\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQOscServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Connect osc-messages with QObjects\&. 
.PP
Definition at line 64 of file qosctypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
