.TH "PCF_CMapRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_CMapRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMapRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_ULong \fBnum_encodings\fP"
.br
.ti -1c
.RI "\fBPCF_Encoding\fP \fBencodings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file pcfdrivr\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
