.TH "PCF_MetricRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_MetricRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Short \fBleftSideBearing\fP"
.br
.ti -1c
.RI "FT_Short \fBrightSideBearing\fP"
.br
.ti -1c
.RI "FT_Short \fBcharacterWidth\fP"
.br
.ti -1c
.RI "FT_Short \fBascent\fP"
.br
.ti -1c
.RI "FT_Short \fBdescent\fP"
.br
.ti -1c
.RI "FT_Short \fBattributes\fP"
.br
.ti -1c
.RI "FT_ULong \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file pcf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
