.TH "PCF_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_StreamRec\fP \fBcomp_stream\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBcomp_source\fP"
.br
.ti -1c
.RI "char * \fBcharset_encoding\fP"
.br
.ti -1c
.RI "char * \fBcharset_registry\fP"
.br
.ti -1c
.RI "\fBPCF_TocRec\fP \fBtoc\fP"
.br
.ti -1c
.RI "\fBPCF_AccelRec\fP \fBaccel\fP"
.br
.ti -1c
.RI "int \fBnprops\fP"
.br
.ti -1c
.RI "\fBPCF_Property\fP \fBproperties\fP"
.br
.ti -1c
.RI "FT_ULong \fBnmetrics\fP"
.br
.ti -1c
.RI "\fBPCF_Metric\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_ULong \fBnencodings\fP"
.br
.ti -1c
.RI "\fBPCF_Encoding\fP \fBencodings\fP"
.br
.ti -1c
.RI "FT_Short \fBdefaultChar\fP"
.br
.ti -1c
.RI "FT_ULong \fBbitmapsFormat\fP"
.br
.ti -1c
.RI "\fBFT_CharMap\fP \fBcharmap_handle\fP"
.br
.ti -1c
.RI "\fBFT_CharMapRec\fP \fBcharmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file pcf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
