.TH "PCF_Compressed_MetricRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_Compressed_MetricRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBleftSideBearing\fP"
.br
.ti -1c
.RI "FT_Byte \fBrightSideBearing\fP"
.br
.ti -1c
.RI "FT_Byte \fBcharacterWidth\fP"
.br
.ti -1c
.RI "FT_Byte \fBascent\fP"
.br
.ti -1c
.RI "FT_Byte \fBdescent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file pcf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
