.TH "PCF_PropertyRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_PropertyRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBname\fP"
.br
.ti -1c
.RI "FT_Byte \fBisString\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   FT_String * \fBatom\fP"
.br
.ti -1c
.RI "   FT_Long \fBl\fP"
.br
.ti -1c
.RI "   FT_ULong \fBul\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file pcf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
