.TH "PCF_AccelRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_AccelRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBnoOverlap\fP"
.br
.ti -1c
.RI "FT_Byte \fBconstantMetrics\fP"
.br
.ti -1c
.RI "FT_Byte \fBterminalFont\fP"
.br
.ti -1c
.RI "FT_Byte \fBconstantWidth\fP"
.br
.ti -1c
.RI "FT_Byte \fBinkInside\fP"
.br
.ti -1c
.RI "FT_Byte \fBinkMetrics\fP"
.br
.ti -1c
.RI "FT_Byte \fBdrawDirection\fP"
.br
.ti -1c
.RI "FT_Long \fBfontAscent\fP"
.br
.ti -1c
.RI "FT_Long \fBfontDescent\fP"
.br
.ti -1c
.RI "FT_Long \fBmaxOverlap\fP"
.br
.ti -1c
.RI "\fBPCF_MetricRec\fP \fBminbounds\fP"
.br
.ti -1c
.RI "\fBPCF_MetricRec\fP \fBmaxbounds\fP"
.br
.ti -1c
.RI "\fBPCF_MetricRec\fP \fBink_minbounds\fP"
.br
.ti -1c
.RI "\fBPCF_MetricRec\fP \fBink_maxbounds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file pcf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
