.TH "PDFDocFactory" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDFDocFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPDFDocFactory\fP (\fBGooList\fP *pdfDocBuilders=NULL)"
.br
.ti -1c
.RI "\fBPDFDoc\fP * \fBcreatePDFDoc\fP (const \fBGooString\fP &uri, \fBGooString\fP *ownerPassword=NULL, \fBGooString\fP *userPassword=NULL, void *guiDataA=NULL)"
.br
.ti -1c
.RI "void \fBregisterPDFDocBuilder\fP (\fBPDFDocBuilder\fP *pdfDocBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file PDFDocFactory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
