.TH "PDFDocBuilder" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDFDocBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCurlPDFDocBuilder\fP, \fBLocalPDFDocBuilder\fP, and \fBStdinPDFDocBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBPDFDoc\fP * \fBbuildPDFDoc\fP (const \fBGooString\fP &uri, \fBGooString\fP *ownerPassword=NULL, \fBGooString\fP *userPassword=NULL, void *guiDataA=NULL)=0"
.br
.ti -1c
.RI "virtual GBool \fBsupports\fP (const \fBGooString\fP &uri)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file PDFDocBuilder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
