.TH "pem_ctx_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pem_ctx_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBversion\fP"
.br
.ti -1c
.RI "   int \fBmode\fP"
.br
.ti -1c
.RI "} \fBproc_type\fP"
.br
.ti -1c
.RI "char * \fBdomain\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBcipher\fP"
.br
.ti -1c
.RI "} \fBDEK_info\fP"
.br
.ti -1c
.RI "\fBPEM_USER\fP * \fBoriginator\fP"
.br
.ti -1c
.RI "int \fBnum_recipient\fP"
.br
.ti -1c
.RI "\fBPEM_USER\fP ** \fBrecipient\fP"
.br
.ti -1c
.RI "\fBEVP_MD\fP * \fBmd\fP"
.br
.ti -1c
.RI "int \fBmd_enc\fP"
.br
.ti -1c
.RI "int \fBmd_len\fP"
.br
.ti -1c
.RI "char * \fBmd_data\fP"
.br
.ti -1c
.RI "\fBEVP_CIPHER\fP * \fBdec\fP"
.br
.ti -1c
.RI "int \fBkey_len\fP"
.br
.ti -1c
.RI "unsigned char * \fBkey\fP"
.br
.ti -1c
.RI "int \fBdata_enc\fP"
.br
.ti -1c
.RI "int \fBdata_len\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file pem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
