.TH "PFR_BitWriter_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_BitWriter_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte * \fBline\fP"
.br
.ti -1c
.RI "FT_Int \fBpitch\fP"
.br
.ti -1c
.RI "FT_UInt \fBwidth\fP"
.br
.ti -1c
.RI "FT_UInt \fBrows\fP"
.br
.ti -1c
.RI "FT_UInt \fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file pfrsbit\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
