.TH "PFR_GlyphRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_GlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBformat\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_xy_control\fP"
.br
.ti -1c
.RI "FT_Pos * \fBx_control\fP"
.br
.ti -1c
.RI "FT_Pos * \fBy_control\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_subs\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_subs\fP"
.br
.ti -1c
.RI "\fBPFR_SubGlyphRec\fP * \fBsubs\fP"
.br
.ti -1c
.RI "FT_GlyphLoader \fBloader\fP"
.br
.ti -1c
.RI "FT_Bool \fBpath_begun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 334 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
