.TH "PFR_KernItemRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_KernItemRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPFR_KernItem\fP \fBnext\fP"
.br
.ti -1c
.RI "FT_Byte \fBpair_count\fP"
.br
.ti -1c
.RI "FT_Byte \fBflags\fP"
.br
.ti -1c
.RI "FT_Short \fBbase_adj\fP"
.br
.ti -1c
.RI "FT_UInt \fBpair_size\fP"
.br
.ti -1c
.RI "FT_Offset \fBoffset\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBpair1\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBpair2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 196 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
