.TH "PFR_SubGlyphRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_SubGlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBx_scale\fP"
.br
.ti -1c
.RI "FT_Fixed \fBy_scale\fP"
.br
.ti -1c
.RI "FT_Int \fBx_delta\fP"
.br
.ti -1c
.RI "FT_Int \fBy_delta\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBgps_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBgps_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 312 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
