.TH "PFR_SlotRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_SlotRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_GlyphSlotRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBPFR_GlyphRec\fP \fBglyph\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file pfrobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
