.TH "PFR_HeaderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_HeaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt32 \fBsignature\fP"
.br
.ti -1c
.RI "FT_UInt \fBversion\fP"
.br
.ti -1c
.RI "FT_UInt \fBsignature2\fP"
.br
.ti -1c
.RI "FT_UInt \fBheader_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBlog_dir_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBlog_dir_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBlog_font_max_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBlog_font_section_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBlog_font_section_offset\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphy_font_max_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphy_font_section_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphy_font_section_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBgps_max_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBgps_section_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBgps_section_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_blue_values\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_x_orus\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_y_orus\fP"
.br
.ti -1c
.RI "FT_UInt \fBphy_font_max_size_high\fP"
.br
.ti -1c
.RI "FT_UInt \fBcolor_flags\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBbct_max_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBbct_set_max_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphy_bct_set_max_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_phy_fonts\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_vert_stem_snap\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_horz_stem_snap\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_chars\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
