.TH "PFR_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "PFR_HeaderRec \fBheader\fP"
.br
.ti -1c
.RI "\fBPFR_LogFontRec\fP \fBlog_font\fP"
.br
.ti -1c
.RI "\fBPFR_PhyFontRec\fP \fBphy_font\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file pfrobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
