.TH "PFR_DimensionRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_DimensionRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBstandard\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_stem_snaps\fP"
.br
.ti -1c
.RI "FT_Int * \fBstem_snaps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
