.TH "PFR_BitmapCharRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_BitmapCharRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBchar_code\fP"
.br
.ti -1c
.RI "FT_UInt \fBgps_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBgps_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
