.TH "PFR_LogFontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_LogFontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt32 \fBsize\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBoffset\fP"
.br
.ti -1c
.RI "FT_Int32 \fBmatrix\fP [4]"
.br
.ti -1c
.RI "FT_UInt \fBstroke_flags\fP"
.br
.ti -1c
.RI "FT_Int \fBstroke_thickness\fP"
.br
.ti -1c
.RI "FT_Int \fBbold_thickness\fP"
.br
.ti -1c
.RI "FT_Int32 \fBmiter_limit\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphys_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphys_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
