.TH "PFR_PhyFontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_PhyFontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBoffset\fP"
.br
.ti -1c
.RI "FT_UInt \fBfont_ref_number\fP"
.br
.ti -1c
.RI "FT_UInt \fBoutline_resolution\fP"
.br
.ti -1c
.RI "FT_UInt \fBmetrics_resolution\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBbbox\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.ti -1c
.RI "FT_Int \fBstandard_advance\fP"
.br
.ti -1c
.RI "FT_Int \fBascent\fP"
.br
.ti -1c
.RI "FT_Int \fBdescent\fP"
.br
.ti -1c
.RI "FT_Int \fBleading\fP"
.br
.ti -1c
.RI "\fBPFR_DimensionRec\fP \fBhorizontal\fP"
.br
.ti -1c
.RI "\fBPFR_DimensionRec\fP \fBvertical\fP"
.br
.ti -1c
.RI "FT_String * \fBfont_id\fP"
.br
.ti -1c
.RI "FT_String * \fBfamily_name\fP"
.br
.ti -1c
.RI "FT_String * \fBstyle_name\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_strikes\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_strikes\fP"
.br
.ti -1c
.RI "\fBPFR_StrikeRec\fP * \fBstrikes\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_blue_values\fP"
.br
.ti -1c
.RI "FT_Int * \fBblue_values\fP"
.br
.ti -1c
.RI "FT_UInt \fBblue_fuzz\fP"
.br
.ti -1c
.RI "FT_UInt \fBblue_scale\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_chars\fP"
.br
.ti -1c
.RI "FT_Offset \fBchars_offset\fP"
.br
.ti -1c
.RI "\fBPFR_Char\fP \fBchars\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_kern_pairs\fP"
.br
.ti -1c
.RI "\fBPFR_KernItem\fP \fBkern_items\fP"
.br
.ti -1c
.RI "\fBPFR_KernItem\fP * \fBkern_items_tail\fP"
.br
.ti -1c
.RI "FT_ULong \fBbct_offset\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcursor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 222 of file pfrtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
