.TH "pkcs7_recip_info_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkcs7_recip_info_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBPKCS7_ISSUER_AND_SERIAL\fP * \fBissuer_and_serial\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBkey_enc_algor\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBenc_key\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBcert\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file pkcs7\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
