.TH "PKCS12_SAFEBAG" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PKCS12_SAFEBAG
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP) *attrib"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBpkcs12_bag_st\fP * \fBbag\fP"
.br
.ti -1c
.RI "   struct \fBpkcs8_priv_key_info_st\fP * \fBkeybag\fP"
.br
.ti -1c
.RI "   \fBX509_SIG\fP * \fBshkeybag\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 111 of file pkcs12\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
