.TH "pkcs7_signed_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkcs7_signed_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ALGOR\fP) *md_algs"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP) *cert"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_CRL\fP) *crl"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBPKCS7_SIGNER_INFO\fP) *signer_info"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "struct \fBpkcs7_st\fP * \fBcontents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file pkcs7\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
