.TH "pkcs7_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkcs7_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBasn1\fP"
.br
.ti -1c
.RI "long \fBlength\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBdetached\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   \fBASN1_OCTET_STRING\fP * \fBdata\fP"
.br
.ti -1c
.RI "   \fBPKCS7_SIGNED\fP * \fBsign\fP"
.br
.ti -1c
.RI "   \fBPKCS7_ENVELOPE\fP * \fBenveloped\fP"
.br
.ti -1c
.RI "   \fBPKCS7_SIGN_ENVELOPE\fP * \fBsigned_and_enveloped\fP"
.br
.ti -1c
.RI "   \fBPKCS7_DIGEST\fP * \fBdigest\fP"
.br
.ti -1c
.RI "   \fBPKCS7_ENCRYPT\fP * \fBencrypted\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 175 of file pkcs7\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
