.TH "pm_fns_node" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pm_fns_node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pm_write_short_fn \fBwrite_short\fP"
.br
.ti -1c
.RI "pm_begin_sysex_fn \fBbegin_sysex\fP"
.br
.ti -1c
.RI "pm_end_sysex_fn \fBend_sysex\fP"
.br
.ti -1c
.RI "pm_write_byte_fn \fBwrite_byte\fP"
.br
.ti -1c
.RI "pm_write_realtime_fn \fBwrite_realtime\fP"
.br
.ti -1c
.RI "pm_write_flush_fn \fBwrite_flush\fP"
.br
.ti -1c
.RI "pm_synchronize_fn \fBsynchronize\fP"
.br
.ti -1c
.RI "pm_open_fn \fBopen\fP"
.br
.ti -1c
.RI "pm_abort_fn \fBabort\fP"
.br
.ti -1c
.RI "pm_close_fn \fBclose\fP"
.br
.ti -1c
.RI "pm_poll_fn \fBpoll\fP"
.br
.ti -1c
.RI "pm_has_host_error_fn \fBhas_host_error\fP"
.br
.ti -1c
.RI "pm_host_error_fn \fBhost_error\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file pminternal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
