.TH "pm_internal_struct" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pm_internal_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdevice_id\fP"
.br
.ti -1c
.RI "short \fBwrite_flag\fP"
.br
.ti -1c
.RI "PmTimeProcPtr \fBtime_proc\fP"
.br
.ti -1c
.RI "void * \fBtime_info\fP"
.br
.ti -1c
.RI "long \fBbuffer_len\fP"
.br
.ti -1c
.RI "PmQueue * \fBqueue\fP"
.br
.ti -1c
.RI "long \fBlatency\fP"
.br
.ti -1c
.RI "int \fBsysex_in_progress\fP"
.br
.ti -1c
.RI "PmMessage \fBsysex_message\fP"
.br
.ti -1c
.RI "int \fBsysex_message_count\fP"
.br
.ti -1c
.RI "long \fBfilters\fP"
.br
.ti -1c
.RI "int \fBchannel_mask\fP"
.br
.ti -1c
.RI "PmTimestamp \fBlast_msg_time\fP"
.br
.ti -1c
.RI "PmTimestamp \fBsync_time\fP"
.br
.ti -1c
.RI "PmTimestamp \fBnow\fP"
.br
.ti -1c
.RI "int \fBfirst_message\fP"
.br
.ti -1c
.RI "\fBpm_fns_type\fP \fBdictionary\fP"
.br
.ti -1c
.RI "void * \fBdescriptor\fP"
.br
.ti -1c
.RI "unsigned char * \fBfill_base\fP"
.br
.ti -1c
.RI "unsigned long * \fBfill_offset_ptr\fP"
.br
.ti -1c
.RI "int \fBfill_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file pminternal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
