.TH "PmDeviceInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PmDeviceInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstructVersion\fP"
.br
.ti -1c
.RI "const char * \fBinterf\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBinput\fP"
.br
.ti -1c
.RI "int \fBoutput\fP"
.br
.ti -1c
.RI "int \fBopened\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 191 of file portmidi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
