.TH "POLICYQUALINFO_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
POLICYQUALINFO_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBpqualid\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBASN1_IA5STRING\fP * \fBcpsuri\fP"
.br
.ti -1c
.RI "   \fBUSERNOTICE\fP * \fBusernotice\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 291 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
