.TH "Poppler::PDFConverter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::PDFConverter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-qt5\&.h>\fP
.PP
Inherits \fBPoppler::BaseConverter\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPDFOption\fP { \fBWithChanges\fP = 0x00000001 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PDFConverter\fP ()"
.br
.ti -1c
.RI "void \fBsetPDFOptions\fP (PDFOptions options)"
.br
.ti -1c
.RI "PDFOptions \fBpdfOptions\fP () const"
.br
.ti -1c
.RI "bool \fBconvert\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDocument\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts a PDF to PDF (thus saves a copy of the document)\&.
.PP
\fBSince:\fP
.RS 4
0\&.8 
.RE
.PP

.PP
Definition at line 1624 of file poppler\-qt5\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPoppler::PDFConverter::PDFOption\fP"
Options for the PDF export\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWithChanges \fP\fP
The changes done to the document are saved as well\&. 
.PP
Definition at line 1631 of file poppler\-qt5\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Poppler::PDFConverter::~PDFConverter ()\fC [virtual]\fP"
Destructor\&. 
.PP
Definition at line 53 of file poppler\-pdf\-converter\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Poppler::PDFConverter::convert ()\fC [virtual]\fP"
Does the conversion\&.
.PP
\fBReturns:\fP
.RS 4
whether the conversion succeeded 
.RE
.PP

.PP
Implements \fBPoppler::BaseConverter\fP\&.
.PP
Definition at line 69 of file poppler\-pdf\-converter\&.cc\&.
.SS "PDFConverter::PDFOptions Poppler::PDFConverter::pdfOptions () const"
The currently set options for the PDF export\&. 
.PP
Definition at line 63 of file poppler\-pdf\-converter\&.cc\&.
.SS "void Poppler::PDFConverter::setPDFOptions (PDFOptions options)"
Sets the options for the PDF export\&. 
.PP
Definition at line 57 of file poppler\-pdf\-converter\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
