.TH "Poppler::RichMediaAnnotation::Asset" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Asset
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "\fBEmbeddedFile\fP * \fBembeddedFile\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The asset object of a \fBRichMediaAnnotation::Content\fP object\&.
.PP
The asset object provides a mapping between identifier name, as used in the flash vars string of \fBRichMediaAnnotation::Params\fP, and the associated file spec object\&. 
.PP
Definition at line 1175 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEmbeddedFile\fP * Poppler::RichMediaAnnotation::Asset::embeddedFile () const"
Returns the embedded file the asset points to\&. 
.PP
Definition at line 4774 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::RichMediaAnnotation::Asset::name () const"
Returns the identifier name of the asset\&. 
.PP
Definition at line 4763 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
