.TH "Poppler::PageData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::PageData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLink\fP * \fBconvertLinkActionToLink\fP (::\fBLinkAction\fP *a, const QRectF &linkArea)"
.br
.ti -1c
.RI "\fBTextPage\fP * \fBprepareTextSearch\fP (const QString &text, \fBPage::Rotation\fP rotate, QVector< Unicode > *u)"
.br
.ti -1c
.RI "GBool \fBperformSingleTextSearch\fP (\fBTextPage\fP *textPage, QVector< Unicode > &u, double &sLeft, double &sTop, double &sRight, double &sBottom, \fBPage::SearchDirection\fP direction, GBool sCase, GBool sWords)"
.br
.ti -1c
.RI "QList< QRectF > \fBperformMultipleTextSearch\fP (\fBTextPage\fP *textPage, QVector< Unicode > &u, GBool sCase, GBool sWords)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLink\fP * \fBconvertLinkActionToLink\fP (::\fBLinkAction\fP *a, \fBDocumentData\fP *parentDoc, const QRectF &linkArea)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDocumentData\fP * \fBparentDoc\fP"
.br
.ti -1c
.RI "::\fBPage\fP * \fBpage\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "\fBPageTransition\fP * \fBtransition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file poppler\-page\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
