.TH "Poppler::PSConverterPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::PSConverterPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPoppler::BaseConverterPrivate\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< int > \fBpageList\fP"
.br
.ti -1c
.RI "QString \fBtitle\fP"
.br
.ti -1c
.RI "double \fBhDPI\fP"
.br
.ti -1c
.RI "double \fBvDPI\fP"
.br
.ti -1c
.RI "int \fBrotate\fP"
.br
.ti -1c
.RI "int \fBpaperWidth\fP"
.br
.ti -1c
.RI "int \fBpaperHeight\fP"
.br
.ti -1c
.RI "int \fBmarginRight\fP"
.br
.ti -1c
.RI "int \fBmarginBottom\fP"
.br
.ti -1c
.RI "int \fBmarginLeft\fP"
.br
.ti -1c
.RI "int \fBmarginTop\fP"
.br
.ti -1c
.RI "PSConverter::PSOptions \fBopts\fP"
.br
.ti -1c
.RI "void(* \fBpageConvertedCallback\fP )(int page, void *payload)"
.br
.ti -1c
.RI "void * \fBpageConvertedPayload\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file poppler\-ps\-converter\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
