.TH "Poppler::SoundAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::SoundAnnotation \- \fBSound\fP annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "QString \fBsoundIconName\fP () const"
.br
.ti -1c
.RI "void \fBsetSoundIconName\fP (const QString &icon)"
.br
.ti -1c
.RI "\fBSoundObject\fP * \fBsound\fP () const"
.br
.ti -1c
.RI "void \fBsetSound\fP (\fBSoundObject\fP *ef)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSound\fP annotation\&. 

The sound annotation represents a sound to be played when activated\&.
.PP
\fBSince:\fP
.RS 4
0\&.10 
.RE
.PP

.PP
Definition at line 861 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Poppler::SoundAnnotation::setSound (\fBSoundObject\fP * ef)"
Sets a new \fBSoundObject\fP for this annotation\&.
.PP
\fBNote:\fP
.RS 4
\fBSoundAnnotation\fP takes ownership of the object 
.RE
.PP

.PP
Definition at line 4343 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::SoundAnnotation::setSoundIconName (const QString & icon)"
Sets a new name for the icon of this annotation\&. 
.PP
Definition at line 4331 of file poppler\-annotation\&.cc\&.
.SS "\fBSoundObject\fP * Poppler::SoundAnnotation::sound () const"
Returns the \fBSoundObject\fP of this annotation\&. 
.PP
Definition at line 4337 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::SoundAnnotation::soundIconName () const"
Returns the name of the icon of this annotation\&. 
.PP
Definition at line 4325 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::SoundAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 4320 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
