.TH "Poppler::MediaRendition" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::MediaRendition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-media\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMediaRendition\fP (::\fBMediaRendition\fP *rendition)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "QString \fBcontentType\fP () const"
.br
.ti -1c
.RI "QString \fBfileName\fP () const"
.br
.ti -1c
.RI "bool \fBisEmbedded\fP () const"
.br
.ti -1c
.RI "QByteArray \fBdata\fP () const"
.br
.ti -1c
.RI "bool \fBautoPlay\fP () const"
.br
.ti -1c
.RI "bool \fBshowControls\fP () const"
.br
.ti -1c
.RI "float \fBrepeatCount\fP () const"
.br
.ti -1c
.RI "QSize \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt wrapper for \fBMediaRendition\fP\&.
.PP
\fBSince:\fP
.RS 4
0\&.20 
.RE
.PP

.PP
Definition at line 40 of file poppler\-media\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MediaRendition::MediaRendition (::\fBMediaRendition\fP * rendition)"
Constructs a \fBMediaRendition\fP\&. Takes ownership of the passed rendition 
.PP
Definition at line 50 of file poppler\-media\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MediaRendition::autoPlay () const"
Convenience accessor for auto-play parameter\&. 
.PP
Definition at line 115 of file poppler\-media\&.cc\&.
.SS "QString MediaRendition::contentType () const"
Returns content type\&. 
.PP
Definition at line 68 of file poppler\-media\&.cc\&.
.SS "QByteArray MediaRendition::data () const"
Returns data buffer\&. 
.PP
Definition at line 92 of file poppler\-media\&.cc\&.
.SS "QString MediaRendition::fileName () const"
Returns file name\&. 
.PP
Definition at line 76 of file poppler\-media\&.cc\&.
.SS "bool MediaRendition::isEmbedded () const"
Returns true if media is embedded\&. 
.PP
Definition at line 84 of file poppler\-media\&.cc\&.
.SS "bool MediaRendition::isValid () const"
Check if wrapper is holding a valid rendition object\&. 
.PP
Definition at line 61 of file poppler\-media\&.cc\&.
.SS "float MediaRendition::repeatCount () const"
Convenience accessor for repeat count parameter\&. 
.PP
Definition at line 139 of file poppler\-media\&.cc\&.
.SS "bool MediaRendition::showControls () const"
Convenience accessor for show controls parameter\&. 
.PP
Definition at line 127 of file poppler\-media\&.cc\&.
.SS "QSize MediaRendition::size () const"
Convenience accessor for size parameter\&. 
.PP
Definition at line 151 of file poppler\-media\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
