.TH "PopplerCache" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PopplerCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopplerCache\fP (int cacheSizeA)"
.br
.ti -1c
.RI "\fBPopplerCacheItem\fP * \fBlookup\fP (const \fBPopplerCacheKey\fP &key)"
.br
.ti -1c
.RI "void \fBput\fP (\fBPopplerCacheKey\fP *key, \fBPopplerCacheItem\fP *item)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "int \fBnumberOfItems\fP ()"
.br
.ti -1c
.RI "\fBPopplerCacheItem\fP * \fBitem\fP (int index)"
.br
.ti -1c
.RI "\fBPopplerCacheKey\fP * \fBkey\fP (int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file PopplerCache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
