.TH "Poppler::RichMediaAnnotation::Configuration::Private" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Configuration::Private
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRichMediaAnnotation::Configuration::Type\fP \fBtype\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QList< \fBRichMediaAnnotation::Instance\fP *> \fBinstances\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4674 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
