.TH "Poppler::XPDFReader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::XPDFReader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlookupName\fP (\fBDict\fP *, char *, QString &dest)"
.br
.ti -1c
.RI "static void \fBlookupString\fP (\fBDict\fP *, char *, QString &dest)"
.br
.ti -1c
.RI "static void \fBlookupBool\fP (\fBDict\fP *, char *, bool &dest)"
.br
.ti -1c
.RI "static void \fBlookupInt\fP (\fBDict\fP *, char *, int &dest)"
.br
.ti -1c
.RI "static void \fBlookupNum\fP (\fBDict\fP *, char *, double &dest)"
.br
.ti -1c
.RI "static int \fBlookupNumArray\fP (\fBDict\fP *, char *, double *dest, int len)"
.br
.ti -1c
.RI "static void \fBlookupColor\fP (\fBDict\fP *, char *, QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "static void \fBlookupIntRef\fP (\fBDict\fP *, char *, int &dest)"
.br
.ti -1c
.RI "static void \fBlookupDate\fP (\fBDict\fP *, char *, QDateTime &dest)"
.br
.ti -1c
.RI "static void \fBtransform\fP (double *M, double x, double y, QPointF &res)"
.br
.ti -1c
.RI "static void \fBinvTransform\fP (double *M, const QPointF &p, double &x, double &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file poppler\-annotation\-helper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
