.TH "Poppler::RichMediaAnnotation::Configuration" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Configuration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBType3D\fP, \fBTypeFlash\fP, \fBTypeSound\fP, \fBTypeVideo\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QList< \fBRichMediaAnnotation::Instance\fP *> \fBinstances\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The configuration object of a \fBRichMediaAnnotation::Content\fP object\&.
.PP
The configuration object provides access to the various \fBInstance\fP objects of the rich media annotation\&. 
.PP
Definition at line 1125 of file poppler\-annotation\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPoppler::RichMediaAnnotation::Configuration::Type\fP"
Describes the media type of the configuration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType3D \fP\fP
A 3D media file\&. 
.TP
\fB\fITypeFlash \fP\fP
A Flash media file\&. 
.TP
\fB\fITypeSound \fP\fP
A sound media file\&. 
.TP
\fB\fITypeVideo \fP\fP
A video media file\&. 
.PP
Definition at line 1133 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QList< \fBRichMediaAnnotation::Instance\fP *> Poppler::RichMediaAnnotation::Configuration::instances () const"
Returns the list of \fBInstance\fP objects of the configuration\&. 
.PP
Definition at line 4726 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::RichMediaAnnotation::Configuration::name () const"
Returns the name of the configuration\&. 
.PP
Definition at line 4713 of file poppler\-annotation\&.cc\&.
.SS "\fBRichMediaAnnotation::Configuration::Type\fP Poppler::RichMediaAnnotation::Configuration::type () const"
Returns the media type of the configuration\&. 
.PP
Definition at line 4703 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
