.TH "Poppler::LinkAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkAnnotation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBHighlightMode\fP { \fBNone\fP, \fBInvert\fP, \fBOutline\fP, \fBPush\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "\fBLink\fP * \fBlinkDestination\fP () const"
.br
.ti -1c
.RI "void \fBsetLinkDestination\fP (\fBLink\fP *link)"
.br
.ti -1c
.RI "HighlightMode \fBlinkHighlightMode\fP () const"
.br
.ti -1c
.RI "void \fBsetLinkHighlightMode\fP (HighlightMode mode)"
.br
.ti -1c
.RI "QPointF \fBlinkRegionPoint\fP (int id) const"
.br
.ti -1c
.RI "void \fBsetLinkRegionPoint\fP (int id, const QPointF &point)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationUtils\fP"
.br
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 748 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLink\fP * Poppler::LinkAnnotation::linkDestination () const"

.PP
\fBSince:\fP
.RS 4
0\&.20 
.RE
.PP

.PP
Definition at line 3955 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::LinkAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 3950 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
