.TH "Poppler::RichMediaAnnotation::Content" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Content
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QList< \fBRichMediaAnnotation::Configuration\fP *> \fBconfigurations\fP () const"
.br
.ti -1c
.RI "QList< \fBRichMediaAnnotation::Asset\fP *> \fBassets\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The content object of a \fBRichMediaAnnotation\fP\&.
.PP
The content object provides access to the list of configurations and assets of the rich media annotation\&. 
.PP
Definition at line 1207 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QList< \fBRichMediaAnnotation::Asset\fP *> Poppler::RichMediaAnnotation::Content::assets () const"
Returns the list of asset objects of the content object\&. 
.PP
Definition at line 4827 of file poppler\-annotation\&.cc\&.
.SS "QList< \fBRichMediaAnnotation::Configuration\fP *> Poppler::RichMediaAnnotation::Content::configurations () const"
Returns the list of configuration objects of the content object\&. 
.PP
Definition at line 4814 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
