.TH "Poppler::RichMediaAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation \- RichMedia annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivation\fP"
.br
.ti -1c
.RI "class \fBAsset\fP"
.br
.ti -1c
.RI "class \fBConfiguration\fP"
.br
.ti -1c
.RI "class \fBContent\fP"
.br
.ti -1c
.RI "class \fBDeactivation\fP"
.br
.ti -1c
.RI "class \fBInstance\fP"
.br
.ti -1c
.RI "class \fBParams\fP"
.br
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "\fBRichMediaAnnotation::Settings\fP * \fBsettings\fP () const"
.br
.ti -1c
.RI "\fBRichMediaAnnotation::Content\fP * \fBcontent\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
RichMedia annotation\&. 

The RichMedia annotation represents a video or sound on a page\&.
.PP
\fBSince:\fP
.RS 4
0\&.36 
.RE
.PP

.PP
Definition at line 1038 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRichMediaAnnotation::Content\fP * Poppler::RichMediaAnnotation::content () const"
Returns the \fBContent\fP object of the rich media annotation or \fC0\fP if it doesn't exist\&. 
.PP
Definition at line 5039 of file poppler\-annotation\&.cc\&.
.SS "\fBRichMediaAnnotation::Settings\fP * Poppler::RichMediaAnnotation::settings () const"
Returns the \fBSettings\fP object of the rich media annotation or \fC0\fP if it doesn't exist\&. 
.PP
Definition at line 5024 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::RichMediaAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 5011 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
