.TH "Poppler::MovieAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::MovieAnnotation \- \fBMovie\fP annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "\fBMovieObject\fP * \fBmovie\fP () const"
.br
.ti -1c
.RI "void \fBsetMovie\fP (\fBMovieObject\fP *\fBmovie\fP)"
.br
.ti -1c
.RI "QString \fBmovieTitle\fP () const"
.br
.ti -1c
.RI "void \fBsetMovieTitle\fP (const QString &title)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBMovie\fP annotation\&. 

The movie annotation represents a movie to be played when activated\&.
.PP
\fBSince:\fP
.RS 4
0\&.10 
.RE
.PP

.PP
Definition at line 905 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMovieObject\fP * Poppler::MovieAnnotation::movie () const"
Returns the \fBMovieObject\fP of this annotation\&. 
.PP
Definition at line 4429 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::MovieAnnotation::movieTitle () const"
Returns the title of the movie of this annotation\&. 
.PP
Definition at line 4441 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::MovieAnnotation::setMovie (\fBMovieObject\fP * movie)"
Sets a new \fBMovieObject\fP for this annotation\&.
.PP
\fBNote:\fP
.RS 4
\fBMovieAnnotation\fP takes ownership of the object 
.RE
.PP

.PP
Definition at line 4435 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::MovieAnnotation::setMovieTitle (const QString & title)"
Sets a new title for the movie of this annotation\&. 
.PP
Definition at line 4447 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::MovieAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 4424 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
