.TH "Poppler::RichMediaAnnotation::Deactivation::Private" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Deactivation::Private
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRichMediaAnnotation::Deactivation::Condition\fP \fBcondition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4864 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
