.TH "Poppler::SoundData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::SoundData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSoundObject::SoundType\fP \fBm_type\fP"
.br
.ti -1c
.RI "\fBSound\fP * \fBm_soundObj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file poppler\-sound\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
