.TH "Poppler::BaseConverterPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::BaseConverterPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPoppler::PDFConverterPrivate\fP, and \fBPoppler::PSConverterPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QIODevice * \fBopenDevice\fP ()"
.br
.ti -1c
.RI "void \fBcloseDevice\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDocumentData\fP * \fBdocument\fP"
.br
.ti -1c
.RI "QString \fBoutputFileName\fP"
.br
.ti -1c
.RI "QIODevice * \fBiodev\fP"
.br
.ti -1c
.RI "bool \fBownIodev\fP: 1"
.br
.ti -1c
.RI "BaseConverter::Error \fBlastError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file poppler\-converter\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
