.TH "Poppler::FileAttachmentAnnotationPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::FileAttachmentAnnotationPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPoppler::AnnotationPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnnotation\fP * \fBmakeAlias\fP ()"
.br
.ti -1c
.RI "\fBAnnot\fP * \fBcreateNativeAnnot\fP (::\fBPage\fP *destPage, \fBDocumentData\fP *doc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBicon\fP"
.br
.ti -1c
.RI "\fBEmbeddedFile\fP * \fBembfile\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBFileAttachmentAnnotation\fP [\fBAnnotation\fP] 
.PP
Definition at line 4142 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
