.TH "Poppler::FormFieldData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::FormFieldData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormFieldData\fP (\fBDocumentData\fP *_doc, ::\fBPage\fP *p, ::\fBFormWidget\fP *w)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDocumentData\fP * \fBdoc\fP"
.br
.ti -1c
.RI "::\fBPage\fP * \fBpage\fP"
.br
.ti -1c
.RI "::\fBFormWidget\fP * \fBfm\fP"
.br
.ti -1c
.RI "QRectF \fBbox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 221 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
