.TH "Poppler::TextBoxData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::TextBoxData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBtext\fP"
.br
.ti -1c
.RI "QRectF \fBbBox\fP"
.br
.ti -1c
.RI "\fBTextBox\fP * \fBnextWord\fP"
.br
.ti -1c
.RI "QVector< QRectF > \fBcharBBoxes\fP"
.br
.ti -1c
.RI "bool \fBhasSpaceAfter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 206 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
