.TH "Poppler::FontInfoData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::FontInfoData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontInfoData\fP (const \fBFontInfoData\fP &fid)"
.br
.ti -1c
.RI "\fBFontInfoData\fP (::\fBFontInfo\fP *fi)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBfontName\fP"
.br
.ti -1c
.RI "QString \fBfontFile\fP"
.br
.ti -1c
.RI "bool \fBisEmbedded\fP: 1"
.br
.ti -1c
.RI "bool \fBisSubset\fP: 1"
.br
.ti -1c
.RI "\fBFontInfo::Type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBRef\fP \fBembRef\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
