.TH "Poppler::LinkBrowse" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkBrowse \- An URL to browse\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-link\&.h>\fP
.PP
Inherits \fBPoppler::Link\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBurl\fP () const"
.br
.ti -1c
.RI "\fBLinkBrowse\fP (const QRectF &\fBlinkArea\fP, const QString &\fBurl\fP)"
.br
.ti -1c
.RI "\fB~LinkBrowse\fP ()"
.br
.ti -1c
.RI "\fBLinkType\fP \fBlinkType\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An URL to browse\&. 

The \fBLinkBrowse\fP link holds a URL (eg 'http://poppler.freedesktop.org', 'john@some.org', etc) to be open\&.
.PP
The format of the URL is specified by RFC 2396 (http://www.ietf.org/rfc/rfc2396.txt) 
.PP
Definition at line 320 of file poppler\-link\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Poppler::LinkBrowse::LinkBrowse (const QRectF & linkArea, const QString & url)"
Create a new browse link\&.
.PP
\fBParameters:\fP
.RS 4
\fIlinkArea\fP the active area of the link 
.br
\fIurl\fP the URL to be open 
.RE
.PP

.PP
Definition at line 510 of file poppler\-link\&.cc\&.
.SS "Poppler::LinkBrowse::~LinkBrowse ()"
Destructor\&. 
.PP
Definition at line 517 of file poppler\-link\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLink::LinkType\fP Poppler::LinkBrowse::linkType () const\fC [virtual]\fP"
The type of this link\&. 
.PP
Reimplemented from \fBPoppler::Link\fP\&.
.PP
Definition at line 527 of file poppler\-link\&.cc\&.
.SS "QString Poppler::LinkBrowse::url () const"
The URL to open 
.PP
Definition at line 521 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
