.TH "Poppler::LinkDestinationPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkDestinationPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinkDestination::Kind\fP \fBkind\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "int \fBpageNum\fP"
.br
.ti -1c
.RI "double \fBleft\fP"
.br
.ti -1c
.RI "double \fBbottom\fP"
.br
.ti -1c
.RI "double \fBright\fP"
.br
.ti -1c
.RI "double \fBtop\fP"
.br
.ti -1c
.RI "double \fBzoom\fP"
.br
.ti -1c
.RI "bool \fBchangeLeft\fP: 1"
.br
.ti -1c
.RI "bool \fBchangeTop\fP: 1"
.br
.ti -1c
.RI "bool \fBchangeZoom\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
