.TH "Poppler::DocumentData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::DocumentData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocumentData\fP (const QString &filePath, \fBGooString\fP *ownerPassword, \fBGooString\fP *userPassword)"
.br
.ti -1c
.RI "\fBDocumentData\fP (const QByteArray &data, \fBGooString\fP *ownerPassword, \fBGooString\fP *userPassword)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBaddTocChildren\fP (QDomDocument *docSyn, QDomNode *parent, \fBGooList\fP *items)"
.br
.ti -1c
.RI "void \fBsetPaperColor\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBfillMembers\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDocument\fP * \fBcheckDocument\fP (\fBDocumentData\fP *doc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPDFDoc\fP * \fBdoc\fP"
.br
.ti -1c
.RI "QString \fBm_filePath\fP"
.br
.ti -1c
.RI "QByteArray \fBfileContents\fP"
.br
.ti -1c
.RI "bool \fBlocked\fP"
.br
.ti -1c
.RI "\fBDocument::RenderBackend\fP \fBm_backend\fP"
.br
.ti -1c
.RI "QList< \fBEmbeddedFile\fP * > \fBm_embeddedFiles\fP"
.br
.ti -1c
.RI "QPointer< \fBOptContentModel\fP > \fBm_optContentModel\fP"
.br
.ti -1c
.RI "QColor \fBpaperColor\fP"
.br
.ti -1c
.RI "int \fBm_hints\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
