.TH "Poppler::LinkRenditionPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkRenditionPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPoppler::LinkPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkRenditionPrivate\fP (const QRectF &area, ::\fBMediaRendition\fP *rendition, ::\fBLinkRendition::RenditionOperation\fP operation, const QString &script, const \fBRef\fP &annotationReference)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMediaRendition\fP * \fBrendition\fP"
.br
.ti -1c
.RI "\fBLinkRendition::RenditionAction\fP \fBaction\fP"
.br
.ti -1c
.RI "QString \fBscript\fP"
.br
.ti -1c
.RI "\fBRef\fP \fBannotationReference\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 168 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
