.TH "Poppler::CaretAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::CaretAnnotation \- Caret annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCaretSymbol\fP { \fBNone\fP, \fBP\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "\fBCaretSymbol\fP \fBcaretSymbol\fP () const"
.br
.ti -1c
.RI "void \fBsetCaretSymbol\fP (\fBCaretSymbol\fP symbol)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationUtils\fP"
.br
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Caret annotation\&. 

The caret annotation represents a symbol to indicate the presence of text\&. 
.PP
Definition at line 784 of file poppler\-annotation\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPoppler::CaretAnnotation::CaretSymbol\fP"
The symbols for the caret annotation\&. 
.PP
Definition at line 797 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAnnotation::SubType\fP Poppler::CaretAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 4111 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
