.TH "Poppler::QIODeviceOutStream" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::QIODeviceOutStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQIODeviceOutStream\fP (QIODevice *device)"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual Goffset \fBgetPos\fP ()"
.br
.ti -1c
.RI "virtual void \fBput\fP (char c)"
.br
.ti -1c
.RI "virtual void \fBprintf\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file poppler\-qiodeviceoutstream\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
