.TH "Poppler::LinkDestinationData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkDestinationData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkDestinationData\fP (\fBLinkDest\fP *l, \fBGooString\fP *nd, \fBPoppler::DocumentData\fP *pdfdoc, bool external)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinkDest\fP * \fBld\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBnamedDest\fP"
.br
.ti -1c
.RI "\fBPoppler::DocumentData\fP * \fBdoc\fP"
.br
.ti -1c
.RI "bool \fBexternalDest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
