.TH "Poppler::FileAttachmentAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::FileAttachmentAnnotation \- File attachment annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "QString \fBfileIconName\fP () const"
.br
.ti -1c
.RI "void \fBsetFileIconName\fP (const QString &icon)"
.br
.ti -1c
.RI "\fBEmbeddedFile\fP * \fBembeddedFile\fP () const"
.br
.ti -1c
.RI "void \fBsetEmbeddedFile\fP (\fBEmbeddedFile\fP *ef)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
File attachment annotation\&. 

The file attachment annotation represents a file embedded in the document\&.
.PP
\fBSince:\fP
.RS 4
0\&.10 
.RE
.PP

.PP
Definition at line 817 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEmbeddedFile\fP * Poppler::FileAttachmentAnnotation::embeddedFile () const"
Returns the \fBEmbeddedFile\fP of this annotation\&. 
.PP
Definition at line 4233 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::FileAttachmentAnnotation::fileIconName () const"
Returns the name of the icon of this annotation\&. 
.PP
Definition at line 4221 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::FileAttachmentAnnotation::setEmbeddedFile (\fBEmbeddedFile\fP * ef)"
Sets a new \fBEmbeddedFile\fP for this annotation\&.
.PP
\fBNote:\fP
.RS 4
\fBFileAttachmentAnnotation\fP takes ownership of the object 
.RE
.PP

.PP
Definition at line 4239 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::FileAttachmentAnnotation::setFileIconName (const QString & icon)"
Sets a new name for the icon of this annotation\&. 
.PP
Definition at line 4227 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::FileAttachmentAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 4216 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
