.TH "Poppler::ScreenAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::ScreenAnnotation \- Screen annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "\fBLinkRendition\fP * \fBaction\fP () const"
.br
.ti -1c
.RI "void \fBsetAction\fP (\fBLinkRendition\fP *\fBaction\fP)"
.br
.ti -1c
.RI "QString \fBscreenTitle\fP () const"
.br
.ti -1c
.RI "void \fBsetScreenTitle\fP (const QString &title)"
.br
.ti -1c
.RI "\fBLink\fP * \fBadditionalAction\fP (\fBAdditionalActionType\fP type) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Screen annotation\&. 

The screen annotation represents a screen to be played when activated\&.
.PP
\fBSince:\fP
.RS 4
0\&.20 
.RE
.PP

.PP
Definition at line 949 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLinkRendition\fP * Poppler::ScreenAnnotation::action () const"
Returns the \fBLinkRendition\fP of this annotation\&. 
.PP
Definition at line 4515 of file poppler\-annotation\&.cc\&.
.SS "\fBLink\fP * Poppler::ScreenAnnotation::additionalAction (\fBAdditionalActionType\fP type) const"
Returns the additional action of the given \fCtype\fP fo the annotation or \fC0\fP if no action has been defined\&.
.PP
\fBSince:\fP
.RS 4
0\&.22 
.RE
.PP

.PP
Definition at line 4539 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::ScreenAnnotation::screenTitle () const"
Returns the title of the screen of this annotation\&. 
.PP
Definition at line 4527 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::ScreenAnnotation::setAction (\fBLinkRendition\fP * action)"
Sets a new \fBLinkRendition\fP for this annotation\&.
.PP
\fBNote:\fP
.RS 4
\fBScreenAnnotation\fP takes ownership of the object 
.RE
.PP

.PP
Definition at line 4521 of file poppler\-annotation\&.cc\&.
.SS "void Poppler::ScreenAnnotation::setScreenTitle (const QString & title)"
Sets a new title for the screen of this annotation\&. 
.PP
Definition at line 4533 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::ScreenAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 4510 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
