.TH "Poppler" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnnotation\fP"
.br
.RI "\fBAnnotation\fP class holding properties shared by all annotations\&. "
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBAnnotationUtils\fP"
.br
.RI "Helper class for (recursive) \fBAnnotation\fP retrieval/storage\&. "
.ti -1c
.RI "class \fBBaseConverter\fP"
.br
.RI "Base converter\&. "
.ti -1c
.RI "class \fBBaseConverterPrivate\fP"
.br
.ti -1c
.RI "class \fBCaretAnnotation\fP"
.br
.RI "Caret annotation\&. "
.ti -1c
.RI "class \fBCaretAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBDocument\fP"
.br
.RI "PDF document\&. "
.ti -1c
.RI "class \fBDocumentData\fP"
.br
.ti -1c
.RI "class \fBEmbeddedFile\fP"
.br
.ti -1c
.RI "class \fBEmbeddedFileData\fP"
.br
.ti -1c
.RI "class \fBFileAttachmentAnnotation\fP"
.br
.RI "File attachment annotation\&. "
.ti -1c
.RI "class \fBFileAttachmentAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBFontInfo\fP"
.br
.ti -1c
.RI "class \fBFontInfoData\fP"
.br
.ti -1c
.RI "class \fBFontIterator\fP"
.br
.ti -1c
.RI "class \fBFontIteratorData\fP"
.br
.ti -1c
.RI "class \fBFormField\fP"
.br
.ti -1c
.RI "class \fBFormFieldButton\fP"
.br
.ti -1c
.RI "class \fBFormFieldChoice\fP"
.br
.ti -1c
.RI "class \fBFormFieldData\fP"
.br
.ti -1c
.RI "class \fBFormFieldText\fP"
.br
.ti -1c
.RI "class \fBGeomAnnotation\fP"
.br
.RI "Geometric annotation\&. "
.ti -1c
.RI "class \fBGeomAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBHighlightAnnotation\fP"
.br
.RI "Text highlight annotation\&. "
.ti -1c
.RI "class \fBHighlightAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBInkAnnotation\fP"
.br
.RI "Ink \fBAnnotation\fP\&. "
.ti -1c
.RI "class \fBInkAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBLineAnnotation\fP"
.br
.RI "Polygon/polyline annotation\&. "
.ti -1c
.RI "class \fBLineAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBLink\fP"
.br
.RI "Encapsulates data that describes a link\&. "
.ti -1c
.RI "class \fBLinkAction\fP"
.br
.RI "'Standard' action request\&. "
.ti -1c
.RI "class \fBLinkActionPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkAnnotation\fP"
.br
.ti -1c
.RI "class \fBLinkAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkBrowse\fP"
.br
.RI "An URL to browse\&. "
.ti -1c
.RI "class \fBLinkBrowsePrivate\fP"
.br
.ti -1c
.RI "class \fBLinkDestination\fP"
.br
.RI "A destination\&. "
.ti -1c
.RI "class \fBLinkDestinationData\fP"
.br
.ti -1c
.RI "class \fBLinkDestinationPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkExecute\fP"
.br
.RI "Generic execution request\&. "
.ti -1c
.RI "class \fBLinkExecutePrivate\fP"
.br
.ti -1c
.RI "class \fBLinkExtractorOutputDev\fP"
.br
.ti -1c
.RI "class \fBLinkGoto\fP"
.br
.RI "Viewport reaching request\&. "
.ti -1c
.RI "class \fBLinkGotoPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkJavaScript\fP"
.br
.ti -1c
.RI "class \fBLinkJavaScriptPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkMovie\fP"
.br
.ti -1c
.RI "class \fBLinkMoviePrivate\fP"
.br
.ti -1c
.RI "class \fBLinkPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkRendition\fP"
.br
.ti -1c
.RI "class \fBLinkRenditionPrivate\fP"
.br
.ti -1c
.RI "class \fBLinkSound\fP"
.br
.ti -1c
.RI "class \fBLinkSoundPrivate\fP"
.br
.ti -1c
.RI "class \fBMediaRendition\fP"
.br
.ti -1c
.RI "class \fBMediaRenditionPrivate\fP"
.br
.ti -1c
.RI "class \fBMovieAnnotation\fP"
.br
.RI "\fBMovie\fP annotation\&. "
.ti -1c
.RI "class \fBMovieAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBMovieData\fP"
.br
.ti -1c
.RI "class \fBMovieObject\fP"
.br
.ti -1c
.RI "class \fBOptContentItem\fP"
.br
.ti -1c
.RI "class \fBOptContentModel\fP"
.br
.RI "\fBModel\fP for optional content\&. "
.ti -1c
.RI "class \fBOptContentModelPrivate\fP"
.br
.ti -1c
.RI "class \fBPage\fP"
.br
.RI "A page in a document\&. "
.ti -1c
.RI "class \fBPageData\fP"
.br
.ti -1c
.RI "class \fBPageTransition\fP"
.br
.RI "Describes how a PDF file viewer shall perform the transition from one page to another\&. "
.ti -1c
.RI "class \fBPageTransitionData\fP"
.br
.ti -1c
.RI "class \fBPageTransitionParams\fP"
.br
.ti -1c
.RI "class \fBPDFConverter\fP"
.br
.ti -1c
.RI "class \fBPDFConverterPrivate\fP"
.br
.ti -1c
.RI "class \fBPSConverter\fP"
.br
.ti -1c
.RI "class \fBPSConverterPrivate\fP"
.br
.ti -1c
.RI "class \fBQIODeviceOutStream\fP"
.br
.ti -1c
.RI "class \fBRadioButtonGroup\fP"
.br
.ti -1c
.RI "class \fBRichMediaAnnotation\fP"
.br
.RI "RichMedia annotation\&. "
.ti -1c
.RI "class \fBRichMediaAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBScreenAnnotation\fP"
.br
.RI "Screen annotation\&. "
.ti -1c
.RI "class \fBScreenAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBSoundAnnotation\fP"
.br
.RI "\fBSound\fP annotation\&. "
.ti -1c
.RI "class \fBSoundAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBSoundData\fP"
.br
.ti -1c
.RI "class \fBSoundObject\fP"
.br
.ti -1c
.RI "class \fBStampAnnotation\fP"
.br
.RI "Stamp annotation\&. "
.ti -1c
.RI "class \fBStampAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBTextAnnotation\fP"
.br
.RI "\fBAnnotation\fP containing text\&. "
.ti -1c
.RI "class \fBTextAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBTextBox\fP"
.br
.ti -1c
.RI "class \fBTextBoxData\fP"
.br
.ti -1c
.RI "class \fBWidgetAnnotation\fP"
.br
.RI "Widget annotation\&. "
.ti -1c
.RI "class \fBWidgetAnnotationPrivate\fP"
.br
.ti -1c
.RI "class \fBXPDFReader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBPopplerDebugFunc\fP) (const QString &, const QVariant &)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QColor \fBconvertAnnotColor\fP (\fBAnnotColor\fP *\fBcolor\fP)"
.br
.ti -1c
.RI "\fBAnnotColor\fP * \fBconvertQColor\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "QDateTime \fBconvertDate\fP (char *dateString)"
.br
.ti -1c
.RI "bool \fBisCmsAvailable\fP ()"
.br
.ti -1c
.RI "bool \fBisOverprintPreviewAvailable\fP ()"
.br
.ti -1c
.RI "void \fBsetDebugErrorFunction\fP (\fBPopplerDebugFunc\fP function, const QVariant &closure)"
.br
.ti -1c
.RI "void \fBqt5ErrorFunction\fP (void *, ErrorCategory, Goffset pos, char *msg)"
.br
.ti -1c
.RI "QString \fBunicodeToQString\fP (Unicode *u, int len)"
.br
.ti -1c
.RI "QString \fBUnicodeParsedString\fP (\fBGooString\fP *s1)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBQStringToUnicodeGooString\fP (const QString &s)"
.br
.ti -1c
.RI "\fBGooString\fP * \fBQStringToGooString\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBlinkActionToTocItem\fP (::\fBLinkAction\fP *a, \fBDocumentData\fP *doc, QDomElement *e)"
.br
.ti -1c
.RI "void \fBqt5ErrorFunction\fP (int pos, char *msg, va_list args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Poppler Qt5 binding\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* Poppler::PopplerDebugFunc) (const QString &, const QVariant &)"
Debug/error function\&.
.PP
This function type is used for debugging & error output; the first parameter is the actual message, the second is the unaltered closure argument which was passed to the setDebugErrorFunction call\&.
.PP
\fBSince:\fP
.RS 4
0\&.16 
.RE
.PP

.PP
Definition at line 78 of file poppler\-qt5\&.h\&.
.SH "Function Documentation"
.PP 
.SS "POPPLER_QT5_EXPORT QDateTime Poppler::convertDate (char * dateString)"
Conversion from PDF date string format to QDateTime 
.PP
Definition at line 636 of file poppler\-document\&.cc\&.
.SS "POPPLER_QT5_EXPORT bool Poppler::isCmsAvailable ()"
Whether the color management functions are available\&.
.PP
\fBSince:\fP
.RS 4
0\&.12 
.RE
.PP

.PP
Definition at line 667 of file poppler\-document\&.cc\&.
.SS "POPPLER_QT5_EXPORT bool Poppler::isOverprintPreviewAvailable ()"
Whether the overprint preview functionality is available\&.
.PP
\fBSince:\fP
.RS 4
0\&.22 
.RE
.PP

.PP
Definition at line 676 of file poppler\-document\&.cc\&.
.SS "POPPLER_QT5_EXPORT void Poppler::setDebugErrorFunction (\fBPopplerDebugFunc\fP debugFunction, const QVariant & closure)"
Set a new debug/error output function\&.
.PP
If not set, by default error and debug messages will be sent to the Qt \fCqDebug()\fP function\&.
.PP
\fBParameters:\fP
.RS 4
\fIdebugFunction\fP the new debug function 
.br
\fIclosure\fP user data which will be passes as-is to the debug function
.RE
.PP
\fBSince:\fP
.RS 4
0\&.16 
.RE
.PP

.PP
Definition at line 53 of file poppler\-private\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
