.TH "Poppler::RichMediaAnnotation::Asset::Private" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Asset::Private
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "\fBEmbeddedFile\fP * \fBembeddedFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4732 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
