.TH "Poppler::LinkPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPoppler::LinkActionPrivate\fP, \fBPoppler::LinkBrowsePrivate\fP, \fBPoppler::LinkExecutePrivate\fP, \fBPoppler::LinkGotoPrivate\fP, \fBPoppler::LinkJavaScriptPrivate\fP, \fBPoppler::LinkMoviePrivate\fP, \fBPoppler::LinkRenditionPrivate\fP, and \fBPoppler::LinkSoundPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkPrivate\fP (const QRectF &area)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QRectF \fBlinkArea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
