.TH "PopplerCacheKey" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PopplerCacheKey
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGfxICCBasedColorSpaceKey\fP, \fBObjectKey\fP, and \fBObjectStreamKey\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBoperator==\fP (const \fBPopplerCacheKey\fP &key) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file PopplerCache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
