.TH "Poppler::LinkGotoPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkGotoPrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPoppler::LinkPrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkGotoPrivate\fP (const QRectF &area, const \fBLinkDestination\fP &dest)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBextFileName\fP"
.br
.ti -1c
.RI "\fBLinkDestination\fP \fBdestination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
