.TH "Poppler::Annotation::Popup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::Annotation::Popup \- Container class for \fBAnnotation\fP pop-up window information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopup\fP (const \fBPopup\fP &other)"
.br
.ti -1c
.RI "\fBPopup\fP & \fBoperator=\fP (const \fBPopup\fP &other)"
.br
.ti -1c
.RI "int \fBflags\fP () const"
.br
.ti -1c
.RI "void \fBsetFlags\fP (int flags)"
.br
.ti -1c
.RI "QRectF \fBgeometry\fP () const"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const QRectF &geom)"
.br
.ti -1c
.RI "QString \fBtitle\fP () const"
.br
.ti -1c
.RI "void \fBsetTitle\fP (const QString &title)"
.br
.ti -1c
.RI "QString \fBsummary\fP () const"
.br
.ti -1c
.RI "void \fBsetSummary\fP (const QString &summary)"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.ti -1c
.RI "void \fBsetText\fP (const QString &text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container class for \fBAnnotation\fP pop-up window information\&. 


.PP
\fBSince:\fP
.RS 4
0\&.20 
.RE
.PP

.PP
Definition at line 343 of file poppler\-annotation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
