.TH "Poppler::Annotation::Style::Private" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::Annotation::Style::Private
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "double \fBopacity\fP"
.br
.ti -1c
.RI "double \fBwidth\fP"
.br
.ti -1c
.RI "Annotation::LineStyle \fBlineStyle\fP"
.br
.ti -1c
.RI "double \fBxCorners\fP"
.br
.ti -1c
.RI "double \fByCorners\fP"
.br
.ti -1c
.RI "QVector< double > \fBdashArray\fP"
.br
.ti -1c
.RI "Annotation::LineEffect \fBlineEffect\fP"
.br
.ti -1c
.RI "double \fBeffectIntensity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 842 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
