.TH "Poppler::PageTransitionData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::PageTransitionData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageTransitionData\fP (\fBObject\fP *trans)"
.br
.ti -1c
.RI "\fBPageTransitionData\fP (const \fBPageTransitionData\fP &ptd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "::\fBPageTransition\fP * \fBpt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file poppler\-page\-transition\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
