.TH "Poppler::GeomAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::GeomAnnotation \- Geometric annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGeomType\fP { \fBInscribedSquare\fP, \fBInscribedCircle\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "GeomType \fBgeomType\fP () const"
.br
.ti -1c
.RI "void \fBsetGeomType\fP (GeomType \fBstyle\fP)"
.br
.ti -1c
.RI "QColor \fBgeomInnerColor\fP () const"
.br
.ti -1c
.RI "void \fBsetGeomInnerColor\fP (const QColor &\fBcolor\fP)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationUtils\fP"
.br
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Geometric annotation\&. 

The geometric annotation represents a geometric figure, like a rectangle or an ellipse\&. 
.PP
Definition at line 577 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAnnotation::SubType\fP Poppler::GeomAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 2981 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
