.TH "Poppler::Annotation::Style" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::Annotation::Style \- Container class for \fBAnnotation\fP style information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStyle\fP (const \fBStyle\fP &other)"
.br
.ti -1c
.RI "\fBStyle\fP & \fBoperator=\fP (const \fBStyle\fP &other)"
.br
.ti -1c
.RI "QColor \fBcolor\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "double \fBopacity\fP () const"
.br
.ti -1c
.RI "void \fBsetOpacity\fP (double opacity)"
.br
.ti -1c
.RI "double \fBwidth\fP () const"
.br
.ti -1c
.RI "void \fBsetWidth\fP (double width)"
.br
.ti -1c
.RI "LineStyle \fBlineStyle\fP () const"
.br
.ti -1c
.RI "void \fBsetLineStyle\fP (LineStyle \fBstyle\fP)"
.br
.ti -1c
.RI "double \fBxCorners\fP () const"
.br
.ti -1c
.RI "void \fBsetXCorners\fP (double radius)"
.br
.ti -1c
.RI "double \fByCorners\fP () const"
.br
.ti -1c
.RI "void \fBsetYCorners\fP (double radius)"
.br
.ti -1c
.RI "const QVector< double > & \fBdashArray\fP () const"
.br
.ti -1c
.RI "void \fBsetDashArray\fP (const QVector< double > &array)"
.br
.ti -1c
.RI "LineEffect \fBlineEffect\fP () const"
.br
.ti -1c
.RI "void \fBsetLineEffect\fP (LineEffect effect)"
.br
.ti -1c
.RI "double \fBeffectIntensity\fP () const"
.br
.ti -1c
.RI "void \fBsetEffectIntensity\fP (double intens)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container class for \fBAnnotation\fP style information\&. 


.PP
\fBSince:\fP
.RS 4
0\&.20 
.RE
.PP

.PP
Definition at line 296 of file poppler\-annotation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
