.TH "Poppler::EmbeddedFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::EmbeddedFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-qt5\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~EmbeddedFile\fP ()"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBdescription\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "QDateTime \fBmodDate\fP () const"
.br
.ti -1c
.RI "QDateTime \fBcreateDate\fP () const"
.br
.ti -1c
.RI "QByteArray \fBchecksum\fP () const"
.br
.ti -1c
.RI "QString \fBmimeType\fP () const"
.br
.ti -1c
.RI "QByteArray \fBdata\fP ()"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDocumentData\fP"
.br
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container class for an embedded file with a PDF document 
.PP
Definition at line 314 of file poppler\-qt5\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Poppler::EmbeddedFile::~EmbeddedFile ()"
Destructor\&. 
.PP
Definition at line 64 of file poppler\-embeddedfile\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "QByteArray Poppler::EmbeddedFile::checksum () const"
The MD5 checksum of the file\&.
.PP
This will return an empty QByteArray if there is no checksum element\&. 
.PP
Definition at line 98 of file poppler\-embeddedfile\&.cc\&.
.SS "QDateTime Poppler::EmbeddedFile::createDate () const"
The creation date for the embedded file, if known\&. 
.PP
Definition at line 92 of file poppler\-embeddedfile\&.cc\&.
.SS "QByteArray Poppler::EmbeddedFile::data ()"
The data as a byte array 
.PP
Definition at line 110 of file poppler\-embeddedfile\&.cc\&.
.SS "QString Poppler::EmbeddedFile::description () const"
The description associated with the file, if any\&.
.PP
This will return an empty QString if there is no description element 
.PP
Definition at line 75 of file poppler\-embeddedfile\&.cc\&.
.SS "bool Poppler::EmbeddedFile::isValid () const"
Is the embedded file valid?
.PP
\fBSince:\fP
.RS 4
0\&.12 
.RE
.PP

.PP
Definition at line 130 of file poppler\-embeddedfile\&.cc\&.
.SS "QString Poppler::EmbeddedFile::mimeType () const"
The MIME type of the file, if known\&.
.PP
\fBSince:\fP
.RS 4
0\&.8 
.RE
.PP

.PP
Definition at line 104 of file poppler\-embeddedfile\&.cc\&.
.SS "QDateTime Poppler::EmbeddedFile::modDate () const"
The modification date for the embedded file, if known\&. 
.PP
Definition at line 86 of file poppler\-embeddedfile\&.cc\&.
.SS "QString Poppler::EmbeddedFile::name () const"
The name associated with the file 
.PP
Definition at line 69 of file poppler\-embeddedfile\&.cc\&.
.SS "int Poppler::EmbeddedFile::size () const"
The size of the file\&.
.PP
This will return < 0 if there is no size element 
.PP
Definition at line 81 of file poppler\-embeddedfile\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
