.TH "Poppler::FontIteratorData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::FontIteratorData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontIteratorData\fP (int startPage, \fBDocumentData\fP *dd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFontInfoScanner\fP \fBfontInfoScanner\fP"
.br
.ti -1c
.RI "int \fBtotalPages\fP"
.br
.ti -1c
.RI "int \fBcurrentPage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 187 of file poppler\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
