.TH "Poppler::StampAnnotation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::StampAnnotation \- Stamp annotation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.PP
Inherits \fBPoppler::Annotation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSubType\fP \fBsubType\fP () const"
.br
.ti -1c
.RI "QString \fBstampIconName\fP () const"
.br
.ti -1c
.RI "void \fBsetStampIconName\fP (const QString &name)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationUtils\fP"
.br
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Stamp annotation\&. 

A simple annotation drawing a stamp on a page\&. 
.PP
Definition at line 676 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Poppler::StampAnnotation::setStampIconName (const QString & name)"
Set the icon type for this stamp annotation\&.
.PP
\fBSee also:\fP
.RS 4
\fBstampIconName\fP for the list of standard icon names 
.RE
.PP

.PP
Definition at line 3439 of file poppler\-annotation\&.cc\&.
.SS "QString Poppler::StampAnnotation::stampIconName () const"
The name of the icon for this stamp annotation\&.
.PP
Standard names for stamp annotation icons are:
.IP "\(bu" 2
Approved
.IP "\(bu" 2
AsIs
.IP "\(bu" 2
Confidential
.IP "\(bu" 2
Departmental
.IP "\(bu" 2
Draft (this is the default icon type)
.IP "\(bu" 2
Experimental
.IP "\(bu" 2
Expired
.IP "\(bu" 2
Final
.IP "\(bu" 2
ForComment
.IP "\(bu" 2
ForPublicRelease
.IP "\(bu" 2
NotApproved
.IP "\(bu" 2
NotForPublicRelease
.IP "\(bu" 2
Sold
.IP "\(bu" 2
TopSecret 
.PP

.PP
Definition at line 3428 of file poppler\-annotation\&.cc\&.
.SS "\fBAnnotation::SubType\fP Poppler::StampAnnotation::subType () const\fC [virtual]\fP"
The type of the annotation\&. 
.PP
Implements \fBPoppler::Annotation\fP\&.
.PP
Definition at line 3423 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
