.TH "Poppler::EmbeddedFileData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::EmbeddedFileData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmbeddedFileData\fP (\fBFileSpec\fP *fs)"
.br
.ti -1c
.RI "\fBEmbFile\fP * \fBembFile\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFileSpec\fP * \fBfilespec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file poppler\-embeddedfile\-private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
