.TH "Poppler::RichMediaAnnotation::Instance" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Instance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBType3D\fP, \fBTypeFlash\fP, \fBTypeSound\fP, \fBTypeVideo\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "\fBRichMediaAnnotation::Params\fP * \fBparams\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The instance object of a \fBRichMediaAnnotation::Configuration\fP object\&.
.PP
The instance object represents one media object, that should be shown on the page\&. It has a media type and a \fBParams\fP object, to define the media specific parameters\&. 
.PP
Definition at line 1082 of file poppler\-annotation\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPoppler::RichMediaAnnotation::Instance::Type\fP"
Describes the media type of the instance\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType3D \fP\fP
A 3D media file\&. 
.TP
\fB\fITypeFlash \fP\fP
A Flash media file\&. 
.TP
\fB\fITypeSound \fP\fP
A sound media file\&. 
.TP
\fB\fITypeVideo \fP\fP
A video media file\&. 
.PP
Definition at line 1090 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRichMediaAnnotation::Params\fP * Poppler::RichMediaAnnotation::Instance::params () const"
Returns the params object of the instance or \fC0\fP if it doesn't exist\&. 
.PP
Definition at line 4668 of file poppler\-annotation\&.cc\&.
.SS "\fBRichMediaAnnotation::Instance::Type\fP Poppler::RichMediaAnnotation::Instance::type () const"
Returns the media type of the instance\&. 
.PP
Definition at line 4657 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
