.TH "Poppler::RichMediaAnnotation::Params" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Params
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QString \fBflashVars\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The params object of a \fBRichMediaAnnotation::Instance\fP object\&.
.PP
The params object provides media specific parameters, to play back the media inside the PDF viewer\&.
.PP
At the moment only parameters for flash player are supported\&. 
.PP
Definition at line 1055 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QString Poppler::RichMediaAnnotation::Params::flashVars () const"
Returns the parameters for the flash player\&. 
.PP
Definition at line 4620 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
