.TH "Poppler::RichMediaAnnotation::Params::Private" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Params::Private
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBflashVars\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRichMediaAnnotation\fP [\fBAnnotation\fP] 
.PP
Definition at line 4598 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
