.TH "Poppler::RichMediaAnnotation::Activation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::RichMediaAnnotation::Activation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-annotation\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrivate\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCondition\fP { \fBPageOpened\fP, \fBPageVisible\fP, \fBUserAction\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondition\fP \fBcondition\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAnnotationPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The activation object of the \fBRichMediaAnnotation::Settings\fP object\&.
.PP
The activation object is a wrapper around the settings for the activation state\&. At the moment it provides only the activation condition\&. 
.PP
Definition at line 1239 of file poppler\-annotation\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPoppler::RichMediaAnnotation::Activation::Condition\fP"
Describes the condition for activating the rich media\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPageOpened \fP\fP
Activate when page is opened\&. 
.TP
\fB\fIPageVisible \fP\fP
Activate when page becomes visible\&. 
.TP
\fB\fIUserAction \fP\fP
Activate when user interacts with the annotation\&. 
.PP
Definition at line 1247 of file poppler\-annotation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRichMediaAnnotation::Activation::Condition\fP Poppler::RichMediaAnnotation::Activation::condition () const"
Returns the activation condition\&. 
.PP
Definition at line 4858 of file poppler\-annotation\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
