.TH "Poppler::LinkJavaScript" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poppler::LinkJavaScript
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <poppler\-link\&.h>\fP
.PP
Inherits \fBPoppler::Link\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkJavaScript\fP (const QRectF &\fBlinkArea\fP, const QString &js)"
.br
.ti -1c
.RI "virtual \fB~LinkJavaScript\fP ()"
.br
.ti -1c
.RI "\fBLinkType\fP \fBlinkType\fP () const"
.br
.ti -1c
.RI "QString \fBscript\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
JavaScript: a JavaScript code to be interpreted\&.
.PP
\fBSince:\fP
.RS 4
0\&.10 
.RE
.PP

.PP
Definition at line 526 of file poppler\-link\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LinkJavaScript::LinkJavaScript (const QRectF & linkArea, const QString & js)"
Create a new JavaScript link\&.
.PP
\fBParameters:\fP
.RS 4
\fIlinkArea\fP the active area of the link 
.br
\fIjs\fP the JS code to be interpreted 
.RE
.PP

.PP
Definition at line 651 of file poppler\-link\&.cc\&.
.SS "LinkJavaScript::~LinkJavaScript ()\fC [virtual]\fP"
Destructor\&. 
.PP
Definition at line 658 of file poppler\-link\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLink::LinkType\fP LinkJavaScript::linkType () const\fC [virtual]\fP"
The type of this link\&. 
.PP
Reimplemented from \fBPoppler::Link\fP\&.
.PP
Definition at line 662 of file poppler\-link\&.cc\&.
.SS "QString LinkJavaScript::script () const"
The JS code 
.PP
Definition at line 667 of file poppler\-link\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
