.TH "Prbsgen" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prbsgen
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBG7\fP = 0x00000041, \fBG8\fP = 0x0000008E, \fBG15\fP = 0x00004001, \fBG16\fP = 0x00008016, \fBG23\fP = 0x00400010, \fBG24\fP = 0x0080000D, \fBG31\fP = 0x40000004, \fBG32\fP = 0x80000057 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_poly\fP (uint32_t poly)"
.br
.ti -1c
.RI "void \fBset_stat\fP (uint32_t stat)"
.br
.ti -1c
.RI "void \fBsync_forw\fP (uint32_t bits)"
.br
.ti -1c
.RI "void \fBsync_back\fP (uint32_t bits)"
.br
.ti -1c
.RI "int \fBstep\fP (void)"
.br
.ti -1c
.RI "void \fBcrc_in\fP (int b)"
.br
.ti -1c
.RI "int \fBcrc_out\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBstat\fP (void) const"
.br
.ti -1c
.RI "uint32_t \fBpoly\fP (void) const"
.br
.ti -1c
.RI "uint32_t \fBmask\fP (void) const"
.br
.ti -1c
.RI "uint32_t \fBhbit\fP (void) const"
.br
.ti -1c
.RI "int \fBdegr\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file prbsgen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
