.TH "ProgressBarData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressBarData \- generic data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <progressbardata\&.h>\fP
.PP
Inherits \fBGenericData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressBarData\fP (QObject *parent, QWidget *widget, int duration)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~ProgressBarData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.RI "event filter "
.ti -1c
.RI "virtual int \fBvalue\fP (void) const"
.br
.RI "progressbar value (during animation) "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP (int)"
.br
.RI "triggered by progressBar::valueChanged "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "const int & \fBstartValue\fP (void) const"
.br
.ti -1c
.RI "void \fBsetStartValue\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "const int & \fBendValue\fP (void) const"
.br
.ti -1c
.RI "void \fBsetEndValue\fP (int \fBvalue\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
generic data 
.PP
Definition at line 33 of file progressbardata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
