.TH "PS_DesignMap_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_DesignMap_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBnum_points\fP"
.br
.ti -1c
.RI "FT_Long * \fBdesign_points\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBblend_points\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 286 of file t1tables\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
