.TH "PS_HintsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_HintsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBmagic\fP"
.br
.ti -1c
.RI "PS_Hint_Type \fBhint_type\fP"
.br
.ti -1c
.RI "\fBPS_DimensionRec\fP \fBdimension\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file pshrec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
