.TH "PS_MaskRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_MaskRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_bits\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_bits\fP"
.br
.ti -1c
.RI "FT_Byte * \fBbytes\fP"
.br
.ti -1c
.RI "FT_UInt \fBend_point\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file pshrec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
