.TH "PS_Parser_FuncsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_Parser_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(\fBPS_Parser\fP parser, FT_Byte *base, FT_Byte *limit, FT_Memory memory)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(\fBPS_Parser\fP parser)"
.br
.ti -1c
.RI "void(* \fBskip_spaces\fP )(\fBPS_Parser\fP parser)"
.br
.ti -1c
.RI "void(* \fBskip_PS_token\fP )(\fBPS_Parser\fP parser)"
.br
.ti -1c
.RI "FT_Long(* \fBto_int\fP )(\fBPS_Parser\fP parser)"
.br
.ti -1c
.RI "FT_Fixed(* \fBto_fixed\fP )(\fBPS_Parser\fP parser, FT_Int power_ten)"
.br
.ti -1c
.RI "FT_Error(* \fBto_bytes\fP )(\fBPS_Parser\fP parser, FT_Byte *bytes, FT_Offset max_bytes, FT_ULong *pnum_bytes, FT_Bool delimiters)"
.br
.ti -1c
.RI "FT_Int(* \fBto_coord_array\fP )(\fBPS_Parser\fP parser, FT_Int max_coords, FT_Short *coords)"
.br
.ti -1c
.RI "FT_Int(* \fBto_fixed_array\fP )(\fBPS_Parser\fP parser, FT_Int max_values, FT_Fixed *values, FT_Int power_ten)"
.br
.ti -1c
.RI "void(* \fBto_token\fP )(\fBPS_Parser\fP parser, \fBT1_Token\fP token)"
.br
.ti -1c
.RI "void(* \fBto_token_array\fP )(\fBPS_Parser\fP parser, \fBT1_Token\fP tokens, FT_UInt max_tokens, FT_Int *pnum_tokens)"
.br
.ti -1c
.RI "FT_Error(* \fBload_field\fP )(\fBPS_Parser\fP parser, const \fBT1_Field\fP field, void **objects, FT_UInt max_objects, FT_ULong *pflags)"
.br
.ti -1c
.RI "FT_Error(* \fBload_field_table\fP )(\fBPS_Parser\fP parser, const \fBT1_Field\fP field, void **objects, FT_UInt max_objects, FT_ULong *pflags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 342 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
