.TH "PS_Table_FuncsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_Table_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Error(* \fBinit\fP )(PS_Table \fBtable\fP, FT_Int count, FT_Memory memory)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(PS_Table \fBtable\fP)"
.br
.ti -1c
.RI "FT_Error(* \fBadd\fP )(PS_Table \fBtable\fP, FT_Int idx, void *object, FT_UInt length)"
.br
.ti -1c
.RI "void(* \fBrelease\fP )(PS_Table \fBtable\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
