.TH "PS_TableRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_TableRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte * \fBblock\fP"
.br
.ti -1c
.RI "FT_Offset \fBcursor\fP"
.br
.ti -1c
.RI "FT_Offset \fBcapacity\fP"
.br
.ti -1c
.RI "FT_ULong \fBinit\fP"
.br
.ti -1c
.RI "FT_Int \fBmax_elems\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_elems\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBelements\fP"
.br
.ti -1c
.RI "FT_UInt * \fBlengths\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBPS_Table_FuncsRec\fP \fBfuncs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 120 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
