.TH "PSAux_ServiceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSAux_ServiceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBPS_Table_FuncsRec\fP * \fBps_table_funcs\fP"
.br
.ti -1c
.RI "const \fBPS_Parser_FuncsRec\fP * \fBps_parser_funcs\fP"
.br
.ti -1c
.RI "const \fBT1_Builder_FuncsRec\fP * \fBt1_builder_funcs\fP"
.br
.ti -1c
.RI "const \fBT1_Decoder_FuncsRec\fP * \fBt1_decoder_funcs\fP"
.br
.ti -1c
.RI "void(* \fBt1_decrypt\fP )(FT_Byte *buffer, FT_Offset length, FT_UShort seed)"
.br
.ti -1c
.RI "\fBT1_CMap_Classes\fP \fBt1_cmap_classes\fP"
.br
.ti -1c
.RI "const \fBAFM_Parser_FuncsRec\fP * \fBafm_parser_funcs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 798 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
