.TH "PSFont8Info" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSFont8Info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRef\fP \fBfontID\fP"
.br
.ti -1c
.RI "int * \fBcodeToGID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 915 of file PSOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
