.TH "PSFontParam16" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSFontParam16
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPSFontParam16\fP (\fBGooString\fP *nameA, int wModeA, \fBGooString\fP *psFontNameA, \fBGooString\fP *encodingA)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBname\fP"
.br
.ti -1c
.RI "int \fBwMode\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBpsFontName\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBencoding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file GlobalParams\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
