.TH "PSH_Hint_TableRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_Hint_TableRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBmax_hints\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_hints\fP"
.br
.ti -1c
.RI "PSH_Hint \fBhints\fP"
.br
.ti -1c
.RI "PSH_Hint * \fBsort\fP"
.br
.ti -1c
.RI "PSH_Hint * \fBsort_global\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_zones\fP"
.br
.ti -1c
.RI "\fBPSH_ZoneRec\fP * \fBzones\fP"
.br
.ti -1c
.RI "\fBPSH_Zone\fP \fBzone\fP"
.br
.ti -1c
.RI "\fBPS_Mask_Table\fP \fBhint_masks\fP"
.br
.ti -1c
.RI "\fBPS_Mask_Table\fP \fBcounter_masks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file pshalgo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
