.TH "PSH_GlyphRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_GlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_points\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_contours\fP"
.br
.ti -1c
.RI "\fBPSH_Point\fP \fBpoints\fP"
.br
.ti -1c
.RI "\fBPSH_Contour\fP \fBcontours\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP * \fBoutline\fP"
.br
.ti -1c
.RI "PSH_Globals \fBglobals\fP"
.br
.ti -1c
.RI "\fBPSH_Hint_TableRec\fP \fBhint_tables\fP [2]"
.br
.ti -1c
.RI "FT_Bool \fBvertical\fP"
.br
.ti -1c
.RI "FT_Int \fBmajor_dir\fP"
.br
.ti -1c
.RI "FT_Int \fBminor_dir\fP"
.br
.ti -1c
.RI "FT_Bool \fBdo_horz_hints\fP"
.br
.ti -1c
.RI "FT_Bool \fBdo_vert_hints\fP"
.br
.ti -1c
.RI "FT_Bool \fBdo_horz_snapping\fP"
.br
.ti -1c
.RI "FT_Bool \fBdo_vert_snapping\fP"
.br
.ti -1c
.RI "FT_Bool \fBdo_stem_adjust\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 189 of file pshalgo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
