.TH "PSH_Blue_ZoneRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_Blue_ZoneRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBorg_ref\fP"
.br
.ti -1c
.RI "FT_Int \fBorg_delta\fP"
.br
.ti -1c
.RI "FT_Int \fBorg_top\fP"
.br
.ti -1c
.RI "FT_Int \fBorg_bottom\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_ref\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_delta\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_bottom\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_top\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file pshglob\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
