.TH "PSH_PointRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_PointRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPSH_Point\fP \fBprev\fP"
.br
.ti -1c
.RI "\fBPSH_Point\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBPSH_Contour\fP \fBcontour\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags2\fP"
.br
.ti -1c
.RI "FT_Char \fBdir_in\fP"
.br
.ti -1c
.RI "FT_Char \fBdir_out\fP"
.br
.ti -1c
.RI "PSH_Hint \fBhint\fP"
.br
.ti -1c
.RI "FT_Pos \fBorg_u\fP"
.br
.ti -1c
.RI "FT_Pos \fBorg_v\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file pshalgo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
