.TH "PSHinter_Interface_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSHinter_Interface_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPSH_Globals_Funcs\fP(* \fBget_globals_funcs\fP )(\fBFT_Module\fP module)"
.br
.ti -1c
.RI "\fBT1_Hints_Funcs\fP(* \fBget_t1_funcs\fP )(\fBFT_Module\fP module)"
.br
.ti -1c
.RI "\fBT2_Hints_Funcs\fP(* \fBget_t2_funcs\fP )(\fBFT_Module\fP module)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 672 of file pshints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
