.TH "PSObject" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSObject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PSObjectType \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   GBool \fBbooln\fP"
.br
.ti -1c
.RI "   int \fBintg\fP"
.br
.ti -1c
.RI "   double \fBreal\fP"
.br
.ti -1c
.RI "   PSOp \fBop\fP"
.br
.ti -1c
.RI "   int \fBblk\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 984 of file Function\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
