.TH "PSStack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSStack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBpushBool\fP (GBool booln)"
.br
.ti -1c
.RI "void \fBpushInt\fP (int intg)"
.br
.ti -1c
.RI "void \fBpushReal\fP (double real)"
.br
.ti -1c
.RI "GBool \fBpopBool\fP ()"
.br
.ti -1c
.RI "int \fBpopInt\fP ()"
.br
.ti -1c
.RI "double \fBpopNum\fP ()"
.br
.ti -1c
.RI "GBool \fBempty\fP ()"
.br
.ti -1c
.RI "GBool \fBtopIsInt\fP ()"
.br
.ti -1c
.RI "GBool \fBtopTwoAreInts\fP ()"
.br
.ti -1c
.RI "GBool \fBtopIsReal\fP ()"
.br
.ti -1c
.RI "GBool \fBtopTwoAreNums\fP ()"
.br
.ti -1c
.RI "void \fBcopy\fP (int n)"
.br
.ti -1c
.RI "void \fBroll\fP (int n, int j)"
.br
.ti -1c
.RI "void \fBindex\fP (int i)"
.br
.ti -1c
.RI "void \fBpop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 997 of file Function\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
