.TH "QOscBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QOscBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.PP
Inherited by \fBQOscClient\fP, and \fBQOscServer\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQOscBase\fP (QObject *)"
.br
.ti -1c
.RI "virtual void \fBsetSocket\fP (QUdpSocket *)"
.br
.ti -1c
.RI "QUdpSocket * \fBsocket\fP () const"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBfillQByteArrayUp\fP (QByteArray &in)"
.br
.ti -1c
.RI "static QByteArray \fBreverseQByteArray\fP (QByteArray in)"
.br
.ti -1c
.RI "static QByteArray \fBfromString\fP (QString)"
.br
.ti -1c
.RI "static QByteArray \fBfromInt32\fP (qint32)"
.br
.ti -1c
.RI "static QByteArray \fBfromFloat\fP (float)"
.br
.ti -1c
.RI "static QString \fBtoString\fP (const QByteArray &)"
.br
.ti -1c
.RI "static qint32 \fBtoInt32\fP (const QByteArray &)"
.br
.ti -1c
.RI "static float \fBtoFloat\fP (const QByteArray &)"
.br
.ti -1c
.RI "static void \fBoscMessageParseArgs\fP (const QVariant &, QString &, QByteArray &)"
.br
.ti -1c
.RI "static QByteArray \fBoscMessage\fP (QString path, QVariant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file qosctypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
