.TH "QPaintEnginePrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QPaintEnginePrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSvgPaintEnginePrivate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtransformSystemClip\fP ()"
.br
.ti -1c
.RI "void \fBsetSystemTransform\fP (const QTransform &xform)"
.br
.ti -1c
.RI "void \fBsetSystemViewport\fP (const QRegion &region)"
.br
.ti -1c
.RI "virtual void \fBsystemStateChanged\fP ()"
.br
.ti -1c
.RI "void \fBdrawBoxTextItem\fP (const QPointF &p, const QTextItemInt &ti)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QPaintDevice * \fBpdev\fP"
.br
.ti -1c
.RI "QPaintEngine * \fBq_ptr\fP"
.br
.ti -1c
.RI "QRegion \fBsystemClip\fP"
.br
.ti -1c
.RI "QRect \fBsystemRect\fP"
.br
.ti -1c
.RI "QRegion \fBsystemViewport\fP"
.br
.ti -1c
.RI "QTransform \fBsystemTransform\fP"
.br
.ti -1c
.RI "QWidget * \fBcurrentClipWidget\fP"
.br
.ti -1c
.RI "uint \fBhasSystemTransform\fP: 1"
.br
.ti -1c
.RI "uint \fBhasSystemViewport\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file paintengine_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
