.TH "qt_meta_stringdata_Ms__SegmentView_t" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_Ms__SegmentView_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [1]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 704 of file moc_debugger\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
