.TH "QtLocalPeer" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QtLocalPeer
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmessageReceived\fP (const QString &message)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQtLocalPeer\fP (QObject *parent=0, const QString &appId=QString())"
.br
.ti -1c
.RI "bool \fBisClient\fP ()"
.br
.ti -1c
.RI "bool \fBsendMessage\fP (const QString &message, int timeout)"
.br
.ti -1c
.RI "QString \fBapplicationId\fP () const"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBreceiveConnection\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBsocketName\fP"
.br
.ti -1c
.RI "QLocalServer * \fBserver\fP"
.br
.ti -1c
.RI "\fBQtLP_Private::QtLockedFile\fP \fBlockFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file qtlocalpeer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
