.TH "QXmlUtils" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QXmlUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisEncName\fP (const QString &encName)"
.br
.ti -1c
.RI "static bool \fBisChar\fP (const QChar c)"
.br
.ti -1c
.RI "static bool \fBisNameChar\fP (const QChar c)"
.br
.ti -1c
.RI "static bool \fBisLetter\fP (const QChar c)"
.br
.ti -1c
.RI "static bool \fBisNCName\fP (const QStringRef &ncName)"
.br
.ti -1c
.RI "static bool \fBisNCName\fP (const QString &ncName)"
.br
.ti -1c
.RI "static bool \fBisPublicID\fP (const QString &candidate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file xmlutils_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
