.TH "QZipReader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QZipReader
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FileInfo::filePath The full filepath inside the archive\&.
.PP
FileInfo::isDir A boolean type indicating if the entry is a directory\&.
.PP
FileInfo::isFile A boolean type, if it is one this entry is a file\&.
.PP
FileInfo::isSymLink A boolean type, if it is one this entry is symbolic link\&.
.PP
FileInfo::permissions A list of flags for the permissions of this entry\&.
.PP
FileInfo::crc32 The calculated checksum as a crc32 type\&.
.PP
FileInfo::size The total size of the unpacked content\&.
.PP
FileInfo::d 

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
