.TH "rand_meth_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rand_meth_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBseed\fP )(const void *buf, int num)"
.br
.ti -1c
.RI "int(* \fBbytes\fP )(unsigned char *buf, int num)"
.br
.ti -1c
.RI "void(* \fBcleanup\fP )(void)"
.br
.ti -1c
.RI "void(* \fBadd\fP )(const void *buf, int num, double entropy)"
.br
.ti -1c
.RI "int(* \fBpseudorand\fP )(unsigned char *buf, int num)"
.br
.ti -1c
.RI "int(* \fBstatus\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file rand\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
