.TH "RescaleDrawImage" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RescaleDrawImage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCairoRescaleBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "cairo_surface_t * \fBgetSourceImage\fP (\fBStream\fP *str, int widthA, int height, int scaledWidth, int scaledHeight, GBool printing, \fBGfxImageColorMap\fP *colorMapA, int *maskColorsA)"
.br
.ti -1c
.RI "void \fBgetRow\fP (int row_num, uint32_t *row_data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3011 of file CairoOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
