.TH "RGBGrayEncoder" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBGrayEncoder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRGBGrayEncoder\fP (\fBStream\fP *strA)"
.br
.ti -1c
.RI "virtual StreamKind \fBgetKind\fP ()"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetChar\fP ()"
.br
.ti -1c
.RI "virtual int \fBlookChar\fP ()"
.br
.ti -1c
.RI "virtual \fBGooString\fP * \fBgetPSFilter\fP (int, const char *)"
.br
.ti -1c
.RI "virtual GBool \fBisBinary\fP (GBool)"
.br
.ti -1c
.RI "virtual GBool \fBisEncoder\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1271 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
