.TH "Rngen" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rngen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (uint32_t seed)"
.br
.ti -1c
.RI "uint32_t \fBirand\fP (void)"
.br
.ti -1c
.RI "double \fBurand\fP (void)"
.br
.ti -1c
.RI "double \fBgrand\fP (void)"
.br
.ti -1c
.RI "void \fBgrand\fP (double *x, double *y)"
.br
.ti -1c
.RI "float \fBurandf\fP (void)"
.br
.ti -1c
.RI "float \fBgrandf\fP (void)"
.br
.ti -1c
.RI "void \fBgrandf\fP (float *x, float *y)"
.br
.ti -1c
.RI "\fBRngen\fP (const \fBRngen\fP &)"
.br
.ti -1c
.RI "\fBRngen\fP & \fBoperator=\fP (const \fBRngen\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file rngen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
