.TH "SampledFunction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampledFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampledFunction\fP (\fBObject\fP *funcObj, \fBDict\fP *dict)"
.br
.ti -1c
.RI "virtual \fBFunction\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetType\fP ()"
.br
.ti -1c
.RI "virtual void \fBtransform\fP (double *in, double *out)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBhasDifferentResultSet\fP (\fBFunction\fP *func)"
.br
.ti -1c
.RI "int \fBgetSampleSize\fP (int i)"
.br
.ti -1c
.RI "double \fBgetEncodeMin\fP (int i)"
.br
.ti -1c
.RI "double \fBgetEncodeMax\fP (int i)"
.br
.ti -1c
.RI "double \fBgetDecodeMin\fP (int i)"
.br
.ti -1c
.RI "double \fBgetDecodeMax\fP (int i)"
.br
.ti -1c
.RI "double * \fBgetSamples\fP ()"
.br
.ti -1c
.RI "int \fBgetSampleNumber\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 125 of file Function\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
