.TH "Sample" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSample\fP (int ch, short *val, int f, int sr)"
.br
.ti -1c
.RI "bool \fBread\fP (const QString &)"
.br
.ti -1c
.RI "int \fBframes\fP () const"
.br
.ti -1c
.RI "short * \fBdata\fP () const"
.br
.ti -1c
.RI "int \fBchannel\fP () const"
.br
.ti -1c
.RI "int \fBsampleRate\fP () const"
.br
.ti -1c
.RI "void \fBsetLoopStart\fP (int v)"
.br
.ti -1c
.RI "void \fBsetLoopEnd\fP (int v)"
.br
.ti -1c
.RI "void \fBsetLoopMode\fP (int v)"
.br
.ti -1c
.RI "int \fBloopStart\fP ()"
.br
.ti -1c
.RI "int \fBloopEnd\fP ()"
.br
.ti -1c
.RI "int \fBloopMode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file sample\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
