.TH "libmscore/score.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/score.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br
\fC#include 'select\&.h'\fP
.br
\fC#include 'synthesizerstate\&.h'\fP
.br
\fC#include 'mscoreview\&.h'\fP
.br
\fC#include 'spannermap\&.h'\fP
.br
\fC#include 'layoutbreak\&.h'\fP
.br
\fC#include 'property\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::MeasureBaseList\fP"
.br
.ti -1c
.RI "struct \fBMs::MidiMapping\fP"
.br
.ti -1c
.RI "struct \fBMs::MidiInputEvent\fP"
.br
.ti -1c
.RI "struct \fBMs::Position\fP"
.br
.ti -1c
.RI "struct \fBMs::Layer\fP"
.br
.ti -1c
.RI "class \fBMs::CmdState\fP"
.br
.ti -1c
.RI "class \fBMs::UpdateState\fP"
.br
.ti -1c
.RI "class \fBMs::Movements\fP"
.br
.ti -1c
.RI "class \fBMs::Score\fP"
.br
.ti -1c
.RI "class \fBMs::MasterScore\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QFlags< LayoutFlag > \fBMs::LayoutFlags\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPOS\fP : char { \fBCURRENT\fP, \fBLEFT\fP, \fBRIGHT\fP }"
.br
.ti -1c
.RI "enum \fBPad\fP : char { \fBNOTE00\fP, \fBNOTE0\fP, \fBNOTE1\fP, \fBNOTE2\fP, \fBNOTE4\fP, \fBNOTE8\fP, \fBNOTE16\fP, \fBNOTE32\fP, \fBNOTE64\fP, \fBNOTE128\fP, \fBREST\fP, \fBDOT\fP, \fBDOTDOT\fP, \fBDOT3\fP, \fBDOT4\fP }"
.br
.ti -1c
.RI "enum \fBLayoutMode\fP : char { \fBPAGE\fP, \fBFLOAT\fP, \fBLINE\fP, \fBSYSTEM\fP }"
.br
.ti -1c
.RI "enum \fBLayoutFlag\fP : char { \fBNO_FLAGS\fP = 0, \fBFIX_PITCH_VELO\fP = 1, \fBPLAY_EVENTS\fP = 2 }"
.br
.ti -1c
.RI "enum \fBPlayMode\fP : char { \fBSYNTHESIZER\fP, \fBAUDIO\fP }"
.br
.ti -1c
.RI "enum \fBUpdateMode\fP { \fBDoNothing\fP, \fBUpdate\fP, \fBUpdateAll\fP, \fBLayout\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMs::fixTicks\fP ()"
.br
.ti -1c
.RI "\fBMs::Q_DECLARE_OPERATORS_FOR_FLAGS\fP (LayoutFlags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of Score class\&. 
.PP
Definition in file \fBscore\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
