.TH "ScrollBarData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScrollBarData \- scrollbar data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scrollbardata\&.h>\fP
.PP
Inherits \fBSliderData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScrollBarData\fP (QObject *parent, QWidget *target, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~ScrollBarData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *, QEvent *)"
.br
.RI "event filter "
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBanimation\fP (QStyle::SubControl) const"
.br
.RI "return animation for a given subcontrol "
.ti -1c
.RI "virtual qreal \fBopacity\fP (QStyle::SubControl) const"
.br
.RI "return default opacity for a given subcontrol "
.ti -1c
.RI "virtual bool \fBisHovered\fP (QStyle::SubControl control) const"
.br
.RI "return default opacity for a given subcontrol "
.ti -1c
.RI "virtual QRect \fBsubControlRect\fP (QStyle::SubControl control) const"
.br
.RI "subControlRect "
.ti -1c
.RI "virtual void \fBsetSubControlRect\fP (QStyle::SubControl control, const QRect &rect)"
.br
.RI "subcontrol rect "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int duration)"
.br
.RI "duration "
.ti -1c
.RI "virtual void \fBsetAddLineOpacity\fP (qreal value)"
.br
.RI "addLine opacity "
.ti -1c
.RI "virtual qreal \fBaddLineOpacity\fP (void) const"
.br
.RI "addLine opacity "
.ti -1c
.RI "virtual void \fBsetSubLineOpacity\fP (qreal value)"
.br
.RI "subLine opacity "
.ti -1c
.RI "virtual qreal \fBsubLineOpacity\fP (void) const"
.br
.RI "subLine opacity "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBclearAddLineRect\fP (void)"
.br
.RI "clear addLineRect "
.ti -1c
.RI "void \fBclearSubLineRect\fP (void)"
.br
.RI "clear subLineRect "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhoverMoveEvent\fP (QObject *, QEvent *)"
.br
.RI "hoverMoveEvent "
.ti -1c
.RI "virtual void \fBhoverLeaveEvent\fP (QObject *, QEvent *)"
.br
.RI "hoverMoveEvent "
.ti -1c
.RI "virtual void \fBupdateAddLineArrow\fP (QStyle::SubControl)"
.br
.RI "update add line arrow "
.ti -1c
.RI "virtual void \fBupdateSubLineArrow\fP (QStyle::SubControl)"
.br
.RI "update sub line arrow "
.in -1c
.PP
.RI "\fBhover flags\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual bool \fBaddLineArrowHovered\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetAddLineArrowHovered\fP (bool value)"
.br
.ti -1c
.RI "virtual bool \fBsubLineArrowHovered\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsetSubLineArrowHovered\fP (bool value)"
.br
.in -1c
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBaddLineOpacity\fP"
.br
.ti -1c
.RI "qreal \fBsubLineOpacity\fP"
.br
.in -1c
.SS "timelines"

.in +1c
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBaddLineAnimation\fP (void) const"
.br
.ti -1c
.RI "virtual const \fBAnimation::Pointer\fP & \fBsubLineAnimation\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
scrollbar data 
.PP
Definition at line 33 of file scrollbardata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
