.TH "mscore/selectdialog.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mscore/selectdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'libmscore/select\&.h'\fP
.br
\fC#include 'selectdialog\&.h'\fP
.br
\fC#include 'libmscore/element\&.h'\fP
.br
\fC#include 'libmscore/system\&.h'\fP
.br
\fC#include 'libmscore/score\&.h'\fP
.br
\fC#include 'libmscore/slur\&.h'\fP
.br
\fC#include 'libmscore/articulation\&.h'\fP
.br
\fC#include 'musescore\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of class Selection plus other selection related functions\&. 
.PP
Definition in file \fBselectdialog\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
