.TH "SeparatorDelegate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeparatorDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits QStyledItemDelegate\&.
.PP
Inherited by \fBMs::OperationsDelegate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSeparatorDelegate\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBsetFrozenRowIndex\fP (int index)"
.br
.ti -1c
.RI "void \fBsetFrozenColIndex\fP (int index)"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file importmidi_view\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
