.TH "SetDefaultColors" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetDefaultColors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNormalBackground\fP [3]"
.br
.ti -1c
.RI "int \fBAlternateBackground\fP [3]"
.br
.ti -1c
.RI "int \fBNormalText\fP [3]"
.br
.ti -1c
.RI "int \fBInactiveText\fP [3]"
.br
.ti -1c
.RI "int \fBActiveText\fP [3]"
.br
.ti -1c
.RI "int \fBLinkText\fP [3]"
.br
.ti -1c
.RI "int \fBVisitedText\fP [3]"
.br
.ti -1c
.RI "int \fBNegativeText\fP [3]"
.br
.ti -1c
.RI "int \fBNeutralText\fP [3]"
.br
.ti -1c
.RI "int \fBPositiveText\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 141 of file colorscheme\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
