.TH "SfzListDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SfzListDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSfzListDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "std::vector< struct \fBSfzNamePath\fP > \fBgetNamePaths\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (const QString &name, const QString &path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file zerberusgui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
