.TH "SfzRegion" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SfzRegion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const QString &)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "int \fBreadKey\fP (const QString &, \fBSfzControl\fP c) const"
.br
.ti -1c
.RI "void \fBreadOp\fP (const QString &token, const QString &data, \fBSfzControl\fP &c)"
.br
.ti -1c
.RI "void \fBsetZone\fP (\fBZone\fP *) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "double \fBamp_veltrack\fP"
.br
.ti -1c
.RI "double \fBampeg_delay\fP"
.br
.ti -1c
.RI "double \fBampeg_start\fP"
.br
.ti -1c
.RI "double \fBampeg_attack\fP"
.br
.ti -1c
.RI "double \fBampeg_hold\fP"
.br
.ti -1c
.RI "double \fBampeg_decay\fP"
.br
.ti -1c
.RI "double \fBampeg_sustain\fP"
.br
.ti -1c
.RI "double \fBampeg_release\fP"
.br
.ti -1c
.RI "double \fBrt_decay\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2delay\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2attack\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2hold\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2decay\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2sustain\fP"
.br
.ti -1c
.RI "double \fBampeg_vel2release\fP"
.br
.ti -1c
.RI "QString \fBsample\fP"
.br
.ti -1c
.RI "int \fBlochan\fP"
.br
.ti -1c
.RI "int \fBhichan\fP"
.br
.ti -1c
.RI "int \fBlokey\fP"
.br
.ti -1c
.RI "int \fBhikey\fP"
.br
.ti -1c
.RI "int \fBlovel\fP"
.br
.ti -1c
.RI "int \fBhivel\fP"
.br
.ti -1c
.RI "int \fBpitch_keycenter\fP"
.br
.ti -1c
.RI "double \fBhirand\fP"
.br
.ti -1c
.RI "double \fBlorand\fP"
.br
.ti -1c
.RI "int \fBon_locc\fP [128]"
.br
.ti -1c
.RI "int \fBon_hicc\fP [128]"
.br
.ti -1c
.RI "int \fBlocc\fP [128]"
.br
.ti -1c
.RI "int \fBhicc\fP [128]"
.br
.ti -1c
.RI "bool \fBuse_cc\fP"
.br
.ti -1c
.RI "int \fBoff_by\fP"
.br
.ti -1c
.RI "int \fBgroup\fP"
.br
.ti -1c
.RI "int \fBseq_length\fP"
.br
.ti -1c
.RI "int \fBseq_position\fP"
.br
.ti -1c
.RI "double \fBvolume\fP"
.br
.ti -1c
.RI "int \fBoctave_offset\fP"
.br
.ti -1c
.RI "int \fBnote_offset\fP"
.br
.ti -1c
.RI "int \fBtune\fP"
.br
.ti -1c
.RI "int \fBtranspose\fP"
.br
.ti -1c
.RI "double \fBpitch_keytrack\fP"
.br
.ti -1c
.RI "int \fBloopStart\fP"
.br
.ti -1c
.RI "int \fBloopEnd\fP"
.br
.ti -1c
.RI "Trigger \fBtrigger\fP"
.br
.ti -1c
.RI "LoopMode \fBloop_mode\fP"
.br
.ti -1c
.RI "OffMode \fBoff_mode\fP"
.br
.ti -1c
.RI "std::map< int, double > \fBgain_oncc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file sfz\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
