.TH "SignatureInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignatureInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignatureInfo\fP (SignatureValidationStatus, CertificateValidationStatus)"
.br
.ti -1c
.RI "SignatureValidationStatus \fBgetSignatureValStatus\fP ()"
.br
.ti -1c
.RI "CertificateValidationStatus \fBgetCertificateValStatus\fP ()"
.br
.ti -1c
.RI "char * \fBgetSignerName\fP ()"
.br
.ti -1c
.RI "time_t \fBgetSigningTime\fP ()"
.br
.ti -1c
.RI "bool \fBisSubfilterSupported\fP ()"
.br
.ti -1c
.RI "void \fBsetSignatureValStatus\fP (enum SignatureValidationStatus)"
.br
.ti -1c
.RI "void \fBsetCertificateValStatus\fP (enum CertificateValidationStatus)"
.br
.ti -1c
.RI "void \fBsetSignerName\fP (char *)"
.br
.ti -1c
.RI "void \fBsetSigningTime\fP (time_t)"
.br
.ti -1c
.RI "void \fBsetSubFilterSupport\fP (bool isSupported)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file SignatureInfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
