.TH "SliderData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliderData \- scrollbar data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sliderdata\&.h>\fP
.PP
Inherits \fBGenericData\fP\&.
.PP
Inherited by \fBScrollBarData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSliderData\fP (QObject *parent, QWidget *target, int duration)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~SliderData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBupdateState\fP (bool)"
.br
.RI "update state "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBsliderHovered\fP (void) const"
.br
.RI "hover "
.ti -1c
.RI "virtual void \fBsetSliderHovered\fP (bool value)"
.br
.RI "hover "
.ti -1c
.RI "virtual void \fBupdateSlider\fP (QStyle::SubControl)"
.br
.RI "update slider "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
scrollbar data 
.PP
Definition at line 33 of file sliderdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
