.TH "Sound" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP * \fBgetObject\fP ()"
.br
.ti -1c
.RI "\fBStream\fP * \fBgetStream\fP ()"
.br
.ti -1c
.RI "SoundKind \fBgetSoundKind\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFileName\fP ()"
.br
.ti -1c
.RI "double \fBgetSamplingRate\fP ()"
.br
.ti -1c
.RI "int \fBgetChannels\fP ()"
.br
.ti -1c
.RI "int \fBgetBitsPerSample\fP ()"
.br
.ti -1c
.RI "SoundEncoding \fBgetEncoding\fP ()"
.br
.ti -1c
.RI "\fBSound\fP * \fBcopy\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSound\fP * \fBparseSound\fP (\fBObject\fP *s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file Sound\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
