.TH "sources.SourceBlockFormat" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources.SourceBlockFormat \- SOURCE BLOCK FORMAT CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, id, start, column, end)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBstart\fP"
.br
.ti -1c
.RI "\fBcolumn\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SOURCE BLOCK FORMAT CLASS\&. 

A simple class containing compiled regular expressions to detect potential documentation format block comments within C source code\&.
.PP
The `column' pattern must contain a group to `unbox' the content of documentation comment blocks\&.
.PP
Later on, paragraphs are converted to long lines, which simplifies the regular expressions that act upon the text\&. 
.PP
Definition at line 48 of file sources\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def sources\&.SourceBlockFormat\&.__init__ ( self,  id,  start,  column,  end)"

.PP
.nf
Create a block pattern, used to recognize special documentation
   blocks.
.fi
.PP
 
.PP
Definition at line 50 of file sources\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
