.TH "sources.SourceBlock" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources.SourceBlock \- SOURCE BLOCK CLASS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, processor, filename, lineno, lines)"
.br
.ti -1c
.RI "def \fBlocation\fP (self)"
.br
.ti -1c
.RI "def \fBdump\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprocessor\fP"
.br
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.ti -1c
.RI "\fBlines\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SOURCE BLOCK CLASS\&. 

There are two important fields in a `SourceBlock' object\&.
.PP
self\&.lines A list of text lines for the corresponding block\&.
.PP
self\&.content For documentation comment blocks only, this is the block content that has been `unboxed' from its decoration\&. This is `None' for all other blocks (i\&.e\&., sources or ordinary comments with no starting markup tag) 
.PP
Definition at line 249 of file sources\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
