.TH "SParmId" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SParmId
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSParmId\fP (int v)"
.br
.ti -1c
.RI "\fBSParmId\fP (int a, int b, int c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      unsigned \fBsyntiId\fP:2"
.br
.ti -1c
.RI "      unsigned \fBsubsystemId\fP:4"
.br
.ti -1c
.RI "      unsigned \fBparamId\fP:16"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   unsigned \fBval\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file sparm_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
