.TH "SpinBoxEngine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinBoxEngine \- handle spinbox arrows hover effect  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spinboxengine\&.h>\fP
.PP
Inherits \fBBaseEngine\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBunregisterWidget\fP (QObject *object)"
.br
.RI "remove widget from map "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinBoxEngine\fP (QObject *parent)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~SpinBoxEngine\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBregisterWidget\fP (QWidget *)"
.br
.RI "register widget "
.ti -1c
.RI "virtual bool \fBupdateState\fP (const QObject *object, QStyle::SubControl subControl, bool value)"
.br
.RI "state "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (const QObject *object, QStyle::SubControl subControl)"
.br
.RI "true if widget is animated "
.ti -1c
.RI "virtual qreal \fBopacity\fP (const QObject *object, QStyle::SubControl subControl)"
.br
.RI "animation opacity "
.ti -1c
.RI "virtual void \fBsetEnabled\fP (bool value)"
.br
.RI "enability "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int value)"
.br
.RI "duration "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
handle spinbox arrows hover effect 
.PP
Definition at line 35 of file spinboxengine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
