.TH "SpinBoxData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinBoxData \- handles spinbox arrows hover  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spinboxdata\&.h>\fP
.PP
Inherits \fBAnimationData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinBoxData\fP (QObject *, QWidget *, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~SpinBoxData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBupdateState\fP (QStyle::SubControl subControl, bool value)"
.br
.RI "animation state "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (QStyle::SubControl subControl) const"
.br
.RI "animation state "
.ti -1c
.RI "virtual qreal \fBopacity\fP (QStyle::SubControl subControl) const"
.br
.RI "opacity "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int duration)"
.br
.RI "duration "
.in -1c
.PP
.RI "\fBup arrow animation\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "qreal \fBupArrowOpacity\fP (void) const"
.br
.RI "opacity "
.ti -1c
.RI "void \fBsetUpArrowOpacity\fP (qreal value)"
.br
.RI "opacity "
.ti -1c
.RI "\fBAnimation::Pointer\fP \fBupArrowAnimation\fP (void) const"
.br
.RI "animation "
.in -1c
.in -1c
.PP
.RI "\fBdown arrow animation\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "qreal \fBdownArrowOpacity\fP (void) const"
.br
.RI "opacity "
.ti -1c
.RI "void \fBsetDownArrowOpacity\fP (qreal value)"
.br
.RI "opacity "
.ti -1c
.RI "\fBAnimation::Pointer\fP \fBdownArrowAnimation\fP (void) const"
.br
.RI "animation "
.in -1c
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBupArrowOpacity\fP"
.br
.RI "declare opacity property "
.ti -1c
.RI "qreal \fBdownArrowOpacity\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
handles spinbox arrows hover 
.PP
Definition at line 33 of file spinboxdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
