.TH "SplashOutFontFileID" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashOutFontFileID
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSplashFontFileID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashOutFontFileID\fP (\fBRef\fP *rA)"
.br
.ti -1c
.RI "GBool \fBmatches\fP (\fBSplashFontFileID\fP *id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1211 of file SplashOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
