.TH "SplashUnivariatePattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashUnivariatePattern
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSplashPattern\fP\&.
.PP
Inherited by \fBSplashAxialPattern\fP, and \fBSplashRadialPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashUnivariatePattern\fP (SplashColorMode colorMode, \fBGfxState\fP *state, \fBGfxUnivariateShading\fP *shading)"
.br
.ti -1c
.RI "virtual GBool \fBgetColor\fP (int x, int y, SplashColorPtr c)"
.br
.ti -1c
.RI "virtual GBool \fBtestPosition\fP (int x, int y)"
.br
.ti -1c
.RI "virtual GBool \fBisStatic\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBgetParameter\fP (double xs, double ys, double *t)=0"
.br
.ti -1c
.RI "virtual \fBGfxUnivariateShading\fP * \fBgetShading\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBisCMYK\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMatrix\fP \fBictm\fP"
.br
.ti -1c
.RI "double \fBt0\fP"
.br
.ti -1c
.RI "double \fBt1\fP"
.br
.ti -1c
.RI "double \fBdt\fP"
.br
.ti -1c
.RI "\fBGfxUnivariateShading\fP * \fBshading\fP"
.br
.ti -1c
.RI "\fBGfxState\fP * \fBstate\fP"
.br
.ti -1c
.RI "SplashColorMode \fBcolorMode\fP"
.br
.ti -1c
.RI "GfxColorSpaceMode \fBgfxMode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file SplashOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
