.TH "SplashTransparencyGroup" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashTransparencyGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtx\fP"
.br
.ti -1c
.RI "int \fBty\fP"
.br
.ti -1c
.RI "\fBSplashBitmap\fP * \fBtBitmap\fP"
.br
.ti -1c
.RI "\fBSplashBitmap\fP * \fBsoftmask\fP"
.br
.ti -1c
.RI "\fBGfxColorSpace\fP * \fBblendingColorSpace\fP"
.br
.ti -1c
.RI "GBool \fBisolated\fP"
.br
.ti -1c
.RI "\fBSplashBitmap\fP * \fBshape\fP"
.br
.ti -1c
.RI "GBool \fBknockout\fP"
.br
.ti -1c
.RI "SplashCoord \fBknockoutOpacity\fP"
.br
.ti -1c
.RI "GBool \fBfontAA\fP"
.br
.ti -1c
.RI "\fBSplashBitmap\fP * \fBorigBitmap\fP"
.br
.ti -1c
.RI "\fBSplash\fP * \fBorigSplash\fP"
.br
.ti -1c
.RI "\fBSplashTransparencyGroup\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1343 of file SplashOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
