.TH "SplashXPathAdjust" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashXPathAdjust
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfirstPt\fP"
.br
.ti -1c
.RI "int \fBlastPt\fP"
.br
.ti -1c
.RI "GBool \fBvert\fP"
.br
.ti -1c
.RI "SplashCoord \fBx0a\fP"
.br
.ti -1c
.RI "SplashCoord \fBx0b\fP"
.br
.ti -1c
.RI "SplashCoord \fBxma\fP"
.br
.ti -1c
.RI "SplashCoord \fBxmb\fP"
.br
.ti -1c
.RI "SplashCoord \fBx1a\fP"
.br
.ti -1c
.RI "SplashCoord \fBx1b\fP"
.br
.ti -1c
.RI "SplashCoord \fBx0\fP"
.br
.ti -1c
.RI "SplashCoord \fBx1\fP"
.br
.ti -1c
.RI "SplashCoord \fBxm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file SplashXPath\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
