.TH "SplashOutImageData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashOutImageData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImageStream\fP * \fBimgStr\fP"
.br
.ti -1c
.RI "\fBGfxImageColorMap\fP * \fBcolorMap\fP"
.br
.ti -1c
.RI "SplashColorPtr \fBlookup\fP"
.br
.ti -1c
.RI "int * \fBmaskColors\fP"
.br
.ti -1c
.RI "SplashColorMode \fBcolorMode\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "\fBImageStream\fP * \fBmaskStr\fP"
.br
.ti -1c
.RI "\fBGfxImageColorMap\fP * \fBmaskColorMap\fP"
.br
.ti -1c
.RI "SplashColor \fBmatteColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3003 of file SplashOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
