.TH "SplashFontFile" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashFontFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSplashFont\fP * \fBmakeFont\fP (SplashCoord *mat, SplashCoord *textMat)=0"
.br
.ti -1c
.RI "\fBSplashFontFileID\fP * \fBgetID\fP ()"
.br
.ti -1c
.RI "void \fBincRefCnt\fP ()"
.br
.ti -1c
.RI "void \fBdecRefCnt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBdoAdjustMatrix\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashFontFile\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *srcA)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSplashFontFileID\fP * \fBid\fP"
.br
.ti -1c
.RI "\fBSplashFontSrc\fP * \fBsrc\fP"
.br
.ti -1c
.RI "int \fBrefCnt\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSplashFontEngine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file SplashFontFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
