.TH "SplashPipe" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashPipe
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "\fBSplashPattern\fP * \fBpattern\fP"
.br
.ti -1c
.RI "Guchar \fBaInput\fP"
.br
.ti -1c
.RI "GBool \fBusesShape\fP"
.br
.ti -1c
.RI "SplashColorPtr \fBcSrc\fP"
.br
.ti -1c
.RI "SplashColor \fBcSrcVal\fP"
.br
.ti -1c
.RI "Guchar * \fBalpha0Ptr\fP"
.br
.ti -1c
.RI "GBool \fBknockout\fP"
.br
.ti -1c
.RI "Guchar \fBknockoutOpacity\fP"
.br
.ti -1c
.RI "SplashColorPtr \fBsoftMaskPtr\fP"
.br
.ti -1c
.RI "SplashColorPtr \fBdestColorPtr\fP"
.br
.ti -1c
.RI "int \fBdestColorMask\fP"
.br
.ti -1c
.RI "Guchar * \fBdestAlphaPtr\fP"
.br
.ti -1c
.RI "Guchar \fBshape\fP"
.br
.ti -1c
.RI "GBool \fBnoTransparency\fP"
.br
.ti -1c
.RI "SplashPipeResultColorCtrl \fBresultColorCtrl\fP"
.br
.ti -1c
.RI "GBool \fBnonIsolatedGroup\fP"
.br
.ti -1c
.RI "void(Splash::* \fBrun\fP )(\fBSplashPipe\fP *pipe)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file Splash\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
