.TH "SplashFontCacheTag" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashFontCacheTag
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "short \fBxFrac\fP"
.br
.ti -1c
.RI "short \fByFrac\fP"
.br
.ti -1c
.RI "int \fBmru\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file SplashFont\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
