.TH "SplashFontEngine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashFontEngine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashFontEngine\fP (GBool aa)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBgetFontFile\fP (\fBSplashFontFileID\fP *id)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadType1Font\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src, const char **enc)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadType1CFont\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src, const char **enc)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadOpenTypeT1CFont\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src, const char **enc)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadCIDFont\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadOpenTypeCFFFont\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src, int *codeToGID, int codeToGIDLen)"
.br
.ti -1c
.RI "\fBSplashFontFile\fP * \fBloadTrueTypeFont\fP (\fBSplashFontFileID\fP *idA, \fBSplashFontSrc\fP *src, int *codeToGID, int codeToGIDLen, int faceIndex=0)"
.br
.ti -1c
.RI "\fBSplashFont\fP * \fBgetFont\fP (\fBSplashFontFile\fP *fontFile, SplashCoord *textMat, SplashCoord *ctm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file SplashFontEngine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
