.TH "SplashState" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashState\fP (int width, int height, GBool vectorAntialias, \fBSplashScreenParams\fP *screenParams)"
.br
.ti -1c
.RI "\fBSplashState\fP (int width, int height, GBool vectorAntialias, \fBSplashScreen\fP *screenA)"
.br
.ti -1c
.RI "\fBSplashState\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "void \fBsetStrokePattern\fP (\fBSplashPattern\fP *strokePatternA)"
.br
.ti -1c
.RI "void \fBsetFillPattern\fP (\fBSplashPattern\fP *fillPatternA)"
.br
.ti -1c
.RI "void \fBsetScreen\fP (\fBSplashScreen\fP *screenA)"
.br
.ti -1c
.RI "void \fBsetLineDash\fP (SplashCoord *lineDashA, int lineDashLengthA, SplashCoord lineDashPhaseA)"
.br
.ti -1c
.RI "void \fBsetSoftMask\fP (\fBSplashBitmap\fP *softMaskA)"
.br
.ti -1c
.RI "void \fBsetFillOverprint\fP (GBool fillOverprintA)"
.br
.ti -1c
.RI "void \fBsetStrokeOverprint\fP (GBool strokeOverprintA)"
.br
.ti -1c
.RI "void \fBsetOverprintMode\fP (int overprintModeA)"
.br
.ti -1c
.RI "void \fBsetTransfer\fP (Guchar *red, Guchar *green, Guchar *blue, Guchar *gray)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSplash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file SplashState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
