.TH "SplashGlyphBitmap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashGlyphBitmap
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "GBool \fBaa\fP"
.br
.ti -1c
.RI "Guchar * \fBdata\fP"
.br
.ti -1c
.RI "GBool \fBfreeData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SplashGlyphBitmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
