.TH "SplashScreen" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashScreen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashScreen\fP (\fBSplashScreenParams\fP *params)"
.br
.ti -1c
.RI "\fBSplashScreen\fP (\fBSplashScreen\fP *screen)"
.br
.ti -1c
.RI "\fBSplashScreen\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "int \fBtest\fP (int x, int y, Guchar value)"
.br
.ti -1c
.RI "GBool \fBisStatic\fP (Guchar value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file SplashScreen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
