.TH "SplashXPathScanner" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashXPathScanner
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashXPathScanner\fP (\fBSplashXPath\fP *xPathA, GBool eoA, int clipYMin, int clipYMax)"
.br
.ti -1c
.RI "void \fBgetBBox\fP (int *xMinA, int *yMinA, int *xMaxA, int *yMaxA)"
.br
.ti -1c
.RI "void \fBgetBBoxAA\fP (int *xMinA, int *yMinA, int *xMaxA, int *yMaxA)"
.br
.ti -1c
.RI "GBool \fBhasPartialClip\fP ()"
.br
.ti -1c
.RI "void \fBgetSpanBounds\fP (int y, int *spanXMin, int *spanXMax)"
.br
.ti -1c
.RI "GBool \fBtest\fP (int x, int y)"
.br
.ti -1c
.RI "GBool \fBtestSpan\fP (int x0, int x1, int y)"
.br
.ti -1c
.RI "GBool \fBgetNextSpan\fP (int y, int *x0, int *x1)"
.br
.ti -1c
.RI "void \fBrenderAALine\fP (\fBSplashBitmap\fP *aaBuf, int *x0, int *x1, int y, GBool adjustVertLine=gFalse)"
.br
.ti -1c
.RI "void \fBclipAALine\fP (\fBSplashBitmap\fP *aaBuf, int *x0, int *x1, int y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file SplashXPathScanner\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
