.TH "SplashPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSplashFunctionPattern\fP, \fBSplashGouraudColor\fP, \fBSplashSolidColor\fP, and \fBSplashUnivariatePattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBSplashPattern\fP * \fBcopy\fP ()=0"
.br
.ti -1c
.RI "virtual GBool \fBgetColor\fP (int x, int y, SplashColorPtr c)=0"
.br
.ti -1c
.RI "virtual GBool \fBtestPosition\fP (int x, int y)=0"
.br
.ti -1c
.RI "virtual GBool \fBisStatic\fP ()=0"
.br
.ti -1c
.RI "virtual GBool \fBisCMYK\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file SplashPattern\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
