.TH "SplashXPath" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashXPath
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashXPath\fP (\fBSplashPath\fP *path, SplashCoord *matrix, SplashCoord flatness, GBool closeSubpaths, GBool adjustLines=gFalse, int linePosI=0)"
.br
.ti -1c
.RI "\fBSplashXPath\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "void \fBaaScale\fP ()"
.br
.ti -1c
.RI "void \fBsort\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashXPath\fP (\fBSplashXPath\fP *xPath)"
.br
.ti -1c
.RI "void \fBtransform\fP (SplashCoord *matrix, SplashCoord xi, SplashCoord yi, SplashCoord *xo, SplashCoord *yo)"
.br
.ti -1c
.RI "void \fBstrokeAdjust\fP (\fBSplashXPathAdjust\fP *adjust, SplashCoord *xp, SplashCoord *yp)"
.br
.ti -1c
.RI "void \fBgrow\fP (int nSegs)"
.br
.ti -1c
.RI "void \fBaddCurve\fP (SplashCoord x0, SplashCoord y0, SplashCoord x1, SplashCoord y1, SplashCoord x2, SplashCoord y2, SplashCoord x3, SplashCoord y3, SplashCoord flatness, GBool first, GBool last, GBool end0, GBool end1)"
.br
.ti -1c
.RI "void \fBaddSegment\fP (SplashCoord x0, SplashCoord y0, SplashCoord x1, SplashCoord y1)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSplashXPathSeg\fP * \fBsegs\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSplashXPathScanner\fP"
.br
.ti -1c
.RI "class \fBSplashClip\fP"
.br
.ti -1c
.RI "class \fBSplash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file SplashXPath\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
