.TH "SplashSolidColor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashSolidColor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSplashPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashSolidColor\fP (SplashColorPtr colorA)"
.br
.ti -1c
.RI "virtual \fBSplashPattern\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBgetColor\fP (int x, int y, SplashColorPtr c)"
.br
.ti -1c
.RI "virtual GBool \fBtestPosition\fP (int x, int y)"
.br
.ti -1c
.RI "virtual GBool \fBisStatic\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBisCMYK\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file SplashPattern\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
