.TH "SplashScreenParams" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashScreenParams
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SplashScreenType \fBtype\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBdotRadius\fP"
.br
.ti -1c
.RI "SplashCoord \fBgamma\fP"
.br
.ti -1c
.RI "SplashCoord \fBblackThreshold\fP"
.br
.ti -1c
.RI "SplashCoord \fBwhiteThreshold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file SplashTypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
