.TH "SplashFontSrc" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashFontSrc
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetFile\fP (\fBGooString\fP *file, GBool del)"
.br
.ti -1c
.RI "void \fBsetFile\fP (const char *file, GBool del)"
.br
.ti -1c
.RI "void \fBsetBuf\fP (char *bufA, int buflenA, GBool del)"
.br
.ti -1c
.RI "void \fBref\fP ()"
.br
.ti -1c
.RI "void \fBunref\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GBool \fBisFile\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBfileName\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBbufLen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file SplashFontFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
