.TH "SplashFontFileID" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashFontFileID
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSplashOutFontFileID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual GBool \fBmatches\fP (\fBSplashFontFileID\fP *id)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file SplashFontFileID\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
