.TH "SplashGouraudPattern" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashGouraudPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSplashGouraudColor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashGouraudPattern\fP (GBool bDirectColorTranslation, \fBGfxState\fP *state, \fBGfxGouraudTriangleShading\fP *shading, SplashColorMode mode)"
.br
.ti -1c
.RI "virtual \fBSplashPattern\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBgetColor\fP (int x, int y, SplashColorPtr c)"
.br
.ti -1c
.RI "virtual GBool \fBtestPosition\fP (int x, int y)"
.br
.ti -1c
.RI "virtual GBool \fBisStatic\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBisCMYK\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBisParameterized\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetNTriangles\fP ()"
.br
.ti -1c
.RI "virtual void \fBgetTriangle\fP (int i, double *x0, double *y0, double *color0, double *x1, double *y1, double *color1, double *x2, double *y2, double *color2)"
.br
.ti -1c
.RI "virtual void \fBgetParameterizedColor\fP (double t, SplashColorMode mode, SplashColorPtr c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file SplashOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
