.TH "SplitterEngine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplitterEngine \- QSplitter animation engine\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <splitterengine\&.h>\fP
.PP
Inherits \fBBaseEngine\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBunregisterWidget\fP (QObject *\fBdata\fP)"
.br
.RI "remove widget from map "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplitterEngine\fP (QObject *parent)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~SplitterEngine\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual void \fBsetEnabled\fP (bool value)"
.br
.RI "enability "
.ti -1c
.RI "virtual void \fBsetDuration\fP (int value)"
.br
.RI "duration "
.ti -1c
.RI "virtual bool \fBregisterWidget\fP (QWidget *)"
.br
.RI "register widget "
.ti -1c
.RI "virtual bool \fBupdateState\fP (const QPaintDevice *, bool)"
.br
.RI "true if widget hover state is changed "
.ti -1c
.RI "virtual bool \fBisAnimated\fP (const QPaintDevice *)"
.br
.RI "true if widget is animated "
.ti -1c
.RI "virtual qreal \fBopacity\fP (const QPaintDevice *object)"
.br
.RI "animation opacity "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPaintDeviceDataMap\fP< \fBWidgetStateData\fP >::Value \fBdata\fP (const QPaintDevice *object)"
.br
.RI "returns data associated to widget "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
QSplitter animation engine\&. 
.PP
Definition at line 35 of file splitterengine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
