.TH "srp_ctx_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srp_ctx_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBSRP_cb_arg\fP"
.br
.ti -1c
.RI "int(* \fBTLS_ext_srp_username_callback\fP )(\fBSSL\fP *, int *, void *)"
.br
.ti -1c
.RI "int(* \fBSRP_verify_param_callback\fP )(\fBSSL\fP *, void *)"
.br
.ti -1c
.RI "char *(* \fBSRP_give_srp_client_pwd_callback\fP )(\fBSSL\fP *, void *)"
.br
.ti -1c
.RI "char * \fBlogin\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBN\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBg\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBs\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBB\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBA\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBa\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBb\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBv\fP"
.br
.ti -1c
.RI "char * \fBinfo\fP"
.br
.ti -1c
.RI "int \fBstrength\fP"
.br
.ti -1c
.RI "unsigned long \fBsrp_Mask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 709 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
