.TH "ssl2_state_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl2_state_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBthree_byte_header\fP"
.br
.ti -1c
.RI "int \fBclear_text\fP"
.br
.ti -1c
.RI "int \fBescape\fP"
.br
.ti -1c
.RI "int \fBssl2_rollback\fP"
.br
.ti -1c
.RI "unsigned int \fBwnum\fP"
.br
.ti -1c
.RI "int \fBwpend_tot\fP"
.br
.ti -1c
.RI "const unsigned char * \fBwpend_buf\fP"
.br
.ti -1c
.RI "int \fBwpend_off\fP"
.br
.ti -1c
.RI "int \fBwpend_len\fP"
.br
.ti -1c
.RI "int \fBwpend_ret\fP"
.br
.ti -1c
.RI "int \fBrbuf_left\fP"
.br
.ti -1c
.RI "int \fBrbuf_offs\fP"
.br
.ti -1c
.RI "unsigned char * \fBrbuf\fP"
.br
.ti -1c
.RI "unsigned char * \fBwbuf\fP"
.br
.ti -1c
.RI "unsigned char * \fBwrite_ptr\fP"
.br
.ti -1c
.RI "unsigned int \fBpadding\fP"
.br
.ti -1c
.RI "unsigned int \fBrlength\fP"
.br
.ti -1c
.RI "int \fBract_data_length\fP"
.br
.ti -1c
.RI "unsigned int \fBwlength\fP"
.br
.ti -1c
.RI "int \fBwact_data_length\fP"
.br
.ti -1c
.RI "unsigned char * \fBract_data\fP"
.br
.ti -1c
.RI "unsigned char * \fBwact_data\fP"
.br
.ti -1c
.RI "unsigned char * \fBmac_data\fP"
.br
.ti -1c
.RI "unsigned char * \fBread_key\fP"
.br
.ti -1c
.RI "unsigned char * \fBwrite_key\fP"
.br
.ti -1c
.RI "unsigned int \fBchallenge_length\fP"
.br
.ti -1c
.RI "unsigned char \fBchallenge\fP [SSL2_MAX_CHALLENGE_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBconn_id_length\fP"
.br
.ti -1c
.RI "unsigned char \fBconn_id\fP [SSL2_MAX_CONNECTION_ID_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBkey_material_length\fP"
.br
.ti -1c
.RI "unsigned char \fBkey_material\fP [SSL2_MAX_KEY_MATERIAL_LENGTH *2]"
.br
.ti -1c
.RI "unsigned long \fBread_sequence\fP"
.br
.ti -1c
.RI "unsigned long \fBwrite_sequence\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBconn_id_length\fP"
.br
.ti -1c
.RI "   unsigned int \fBcert_type\fP"
.br
.ti -1c
.RI "   unsigned int \fBcert_length\fP"
.br
.ti -1c
.RI "   unsigned int \fBcsl\fP"
.br
.ti -1c
.RI "   unsigned int \fBclear\fP"
.br
.ti -1c
.RI "   unsigned int \fBenc\fP"
.br
.ti -1c
.RI "   unsigned char \fBccl\fP [SSL2_MAX_CERT_CHALLENGE_LENGTH]"
.br
.ti -1c
.RI "   unsigned int \fBcipher_spec_length\fP"
.br
.ti -1c
.RI "   unsigned int \fBsession_id_length\fP"
.br
.ti -1c
.RI "   unsigned int \fBclen\fP"
.br
.ti -1c
.RI "   unsigned int \fBrlen\fP"
.br
.ti -1c
.RI "} \fBtmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file ssl2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
