.TH "ssl3_record_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl3_record_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBlength\fP"
.br
.ti -1c
.RI "unsigned int \fBoff\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "unsigned char * \fBinput\fP"
.br
.ti -1c
.RI "unsigned char * \fBcomp\fP"
.br
.ti -1c
.RI "unsigned long \fBepoch\fP"
.br
.ti -1c
.RI "unsigned char \fBseq_num\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 353 of file ssl3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
