.TH "ssl_session_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_session_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSSL_CIPHER\fP) *ciphers"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBssl_version\fP"
.br
.ti -1c
.RI "unsigned int \fBkey_arg_length\fP"
.br
.ti -1c
.RI "unsigned char \fBkey_arg\fP [SSL_MAX_KEY_ARG_LENGTH]"
.br
.ti -1c
.RI "int \fBmaster_key_length\fP"
.br
.ti -1c
.RI "unsigned char \fBmaster_key\fP [SSL_MAX_MASTER_KEY_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBsession_id_length\fP"
.br
.ti -1c
.RI "unsigned char \fBsession_id\fP [SSL_MAX_SSL_SESSION_ID_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBsid_ctx_length\fP"
.br
.ti -1c
.RI "unsigned char \fBsid_ctx\fP [SSL_MAX_SID_CTX_LENGTH]"
.br
.ti -1c
.RI "unsigned int \fBkrb5_client_princ_len\fP"
.br
.ti -1c
.RI "unsigned char \fBkrb5_client_princ\fP [SSL_MAX_KRB5_PRINCIPAL_LENGTH]"
.br
.ti -1c
.RI "char * \fBpsk_identity_hint\fP"
.br
.ti -1c
.RI "char * \fBpsk_identity\fP"
.br
.ti -1c
.RI "int \fBnot_resumable\fP"
.br
.ti -1c
.RI "struct sess_cert_st * \fBsess_cert\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBpeer\fP"
.br
.ti -1c
.RI "long \fBverify_result\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "long \fBtimeout\fP"
.br
.ti -1c
.RI "long \fBtime\fP"
.br
.ti -1c
.RI "unsigned int \fBcompress_meth\fP"
.br
.ti -1c
.RI "const \fBSSL_CIPHER\fP * \fBcipher\fP"
.br
.ti -1c
.RI "unsigned long \fBcipher_id\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.ti -1c
.RI "struct \fBssl_session_st\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBssl_session_st\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBtlsext_hostname\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ecpointformatlist_length\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_ecpointformatlist\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ellipticcurvelist_length\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_ellipticcurvelist\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_tick\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ticklen\fP"
.br
.ti -1c
.RI "long \fBtlsext_tick_lifetime_hint\fP"
.br
.ti -1c
.RI "char * \fBsrp_username\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 470 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
