.TH "ssl_cipher_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_cipher_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "unsigned long \fBid\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm_mkey\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm_auth\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm_enc\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm_mac\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm_ssl\fP"
.br
.ti -1c
.RI "unsigned long \fBalgo_strength\fP"
.br
.ti -1c
.RI "unsigned long \fBalgorithm2\fP"
.br
.ti -1c
.RI "int \fBstrength_bits\fP"
.br
.ti -1c
.RI "int \fBalg_bits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 389 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
