.TH "StackedWidgetData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StackedWidgetData \- generic data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stackedwidgetdata\&.h>\fP
.PP
Inherits \fBTransitionData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStackedWidgetData\fP (QObject *, QStackedWidget *, int)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~StackedWidgetData\fP (void)"
.br
.RI "destructor "
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual bool \fBinitializeAnimation\fP (void)"
.br
.RI "initialize animation "
.ti -1c
.RI "virtual bool \fBanimate\fP (void)"
.br
.RI "animate "
.ti -1c
.RI "virtual void \fBfinishAnimation\fP (void)"
.br
.RI "finish animation "
.ti -1c
.RI "virtual void \fBtargetDestroyed\fP (void)"
.br
.RI "called when target is destroyed "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
generic data 
.PP
Definition at line 34 of file stackedwidgetdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
