.TH "StandardAuthData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StandardAuthData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardAuthData\fP (\fBGooString\fP *ownerPasswordA, \fBGooString\fP *userPasswordA)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBownerPassword\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBuserPassword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file SecurityHandler\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
