.TH "StandardSecurityHandler" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StandardSecurityHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSecurityHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardSecurityHandler\fP (\fBPDFDoc\fP *docA, \fBObject\fP *encryptDictA)"
.br
.ti -1c
.RI "virtual GBool \fBisUnencrypted\fP ()"
.br
.ti -1c
.RI "virtual void * \fBmakeAuthData\fP (\fBGooString\fP *ownerPassword, \fBGooString\fP *userPassword)"
.br
.ti -1c
.RI "virtual void * \fBgetAuthData\fP ()"
.br
.ti -1c
.RI "virtual void \fBfreeAuthData\fP (void *authData)"
.br
.ti -1c
.RI "virtual GBool \fBauthorize\fP (void *authData)"
.br
.ti -1c
.RI "virtual int \fBgetPermissionFlags\fP ()"
.br
.ti -1c
.RI "virtual GBool \fBgetOwnerPasswordOk\fP ()"
.br
.ti -1c
.RI "virtual Guchar * \fBgetFileKey\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetFileKeyLength\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetEncVersion\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetEncRevision\fP ()"
.br
.ti -1c
.RI "virtual CryptAlgorithm \fBgetEncAlgorithm\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 106 of file SecurityHandler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
