.TH "StateEffects" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateEffects
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateEffects\fP (QPalette::ColorGroup state)"
.br
.ti -1c
.RI "QBrush \fBbrush\fP (const QBrush &background) const"
.br
.ti -1c
.RI "QBrush \fBbrush\fP (const QBrush &foreground, const QBrush &background) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file colorscheme\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
