.TH "StitchingFunction" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StitchingFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStitchingFunction\fP (\fBObject\fP *funcObj, \fBDict\fP *dict, std::set< int > *usedParents)"
.br
.ti -1c
.RI "virtual \fBFunction\fP * \fBcopy\fP ()"
.br
.ti -1c
.RI "virtual int \fBgetType\fP ()"
.br
.ti -1c
.RI "virtual void \fBtransform\fP (double *in, double *out)"
.br
.ti -1c
.RI "virtual GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBgetNumFuncs\fP ()"
.br
.ti -1c
.RI "\fBFunction\fP * \fBgetFunc\fP (int i)"
.br
.ti -1c
.RI "double * \fBgetBounds\fP ()"
.br
.ti -1c
.RI "double * \fBgetEncode\fP ()"
.br
.ti -1c
.RI "double * \fBgetScale\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 198 of file Function\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
