.TH "str_src_mgr" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
str_src_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct jpeg_source_mgr \fBpub\fP"
.br
.ti -1c
.RI "JOCTET \fBbuffer\fP"
.br
.ti -1c
.RI "\fBStream\fP * \fBstr\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file DCTStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
