.TH "StreamPredictor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamPredictor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamPredictor\fP (\fBStream\fP *strA, int predictorA, int widthA, int nCompsA, int nBitsA)"
.br
.ti -1c
.RI "GBool \fBisOk\fP ()"
.br
.ti -1c
.RI "int \fBlookChar\fP ()"
.br
.ti -1c
.RI "int \fBgetChar\fP ()"
.br
.ti -1c
.RI "int \fBgetChars\fP (int nChars, Guchar *buffer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 406 of file Stream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
