.TH "SvgGeneratorPrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgGeneratorPrivate
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSvgPaintEngine\fP * \fBengine\fP"
.br
.ti -1c
.RI "uint \fBowns_iodevice\fP: 1"
.br
.ti -1c
.RI "QString \fBfileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 677 of file svggenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
