.TH "SvgPaintEnginePrivate" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgPaintEnginePrivate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQPaintEnginePrivate\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_attributes\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QSize \fBsize\fP"
.br
.ti -1c
.RI "QRectF \fBviewBox\fP"
.br
.ti -1c
.RI "QIODevice * \fBoutputDevice\fP"
.br
.ti -1c
.RI "QTextStream * \fBstream\fP"
.br
.ti -1c
.RI "int \fBresolution\fP"
.br
.ti -1c
.RI "QString \fBheader\fP"
.br
.ti -1c
.RI "QString \fBbody\fP"
.br
.ti -1c
.RI "QBrush \fBbrush\fP"
.br
.ti -1c
.RI "QPen \fBpen\fP"
.br
.ti -1c
.RI "QMatrix \fBmatrix\fP"
.br
.ti -1c
.RI "struct \fBSvgPaintEnginePrivate::_attributes\fP \fBattributes\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 156 of file svggenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
