.TH "SvgPaintEngine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgPaintEngine
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPaintEngine\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBbegin\fP (QPaintDevice *device)"
.br
.ti -1c
.RI "bool \fBend\fP ()"
.br
.ti -1c
.RI "void \fBupdateState\fP (const QPaintEngineState &state)"
.br
.ti -1c
.RI "void \fBpopGroup\fP ()"
.br
.ti -1c
.RI "void \fBdrawPath\fP (const QPainterPath &path)"
.br
.ti -1c
.RI "void \fBdrawPixmap\fP (const QRectF &r, const QPixmap &pm, const QRectF &sr)"
.br
.ti -1c
.RI "void \fBdrawPolygon\fP (const QPointF *points, int pointCount, PolygonDrawMode mode)"
.br
.ti -1c
.RI "void \fBdrawImage\fP (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlag=Qt::AutoColor)"
.br
.ti -1c
.RI "QPaintEngine::Type \fBtype\fP () const"
.br
.ti -1c
.RI "QSize \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBsetSize\fP (const QSize &size)"
.br
.ti -1c
.RI "QRectF \fBviewBox\fP () const"
.br
.ti -1c
.RI "void \fBsetViewBox\fP (const QRectF &viewBox)"
.br
.ti -1c
.RI "QString \fBdocumentTitle\fP () const"
.br
.ti -1c
.RI "void \fBsetDocumentTitle\fP (const QString &title)"
.br
.ti -1c
.RI "QString \fBdocumentDescription\fP () const"
.br
.ti -1c
.RI "void \fBsetDocumentDescription\fP (const QString &description)"
.br
.ti -1c
.RI "QIODevice * \fBoutputDevice\fP () const"
.br
.ti -1c
.RI "void \fBsetOutputDevice\fP (QIODevice *device)"
.br
.ti -1c
.RI "int \fBresolution\fP ()"
.br
.ti -1c
.RI "void \fBsetResolution\fP (int resolution)"
.br
.ti -1c
.RI "QTextStream & \fBstream\fP ()"
.br
.ti -1c
.RI "const QString \fBqpenToSvg\fP (const QPen &spen)"
.br
.ti -1c
.RI "const QString \fBqbrushToSvg\fP (const QBrush &sbrush)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBMs::Element\fP * \fB_element\fP = NULL"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSvgGenerator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 226 of file svggenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
