.TH "bww2mxml/symbols.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/symbols.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSymbol\fP { \fBCOMMENT\fP, \fBHEADER\fP, \fBSTRING\fP, \fBCLEF\fP, \fBKEY\fP, \fBTEMPO\fP, \fBTSIG\fP, \fBPART\fP, \fBBAR\fP, \fBNOTE\fP, \fBTIE\fP, \fBTRIPLET\fP, \fBDOT\fP, \fBGRACE\fP, \fBUNKNOWN\fP, \fBNONE\fP }"
.br
.ti -1c
.RI "enum \fBStartStop\fP { \fBST_NONE\fP, \fBST_START\fP, \fBST_CONTINUE\fP, \fBST_STOP\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBBww::symbolToString\fP (Symbol s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of tokens types for bww lexer and parser 
.PP
Definition in file \fBsymbols\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
