.TH "SyntiParameter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyntiParameter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyntiParameter\fP (const \fBSyntiParameter\fP &)"
.br
.ti -1c
.RI "\fBSyntiParameter\fP & \fBoperator=\fP (const \fBSyntiParameter\fP &)"
.br
.ti -1c
.RI "\fBSyntiParameter\fP (const QString &name, float val)"
.br
.ti -1c
.RI "\fBSyntiParameter\fP (int id, const QString &name, float)"
.br
.ti -1c
.RI "\fBSyntiParameter\fP (int id, const QString &name, const QString &val)"
.br
.ti -1c
.RI "\fBSyntiParameter\fP (const QString &name, const QString &val)"
.br
.ti -1c
.RI "SyntiParameterType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBwrite\fP (Ms::Xml &) const"
.br
.ti -1c
.RI "const QString & \fBname\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &s)"
.br
.ti -1c
.RI "int \fBid\fP () const"
.br
.ti -1c
.RI "void \fBsetId\fP (int v)"
.br
.ti -1c
.RI "QString \fBsval\fP () const"
.br
.ti -1c
.RI "float \fBfval\fP () const"
.br
.ti -1c
.RI "void \fBset\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBset\fP (float v)"
.br
.ti -1c
.RI "void \fBset\fP (const QString &s, float, float, float)"
.br
.ti -1c
.RI "float \fBmin\fP () const"
.br
.ti -1c
.RI "float \fBmax\fP () const"
.br
.ti -1c
.RI "void \fBsetRange\fP (float a, float b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSyntiParameter\fP &) const"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file sparm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
