.TH "SyntiParameterData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyntiParameterData
.SH SYNOPSIS
.br
.PP
.PP
Inherits QSharedData\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyntiParameterData\fP (const QString &name, float val)"
.br
.ti -1c
.RI "\fBSyntiParameterData\fP (int id, const QString &name, float)"
.br
.ti -1c
.RI "\fBSyntiParameterData\fP (const QString &name, const QString &val)"
.br
.ti -1c
.RI "\fBSyntiParameterData\fP (int id, const QString &name, const QString &val)"
.br
.ti -1c
.RI "\fBSyntiParameterData\fP (const \fBSyntiParameterData\fP &pd)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (Ms::Xml &) const"
.br
.ti -1c
.RI "virtual bool \fBoperator==\fP (const \fBSyntiParameterData\fP &) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_id\fP"
.br
.ti -1c
.RI "QString \fB_name\fP"
.br
.ti -1c
.RI "SyntiParameterType \fB_type\fP"
.br
.ti -1c
.RI "float \fB_fval\fP"
.br
.ti -1c
.RI "float \fB_min\fP"
.br
.ti -1c
.RI "float \fB_max\fP"
.br
.ti -1c
.RI "QString \fB_sval\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSyntiParameter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file sparm_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
