.TH "SysFontInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysFontInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysFontInfo\fP (\fBGooString\fP *nameA, GBool boldA, GBool italicA, GBool obliqueA, GBool fixedWidthA, \fBGooString\fP *pathA, SysFontType typeA, int fontNumA, \fBGooString\fP *substituteNameA)"
.br
.ti -1c
.RI "GBool \fBmatch\fP (\fBSysFontInfo\fP *fi)"
.br
.ti -1c
.RI "GBool \fBmatch\fP (\fBGooString\fP *nameA, GBool boldA, GBool italicA, GBool obliqueA, GBool fixedWidthA)"
.br
.ti -1c
.RI "GBool \fBmatch\fP (\fBGooString\fP *nameA, GBool boldA, GBool italicA)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGooString\fP * \fBname\fP"
.br
.ti -1c
.RI "GBool \fBbold\fP"
.br
.ti -1c
.RI "GBool \fBitalic\fP"
.br
.ti -1c
.RI "GBool \fBoblique\fP"
.br
.ti -1c
.RI "GBool \fBfixedWidth\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBpath\fP"
.br
.ti -1c
.RI "SysFontType \fBtype\fP"
.br
.ti -1c
.RI "int \fBfontNum\fP"
.br
.ti -1c
.RI "\fBGooString\fP * \fBsubstituteName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 207 of file GlobalParams\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
