.TH "libmscore/system.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/system.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'system\&.h'\fP
.br
\fC#include 'measure\&.h'\fP
.br
\fC#include 'segment\&.h'\fP
.br
\fC#include 'score\&.h'\fP
.br
\fC#include 'sig\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'xml\&.h'\fP
.br
\fC#include 'clef\&.h'\fP
.br
\fC#include 'text\&.h'\fP
.br
\fC#include 'navigate\&.h'\fP
.br
\fC#include 'select\&.h'\fP
.br
\fC#include 'staff\&.h'\fP
.br
\fC#include 'part\&.h'\fP
.br
\fC#include 'page\&.h'\fP
.br
\fC#include 'style\&.h'\fP
.br
\fC#include 'bracket\&.h'\fP
.br
\fC#include 'mscore\&.h'\fP
.br
\fC#include 'barline\&.h'\fP
.br
\fC#include 'box\&.h'\fP
.br
\fC#include 'chordrest\&.h'\fP
.br
\fC#include 'iname\&.h'\fP
.br
\fC#include 'spanner\&.h'\fP
.br
\fC#include 'sym\&.h'\fP
.br
\fC#include 'spacer\&.h'\fP
.br
\fC#include 'systemdivider\&.h'\fP
.br
\fC#include 'textframe\&.h'\fP
.br
\fC#include 'stafflines\&.h'\fP
.br
\fC#include 'bracketItem\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of classes SysStaff and System\&. 
.PP
Definition in file \fBsystem\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
