.TH "libmscore/system.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/system.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br
\fC#include 'spatium\&.h'\fP
.br
\fC#include 'symbol\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMs::SysStaff\fP"
.br
.RI "One staff of a \fBSystem\fP\&. "
.ti -1c
.RI "class \fBMs::System\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< System * >::iterator \fBMs::iSystem\fP"
.br
.ti -1c
.RI "typedef QList< System * >::const_iterator \fBMs::ciSystem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of classes SysStaff and System 
.PP
Definition in file \fBsystem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
