.TH "T1_Builder_FuncsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_Builder_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(\fBT1_Builder\fP builder, \fBFT_Face\fP face, \fBFT_Size\fP size, \fBFT_GlyphSlot\fP slot, FT_Bool hinting)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(\fBT1_Builder\fP builder)"
.br
.ti -1c
.RI "T1_Builder_Check_Points_Func \fBcheck_points\fP"
.br
.ti -1c
.RI "T1_Builder_Add_Point_Func \fBadd_point\fP"
.br
.ti -1c
.RI "T1_Builder_Add_Point1_Func \fBadd_point1\fP"
.br
.ti -1c
.RI "T1_Builder_Add_Contour_Func \fBadd_contour\fP"
.br
.ti -1c
.RI "T1_Builder_Start_Point_Func \fBstart_point\fP"
.br
.ti -1c
.RI "T1_Builder_Close_Contour_Func \fBclose_contour\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 482 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
