.TH "T1_DecoderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_DecoderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT1_BuilderRec\fP \fBbuilder\fP"
.br
.ti -1c
.RI "FT_Long \fBstack\fP [T1_MAX_CHARSTRINGS_OPERANDS]"
.br
.ti -1c
.RI "FT_Long * \fBtop\fP"
.br
.ti -1c
.RI "\fBT1_Decoder_ZoneRec\fP \fBzones\fP [T1_MAX_SUBRS_CALLS+1]"
.br
.ti -1c
.RI "\fBT1_Decoder_Zone\fP \fBzone\fP"
.br
.ti -1c
.RI "FT_Service_PsCMaps \fBpsnames\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglyph_names\fP"
.br
.ti -1c
.RI "FT_Int \fBlenIV\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_subrs\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBsubrs\fP"
.br
.ti -1c
.RI "FT_UInt * \fBsubrs_len\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBfont_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfont_offset\fP"
.br
.ti -1c
.RI "FT_Int \fBflex_state\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_flex_vectors\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBflex_vectors\fP [7]"
.br
.ti -1c
.RI "\fBPS_Blend\fP \fBblend\fP"
.br
.ti -1c
.RI "FT_Render_Mode \fBhint_mode\fP"
.br
.ti -1c
.RI "T1_Decoder_Callback \fBparse_callback\fP"
.br
.ti -1c
.RI "\fBT1_Decoder_FuncsRec\fP \fBfuncs\fP"
.br
.ti -1c
.RI "FT_Long * \fBbuildchar\fP"
.br
.ti -1c
.RI "FT_UInt \fBlen_buildchar\fP"
.br
.ti -1c
.RI "FT_Bool \fBseac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 663 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
