.TH "T1_Decoder_FuncsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_Decoder_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Error(* \fBinit\fP )(\fBT1_Decoder\fP decoder, \fBFT_Face\fP face, \fBFT_Size\fP size, \fBFT_GlyphSlot\fP slot, FT_Byte **glyph_names, \fBPS_Blend\fP blend, FT_Bool hinting, FT_Render_Mode hint_mode, T1_Decoder_Callback callback)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(\fBT1_Decoder\fP decoder)"
.br
.ti -1c
.RI "FT_Error(* \fBparse_charstrings\fP )(\fBT1_Decoder\fP decoder, FT_Byte *base, FT_UInt len)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 639 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
