.TH "T1_EncodingRecRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_EncodingRecRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBnum_chars\fP"
.br
.ti -1c
.RI "FT_Int \fBcode_first\fP"
.br
.ti -1c
.RI "FT_Int \fBcode_last\fP"
.br
.ti -1c
.RI "FT_UShort * \fBchar_index\fP"
.br
.ti -1c
.RI "FT_String ** \fBchar_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file t1types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
