.TH "T1_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBT1_FontRec\fP \fBtype1\fP"
.br
.ti -1c
.RI "const void * \fBpsnames\fP"
.br
.ti -1c
.RI "const void * \fBpsaux\fP"
.br
.ti -1c
.RI "const void * \fBafm_data\fP"
.br
.ti -1c
.RI "\fBFT_CharMapRec\fP \fBcharmaprecs\fP [2]"
.br
.ti -1c
.RI "\fBFT_CharMap\fP \fBcharmaps\fP [2]"
.br
.ti -1c
.RI "\fBPS_Blend\fP \fBblend\fP"
.br
.ti -1c
.RI "FT_Int \fBndv_idx\fP"
.br
.ti -1c
.RI "FT_Int \fBcdv_idx\fP"
.br
.ti -1c
.RI "FT_UInt \fBlen_buildchar\fP"
.br
.ti -1c
.RI "FT_Long * \fBbuildchar\fP"
.br
.ti -1c
.RI "const void * \fBpshinter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 198 of file t1types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
