.TH "T1_FieldRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_FieldRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBident\fP"
.br
.ti -1c
.RI "T1_FieldLocation \fBlocation\fP"
.br
.ti -1c
.RI "T1_FieldType \fBtype\fP"
.br
.ti -1c
.RI "T1_Field_ParseFunc \fBreader\fP"
.br
.ti -1c
.RI "FT_UInt \fBoffset\fP"
.br
.ti -1c
.RI "FT_Byte \fBsize\fP"
.br
.ti -1c
.RI "FT_UInt \fBarray_max\fP"
.br
.ti -1c
.RI "FT_UInt \fBcount_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBdict\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 224 of file psaux\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
