.TH "T1_FontRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_FontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PS_FontInfoRec \fBfont_info\fP"
.br
.ti -1c
.RI "\fBPS_FontExtraRec\fP \fBfont_extra\fP"
.br
.ti -1c
.RI "\fBPS_PrivateRec\fP \fBprivate_dict\fP"
.br
.ti -1c
.RI "FT_String * \fBfont_name\fP"
.br
.ti -1c
.RI "T1_EncodingType \fBencoding_type\fP"
.br
.ti -1c
.RI "T1_EncodingRec \fBencoding\fP"
.br
.ti -1c
.RI "FT_Byte * \fBsubrs_block\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcharstrings_block\fP"
.br
.ti -1c
.RI "FT_Byte * \fBglyph_names_block\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_subrs\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBsubrs\fP"
.br
.ti -1c
.RI "FT_UInt * \fBsubrs_len\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_String ** \fBglyph_names\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBcharstrings\fP"
.br
.ti -1c
.RI "FT_UInt * \fBcharstrings_len\fP"
.br
.ti -1c
.RI "FT_Byte \fBpaint_type\fP"
.br
.ti -1c
.RI "FT_Byte \fBfont_type\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBfont_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfont_offset\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBfont_bbox\fP"
.br
.ti -1c
.RI "FT_Long \fBfont_id\fP"
.br
.ti -1c
.RI "FT_Fixed \fBstroke_width\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file t1types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
