.TH "T1_Loader_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_Loader_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T1_ParserRec \fBparser\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_chars\fP"
.br
.ti -1c
.RI "\fBPS_TableRec\fP \fBencoding_table\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_glyphs\fP"
.br
.ti -1c
.RI "\fBPS_TableRec\fP \fBglyph_names\fP"
.br
.ti -1c
.RI "\fBPS_TableRec\fP \fBcharstrings\fP"
.br
.ti -1c
.RI "\fBPS_TableRec\fP \fBswap_table\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_subrs\fP"
.br
.ti -1c
.RI "\fBPS_TableRec\fP \fBsubrs\fP"
.br
.ti -1c
.RI "FT_Bool \fBfontdata\fP"
.br
.ti -1c
.RI "FT_UInt \fBkeywords_encountered\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file t1load\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
