.TH "T2_Hints_FuncsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T2_Hints_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T2_Hints \fBhints\fP"
.br
.ti -1c
.RI "T2_Hints_OpenFunc \fBopen\fP"
.br
.ti -1c
.RI "T2_Hints_CloseFunc \fBclose\fP"
.br
.ti -1c
.RI "T2_Hints_StemsFunc \fBstems\fP"
.br
.ti -1c
.RI "T2_Hints_MaskFunc \fBhintmask\fP"
.br
.ti -1c
.RI "T2_Hints_CounterFunc \fBcounter\fP"
.br
.ti -1c
.RI "T2_Hints_ApplyFunc \fBapply\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 656 of file pshints\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
