.TH "T3FontCache" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T3FontCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBT3FontCache\fP (\fBRef\fP *fontID, double m11A, double m12A, double m21A, double m22A, int glyphXA, int glyphYA, int glyphWA, int glyphHA, GBool aa, GBool validBBoxA)"
.br
.ti -1c
.RI "GBool \fBmatches\fP (\fBRef\fP *idA, double m11A, double m12A, double m21A, double m22A)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRef\fP \fBfontID\fP"
.br
.ti -1c
.RI "double \fBm11\fP"
.br
.ti -1c
.RI "double \fBm12\fP"
.br
.ti -1c
.RI "double \fBm21\fP"
.br
.ti -1c
.RI "double \fBm22\fP"
.br
.ti -1c
.RI "int \fBglyphX\fP"
.br
.ti -1c
.RI "int \fBglyphY\fP"
.br
.ti -1c
.RI "int \fBglyphW\fP"
.br
.ti -1c
.RI "int \fBglyphH\fP"
.br
.ti -1c
.RI "GBool \fBvalidBBox\fP"
.br
.ti -1c
.RI "int \fBglyphSize\fP"
.br
.ti -1c
.RI "int \fBcacheSets\fP"
.br
.ti -1c
.RI "int \fBcacheAssoc\fP"
.br
.ti -1c
.RI "Guchar * \fBcacheData\fP"
.br
.ti -1c
.RI "\fBT3FontCacheTag\fP * \fBcacheTags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1237 of file SplashOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
