.TH "T42_ParserRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T42_ParserRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPS_ParserRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "FT_Byte * \fBbase_dict\fP"
.br
.ti -1c
.RI "FT_Long \fBbase_len\fP"
.br
.ti -1c
.RI "FT_Bool \fBin_memory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file t42parse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
