.TH "T42_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T42_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBT1_FontRec\fP \fBtype1\fP"
.br
.ti -1c
.RI "const void * \fBpsnames\fP"
.br
.ti -1c
.RI "const void * \fBpsaux\fP"
.br
.ti -1c
.RI "FT_Byte * \fBttf_data\fP"
.br
.ti -1c
.RI "FT_Long \fBttf_size\fP"
.br
.ti -1c
.RI "\fBFT_Face\fP \fBttf_face\fP"
.br
.ti -1c
.RI "\fBFT_CharMapRec\fP \fBcharmaprecs\fP [2]"
.br
.ti -1c
.RI "\fBFT_CharMap\fP \fBcharmaps\fP [2]"
.br
.ti -1c
.RI "\fBPS_UnicodesRec\fP \fBunicode_map\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file t42types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
