.TH "table_cell_def" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table_cell_def
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBvalign\fP { \fBvalign_top\fP, \fBvalign_bottom\fP, \fBvalign_center\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBright_equals\fP (int x)"
.br
.ti -1c
.RI "bool \fBleft_equals\fP (int x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBBorderTop\fP"
.br
.ti -1c
.RI "bool \fBBorderBottom\fP"
.br
.ti -1c
.RI "bool \fBBorderLeft\fP"
.br
.ti -1c
.RI "bool \fBBorderRight\fP"
.br
.ti -1c
.RI "bool * \fBActiveBorder\fP"
.br
.ti -1c
.RI "int \fBRight\fP"
.br
.ti -1c
.RI "int \fBLeft\fP"
.br
.ti -1c
.RI "bool \fBMerged\fP"
.br
.ti -1c
.RI "bool \fBFirstMerged\fP"
.br
.ti -1c
.RI "valign \fBVAlign\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file rtf_table\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
