.TH "table" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBkilling_ptr_vector< table_row >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBmake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file rtf_table\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
