.TH "TBBox_Rec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBBox_Rec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Vector\fP \fBlast\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBbbox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file ftbbox\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
