.TH "TempoMap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempoMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits map< int, double >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBtempo\fP (int tick) const"
.br
.ti -1c
.RI "int \fBtime2tick\fP (double, double, int) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file tempomap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
