.TH "TestOpcodes" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestOpcodes
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and \fBMs::MTest\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file tst_sfzopcodes\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
