.TH "TestDurationType" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestDurationType
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject, and \fBMs::MTest\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 38 of file tst_durationtype\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
