.TH "TextPool" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextPool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextWord\fP * \fBgetPool\fP (int baseIdx)"
.br
.ti -1c
.RI "void \fBsetPool\fP (int baseIdx, \fBTextWord\fP *p)"
.br
.ti -1c
.RI "int \fBgetBaseIdx\fP (double base)"
.br
.ti -1c
.RI "void \fBaddWord\fP (\fBTextWord\fP *word)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextBlock\fP"
.br
.ti -1c
.RI "class \fBTextPage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 241 of file TextOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
