.TH "TextUnderline" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextUnderline
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextUnderline\fP (double x0A, double y0A, double x1A, double y1A)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx0\fP"
.br
.ti -1c
.RI "double \fBy0\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBy1\fP"
.br
.ti -1c
.RI "GBool \fBhoriz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 275 of file TextOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
