.TH "TextSelectionDumper" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextSelectionDumper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTextSelectionVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextSelectionDumper\fP (\fBTextPage\fP *page)"
.br
.ti -1c
.RI "virtual void \fBvisitBlock\fP (\fBTextBlock\fP *block, \fBTextLine\fP *begin, \fBTextLine\fP *end, \fBPDFRectangle\fP *selection)"
.br
.ti -1c
.RI "virtual void \fBvisitLine\fP (\fBTextLine\fP *line, \fBTextWord\fP *begin, \fBTextWord\fP *end, int edge_begin, int edge_end, \fBPDFRectangle\fP *selection)"
.br
.ti -1c
.RI "virtual void \fBvisitWord\fP (\fBTextWord\fP *word, int begin, int end, \fBPDFRectangle\fP *selection)"
.br
.ti -1c
.RI "void \fBendPage\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetText\fP (void)"
.br
.ti -1c
.RI "\fBGooList\fP ** \fBtakeWordList\fP (int *nLines)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 4323 of file TextOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
