.TH "TextWordSelection" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextWordSelection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextWordSelection\fP (\fBTextWord\fP *word, int begin, int end)"
.br
.ti -1c
.RI "\fBTextWord\fP * \fBgetWord\fP () const"
.br
.ti -1c
.RI "int \fBgetBegin\fP () const"
.br
.ti -1c
.RI "int \fBgetEnd\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextSelectionPainter\fP"
.br
.ti -1c
.RI "class \fBTextSelectionDumper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 504 of file TextOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
