.TH "TextFontInfo" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextFontInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextFontInfo\fP (\fBGfxState\fP *state)"
.br
.ti -1c
.RI "GBool \fBmatches\fP (\fBGfxState\fP *state)"
.br
.ti -1c
.RI "GBool \fBmatches\fP (\fBTextFontInfo\fP *fontInfo)"
.br
.ti -1c
.RI "double \fBgetAscent\fP ()"
.br
.ti -1c
.RI "double \fBgetDescent\fP ()"
.br
.ti -1c
.RI "int \fBgetWMode\fP ()"
.br
.ti -1c
.RI "\fBGooString\fP * \fBgetFontName\fP ()"
.br
.ti -1c
.RI "GBool \fBisFixedWidth\fP ()"
.br
.ti -1c
.RI "GBool \fBisSerif\fP ()"
.br
.ti -1c
.RI "GBool \fBisSymbolic\fP ()"
.br
.ti -1c
.RI "GBool \fBisItalic\fP ()"
.br
.ti -1c
.RI "GBool \fBisBold\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextWord\fP"
.br
.ti -1c
.RI "class \fBTextPage\fP"
.br
.ti -1c
.RI "class \fBTextSelectionPainter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file TextOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
