.TH "TextLineFrag" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextLineFrag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBTextLine\fP *lineA, int startA, int lenA)"
.br
.ti -1c
.RI "void \fBcomputeCoords\fP (GBool oneRot)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBcmpYXPrimaryRot\fP (const void *p1, const void *p2)"
.br
.ti -1c
.RI "static int \fBcmpYXLineRot\fP (const void *p1, const void *p2)"
.br
.ti -1c
.RI "static int \fBcmpXYLineRot\fP (const void *p1, const void *p2)"
.br
.ti -1c
.RI "static int \fBcmpXYColumnPrimaryRot\fP (const void *p1, const void *p2)"
.br
.ti -1c
.RI "static int \fBcmpXYColumnLineRot\fP (const void *p1, const void *p2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTextLine\fP * \fBline\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "double \fBxMin\fP"
.br
.ti -1c
.RI "double \fBxMax\fP"
.br
.ti -1c
.RI "double \fByMin\fP"
.br
.ti -1c
.RI "double \fByMax\fP"
.br
.ti -1c
.RI "double \fBbase\fP"
.br
.ti -1c
.RI "int \fBcol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1191 of file TextOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
