.TH "TextLink" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextLink
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextLink\fP (int xMinA, int yMinA, int xMaxA, int yMaxA, \fBAnnotLink\fP *linkA)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBxMin\fP"
.br
.ti -1c
.RI "int \fByMin\fP"
.br
.ti -1c
.RI "int \fBxMax\fP"
.br
.ti -1c
.RI "int \fByMax\fP"
.br
.ti -1c
.RI "\fBAnnotLink\fP * \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 290 of file TextOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
