.TH "TextLine" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextLine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextLine\fP (\fBTextBlock\fP *blkA, int rotA, double baseA)"
.br
.ti -1c
.RI "void \fBaddWord\fP (\fBTextWord\fP *word)"
.br
.ti -1c
.RI "double \fBprimaryDelta\fP (\fBTextLine\fP *line)"
.br
.ti -1c
.RI "int \fBprimaryCmp\fP (\fBTextLine\fP *line)"
.br
.ti -1c
.RI "int \fBsecondaryCmp\fP (\fBTextLine\fP *line)"
.br
.ti -1c
.RI "int \fBcmpYX\fP (\fBTextLine\fP *line)"
.br
.ti -1c
.RI "void \fBcoalesce\fP (\fBUnicodeMap\fP *uMap)"
.br
.ti -1c
.RI "void \fBvisitSelection\fP (\fBTextSelectionVisitor\fP *visitor, \fBPDFRectangle\fP *selection, SelectionStyle style)"
.br
.ti -1c
.RI "\fBTextWord\fP * \fBgetWords\fP ()"
.br
.ti -1c
.RI "\fBTextLine\fP * \fBgetNext\fP ()"
.br
.ti -1c
.RI "GBool \fBisHyphenated\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBcmpXY\fP (const void *p1, const void *p2)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextLineFrag\fP"
.br
.ti -1c
.RI "class \fBTextBlock\fP"
.br
.ti -1c
.RI "class \fBTextFlow\fP"
.br
.ti -1c
.RI "class \fBTextWordList\fP"
.br
.ti -1c
.RI "class \fBTextPage\fP"
.br
.ti -1c
.RI "class \fBTextSelectionPainter\fP"
.br
.ti -1c
.RI "class \fBTextSelectionSizer\fP"
.br
.ti -1c
.RI "class \fBTextSelectionDumper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 273 of file TextOutputDev\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
