.TH "TilingSplashOutBitmap" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TilingSplashOutBitmap
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSplashBitmap\fP * \fBbitmap\fP"
.br
.ti -1c
.RI "\fBSplashPattern\fP * \fBpattern\fP"
.br
.ti -1c
.RI "SplashColorMode \fBcolorMode\fP"
.br
.ti -1c
.RI "int \fBpaintType\fP"
.br
.ti -1c
.RI "int \fBrepeatX\fP"
.br
.ti -1c
.RI "int \fBrepeatY\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3411 of file SplashOutputDev\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
