.TH "tohtml.HtmlFormatter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tohtml.HtmlFormatter \- HTML FORMATTER CLASS\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, processor, project_title, file_prefix)"
.br
.ti -1c
.RI "def \fBmake_section_url\fP (self, section)"
.br
.ti -1c
.RI "def \fBmake_block_url\fP (self, block, name=None)"
.br
.ti -1c
.RI "def \fBmake_html_word\fP (self, word)"
.br
.ti -1c
.RI "def \fBmake_html_para\fP (self, words)"
.br
.ti -1c
.RI "def \fBmake_html_code\fP (self, lines)"
.br
.ti -1c
.RI "def \fBmake_html_items\fP (self, items)"
.br
.ti -1c
.RI "def \fBprint_html_items\fP (self, items)"
.br
.ti -1c
.RI "def \fBprint_html_field\fP (self, field)"
.br
.ti -1c
.RI "def \fBhtml_source_quote\fP (self, line, block_name=None)"
.br
.ti -1c
.RI "def \fBprint_html_field_list\fP (self, fields)"
.br
.ti -1c
.RI "def \fBprint_html_markup\fP (self, markup)"
.br
.ti -1c
.RI "def \fBindex_enter\fP (self)"
.br
.ti -1c
.RI "def \fBindex_name_enter\fP (self, name)"
.br
.ti -1c
.RI "def \fBindex_exit\fP (self)"
.br
.ti -1c
.RI "def \fBindex_dump\fP (self, index_filename=None)"
.br
.ti -1c
.RI "def \fBtoc_enter\fP (self)"
.br
.ti -1c
.RI "def \fBtoc_chapter_enter\fP (self, chapter)"
.br
.ti -1c
.RI "def \fBtoc_section_enter\fP (self, section)"
.br
.ti -1c
.RI "def \fBtoc_section_exit\fP (self, section)"
.br
.ti -1c
.RI "def \fBtoc_chapter_exit\fP (self, chapter)"
.br
.ti -1c
.RI "def \fBtoc_index\fP (self, index_filename)"
.br
.ti -1c
.RI "def \fBtoc_exit\fP (self)"
.br
.ti -1c
.RI "def \fBtoc_dump\fP (self, toc_filename=None, index_filename=None)"
.br
.ti -1c
.RI "def \fBsection_enter\fP (self, section)"
.br
.ti -1c
.RI "def \fBblock_enter\fP (self, block)"
.br
.ti -1c
.RI "def \fBmarkup_enter\fP (self, markup, block)"
.br
.ti -1c
.RI "def \fBmarkup_exit\fP (self, markup, block)"
.br
.ti -1c
.RI "def \fBblock_exit\fP (self, block)"
.br
.ti -1c
.RI "def \fBsection_exit\fP (self, section)"
.br
.ti -1c
.RI "def \fBsection_dump_all\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBproject_title\fP"
.br
.ti -1c
.RI "\fBfile_prefix\fP"
.br
.ti -1c
.RI "\fBhtml_header\fP"
.br
.ti -1c
.RI "\fBhtml_index_header\fP"
.br
.ti -1c
.RI "\fBhtml_toc_header\fP"
.br
.ti -1c
.RI "\fBhtml_footer\fP"
.br
.ti -1c
.RI "\fBcolumns\fP"
.br
.ti -1c
.RI "\fBindex_items\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HTML FORMATTER CLASS\&. 
.PP
Definition at line 259 of file tohtml\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tohtml\&.HtmlFormatter\&.make_html_code ( self,  lines)"

.PP
.nf
Convert a code sequence to HTML.
.fi
.PP
 
.PP
Definition at line 365 of file tohtml\&.py\&.
.SS "def tohtml\&.HtmlFormatter\&.make_html_items ( self,  items)"

.PP
.nf
Convert a field's content into HTML.
.fi
.PP
 
.PP
Definition at line 373 of file tohtml\&.py\&.
.SS "def tohtml\&.HtmlFormatter\&.make_html_para ( self,  words)"

.PP
.nf
Convert words of a paragraph into tagged HTML text.  Also handle
   cross references.
.fi
.PP
 
.PP
Definition at line 346 of file tohtml\&.py\&.
.SS "def tohtml\&.HtmlFormatter\&.make_html_word ( self,  word)"

.PP
.nf
Analyze a simple word to detect cross-references and markup.
.fi
.PP
 
.PP
Definition at line 314 of file tohtml\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
