.TH "TProfile_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TProfile_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_F26Dot6 \fBX\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBlink\fP"
.br
.ti -1c
.RI "PLong \fBoffset\fP"
.br
.ti -1c
.RI "UShort \fBflags\fP"
.br
.ti -1c
.RI "Long \fBheight\fP"
.br
.ti -1c
.RI "Long \fBstart\fP"
.br
.ti -1c
.RI "Int \fBcountL\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 355 of file ftraster\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
