.TH "TracksView" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracksView
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTableView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTracksView\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetModel\fP (QAbstractItemModel *model)"
.br
.ti -1c
.RI "void \fBsetFrozenRowCount\fP (int count)"
.br
.ti -1c
.RI "void \fBsetFrozenColCount\fP (int count)"
.br
.ti -1c
.RI "void \fBsetItemDelegate\fP (\fBSeparatorDelegate\fP *delegate)"
.br
.ti -1c
.RI "void \fBrestoreHHeaderState\fP (const QByteArray &data)"
.br
.ti -1c
.RI "void \fBrestoreVHeaderState\fP (const QByteArray &data)"
.br
.ti -1c
.RI "void \fBsetHHeaderResizeMode\fP (QHeaderView::ResizeMode mode)"
.br
.ti -1c
.RI "void \fBsetVHeaderDefaultSectionSize\fP (int size)"
.br
.ti -1c
.RI "void \fBresetHHeader\fP ()"
.br
.ti -1c
.RI "void \fBresetVHeader\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "bool \fBviewportEvent\fP (QEvent *event)"
.br
.ti -1c
.RI "void \fBwheelEvent\fP (QWheelEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file importmidi_view\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
