.TH "Transitions" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transitions \- stores engines  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transitions\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetupEngines\fP (void)"
.br
.RI "setup engines "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransitions\fP (QObject *)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~Transitions\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "void \fBregisterWidget\fP (QWidget *widget) const"
.br
.RI "register animations corresponding to given widget, depending on its type\&. "
.ti -1c
.RI "void \fBunregisterWidget\fP (QWidget *widget) const"
.br
.ti -1c
.RI "\fBComboBoxEngine\fP & \fBcomboBoxEngine\fP (void) const"
.br
.RI "qlabel engine "
.ti -1c
.RI "\fBLabelEngine\fP & \fBlabelEngine\fP (void) const"
.br
.RI "qlabel engine "
.ti -1c
.RI "\fBLineEditEngine\fP & \fBlineEditEngine\fP (void) const"
.br
.RI "qlineedit engine "
.ti -1c
.RI "\fBStackedWidgetEngine\fP & \fBstackedWidgetEngine\fP (void) const"
.br
.RI "stacked widget engine "
.in -1c
.SH "Detailed Description"
.PP 
stores engines 
.PP
Definition at line 36 of file transitions\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Transitions::unregisterWidget (QWidget * widget) const"
unregister all animations associated to a widget 
.PP
Definition at line 96 of file transitions\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
