.TH "TrueTypeTable" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrueTypeTable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Guint \fBtag\fP"
.br
.ti -1c
.RI "Guint \fBchecksum\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "int \fBorigOffset\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file FoFiTrueType\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
