.TH "TS_resp_ctx" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_resp_ctx
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP) *certs"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBASN1_OBJECT\fP) *policies"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBEVP_MD\fP) *mds"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBsigner_cert\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBsigner_key\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBdefault_policy\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBseconds\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBmillis\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBmicros\fP"
.br
.ti -1c
.RI "unsigned \fBclock_precision_digits\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "TS_serial_cb \fBserial_cb\fP"
.br
.ti -1c
.RI "void * \fBserial_cb_data\fP"
.br
.ti -1c
.RI "TS_time_cb \fBtime_cb\fP"
.br
.ti -1c
.RI "void * \fBtime_cb_data\fP"
.br
.ti -1c
.RI "TS_extension_cb \fBextension_cb\fP"
.br
.ti -1c
.RI "void * \fBextension_cb_data\fP"
.br
.ti -1c
.RI "\fBTS_REQ\fP * \fBrequest\fP"
.br
.ti -1c
.RI "\fBTS_RESP\fP * \fBresponse\fP"
.br
.ti -1c
.RI "\fBTS_TST_INFO\fP * \fBtst_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 500 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
