.TH "TS_req_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_req_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP) *extensions"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBTS_MSG_IMPRINT\fP * \fBmsg_imprint\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBpolicy_id\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBnonce\fP"
.br
.ti -1c
.RI "ASN1_BOOLEAN \fBcert_req\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
