.TH "TT_CMap_ClassRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_CMap_ClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMap_ClassRec\fP \fBclazz\fP"
.br
.ti -1c
.RI "FT_UInt \fBformat\fP"
.br
.ti -1c
.RI "TT_CMap_ValidateFunc \fBvalidate\fP"
.br
.ti -1c
.RI "TT_CMap_Info_GetFunc \fBget_cmap_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file ttcmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
