.TH "TT_ExecContextRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_ExecContextRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBTT_Size\fP \fBsize\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.ti -1c
.RI "FT_Long \fBtop\fP"
.br
.ti -1c
.RI "FT_Long \fBstackSize\fP"
.br
.ti -1c
.RI "FT_Long * \fBstack\fP"
.br
.ti -1c
.RI "FT_Long \fBargs\fP"
.br
.ti -1c
.RI "FT_Long \fBnew_top\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBzp0\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBzp1\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBzp2\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBpts\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBtwilight\fP"
.br
.ti -1c
.RI "\fBFT_Size_Metrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "\fBTT_Size_Metrics\fP \fBtt_metrics\fP"
.br
.ti -1c
.RI "\fBTT_GraphicsState\fP \fBGS\fP"
.br
.ti -1c
.RI "FT_Int \fBcurRange\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcode\fP"
.br
.ti -1c
.RI "FT_Long \fBIP\fP"
.br
.ti -1c
.RI "FT_Long \fBcodeSize\fP"
.br
.ti -1c
.RI "FT_Byte \fBopcode\fP"
.br
.ti -1c
.RI "FT_Int \fBlength\fP"
.br
.ti -1c
.RI "FT_Bool \fBstep_ins\fP"
.br
.ti -1c
.RI "FT_ULong \fBcvtSize\fP"
.br
.ti -1c
.RI "FT_Long * \fBcvt\fP"
.br
.ti -1c
.RI "FT_UInt \fBglyphSize\fP"
.br
.ti -1c
.RI "FT_Byte * \fBglyphIns\fP"
.br
.ti -1c
.RI "FT_UInt \fBnumFDefs\fP"
.br
.ti -1c
.RI "FT_UInt \fBmaxFDefs\fP"
.br
.ti -1c
.RI "\fBTT_DefArray\fP \fBFDefs\fP"
.br
.ti -1c
.RI "FT_UInt \fBnumIDefs\fP"
.br
.ti -1c
.RI "FT_UInt \fBmaxIDefs\fP"
.br
.ti -1c
.RI "\fBTT_DefArray\fP \fBIDefs\fP"
.br
.ti -1c
.RI "FT_UInt \fBmaxFunc\fP"
.br
.ti -1c
.RI "FT_UInt \fBmaxIns\fP"
.br
.ti -1c
.RI "FT_Int \fBcallTop\fP"
.br
.ti -1c
.RI "FT_Int \fBcallSize\fP"
.br
.ti -1c
.RI "\fBTT_CallStack\fP \fBcallStack\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxPoints\fP"
.br
.ti -1c
.RI "FT_Short \fBmaxContours\fP"
.br
.ti -1c
.RI "TT_CodeRangeTable \fBcodeRangeTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBstoreSize\fP"
.br
.ti -1c
.RI "FT_Long * \fBstorage\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBperiod\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBphase\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBthreshold\fP"
.br
.ti -1c
.RI "FT_Bool \fBinstruction_trap\fP"
.br
.ti -1c
.RI "\fBTT_GraphicsState\fP \fBdefault_GS\fP"
.br
.ti -1c
.RI "FT_Bool \fBis_composite\fP"
.br
.ti -1c
.RI "FT_Bool \fBpedantic_hinting\fP"
.br
.ti -1c
.RI "FT_Long \fBF_dot_P\fP"
.br
.ti -1c
.RI "TT_Round_Func \fBfunc_round\fP"
.br
.ti -1c
.RI "TT_Project_Func \fBfunc_project\fP"
.br
.ti -1c
.RI "TT_Project_Func \fBfunc_dualproj\fP"
.br
.ti -1c
.RI "TT_Project_Func \fBfunc_freeProj\fP"
.br
.ti -1c
.RI "TT_Move_Func \fBfunc_move\fP"
.br
.ti -1c
.RI "TT_Move_Func \fBfunc_move_orig\fP"
.br
.ti -1c
.RI "TT_Cur_Ppem_Func \fBfunc_cur_ppem\fP"
.br
.ti -1c
.RI "TT_Get_CVT_Func \fBfunc_read_cvt\fP"
.br
.ti -1c
.RI "TT_Set_CVT_Func \fBfunc_write_cvt\fP"
.br
.ti -1c
.RI "TT_Set_CVT_Func \fBfunc_move_cvt\fP"
.br
.ti -1c
.RI "FT_Bool \fBgrayscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file ttinterp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
