.TH "TT_FaceRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "TTC_HeaderRec \fBttc_header\fP"
.br
.ti -1c
.RI "FT_ULong \fBformat_tag\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_tables\fP"
.br
.ti -1c
.RI "\fBTT_Table\fP \fBdir_tables\fP"
.br
.ti -1c
.RI "TT_Header \fBheader\fP"
.br
.ti -1c
.RI "\fBTT_HoriHeader\fP \fBhorizontal\fP"
.br
.ti -1c
.RI "\fBTT_MaxProfile\fP \fBmax_profile\fP"
.br
.ti -1c
.RI "FT_Bool \fBvertical_info\fP"
.br
.ti -1c
.RI "\fBTT_VertHeader\fP \fBvertical\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_names\fP"
.br
.ti -1c
.RI "\fBTT_NameTableRec\fP \fBname_table\fP"
.br
.ti -1c
.RI "\fBTT_OS2\fP \fBos2\fP"
.br
.ti -1c
.RI "\fBTT_Postscript\fP \fBpostscript\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcmap_table\fP"
.br
.ti -1c
.RI "FT_ULong \fBcmap_size\fP"
.br
.ti -1c
.RI "TT_Loader_GotoTableFunc \fBgoto_table\fP"
.br
.ti -1c
.RI "TT_Loader_StartGlyphFunc \fBaccess_glyph_frame\fP"
.br
.ti -1c
.RI "TT_Loader_EndGlyphFunc \fBforget_glyph_frame\fP"
.br
.ti -1c
.RI "TT_Loader_ReadGlyphFunc \fBread_glyph_header\fP"
.br
.ti -1c
.RI "TT_Loader_ReadGlyphFunc \fBread_simple_glyph\fP"
.br
.ti -1c
.RI "TT_Loader_ReadGlyphFunc \fBread_composite_glyph\fP"
.br
.ti -1c
.RI "void * \fBsfnt\fP"
.br
.ti -1c
.RI "void * \fBpsnames\fP"
.br
.ti -1c
.RI "\fBTT_GaspRec\fP \fBgasp\fP"
.br
.ti -1c
.RI "\fBTT_PCLT\fP \fBpclt\fP"
.br
.ti -1c
.RI "FT_ULong \fBnum_sbit_scales\fP"
.br
.ti -1c
.RI "\fBTT_SBit_Scale\fP \fBsbit_scales\fP"
.br
.ti -1c
.RI "\fBTT_Post_NamesRec\fP \fBpostscript_names\fP"
.br
.ti -1c
.RI "FT_ULong \fBfont_program_size\fP"
.br
.ti -1c
.RI "FT_Byte * \fBfont_program\fP"
.br
.ti -1c
.RI "FT_ULong \fBcvt_program_size\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcvt_program\fP"
.br
.ti -1c
.RI "FT_ULong \fBcvt_size\fP"
.br
.ti -1c
.RI "FT_Short * \fBcvt\fP"
.br
.ti -1c
.RI "TT_Interpreter \fBinterpreter\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBextra\fP"
.br
.ti -1c
.RI "const char * \fBpostscript_name\fP"
.br
.ti -1c
.RI "FT_ULong \fBglyf_len\fP"
.br
.ti -1c
.RI "FT_Byte * \fBhorz_metrics\fP"
.br
.ti -1c
.RI "FT_ULong \fBhorz_metrics_size\fP"
.br
.ti -1c
.RI "FT_Byte * \fBvert_metrics\fP"
.br
.ti -1c
.RI "FT_ULong \fBvert_metrics_size\fP"
.br
.ti -1c
.RI "FT_ULong \fBnum_locations\fP"
.br
.ti -1c
.RI "FT_Byte * \fBglyph_locations\fP"
.br
.ti -1c
.RI "FT_Byte * \fBhdmx_table\fP"
.br
.ti -1c
.RI "FT_ULong \fBhdmx_table_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBhdmx_record_count\fP"
.br
.ti -1c
.RI "FT_ULong \fBhdmx_record_size\fP"
.br
.ti -1c
.RI "FT_Byte * \fBhdmx_record_sizes\fP"
.br
.ti -1c
.RI "FT_Byte * \fBsbit_table\fP"
.br
.ti -1c
.RI "FT_ULong \fBsbit_table_size\fP"
.br
.ti -1c
.RI "TT_SbitTableType \fBsbit_table_type\fP"
.br
.ti -1c
.RI "FT_UInt \fBsbit_num_strikes\fP"
.br
.ti -1c
.RI "FT_Byte * \fBkern_table\fP"
.br
.ti -1c
.RI "FT_ULong \fBkern_table_size\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_kern_tables\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBkern_avail_bits\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBkern_order_bits\fP"
.br
.ti -1c
.RI "FT_ULong \fBhorz_metrics_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBvert_metrics_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1251 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
