.TH "TT_GraphicsState_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_GraphicsState_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBrp0\fP"
.br
.ti -1c
.RI "FT_UShort \fBrp1\fP"
.br
.ti -1c
.RI "FT_UShort \fBrp2\fP"
.br
.ti -1c
.RI "\fBFT_UnitVector\fP \fBdualVector\fP"
.br
.ti -1c
.RI "\fBFT_UnitVector\fP \fBprojVector\fP"
.br
.ti -1c
.RI "\fBFT_UnitVector\fP \fBfreeVector\fP"
.br
.ti -1c
.RI "FT_Long \fBloop\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBminimum_distance\fP"
.br
.ti -1c
.RI "FT_Int \fBround_state\fP"
.br
.ti -1c
.RI "FT_Bool \fBauto_flip\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBcontrol_value_cutin\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBsingle_width_cutin\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBsingle_width_value\fP"
.br
.ti -1c
.RI "FT_UShort \fBdelta_base\fP"
.br
.ti -1c
.RI "FT_UShort \fBdelta_shift\fP"
.br
.ti -1c
.RI "FT_Byte \fBinstruct_control\fP"
.br
.ti -1c
.RI "FT_Bool \fBscan_control\fP"
.br
.ti -1c
.RI "FT_Int \fBscan_type\fP"
.br
.ti -1c
.RI "FT_UShort \fBgep0\fP"
.br
.ti -1c
.RI "FT_UShort \fBgep1\fP"
.br
.ti -1c
.RI "FT_UShort \fBgep2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file ttobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
