.TH "TT_LoaderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_LoaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBTT_Size\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBFT_GlyphSlot\fP \fBglyph\fP"
.br
.ti -1c
.RI "FT_GlyphLoader \fBgloader\fP"
.br
.ti -1c
.RI "FT_ULong \fBload_flags\fP"
.br
.ti -1c
.RI "FT_UInt \fBglyph_index\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "FT_Int \fBbyte_len\fP"
.br
.ti -1c
.RI "FT_Short \fBn_contours\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBbbox\fP"
.br
.ti -1c
.RI "FT_Int \fBleft_bearing\fP"
.br
.ti -1c
.RI "FT_Int \fBadvance\fP"
.br
.ti -1c
.RI "FT_Int \fBlinear\fP"
.br
.ti -1c
.RI "FT_Bool \fBlinear_def\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp1\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp2\fP"
.br
.ti -1c
.RI "FT_ULong \fBglyf_offset\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBTT_GlyphZoneRec\fP \fBzone\fP"
.br
.ti -1c
.RI "\fBTT_ExecContext\fP \fBexec\fP"
.br
.ti -1c
.RI "FT_Byte * \fBinstructions\fP"
.br
.ti -1c
.RI "FT_ULong \fBins_pos\fP"
.br
.ti -1c
.RI "void * \fBother\fP"
.br
.ti -1c
.RI "FT_Int \fBtop_bearing\fP"
.br
.ti -1c
.RI "FT_Int \fBvadvance\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp3\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBpp4\fP"
.br
.ti -1c
.RI "FT_Byte * \fBcursor\fP"
.br
.ti -1c
.RI "FT_Byte * \fBlimit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1473 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
