.TH "TT_MaxProfile_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_MaxProfile_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBversion\fP"
.br
.ti -1c
.RI "FT_UShort \fBnumGlyphs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxPoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxContours\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxCompositePoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxCompositeContours\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxZones\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxTwilightPoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxStorage\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxFunctionDefs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxInstructionDefs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxStackElements\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxSizeOfInstructions\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxComponentElements\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxComponentDepth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 551 of file tttables\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
