.TH "TT_NameEntryRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_NameEntryRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBplatformID\fP"
.br
.ti -1c
.RI "FT_UShort \fBencodingID\fP"
.br
.ti -1c
.RI "FT_UShort \fBlanguageID\fP"
.br
.ti -1c
.RI "FT_UShort \fBnameID\fP"
.br
.ti -1c
.RI "FT_UShort \fBstringLength\fP"
.br
.ti -1c
.RI "FT_ULong \fBstringOffset\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 270 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
