.TH "TT_Post_20Rec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Post_20Rec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_names\fP"
.br
.ti -1c
.RI "FT_UShort * \fBglyph_indices\fP"
.br
.ti -1c
.RI "FT_Char ** \fBglyph_names\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 753 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
