.TH "TT_SBitDecoderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBitDecoderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP * \fBbitmap\fP"
.br
.ti -1c
.RI "\fBTT_SBit_Metrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_Bool \fBmetrics_loaded\fP"
.br
.ti -1c
.RI "FT_Bool \fBbitmap_allocated\fP"
.br
.ti -1c
.RI "FT_Byte \fBbit_depth\fP"
.br
.ti -1c
.RI "FT_ULong \fBebdt_start\fP"
.br
.ti -1c
.RI "FT_ULong \fBebdt_size\fP"
.br
.ti -1c
.RI "FT_ULong \fBstrike_index_array\fP"
.br
.ti -1c
.RI "FT_ULong \fBstrike_index_count\fP"
.br
.ti -1c
.RI "FT_Byte * \fBeblc_base\fP"
.br
.ti -1c
.RI "FT_Byte * \fBeblc_limit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 328 of file ttsbit\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
