.TH "TT_SBit_ComponentRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_ComponentRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBglyph_code\fP"
.br
.ti -1c
.RI "FT_Char \fBx_offset\fP"
.br
.ti -1c
.RI "FT_Char \fBy_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 677 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
