.TH "TT_SBit_RangeRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_RangeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBfirst_glyph\fP"
.br
.ti -1c
.RI "FT_UShort \fBlast_glyph\fP"
.br
.ti -1c
.RI "FT_UShort \fBindex_format\fP"
.br
.ti -1c
.RI "FT_UShort \fBimage_format\fP"
.br
.ti -1c
.RI "FT_ULong \fBimage_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBimage_size\fP"
.br
.ti -1c
.RI "\fBTT_SBit_MetricsRec\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_ULong \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_ULong * \fBglyph_offsets\fP"
.br
.ti -1c
.RI "FT_UShort * \fBglyph_codes\fP"
.br
.ti -1c
.RI "FT_ULong \fBtable_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 577 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
