.TH "TT_SBit_MetricsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_MetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBheight\fP"
.br
.ti -1c
.RI "FT_UShort \fBwidth\fP"
.br
.ti -1c
.RI "FT_Short \fBhoriBearingX\fP"
.br
.ti -1c
.RI "FT_Short \fBhoriBearingY\fP"
.br
.ti -1c
.RI "FT_UShort \fBhoriAdvance\fP"
.br
.ti -1c
.RI "FT_Short \fBvertBearingX\fP"
.br
.ti -1c
.RI "FT_Short \fBvertBearingY\fP"
.br
.ti -1c
.RI "FT_UShort \fBvertAdvance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 423 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
