.TH "tt_sfnt_id_rec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tt_sfnt_id_rec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBCheckSum\fP"
.br
.ti -1c
.RI "FT_ULong \fBLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file ttobjs\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
