.TH "TT_SBit_LineMetricsRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_LineMetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Char \fBascender\fP"
.br
.ti -1c
.RI "FT_Char \fBdescender\fP"
.br
.ti -1c
.RI "FT_Byte \fBmax_width\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_slope_numerator\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_slope_denominator\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_offset\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_origin_SB\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_advance_SB\fP"
.br
.ti -1c
.RI "FT_Char \fBmax_before_BL\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_after_BL\fP"
.br
.ti -1c
.RI "FT_Char \fBpads\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 523 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
