.TH "TT_Transform_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Transform_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBxx\fP"
.br
.ti -1c
.RI "FT_Fixed \fBxy\fP"
.br
.ti -1c
.RI "FT_Fixed \fByx\fP"
.br
.ti -1c
.RI "FT_Fixed \fByy\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBox\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBoy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 180 of file ttobjs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
