.TH "TT_ValidatorRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_ValidatorRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_ValidatorRec\fP \fBvalidator\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file ttcmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
