.TH "Tuning" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuning
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBgetnotefreq\fP (int note, int keyshift)"
.br
.ti -1c
.RI "int \fBgetoctavesize\fP ()"
.br
.ti -1c
.RI "bool \fBloadscl\fP (const QString &filename)"
.br
.ti -1c
.RI "bool \fBloadkbm\fP (const QString &filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBinvertupdown\fP"
.br
.ti -1c
.RI "int \fBinvertupdowncenter\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "unsigned char \fBaNote\fP"
.br
.ti -1c
.RI "float \fBaFreq\fP"
.br
.ti -1c
.RI "int \fBscaleshift\fP"
.br
.ti -1c
.RI "unsigned char \fBfirstkey\fP"
.br
.ti -1c
.RI "unsigned char \fBlastkey\fP"
.br
.ti -1c
.RI "unsigned char \fBmiddlenote\fP"
.br
.ti -1c
.RI "unsigned char \fBmapsize\fP"
.br
.ti -1c
.RI "bool \fBmappingenabled\fP"
.br
.ti -1c
.RI "short int \fBmapping\fP [128]"
.br
.ti -1c
.RI "unsigned char \fBglobalfinedetune\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBcomment\fP"
.br
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "float \fBtuning\fP"
.br
.ti -1c
.RI "unsigned int \fBx1\fP"
.br
.ti -1c
.RI "unsigned int \fBx2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file tuning\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
