.TH "Type1CEexecBuf" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type1CEexecBuf
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FoFiOutputFunc \fBoutputFunc\fP"
.br
.ti -1c
.RI "void * \fBoutputStream\fP"
.br
.ti -1c
.RI "GBool \fBascii\fP"
.br
.ti -1c
.RI "Gushort \fBr1\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file FoFiType1C\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
