.TH "Type1CPrivateDict" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type1CPrivateDict
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBfontMatrix\fP [6]"
.br
.ti -1c
.RI "GBool \fBhasFontMatrix\fP"
.br
.ti -1c
.RI "int \fBblueValues\fP [type1CMaxBlueValues]"
.br
.ti -1c
.RI "int \fBnBlueValues\fP"
.br
.ti -1c
.RI "int \fBotherBlues\fP [type1CMaxOtherBlues]"
.br
.ti -1c
.RI "int \fBnOtherBlues\fP"
.br
.ti -1c
.RI "int \fBfamilyBlues\fP [type1CMaxBlueValues]"
.br
.ti -1c
.RI "int \fBnFamilyBlues\fP"
.br
.ti -1c
.RI "int \fBfamilyOtherBlues\fP [type1CMaxOtherBlues]"
.br
.ti -1c
.RI "int \fBnFamilyOtherBlues\fP"
.br
.ti -1c
.RI "double \fBblueScale\fP"
.br
.ti -1c
.RI "int \fBblueShift\fP"
.br
.ti -1c
.RI "int \fBblueFuzz\fP"
.br
.ti -1c
.RI "double \fBstdHW\fP"
.br
.ti -1c
.RI "GBool \fBhasStdHW\fP"
.br
.ti -1c
.RI "double \fBstdVW\fP"
.br
.ti -1c
.RI "GBool \fBhasStdVW\fP"
.br
.ti -1c
.RI "double \fBstemSnapH\fP [type1CMaxStemSnap]"
.br
.ti -1c
.RI "int \fBnStemSnapH\fP"
.br
.ti -1c
.RI "double \fBstemSnapV\fP [type1CMaxStemSnap]"
.br
.ti -1c
.RI "int \fBnStemSnapV\fP"
.br
.ti -1c
.RI "GBool \fBforceBold\fP"
.br
.ti -1c
.RI "GBool \fBhasForceBold\fP"
.br
.ti -1c
.RI "double \fBforceBoldThreshold\fP"
.br
.ti -1c
.RI "int \fBlanguageGroup\fP"
.br
.ti -1c
.RI "double \fBexpansionFactor\fP"
.br
.ti -1c
.RI "int \fBinitialRandomSeed\fP"
.br
.ti -1c
.RI "int \fBsubrsOffset\fP"
.br
.ti -1c
.RI "double \fBdefaultWidthX\fP"
.br
.ti -1c
.RI "GBool \fBdefaultWidthXFP\fP"
.br
.ti -1c
.RI "double \fBnominalWidthX\fP"
.br
.ti -1c
.RI "GBool \fBnominalWidthXFP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file FoFiType1C\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
