.TH "Type1CTopDict" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type1CTopDict
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfirstOp\fP"
.br
.ti -1c
.RI "int \fBversionSID\fP"
.br
.ti -1c
.RI "int \fBnoticeSID\fP"
.br
.ti -1c
.RI "int \fBcopyrightSID\fP"
.br
.ti -1c
.RI "int \fBfullNameSID\fP"
.br
.ti -1c
.RI "int \fBfamilyNameSID\fP"
.br
.ti -1c
.RI "int \fBweightSID\fP"
.br
.ti -1c
.RI "int \fBisFixedPitch\fP"
.br
.ti -1c
.RI "double \fBitalicAngle\fP"
.br
.ti -1c
.RI "double \fBunderlinePosition\fP"
.br
.ti -1c
.RI "double \fBunderlineThickness\fP"
.br
.ti -1c
.RI "int \fBpaintType\fP"
.br
.ti -1c
.RI "int \fBcharstringType\fP"
.br
.ti -1c
.RI "double \fBfontMatrix\fP [6]"
.br
.ti -1c
.RI "GBool \fBhasFontMatrix\fP"
.br
.ti -1c
.RI "int \fBuniqueID\fP"
.br
.ti -1c
.RI "double \fBfontBBox\fP [4]"
.br
.ti -1c
.RI "double \fBstrokeWidth\fP"
.br
.ti -1c
.RI "int \fBcharsetOffset\fP"
.br
.ti -1c
.RI "int \fBencodingOffset\fP"
.br
.ti -1c
.RI "int \fBcharStringsOffset\fP"
.br
.ti -1c
.RI "int \fBprivateSize\fP"
.br
.ti -1c
.RI "int \fBprivateOffset\fP"
.br
.ti -1c
.RI "int \fBregistrySID\fP"
.br
.ti -1c
.RI "int \fBorderingSID\fP"
.br
.ti -1c
.RI "int \fBsupplement\fP"
.br
.ti -1c
.RI "int \fBfdArrayOffset\fP"
.br
.ti -1c
.RI "int \fBfdSelectOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file FoFiType1C\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
