.TH "Ui::ArticulationProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ArticulationProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ArticulationProperties\fP\&.
.PP
Inherited by \fBMs::ArticulationProperties\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 161 of file ui_articulation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
