.TH "Ui::AlignSelect" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::AlignSelect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_AlignSelect\fP\&.
.PP
Inherited by \fBMs::AlignSelect\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 167 of file ui_align_select\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
