.TH "Ui::BendDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::BendDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_BendDialog\fP\&.
.PP
Inherited by \fBMs::BendProperties\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 155 of file ui_bend\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
