.TH "Ui::ChordStyleEditor" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ChordStyleEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ChordStyleEditor\fP\&.
.PP
Inherited by \fBMs::ChordStyleEditor\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 153 of file ui_harmonyedit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
