.TH "Ui::EditStringDataBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditStringDataBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditStringDataBase\fP\&.
.PP
Inherited by \fBMs::EditStringData\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 173 of file ui_editstringdata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
