.TH "Ui::EditRaster" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditRaster
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditRaster\fP\&.
.PP
Inherited by \fBMs::EditRaster\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 140 of file ui_editraster\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
