.TH "Ui::EditPitchBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditPitchBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditPitchBase\fP\&.
.PP
Inherited by \fBMs::EditPitch\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 852 of file ui_editpitch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
