.TH "Ui::EditDrumsetBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditDrumsetBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditDrumsetBase\fP\&.
.PP
Inherited by \fBMs::EditDrumset\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 289 of file ui_editdrumset\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
