.TH "Ui::ExcerptsDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ExcerptsDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ExcerptsDialog\fP\&.
.PP
Inherited by \fBMs::ExcerptsDialog\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 326 of file ui_excerptsdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
