.TH "Ui::EditInstrumentBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditInstrumentBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditInstrumentBase\fP\&.
.PP
Inherited by \fBMs::EditInstrument\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 224 of file ui_editinstrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
