.TH "Ui::EditStyleBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditStyleBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditStyleBase\fP\&.
.PP
Inherited by \fBMs::EditStyle\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7448 of file ui_editstyle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
