.TH "Ui::EditStaffBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditStaffBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_EditStaffBase\fP\&.
.PP
Inherited by \fBMs::EditStaff\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 738 of file ui_editstaff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
