.TH "Ui::FretDiagramProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::FretDiagramProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_FretDiagramProperties\fP\&.
.PP
Inherited by \fBMs::FretDiagramProperties\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 128 of file ui_fretdprops\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
