.TH "Ui::FluidGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::FluidGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_FluidGui\fP\&.
.PP
Inherited by \fBFluidGui\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 135 of file ui_fluid_gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
