.TH "Ui::InspectorSegment" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorSegment\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 135 of file ui_inspector_segment\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
