.TH "Ui::InspectorOttava" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorOttava
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorOttava\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 206 of file ui_inspector_ottava\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
