.TH "Ui::InspectorTuplet" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorTuplet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorTuplet\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 215 of file ui_inspector_tuplet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
