.TH "Ui::InspectorStaffText" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorStaffText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorStaffText\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 163 of file ui_inspector_stafftext\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
