.TH "Ui::InspectorArticulation" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorArticulation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorArticulation\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 276 of file ui_inspector_articulation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
