.TH "Ui::InspectorElement" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorElement\fP\&.
.PP
Inherited by \fBMs::UiInspectorElement\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 259 of file ui_inspector_element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
