.TH "Ui::InspectorBreak" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::InspectorBreak
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_InspectorBreak\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 86 of file ui_inspector_break\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
