.TH "Ui::LayerManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::LayerManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_LayerManager\fP\&.
.PP
Inherited by \fBMs::LayerManager\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 267 of file ui_layer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
