.TH "Ui::MeasuresDialogBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MeasuresDialogBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_MeasuresDialogBase\fP\&.
.PP
Inherited by \fBMs::MeasuresDialog\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 132 of file ui_measuresdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
