.TH "Ui::MediaDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MediaDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_MediaDialog\fP\&.
.PP
Inherited by \fBMs::MediaDialog\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 207 of file ui_mediadialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
