.TH "Ui::MeasurePropertiesBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MeasurePropertiesBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_MeasurePropertiesBase\fP\&.
.PP
Inherited by \fBMs::MeasureProperties\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 416 of file ui_measureproperties\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
