.TH "Ui::NewWizard" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::NewWizard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_NewWizard\fP\&.
.PP
Inherited by \fBMs::TitleWizard\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 151 of file ui_newwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
