.TH "Ui::PluginManager" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::PluginManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_PluginManager\fP\&.
.PP
Inherited by \fBMs::PluginManager\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 199 of file ui_pluginManager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
