.TH "Ui::PlayPanelBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::PlayPanelBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_PlayPanelBase\fP\&.
.PP
Inherited by \fBMs::PlayPanel\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 407 of file ui_playpanel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
