.TH "Ui::PaletteCellProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::PaletteCellProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_PaletteCellProperties\fP\&.
.PP
Inherited by \fBMs::PaletteCellProperties\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 160 of file ui_cellproperties\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
