.TH "Ui::SplitStaff" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SplitStaff
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SplitStaff\fP\&.
.PP
Inherited by \fBMs::SplitStaff\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 120 of file ui_splitstaff\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
