.TH "Ui::ShortcutCaptureDialogBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ShortcutCaptureDialogBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ShortcutCaptureDialogBase\fP\&.
.PP
Inherited by \fBMs::ShortcutCaptureDialog\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 170 of file ui_shortcutcapturedialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
