.TH "Ui::SectionBreakProperties" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SectionBreakProperties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SectionBreakProperties\fP\&.
.PP
Inherited by \fBMs::SectionBreakProperties\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 116 of file ui_sectionbreak\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
