.TH "Ui::SizeSelect" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SizeSelect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SizeSelect\fP\&.
.PP
Inherited by \fBMs::SizeSelect\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 92 of file ui_size_select\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
