.TH "Ui::Startcenter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::Startcenter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_Startcenter\fP\&.
.PP
Inherited by \fBMs::Startcenter\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 105 of file ui_startcenter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
