.TH "Ui::SelectInstrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SelectInstrument
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SelectInstrument\fP\&.
.PP
Inherited by \fBMs::SelectInstrument\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 130 of file ui_selectinstr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
