.TH "Ui::SelectDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SelectDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SelectDialog\fP\&.
.PP
Inherited by \fBMs::SelectDialog\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 194 of file ui_selectdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
