.TH "Ui::SymbolDialogBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SymbolDialogBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SymbolDialogBase\fP\&.
.PP
Inherited by \fBMs::SymbolDialog\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 126 of file ui_symboldialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
