.TH "Ui::ScoreBrowser" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ScoreBrowser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ScoreBrowser\fP\&.
.PP
Inherited by \fBMs::ScoreBrowser\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 89 of file ui_scoreBrowser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
