.TH "Ui::TremoloBarDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::TremoloBarDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_TremoloBarDialog\fP\&.
.PP
Inherited by \fBMs::TremoloBarProperties\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 171 of file ui_tremolobar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
