.TH "Ui::TextPaletteBase" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::TextPaletteBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_TextPaletteBase\fP\&.
.PP
Inherited by \fBMs::TextPalette\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 58 of file ui_textpalette\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
