.TH "Ui::TimesigWizard" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::TimesigWizard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_TimesigWizard\fP\&.
.PP
Inherited by \fBMs::TimesigWizard\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 301 of file ui_timesigwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
