.TH "Ui::UploadScoreDialog" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::UploadScoreDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_UploadScoreDialog\fP\&.
.PP
Inherited by \fBMs::UploadScoreDialog\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 361 of file ui_uploadscoredialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
