.TH "Ui::ZerberusGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ZerberusGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_ZerberusGui\fP\&.
.PP
Inherited by \fBZerberusGui\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 91 of file ui_zerberus_gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
