.TH "v3_ext_ctx" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v3_ext_ctx
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBissuer_cert\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBsubject_cert\fP"
.br
.ti -1c
.RI "\fBX509_REQ\fP * \fBsubject_req\fP"
.br
.ti -1c
.RI "\fBX509_CRL\fP * \fBcrl\fP"
.br
.ti -1c
.RI "\fBX509V3_CONF_METHOD\fP * \fBdb_meth\fP"
.br
.ti -1c
.RI "void * \fBdb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
