.TH "v3_ext_method" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v3_ext_method
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBext_nid\fP"
.br
.ti -1c
.RI "int \fBext_flags\fP"
.br
.ti -1c
.RI "\fBASN1_ITEM_EXP\fP * \fBit\fP"
.br
.ti -1c
.RI "X509V3_EXT_NEW \fBext_new\fP"
.br
.ti -1c
.RI "X509V3_EXT_FREE \fBext_free\fP"
.br
.ti -1c
.RI "X509V3_EXT_D2I \fBd2i\fP"
.br
.ti -1c
.RI "X509V3_EXT_I2D \fBi2d\fP"
.br
.ti -1c
.RI "X509V3_EXT_I2S \fBi2s\fP"
.br
.ti -1c
.RI "X509V3_EXT_S2I \fBs2i\fP"
.br
.ti -1c
.RI "X509V3_EXT_I2V \fBi2v\fP"
.br
.ti -1c
.RI "X509V3_EXT_V2I \fBv2i\fP"
.br
.ti -1c
.RI "X509V3_EXT_I2R \fBi2r\fP"
.br
.ti -1c
.RI "X509V3_EXT_R2I \fBr2i\fP"
.br
.ti -1c
.RI "void * \fBusr_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
