.TH "libmscore/velo.cpp" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/velo.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'velo\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of class VeloList\&. 
.PP
Definition in file \fBvelo\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
