.TH "libmscore/velo.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmscore/velo.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMs::VeloEvent\fP"
.br
.ti -1c
.RI "class \fBMs::VeloList\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMs\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMs::VeloType\fP : char { \fBFIX\fP, \fBRAMP\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of classes VeloList\&. 
.PP
Definition in file \fBvelo\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
