.TH "ViewerPreferences" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewerPreferences
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBNonFullScreenPageMode\fP { \fBnfpmUseNone\fP, \fBnfpmUseOutlines\fP, \fBnfpmUseThumbs\fP, \fBnfpmUseOC\fP }"
.br
.ti -1c
.RI "enum \fBDirection\fP { \fBdirectionL2R\fP, \fBdirectionR2L\fP }"
.br
.ti -1c
.RI "enum \fBPrintScaling\fP { \fBprintScalingNone\fP, \fBprintScalingAppDefault\fP }"
.br
.ti -1c
.RI "enum \fBDuplex\fP { \fBduplexNone\fP, \fBduplexSimplex\fP, \fBduplexDuplexFlipShortEdge\fP, \fBduplexDuplexFlipLongEdge\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewerPreferences\fP (\fBDict\fP *prefDict)"
.br
.ti -1c
.RI "GBool \fBgetHideToolbar\fP () const"
.br
.ti -1c
.RI "GBool \fBgetHideMenubar\fP () const"
.br
.ti -1c
.RI "GBool \fBgetHideWindowUI\fP () const"
.br
.ti -1c
.RI "GBool \fBgetFitWindow\fP () const"
.br
.ti -1c
.RI "GBool \fBgetCenterWindow\fP () const"
.br
.ti -1c
.RI "GBool \fBgetDisplayDocTitle\fP () const"
.br
.ti -1c
.RI "NonFullScreenPageMode \fBgetNonFullScreenPageMode\fP () const"
.br
.ti -1c
.RI "Direction \fBgetDirection\fP () const"
.br
.ti -1c
.RI "PrintScaling \fBgetPrintScaling\fP () const"
.br
.ti -1c
.RI "Duplex \fBgetDuplex\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ViewerPreferences\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
