.TH "Voice" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Voice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVoice\fP (\fBZerberus\fP *)"
.br
.ti -1c
.RI "\fBVoice\fP * \fBnext\fP () const"
.br
.ti -1c
.RI "void \fBsetNext\fP (\fBVoice\fP *v)"
.br
.ti -1c
.RI "void \fBstart\fP (\fBChannel\fP *channel, int key, int velo, const \fBZone\fP *, double durSinceNoteOn)"
.br
.ti -1c
.RI "void \fBupdateEnvelopes\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP (int frames, float *)"
.br
.ti -1c
.RI "void \fBupdateLoop\fP ()"
.br
.ti -1c
.RI "short \fBgetData\fP (int pos)"
.br
.ti -1c
.RI "\fBChannel\fP * \fBchannel\fP () const"
.br
.ti -1c
.RI "int \fBkey\fP () const"
.br
.ti -1c
.RI "int \fBvelocity\fP () const"
.br
.ti -1c
.RI "bool \fBisPlaying\fP () const"
.br
.ti -1c
.RI "bool \fBisSustained\fP () const"
.br
.ti -1c
.RI "bool \fBisOff\fP () const"
.br
.ti -1c
.RI "bool \fBisStopped\fP () const"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP (float time)"
.br
.ti -1c
.RI "void \fBsustained\fP ()"
.br
.ti -1c
.RI "void \fBoff\fP ()"
.br
.ti -1c
.RI "const char * \fBstate\fP () const"
.br
.ti -1c
.RI "LoopMode \fBloopMode\fP () const"
.br
.ti -1c
.RI "int \fBgetSamplesSinceStart\fP ()"
.br
.ti -1c
.RI "float \fBgetGain\fP ()"
.br
.ti -1c
.RI "OffMode \fBoffMode\fP () const"
.br
.ti -1c
.RI "int \fBoffBy\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file voice\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
