.TH "WidgetStateData" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetStateData \- handle widget state (hover/focus/enable) changes  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <widgetstatedata\&.h>\fP
.PP
Inherits \fBGenericData\fP\&.
.PP
Inherited by \fBEnableData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWidgetStateData\fP (QObject *parent, QWidget *target, int duration, bool state=false)"
.br
.RI "constructor "
.ti -1c
.RI "virtual \fB~WidgetStateData\fP (void)"
.br
.RI "destructor "
.ti -1c
.RI "virtual bool \fBupdateState\fP (bool value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
handle widget state (hover/focus/enable) changes 
.PP
Definition at line 34 of file widgetstatedata\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool WidgetStateData::updateState (bool value)\fC [virtual]\fP"
returns true if hover has Changed and starts timer accordingly 
.PP
Definition at line 31 of file widgetstatedata\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
