.TH "WinNameInfoRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinNameInfoRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBoffset\fP"
.br
.ti -1c
.RI "FT_UShort \fBlength\fP"
.br
.ti -1c
.RI "FT_UShort \fBflags\fP"
.br
.ti -1c
.RI "FT_UShort \fBid\fP"
.br
.ti -1c
.RI "FT_UShort \fBhandle\fP"
.br
.ti -1c
.RI "FT_UShort \fBusage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file winfnt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
