.TH "WinPE32_SectionRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinPE32_SectionRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBname\fP [8]"
.br
.ti -1c
.RI "FT_ULong \fBvirtual_address\fP"
.br
.ti -1c
.RI "FT_ULong \fBsize_of_raw_data\fP"
.br
.ti -1c
.RI "FT_ULong \fBpointer_to_raw_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file winfnt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
