.TH "WinPE_RsrcDirRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinPE_RsrcDirRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBcharacteristics\fP"
.br
.ti -1c
.RI "FT_ULong \fBtime_date_stamp\fP"
.br
.ti -1c
.RI "FT_UShort \fBmajor_version\fP"
.br
.ti -1c
.RI "FT_UShort \fBminor_version\fP"
.br
.ti -1c
.RI "FT_UShort \fBnumber_of_named_entries\fP"
.br
.ti -1c
.RI "FT_UShort \fBnumber_of_id_entries\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file winfnt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
