.TH "WOFF_HeaderRec_" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WOFF_HeaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBsignature\fP"
.br
.ti -1c
.RI "FT_ULong \fBflavor\fP"
.br
.ti -1c
.RI "FT_ULong \fBlength\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_tables\fP"
.br
.ti -1c
.RI "FT_UShort \fBreserved\fP"
.br
.ti -1c
.RI "FT_ULong \fBtotalSfntSize\fP"
.br
.ti -1c
.RI "FT_UShort \fBmajorVersion\fP"
.br
.ti -1c
.RI "FT_UShort \fBminorVersion\fP"
.br
.ti -1c
.RI "FT_ULong \fBmetaOffset\fP"
.br
.ti -1c
.RI "FT_ULong \fBmetaLength\fP"
.br
.ti -1c
.RI "FT_ULong \fBmetaOrigLength\fP"
.br
.ti -1c
.RI "FT_ULong \fBprivOffset\fP"
.br
.ti -1c
.RI "FT_ULong \fBprivLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 153 of file tttypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
