.TH "bww2mxml/writer.h" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bww2mxml/writer.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QString>\fP
.br
\fC#include 'symbols\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBww::MeasureBeginFlags\fP"
.br
.ti -1c
.RI "struct \fBBww::MeasureEndFlags\fP"
.br
.ti -1c
.RI "class \fBBww::Writer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBww\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBeamType\fP { \fBBM_NONE\fP, \fBBM_BEGIN\fP, \fBBM_CONTINUE\fP, \fBBM_END\fP, \fBBM_FORWARD_HOOK\fP, \fBBM_BACKWARD_HOOK\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of class Writer 
.PP
Definition in file \fBwriter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
