.TH "X509_crl_info_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_crl_info_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_REVOKED\fP) *revoked"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP) *extensions"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBsig_alg\fP"
.br
.ti -1c
.RI "\fBX509_NAME\fP * \fBissuer\fP"
.br
.ti -1c
.RI "\fBASN1_TIME\fP * \fBlastUpdate\fP"
.br
.ti -1c
.RI "\fBASN1_TIME\fP * \fBnextUpdate\fP"
.br
.ti -1c
.RI "\fBASN1_ENCODING\fP \fBenc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 449 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
