.TH "x509_cert_aux_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_cert_aux_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBASN1_OBJECT\fP) *trust"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBASN1_OBJECT\fP) *reject"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ALGOR\fP) *other"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBASN1_UTF8STRING\fP * \fBalias\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBkeyid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 270 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
