.TH "x509_trust_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_trust_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtrust\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int(* \fBcheck_trust\fP )(struct \fBx509_trust_st\fP *, \fBX509\fP *, int)"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBarg1\fP"
.br
.ti -1c
.RI "void * \fBarg2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 316 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
