.TH "X509_name_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_name_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_NAME_ENTRY\fP) *entries"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmodified\fP"
.br
.ti -1c
.RI "\fBBUF_MEM\fP * \fBbytes\fP"
.br
.ti -1c
.RI "unsigned char * \fBcanon_enc\fP"
.br
.ti -1c
.RI "int \fBcanon_enclen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 185 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
