.TH "X509V3_CONF_METHOD_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509V3_CONF_METHOD_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP) *(*get_section)(void *db"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char *(* \fBget_string\fP )(void *db, char *section, char *value)"
.br
.ti -1c
.RI "char * \fBsection\fP"
.br
.ti -1c
.RI "void(* \fBfree_string\fP )(void *db, char *string)"
.br
.ti -1c
.RI "void(* \fBfree_section\fP )(void *db, STACK_OF(\fBCONF_VALUE\fP) *section)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
