.TH "x509_object_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_object_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   \fBX509\fP * \fBx509\fP"
.br
.ti -1c
.RI "   \fBX509_CRL\fP * \fBcrl\fP"
.br
.ti -1c
.RI "   \fBEVP_PKEY\fP * \fBpkey\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file x509_vfy\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
