.TH "X509_crl_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_crl_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (GENERAL_NAMES) *issuers"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBX509_CRL_INFO\fP * \fBcrl\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBsig_alg\fP"
.br
.ti -1c
.RI "\fBASN1_BIT_STRING\fP * \fBsignature\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBAUTHORITY_KEYID\fP * \fBakid\fP"
.br
.ti -1c
.RI "\fBISSUING_DIST_POINT\fP * \fBidp\fP"
.br
.ti -1c
.RI "int \fBidp_flags\fP"
.br
.ti -1c
.RI "int \fBidp_reasons\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBcrl_number\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBbase_crl_number\fP"
.br
.ti -1c
.RI "unsigned char \fBsha1_hash\fP [SHA_DIGEST_LENGTH]"
.br
.ti -1c
.RI "const X509_CRL_METHOD * \fBmeth\fP"
.br
.ti -1c
.RI "void * \fBmeth_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 461 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
