.TH "x509_st" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_st
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBDIST_POINT\fP) *crldp"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBGENERAL_NAME\fP) *altname"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBIPAddressFamily\fP) *rfc3779_addr"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBX509_CINF\fP * \fBcert_info\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBsig_alg\fP"
.br
.ti -1c
.RI "\fBASN1_BIT_STRING\fP * \fBsignature\fP"
.br
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.ti -1c
.RI "long \fBex_pathlen\fP"
.br
.ti -1c
.RI "long \fBex_pcpathlen\fP"
.br
.ti -1c
.RI "unsigned long \fBex_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBex_kusage\fP"
.br
.ti -1c
.RI "unsigned long \fBex_xkusage\fP"
.br
.ti -1c
.RI "unsigned long \fBex_nscert\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBskid\fP"
.br
.ti -1c
.RI "\fBAUTHORITY_KEYID\fP * \fBakid\fP"
.br
.ti -1c
.RI "X509_POLICY_CACHE * \fBpolicy_cache\fP"
.br
.ti -1c
.RI "\fBNAME_CONSTRAINTS\fP * \fBnc\fP"
.br
.ti -1c
.RI "struct \fBASIdentifiers_st\fP * \fBrfc3779_asid\fP"
.br
.ti -1c
.RI "unsigned char \fBsha1_hash\fP [SHA_DIGEST_LENGTH]"
.br
.ti -1c
.RI "\fBX509_CERT_AUX\fP * \fBaux\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 279 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
