.TH "XmlReader" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits QXmlStreamReader\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlReader\fP (QFile *)"
.br
.ti -1c
.RI "\fBXmlReader\fP (const QByteArray &d)"
.br
.ti -1c
.RI "\fBXmlReader\fP (QIODevice *d)"
.br
.ti -1c
.RI "\fBXmlReader\fP (const QString &d)"
.br
.ti -1c
.RI "void \fBunknown\fP () const"
.br
.ti -1c
.RI "void \fBerror\fP (const QString &s) const"
.br
.ti -1c
.RI "void \fBerror\fP (int, int)"
.br
.ti -1c
.RI "QString \fBattribute\fP (const char *s) const"
.br
.ti -1c
.RI "QString \fBattribute\fP (const char *s, const QString &) const"
.br
.ti -1c
.RI "int \fBintAttribute\fP (const char *s, int _default=0, int base=10) const"
.br
.ti -1c
.RI "double \fBdoubleAttribute\fP (const char *s) const"
.br
.ti -1c
.RI "double \fBdoubleAttribute\fP (const char *s, double _default) const"
.br
.ti -1c
.RI "bool \fBhasAttribute\fP (const char *s) const"
.br
.ti -1c
.RI "int \fBreadInt\fP ()"
.br
.ti -1c
.RI "int \fBreadInt\fP (bool *ok)"
.br
.ti -1c
.RI "double \fBreadDouble\fP ()"
.br
.ti -1c
.RI "QPointF \fBreadPoint\fP ()"
.br
.ti -1c
.RI "QSizeF \fBreadSize\fP ()"
.br
.ti -1c
.RI "QRectF \fBreadRect\fP ()"
.br
.ti -1c
.RI "void \fBsetDocName\fP (const QString &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file xmlreader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
