.TH "XmlStreamReaderPrivate::Entity" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamReaderPrivate::Entity
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntity\fP (const QString &str=QString())"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEntity\fP \fBcreateLiteral\fP (const QString &entity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBvalue\fP"
.br
.ti -1c
.RI "uint \fBexternal\fP: 1"
.br
.ti -1c
.RI "uint \fBunparsed\fP: 1"
.br
.ti -1c
.RI "uint \fBliteral\fP: 1"
.br
.ti -1c
.RI "uint \fBhasBeenParsed\fP: 1"
.br
.ti -1c
.RI "uint \fBisCurrentlyReferenced\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 757 of file xmlstream_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
