.TH "XmlStreamEntityResolver" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamEntityResolver \- The \fBXmlStreamEntityResolver\fP class provides an entity resolver for a \fBXmlStreamReader\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~XmlStreamEntityResolver\fP ()"
.br
.ti -1c
.RI "virtual QString \fBresolveEntity\fP (const QString &publicId, const QString &systemId)"
.br
.ti -1c
.RI "virtual QString \fBresolveUndeclaredEntity\fP (const QString &name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXmlStreamEntityResolver\fP class provides an entity resolver for a \fBXmlStreamReader\fP\&. 

QtCore  
.PP
\fBSince:\fP
.RS 4
4\&.4 
.RE
.PP

.PP
Definition at line 219 of file xmlstream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlStreamEntityResolver::~XmlStreamEntityResolver ()\fC [virtual]\fP"
Destroys the entity resolver\&. 
.PP
Definition at line 175 of file xmlstream\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString XmlStreamEntityResolver::resolveUndeclaredEntity (const QString & name)\fC [virtual]\fP"
Resolves the undeclared entity \fIname\fP and returns its replacement text\&. If the entity is also unknown to the entity resolver, it returns an empty string\&.
.PP
The default implementation always returns an empty string\&. 
.PP
Definition at line 198 of file xmlstream\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
