.TH "XmlStreamReaderPrivate::DtdAttribute" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamReaderPrivate::DtdAttribute
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QStringRef \fBtagName\fP"
.br
.ti -1c
.RI "QStringRef \fBattributeQualifiedName\fP"
.br
.ti -1c
.RI "QStringRef \fBattributePrefix\fP"
.br
.ti -1c
.RI "QStringRef \fBattributeName\fP"
.br
.ti -1c
.RI "QStringRef \fBdefaultValue\fP"
.br
.ti -1c
.RI "bool \fBisCDATA\fP"
.br
.ti -1c
.RI "bool \fBisNamespaceAttribute\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 822 of file xmlstream_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
