.TH "XmlStreamNotationDeclaration" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamNotationDeclaration \- The \fBXmlStreamNotationDeclaration\fP class represents a DTD notation declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlStreamNotationDeclaration\fP ()"
.br
.ti -1c
.RI "\fB~XmlStreamNotationDeclaration\fP ()"
.br
.ti -1c
.RI "\fBXmlStreamNotationDeclaration\fP (const \fBXmlStreamNotationDeclaration\fP &)"
.br
.ti -1c
.RI "\fBXmlStreamNotationDeclaration\fP & \fBoperator=\fP (const \fBXmlStreamNotationDeclaration\fP &)"
.br
.ti -1c
.RI "QStringRef \fBname\fP () const"
.br
.ti -1c
.RI "QStringRef \fBsystemId\fP () const"
.br
.ti -1c
.RI "QStringRef \fBpublicId\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBXmlStreamNotationDeclaration\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBXmlStreamNotationDeclaration\fP &other) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBXmlStreamReaderPrivate\fP"
.br
.in -1c
.SS "Related Functions"
(Note that these are not member functions\&.) 
.in +1c
.ti -1c
.RI "\fBXmlStreamNotationDeclarations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXmlStreamNotationDeclaration\fP class represents a DTD notation declaration\&. 

QtCore 
.PP
\fBSince:\fP
.RS 4
4\&.3 
.RE
.PP
An notation declaration consists of a \fBname()\fP, a \fBsystemId()\fP, and a \fBpublicId()\fP\&. 
.PP
Definition at line 163 of file xmlstream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlStreamNotationDeclaration::XmlStreamNotationDeclaration ()"
Creates an empty notation declaration\&. 
.PP
Definition at line 2433 of file xmlstream\&.cpp\&.
.SS "XmlStreamNotationDeclaration::~XmlStreamNotationDeclaration ()"
Destructs this notation declaration\&. 
.PP
Definition at line 2458 of file xmlstream\&.cpp\&.
.SS "XmlStreamNotationDeclaration::XmlStreamNotationDeclaration (const \fBXmlStreamNotationDeclaration\fP & other)"
Creates a copy of \fIother\fP\&. 
.PP
Definition at line 2439 of file xmlstream\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QStringRef XmlStreamNotationDeclaration::name () const\fC [inline]\fP"
Returns the notation name\&. 
.PP
Definition at line 173 of file xmlstream\&.h\&.
.SS "bool XmlStreamNotationDeclaration::operator!= (const \fBXmlStreamNotationDeclaration\fP & other) const\fC [inline]\fP"
Compares this notation declaration with \fIother\fP and returns \fCtrue\fP if they are not equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 180 of file xmlstream\&.h\&.
.SS "\fBXmlStreamNotationDeclaration\fP & XmlStreamNotationDeclaration::operator= (const \fBXmlStreamNotationDeclaration\fP & other)"
Assigns \fIother\fP to this notation declaration\&. 
.PP
Definition at line 2447 of file xmlstream\&.cpp\&.
.SS "bool XmlStreamNotationDeclaration::operator== (const \fBXmlStreamNotationDeclaration\fP & other) const\fC [inline]\fP"
Compares this notation declaration with \fIother\fP and returns \fCtrue\fP if they are equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 176 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamNotationDeclaration::publicId () const\fC [inline]\fP"
Returns the public identifier\&. 
.PP
Definition at line 175 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamNotationDeclaration::systemId () const\fC [inline]\fP"
Returns the system identifier\&. 
.PP
Definition at line 174 of file xmlstream\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "XmlStreamNotationDeclarations\fC [related]\fP"
Synonym for QVector<XmlStreamNotationDeclaration>\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
