.TH "XmlStreamEntityDeclaration" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamEntityDeclaration \- The \fBXmlStreamEntityDeclaration\fP class represents a DTD entity declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlStreamEntityDeclaration\fP ()"
.br
.ti -1c
.RI "\fB~XmlStreamEntityDeclaration\fP ()"
.br
.ti -1c
.RI "\fBXmlStreamEntityDeclaration\fP (const \fBXmlStreamEntityDeclaration\fP &)"
.br
.ti -1c
.RI "\fBXmlStreamEntityDeclaration\fP & \fBoperator=\fP (const \fBXmlStreamEntityDeclaration\fP &)"
.br
.ti -1c
.RI "QStringRef \fBname\fP () const"
.br
.ti -1c
.RI "QStringRef \fBnotationName\fP () const"
.br
.ti -1c
.RI "QStringRef \fBsystemId\fP () const"
.br
.ti -1c
.RI "QStringRef \fBpublicId\fP () const"
.br
.ti -1c
.RI "QStringRef \fBvalue\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBXmlStreamEntityDeclaration\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBXmlStreamEntityDeclaration\fP &other) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBXmlStreamReaderPrivate\fP"
.br
.in -1c
.SS "Related Functions"
(Note that these are not member functions\&.) 
.in +1c
.ti -1c
.RI "\fBXmlStreamEntityDeclarations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXmlStreamEntityDeclaration\fP class represents a DTD entity declaration\&. 

QtCore 
.PP
\fBSince:\fP
.RS 4
4\&.3 
.RE
.PP
An entity declaration consists of a \fBname()\fP, a \fBnotationName()\fP, a \fBsystemId()\fP, a \fBpublicId()\fP, and a \fBvalue()\fP\&. 
.PP
Definition at line 188 of file xmlstream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlStreamEntityDeclaration::XmlStreamEntityDeclaration ()"
Creates an empty entity declaration\&. 
.PP
Definition at line 2599 of file xmlstream\&.cpp\&.
.SS "XmlStreamEntityDeclaration::~XmlStreamEntityDeclaration ()"
Destructs this entity declaration\&. 
.PP
Definition at line 2627 of file xmlstream\&.cpp\&.
.SS "XmlStreamEntityDeclaration::XmlStreamEntityDeclaration (const \fBXmlStreamEntityDeclaration\fP & other)"
Creates a copy of \fIother\fP\&. 
.PP
Definition at line 2606 of file xmlstream\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QStringRef XmlStreamEntityDeclaration::name () const\fC [inline]\fP"
Returns the entity name\&. 
.PP
Definition at line 198 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamEntityDeclaration::notationName () const\fC [inline]\fP"
Returns the notation name\&. 
.PP
Definition at line 199 of file xmlstream\&.h\&.
.SS "bool XmlStreamEntityDeclaration::operator!= (const \fBXmlStreamEntityDeclaration\fP & other) const\fC [inline]\fP"
Compares this entity declaration with \fIother\fP and returns \fCtrue\fP if they are not equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 210 of file xmlstream\&.h\&.
.SS "\fBXmlStreamEntityDeclaration\fP & XmlStreamEntityDeclaration::operator= (const \fBXmlStreamEntityDeclaration\fP & other)"
Assigns \fIother\fP to this entity declaration\&. 
.PP
Definition at line 2614 of file xmlstream\&.cpp\&.
.SS "bool XmlStreamEntityDeclaration::operator== (const \fBXmlStreamEntityDeclaration\fP & other) const\fC [inline]\fP"
Compares this entity declaration with \fIother\fP and returns \fCtrue\fP if they are equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 203 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamEntityDeclaration::publicId () const\fC [inline]\fP"
Returns the public identifier\&. 
.PP
Definition at line 201 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamEntityDeclaration::systemId () const\fC [inline]\fP"
Returns the system identifier\&. 
.PP
Definition at line 200 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamEntityDeclaration::value (void) const\fC [inline]\fP"
Returns the entity's value\&. 
.PP
Definition at line 202 of file xmlstream\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "XmlStreamEntityDeclarations\fC [related]\fP"
Synonym for QVector<XmlStreamEntityDeclaration>\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
