.TH "XmlStreamPrivateTagStack" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamPrivateTagStack
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBXmlStreamReaderPrivate\fP, and \fBXmlStreamWriterPrivate\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNamespaceDeclaration\fP"
.br
.ti -1c
.RI "struct \fBTag\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QStringRef \fBaddToStringStorage\fP (const QStringRef &s)"
.br
.ti -1c
.RI "QStringRef \fBaddToStringStorage\fP (const QString &s)"
.br
.ti -1c
.RI "\fBTag\fP & \fBtagStack_pop\fP ()"
.br
.ti -1c
.RI "\fBTag\fP & \fBtagStack_push\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBXmlStreamSimpleStack\fP< \fBNamespaceDeclaration\fP > \fBnamespaceDeclarations\fP"
.br
.ti -1c
.RI "QString \fBtagStackStringStorage\fP"
.br
.ti -1c
.RI "int \fBtagStackStringStorageSize\fP"
.br
.ti -1c
.RI "bool \fBtagsDone\fP"
.br
.ti -1c
.RI "\fBXmlStreamSimpleStack\fP< \fBTag\fP > \fBtagStack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 678 of file xmlstream_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
