.TH "XmlStreamNamespaceDeclaration" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamNamespaceDeclaration \- The \fBXmlStreamNamespaceDeclaration\fP class represents a namespace declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlStreamNamespaceDeclaration\fP ()"
.br
.ti -1c
.RI "\fBXmlStreamNamespaceDeclaration\fP (const \fBXmlStreamNamespaceDeclaration\fP &)"
.br
.ti -1c
.RI "\fBXmlStreamNamespaceDeclaration\fP (const QString &\fBprefix\fP, const QString &\fBnamespaceUri\fP)"
.br
.ti -1c
.RI "\fB~XmlStreamNamespaceDeclaration\fP ()"
.br
.ti -1c
.RI "\fBXmlStreamNamespaceDeclaration\fP & \fBoperator=\fP (const \fBXmlStreamNamespaceDeclaration\fP &)"
.br
.ti -1c
.RI "QStringRef \fBprefix\fP () const"
.br
.ti -1c
.RI "QStringRef \fBnamespaceUri\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBXmlStreamNamespaceDeclaration\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBXmlStreamNamespaceDeclaration\fP &other) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBXmlStreamReaderPrivate\fP"
.br
.in -1c
.SS "Related Functions"
(Note that these are not member functions\&.) 
.in +1c
.ti -1c
.RI "\fBXmlStreamNamespaceDeclarations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXmlStreamNamespaceDeclaration\fP class represents a namespace declaration\&. 

QtCore 
.PP
\fBSince:\fP
.RS 4
4\&.3 
.RE
.PP
An namespace declaration consists of a \fBprefix()\fP and a \fBnamespaceUri()\fP\&. 
.PP
Definition at line 139 of file xmlstream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlStreamNamespaceDeclaration::XmlStreamNamespaceDeclaration ()"
Creates an empty namespace declaration\&. 
.PP
Definition at line 2518 of file xmlstream\&.cpp\&.
.SS "XmlStreamNamespaceDeclaration::XmlStreamNamespaceDeclaration (const \fBXmlStreamNamespaceDeclaration\fP & other)"
Creates a copy of \fIother\fP\&. 
.PP
Definition at line 2536 of file xmlstream\&.cpp\&.
.SS "XmlStreamNamespaceDeclaration::XmlStreamNamespaceDeclaration (const QString & prefix, const QString & namespaceUri)"

.PP
\fBSince:\fP
.RS 4
4\&.4
.RE
.PP
Creates a namespace declaration with \fIprefix\fP and \fInamespaceUri\fP\&. 
.PP
Definition at line 2527 of file xmlstream\&.cpp\&.
.SS "XmlStreamNamespaceDeclaration::~XmlStreamNamespaceDeclaration ()"
Destructs this namespace declaration\&. 
.PP
Definition at line 2553 of file xmlstream\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QStringRef XmlStreamNamespaceDeclaration::namespaceUri () const\fC [inline]\fP"
Returns the namespaceUri\&. 
.PP
Definition at line 151 of file xmlstream\&.h\&.
.SS "bool XmlStreamNamespaceDeclaration::operator!= (const \fBXmlStreamNamespaceDeclaration\fP & other) const\fC [inline]\fP"
Compares this namespace declaration with \fIother\fP and returns \fCtrue\fP if they are not equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 155 of file xmlstream\&.h\&.
.SS "\fBXmlStreamNamespaceDeclaration\fP & XmlStreamNamespaceDeclaration::operator= (const \fBXmlStreamNamespaceDeclaration\fP & other)"
Assigns \fIother\fP to this namespace declaration\&. 
.PP
Definition at line 2544 of file xmlstream\&.cpp\&.
.SS "bool XmlStreamNamespaceDeclaration::operator== (const \fBXmlStreamNamespaceDeclaration\fP & other) const\fC [inline]\fP"
Compares this namespace declaration with \fIother\fP and returns \fCtrue\fP if they are equal; otherwise returns \fCfalse\fP\&. 
.PP
Definition at line 152 of file xmlstream\&.h\&.
.SS "QStringRef XmlStreamNamespaceDeclaration::prefix () const\fC [inline]\fP"
Returns the prefix\&. 
.PP
Definition at line 150 of file xmlstream\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "XmlStreamNamespaceDeclarations\fC [related]\fP"
Synonym for QVector<XmlStreamNamespaceDeclaration>\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
