.TH "XmlStreamStringRef" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamStringRef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlStreamStringRef\fP (const QStringRef &aString)"
.br
.ti -1c
.RI "\fBXmlStreamStringRef\fP (const QString &aString)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBoperator QStringRef\fP () const"
.br
.ti -1c
.RI "const QString * \fBstring\fP () const"
.br
.ti -1c
.RI "int \fBposition\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
QtCore 
.PP
\fBSince:\fP
.RS 4
4\&.3 
.RE
.PP

.PP
Definition at line 50 of file xmlstream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
