.TH "XmlStreamSimpleStack< T >" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlStreamSimpleStack< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreserve\fP (int extraCapacity)"
.br
.ti -1c
.RI "T & \fBpush\fP ()"
.br
.ti -1c
.RI "T & \fBrawPush\fP ()"
.br
.ti -1c
.RI "const T & \fBtop\fP () const"
.br
.ti -1c
.RI "T & \fBtop\fP ()"
.br
.ti -1c
.RI "T & \fBpop\fP ()"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int index)"
.br
.ti -1c
.RI "const T & \fBat\fP (int index) const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBresize\fP (int s)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class XmlStreamSimpleStack< T >"

.PP
Definition at line 644 of file xmlstream_p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
