.TH "XmlWriter" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTextStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlWriter\fP (QIODevice *dev)"
.br
.ti -1c
.RI "void \fBheader\fP ()"
.br
.ti -1c
.RI "void \fBstag\fP (const QString &)"
.br
.ti -1c
.RI "void \fBetag\fP ()"
.br
.ti -1c
.RI "void \fBtagE\fP (const QString &)"
.br
.ti -1c
.RI "void \fBtagE\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBntag\fP (const char *name)"
.br
.ti -1c
.RI "void \fBnetag\fP (const char *name)"
.br
.ti -1c
.RI "void \fBtag\fP (const QString &, QVariant data)"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, const char *s)"
.br
.ti -1c
.RI "void \fBtag\fP (const char *name, const QString &s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBxmlString\fP (const QString &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file xmlwriter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
