.TH "XpdfPluginVecTable" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XpdfPluginVecTable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "XpdfObject(* \fB_xpdfGetInfoDict\fP )(XpdfDoc doc)"
.br
.ti -1c
.RI "XpdfObject(* \fB_xpdfGetCatalog\fP )(XpdfDoc doc)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsBool\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsInt\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsReal\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsString\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsName\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsNull\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsArray\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsDict\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsStream\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfObjIsRef\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfBool(* \fB_xpdfBoolValue\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "int(* \fB_xpdfIntValue\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "double(* \fB_xpdfRealValue\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "int(* \fB_xpdfStringLength\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "char *(* \fB_xpdfStringValue\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "char *(* \fB_xpdfNameValue\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "int(* \fB_xpdfArrayLength\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "XpdfObject(* \fB_xpdfArrayGet\fP )(XpdfObject obj, int idx)"
.br
.ti -1c
.RI "XpdfObject(* \fB_xpdfDictGet\fP )(XpdfObject obj, char *key)"
.br
.ti -1c
.RI "void(* \fB_xpdfFreeObj\fP )(XpdfObject obj)"
.br
.ti -1c
.RI "void *(* \fB_xpdfMalloc\fP )(int size)"
.br
.ti -1c
.RI "void *(* \fB_xpdfRealloc\fP )(void *p, int size)"
.br
.ti -1c
.RI "void(* \fB_xpdfFree\fP )(void *p)"
.br
.ti -1c
.RI "void(* \fB_xpdfRegisterSecurityHandler\fP )(\fBXpdfSecurityHandler\fP *handler)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 211 of file XpdfPluginAPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
