.TH "XRefEntry" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XRefEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlag\fP { \fBUpdated\fP, \fBUnencrypted\fP, \fBDontRewrite\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GBool \fBgetFlag\fP (Flag flag)"
.br
.ti -1c
.RI "void \fBsetFlag\fP (Flag flag, GBool value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Goffset \fBoffset\fP"
.br
.ti -1c
.RI "int \fBgen\fP"
.br
.ti -1c
.RI "XRefEntryType \fBtype\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBObject\fP \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file XRef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
