.TH "z_stream_s" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
z_stream_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Bytef * \fBnext_in\fP"
.br
.ti -1c
.RI "uInt \fBavail_in\fP"
.br
.ti -1c
.RI "uLong \fBtotal_in\fP"
.br
.ti -1c
.RI "Bytef * \fBnext_out\fP"
.br
.ti -1c
.RI "uInt \fBavail_out\fP"
.br
.ti -1c
.RI "uLong \fBtotal_out\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.ti -1c
.RI "struct \fBinternal_state\fP FAR * \fBstate\fP"
.br
.ti -1c
.RI "alloc_func \fBzalloc\fP"
.br
.ti -1c
.RI "free_func \fBzfree\fP"
.br
.ti -1c
.RI "voidpf \fBopaque\fP"
.br
.ti -1c
.RI "int \fBdata_type\fP"
.br
.ti -1c
.RI "uLong \fBadler\fP"
.br
.ti -1c
.RI "uLong \fBreserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file zlib\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
