.TH "ZerberusGui" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZerberusGui
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::SynthesizerGui\fP, and \fBUi::ZerberusGui\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsynthesizerChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZerberusGui\fP (\fBMs::Synthesizer\fP *)"
.br
.ti -1c
.RI "\fBZerberus\fP * \fBzerberus\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 55 of file zerberusgui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
