.TH "Zerberus" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zerberus
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMs::Synthesizer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBprocess\fP (unsigned frames, float *, float *, float *)"
.br
.ti -1c
.RI "virtual void \fBplay\fP (const \fBMs::PlayEvent\fP &event)"
.br
.ti -1c
.RI "bool \fBloadInstrument\fP (const QString &)"
.br
.ti -1c
.RI "\fBZInstrument\fP * \fBinstrument\fP (int program) const"
.br
.ti -1c
.RI "\fBVoice\fP * \fBgetActiveVoices\fP ()"
.br
.ti -1c
.RI "\fBChannel\fP * \fBchannel\fP (int n)"
.br
.ti -1c
.RI "int \fBloadProgress\fP ()"
.br
.ti -1c
.RI "void \fBsetLoadProgress\fP (int val)"
.br
.ti -1c
.RI "bool \fBloadWasCanceled\fP ()"
.br
.ti -1c
.RI "void \fBsetLoadWasCanceled\fP (bool status)"
.br
.ti -1c
.RI "virtual void \fBsetMasterTuning\fP (double val)"
.br
.ti -1c
.RI "virtual double \fBmasterTuning\fP () const"
.br
.ti -1c
.RI "double \fBct2hz\fP (double c)"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const"
.br
.ti -1c
.RI "virtual const QList< \fBMs::MidiPatch\fP * > & \fBgetPatchInfo\fP () const"
.br
.ti -1c
.RI "virtual \fBMs::SynthesizerGroup\fP \fBstate\fP () const"
.br
.ti -1c
.RI "virtual bool \fBsetState\fP (const \fBMs::SynthesizerGroup\fP &)"
.br
.ti -1c
.RI "virtual void \fBallSoundsOff\fP (int channel)"
.br
.ti -1c
.RI "virtual void \fBallNotesOff\fP (int channel)"
.br
.ti -1c
.RI "virtual bool \fBaddSoundFont\fP (const QString &)"
.br
.ti -1c
.RI "virtual bool \fBremoveSoundFont\fP (const QString &)"
.br
.ti -1c
.RI "virtual bool \fBloadSoundFonts\fP (const QStringList &)"
.br
.ti -1c
.RI "virtual QStringList \fBsoundFonts\fP () const"
.br
.ti -1c
.RI "virtual \fBMs::SynthesizerGui\fP * \fBgui\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QFileInfoList \fBsfzFiles\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 70 of file zerberus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
