.TH "ZInstrument" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZInstrument
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZInstrument\fP (\fBZerberus\fP *)"
.br
.ti -1c
.RI "int \fBrefCount\fP () const"
.br
.ti -1c
.RI "void \fBsetRefCount\fP (int val)"
.br
.ti -1c
.RI "bool \fBload\fP (const QString &)"
.br
.ti -1c
.RI "int \fBprogram\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBpath\fP () const"
.br
.ti -1c
.RI "const std::list< \fBZone\fP * > & \fBzones\fP () const"
.br
.ti -1c
.RI "std::list< \fBZone\fP * > & \fBzones\fP ()"
.br
.ti -1c
.RI "\fBSample\fP * \fBreadSample\fP (const QString &s, \fBMQZipReader\fP *uz)"
.br
.ti -1c
.RI "void \fBaddZone\fP (\fBZone\fP *z)"
.br
.ti -1c
.RI "void \fBaddRegion\fP (\fBSfzRegion\fP &)"
.br
.ti -1c
.RI "int \fBgetSetCC\fP (int v)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static QByteArray \fBbuf\fP"
.br
.ti -1c
.RI "static int \fBidx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file instrument\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
