.TH "Zone" 3 "Mon Jun 5 2017" "MuseScore-2.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zone
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBmatch\fP (\fBChannel\fP *, int key, int velo, Trigger, double rand, int cc, int ccVal)"
.br
.ti -1c
.RI "void \fBupdateCCGain\fP (\fBChannel\fP *c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSample\fP * \fBsample\fP = 0"
.br
.ti -1c
.RI "int \fBoffset\fP = 0"
.br
.ti -1c
.RI "int \fBseq\fP = 0"
.br
.ti -1c
.RI "int \fBseqLen\fP = 0"
.br
.ti -1c
.RI "int \fBseqPos\fP = 0"
.br
.ti -1c
.RI "char \fBkeyLo\fP = 0"
.br
.ti -1c
.RI "char \fBkeyHi\fP = 127"
.br
.ti -1c
.RI "char \fBveloLo\fP = 0"
.br
.ti -1c
.RI "char \fBveloHi\fP = 127"
.br
.ti -1c
.RI "char \fBkeyBase\fP = 60"
.br
.ti -1c
.RI "int \fBtune\fP = 0"
.br
.ti -1c
.RI "double \fBpitchKeytrack\fP = 100\&.0"
.br
.ti -1c
.RI "float \fBvolume\fP = 1\&.0"
.br
.ti -1c
.RI "float \fBlVol\fP = \&.5"
.br
.ti -1c
.RI "float \fBrVol\fP = \&.5"
.br
.ti -1c
.RI "float \fBampVeltrack\fP = 100"
.br
.ti -1c
.RI "float \fBampegDelay\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegStart\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegAttack\fP = 1\&.0"
.br
.ti -1c
.RI "float \fBampegHold\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegDecay\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegSustain\fP = 1\&.0"
.br
.ti -1c
.RI "float \fBampegRelease\fP = 200\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Delay\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Attack\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Hold\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Decay\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Sustain\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBampegVel2Release\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBrtDecay\fP = 0\&.0"
.br
.ti -1c
.RI "Trigger \fBtrigger\fP = Trigger::ATTACK"
.br
.ti -1c
.RI "LoopMode \fBloopMode\fP = LoopMode::NO_LOOP"
.br
.ti -1c
.RI "OffMode \fBoffMode\fP = OffMode::FAST"
.br
.ti -1c
.RI "int \fBgroup\fP = 0"
.br
.ti -1c
.RI "int \fBoffBy\fP = 0"
.br
.ti -1c
.RI "int \fBloopStart\fP"
.br
.ti -1c
.RI "int \fBloopEnd\fP"
.br
.ti -1c
.RI "double \fBloRand\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBhiRand\fP = 1\&.0"
.br
.ti -1c
.RI "std::map< int, double > \fBgainOnCC\fP"
.br
.ti -1c
.RI "double \fBccGain\fP = 1\&.0"
.br
.ti -1c
.RI "int \fBonLocc\fP [128]"
.br
.ti -1c
.RI "int \fBonHicc\fP [128]"
.br
.ti -1c
.RI "int \fBlocc\fP [128]"
.br
.ti -1c
.RI "int \fBhicc\fP [128]"
.br
.ti -1c
.RI "bool \fBuseCC\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file zone\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MuseScore-2\&.2 from the source code\&.
